### ISSUE TITLE
Error while running the demo

### ISSUE THREAD

**Issue by stphnrdmr** [CookPete/react-player#1]
I executed all the commands as described in the README but the bundle.js won't be generated, the browser shows `GET http://localhost:3000/static/bundle.js 404 (Not Found)`. I captured the output of `npm start` in this [gist](https://gist.github.com/stphnrdmr/14944930be6e246a1116#file-react-player-errors-log). Do you have any idea what I'm doing wrong?

**Comment by stphnrdmr** [comment]
I just ran `npm i imports-loader exports-loader whatwg-fetch --save`,  that lets me create the bundle.js file. Now when I click any of the buttons for loading a video I get: `Uncaught TypeError: _players2.default.find is not a function` in `ReactPlayer.js?fd27:36`

**Comment by CookPete** [comment]
Hi @stphnrdmr,

Looks like I need to add those packages to `package.json`. Thanks for spotting that.

As for your second error, I'm using [Array.find](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find) which doesn't have great browser support yet, so I should probably polyfill that. I'm using Chrome Canary 47 when testing this thing, which is admittedly rather bleeding edge.

**Comment by CookPete** [comment]
Fixed in `0.0.4`

**Comment by stphnrdmr** [comment]
Now everything works fine! Thank you for this awesome project :smile:
