### ISSUE TITLE
Vimeo video not loading within a modal

### ISSUE THREAD

**Issue by stephenyeargin** [CookPete/react-player#100]
Howdy!

I have a use case where a video is to play in a (Bootstrap) modal when a trigger is clicked. My attempts have left me with an empty gray frame. When I inspect the generated HTML, I can see that all of my configuration is there (and that it detected the URL as a Vimeo resource).

This happens with all Vimeo links. If I provide A YouTube link, the video loads in fine.

Any thoughts as to what may be going on?

---

### On page

![screen shot 2016-08-27 at 11 46 56 am](https://cloud.githubusercontent.com/assets/80459/18028939/d512a3da-6c4f-11e6-909c-e04a8f9630f4.png)

### Generated HTML

![screen shot 2016-08-27 at 11 47 27 am](https://cloud.githubusercontent.com/assets/80459/18028948/1043387a-6c50-11e6-9183-c374bab5f68a.png)

### React debug

![screen shot 2016-08-27 at 11 46 37 am](https://cloud.githubusercontent.com/assets/80459/18028941/da56e68a-6c4f-11e6-91d5-75ed67a330ed.png)

### On page

![screen shot 2016-08-27 at 11 57 25 am](https://cloud.githubusercontent.com/assets/80459/18028959/347c2b48-6c50-11e6-9288-b1efb88b9cfc.png)

### Generated HTML

![screen shot 2016-08-27 at 11 57 45 am](https://cloud.githubusercontent.com/assets/80459/18028961/39e5aee2-6c50-11e6-8560-d5f3348dedff.png)

### React debug

![screen shot 2016-08-27 at 11 58 45 am](https://cloud.githubusercontent.com/assets/80459/18028964/4a343854-6c50-11e6-8a50-d98b5fbd1a13.png)

**Comment by CookPete** [comment]
Hey @stephenyeargin, do you have an example repo of this happening?

**Comment by stephenyeargin** [comment]
>do you have an example repo of this happening?

It's in a [proprietary product](https://auditor.raventools.com), so I would not be able to share the exact source code around all of it. That said, I can give a few things that are happening:

- React components are loaded using `require.js`
- The modal is a re-styled version of Bootstrap's [default](http://getbootstrap.com/javascript/#modals)
- Here is a [gist](https://gist.github.com/stephenyeargin/b6c9c1edcf71045d53722210dd67e717) of the videobox I'm attempting to add.

**Comment by stephenyeargin** [comment]
Through some more digging with the React Debug Tools:

- The `$r.iframe.src` property has the correct player data.
- The rendered version of the `<iframe>` tag does not have a `src` attribute
- I started reading this [engineering topic](https://developer.zendesk.com/blog/rendering-to-iframes-in-react) from @Zendesk to see how hard this problem can really be
- While playing in the debug console, I am yet to find a `load()` event that may set things up, thereby at least telling me where in the lifecycle this is falling apart.

**Comment by stephenyeargin** [comment]
Figured it out. We were using an older version of react (`0.13.x`) which wasn't behaving. A forced upgrade made it work.
