### ISSUE TITLE
Incorrect Vimeo thumbnail url

### ISSUE THREAD

**Issue by positimo** [CookPete/react-player#1000]
Noembed seems to return stale information for Vimeo thumbnails at least when the thumbnail gets updated.

#### Current Behavior
The Vimeo video thumbnail url returned from Noembed API `https://noembed.com/embed?url=...` does not match with the thumbnail information received from Vimeo's Oembed API `https://vimeo.com/api/oembed.json?url=...`.

#### Expected Behavior
I would expect to receive the up-to-date thumbnail url, which is provided by the Vimeo API.

#### Steps to Reproduce
1. Upload a video to Vimeo
2. Update the video thumbnail
3. Monitor the thumbnails provided by the two API's

#### Other Information
Is Noembed still a reliable source of information, the library hasn't been updated in 3 years!
https://github.com/leedo/noembed

**Comment by CookPete** [comment]
>Is Noembed still a reliable source of information, the library hasn't been updated in 3 years!

I'm open to suggestions for a service that returns up to date thumbnails from an arbitrary URL?

**Comment by positimo** [comment]
Cool, no ideas here unfortunately, just stumbled into the whole topic of video thumbnails first time today...
