### ISSUE TITLE
How can we add `ffmpeg` codec in the react-player?

### ISSUE THREAD

**Issue by SandeepKharbanda** [CookPete/react-player#1001]
How can we add `ffmpeg` codec in the react-player?
#### Current Behavior
I am unable to play 4K & live URLs as these URLs are working on other platforms(After adding ffmpeg codec)

#### Environment
- URL attempting to play: http://tivix.eu:8000/movie/demo4/1SVHifcnbO/88814.mkv

**Comment by Shashank2406** [comment]
+1

**Comment by SandeepKharbanda** [comment]
Any update?

**Comment by jasmeet447** [comment]
+1

**Comment by souvikTtn** [comment]
+1

**Comment by sakshityagi** [comment]
+1

**Comment by CookPete** [comment]
This is very unlikely to happen. See https://github.com/videojs/video.js/issues/5910#issuecomment-479485887

Every resource I can find tells you to use `ffmpeg` to encode your `mkv` videos into a web-friendly format. If anyone can find any tool or library to play them natively in the browser, then ReactPlayer may be able to use that, however I'm not sure such a thing exists.
