### ISSUE TITLE
Support for .H265 Codec?

### ISSUE THREAD

**Issue by Shashank2406** [CookPete/react-player#1002]
No Support for .H265 Codec

Current Behavior

When playing .H265 video codec the player throws an error

Environment

URL attempting to play: http://tivix.eu:8000/movie/demo4/1SVHifcnbO/88814.mkv

Error

bubbles: false
cancelBubble: false
cancelable: true
composed: false
currentTarget: null
defaultPrevented: false
eventPhase: 0
isTrusted: true
path: (8) [video, div, div.App, div#root, body, html, document, Window]
returnValue: true
srcElement: video
target: video
timeStamp: 1427.930000001652
type: "error"

**Comment by SandeepKharbanda** [comment]
I am also getting the same issue?

**Comment by Shashank2406** [comment]
Any update?

**Comment by souvikTtn** [comment]
+1

**Comment by sakshityagi** [comment]
Any update on this? Facing same issue.

**Comment by CookPete** [comment]
Unless you are playing a HLS or DASH stream, ReactPlayer simply renders a `<video>` element with some event bindings when you pass a file path. Nothing special. If the browser doesn't natively support it, ReactPlayer won't support it.

More info here (namely in the resources tab): https://caniuse.com/#feat=hevc
