### ISSUE TITLE
It is not possible to maximize video

### ISSUE THREAD

**Issue by jurajkrivda** [cookpete/react-player#1007]
#### Current Behavior
If I click on the fullscreen button nothing happens

#### Expected Behavior
I expect the video to maximize

#### Environment
- Browser: Chrome
- Operating system: OSX Catalina

#### Other Information
Allow attribute will take precedence over 'allowfullscreen'.
[Deprecation] 'HTMLVideoElement.webkitSupportsFullscreen' is deprecated. Please use 'Document.fullscreenEnabled' instead.

**Comment by CookPete** [comment]
What type of URL are you trying to play? It might be that the player API needs some extra configuration.

**Comment by jurajkrivda** [comment]
@CookPete it is for any twitch stream. My component

```
function Player({ url, parent }: PlayerProps) {
  return (
    <ReactPlayer
      style={{
        position: 'absolute',
        top: 0,
        left: 0,
        width: '100%',
        height: '100%',
      }}
      playing={false}
      url={url}
      width="100%"
      height="100%"
      config={{
        options: {
          theme: 'dark',
          parent,
          allowfullscreen: true,
        },
      }}
    />
  );
}
```

**Comment by CookPete** [comment]
There must be something going on with your specific environment/implementation. The Twitch examples at https://cookpete.com/react-player seem to work fine?

**Comment by jurajkrivda** [comment]
It works but you implement your own controls. When I have controls=true it doesn't work as I wrote above

**Comment by CookPete** [comment]
I'm going to need an example repo or a better way to reproduce this. I can enable controls (ie `controls={true}`) on the demo app and fullscreen works fine for Twitch videos.
