### ISSUE TITLE
Callback on 25%, 50%, 75% and 100% of watched media?

### ISSUE THREAD

**Issue by FBosler** [CookPete/react-player#1008]
This isn't really a bug I think, but more of a feature request probably. I know I can specify an interval `progressInterval` to periodically poll progress.

However, that means I have to keep track of said thresholds myself and check against the actual progress on each `onProgress` call. Is there a better way of doing that?

I guess one could also do something like this:

```
    ref={player}

return <ReactPlayer
    progressInterval={player.current?.getDuration()/4*1000}
     onProgress={(played) => console.log('onprogress', played)}
/>
```
But this leads to somewhat funny thresholds:
![image](https://user-images.githubusercontent.com/14016698/92467085-55503480-f1d1-11ea-91ca-477eadbd4a24.png)

Cheers and thank you for the amazing library

**Comment by CookPete** [comment]
I think `progressInterval={player.current?.getDuration()/4*1000}` is just begging for problems… 😄 

You're better off keeping the default `progressInterval` (or a more frequent one) and checking when `played` is over `0.25`, `0.5`, `0.75` etc, perhaps with some extra state to only run something once when it hits each mark. I don't think things will get any more sophisticated than that.

**Comment by FBosler** [comment]
Yea that’s what I thought I would have to do. Thx Pete. Cheers
