### ISSUE TITLE
Can´t remove you tube play logo and details

### ISSUE THREAD

**Issue by dariomadeira** [CookPete/react-player#1009]
I have not been able to remove the logo of you tube in the center of the video or its description.
I tried with: 

```
config={{
    youtube: {
      playerVars: { showinfo: 1 }
    },
    facebook: {
      appId: '12345'
    }
  }}
```

but it keeps popping up, is there any way to get it out?

**Comment by CookPete** [comment]
`showinfo` has been deprecated since 2018:

>The showinfo parameter, which indicates whether the player should display information like the video title and uploader before the video starts playing, is also being deprecated. Following the change, the channel avatar and video title will always display before playback begins, when playback is paused, and when playback ends. The avatar being displayed is new behavior that will be consistent across all embedded players.

https://developers.google.com/youtube/player_parameters#release_notes_08_23_2018

The only thing left to use is `modestbranding`, which ReactPlayer defaults to `1` – but this still shows a youtube logo and avatar/title when the video is paused.
