### ISSUE TITLE
onDuration fires on unmounted component when re-mounting

### ISSUE THREAD

**Issue by kevinzwh** [CookPete/react-player#101]
I'm not sure if this is a bug in ReactPlayer or my code, but I found that onDuration will fire on the component when trying to re-mount after having been unmounted.

I'm providing onDuration with a function that sets state that I want my component to use once the video player is successfully loaded.

Here's a snippet of the callback:
```es6
  setRendered() {
      this.setState({ rendered: true })
    }
  },
```

```es6
<ReactPlayer
  { ...this.props }
  onDuration={ this.setRendered }
```

I have a tabbed interface that renders components that a user wants to see - so when a user clicks another tab, it unmounts ReactPlayer and renders a different component. When you try to mount ReactPlayer again is where this warning occurs.

Here's the warning message:
```
warning.js:36 Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the VideoPlayer component.
printWarning @ warning.js:36
warning @ warning.js:60
getInternalInstanceReadyForUpdate @ ReactUpdateQueue.js:49
enqueueSetState @ ReactUpdateQueue.js:201
ReactComponent.setState @ ReactComponent.js:64
setPlayerState @ video_player.jsx:26
setRendered @ video_player.jsx:36
Base._this.onReady @ Base.js:63
Vimeo._this.onMessage @ Vimeo.js:78
```

I currently have a workaround, however it would be great if I didn't have to do this since using `isMounted` is an [anti-pattern](https://facebook.github.io/react/blog/2015/12/16/ismounted-antipattern.html)

```es6
// Workaround

  setRendered() {
    if(this.isMounted()) {
      this.setPlayerState('rendered')
    }
  },
```

**Comment by CookPete** [comment]
Hey @kevinzwh, does [this commit](https://github.com/CookPete/react-player/commit/29c6fe02bec1c77dbccdd542f956c2e4a4f5be29) help? The only reason I can think this would happen is because Vimeo's event listener isn't removed when unmounting.

Also, if you are using `onDuration` to check whether the player has loaded or not, we should really look at exposing an `onReady` prop instead?

**Comment by kevinzwh** [comment]
@CookPete That was quick! 
Just checked it, definitely fixed. You were right about the vimeo event listener being the issue!

On the second note, an exposed onReady prop would definitely be great to have.
