### ISSUE TITLE
Plan for an expansion to support youku videos

### ISSUE THREAD

**Issue by rocklaam** [cookpete/react-player#1011]
#### Expectation
Hi all, I admire this library a lot. I wonder if we have any plan to extend the library to support youku videos (a replacement for youtube in China) or not?

#### Idea
I see some libraries on npm/ Git, and they are using the iframe mechanism to load youku videos. This mechanism is the same as playing youtube on this library. I think you are able to do this. Hope it helps and many thanks for a wonderful library!

**Comment by CookPete** [comment]
@rocklaam do you have a `client_id` that I can use for testing? Support will be quite basic but I think it is possible.

**Comment by cookpete** [comment]
I actually have something working but I need a `client_id` to test this. @rocklaam reopen when you have one I can use!
