### ISSUE TITLE
react-player is not visible inside iframe

### ISSUE THREAD

**Issue by eliascygnus** [CookPete/react-player#1012]
#### Current Behavior
React-player is not visible inside iframe, but still it's working

#### Expected Behavior
React-player should probably work inside iframe

#### Steps to Reproduce

1. Create iframe
2. Put react-player inside iframe

#### Environment
- URL attempting to play: 
- Browser: chrome
- Operating system: macOS
- jsFiddle example: https://jsfiddle.net/q4m5wnj0/18/

**Comment by CookPete** [comment]
I don't think rendering components directly inside `<iframe>` tags will work out of the box. You may find these things helpful:

- https://stackoverflow.com/a/34744946/1250405
- https://github.com/ryanseddon/react-frame-component
