### ISSUE TITLE
Player crashes after playing for about 1-2 days straight

### ISSUE THREAD

**Issue by zigliad** [cookpete/react-player#1013]
I have a website that used in lobbies, without any user interaction, which just shows some messages and plays music from youtube.
The player works fine, but after a day or two it crashes and there is a gray screen... Then i refresh the page and it working again for 1-2 days... and again and again.

This is really frustrating. Just to be clear, i am using react player to play a youtube playlist with about 60 songs.

**Comment by CookPete** [comment]
Can you narrow this down to a problem with ReactPlayer? Or does it happen with a normal youtube playlist embed?

**Comment by zigliad** [comment]
Hi, acatully I am not sure, how can I check it?
Meanwhile, I got a screenshot of the error, if it helps:

![CEFC1090-2220-4B3E-BE90-0E2ED953D239](https://user-images.githubusercontent.com/46021388/93169183-3b60a580-f72d-11ea-9516-e2096c3d8e04.jpeg)

I will try to understand also if this is specific for react player and I hope I will come back with an answer soon, 

Thanks for your reply!

**Comment by zigliad** [comment]
> Can you narrow this down to a problem with ReactPlayer? Or does it happen with a normal youtube playlist embed?

Hi man. Im pretty sure now its a problem with ReactPlayer, as it works fine for days without it.
Still, it will be great if it will be solved because this library is very, very nice and useful.

**Comment by afzaalahmad** [comment]
@zigliad did you try playing youtube video directly for days in their player, because I am pretty sure that there player has this problem, because I've seen this problem on youtube so just cross checking with you. If not, can you do that?

**Comment by cookpete** [comment]
I think based on what @afzaalahmad said, I don't know what can be done about this. The "solution" would be to add some logic or a browser extension to refresh the page every 24 hours or so.
