### ISSUE TITLE
Youtube Video Swap Broken on Chrome

### ISSUE THREAD

**Issue by dalespiteri** [cookpete/react-player#1014]
## Current Behavior
Setting a new youtube URL is no longer swapping videos. It's giving an error: ReactPlayer: the attempt to load https://www.youtube.com/watch?v=... is being deferred until the player has loaded.

#### Expected Behavior
The video player to update with the new video URL. 

#### Steps to Reproduce
1. Go here: https://cookpete.com/react-player/
2. Select a test youtube video, or paste in a custom URL. First load seems to be fine.
2. Paste in a new youtube URL in the Custom URL text field and click load.
3. Check console for error message
4. You can also just click A under youtube to load the first video, then click B under youtube and the video will not switch.

#### Environment
- URL attempting to play: Tried many different ones, but here is one: https://youtu.be/6r-WSSbKUC8
- Browser: Chrome
- Operating system: Windows 10

#### Other Information
I've test this in Edge, and Firefox as well, but the player works normally. Seems to be specific to Chrome.

**Comment by cookpete** [comment]
I am assuming this was a temporary bug with the Youtube player API. Things seem fine now? Or do you happen to be using `config.embedOptions.events`?
