### ISSUE TITLE
Adding any events in youtube embedOptions stops the Player onReady event from ever triggering

### ISSUE THREAD

**Issue by mherczeg** [cookpete/react-player#1016]
#### Current Behavior
Youtube embedOptions are completely overwritten with the config value ( [src](https://github.com/CookPete/react-player/blob/19857af64d1afa55767d808ea5f61c4eecb4d21f/src/players/YouTube.js#L74) )

causing this handler to never run.

```javascript
onReady: () => {
  if (loop) {
    this.player.setLoop(true) // Enable playlist looping
  }
  this.props.onReady()
},
```

the ready handler never running stops a couple things from working, one of them is changing the url (I've ran into this [warning](https://github.com/CookPete/react-player/blob/19857af64d1afa55767d808ea5f61c4eecb4d21f/src/Player.js#L44), though this particular problem can be circumvented by setting the url to empty first, and then to the new value), and the progress update won't fire either. 

#### Expected Behavior

both the event handlers passed in through the props, and the event handlers added in the `Youtube` class are classed

**Comment by CookPete** [comment]
What events are you using, out of curiosity? I think most, if not all, are covered by other ReactPlayer props.

**Comment by mherczeg** [comment]
`onStateChange`

**Comment by CookPete** [comment]
What state change are you listening for? The logic here covers every type, I think?

https://github.com/CookPete/react-player/blob/19857af64d1afa55767d808ea5f61c4eecb4d21f/src/players/YouTube.js#L106-L125

**Comment by mherczeg** [comment]
fair enough, I guess I can work around using the youtube player events, thanks.

(I would still recommend to either not allow `embedOptions.events` in the config, or to not overwrite the default ones completely, so people naively trying to use youtube player events won't break the player.)

**Comment by cookpete** [comment]
I'm going to add a console warning when `embedOptions.events` is set.
