### ISSUE TITLE
Override hls configuration to add authorization header

### ISSUE THREAD

**Issue by amanpwl92** [cookpete/react-player#1018]
I am trying to play audio from an API but that stream API need a security token. I tried to override hls confiuration like this : 
`<ReactPlayer url={url}`
                             `config={{`
                                 `file: {`
                                     `forceAudio: true,`
                                     `hlsOptions: {`
                                     `forceHLS: true,`
                                     `debug: false,`
                                     `xhrSetup: function(xhr, url) {`
                                                 `xhr.setRequestHeader('Authorization', `Bearer ${token}`)`
                                         `},`
                                     `}`
                                ` }`
`}}/>`

But it is not able to achieve what i was expecting. Could someone help ?

**Comment by potikorn** [comment]
Same here I can't play video from my site with authorization, seem like media request does not take token key. Can anyone help us?

**Comment by cookpete** [comment]
This is better suited for https://github.com/video-dev/hls.js/issues – this isn't a problem with ReactPlayer specifically.
