### ISSUE TITLE
HLS options not working on ios.

### ISSUE THREAD

**Issue by gkan30** [CookPete/react-player#1019]
HLS options don't work on ios. This works perfectly when I use any other platform. The bearer token is simply not getting attached to the header. I used console.log() and on ios alone the xhtSetup is never executed. How do I make it work on ios?

`config={{
                file: {
                  hlsOptions: {
                    xhrSetup: function(xhr, url) {
                        xhr.setRequestHeader('Authorization',localStorage.getItem('jwtToken'))
                    }
                  }
                }
              }}`

**Comment by CookPete** [comment]
HLS.js is not supported on iOS, so your config won't be applied. See https://github.com/video-dev/hls.js/issues/2367#issuecomment-530939229

**Comment by a-tonchev** [comment]
The hls works perfectly fine under IOS, only the Authentication token is not send with the header, is there any way to add this? When I remove the security of my server the video is played also in IOS
