### ISSUE TITLE
Video Events invoked twice

### ISSUE THREAD

**Issue by sid8491** [cookpete/react-player#1022]
#### Current Behavior
I am using react-player for watch-party based webapp where users can create a room and other users in the room.
Once added, any of the users can perform an action and that action will be applied for all the other users in the room. I am using django-channels for websocket handling in this case.
If there is pause event triggered by a user, websocket event is published to all the users and based on the event video is paused for all the other users.
Now the issue comes, when the video is paused on incoming event, it is again cause onPause action and sending event.
To solve this, I have used useState hook to determine we want to send the event or not.

But there is an issue that onPaouse is occuring twice in my case when the video is paused by incoming event.

```
const [playing, setPlaying] = useState(false);
const [userName, setUserName] = useState(getUserName());
const [sendEvent, setSendEvent] = useState("true");
const player = useRef(null);
const [videoUrl, setVideoUrl] = useState(DEFAULT_VIDEO_URL)

useEffect(() => {
    const websocketUrl = `ws://127.0.0.1:8000/room/`;
    socket = new W3CWebSocket(websocketUrl);
    socket.onmessage = (message) => {
        const data = JSON.parse(message.data)
        if (data.event === 'pause') {
                console.log(`I am ${userName}`);
                console.log(data);
                if (userName !== data.name) {   // do not perform for the user who invoked it
                    console.log(`inside if by ${userName}`);
                    player.current.seekTo(data.currentTime);
                    setSendEvent(false);    // do not send event
                    setPlaying(false);         //pause the video
                }
            }
        }
    }, [])

    const playerPause = () => {
        console.log(`trying to pause by ${userName} with sendEvent: ${sendEvent}`);
        if (sendEvent === true) {    //skip sending events
            socket.send(JSON.stringify({
                'name': userName,
                'event': 'pause',
                'currentTime': player.current.getCurrentTime()
            }));
        }
        setSendEvent(true);    // so that new events can be sent again
    }

<ReactPlayer  ref={player} url={videoUrl} controls={true} playing={playing} onPause={playerPause} />
```
![Issue GIF](https://media.giphy.com/media/WVuHcKiKQicx586GY6/giphy.gif)

Same GIF in HD:
- ![Issue GIF](https://media.giphy.com/media/WVuHcKiKQicx586GY6/source.gif)
- ![Issue GIF](https://github.com/sid8491/virtual_theater/blob/master/React%20player%20issue.gif)
- ![Issue GIF](https://s1.gifyu.com/images/React-player-issue.gif)

As you can see, I am getting two events for the 2nd user. First time it is working fine, as sendEvent is False, but for some reason it is invoking `playerPause()` function again which is causing the issue and event is being send again.

Could you please help me to find the underlying issue here.

#### Environment
- URL attempting to play: Any youtube url
- Browser: Chrome
- Operating system: Win10

**Comment by cookpete** [comment]
There is no easy solution for this. Anything that pauses a youtube player will cause an `onPause` event, whether it's a user clicking pause or a server event coming in.

My suggestion would be, when a `pause` event comes in from the server, to set a flag that indicates "the next `onPause` should do nothing". Then in your `onPause` listener you check for the flag – if it's true then don't send a pause event out and set the flag to false. If it's false then send a pause event out as normal.

You expose yourself to a bug when users pause the video at the exact same time as a pause event comes in from the server, but I assume this would be extremely rare.
