### ISSUE TITLE
Disable recommendations videos Youtube at the end of video

### ISSUE THREAD

**Issue by gaweki** [CookPete/react-player#1026]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior

At end of video, youtube still give other video recommendation 

#### Expected Behavior

At end of video, only show the pause button / don't show other video recommendation

#### Steps to Reproduce

1. Play video
1. Pull to the end
1. At the end, the recommendation appear as cards

#### Environment
- URL attempting to play: video in demo 
- Browser: Chrome
- Operating system: macOs Catallina
- jsFiddle example: on demo example

**Comment by CookPete** [comment]
There is no way to disable these any more. Youtube changed the `rel=0` behaviour in 2018: https://developers.google.com/youtube/player_parameters#release_notes_08_23_2018

That said, the videos don't show if the player is smaller than a certain width. See https://github.com/CookPete/react-player/issues/959
