### ISSUE TITLE
How does the React Player demo loads an url to the react-player component?

### ISSUE THREAD

**Issue by gordielachance** [CookPete/react-player#1027]
Hello, [I've already asked](https://stackoverflow.com/questions/63983816/how-does-the-react-player-demo-loads-an-url-to-the-react-player-component) this question on Stackoverflow but I don't get any responses.
I hope it do not bother to ask here :

I'm a react newbie. 

I'm looking at the [demo code](https://github.com/CookPete/react-player/blob/HEAD/src/demo/App.js) of the react-player component.

I understand that the app has functions "hooked" on the react-player component; that are declared like, for instance, 

    <ReactPlayer
    ref={this.ref}
    onPause={this.handlePause} 

What I don't get is **how an URL is loaded from the app to the react-player component** when you click on a button of the demo.  

Could someone explain that to me ? 

Thanks !

**Comment by gordielachance** [comment]
up?

**Comment by gordielachance** [comment]
could anyone help here ?
Thanks !

**Comment by CookPete** [comment]
The `url` is passed in as a prop to ReactPlayer:

```jsx
<ReactPlayer url='https://www.youtube.com/watch?v=3tH4dyOPZnY' />
```

In the demo app, the `url` is stored in state, and updated when clicking a button. Basic example using hooks below:

```jsx
const Player = () => {
  const [url, setUrl] = useState(null) // Set url as `null` at first, so nothing will play
  const onClickPlay = () => setUrl('https://www.youtube.com/watch?v=3tH4dyOPZnY')
  return (
    <div>
      <ReactPlayer url={url} />
      <button onClick={onClickPlay}>Play video</button>
    </div>
  )
}
```
