### ISSUE TITLE
How to add Thumbnail in react-player

### ISSUE THREAD

**Issue by Aneesawan34** [CookPete/react-player#1029]
I have try many times to add thumbnail in react-player but, failed. please give solution of it

**Comment by CookPete** [comment]
You can use `light` mode, which shows a thumbnail before loading the player. You can pass an image URL to the `light` prop to set your own thumbnail:

```jsx
<ReactPlayer
  url='https://www.youtube.com/watch?v=C0DPdy98e4c'
  playing
  light='https://placehold.it/640x360.jpg'
/>
```

https://jsfiddle.net/v6c7s1or/

If you are playing a file URL, you could use `poster` – see https://github.com/CookPete/react-player/issues/301.

**Comment by Aneesawan34** [comment]
it works thank you so much

**Comment by cookpete** [comment]
@chaithracheth See https://github.com/cookpete/react-player/issues/947

**Comment by ShoaibQasim1** [comment]
how to add a thumbnail from public folder not from any online url 
 in react-player

**Comment by adnangithubprojects** [comment]
how to add thumbnail when internet is slow it show thumbnail but when internet is fast it should play video automatically.

**Comment by tiredpyrx** [comment]
> how to add a thumbnail from public folder not from any online url in react-player

prefix image path with "/" ?
