### ISSUE TITLE
[Question] Embedding TikTok Videos

### ISSUE THREAD

**Issue by richessler** [cookpete/react-player#1030]
Feature Request/In work progress inquiry

#### Current Behavior
Doesn't support TikTok embedding

#### Expected Behavior
Support TikTok Embedding

This post is just a feature request and/or inquiry into work in progress. Will you be adding the ability to embed tiktok videos? Specifically is it in your roadmap or something for a PR?

**Comment by cookpete** [comment]
It doesn't look like there is an interactive player API for TikTok videos. There would be no value adding this to ReactPlayer – you may as well just render the standard embed code in your app: https://developers.tiktok.com/doc/Embed
