### ISSUE TITLE
Embedded Facebook Live videos will only play in fullscreen

### ISSUE THREAD

**Issue by becauseinterwebs** [cookpete/react-player#1032]
#### Current Behavior
I am embedding a Facebook Live video into a React app.  On Android, the video plays in place.  On iOS, when you click play it goes to fullscreen and will not play inline.

#### Expected Behavior
Video should play inline.

#### Steps to Reproduce
1.  Create an FB Live video
2.  Get the video URL
3. Play it in react-player

#### Environment
- URL attempting to play: Any FB Live url
- Browser: Chrome/Safari
- Operating system: iOS 13/14

<ReactPlayer
                playsinline={true}
                controls={false}
                ref={ref}
                pip={false}
                className='react-player'
                width='100%'
                height='100%'
                url={urlToPlay}
                playing={playing}
                volume={volume}
                muted={muted}
                config={{
                    youtube: {
                        playerVars: { showinfo: 1 }
                    },
                    facebook: {
                        appId: process.env.REACT_APP_FB_ID
                    }
                }}
/>

#### Other Information
I'm thinking this may actually be an issue with iOS, but wanted to post it here to see if there are any settings or anything that can be done to prevent it from going fullscreen.  I have tried variations on the settings and nothing seems to work (or I have not found the magic combo ;) )

**Comment by pmourer** [comment]
I'm having a possibly similar issue where it seems that vimeo videos are requesting fullscreen when they start playing on mobile.

**Comment by cookpete** [comment]
There doesn't seem to be any setting in the FB embed options to enable `playsinline` on the video element. Not much we can do I'm afraid.

https://developers.facebook.com/docs/plugins/embedded-video-player/
