### ISSUE TITLE
Not able to embed permanent live url link in youtube

### ISSUE THREAD

**Issue by rajorpratyush** [cookpete/react-player#1033]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior

Not able to use permanent live url from youtube i.e https://www.youtube-nocookie.com/embed/live_stream?channel=UC6K7yzj2kV3v3sASdaYCY0Q although i am able to embed the same with iframe

#### Expected Behavior

I should be able to use permanent live embed 

#### Steps to Reproduce

Just put https://www.youtube-nocookie.com/embed/live_stream?channel=UC6K7yzj2kV3v3sASdaYCY0Q  in mediaurl and it will not work but with iframe this works

#### Environment
- URL attempting to play: https://www.youtube-nocookie.com/embed/live_stream?channel=UC6K7yzj2kV3v3sASdaYCY0Q
- Browser: Chrome
- Operating system: Mac
- jsFiddle example: https://jsfiddle.net/sv5x3ug1

#### Other Information

No

**Comment by mohabkandil** [comment]
using the permanent live URL results in playing a weird playlist

I entered this URL:
https://www.youtube.com/embed/live_stream?channel=UCLA_DiR1FfKNvjuUpBHmylQ

but the iframe I got had src= https://www.youtube.com/embed/null?autoplay=0&mute=0&controls=0&origin=http%3A%2F%2Flocalhost%3A8000&playsinline=1&listType=playlist&list=UUIYVU7fPs_n6gJIBso3ryeg&showinfo=0&rel=0&iv_load_policy=3&modestbranding=1&enablejsapi=1&widgetid=1

any idea what is going on here?

**Comment by IgnusG** [comment]
Not sure if this is related, but I do get an old version of the stream when I enter such URL. It loads fine but displays something different (from the past) than what I would get if I open the url in the browser directly.

**Comment by IgnusG** [comment]
I've removed the `list_type`, added `live_stream` instead of `null` and changed `list` to `channel` (not replacing `UC` with `UU` in the URL) which seems to work:

```
https://www.youtube.com/embed/live_stream?autoplay=0&amp;mute=0&amp;controls=0&amp;origin=http%3A%2F%2Flocalhost%3A8000&amp;playsinline=1&amp;channel=UCLA_DiR1FfKNvjuUpBHmylQ&amp;showinfo=0&amp;rel=0&amp;iv_load_policy=3&amp;modestbranding=1&amp;enablejsapi=1&amp;widgetid=1
```

**Comment by IgnusG** [comment]
Seems like the JS API does not support these methods. The only solution I found online is from this stackoverflow thread (2017) that suggests creating an iframe with the constructed url and passing that to the YT instance instance instead of an empty div:

https://stackoverflow.com/questions/47241553/youtube-iframe-api-for-live-videos

```
<iframe id="player" src="https://www.youtube.com/embed/live_stream?channel=CHANNEL_ID?enablejsapi=1"></iframe>

var player = new YT.Player('player', {});
```
