### ISSUE TITLE
Using a unique key on a parent element cause react to re-render all components upon video play back?

### ISSUE THREAD

**Issue by UPLukeet** [cookpete/react-player#1037]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior
pressing play on the video starts the video but as soon as it starts it stops as all elements re-render

#### Expected Behavior
video to play

#### Steps to Reproduce
    const Uid = Math.random() * Math.random();
using a unique key such as 
```
<div key={Uid}>
<Reactplayer></Reactplayer>
</div>
```

causes this issue

#### Environment
Youtube url 
Chrome
Windows and android
- jsFiddle example: https://jsfiddle.net/sv5x3ug1 don't know?

**Comment by cookpete** [comment]
This is how React works. If you pass a random `key` that changes on every render, React will unmount and re-mount that element on every render.
