### ISSUE TITLE
Can I take a screenshot of video somehow?

### ISSUE THREAD

**Issue by batrlatom** [cookpete/react-player#1038]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior
Unable to take a screenshot

#### Expected Behavior
I would like to somehow take a screenshot of the current frame played in the videoplayer

#### Environment
any youtube video

**Comment by Rile14929** [comment]
I also encountered the same problem，Is it resolved?

**Comment by Rile14929** [comment]
https://github.com/CookPete/react-player/issues/341     This might help you

**Comment by batrlatom** [comment]
Hi, thanks for the hint. I was able to somehow resolved half of the equation since I am able to get a screenshot of video source from mp4. But getting screenshot of youtube video would be great. Is it possible?

**Comment by Rile14929** [comment]
Maybe not, my personal opinion

**Comment by cookpete** [comment]
It looks unlikely this will ever be possible with players that use iframes: https://developer.mozilla.org/en-US/docs/Mozilla/Gecko/Chrome/API/Browser_API/getScreenshot#Browser_compatibility
