### ISSUE TITLE
React-player forces global Promise to es6-promise

### ISSUE THREAD

**Issue by sedubois** [CookPete/react-player#104]
I use the great [https://github.com/este/este](Este) boilerplate, which relies on the global promise being Bluebird. However importing react-player changes that to es6-promise. 

Could react-player be changed so that it doesn't affect the global Promise?

**Comment by CookPete** [comment]
Hey @sedubois what errors are you getting? I'm assuming that moving to a [proper webpack polyfill](https://gist.github.com/Couto/b29676dd1ab8714a818f) will solve your issue but I'm just curious.

**Comment by sedubois** [comment]
I'm not terribly familiar with polyfills, here's what I did: https://github.com/belongapp/belong/commit/3897f6c9d97213a60f170026101816c71dfae51b

If I don't add that code in `configureBluebird.js`, then an unrelated issue arises in the browser: `finally` undefined in https://github.com/belongapp/belong/blob/master/src/common/app/actions.js#L21, because an es6-promise is thrown instead of bluebird (and `finally` is only in bluebird API).

**Comment by CookPete** [comment]
Ah I see now. I think the right thing to do is to remove the [import line](https://github.com/CookPete/react-player/blob/master/src/ReactPlayer.js#L1), move the polyfills to the webpack config and simply add a note to the readme telling devs to roll their own polyfill to support older browsers.

**Comment by CookPete** [comment]
>Apparently the use of babel-loader means webpack.ProvidePlugin can't be used

This is interesting. I have tested a promise and fetch polyfill using `ProvidePlugin` [like so](https://gist.github.com/Couto/b29676dd1ab8714a818f#gistcomment-1617941) and it seems to work ok.

**Comment by CookPete** [comment]
@sedubois for your use case, perhaps check out [babel-plugin-transform-promise-to-bluebird](https://github.com/chpio/babel-plugin-transform-promise-to-bluebird). From [this discussion](https://github.com/babel/babel-loader/issues/23).

**Comment by sedubois** [comment]
Thanks. I moved to another stack and this might not apply anymore.

**Comment by CookPete** [comment]
No problem. I think your point still stands and that the package should let developers choose to apply their own promise polyfill for older browsers.

**Comment by sedubois** [comment]
Yes! Shall I reopen?
