### ISSUE TITLE
follow HTTP 302 redirect

### ISSUE THREAD

**Issue by hex-m** [cookpete/react-player#1040]
#### Current Behavior
An URL that leads to a HTTP 302 response with a link to a video file is not played.

#### Expected Behavior
The redirect should be followed and the video played.

#### Steps to Reproduce
1. open the [demo](https://cookpete.com/react-player/)
1. enter this URL: https://fileshare.uibk.ac.at/f/4d6132da815d44d6ae5b/?dl=1
1. press "load"
1. nothing happens

verify it works if you resolve the redirect manually:
1. open the [demo](https://cookpete.com/react-player/)
1. enter this URL: https://fileshare.uibk.ac.at/seafhttp/files/a67fa2d5-5289-478c-ba6f-ecceac9a50b3/Coffee_Run_-_Blender_Open_Movie-full_movie.webm
1. press load
1. enjoy the video

#### Other Information
The example video is hosted on a Seafile instance.

**Comment by jayunewal** [comment]
I am facing the same issue. Is there any update on this issue?

**Comment by cookpete** [comment]
If your URL does not end in `.m3u8` but redirects to a `.m3u8` file, you need to force hls.js with `config={{ forceHLS: true }}`
