### ISSUE TITLE
Please add "module" entrypoint in package.json manifest 

### ISSUE THREAD

**Issue by kristianmandrup** [cookpete/react-player#1042]
Package found! However, no web-optimized "module" entrypoint was found in its package.json manifest.

This will allow it to work with snowpack, a modern package manager for the web.

Please make it compatible with modern web ES modules

**Comment by luwes** [comment]
there is a ESM bundle nowadays in the dist folder
https://github.com/cookpete/react-player/blob/master/dist/ReactPlayer.standalone.es6.js
