### ISSUE TITLE
multi-codec manifests fail with InvalidStateError with File Player on Safari

### ISSUE THREAD

**Issue by Marioario** [cookpete/react-player#1043]
#### Current Behavior
HLS manifests that use multiple codecs create InvalidStateError: the object is in an invalid state errors on Safari (works fine on Chrome).

Here are two as example manifests to reproduce the issue
https://video-cdn.livenation.com/lyv/20200929/0/prog/v0/platform_vod.m3u8
https://video-cdn.livenation.com/lyv/20200929/0/4up/v0/platform_vod.m3u8

#### Expected Behavior
Expected to play on Safari

#### Steps to Reproduce
1. https://cookpete.com/react-player/
2. Paste https://video-cdn.livenation.com/lyv/20200929/0/4up/v0/platform_vod.m3u8
3. Click "Load"
4. Check console

#### Environment
- URL attempting to play: https://video-cdn.livenation.com/lyv/20200929/0/4up/v0/platform_vod.m3u8
- Browser: Safari
- Operating system: Mac
- jsFiddle example: N/A

#### Other Information
This same manifest works on other players such as JWPlayer: https://www.jwplayer.com/developers/stream-tester/

**Comment by cookpete** [comment]
Relevant issues with `hls.js`: https://github.com/video-dev/hls.js/search?q=safari+invalid+state&type=issues

This is not something that can be fixed in this repo.
