### ISSUE TITLE
How do you change the playback speed while video is playing

### ISSUE THREAD

**Issue by duncangroenewald** [cookpete/react-player#1047]
#### Current Behavior
I am trying to change the video playback speed while a video is playing but using a 'useState()' property results in the whole video screen refreshing and playback suspends or gets stuck.

Is there an example somewhere using React on how to do this.  I am not very familiar with React but setting any state properties seems to cause the ReactPlayer to refresh its screen which is no desirable.

#### Expected Behavior
I expect to be able to change the 'playbackRate' state property and react-player should change the playback speed accordingly without refreshing its screen and stalling playback.  And I say 'stalling' because the pause button is still showing but the video playback is stopped

#### Steps to Reproduce
Here is the essence of my code
```
const [playbackRate, setPlaybackRate] = useState(1);
  const handleSpeed = (event, newSpeed) => {
    setPlaybackRate(newSpeed)
  };
  const setPlayBack = () => {
    videoRef.current.playbackRate = playbackRate;
  };
  return (
    <AppCard height={1}>
      <Box mt={-5} mx={-6} position="relative" >
        <ReactPlayer
          ref={videoRef}
          onCanPlay={() => setPlayBack()}
          className={classes.reactPlayer}
          controls={true}
          url={authLink}
          playbackRate={playbackRate}
        />
        <Box zIndex="tooltip" position="absolute" right={0} top={0} >
        <ToggleButtonGroup orientation="vertical" value={playbackRate} 
        exclusive onChange={handleSpeed}
        position="absolute" right={0} top={50}
        >
          
          <ToggleButton value={0.5} aria-label="list">
            <SlowMotionVideoIcon />
          </ToggleButton>
          <ToggleButton value={1} aria-label="module">
            <PlayCircleOutlineIcon />
          </ToggleButton>
          <ToggleButton value={2.0} aria-label="quilt">
            <FastForwardIcon />
          </ToggleButton>
        </ToggleButtonGroup>
        </Box>
      </Box>
```

#### Environment
N/A

#### Other Information
N/A

**Comment by cookpete** [comment]
> I am not very familiar with React but setting any state properties seems to cause the ReactPlayer to refresh its screen which is no desirable.

It sounds like something weird is happening here outside of ReactPlayer. Updating state should not cause a complete refresh. What type of URL are you trying to play? Are there any errors in the JS console?

Here is a very basic example of using `useState` to change the playback rate, which may help: https://jsfiddle.net/wm5L4oek/

Your use of `videoRef` and `setPlayBack` might be causing issues. You do not need to call `setPlayBack` at all as this [happens internally when a video starts playing](https://github.com/cookpete/react-player/blob/c6e87c5df940b6b8add458bb457914d29c15e2da/src/Player.js#L182-L184). 

Also, `videoRef` is not a reference to the `<video>` element so doing `videoRef.current.playbackRate = playbackRate` will not achieve anything.
