### ISSUE TITLE
YouTube Behaviours on iPhone

### ISSUE THREAD

**Issue by williamli** [cookpete/react-player#1049]
![IMG_1051](https://user-images.githubusercontent.com/179761/96109189-fb016c80-0f10-11eb-8858-c16b31fce9be.PNG)

Top player: YouTube video with `react-player`
Bottom player: official YouTube video with embed code

Differences:
1. `react-player`'s video controls are scattered around the video, some are covered by YouTube's top banner and cannot be clicked. The official YouTube embedded version has all the controls nicely confined in the bottom bar.
2. YouTube's embedded player plays video in fullscreen on iPhone when the play button is pressed. `react-player` (with playsinline set to default) plays the video inline.

Is there any way to make 1 and 2 more "YouTube like"? Right now it is very hard to play the video in fullscreen since the fullscreen button is covered by the YouTube banner.

**Comment by cookpete** [comment]
I have looked at this for a while and I can't figure out how the "native" youtube embed has controls on a single row across the bottom.

I thought it would be a certain attribute but even copying and pasting the raw `<video>` markup doesn't work: https://jsfiddle.net/7r6mv0s9/

I'm not sure there's anything we can do here.

**Comment by prithvin** [comment]
Try to set every other element on the page w/ 
* {
 position: unset !important;
}

hacky but works for me
