### ISSUE TITLE
SoundCloud throws warning when reloading

### ISSUE THREAD

**Issue by sedubois** [CookPete/react-player#105]
`SoundCloud.js:93` throws this warning when reloading page:

`Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the SoundCloud component.`

The code used is here: https://github.com/belongapp/belong/commit/3897f6c9d97213a60f170026101816c71dfae51b

**Comment by CookPete** [comment]
Yeah I have noticed this but not pushed my fix up yet, as there are quite a lot of updates to come. Good spot though!
