### ISSUE TITLE
Error with playbackRate when switching videos

### ISSUE THREAD

**Issue by toschlog** [cookpete/react-player#1052]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior
When switching from a Vimeo video to a YouTube video on Mac, I get this error:

![image](https://user-images.githubusercontent.com/25090868/96158135-2b311700-0ee1-11eb-92c6-2d8964cd3d2a.png)

#### Steps to Reproduce
I have a repro case, but it looks to me like you just need to return from componentDidUpdate before checking the properties if this.player isn't defined.  If it's more complicated than that and you need more information, I'm happy to help.

#### Environment
Chrome, Mac

**Comment by cookpete** [comment]
I'm curious how you got this to happen?
