### ISSUE TITLE
Multiple audio URLs do not play beyond first one

### ISSUE THREAD

**Issue by jnorvell** [cookpete/react-player#1053]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior

In ReactJS (web) app, react player only plays the first URL given in an array and then stops. 

<ReactPlayer
  url={[
    'https://file-examples-com.github.io/uploads/2017/11/file_example_MP3_1MG.mp3',
    'https://filesamples.com/samples/audio/mp3/sample2.mp3'
  ]}
/>

#### Expected Behavior
I am expecting the second, third, fourth, etc. audio URLs to play automatically when the previous is completed.

#### Steps to Reproduce

1. Create a ReactPlayer and pass in an array of web URLs to mp3 audio files
1. Play the first one, and scrub forward to the end
1. Nothing happens after it stops.

#### Environment
- URL attempting to play: 
- Browser:  Chrome 86, Firefox 82
- Operating system: Ubuntu
- jsFiddle example: https://jsfiddle.net/sv5x3ug1

**Comment by cookpete** [comment]
>I am expecting the second, third, fourth, etc. audio URLs to play automatically when the previous is completed.

The readme explains that an array of file paths is for _different sources_ of the same video, not a playlist.

https://github.com/cookpete/react-player#multiple-sources-and-tracks

Rough example of using state to play a list of videos: https://jsfiddle.net/2tr1fshc/
