### ISSUE TITLE
Quality Switcher in HLS video

### ISSUE THREAD

**Issue by sanjib-dev** [cookpete/react-player#1054]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior
No available option found

#### Expected Behavior
Support to add HLS Quality API

#### Environment
- URL attempting to play: HLS Url 
- Browser: Any (except safari)
- Operating system: Win / Linux

#### Other Information
Would be great if `{controls}` will add switcher automatically for HLS

**Comment by cookpete** [comment]
Would be great, but this is out of the scope of this library. ReactPlayer does not provide any custom controls. Only what the browser/player APIs provide. Sorry.
