### ISSUE TITLE
Default dash.js, hls.js and flv.js versions are out of date

### ISSUE THREAD

**Issue by jrstinson** [cookpete/react-player#1055]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior
The versions of dash.js and hls.js being used in react-player are several releases out of date, as such:

dash.js 2.9.2 -> 3.1.3
hls.js 0.13.1 -> 0.14.16

More recent versions are available via jsdelivr and cdnjs, but are not being used.

#### Expected Behavior
react-player should use the most recent stable release of dash.js and hls.js without needing to specify the newer versions in the configuration.

#### Steps to Reproduce
By default, the older versions of dash.js and hls.js are used.

**Comment by Aneesawan34** [comment]
yes currently this package is not run although, I have tried previous version 1.15.2 ? any idea so please share ?

**Comment by cookpete** [comment]
Fixed by https://github.com/cookpete/react-player/pull/1056
