### ISSUE TITLE
how to play video with react-player from spesific path

### ISSUE THREAD

**Issue by genc6541** [cookpete/react-player#1059]
I 'm using react-player for playing videos.It plays videos from urls(like youtube url) succesfully. But I'm trying a video stored in a spesific path like this "E:\video\xxx.mp4" . But video is not loading-

Video Player should work with videos stored whre in a folder path.
I think need to stream but how? I have tried a few way but I could not achieve. Can somebody help me?

#### Environment
- URL attempting to play:  "E:\video\xxx.mp4"
- Browser: Chrome
- Operating system: windows

**Comment by cookpete** [comment]
See https://github.com/cookpete/react-player/issues/823#issuecomment-604073841
