### ISSUE TITLE
onLoaded or onReady callback

### ISSUE THREAD

**Issue by meandavejustice** [CookPete/react-player#106]
It would be really nice to have a way to know when the video is loaded and ready to play. I have my own loading view I would like to use.

**Comment by CookPete** [comment]
If `playing` is set to `true` then `onPlay` is essentially the same as `onReady`, as the video will play as soon as it is ready. However I agree that exposing `onReady` would be nice and wouldn't be hard to add.

**Comment by CookPete** [comment]
Added in `0.11.0`

**Comment by meandavejustice** [comment]
Thanks!
