### ISSUE TITLE
Do not rely on User agent for checking native support for HLS

### ISSUE THREAD

**Issue by praneetrohida** [cookpete/react-player#1060]
#### Current Behavior
The library currently relies on the user agent string to check the native support for HLS. This breaks in the tools (e.g. [Sizzy](https://sizzy.co)) which use user agent to simulate testing on mobile devices.

#### Expected Behavior
The native HLS support should be checked using `video.canPlayType('application/vnd.apple.mpegurl')` as suggested in the hls.js Readme. This will ensure that it does not break when working with tools that rely on the user agent string for simulation.

**Comment by cookpete** [comment]
You can use `config={{ forceHLS: true }}` to force ReactPlayer to use `hls.js`. Using `video.canPlayType` requires loading a `video` into memory which I'm guessing wouldn't be great for SSR or memory efficiency.
