### ISSUE TITLE
React player does not play video in chrome browser when size is more than 200 MB

### ISSUE THREAD

**Issue by sharmadp** [cookpete/react-player#1062]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior

plays sound but does not play the video
#### Expected Behavior

should play both sound and video

#### Steps to Reproduce

1.
1.
1.

#### Environment
- URL attempting to play: 
- Browser: google chrome Version 86.0.4240.111 (Official Build) (64-bit)
- Operating system: windows 10 pro
- jsFiddle example: https://jsfiddle.net/sv5x3ug1

**Comment by cookpete** [comment]
Without an example of the video file you are trying to play there's not much I can do. I can play a `126.48 MB` MP4 in the demo app without any problems.

If audio works but video doesn't, could it be a problem with the encoding of the video itself? Do other videos of the same type/encoding work?
