### ISSUE TITLE
youtube mobile height attirbute not working 

### ISSUE THREAD

**Issue by afhaider** [cookpete/react-player#1063]
i tired many  time but cant find how to increase the mobile view height for this react player 
it work fine on desktop view but not mobile height remain constant as small

**Comment by cookpete** [comment]
Please reopen with a screenshot and a code snippet of the props you are using.

**Comment by afhaider** [comment]
<div className='player-wrapper'>
              {this.props.header.map(header => (
        <ReactPlayer 
          playing={true} loop={true}
          className='react-player'
          url={header.video}
          width={"100%"}
        
         height={670}

          
          light={header.thumbnailvideo}
          // light={"/media/logo/headerbhangra.png"}
          key={header.id}
        />  ))} 
      </div>
