### ISSUE TITLE
 youtube mobile height attirbute not working 

### ISSUE THREAD

**Issue by afhaider** [cookpete/react-player#1064]
i tired many time but cant find how to increase the mobile view height for this react player
it work fine on desktop view but not mobile height remain constant as small

https://drive.google.com/file/d/1Q-xyeZmj2XVKQ0DosZYGG5qiJJcYO3LB/view?usp=sharing

**Comment by afhaider** [comment]
afgt-243510.df.r.appspot.com

this is my native site u can view it on mobile and desktop the bug issue i face is height on mobile view

**Comment by cookpete** [comment]
Passing `height={670}`  will always set the height to `670px` regardless of if you're on mobile or not.

I suggest using `vw` to adjust the height according to the width of the viewport. Something like `height='50vw'`

For more info, see https://css-tricks.com/fun-viewport-units/
