### ISSUE TITLE
Can you load a local file video without an input?

### ISSUE THREAD

**Issue by jd-val** [cookpete/react-player#1065]
Hello,

I'm trying to make a component where the video has been preloaded and will automatically show the video. The video is stored locally in the project under a folder called assets. The only way I've seen to use local files so far is by using a <input> with type = file. I do _not_ want to do this and would rather have the video be there on page load. Is there a way to do this? My current code is below:

App.js related code:
//Route to where the video is
`<PrivateRoute path="/sample_video" render={(props) => (<Video videoFilePath="../assets/videoplayback.mp4" {...props} />)} />
`
Actual component code:

```
const Video = (props) => {
    //useState for video to be converted to URL
    const [videoFilePath, setVideoFileURL] = useState(props.videoFilePath ? props.videoFilePath: null);
 
    return(
        <div className="video-player">
            {/*If video loads correctly, show video. Else, display error message*/}
            {videoFilePath && <ReactPlayer url={videoFilePath} controls="true" />}
            {!videoFilePath && <p>Video failed to load. Please try again.</p>}
        </div>
    )
}
```

Any advice on this would be greatly appreciated

**Comment by cookpete** [comment]
Your video has to load from somewhere. It can be "stored locally in the project" but needs to exist on a web server somewhere when deployed. If your current route is `https://example.com/sample_video` and you are rendering `url='../assets/videoplayback.mp4'` (as per your example) then the video needs to be at `https://example.com/assets/videoplayback.mp4`.
