### ISSUE TITLE
No error fired when Youtube video is "unavailable in your country"

### ISSUE THREAD

**Issue by gordielachance** [cookpete/react-player#1067]
#### Current Behavior
Hi, sometimes a Youtube video is not playing because "unavailable in your country".
For instance, this one does not play in Belgium : https://youtu.be/NwMOpaxroTg

#### Expected Behavior
A player error should be fired so we could handle this ,is that possible ?

**Comment by cookpete** [comment]
There is no `onStateChange` or `onError` event triggered by the player API when this happens. There is nothing we can really do here until YouTube add something that we can hook in to.

Maybe try posting on StackOverflow as per https://developers.google.com/youtube/players/support

**Comment by gordielachance** [comment]
Ok, so I guess i'll have to use a timer that checks if a video has started playing after XX seconds...

**Comment by alyustik** [comment]
@gordielachance I've noticed that onDuration callback is not firing if video is unavailable in your country. Not sure if it is safe to use but maybe it will help

**Comment by gordielachance** [comment]
@cookPete : what about this ? https://stackoverflow.com/a/32503070/782013
