### ISSUE TITLE
Local subs not working

### ISSUE THREAD

**Issue by divya21raj** [cookpete/react-player#1068]
#### Current Behavior
The subtitles aren't showing up with this code
```
<ReactPlayer
            url="http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4"
            config={{
              file: {
                attributes: {
                  crossOrigin: "anonymous",
                },
                tracks: [
                  {
                    kind: "subtitles",
                    src: "subs.vtt",
                    srcLang: "en",
                    label: "subs",
                    default: true,
                  },
                ],
              },
            }}
```

#### Expected Behavior
Subs should show up. What I've tried - 
1. Have a local vid file with url="ElephantsDream.mp4". This doesn't load the video at all, getting some unsupported MIME type error
2. Load the file using a button and getting the url like "blob:http://localhost:3000/4e978751-35e7-4357-90bb-5a227f9c5440"
```
      let files = e.target.files;
      let file = files[0];
      let urlString = URL.createObjectURL(file);
```
which makes the video work, but subs still don't work.

3. Tried the same approach to upload the local subtitle file, but no luck.

#### Environment
- URL attempting to play: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4"
 or local file in project directory "ElephantsDream.mp4" or like "blob:http://localhost:3000/4e978751-35e7-4357-90bb-5a227f9c5440"
- Browser: Firefox and Chrome
- Operating system: Win 10 with WSL2

#### Other Information
That's all. Great work, thanks :)

**Comment by cookpete** [comment]
Sounds like you are having problems with the sample video file which is probably confusing things. 

Hopefully this jsFiddle from #443 helps: https://jsfiddle.net/1ma6kdrL/

If not, please reopen the issue with a jsFiddle or example repo to demonstrate the problem.
