### ISSUE TITLE
playing a list of sources in a background tab stops when the player changes (Chrome autoplay policy ?)

### ISSUE THREAD

**Issue by gordielachance** [cookpete/react-player#1072]
Hi, i'm using your (wonderful) player in a music app i'm working on.
It is basically a playlist that plays tracks and automatically skip to the next one when it is finished or has an error.

My problem is that when the tab is not active, the next track does play only if the player has NOT changed.

track A : Youtube
track B : Youtube
track C : Soundcloud
track D : Soundcloud
track E : Youtube

1.   I click track A (Youtube) in the active tab. It starts to play.  I go to another tab. ✔️
2.   When track A (Youtube) is over, it skips to track B (Youtube again), and plays in the background tab. ✔️
3.   When track B (Youtube) is over, it skips to track C (Soundcloud), and does NOT play unless I go to that tab. ❌
4.   When track C (Soundcloud) is over, it skips to track D (Soundcloud), and plays in the background tab. ✔️
5.   When track D (Soundcloud) is over, it skips to track E (Youtube), and does NOT play unless I go to that tab. ❌

How should I handle this ?

Thanks a lot.

**Comment by cookpete** [comment]
I'm curious to know if you get this problem in `react-player@1.15.3` with 

```
config={{ 
  youtube: { preload: true }, 
  soundcloud: { preload: true }
}}
```


This is [one of the oldest problems](https://github.com/CookPete/react-player/issues/7) I've had with ReactPlayer. The old `preload` config was a hacky way to try and get around this problem, but modern browsers with sophisticated autoplay policies made it very buggy and difficult to maintain.

If you still want to use `react-player@2`, you could try and emulate the old `preload` behaviour with a silent player for each type of track, that you somehow get the user to interact with. This might "prime" the tab so that any subsequent players would autoplay in the background. It is a bit of a pain though, for sure.

**Comment by gordielachance** [comment]
Hi, thanks for your reply.
I'll have a look. Here's [a demo](http://spiff-radio.org/V2/?url=https%3A%2F%2Fwww.reddit.com%2Fr%2Flistentous) of the app i'm working on.

**Comment by cookpete** [comment]
Looks good! Very similar to an old (dead) project of mine: https://github.com/cookpete/rplayr

**Comment by gordielachance** [comment]
Okay ! That is funny !
My idea came from the amazing (and now dead too) [Tomahawk player](https://github.com/tomahawk-player/tomahawk).
I have also written a Ruby API to extract tracklists.
I'll have a look at your code, since I had some troubles handling a playlist (skip songs, etc).  Wonder how you did that.
I think I have something working now, but will have to test it deeply.
Thanks for your help !

PS if by any chance you were interested in being involved in my project, tell me :)

**Comment by gordielachance** [comment]
I'm still struggling with this.

I don't know if something was updated either in your module or in Chrome, but now, I have only one single track playing; even if the same provider is called on the next track.

Here's a paste of [my current file](https://pastebin.com/XiM0TNv0).
The main method of this file, **resolveTracks()**, gets the source to play (will skip unplayable tracks, etc).  
Next track logic is within **handleOnEnded()** which is triggered by ReactPlayer's _onEnded_ event; and **handleOnError()**, which is triggered by ReactPlayer's _onError_ event.

Would you mind having a look at it ?
Thanks !

**Comment by gordielachance** [comment]
@cookpete : maybe a good news, the bug has been assigned at Chromium !  Let’s keep a look at this!

**Comment by gordielachance** [comment]
This [has been fixed](https://bugs.chromium.org/p/chromium/issues/detail?id=1244074#c6) by the Chromium team.  Will be shipped with Chrome 96 (planned for the 16th November 2021)

**Comment by gordielachance** [comment]
I [filled a bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=1733902) for Firefox too.

**Comment by gordielachance** [comment]
Fixed in Firefox 96, stable release planned for 2022-01-11 !
