### ISSUE TITLE
What is recommended size of video for mobile devices?

### ISSUE THREAD

**Issue by oleksi-l** [cookpete/react-player#1073]
Hi, we are using your library in project, it is awesome library. We have many videos in our project. What is recommended size of video for perfect playing on mobile devices?

**Comment by afzaalahmad** [comment]
@oleksi-l I don't think that there is such thing like perfect size for mobile devices, just make sure that you set your video container width and height, 16:9 respectively according to screensize of mobile.
For example, for a mobile having 375px width, best width and height can be 335px and 188.5px respectively, making them exactly 16:9.

**Comment by afzaalahmad** [comment]
@oleksi-l this rule is not specific to mobile devices, make sure to apply 16:9 rule on video for every device in your app.

**Comment by cookpete** [comment]
@afzaalahmad is correct. Devices can be all sorts of widths. Maintaining aspect ratio is the key. Check out the [responsive player example](https://github.com/cookpete/react-player#responsive-player) as a starting point.
