### ISSUE TITLE
how can play with stream bytes without videourl

### ISSUE THREAD

**Issue by genc6541** [cookpete/react-player#1077]
Hello, I have a video stream as bytes in mybackend. Like the below;
  
 string pathAndFilename = "file://file.xx.xom.tr//video.mp4";

            WebClient webClient = new WebClient();
            using (Stream stream = webClient.OpenRead(pathAndFilename))
            {
                // Process image...
                byte[] data1 = new byte[stream.Length];
                stream.Read(data1, 0, data1.Length);

            }

How can give this bytes to videcomponent to play? Is it possible playing with byte stream without giving any url?

**Comment by cookpete** [comment]
If you can get the byte stream into format that a `<video>` element would understand (blob, MediaStream, base64 encoded string) then it will work. If you aren't playing a video from youtube or facebook etc, ReactPlayer just renders a basic `<video>` under the hood.
