### ISSUE TITLE
How not to display advertisement on YouTube

### ISSUE THREAD

**Issue by yuta-m0328** [cookpete/react-player#1078]
In your demo page , any ads or other video suggestions  doesn't show when I stop playing Youtube. What part of the source is this implemented?

#### Current Behavior
Ads appear when I stop the playback of Youtube.

#### Expected Behavior
No ads or other video suggestions appear when I stop playback.

#### Environment
- URL attempting to play: https://github.com/jphacks/A_2010/blob/master/front/src/Main/VideoPlayer.js
- Browser: Chrome
- Operating system: Mac

**Comment by cookpete** [comment]
Are you talking about related videos showing when you pause? If so see https://github.com/cookpete/react-player/issues/959#issuecomment-653648900.

**Comment by yuta-m0328** [comment]
That's really I mean. Thank you.
