### ISSUE TITLE
Embed SoundCloud controls without picture

### ISSUE THREAD

**Issue by sedubois** [CookPete/react-player#108]
How can a SoundCloud track be embedded with controls but without the big blue placeholder picture (as there's nothing to display)?

**Comment by sedubois** [comment]
SoundCloud URLs accept `?show_artwork=true|false`, so this could normally be easily added to `soundcloudConfig` 😊 It would be an opportunity to add there the various query params they support.

**Comment by CookPete** [comment]
>SoundCloud URLs accept ?show_artwork=true|false, so this could normally be easily added to soundcloudConfig 😊 It would be an opportunity to add there the various query params they support.

SoundCloud URLs are just resolved to `mp3` URLs and played by `FilePlayer`, so any query params wouldn't directly work. It would be easy to add a config option to not show any image though.

>By the way, when providing a soundCloudConfig prop, would be good to make sure the default clientId gets used if none is provided.

Agreed, the config structure has always been a bit of a problem (hence why I had a go at [tidying it up](https://github.com/CookPete/react-player/pull/71) for a future version).

**Comment by sedubois** [comment]
OK I understand. Yes it would be useful to have a mechanism to configure how to display the different attributes (artwork, avatar, title, description, waveform, ...).

**Comment by CookPete** [comment]
>Yes it would be useful to have a mechanism to configure how to display the different attributes (artwork, avatar, title, description, waveform, ...).

This would involve changing ReactPlayer to use the Soundcloud Widget API, which is possible but quite a big change. For now, soundcloud tracks just display the artwork along with standard HTML5 `audio` controls.

Meanwhile, I've added a `showArtwork` option to the `soundcloudConfig` prop that will just display no image when set to `false`.

**Comment by sedubois** [comment]
Thanks a lot. Do you plan a new release soon? I didn't [find](https://github.com/npm/npm/issues/2974) a way to depend on GitHub head directly.

**Comment by CookPete** [comment]
Published `0.12.0`

In recent versions of `npm` you can just do `npm install cookpete/react-player` to depend on the latest commit on github.
