### ISSUE TITLE
YouTube video missing sound

### ISSUE THREAD

**Issue by toschlog** [cookpete/react-player#1080]
If I start a YouTube video from the first click in my app, I usually get no sound.  It seem to be a problem with starting the video too quickly after the first click enables audio -- if I wait 100ms before starting the video.  The problem does not occur.  This is happening in Chrome on Windows 10,

Here are the errors I'm seeing in the log file.
![image](https://user-images.githubusercontent.com/25090868/99424517-c3029600-28cf-11eb-897d-ca03230d8299.png)

**Comment by limitless-brain** [comment]
I'm using the player and it works correctly across all platforms, make sure you set up it correctly.
First thing, if you try to use auto-play make sure you override Youtube configuration.

`
<ReactPlayer
..
config={{
                        youtube: {
                            playerVars: {
                                autoplay: true,
                            }
                        },
                    }}
..
/>`

Second, make sure you initialize the player with muted value false.
`
const [muted, setMuted] = useState(false);
..
<ReactPlayer
..
          muted={muted}
..
/>`

I wish that will help you.

**Comment by cookpete** [comment]
Ideally you need to wait for `onReady` before making any changes that will call `unMute` or `setVolume` internally. The youtube player instance doesn't exist at the point you are currently doing it.
