### ISSUE TITLE
Lazy loading MP4 files within electronjs app not playing

### ISSUE THREAD

**Issue by mammacare** [cookpete/react-player#1081]
#### Current Behavior
ReactPlayer is unable to play a lazy-loaded video file.

#### Expected Behavior
I have to dynamically load a video based on the user's selected language and import it after mounting.

#### Steps to Reproduce
// import a video file based on selected language
const videoPath = videoLoader.getVideosPathByLanguage('en'); //returns absolute path to appropriate language dir
const video1 = React.lazy(() => import(videoPath+"\\pad1.mp4"));
....
Render(){ 
   return <ReactPlayer
          url={video1}
          ref={(player) => (this.player = player)}      
          onError={(e) => console.log("onError", e.message)} // this is firing an error message of undefined
        />
}

#### Environment
ElectronJS
Windows 10
#### Other Information
The lazy loading import is using an absolute path to retrieve the mp4 file from within the deployed electronjs app.

**Comment by cookpete** [comment]
Firstly, I'm not sure `React.lazy` is meant to be used for an import of a file path? I think it is intended for lazy loading React components only, which then need to be rendered inside a `<Suspense>`.

Either way, `url` needs to be a string that points to a video file. In your example, `video1` will be a promise (or something promise-like).

Does `url={videoPath+"\pad1.mp4"}` not work? I'm not familiar with how Electron works.
