### ISSUE TITLE
How stop preload when the player is pause/stop ?

### ISSUE THREAD

**Issue by SamuelPelletier** [cookpete/react-player#1083]
#### Current Behavior
When I pause/stop the player keep loading data.

#### Expected Behavior
I would like when I pause the player stop loading data.
Like `preload = "none"` before 2.0

#### Steps to Reproduce
1. Play something
2. Stop the player
3. Check on your browser network tool the data keep loading

#### Environment
- Browser:  Google Chrome
- Operating system: Every

#### Other Information
Issue previous version 2.0 :  #300 
Work well with HLS.js with `hlsPlayer.stopLoad()`

**Comment by SamuelPelletier** [comment]
Well, I find a solution but I am not sure is the good way.
I get the media audio and I do this : 
```
audio.src = '';
audio.load()
```

**Comment by cookpete** [comment]
I don't know if this is something that’s ReactPlayer's responsibility? Preload behaviour is entirely down to the browser. If you want to force browsers to stop preloading, I guess you'd have to just stop rendering a `ReactPlayer` (which I think is a cleaner equivalent to your example) and then use `seekTo` when you want to reload the video and start playing from a certain point.
