### ISSUE TITLE
Call for play/stop from Ref

### ISSUE THREAD

**Issue by sirshurak** [cookpete/react-player#1085]
Is there a possibility to create a function to call Pause and Play from a Ref of a ReactPlayer created by React.createRef() ?

Context:
The current problem is that I have a list of items inside a bootstrap carousel that each one contains a video. Then when I move from item 0 to item 1 the video from item 0 need to be stopped if played.
My first try was to created an array with "playing" state and then when moving foward and backwards on carousel the video would stop. But what was actually happening was that the video after going foward and backwards two times the video won't stop anymore. 
The solution I've found is to create a Ref of the video and call stopVideo() from player inside ReactPlayer, but this solution only works for Youtube.
`refPlayer.current.player.player.player.stopVideo();`

**Comment by cookpete** [comment]
You could use `refPlayer.current.player.player.pause()` if you want to pause all types of player (notice only two `player` in the chain) but this is a hacky way of doing things. 

The "proper" way would be to change the `playing` prop you are passing in to be `true` for the video being displayed and `false` for all others.
