### ISSUE TITLE
Cannot pause player for Vimeo video

### ISSUE THREAD

**Issue by scott0730** [cookpete/react-player#1087]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior

I've used a StyledComponent wrapper around ReactPlayer and a dedicated Play button controlled via setState. After clicking Play button on video unable to pause only on Vimeo.

#### Expected Behavior

Click on the video to pause it

#### Steps to Reproduce

1. Click on the video to play
2. Click the video again, unable to pause

#### Environment
- URL attempting to play: https://vimeo.com/259411563
- Browser: Chrome
- Operating system: OSX

**Comment by cookpete** [comment]
Vimeo videos cannot be paused on click unless you have `controls={true}`. 

You could add a transparent overlay `div` with a click handler to set `playing={false}` in the player.
