### ISSUE TITLE
If I enter a full youtube URL copied from the address bar then it doesn't play.

### ISSUE THREAD

**Issue by sambhav-gore** [cookpete/react-player#1088]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior

I have made a minimum reproduction here - https://codesandbox.io/s/react-player-youtube-wedji

If I enter a URL by directly copying from the browser, example: `https://www.youtube.com/watch?v=Qtb11P1FWnc&ab_channel=Coldplay` then it does not play.

Removing the `ab_channel` param makes it work.

However it does play correctly in the demo, so I am wondering how can I enable that in my app?

#### Expected Behavior

Directly copying the URL from youtube should work.

#### Steps to Reproduce

1. Please see the minimal reproduction at https://codesandbox.io/s/react-player-youtube-wedji

#### Environment
- URL attempting to play: https://www.youtube.com/watch?v=Qtb11P1FWnc&ab_channel=Coldplay
- Browser: Chrome
- Operating system: Tested on MacOS and Ubuntu (20.04)
- jsFiddle example: 

#### Other Information

Does play correctly in the demo.

**Comment by cookpete** [comment]
Good spot! The updated regex for parsing the `channel=` param is incorrectly picking up `ab_channel=` too.

**Comment by michelecocuccio** [comment]
@cookpete hello. Is there a plan to fix this soon? Do you have a time for the next release?

Thanks

**Comment by cookpete** [comment]
>Is there a plan to fix this soon? Do you have a time frame for the next release with this fix?

I have a fix. I’ll publish a release in the next couple of days.

**Comment by michelecocuccio** [comment]
Thanks for the prompt reply @cookpete. Keep the good work 👍

**Comment by arjdesign** [comment]
I am still getting this issue. I was wondering if it has been fixed?
