### ISSUE TITLE
How can I remove border/outline around video player

### ISSUE THREAD

**Issue by RohitKumar-200** [cookpete/react-player#1089]
#### Help needed
A border is shown when I focus on player (when I click on play button). I am playing a mp4 file with player. How can I remove that border/outline. I tried adding inline css, but nothing worked.
![border](https://user-images.githubusercontent.com/55583961/99986747-98d03d00-2dd5-11eb-9008-64581aee1d08.png)
In screenshot above, a white colored unwanted border appears.

**Comment by harshithdwivedi** [comment]
+1, any update on this?

**Comment by cookpete** [comment]
This is just the browser adding an `outline` on focus for accessibility. To remove it just use:
```css
video {
  outline: 0;
}
```

Or use the config prop to apply styles inline:

```js
config={{ attributes: { style: { outline: 0 }}}}
```
