### ISSUE TITLE
Add support for Facebook videos

### ISSUE THREAD

**Issue by danmo** [CookPete/react-player#109]
Hi, seems like live facebook video links aren't working. Any idea on how to overcome this ?

**Comment by CookPete** [comment]
Facebook videos aren't currently supported, but it looks possible using the [embedded video player API](https://developers.facebook.com/docs/plugins/embedded-video-player/api). I'll repurpose this issue to add support for Facebook videos.

**Comment by d4tocchini** [comment]
any updates/progress on this one?

**Comment by CookPete** [comment]
I have attempted it but the result was very buggy, especially when trying to switch from one FB video to another. Maybe _some_ support is better than none, so I'll consider adding basic support and a note that some bugs remain with the API.
