### ISSUE TITLE
Blob URL not playing

### ISSUE THREAD

**Issue by jd-val** [cookpete/react-player#1091]
I am attempting to play a video file that has been retrieved from a backend server in my project. In the code I receive the file and convert to a Blob. I set this blob as a state variable and attempt to play it. The video player loads and the request comes back with a 206 and the video does not play. Code for retrieving the video and the backend endpoint are below. Can someone help me out with this?

```
useEffect(() => {
        const doStuff = async () => {
            const myToken = await getTokenSilently();
            setToken(myToken);
            getSelectedVideo();
        };
        doStuff();
        //
        // eslint-disable-next-line
    }, []);

const getSelectedVideo = async () => {
        try {
            const response = await axios.get(`/api/videos/${videoID}`, {
                headers: {
                    Authorization: `Bearer ${token}`
                }
            });

            const video = new Blob([response.data], { type: "video/mp4" });
            const url = window.URL.createObjectURL(video);
            setVideoFilePath(url);
            setIsLoaded(true);
        } catch (error) {
            console.error("getSelectedVideo caught error:" + error);
        }
    };

    return (
        <div className="video-player">
            {/*If video loads correctly, show video. Else, display error message*/}
            {!isLoaded && <p>Loading...</p>}
            {isLoaded && <ReactPlayer controls url={videoFilePath} />}
        </div>
    );
};
```

backend endpoint code for video:

```
app.get("/api/videos/:videoId", authMiddleware, async (req, res) => {
    res.sendFile("/videos/sample-mp4-file.mp4", { root: __dirname });
});
```

**Comment by cookpete** [comment]
This seems like a problem with your server implementation. If you are using `res.sendFile` I'm not sure why you are getting a 206, which implies partial content for streaming, rather than a full file being downloaded.

I'm going to close this off as it's a problem with the server response and the HTML5 video player, and not ReactPlayer specifically. Hopefully a relevant google search can help you: https://www.google.co.uk/search?q=html5+video+blob+206
