### ISSUE TITLE
Customize volume in TS.

### ISSUE THREAD

**Issue by farmer911** [cookpete/react-player#1092]
Hi, I'm got the problem when was coding volume control range in TS.
The interface volume of React-player is number between 0 to 1, so i can not customize the range input make like the default. Can you help me to find it out solution.

**Comment by afzaalahmad** [comment]
@farmer911 your problem statement is inefficient to determine the problem. It will be helpful if you can share the piece of code.

**Comment by cookpete** [comment]
The range input can return any value you like, as long as you parse it into a decimal between 0 and 1. For example, if the input returns a string like `"100"`, just do `parseInt(value) / 100` before passing it in as `volume`.
