### ISSUE TITLE
React Player does not display Twitch videos inside an iFrame

### ISSUE THREAD

**Issue by ziyak97** [cookpete/react-player#1093]
I have react player embedded inside an iFrame. All urls I tried worked fine except that of Twitch. I get the following error.

player.twitch.tv refused to connect. 

<img width="695" alt="Screen Shot 2020-11-26 at 7 12 15 PM" src="https://user-images.githubusercontent.com/53836911/100357999-80516400-301b-11eb-9806-befb052c7ad2.png">

If I use React player outside of my iframe Twitch works fine. 

Twitch url used - https://www.twitch.tv/x2twins

**Comment by cookpete** [comment]
Is it possibly the new CSP restrictions kicking in? You may need to add `parent` to your `config.options` object.

https://discuss.dev.twitch.tv/t/twitch-embedded-player-updates-in-2020/23956

See also: https://github.com/cookpete/react-player/issues/904
