### ISSUE TITLE
Configurable player import to reduce javascript bundñe impact

### ISSUE THREAD

**Issue by SalahAdDin** [cookpete/react-player#1095]
Hi, this is more like a suggestion than an Issue; I'm using this player in my portfolio and i get this very good.

Looking at my web vitals test i get it has a heavier impact on the bundle size which could be avoided if we could configure which players would want to use in our site:
![image](https://user-images.githubusercontent.com/5034215/100516841-bd426580-3197-11eb-9d2f-ef3750a1c832.png)

Right now, I'm using the global player because most of my videos are from Cloudinary, but maybe in the future, i could embed also youtube videos, for example.

In that case, how could we use the player for both youtube videos and Cloudinary videos? instead to import all players, just importing two or three?

Maybe i'm understanding the player wrong.

Thank you.

**Comment by cookpete** [comment]
Read through the [usage](https://github.com/cookpete/react-player#usage) section of the readme. It depends on your implementation but you should be able to use `react-player/lazy` to only load in relevant chunks based on the URL you pass in. Your bundle will still contain the chunks for every player, but only the ones you need will be loaded at runtime.

Or, if you are only playing youtube, use `react-player/youtube`.

**Comment by cookpete** [comment]
Worth noting that I am planning a rewrite to try and reduce the overall bundle size.

**Comment by ScottAgirs** [comment]
@SalahAdDin would u happen to have some shareable demo for how you used react-player with Cloudinary?

**Comment by SalahAdDin** [comment]
> @SalahAdDin would u happen to have some shareable demo for how you used react-player with Cloudinary?

Actually, I didn't publish any video on my portfolio yet, but the times i tested it, it was working cool.
