### ISSUE TITLE
How to start at a specified time in vimeo

### ISSUE THREAD

**Issue by manishsharma004** [cookpete/react-player#1097]
#### Current Behavior
Unable to start vimeo video at specified time.

#### Expected Behavior
Vimeo iframe embed supports unofficial time format(`#t=32` ). Should be able to use this in react-player.

#### Other Information
Vimeo's oembed doesn't list this `#t=` support while people have shared this over multiple forums. Have tried the 
```jsx
<ReactPlayer
    playerOptions={{
        t: 32
    }}
/>
```
but it didn't work.

Not sure if it's possible without tinkering the Vimeo's Player SDK.

Edit: Thank you for this player.

**Comment by manishsharma004** [comment]
FYI #115  doesn't help in this case.

**Comment by afzaalahmad** [comment]
@manishsharma004 Alternatively just wait for `onReady` and then call `seekTo` on the player instance. 

This approach mentioned in #115 is working absolutely fine in [this fiddle](https://jsfiddle.net/8hbf3a74/).
