### ISSUE TITLE
Media player controls

### ISSUE THREAD

**Issue by oyeanuj** [CookPete/react-player#11]
Hi @CookPete! I noticed in the example that the file players didn't have any standard controls. Is there a config option to show or hide them? If not, what is the best way you recommend to have player controls show up?

Thanks for this library!

**Comment by CookPete** [comment]
Hi @oyeanuj. `ReactPlayer` itself is deliberately as stateless as possible, and no more complex than it needs to be. It gives you the freedom to control it however you want, not forcing you down a certain path. I actually wrote it mainly for playing audio from various sources (and not actually rendering anything visible). The video element is just an added bonus.

See [App.js](https://github.com/CookPete/react-player/blob/master/src/App.js) for a basic example of controls for the player. The logic for `playing/volume/etc` is deliberately managed outside the component and fed in via props.

Perhaps `App.js` could be developed into a bit more of a robust example, with better styles and iconography.

**Comment by CookPete** [comment]
I'll close this now considering the updated [demo file](https://github.com/CookPete/react-player/blob/master/src/demo/App.js) is a pretty good example of how to control the player.
