### ISSUE TITLE
Do setSindId on React-Player

### ISSUE THREAD

**Issue by MatanYemini** [cookpete/react-player#1100]
Hi Everyone, 

#### Current Behavior
Currently, when playing a video clip from youtube with this package, the sound is being played on my default speakers.
In my app, you can choose a different speaker (audio output) than the default.
As a result, when playing the video, it sometimes uses different speakers.

#### Expected Behavior
Give me an option to define the sinkId

#### Steps to Reproduce
Just play a clip while having more than one speaker connected, and choose the not default speaker to the mission

#### Environment
Chrome  (any version from the past 1.5 years)

**Comment by cookpete** [comment]
> Give me an option to define the sinkId

Until the [Youtube player API](https://developers.google.com/youtube/iframe_api_reference) supports this, there’s nothing that ReactPlayer can do here.
