### ISSUE TITLE
Cannot get the player options using youtube url as source + some player vars are not working

### ISSUE THREAD

**Issue by MatanYemini** [cookpete/react-player#1101]
#### Current Behavior
Unable to get the player.getOptions() from the youtube player

My final goal is to detect whether or not closed captions are on so I will be able to sync it.
I don't see this option from the player that I have extract using getInternalPlayer() method
I see that it is enabled on the youtube API

I am actually trying to use some player vars such as:
```
                                        iv_load_policy: 3,
                                        modestbranding: 1,
                                        rel: 1,

```

without a success.

#### Expected Behavior
Get the player options + player vars to work

#### Steps to Reproduce
Just try to get into the options of a youtube player

my code:
```
<ReactPlayer
                            id={"player"}
                            ref={youtubePlayerElement}
                            className={classes.youtubePlayer}
                            width="100%"
                            height="100%"
                            url={youtubeUrl}
                            pip={pip}
                            playing={playing}
                            controls={canControl}
                            light={light}
                            loop={loop}
                            playbackRate={playbackRate}
                            volume={volume}
                            config={{
                                youtube: {
                                    playerVars: {
                                        origin: `*`,
                                        iv_load_policy: 3,
                                        modestbranding: 1,
                                        rel: 1,
                                    },
                                },
                            }}
                            muted={muted}
                            onReady={onReady}
                            onEnded={handleEnded}
                            onError={(e) => console.log("onError", e)}
                        />


```
#### Environment
Latest Chrome

Thanks!

**Comment by cookpete** [comment]
I'm not sure `getOptions` does what you would like. It looks like it just returns the options that _can be set_ via the API. It does not seem to return things like "does the player have captions currently turned on". Even `getOption("captions", "track")` doesn't seem to return what you need, although it might be a good starting point for you:

https://codesandbox.io/s/sharp-ride-lveyh
