### ISSUE TITLE
How to access iframe of embedded video

### ISSUE THREAD

**Issue by KristianLonergan** [cookpete/react-player#1102]
Help needed!

I have went through the documentation and issues and can't seem to find anything about being able to pass props to the iframe of youtube video  (or any embedded video).

I simply want to access the iframe so I can add a style directly onto the iframe (border-radius: 5xp) to make the video look a lot more smoother within my UI

**Comment by cookpete** [comment]
Why not just add `border-radius` and `overflow: hidden` on the top level ReactPlayer element? 
eg https://jsfiddle.net/4L0vu2z8/

If you _really_ wanted to access the iframe, you could do 

```js
<ReactPlayer
  url='https://www.youtube.com/watch?v=hDkuUZ3F1GU'
  onReady={p => {
    const player = p.getInternalPlayer()
    console.log(player.f)
  }}
/>
```

But this is messing with youtube player internals and isn't recommended.
