### ISSUE TITLE
Twitch player is not rendered when passing livestream / channel url

### ISSUE THREAD

**Issue by shaohaolin** [cookpete/react-player#1103]
#### Current Behavior
Example URL: https://player.twitch.tv/?channel=blastpremier&parent=localhost
When passes the above URL in ReactPlayer, the twitch player is not rendered. 
`<ReactPlayer url={playerSource} controls width="100%" height="100%" />`

It seems it renders as a normal video src.
![image](https://user-images.githubusercontent.com/6677092/101673696-5a10c880-3a0c-11eb-838d-f947395afe9f.png)

#### Expected Behavior

Should render twitch player in an iframe.

#### Steps to Reproduce

1. Copy the example URL: https://player.twitch.tv/?channel=blastpremier&parent=localhost
2. Paste in the demo page in the custom URL.

#### Environment
- URL attempting to play: https://player.twitch.tv/?channel=blastpremier&parent=localhost
- Browser: any

**Comment by cookpete** [comment]
@shaohaolin Where did you get that URL from? The pattern ReactPlayer looks for is `twitch.tv/[channel]` so a URL like https://twitch.tv/blastpremier would work.

**Comment by shaohaolin** [comment]
I was based on the twitch embedded API sample. 

```
<iframe
    src="https://player.twitch.tv/?channel=dallas&parent=streamernews.example.com&muted=true"
    height="720"
    width="1280"
    frameborder="0"
    scrolling="no"
    allowfullscreen="true">
</iframe>
```
