### ISSUE TITLE
Question on API: `file.forceHLS` does not work as expected

### ISSUE THREAD

**Issue by lvnam96** [cookpete/react-player#1105]
#### Current Behavior
Using option `file.forceHLS` does not force `react-player/file` to use `hls.js` to fetch the file if file's URI does not pass the file extension checking by `ReactPlayer.canPlay()`.

#### Expected Behavior
Using this option will force `react-player/file` to use `hls.js` no matter what result returned from `ReactPlayer.canPlay()`.

#### Steps to Reproduce
Use any URI that does not end with `*.m3u8`.

#### Environment
Any

#### Other Information
I have an overview at [`getActivePlayer()`](https://github.com/cookpete/react-player/blob/master/src/ReactPlayer.js#L108) and [`shouldUseHLS()`](https://github.com/cookpete/react-player/blob/master/src/players/FilePlayer.js#L128-L130) and still dont get it. If this has been done on purpose, what is the real benefit of this `file.forceHLS` option?

**Comment by cookpete** [comment]
`forceHLS` was designed for use with the root `react-player` import, which falls back to `FilePlayer` if the URL isn't recognised. With the amount of features that have been added over time, some combinations will cause weird situations like this.

If you are using `react-player/file` and `forceHLS` there is probably no point using ReactPlayer. You might as well just use `hls.js` directly?

**Comment by lvnam96** [comment]
> `forceHLS` was designed for use with the root `react-player` import

Same as I thought. The docs confused me 🙈 

> If you are using `react-player/file` and `forceHLS` there is probably no point using ReactPlayer. You might as well just use `hls.js` directly?

In the past, we needed a common stable API from your library to provide the playing feature ASAP while we were making decision on which media format will fit our case. We were in hurry those days.
Now we are tweaking a few configs. One of them is changing the file's name & that's why I faced this issue. Anyway we decide to keep the file's extension as `.m3u8` so everything is good to go.

Thanks for your answer! Your lib saves us a lot of time!
