### ISSUE TITLE
How can I make the player start from a specific time (File)?  Thanks =)

### ISSUE THREAD

**Issue by ramersonrodrigues** [cookpete/react-player#1108]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Steps to Reproduce

1.
1.
1.

#### Environment
- URL attempting to play: 
- Browser: 
- Operating system: 
- jsFiddle example: https://jsfiddle.net/sv5x3ug1

**Comment by cookpete** [comment]
Try this: https://stackoverflow.com/a/25235578
