### ISSUE TITLE
Change volume event

### ISSUE THREAD

**Issue by dan89farhan** [cookpete/react-player#1109]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior

I am using react-player but not found any event related to volume change
#### Expected Behavior

is there any event available for volume change?

Thank you for your help
@cookpete

**Comment by cookpete** [comment]
ReactPlayer can only support what the player APIs support. Not many of the supported URL types have a volume change event so it would be adding a prop that doesn't work with most URLs, which is not ideal.

The `config` prop or `getInternalPlayer` method will let you use some advanced functionality for the specific player you are using. If the player supports volume change events then there should be a way for you to hook in.
