### ISSUE TITLE
Use srt format as subtitle 

### ISSUE THREAD

**Issue by riky1998** [cookpete/react-player#1110]
hi, In the readme section I just see vtt format in the subtitle, can I use srt format as a subtitle? I have tried srt format and it's not working, If I Can't use srt format, is there any way to play srt format in react-player?

**Comment by cookpete** [comment]
SRT files are not supported by HTML5 media, but can be converted: https://stackoverflow.com/questions/26968759/does-html5-video-support-srt-texttrack

**Comment by Angelk90** [comment]
Hi @cookpete , I tried to add subtitles as per example, but it is not working for me.
Can you give me a hand?

Link: https://codesandbox.io/s/exciting-sinoussi-hyd8h?file=/src/App.js
