### ISSUE TITLE
ios can not play media

### ISSUE THREAD

**Issue by benamm** [cookpete/react-player#1112]
I tried to play the video with your library. But this does not happen in iOS

ReactPlayer.canPlay(url) return false :)
 

<img width="438" alt="Screen Shot 1399-10-07 at 15 51 45" src="https://user-images.githubusercontent.com/40948849/103170721-bf154c80-485b-11eb-9bc8-e819a8abcad5.png">

**Comment by cookpete** [comment]
What URL are you trying to play? It could be that it’s just [not supported](https://en.wikipedia.org/wiki/HTML5_video#Browser_support) by iOS Safari.
