### ISSUE TITLE
Purple screen showing up for twitch livestreams

### ISSUE THREAD

**Issue by jeremygottfried** [cookpete/react-player#1114]
#### Current Behavior
This screen shows up for Twitch even if I add the parent domains in the options. It also happens in an incognito window with no adblocker.
I added every parent domain I could think of, but it still happens. I haven't seen this message before, so I have a feeling it is happening now because this is a high traffic livestream. The purple screen goes away after about 30 seconds, but then reappears intermittently.

<img width="1261" alt="Screen Shot 2020-12-30 at 6 52 14 PM" src="https://user-images.githubusercontent.com/34523280/103387250-b4172200-4ad0-11eb-88c2-f8fbca7e0b74.png">

#### Steps to Reproduce
```js
<ReactPlayer
  playing
  controls
  url={url}
  width="100%"
  height={`${height}px`}
  config={{
   twitch: {
     options: {
       parent: ["mysite.com", "www.mysite.com", "subdomain.mysite.com", "www.subdomain.mysite.com"]
     },
   },
 }}
/>
```

It seems to work in an incognito window, but I'm not sure because this issue happens unpredictably on an intermittent basis. I already disabled adblocker but it's still happening.

#### Environment
- URL attempting to play: https://twitch.tv/abracadabra
- Browser: Chrome, Safari, all
- Operating system: macOS Catalina 10.15.1

**Comment by cookpete** [comment]
As far as I can tell this is known as Twitch's "purple screen of death" and there's nothing that can be done in this library to combat it. A quick google search provides a few solutions that involve a browser extension.
