### ISSUE TITLE
A way to hide the youtube player ?

### ISSUE THREAD

**Issue by miyokidev** [cookpete/react-player#1116]
I'm looking for a way to play youtube sounds/musics in background that's why I wanted to know if there is a way to hide the youtube player and controls it only with external buttons etc.

**Comment by AlexRypun** [comment]
Just hide container with css `display: none;`

**Comment by cookpete** [comment]
Yeah use `display: none` or maybe `opacity: 0.00001; pointer-events: none;` because some browsers won't play videos that aren't "visible" to the user.

Note that on some browsers you may need user interaction before you can play videos.
