### ISSUE TITLE
Dailymotion videos do not play with react-player on some old browsers

### ISSUE THREAD

**Issue by joaopa00** [cookpete/react-player#1117]
When I want to play a video on dailymotion, I receive the message
"please udate your internet browser or try using a different one"

It happens with any video.

React-Player should be able to fulfill the requirements of dailymotion.
It happens with the asean browser of my connected tv. With native dailymotion player, videos do not play neither.

In newest chrome or firefox, no problem.

**Comment by cookpete** [comment]
This is something you need to take up with the DailyMotion player API guys: https://developer.dailymotion.com/player

They have a contact/support page here: https://developer.dailymotion.com/support/
