### ISSUE TITLE
Supported video extensions?

### ISSUE THREAD

**Issue by mjsisley** [CookPete/react-player#112]
What video extensions are supposed to be supported?
I am getting the following behavior currently (video stored on s3).

Fully working: mp4, mkv
Only Audio plays: mov
Nothing plays: 3gp, flv

The README references this: https://github.com/CookPete/react-player/blob/master/src/players/FilePlayer.js#L5-L6, but the VIDEO_EXTENSIONS have been removed from the file.

**Comment by mjsisley** [comment]
This was tested in Chrome. This is an issue with the differences in browsers.

**Comment by CookPete** [comment]
Video extensions were removed when the logic was changed to fall back to FilePlayer if no other players can play a given URL. If a file doesn't play it is because the browser doesn't support it natively. See https://github.com/CookPete/react-player/issues/86 for more info.
