### ISSUE TITLE
tabIndex is not configurable

### ISSUE THREAD

**Issue by Arnei** [cookpete/react-player#1124]
Currently the player has a hardcoded tabIndex of 0. I would like to able to change between 0 and 1 instead.

In my current setup, I have multiple ReactPlayers which are controlled through centralized controls, i.e. one play button for all players. Since users cannot interact directly with the players, it would be nice if users could not focus them, in order to avoid confusion for users that rely on keyboard navigation.

**Comment by cookpete** [comment]
> Currently the player has a hardcoded tabIndex of 0.

What specific player are you referring to here? Every different type of URL loads a different player API, which has a different way of loading/rendering a video, usually in an iframe that we have very little control over.

Or do you mean the light mode preview component, which had `tabIndex={0}` added in https://github.com/cookpete/react-player/issues/878 ?

**Comment by Arnei** [comment]
Good point. I am referring to the default player (the player that is used when you provide a video from a random URL). It is absolutely possible that I confused the default player with the light mode preview component when trying to figure out if `tabIndex` was hardcoded.

**Comment by cookpete** [comment]
What URL are you playing? The control you have over what is rendered depends on the type of player.

**Comment by Arnei** [comment]
URLs from a content storage system, for example https://legacy.opencast.org/static/mh_default_org/internal/ID-dual-stream-demo/cba876fc-6bf2-4e6e-bbcf-d6833eb37bf9/dualstream_presenter.mp4

**Comment by cookpete** [comment]
Ah, in that case you can just use `config.attributes` to pass anything to the `<video>` element:

```jsx
<ReactPlayer
  src='file.mp4'
  config={{ attributes: { tabIndex: '-1' }}
/>

**Comment by Arnei** [comment]
Damn, now I'm embarassed I didn't figure that out. Thanks!

**Comment by Arnei** [comment]
Damn, now I'm embarassed I didn't figure that out. Thanks!
