### ISSUE TITLE
Support Wistia custom player controls

### ISSUE THREAD

**Issue by dinhkellie** [cookpete/react-player#1125]
Is there a way to use custom wistia controls with react-player? Using this as a guide for Wistia player controls: [https://wistia.com/support/developers/player-controls-framework](https://wistia.com/support/developers/player-controls-framework) after defining the component, you have to call `Wistia.defineControl(MyComponent);` 

If I am using react-player in my app and passing in a Wistia url, is there support for built-in Wistia functions like this? If so, it would help to have this in the Readme!

**Comment by cookpete** [comment]
As of `v2.8.1` you can use `<ReactPlayer config={{ customControls: [MyCustomControl] }} />`
