### ISSUE TITLE
How to stop playing player when i close the modal parent of it?

### ISSUE THREAD

**Issue by rico000041** [cookpete/react-player#1128]
the player still playing in the background even the component is not displaying

1. Open Modal with player in it
2. Play
3. Close the modal
4. The player Still playing in the background 

Thanks

**Comment by cookpete** [comment]
This depends entirely on your implementation. If your modal system isn't unmounting the player component, your video will continue playing unless you change the `playing` prop to `false`.

**Comment by CalvinJamesHeath** [comment]
Even If playing is set to false by state, it wont stop sometimes. The bug occurs when you scroll up and down real fast with an inView listener which updates correctly but ReactPlayer keeps going.
