### ISSUE TITLE
Subtitles sporadically not showing up

### ISSUE THREAD

**Issue by bureson** [cookpete/react-player#1129]
#### Current Behavior

We started observing an interesting issue recently. When we let the video player sit around for some time, the subtitles don't show up. But if we hit the play button immediately after loading the page, the subtitles show up perfectly every time. We don't quite understand why exactly is this happening and there are no obvious clues in the console or network tab.

#### Expected Behavior

We would expect the subtitles to show up every time.

#### Steps to Reproduce

1. Open this sandbox: https://codesandbox.io/s/young-surf-35kcc?file=/src/App.js:650-766
1. Hit the play button more than 15 seconds after the page has loaded
1. The subtitles don't show up 
* I was able to reproduce this constantly yesterday in the afternoon, but now I'm only able to reproduce it 1 in 10 times
* Reloading the Sandbox inline browser is not as effective as reloading the browser tab
* When not able to reproduce it immediately, try changing wait times or try losing focus on the active browser tab 
* Sometimes waiting even more than a minute does the trick
* When after hitting the play button the button switches its position to pause, then play and then pause again all by itself, the subtitles always work

#### Environment
- URL attempting to play: https://res.cloudinary.com/triggerz-eu-cld/video/upload/sp_4k/v1605597336/HabitDrivers/Videos/HabitDrivers_for_Teams.m3u8
- Browser: Chrome 87
- Operating system: Windows 10
- jsFiddle example: https://codesandbox.io/s/young-surf-35kcc?file=/src/App.js:650-766

#### Other Information

I know that this is a very tricky and annoying bug to even reproduce, not even talking about debugging, but we were able to reproduce it on multiple devices and I would be more than happy if you managed to reproduce it too and give us at least an opinion about where might this be coming from.

**Comment by cookpete** [comment]
I managed to make it happen once, on my second load of the example, and then never again.

I have absolutely no idea why this would happen. All I can think is that `hls.js` is doing something strange with subtitle loading. I would maybe search for issues at https://github.com/video-dev/hls.js/issues but I'm not sure what ReactPlayer can do to try and solve this.

**Comment by bureson** [comment]
@cookpete thanks for the reply. I opened another issue in the HLS project and refed this issue. I'm closing this one for now.

**Comment by robwalch** [comment]
hls.js only loads captions in the HLS manifest or media. https://res.cloudinary.com/triggerz-eu-cld/video/upload/sp_4k/v1605597336/HabitDrivers/Videos/HabitDrivers_for_Teams.m3u8 on its own contains no captions.
