### ISSUE TITLE
react-player not working with react server side rendering 

### ISSUE THREAD

**Issue by danmo** [CookPete/react-player#113]
Hi, trying to render server side a simple component that uses react-player and it doesn't seem to be working.

Route handler looks like this:

```
const ServerPost = (props) => (
          <ReactPlayer url='https://www.youtube.com/watch?v=ysz5S6PUM-U' playing />
        );
        var html = ReactDOMServer.renderToString(
          React.createElement(ServerPost, post),
        );
        reply(html);
```

DOM element looks like this: 
![image](https://cloud.githubusercontent.com/assets/3957234/19386904/ab2ec0c6-921f-11e6-8353-aefd8e84b690.png)

```
<div style="width:640px;height:360px;" data-reactroot="" data-reactid="1" data-react-checksum="-1272364945">
   <div style="height:100%;display:block;" data-reactid="2">
      <div id="youtube-player-0" data-reactid="3"></div>
   </div>
</div>
```

**Comment by CookPete** [comment]
What do you expect to be rendered? YouTube videos use the [iframe API](https://developers.google.com/youtube/iframe_api_reference), which is loaded asynchronously on the client side, so there is nothing else to render on the server.

**Comment by danmo** [comment]
Hi @CookPete , shouldn't the iframe be added to the generated html then ?

**Comment by CookPete** [comment]
The loading of the SDK and iframe render happens on `componentDidMount` (ie on the client, not on the server). The YouTube SDK is loaded in using `fetch` and is deliberately built to work with browsers, not in a node environment.

**Comment by CookPete** [comment]
Pretty much everything in this library relies on client-side scripts loading _after_ components are mounted, so I'll close this unless there is a solid requirement (and expected behaviour) for server side rendering.

**Comment by j4-m** [comment]
Hey @cookpete I know this is a reeeeeeally old issue however I do think that a lack of basic SSR is a problem. For sites which use the video thumbnail for their LCP then CSR of the `background-image` is going to result in massive performance problem. Would you be willing to accept a PR which adds SSR support for the preview\thumbnail markup?
