### ISSUE TITLE
When light prop is set to true for multiple YouTube videos some of the thumbnail images are not loaded

### ISSUE THREAD

**Issue by pedramp20** [cookpete/react-player#1130]
#### Current Behavior
There is a grid of 3x3 react players with their urls pointing to some YouTube videos. The "**light**" prop is set to true for all of them and they are all dynamically added to the their parent in a map, so everything is identical in all of them beside the url. but some the videos' thumbnail images are not loaded (the same videos).  The videos load just fine on click.

#### Expected Behavior
All the thumbnail images to be loaded on start

**Comment by pedramp20** [comment]
Anyone? Any ideas?

**Comment by faran4engg** [comment]
> Anyone? Any ideas?

I am also facing the same issue !

**Comment by flobby** [comment]
I can confirm this

**Comment by Freeride91** [comment]
Same at me!

**Comment by cookpete** [comment]
I’m using noembed to show a thumbnail before loading the player. They have a demo page here: https://noembed.com/demo

Feel free to try the URLs that are failing and see what happens. Some youtube videos return a `403 Forbidden` so that might be what’s happening here.

Or check the URL yourself, eg https://noembed.com/embed?url=https://www.youtube.com/watch?v=tRFOjLIl7G0

**Comment by AndriusCvetkovas** [comment]
Same here. Videos that get 403 returned from noembed don't have their thumbnails showing.

**Comment by ChrisB9** [comment]
Same for me.
Interestingly though is, that it does happen with different videos at different times (or the same video list accessed locally or on a server).

**Comment by cookpete** [comment]
I'll close this off unless anyone can suggest an alternative to noembed for easily getting a thumbnail for any given URL (not just youtube). @ChrisB9's solution is solid if you are using youtube and have the ID handy.

**Comment by onurtahmaz** [comment]
Thanks for the reply! 

Nope, there is no console error. The interesting part is it was working 3 or 4 weeks ago. 

Last question: Do you think there is a way to reduce the CPU usage when I use react-player without the light mode? 

Thanks again for your time!
