### ISSUE TITLE
Hls.m3u8 file works on the demo page but not in my code

### ISSUE THREAD

**Issue by mekkiamiri** [cookpete/react-player#1132]
#### Current Behavior

While adding the ReactPlayer in my app, the file "http://cdn.muse.ai/w/123a70ef1287f5dfcd3f3da3a3aee038ee377b1a119b3defd63af4637d0dfc3f/videos/hls.m3u8" cannot be loaded.
However, it works on the demo page: https://cookpete.com/react-player/
This is my code

```jsx
import React, { Component } from 'react';
import ReactPlayer from 'react-player';



type Props = {
    url: string
}

const ResponsivePlayer =  (props: Props) => (
    <div className='player-wrapper'>
        <ReactPlayer
            className='react-player'
            url='http://cdn.muse.ai/w/123a70ef1287f5dfcd3f3da3a3aee038ee377b1a119b3defd63af4637d0dfc3f/videos/hls.m3u8'
            width='100%'
            height='100%'
            controls
          
        />
  </div>
  );

export default ResponsivePlayer;
```

#### Steps to Reproduce

1. Test the url in the demo page: it should work
2. Test the same url with my code source: video should not be loaded

#### Environment
- URL attempting to play: http://cdn.muse.ai/w/123a70ef1287f5dfcd3f3da3a3aee038ee377b1a119b3defd63af4637d0dfc3f/videos/hls.m3u8
- Browser: Chrome
- Operating system: ArchLinux
- jsFiddle example:

**Comment by cookpete** [comment]
Is it because you are serving your app from `https` and the stream URL is `http`? Many browsers now block requests between the two protocols.

**Comment by mekkiamiri** [comment]
thanks for the reply: it works with https

**Comment by mekkiamiri** [comment]
resolved
