### ISSUE TITLE
How can you add border radius to the video player?

### ISSUE THREAD

**Issue by jake-chambers** [cookpete/react-player#1134]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior

```
      <ReactPlayer
          style='border-radius:16px'
          //style={{borderRadius:16}}
      />

Neither work
```
#### Expected Behavior
Why doesnt it work

#### Environment
- URL attempting to play: Local video
- Browser: Chrome and Safari
- Operating system: MacOS

**Comment by cookpete** [comment]
You need `overflow: hidden` as well.
