### ISSUE TITLE
How to hide or disable the full-screen button on iPhone Safari

### ISSUE THREAD

**Issue by topdev423** [cookpete/react-player#1139]
Hi @cookpete 
I've tried to disable the full-screen button but it's not working on iPhone safari.

#### Current Behavior
iPhone still shows the full-screen button.

![File](https://user-images.githubusercontent.com/20238035/104955710-7abf2d00-597f-11eb-9362-f88c5b8c7a54.jpg)

#### Expected Behavior
It should be disabled like Desktop or Android.

![download](https://user-images.githubusercontent.com/20238035/104956223-8b23d780-5980-11eb-97f6-7ddc7ea319d4.png)

#### Steps to Reproduce
I've tried to fix it by using this config and it works well on  **desktop** and **Android** but iPhone doesn't work.
`
<ReactPlayer
  config={{ file: { attributes: {
     controlsList: 'nodownload nofullscreen',
     disablePictureInPicture: true
  }}}}
/>
`

#### Environment
iPhone 6, 7, 8, 11

**Comment by cookpete** [comment]
I don’t think iOS cares about implementing `controlslist` properly. They have chosen to let users fullscreen videos regardless. 

Even MDN says it’s [not supported](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/controlsList#browser_compatibility) by iOS Safari.
