### ISSUE TITLE
Not able to play YouTube video - "error message": "The caller does not have permission"

### ISSUE THREAD

**Issue by kangbojk** [cookpete/react-player#1140]
#### Current Behavior

YouTube player not playing video. It worked months ago, but now it shows black screen with error code.

#### Expected Behavior

Should play video properly.

#### Steps to Reproduce

1. Go to https://cookpete.com/react-player/ and play demo YouTube video
2. Press F12 and find the POST request, it shows **"message": "The caller does not have permission"**
![react player YT fail](https://user-images.githubusercontent.com/11307216/104986027-2aae9c00-5a4d-11eb-9b95-bd0691cf1348.png)

#### Environment
- URL attempting to play: https://cookpete.com/react-player/
- Browser: Chrome
- Operating system: Windows

#### Other Information

I suspect there is **policy changed in YouTube API**, most of the sites I visited these days produce broken YT videos.

**Comment by cookpete** [comment]
This sounds very specific to your network, and nothing that I can fix in this library. The demo page is working fine for me (and I presume for others too).

**Comment by kangbojk** [comment]
I see. Probably because of AdBlock.
