### ISSUE TITLE
Multi source in multi url

### ISSUE THREAD

**Issue by jclepin** [cookpete/react-player#1147]
Hi,

#### Current Behavior
Mixed youtube, dailymotion, soundcloud urls. The player don't appear.

#### Expected Behavior
Would it be possible to mixe sources in the url array ?

#### Example
url={[
                  "https://www.youtube.com/watch?v=oUFJJNQGwhk",
                  "https://soundcloud.com/bgrz_music/aya-nakamura-feat-stormzy-plus-jamais-bgrz-kompa-remix-1",
                  "https://www.dailymotion.com/video/x7yt6x8",
                  "https://www.youtube.com/watch?v=jNgP6d9HraI",
                  "https://www.youtube.com/watch?v=ysz5S6PUM-U",
                ]}

**Comment by cookpete** [comment]
Arrays of URLs only work for Youtube URLs, as it just proxies the built-in playlist function.

Also see https://github.com/cookpete/react-player/issues/1099#issuecomment-741646073
