### ISSUE TITLE
[Youtube] Video start time

### ISSUE THREAD

**Issue by marcuscaum** [CookPete/react-player#115]
There is a way to set video start time?

**Comment by CookPete** [comment]
You can use youtube's start time parameter:

```js
<ReactPlayer url='https://youtu.be/qv6UVOQ0F44?t=33' />
```

You can use `t` or `start`, you can also use the `m` and `s` format:

```js
<ReactPlayer url='https://youtu.be/qv6UVOQ0F44?start=1m33s' />
```

or pass a `start` [player param](https://developers.google.com/youtube/player_parameters#start):

```js
<ReactPlayer
  url='https://youtu.be/qv6UVOQ0F44'
  youtubeConfig={{
    playerVars: {
      start: 33
    }
  }}
/>

**Comment by againksy** [comment]
@CookPete how can i set such params not for youtube but for any other source?

**Comment by CookPete** [comment]
@againksy For players that support start params, it is usually a case of passing in the start parameter into the `config` prop. The exact config to use depends on what player you are using, but there is a list of config options [here](https://github.com/CookPete/react-player#config-prop) and a list of the APIs used [here](https://github.com/CookPete/react-player#supported-media).

Alternatively just wait for `onReady` and then call `seekTo` on the player instance.
