### ISSUE TITLE
React Playing is playing another video other than the requested video

### ISSUE THREAD

**Issue by AmmarMohamadIsmaeel** [cookpete/react-player#1150]
#### Current Behavior
React player is playing another video however the image of the light prop is correct

#### Expected Behavior
When I click on the play button over the image of the light, the react player should open the requested video but it is opening another video

#### My code
```
<ReactPlayer
                className='react-player'
                url={"https://youtu.be/W-jvyGyEifQ?list=RDze1pC-4mhfY"}
                width='100%'
                height='100%'
                controls
                light
            />
```

#### Environment
- URL attempting to play: https://youtu.be/W-jvyGyEifQ?list=RDze1pC-4mhfY
- Browser: Chrome
- Operating system: Windows and Android 

#### Other Information
I found that this issue is solved when I remove the text after the video ID in the Url.

**Comment by cookpete** [comment]
What video are you expecting to play? It plays this for me, which is the same video that plays when I visit https://youtu.be/W-jvyGyEifQ?list=RDze1pC-4mhfY directly:

![image](https://user-images.githubusercontent.com/1926029/105612486-6a121b00-5db4-11eb-8e1d-987a68dc48ce.png)

**Comment by AmmarMohamadIsmaeel** [comment]
@cookpete  Yess, In the demo project it's working well, but when using it in a react project, this bug is appearing!

**Comment by cookpete** [comment]
The demo project is just a standard React project. There must be something specific in your implementation that is causing this.

The same thing in jsFiddle seems to work fine too: https://jsfiddle.net/t9qga4zy

**Comment by AmmarMohamadIsmaeel** [comment]
@cookpete Unfortunately, it is not working fine in the JSFiddle

Open the URL and notice the name of the video, and then click on it in the JSFiddle project and notice that the opened video is something else, but the thumbnail that appears is for the correct video.

**Comment by cookpete** [comment]
I'm really sorry – I still don't see a problem.

When I open the link directly I get this:

![image](https://user-images.githubusercontent.com/1926029/105764611-17209b00-5f4f-11eb-9f04-53361ea61e43.png)

When I play the link in the demo page I get this:

![image](https://user-images.githubusercontent.com/1926029/105765926-040eca80-5f51-11eb-8d55-592a6a18ee08.png)

And when I play the jsFiddle example I get this:

![image](https://user-images.githubusercontent.com/1926029/105765976-125ce680-5f51-11eb-8651-9e35722b9372.png)

All seems fine to me?

**Comment by AmmarMohamadIsmaeel** [comment]
This is so strange. I really can't understand what is going on.

I tried it with several browsers on several machines, desktops, and mobiles, and I am having the same result. I did not change anything with the jsFiddle project just open it and I am seeing this screen:

![image](https://user-images.githubusercontent.com/57847174/105872731-66280800-6003-11eb-8402-ddab7103d334.png)

Then click on the video to play and another video is playing other than the price tag video.
![image](https://user-images.githubusercontent.com/57847174/105872853-8952b780-6003-11eb-9d2a-b43d137820a5.png)

Please, try to clear your cache and logout from youtube, and try another machine.

@cookpete I am sorry for that confusing problem! 😅

**Comment by Milkhan** [comment]
I can partially confirm @AmmarMohamadIsmaeel, when you click on the video it is playing the first video from the **playlist**.  This is a playlist url and the video in the picture is the 23rd video in the playlist. So when you click it does not play the 23rd video but the first video from the playlist.
And please keep in mind that if you just put a single video link it is working as expected.

**Comment by cookpete** [comment]
Yeah I've now seen this too. Opening in incognito (not signed in to youtube) plays a completely different playlist (with 26 videos instead of 19). I have no idea why the youtube player does this.
