### ISSUE TITLE
onPause trigger when clicking on timeline video

### ISSUE THREAD

**Issue by duchai283** [cookpete/react-player#1151]
How to not trigger onPause when clicking to timeline on the youtube video?
Reproduce : 
I make a trigger like playVideo ? ReactPlayer Component : null 
So when click on the timeline video, onPause trigger and ReactPlayer disappear
The pause button works nice  

#### Expected Behavior 
Not triggering onPause when clicking on the timeline video

**Comment by cookpete** [comment]
Would be nice if we could control it (or even have a callback event for when a user starts to seek) but we are at the mercy of the YouTube player API, and we can't control that behaviour.

You could try something like this, which looks at the sequence of events in a short period of time to determine a pause or seek: https://simplernerd.com/js-youtube-seek/
