### ISSUE TITLE
Fullscreen player on landscape mode

### ISSUE THREAD

**Issue by Blusoup** [cookpete/react-player#1155]
#### Current Behavior
Currently if I have a youtube video playing, when I turn the phone landscape mode it stays in the same size.

#### Desired Behavior
Is it possible to have the video go fullscreen when I turn the phone landscape?

**Comment by cookpete** [comment]
You could use these two to achieve this, although it sounds like quite a jarring user experience (I would let the user decide if they want to fullscreen or not.)

- https://developer.mozilla.org/en-US/docs/Web/API/Window/orientationchange_event
- https://github.com/sindresorhus/screenfull.js/
