### ISSUE TITLE
ReactPlayer seems to have problems with some youtube embedded urls

### ISSUE THREAD

**Issue by davesargrad** [cookpete/react-player#1156]
#### Current Behavior
Urls that contain a hyphen seem to create a problem for rendering. 

For example the following works just fine
https://youtu.be/ANCAyz_U_oo

![image](https://user-images.githubusercontent.com/48793689/106026547-ef891a00-6097-11eb-8c72-3c89f52f4447.png)

Whereas this does not

https://youtu.be/ysz5S6PUM-U

![image](https://user-images.githubusercontent.com/48793689/106026713-295a2080-6098-11eb-85a9-e7166357f97b.png)

---
The code that I am using is exactly the same in both cases.. except for the source URL.
```
function App() {
  return (
    <>
      <AppBar positition="fixed">
        <Toolbar>
          <Typography variant="h6">Streamer</Typography>
        </Toolbar>
      </AppBar>
      <Toolbar />
      <Container maxWidth="md"> 
      <ReactPlayer 
        url="https://www.youtube.com/embed/ysz5S6PUM-U"
        muted={false}
        playing={true}
        controls={true}
      >
      </ReactPlayer>
      </Container>
    </>
  );
}

export default App;
```

I am running my app server on a virtualbox fedora vm on my windows 10 box

**Comment by Yasamato** [comment]
Is this still a problem? I can play both without any problem

**Comment by Dmitrinilssonbysell** [comment]
Slice & Dice your URL. I had this same problem for i whole day. After i search online and could not found any good awnser, i started to manipulate my URL and slice it, like check it over some others and find the sweetspot. That will do it

**Comment by cookpete** [comment]
This looks like something possibly related to your location or IP address or something. Both URLs work fine for me.

https://jsfiddle.net/vzh9tm3a/
