### ISSUE TITLE
HLS m3u8 playlist all segments are being downloaded at once error

### ISSUE THREAD

**Issue by tebitobi** [cookpete/react-player#1157]
With the chrome dev tools network tab open; when the HLS vod is loaded, all segments are downloaded one after another. When I test the HLS stream in another video.js public video player demo, it works fine and segments are downloaded only when it's about to be played. How do I tweak react-player so it has the same behaviour?

**Comment by cookpete** [comment]
I'm not sure exactly why this is happening, but you can use `config={{ hlsOptions: { … } }}` to pass in any [HLS.js config options](https://github.com/video-dev/hls.js/blob/master/docs/API.md#fine-tuning).

**Comment by tebitobi** [comment]
I think I had to set hlsOptions.maxMaxBufferLength low.
