### ISSUE TITLE
cant seem to use video returned by getInternalPlayer, to draw on html5 canvas context

### ISSUE THREAD

**Issue by davesargrad** [cookpete/react-player#1159]
I am following [this](https://www.youtube.com/watch?v=Y-OLcnr8eNo) tutorial that shows how to use ReactPlayer:

I get through most of the tutorial properly.

I see the following error when I try to create bookmark images:
![image](https://user-images.githubusercontent.com/48793689/106284723-8decbb00-6211-11eb-94b0-0769410e8f19.png)

My playerRef is set as follows:
![image](https://user-images.githubusercontent.com/48793689/106287052-5fbcaa80-6214-11eb-997f-9ff84af990a3.png)

![image](https://user-images.githubusercontent.com/48793689/106286918-313ecf80-6214-11eb-96d4-960ffbbb5d0f.png)

I tried using several techniques, and as you see in the image above, I even tried to use the [captureVideoFrame](https://github.com/ilkkao/capture-video-frame/blob/master/capture-video-frame.js) function that is referenced by cookpete [here](https://github.com/CookPete/react-player/issues/341).

getInternalPlayer does not seem to return something that can be passed to the drawImage method of an html5 canvas context.

This code [seems like it should work](https://stackoverflow.com/questions/23745988/get-an-image-from-the-video/44325898):
![image](https://user-images.githubusercontent.com/48793689/106285371-6813e600-6212-11eb-8a10-95c319cb0ce9.png)

However the error I see is as follows:
![image](https://user-images.githubusercontent.com/48793689/106285444-7cf07980-6212-11eb-9378-b64074b77e2f.png)

Note, in the console, I have displayed the video object and it can be seen here:

![image](https://user-images.githubusercontent.com/48793689/106285515-95f92a80-6212-11eb-8572-ec4dea3cbfc4.png)

Looking at your documentation, it seems like getInternalPlayer can only be used in this way if its referencing a FilePlayer
![image](https://user-images.githubusercontent.com/48793689/106287956-6e579180-6215-11eb-9d06-4a17a7155270.png)

How can I get the "current video frame" in a standardized fashion, so that I can then render to an html5 canvas?

**Comment by cookpete** [comment]
The clue is here:

![image](https://user-images.githubusercontent.com/1926029/108281841-6df94900-7178-11eb-90f0-474c8eb7dfdb.png)

It looks like you are playing a Youtube URL, which renders an `<iframe>`, which is what gets returned by `getInternalPlayer()`. The problem is that iframes can't be used in `drawImage` – only images, videos or SVGs are supported, as the error describes.
