### ISSUE TITLE
vimeo.com videos does not play based on specific time

### ISSUE THREAD

**Issue by idaromnet** [cookpete/react-player#1161]
Hello,
I just noticed that if you want to use react-player with vimeo link, the pattern of https://vimeo.com/123#t=0m53s does not work. Basically it does not start the video at 53 second.

Thanks

**Comment by adilanchian** [comment]
There is a seek function in this library! Might be useful for you :).

**Comment by cookpete** [comment]
We are at the mercy of what the Vimeo Player API supports. If it doesn't support passing in a start time, there's not much we can do.

My suggestion would be to listen to `onReady` and then call `onSeek()` on the instance, as @adilanchian mentioned.
