### ISSUE TITLE
Fire an event if unable to parse or if the video doesn't exist

### ISSUE THREAD

**Issue by carpben** [cookpete/react-player#1163]
Is thee any way to fire an event/function if the player isn't able to parse the url, or if it can parse but the video doesn't exist? I understand this might be difficult to implement due to the various providers used.

**Comment by cookpete** [comment]
There is a `ReactPlayer.canPlay` static method for checking if a URL _should_ be playable. If a video doesn't exist then the player API _might_ trigger a call to `onError`, but might not. Depends what you are trying to play and how good the external library is.

**Comment by carpben** [comment]
Thanks @cookpete. This is very helpful.
