### ISSUE TITLE
iFrame titles?

### ISSUE THREAD

**Issue by tago-SE** [cookpete/react-player#1164]
I was wondering if it's possible to set the iframe title of youtube videos (or other video-players) in the config? 
Currently the resulting iframe title is: "Youtube video player".

This is important from an accessability metric standpoint.

Thank you.

**Comment by cookpete** [comment]
We don't have control over this unless the [Youtube player API](https://developers.google.com/youtube/iframe_api_reference) supports it, which it doesn’t.
