### ISSUE TITLE
Embedded videos in in-app browsers do not start playing

### ISSUE THREAD

**Issue by niktverd** [cookpete/react-player#1166]
I have a react web app that embeds an iframe video from youtube / vimeo with react-player. The playback is controlled by a 'go' button which sets the state of playing in <ReactPlayer url={url} playing={true}/>. I don't want to have any controls on my player, so this button is a work around because ipads and iphones don't allow autoplay.

The app now works on ios if I put the link in browsers (works on all browsers), but when I share the link in facebook messenger or instagram, the automatically opens it in an in-app browser where the 'go' button does not set off playback.

Any idea how I could solve this? Can share code/url if necessary.

Link I share in instagram https://candylanding.netlify.app/601b1141bfa41700154f7e13

**Comment by nntverd-carcenter** [comment]
What I actually found out is that I can play videos on Iphones.

Second, I can play video on android only if it is muted.

Only I put flag FALSE to the field muted, video pauses immediately

All it happens in instagram in-app browser Xiaomi Mi-8 Android

Do you have any Idea how to force playing with sound on android?

**Comment by nntverd-carcenter** [comment]
I found in doc such a statement

> Autoplay
> 
> As of Chrome 66, videos must be muted in order to play automatically. Some players, like Facebook, cannot be unmuted until the user interacts with the video, so you may want to enable controls to allow users to unmute videos themselves. Please set muted={true}.

Should playing={stateVariableChangedByUser}  be considered as user non-interacted play start?

**Comment by cookpete** [comment]
There is a specific section about this in the Youtube player API docs: https://developers.google.com/youtube/iframe_api_reference#Autoplay_and_scripted_playback

It is very difficult, especially when using Youtube videos, to do what you are trying to do. I wish you the best of luck but I can't be any more help to you. Autoplay on mobile is very difficult and always changing.

**Comment by adilanchian** [comment]
Hi there!

So in order to use the auto play with this library, you need to explicitly set volume to 0 when muted is set and when unmuted, set it to whatever value between 0-1 (or null for device default). 

So now on iOS devices if playing is set, volume is 0, and is mute is true, your trigger action would turn mute to false and volume to some other value. 

Hope this helps!

**Comment by justintemps** [comment]
I had the same problem, videos weren't playing after the first tap on iOS devices. Here's how I got around it"

1. Set volume to something (or else muted won't work)
2. Use component state to decide whether the player should be playing
3. Same state can toggle muted off and on

Here's a complete example

```
import React, { useState } from "react";
import ReactPlayer from "react-player/lazy";

const Video = ({ video_url, thumbnail }) => {
  const [playing, setPlaying] = useState(false);

  function handleclick() {
    setPlaying(!playing);
  }

  return (
    <div className={styles.container} onClick={handleclick}>
        <ReactPlayer
          autoplay
          volume={0.8}
          muted={!playing}
          playing={playing}
          controls
          light={thumbnail.url}
          width="100%"
          height="100%"
          style={{
            position: "absolute",
            top: 0,
            left: 0,
            width: "100%",
            height: "100%",
          }}
          url={video_url.embed_url}
        />
    </div>
  );
};

export default Video;

```
