### ISSUE TITLE
Player stop playing after a while using Google Drive audio file

### ISSUE THREAD

**Issue by devfromfinland** [cookpete/react-player#1167]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior
I'm using audio file shared publicly via Google Drive and load to ReactPlayer. Audio direct link: https://docs.google.com/uc?export=download&id=12hiTf8kgdVrTe3DDKVwhoMaBJDotORl3

After it is loaded, I let it played for a while without doing anything on the page, then it suddenly stopped (in my case at 12:57) and throw error 206, then 403. Seems like it communicated again with the Google Drive link and got rejected (cors error 206) even though the link is publicly accessible by anyone without authentication.

I checked the buffer in onProgress, it buffered enough till this time (you can see in my attached screenshot).
![Screenshot 2021-02-05 145421](https://user-images.githubusercontent.com/62564734/107036295-12b37800-67c2-11eb-9ea3-1bd9712eb243.png)

If I turned on crossOrigin: 'true' in the attributes, the Player doesn't load the audio.

#### Expected Behavior
There shouldn't be an error and audio keeps playing till the end. I wonder is there a way to solve or work around this? I guess it doesn't happen with youtube link since it uses iframe.

#### Steps to Reproduce
1. Load ReactPlayer with this url: https://docs.google.com/uc?export=download&id=12hiTf8kgdVrTe3DDKVwhoMaBJDotORl3 (the mp3 file is shared publicly from Google Drive and this is the link to access the file directly
2. Let it plays for a while without doing anything (about 13 minutes). Then it will stop.

#### Environment
- URL attempting to play:  https://docs.google.com/uc?export=download&id=12hiTf8kgdVrTe3DDKVwhoMaBJDotORl3
- Browser: Chrome
- Operating system: both Windows and Android
- jsFiddle example: https://jsfiddle.net/devfromfinland/ubdcjq0k/8/ (interesting, in jsFiddle, it works well. I don't know why...)

#### Other Information
- Live app that I'm working on (which has error as I explained above): https://mindfulness.ykitest.fi

**Comment by devfromfinland** [comment]
I think the issue is at parsing the URL. For the first time, it sends request to my direct link, get response from Google for another link with session. But then the second time, ReactPlayer uses the link received previously from Google Drive and skip the original link (I guess session token is attached to it).
![Screenshot 2021-02-05 162051](https://user-images.githubusercontent.com/62564734/107045436-2fee4380-67ce-11eb-9396-9b2180f54e8a.png)

I logged the error object and see error: MediaError { code: 2, message: "PIPELINE_ERROR_READ: FFmpegDemuxer: data source error" }. I'm thinking of a workaround: load the direct link again and continue playing at the time error happened, but I hope there could be a better way.

**Comment by devfromfinland** [comment]
Another question could solve this: why it works on jsFiddle but not on my project.
* jsFiddle: I use https://unpkg.com/react-player@1.9.0/dist/ReactPlayer.js
* my react package.json: "react-player": "^2.8.2"

**Comment by nntverd-carcenter** [comment]
I used to play videos from google drive and show images from it, and found out that everything work well on Android. But IOS devices cannot play video, and images cannot be loaded from Google Drive.

May be it helps

**Comment by devfromfinland** [comment]
Thank you @nntverd-carcenter !

I tested with other cloud storage services. Look like it's the issue from Google's permanent link. Google seems to redirect the link and add another layer of checking session for subsequent requests for security reason even with publicly shared file.

Amazon S3 and Dropbox do not have Redirect on permanent public link.
OneDrive has Redirect, but the file content (mp3) keeps being downloaded from the initial response without a new request -> so it works.

Thank you @cookpete for creating this library!
