### ISSUE TITLE
Vimeo: race condition between `ready` state and call `seekTo`

### ISSUE THREAD

**Issue by newsiberian** [cookpete/react-player#1174]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior

When users call `seekTo` for some services like **Vimeo** they could receive an error `ReactPlayer: could not seek using fraction – duration not yet available` because `seekTo` is depends on video `duration`. Receiving `duration` in case of **Vimeo** is async and it could happen a little bit later after `loaded` will be received.

#### Expected Behavior

`ready` state must be emitted after all required parameters will be received (at least `duration`)

#### Steps to Reproduce

You need to store `played` state somewhere locally and use it to call `seekTo` right after player will emit `ready` and also you must use pass `playing: true` to the player

1. Set progress to the middle of the video
1. Refresh page

**Comment by cookpete** [comment]
I’m not sure what ReactPlayer can/should do about this. If you are seeking using fractions I would suggest disabling seeking in your app until `onDuration` has been called. Waiting for duration before calling `onReady` would couple the two events to tightly and just isn't necessary. Use `onDuration` rather than `onReady` if you require duration for your UI to be "ready".

**Comment by newsiberian** [comment]
Hi, @cookpete. I dont think you are right here. Library authors should strive to provide one API for all such things like different media services (in our case). So, I, like library user, don't wont to write different logic for each service (youtube, vimeo, etc) on my side

**Comment by cookpete** [comment]
>Library authors should strive to provide one API for all such things.

I agree with this, so I’m not sure I understand your point. `onReady` is called when the player is ready to be played. `onDuration` is called when the duration of the video is available. The behaviour of both are consistent across all players.

`onReady` is not "when seeking is ready" – it is "when the video can be played". It doesn’t (and shouldn’t) [care](https://en.wikipedia.org/wiki/Separation_of_concerns) about whether duration is ready or not. That’s what `onDuration` is for. If an action requires duration, you need to block/disable it until `onDuration` is called.
