### ISSUE TITLE
ReactPlayer not working in React 17

### ISSUE THREAD

**Issue by nk11dev** [cookpete/react-player#1176]
**Current Behavior**

@cookpete, Hi!
I can confirm that ReactPlayer not working in React 17 with client-side rendering. 

I use react-player version 2.8.2. Error came right after i upgrade react and react-dom packages versions from "16.14.0" to "17.0.1". 

I saw other react 17 issue https://github.com/cookpete/react-player/issues/1165, but in my case it doesn't connected with NextJS because i don't use it so i create the separated issue for react 17 only.

**Current packages versions:**
```
...
"react-player": "2.8.2",
"react": "17.0.1",
"react-dom": "17.0.1",
...
```

**Console error message:**
```
Uncaught undefined
The above error occurred in one of your React components:
    in Unknown (created by ReactPlayer)
    in Suspense (created by ReactPlayer)
    in div (created by ReactPlayer)
    in ReactPlayer (created by PlayerBlock)
```

**Steps to reproduce:**
I use "react-player" in my "Movies" project and created branch with "react" and "react-dom" packages bumped to "17.0.1": https://github.com/nk11dev/movies/tree/REACT-17-react-player-error-reproduce
1) clone repo and install dependencies
2) run `npm run dev`
3) go to root url (http://localhost:8080/, by default). I put "react-player" in the root script (/src/app/index.client.js) to easily reproduce error

**Expected behavior:**
As i mentioned above, i already use "react-player" in my app with react and react-dom packages  "16.14.0" versions and it works fine. Expected behavior is like there (player works ok): https://nk11dev-movies.herokuapp.com/movies/464052?lng=en. On site it runs in SSR mode, but errors come in client-side rendering too.

**Environment:**
Browser: Chrome 88.0.4324.150
Operating system: Windows 10

**Comment by cookpete** [comment]
Looks like you need to bump `@hot-loader/react-dom` to `17.0.1` too.

**Comment by nk11dev** [comment]
Thanks, you're right. After updating `@hot-loader/react-dom` to `17.0.1` it works.

**Comment by joebentaylor1995** [comment]
Same issue still in `Gatsby 3.11.1`. installed `@hot-loader/react-dom` and that made no difference
