### ISSUE TITLE
still can't make playlists work (autoplay policy ?)

### ISSUE THREAD

**Issue by gordielachance** [cookpete/react-player#1177]
Related to https://github.com/cookpete/react-player/issues/1072, I still can't make playlists work; player is "blocked" by the browser when the tab is inactive.

I suspect that this might be related to your code, since it even does not work when the website is whitelisted for autoplay (for chrome, at _chrome://settings/content/sound_).

This example on codepen has an audio playlist which works when tab is in background (even if not whitelisted) https://codepen.io/danielhoegel/pen/OZNqNo

After a media has ended and that the next one is requested to play (custom code), react-player fires _onReady_ but does not play the media.

#### Other Information
Demo here : http://v2.spiff-radio.org/
I also filled a question on stackoverflow [here](https://stackoverflow.com/questions/66257228/player-in-background-tab-doesnt-play-next-playlist-track-autoplay-policy).

Thanks a lot !

**Comment by TheManFromEarth1** [comment]
With your demo it doesn't work here either on either Firefox or Chrome.

I use the library on a Nextjs project and there it autoplays the next video.

I use onEnded={..} which calls a function which updates the current url={...}.

**Comment by gordielachance** [comment]
Hi @TheManFromEarth1,  it helped !
As I knew it was possible because of your feedback, I kept trying to find out what was the bug.

Well, at the beginning of my function **resolveTracks()**, I had a line


    setSourceUrl('');

Which was "resetting" the stream before loading the next URL.
That was the cause of my bug.  Without that line, going to the next track works !

Thanks a lot for your help.
(no need for _stopOnUnmount_ here)
