### ISSUE TITLE
Start player from specific time?

### ISSUE THREAD

**Issue by rsofista** [cookpete/react-player#1179]
Here's a solution posted here:

https://github.com/CookPete/react-player/issues/433

Should this still work?

My log shows the url is

https://player.vimeo.com/video/443376183#t1m42s

but what's actually in the iframe is

https://player.vimeo.com/video/443376183?title=0&byline=0&portrait=0&playsinline=0&autopause=0&app_id=122963

---

The solution that worked there:

> > how can i write the config for a normal file?
> 
> I am wondering about this too. Tried a couple of ways, for example seeking when onReady, but the player just resets played to zero.

I've found a solution that may help someone using media fragment

Media Fragments
Adding a media fragment to the media URL, you can specify the exact portion you want to play. To add a media fragment, you simply add #t=[start_time][,end_time] to the media URL

<ReactPlayer
ref={this.ref}
url={${source}#t=${this.state.duration * this.props.played}}
/>

I'm passing played as prop to the player component, that I retrieve from the db stored

_Originally posted by @breth84 in https://github.com/cookpete/react-player/issues/433#issuecomment-669146199_

**Comment by cookpete** [comment]
You are talking about two solutions to very different things (Vimeo player vs file URL).

Please search for issues before posting. See https://github.com/cookpete/react-player/issues/1161 and https://github.com/cookpete/react-player/issues/1097 and https://github.com/cookpete/react-player/issues/554.

**Comment by linta03** [comment]
hey  can you tell me how can I start a video on specific time for daily motion in reactPlayer??

**Comment by rsofista** [comment]
> hey can you tell me how can I start a video on specific time for daily motion in reactPlayer??

if you search for "seek(double)" that maybe be it https://developers.dailymotion.com/player/
