### ISSUE TITLE
Hevc content is not playing

### ISSUE THREAD

**Issue by sriramsridhar** [cookpete/react-player#1180]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior
Player loads up master manifest and child manifest urls are not firing in chrome browser

#### Expected Behavior
Child manifest urls should be firing and the video should play based on ts segments within child manifest urls

#### Steps to Reproduce

Fire a hevc encoded hls url with ts segments and player is stuck with the loader icon

#### Environment
- Browser: Chrome
- Operating system: Mac

**Comment by cookpete** [comment]
ReactPlayer is just a proxy for `hls.js`. Does your URL work in the HLS demo? https://hls-js.netlify.app/demo/
