### ISSUE TITLE
Reset player after dynamic update of config

### ISSUE THREAD

**Issue by madeleineostoja** [cookpete/react-player#1183]
I'm trying to have a video play in background mode (looping, muted, no controls) until it is clicked, then to restart as per usual with the full player. Updating the Vimeo player's `config` prop dynamically doesn't seem to work. It would be great to either fix that or to have an instance method to re-initialise the player.

#### Current Behavior
Changing `config` dynamically does not update the player

#### Expected Behavior
Changing `config` dynamically should update the player, or the player should provide a reset method on the instance

#### Steps to Reproduce
1. Set `background: true` on Vimeo player
2. Programatically set `background: false` on playing Vimeo player
3. Watch as nothing changes

#### Environment
- Browser: Chrome
- Operating system: macOS

**Comment by walidvb** [comment]
Could you provide a code example? I can try to take a look

**Comment by akash9406** [comment]
i have the same issue how to update config dynamically so that its reflect on the player
