### ISSUE TITLE
Using ref in electron 12 results in electron freezing/hanging

### ISSUE THREAD

**Issue by uffou** [cookpete/react-player#1188]
#### Current Behavior
When you try to use the ref prop (for access to instance methods) in any way in electron 12 it hangs. There are no errors but you can't do anything which usually happens when there is an infinite loop. If you don't use `ref` everything works normally.

#### Expected Behavior
Business as usual

#### Steps to Reproduce
1. use electron 12
2. `<ReactPlayer ref={this.ref} />`

#### Environment
- URL attempting to play: ANY
- Browser: Electron 12 (Chromium 89, V8 8.9)
- Operating system: ANY

#### Other Information
This issue did not happen in electron 8 but we upgraded to 12 and it started to happen, it also does not happen on the web which is exactly the same implementation. I am not aware whether it happens on electrons 9, 10, 11. It's really odd. I would love to provide more information but there's none. 

Does anyone know of a workaround to access `seekTo` and `wrapper` ?

**Comment by uffou** [comment]
I am closing this issue because I could not reproduce it in a new electron app. It seems there are more implementation-specific reasons for this issue to happen.

**Comment by svmalvaez** [comment]
@uffou have you tried ref.current.seekTo(<amount>, 'seconds/fraction') ?
