### ISSUE TITLE
Soundcloud Private embed src link does not work.

### ISSUE THREAD

**Issue by eddyfabery** [cookpete/react-player#1189]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior
- Current soudcloud iframe src does not account for `secret_token={}` param
- ReactPlayer does not handle private embedable links

#### Expected Behavior
- Play private embedable SoundCloud Links

#### Steps to Reproduce

1. Upload an audio via SoundCloud and mark it as private
2. Copy generated src URL for embed links.
3. Use embed link url and pass it to ReactPlayer as url prop

#### Environment
- URL attempting to play: 
- Browser: 
- Operating system: 
- jsFiddle example: https://jsfiddle.net/sv5x3ug1

#### Other Information
Missing parameter [here](https://github.com/cookpete/react-player/blob/a83203fab34a57f980868c4cf581cd5beb9c1763/src/players/SoundCloud.js#L112)

**Comment by cookpete** [comment]
@eddyfabery Can you post an example of a private embed URL? Even if you change the secret token to something else.

**Comment by papuruth** [comment]
The embedded URL is changed a bit now the URL part includes "api" at front due to which the player doesn't loads the link also I checked the REGEX for sound cloud it matched from soundcloud.com..... ignoring the "api" part

**Comment by shaulgo** [comment]
The link below doesn't work. Seems like it is related. Any ideas how to fix it? 

https://soundcloud.com/user-961206191/exercise-1-learning-how-to-relax-heart-mind-relaxation-exercise/s-xgOUpletYTx?si=4bcfe9479c1d4271802131ea3d632944

**Comment by symbiosdotwiki** [comment]
having the same problem, whats the official solution?

**Comment by symbiosdotwiki** [comment]
ok if someone else has this problem:

typical URL format :
https://soundcloud.com/ARTIST/sets/PLAYLIST_NAME/SECRET_TOKEN

You will need to go to the iframe embed code for the playlist, or the oembed url as in @shaulgo comment and get the PLAYLIST_ID

change the URL to this:
https://api.soundcloud.com/playlists/PLAYLIST_ID?secret_token=SECRET_TOKEN
