### ISSUE TITLE
Deploy process

### ISSUE THREAD

**Issue by jeanmichelcote** [CookPete/react-player#119]
Could someone please detail a bit more what is and when to use those scripts:
```
"build:webpack"
"build:browser"
"build:demo"
"build:compile"
```

I am ready to deploy my app on a test server. What should I do now?

Also, do I have to call any of those aforementioned scripts before running `"start:tunnel"`? 
I've just tried it without a build step and the only thing that shows up when visiting the ngrok URL is the the backgroud image set in the main css file. No player, nothing else.

Thanks for helping out.

**Comment by CookPete** [comment]
I wasn't sure exactly what your goal was here, but all of the `build` scripts are to assist in developing the `ReactPlayer` library itself. You don't really need to worry about using them unless you want to run or build the library in development mode yourself:

* `build:webpack` is part of the [demo app](http://cookpete.com/react-player/) build process
* `build:browser` uses webpack to build a minified version of `ReactPlayer` for `bower` and direct use in `<script>` tags
* `build:demo` cleans up the working directory, runs `build:webpack` and then copies the `index.html` file into the `dist` folder
* `build:compile` uses `babel` to compile the `src` files into `lib` for publishing to `npm`
