### ISSUE TITLE
seekTo not work, sometimes return to 0 and somtimes stay where it was

### ISSUE THREAD

**Issue by reutEshkoli** [cookpete/react-player#1190]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Steps to Reproduce

1.
1.
1.

#### Environment
- URL attempting to play: 
- Browser: 
- Operating system: 
- jsFiddle example: https://jsfiddle.net/sv5x3ug1

**Comment by cookpete** [comment]
I'm going to start closing issues like that that have completely ignored the issue template.
