### ISSUE TITLE
getDuration() not showing proper time when passing youtube Livestream in URL

### ISSUE THREAD

**Issue by SweetSoul** [cookpete/react-player#1191]
#### Current Behavior
When passing a livestream embed as URL getDuration() doesn't work properly, even though the maximum time to seek is X getDuration returns X+Y

#### Expected Behavior
Stream is at 20:00 minutes of stream, getCurrentTime() returns 20:00 - OK
getDuration() returns 22:16 (random number)

#### Steps to Reproduce
1.Setup the player
2.setup console.log the player method
3. Play any live video happening in the time.

#### Environment
- https://www.youtube.com/embed/GEqtUKi0ZXQ 
- Opera 73 on Windows 10 (who tf uses opera?)
- Windows 10

**Comment by cookpete** [comment]
The youtube player API mentions this:

>If the currently playing video is a live event, the getDuration() function will return the elapsed time since the live video stream began. Specifically, this is the amount of time that the video has streamed without being reset or interrupted. In addition, this duration is commonly longer than the actual event time since streaming may begin before the event's start time.

https://developers.google.com/youtube/iframe_api_reference#getDuration

I'm not sure what we can do about it in this library?

**Comment by SweetSoul** [comment]
Thanks @cookpete I wasn't sure that was the case. Closing it.
