### ISSUE TITLE
Multiple sources // skipping options

### ISSUE THREAD

**Issue by clairelct** [cookpete/react-player#1192]
Hi Pete,

I'm trying to display an audio player on my website (for a podcasts section), and would like to create a playlist of internal files such as mp3.
When i'm passing an array of files in the `url` attribute I can see multiple `<source>` tags in the console, but I'm wondering how to render "prev" and "next" buttons to skip from a file to another, is it possible ?

Thanks in advance,
Claire

**Comment by gordielachance** [comment]
I've started to work on a [ReactPlaylister](https://github.com/gordielachance/react-playlister), a playlist wrapper for **ReactPlayer**.  You can see a demo [here](https://spiff-radio.org/react-playlister/).
It is not finished yet, I still have to work on it..
