### ISSUE TITLE
Uncaught TypeError: (0 , _memoizeOne.default) is not a function

### ISSUE THREAD

**Issue by Shing-Ho** [cookpete/react-player#1194]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior

It's suddenly happened today.
Suddenly it's showing Uncaught TypeError: (0 , _memoizeOne.default) is not a function
![image](https://user-images.githubusercontent.com/57267692/111191895-c05e3780-8575-11eb-8362-faf2da7fce12.png)

#### Expected Behavior

It shoudn't show

#### Steps to Reproduce

1.import ReactPlayer from 'react-player';
2.<ReactPlayer url={url} width={835} height={430} />

#### Environment
- URL attempting to play: 
- Browser: chrome
- Operating system: macOS
- react-player: 2.9.0

**Comment by Yasamato** [comment]
I would expect your node modules to not be correctly installed or not of the correct version, as I cannot replicate your issue at all in a fresh ts project.

**Comment by rememberlenny** [comment]
I am getting this error too. I would love to help debug this if anyone has any thoughts.

**Comment by TheAsda** [comment]
I'm facing the same issue with vite

**Comment by Yasamato** [comment]
Just a question, are you guys using vanilla JS or TypeScript? Cannot reproduce on TS at least

**Comment by TheAsda** [comment]
I'm using typescript with vite and react 17

**Comment by rememberlenny** [comment]
I was also using VITEjs. I had to copy the node module and use the source files as a vendor folder to get it working.

The issue seems to be related to how the npm module is compiled.

**Comment by bilalesi** [comment]
any solution for this bug, i am using vite and react 17

**Comment by rememberlenny** [comment]
It’s an issue with compiling the react lazy imports.

I imported the npm module code into our code base as a vendor folder and it worked fine.

**Comment by bilalesi** [comment]
@rememberlenny 
so how we can add it to the project without facing the bug, can you please describe the steps to added it ??! thank you

**Comment by porkytheblack** [comment]
having the same issue, while using typescript and react18
