### ISSUE TITLE
Adding lazy loading to light prop of video thumbnail

### ISSUE THREAD

**Issue by hamzashah38** [cookpete/react-player#1195]
How to add image lazy load to the light prop of the player? 
Please Help.

![image](https://user-images.githubusercontent.com/40095107/111261586-827c1480-8644-11eb-94be-95a3df22bc59.png)

**Comment by bymoe** [comment]
+1 this is important.

**Comment by Rajdeepc** [comment]
How can we make playing true to thumbnail which are .mp4 only when the video is in viewport?

**Comment by ayushthe1** [comment]
is there any solution for this issue yet ?

**Comment by cookpete** [comment]
I think this is solved by https://github.com/cookpete/react-player/pull/1405? You can pass in any component you like in the `light` prop now.
