### ISSUE TITLE
It overrides facebook login appId with value '1309697205772819'

### ISSUE THREAD

**Issue by mrdntgrn** [cookpete/react-player#1196]
#### Current Behavior
We have Next.js web application and we use react-player with dynamic load (front side render, without SSR). We have also Facebook SDK with facebook login enabled. The issue comes out in pages where we load video using react-player. The facebook login simply get failed with message "Can't load URL":

![image](https://user-images.githubusercontent.com/31103575/111295369-b8c98c00-8664-11eb-9067-1c6130cb3076.png)

#### Expected Behavior
The Facebook login should work without problems on pages where react-player used. 

#### Steps to Reproduce

1. Have a simple Next.js app and use react-player (not sure but maybe with [dynamic import](https://nextjs.org/docs/advanced-features/dynamic-import)) for playing a facbook video
2. Have facbook SDK with facebook login enabled
3. Try to login and you will get error about failure ("Can't load URL")
4. You can find that your Facebook appId got overridden with value 1309697205772819

#### Environment
- URL attempting to play: any Facebook video URL
- Browser: any
- Operating system: any

**Comment by fchenhau** [comment]
Face this issue in my project as well. But I found out react-player allows us to override the config. Can refer to https://www.npmjs.com/package/react-player#config-prop

Sample Solution:      
```
<ReactPlayer
  url={url}
  config={{
    facebook: {
      appId: '12345'
    }
  }}
/>
```
