### ISSUE TITLE
Wistia videos not loading

### ISSUE THREAD

**Issue by dan003400** [cookpete/react-player#1198]
It seems Wistia videos are not working, not seeing any errors, just nothing loads up.

I have tried with the testing url as well: https://home.wistia.com/medias/e4a27b971d

Thanks,

Dan

**Comment by dan003400** [comment]
Any updates here?

**Comment by cookpete** [comment]
Hard to investigate this without more info. Wistia videos work fine for me. Did you see the issue template?

![image](https://user-images.githubusercontent.com/1926029/112453110-408f5480-8d4f-11eb-84f9-996bb5f9ca59.png)

**Comment by dan003400** [comment]
Interesting, any reason why dynamically loading the component would cause issues? Seems maybe that prop updates maybe creating an issue that would cause loading to be an issue, possibly a timing issue?

Anything you know of to look out for?

**Comment by lordlpua** [comment]
I see a problem with Wistia, if a user using Edge 17 or 18 version. In this case video wouln't work

**Comment by Yasamato** [comment]
Without you sharing any code this is quite hard to comment on, but you may want to have a more in-depth read about [react props](https://reactjs.org/docs/components-and-props.html) and [lifecycles](https://reactjs.org/docs/state-and-lifecycle.html) in general

**Comment by kash0296** [comment]
Hi! I'm also facing an issue with loading Wistia videos. I have tried the Reactplayer component with vimeo, mixcloud, youtube, dailymotion and those work fine. I tried twitch as well, and it didn't work. What i noticed is, that in the case of wistia at least, the API calls to wistia were not happening, unlike how it does in the react-player demo. I'm not sure how this could be resolved, what could I try to do from my end to get wistia playback to work? I've tried it on codesandbox and it works fine.

**Comment by kash0296** [comment]
@cookpete  hi! I just wanted to follow up back with you. I was wondering if you had any idea why Wistia videos are not playing. If you need any further information, I could try and provide that as well. Thanks!

**Comment by Umangpatel312** [comment]
@cookpete Hi, I am facing a similar issue, First time wistia video is not played and showed an empty screen. I tried to troubleshoot and found that window._wq array has one element when video failed to play and window._wq array is empty when video played successfully

**Comment by Billbastos** [comment]
I am using this video as an example: https://fast.wistia.com/embed/medias/f866qxa5z3 on https://cookpete.com/react-player/
It seems is concatenating `/media` twice.
<img width="1210" alt="Screen Shot 2023-03-06 at 11 03 32 AM" src="https://user-images.githubusercontent.com/1039836/223206890-440979a0-c7c7-46e2-b36d-575901bdd367.png">
<img width="666" alt="Screen Shot 2023-03-06 at 11 07 33 AM" src="https://user-images.githubusercontent.com/1039836/223207181-fdf9d06d-fbb0-4867-9f83-b1a00b0f4d4f.png">

**Comment by bennonite** [comment]
@Billbastos and anyone having a similar issue with a double `/medias/medias` network request - I've found the fix is simply to not include /medias in the url you provide. Building on the above example, instead of using https://fast.wistia.com/embed/medias/f866qxa5z3 for react player use https://fast.wistia.com/embed/f866qxa5z3 and it should work.

**Comment by luwes** [comment]
yes, you have to use the Wistia video page URL. not the iframe embed URL.
that should fix it!
