### ISSUE TITLE
YT script does not load when run from a chrome extension

### ISSUE THREAD

**Issue by walidvb** [cookpete/react-player#1199]
#### Current Behavior
I'm trying to render a ReactPlayer from a chrome extension, on a facebook page. Soundcloud players load fine, but not youtube's

#### Expected Behavior
The youtube iframe should be rendered, or an error should be raised.

#### Steps to Reproduce
1. download [the chrome repo](https://github.com/walidvb/diggers-delights-extension/tree/preact) (make sure you're on the `preact` branch)
2. load it as an unpacked extension
3. open a [facebook page containing a post with a youtube link](https://www.facebook.com/groups/670123987117891/permalink/883150232481931/)

#### Environment
- URL attempting to play: any (but can try with this: https://www.youtube.com/watch?v=Rc2zdjQU7RA  to reproduce)
- Browser: Brave/Chrome `Version 1.21.73 Chromium: 89.0.4389.72 (Official Build) (x86_64)`
- Operating system: MacOS 11.1

#### Other Information

From my debugging, it seems like [this](https://www.youtube.com/watch?v=Rc2zdjQU7RA) is never called. I'm unable to understand where exactly this fails.
The extension modifies facebook headers to allow loading a script from https://youtube.com.
It works fine with [soundcloud](https://www.facebook.com/digitaltsunami/posts/1958771060943277)

Running the code returned by youtube does add `YT` to the window, but it doesn't seem to indeed add it via `load-script`.

PS: embedding a regular youtube iframe works as expected(but you don't get the controls)

**Comment by deannguyen27** [comment]
I also have the same problem, please help if there is a solution.
Message show :
Videos un available
View on youtube
