### ISSUE TITLE
Add Bandcamp support

### ISSUE THREAD

**Issue by walidvb** [cookpete/react-player#1200]
I'd like to add support to display Bandcamp embed URLs.
However, Bandcamp does not provide an API to control the player, meaning it would only display the embed, but not press play(or not hear when the song is finished).

Is that something that would be considered for this brilliant library?

**Comment by Yasamato** [comment]
After a bit of research I came across [iframely.com](https://iframely.com/docs/playerjs) and [embed.ly](https://docs.embed.ly/docs/player), they both seem to offer event listeners for media embeds according to the schema of [Player.js](http://playerjs.io). I bet we could work with that... only downside is that they are both paid services

**Comment by walidvb** [comment]
I don0t believe that this would handle Bandcamp, though? 🤔 Did you see any indicator of that?

**Comment by Yasamato** [comment]
Actually no. I also don't want to try it as they both vaguely claim to support "unified" video control via Player.js

**Comment by cookpete** [comment]
It's pointless to support a player that just renders an iframe with no event listeners or interaction. You might as well just render the iframe directly and save bloating your bundle with ReactPlayer. 

The Bandcamp player would have to support `player.js` for it to be picked up by services like iframely and embedly. If it does then great – pull requests welcome!

**Comment by walidvb** [comment]
Fair point, let's close this then!
