### ISSUE TITLE
IOS Volume Control 2021

### ISSUE THREAD

**Issue by dagreatbrendino** [cookpete/react-player#1203]
#### Current Behavior
IOS Volume Control Doesn't Work

#### Expected Behavior
I know there are a couple issues on this topic already but they are from a couple years ago so I was wondering if in 2021 it is possible to control the video volume. Would it be possible to control by somehow exposing the default html video element controls? I had pretty much lost hope on this one because I haven't been able to find anything anywhere about controlling volume on IOS devices, but I was just messing around on reddit on r/videos and noticed that their player allows you to control the volume of the video.

**Comment by Yasamato** [comment]
This should be a iOS limitation:
> On the desktop, you can set and read the volume property of an <audio> or <video> element. This allows you to set the element’s audio volume relative to the computer’s current volume setting. A value of 1 plays sound at the normal level. A value of 0 silences the audio. Values between 0 and 1 attenuate the audio.
>
> This volume adjustment can be useful, because it allows the user to mute a game, for example, while still listening to music on the computer.
>
> On iOS devices, the audio level is always under the user’s physical control. The volume property is not settable in JavaScript. Reading the volume property always returns 1.

https://developer.apple.com/library/archive/documentation/AudioVideo/Conceptual/Using_HTML5_Audio_Video/Device-SpecificConsiderations/Device-SpecificConsiderations.html#//apple_ref/doc/uid/TP40009523-CH5-SW10
