### ISSUE TITLE
Adding a custom setting 

### ISSUE THREAD

**Issue by VarunRustomji** [cookpete/react-player#1204]
Hey guys, so I'm using mux.com to host videos and want to display them on my site using react-player. 

I want to add a button that allows me to control the playbackRate next to the volume button or in the options section. Is there a way for me to add that to the current styles without having to build a custom wrapper that controls all the styles? 

Currently I have a button outside the player that says '2x' which increases the playback rate, I just want it to be a part of the video player like all the other options.

My current code looks something like this:
https://codesandbox.io/s/elated-driscoll-d4t16?file=/src/Video.js

**Comment by proudlion** [comment]
同问...

**Comment by the872** [comment]
Without hacking the component (using selectors and inject components within those), the real solution is that instead of passing a boolean to `controls` -- it should be able to take a list of children that are rendered at the bottom

**Comment by Yasamato** [comment]
In your given example you are saving a direct file to the player. react-player then proxies it to the browsers own native video player, meaning the browser dictates what controls you have. If you for example open your example in e.g. chrome and firefox, you will see that the players are quite different.

If you want a uniform experience with custom buttons etc. you may want to use your own wrapper for that

**Comment by VarunRustomji** [comment]
Hey @Yasamato & @the872, can you guys point me towards any examples on how to build a custom wrapper?

**Comment by d-ivashchuk** [comment]
@VarunRustomji have you achieved some progress with this? I am having similar use case and figuring it out

**Comment by AgustinAgapito** [comment]
@d-ivashchuk  @VarunRustomji I'm currently facing the same case on playingg youtube videos and built my own wrapper by not passing the control props and accessing the ref of react-player to freely control the video settings though you will be needed to implement things such as pause/play and seek bar.

<div  style={{ postion: 'relative }} >
  <ReactPlayer  />
   <div style={{ position: 'absolute', bottom: 0, width: '100%' }} >
      // your custom wrapper here
  </div>
</div>

I'm only a beginner at reactjs and not very sure if it's the same problem you are facing hpoing it helps

**Comment by Yasamato** [comment]
If you are new to creating your own player interface and want to create a full player. I highly recommend taking a look at already existing code examples like [plyr](https://plyr.io/) or [videojs](https://videojs.com/), which are both available on github.

But yes @AgustinAgapito is not wrong. You want a container which is filled by ReactPlayer and overlay certain html elements (buttons, icons whatever) inside this container. This would just require some css positioning and layout design

**Comment by luwes** [comment]
https://github.com/muxinc/media-chrome is another great alternative to add custom player controls.
