### ISSUE TITLE
React Player interface to dockerized Jellyfin HLS Stream is unreliable

### ISSUE THREAD

**Issue by davesargrad** [cookpete/react-player#1209]
I have been using React Player to playback streams from sources such as YouTube. I just recently got it working with my first instantiation of [Jellyfin](https://jellyfin.org/), on kubernetes. 

I had previsously gotten react player working with jellyfin HLS for a non-kubernetes instance of jellyfin (the seek to time function worked fine in that case).

I use [this ](https://api.jellyfin.org/#operation/GetVariantHlsVideoPlaylist)API.

However, I dont seem to be able to reliably seek a specific point in time. I've [verified ](https://github.com/jellyfin/jellyfin/issues/5722#issuecomment-815844549)that jellyfin invokes the jellyfin-ffmpeg to generate the M3U8 and TS files. However I will wait for minutes before I see the video begin to play at the "seek time". Sometimes it plays after a minute or more.. sometimes it just fails to.

I've been starting to figure out how to log the communication between react player and jellyfin. I'd like to log this on both sides to see if I can isolate the problem. How can I log the times that React Player makes a request to the service for individual TS files and for the M3U8 files?

I am using the first of these methods:

1. https://api.jellyfin.org/#operation/GetVariantHlsVideoPlaylist
2. https://api.jellyfin.org/#operation/GetHlsVideoSegment

**Comment by davesargrad** [comment]
I've also noticed something very interesting.. the seek works for early portions of the video, and for later portions. See [here](https://github.com/jellyfin/jellyfin/issues/5722#issuecomment-815875312).

**Comment by davesargrad** [comment]
I've just verified that when the seek fails to start playing, the "onProgress" callback is not invoked.

**Comment by davesargrad** [comment]
Why does react player continue to request TS files even when the player has reached end of file?

See [here](https://github.com/jellyfin/jellyfin/issues/5722#issuecomment-815958334).. this was not expected by me.

**Comment by davesargrad** [comment]
I am going through the process again.. it is starting to look very repeatable.

Here is the initial m3u8 file

Here are the 64 generated TS files and the single M3U8 file that references them.

```
[root@qatar transcodes]# ls | wc
     65      65    2460
```

```
[root@qatar transcodes]# cat *.m3u8
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:13
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-PLAYLIST-TYPE:VOD
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b8260050.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b8260051.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b8260052.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b8260053.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b8260054.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b8260055.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b8260056.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b8260057.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b8260058.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b8260059.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600510.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600511.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600512.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600513.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600514.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600515.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600516.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600517.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600518.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600519.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600520.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600521.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600522.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600523.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600524.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600525.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600526.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600527.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600528.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600529.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600530.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600531.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600532.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600533.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600534.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600535.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600536.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600537.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600538.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600539.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600540.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600541.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600542.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600543.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600544.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600545.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600546.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600547.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600548.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600549.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600550.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600551.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600552.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600553.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600554.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600555.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600556.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600557.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600558.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600559.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600560.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600561.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600562.ts
#EXTINF:7.400000,
7bfcae043c5fb93c677b4fcd2b82600563.ts
#EXT-X-ENDLIST

```

Here is the start of the network activity

![image](https://user-images.githubusercontent.com/48793689/114064789-80932300-9889-11eb-91b1-1196797138f6.png)

I am assuming that when I get to the end of the file.. the m3u8 file will be overwritten, and an additional 34 TS files will be generated.

**Comment by davesargrad** [comment]
Here is when the video has reached the last ts file 63.ts 

![image](https://user-images.githubusercontent.com/48793689/114066750-0e5f1600-986a-11eb-8ebc-360c0ac03311.png)

We see that "64.ts" is requested, and as soon as we do, I see a new m3u8 generated:

![image](https://user-images.githubusercontent.com/48793689/114066864-2cc51180-986a-11eb-8cd1-707ec71a77ee.png)

```
[root@qatar transcodes]# cat 7bfcae043c5fb93c677b4fcd2b826005.m3u8
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:13
#EXT-X-MEDIA-SEQUENCE:64
#EXT-X-PLAYLIST-TYPE:VOD
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600564.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600565.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600566.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600567.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600568.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600569.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600570.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600571.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600572.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600573.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600574.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600575.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600576.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600577.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600578.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600579.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600580.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600581.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600582.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600583.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600584.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600585.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600586.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600587.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600588.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600589.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600590.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600591.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600592.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600593.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600594.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600595.ts
#EXTINF:12.800000,
7bfcae043c5fb93c677b4fcd2b82600596.ts
#EXTINF:7.400000,
7bfcae043c5fb93c677b4fcd2b82600597.ts
#EXT-X-ENDLIST

```

**Comment by davesargrad** [comment]
After I seek to 6:22, I see react player request and download 54.ts, then nothing. It doesnt actually progress, nor does it request another file.

![image](https://user-images.githubusercontent.com/48793689/114077139-79fab080-9875-11eb-9579-7f414eb7826b.png)

**Comment by davesargrad** [comment]
@cookpete 

Ok.. I've added callbacks to onBuffer, onBufferEnd, onStart, onEnd, onError, onSeek. Currently I simply print these events when they occur.

After I seek I see onBuffer but no onBufferEnd

![image](https://user-images.githubusercontent.com/48793689/114189370-21302400-9918-11eb-9708-3872be29836a.png)



I saw the 52.ts requested and downloaded upon "seek", so it would seem that the buffer should have ended.

![image](https://user-images.githubusercontent.com/48793689/114189316-12497180-9918-11eb-9547-ee380b76c7ef.png)

**Comment by davesargrad** [comment]
As you can see, some buffers fail to end.. some seeks result in a buffer that starts and ends.. however from a network perspective.. all these buffers seemed to download (and end).

![image](https://user-images.githubusercontent.com/48793689/114191016-f3e47580-9919-11eb-96d1-c3b8b4af1d28.png)

**Comment by davesargrad** [comment]
There seems to be a disconnect between when the network activity shows the ts frame reception completing, and the call to onBufferEnd().. even though the frame is received .. at times onBufferEnd is invoked.. other times it isnt.

**Comment by davesargrad** [comment]
i also find it very odd.. that during this time when onBufferEnd is pending, I see a number of ts frames downloaded (and not necessarily in sequence).

![image](https://user-images.githubusercontent.com/48793689/114201817-999ce200-9924-11eb-8469-bc51e7720237.png)

**Comment by cookpete** [comment]
I imagine you are better off hooking up directly to the hls.js events? 

https://github.com/video-dev/hls.js/blob/master/docs/API.md#runtime-events

Right now `onBufferEnd` is just attached to the `playing` event of the `<video>` instance, which it seems isn't very reliable when using HLS.

https://github.com/cookpete/react-player/blob/master/src/players/FilePlayer.js#L56

**Comment by davesargrad** [comment]
@cookpete 

I'll do exactly that.. as soon as I get out of my meeting!! :)

I didnt realize I could hook into them.

**Comment by davesargrad** [comment]
Hmm. not sure its letting me see those events.. this is how i tried to do it

```
const printEvt = (arg) => console.log("Evt: ", arg);

  const getHlsPlayer = (embeddedPlayer) => {
    if (embeddedPlayer.ref.current !== null) {
      const hlsPlayer = embeddedPlayer.ref.current.getInternalPlayer("hls");
      if (typeof hlsPlayer !== "undefined" && typeof hlsPlayer !== null) {
        //console.log ("my on ", hlsPlayer.on);
        hlsPlayer.on(Hls.Events.MEDIA_ATTACHED, (arg) => printEvt({ hls: "onManifest", arg: arg }));
        //console.log("hls player ", hlsPlayer);
      }
      return hlsPlayer;
    }
    return undefined;
  };
```

I've tried both the MANIFEST_PARSED and the MEDIA_ATTACHED_EVENT..

**Comment by davesargrad** [comment]
I do get buffer appending.. so apparently i dont get some of the events that i'd have expected to get.. but others i do
![image](https://user-images.githubusercontent.com/48793689/114214068-dae7be80-9931-11eb-8807-7b1269912a14.png)

**Comment by davesargrad** [comment]
> I imagine you are better off hooking up directly to the hls.js events?
> 
> https://github.com/video-dev/hls.js/blob/master/docs/API.md#runtime-events
> 
> Right now `onBufferEnd` is just attached to the `playing` event of the `<video>` instance, which it seems isn't very reliable when using HLS.
> 
> https://github.com/cookpete/react-player/blob/master/src/players/FilePlayer.js#L56

I want access to the MANIFEST_PARSED event.. it has content that includes the all-critical manifest object (the list of TS files that I'd like to track).

This code gobbles up the args that the API indicates are available.

```
if (this.shouldUseHLS(url)) {
      getSDK(HLS_SDK_URL.replace('VERSION', hlsVersion), HLS_GLOBAL).then(Hls => {
        this.hls = new Hls(hlsOptions)
        this.hls.on(Hls.Events.MANIFEST_PARSED, () => {
          this.props.onReady()
        })
```

The other events that you capture, you pass along in the props callbacks. How can I get access to the manifest?

**Comment by davesargrad** [comment]
I worked this problem till I isolated the culprit (the playlist generation in Jellyfin is buggy). I will close this issue.
