### ISSUE TITLE
Chrome loading issue

### ISSUE THREAD

**Issue by clemclx** [cookpete/react-player#1210]
Hey,

I'm facing an issue while playing multiple videos on same pages and navigating to another page with others videos (using NextJS).

This problem seems to only be on Chrome because it's fully working when I try on Firefox.

**Use case :**

- My homepage display a video wall, where I can hover cards to preview them
- I can navigate to the dedicated page by clicking the card and play this video on his page
- After some video played, no more videos will load and they keeps Pending in chrome Network Tool

I tried to understand what's happening and it seems that previous video requests are not finished, causing Chrome to reach maximum concurrent socket connection.

Am I missing something so that players does not stop connections even when navigating to another page or is it an issue related to Chrome ?

**Env :**

- nextjs @10.0.7 in local dev environment
- react-player @2.9.0
- Chrome version 89.0.4389.114

Thanks in advance.

**Comment by adampl** [comment]
@clemclx How did you resolve this issue?
