### ISSUE TITLE
Soundcloud mobile share url not supported

### ISSUE THREAD

**Issue by obviouscreations** [cookpete/react-player#1211]
When getting a soundcloud url from the soundcloud app it fails to play

**Comment by Yasamato** [comment]
To add a bit more information:
Sharing via mobile apps will generate a URL of the format https://soundcloud.app.goo.gl/MBAd4hAFb1fGXqoLA, which itself is just a redirect to https://soundcloud.com/blossoms-asia/blossoms015?ref=clipboard&p=i&c=0&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing
The final url is playable via react-player.

This I believe should be an issue of soundcloud not react-player, as they give mobile users a link that is not playable via their own [Widget API](https://developers.soundcloud.com/docs/api/html5-widget)...

A possible (but not ideal) workaround would be to prefetch the url and then pass the correct redirected url to react-player.

**Comment by Vo7kov** [comment]
@obviouscreations, as a workaround solution according to @Yasamato's idea:
I'm sending a request with mobile share url, and my backend express server doing next code
<br>
![image](https://github.com/cookpete/react-player/assets/79021164/93f1e094-5a3b-453c-a17d-c36581af0bdd)
<br>
This code makes a `head` request with axios and then graps the `location` header

Hope this may help to someone
