### ISSUE TITLE
Smooth transition between different video sources

### ISSUE THREAD

**Issue by picanumber** [cookpete/react-player#1212]
I'm trying to use the react-player in a way that when the source url for a video changes, the player won't display a black frame or stall. I'm assuming that the network quality is good enough to not cause any problems with this, and the behavior I'm looking resembles "double buffering", i.e. start the new video and only bring it forward when it's ready to "play".

Is there a way to do this, is it planned?

**Comment by the872** [comment]
Depending on your project, you are probably re-rendering the video player, which is causing the "black frame"

First, I would make sure that you are switching to the new video _after_ you have all the data/props loaded. I had a similar issue, when I was setting the switch state too early. The only other thing you can do after that is to use a dissolve CSS transition or something similar to _smooth_ out the transition.
