### ISSUE TITLE
Upgrade to latest HLS.JS

### ISSUE THREAD

**Issue by rossng** [cookpete/react-player#1215]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior

ReactPlayer currently defaults to version 0.13.1 of the hls.js library, which is now over a year old. Version 1.0 (now 1.0.1) was released fairly recently, so it's probably a good time to upgrade ReactPlayer's default version too.

Additionally, as the hls.js API surface is likely to drift over time, it's probably good to make sure everything works properly with the most recent version. I am currently using 1.0 (through specifying `hlsVersion`) and haven't encountered any major issues, though.

#### Expected Behavior

ReactPlayer uses the latest version of hls.js by default.

**Comment by the872** [comment]
const script = document.createElement('script');
    script.src = '/scripts/dash.all.min.js';
    script.async = true;
    document.body.appendChild(script);


Above is what I did  (in my componentDidMount) to localize my Dash dependency -- but you can use it to specify your hls version as well. Below are the notes from the documentation:

> hlsVersion: Override the hls.js version loaded from jsdelivr, default: 0.13.1

> dashVersion: Override the dash.js version loaded from cdnjs, default: 2.9.2

> flvVersion: Override the flv.js version loaded from jsdelivr, default: 1.5.0

**Comment by Yasamato** [comment]
I agree that by default it should ideally include the latest (or tested stable) version and allow backward pinning for compatibility (legacy stuff).

**Comment by luwes** [comment]
closing as outdated
