### ISSUE TITLE
Youtube view count not incrementing

### ISSUE THREAD

**Issue by IniZio** [cookpete/react-player#1217]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior

After I manually play the video til the end, it does not count towards view count. Opening the view in Youtube itself does in same browser session.

#### Expected Behavior

Playing the video in embed should count towards view count as well

#### Steps to Reproduce

1. Open a browser, preferably new IP address
1. Play the embedded the embedded Youtube video, sees the live view count does not increment even after 10 minutes
1.Open the same video in same browser in Youtube, sees the count increment normally after that (~5-10 sec)

#### Environment
- URL attempting to play: 
- Browser: Google Chrome
- Operating system: MacOS Big Sur
- jsFiddle example: https://codesandbox.io/s/compassionate-glitter-r4j26

**Comment by Yasamato** [comment]
I am pretty sure this has nothing to do with react-player, as it just proxies the [YouTube-API](https://developers.google.com/youtube/iframe_api_reference). Did you check that you don't have any extension blocking network requests to YouTube?

**Comment by IniZio** [comment]
It's probably not extension block because I believe those event tracking requests sent to Youtube API. After some experimenting, it seems like if user has autoplay one, the view count will be ignored even if user play again manually after the autoplay.

I think it is not due to react-player but rather how Youtube calculates view count, so I will close this issue. Thanks for your reply @Yasamato!
