### ISSUE TITLE
Full screen seems auto disabled / not working

### ISSUE THREAD

**Issue by newbster1** [cookpete/react-player#1218]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior
The full screen icon seems to appear but on clicking nothing happens, no error pops up.
I am using a webm video , inside chromium CEF and the page is wrapped around an iframe.

The same page when rendered directly, is working on chrome browser.

#### Expected Behavior
Able to work in full screen mode

#### Environment
- URL attempting to play: any webm video url
- Browser: Chromium CEF 
- Operating system: Windows

**Comment by Yasamato** [comment]
I cannot replicate your problem, but react-player does not use any custom player itself for files, but the browsers' own native player. Maybe try checking your settings or browser extensions, that they don't block fullscreen?
