### ISSUE TITLE
Player is not working on Edge 17/18

### ISSUE THREAD

**Issue by lordlpua** [cookpete/react-player#1219]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior

I see a problem with Wistia, if a user using Edge 17 or 18 version. In this case, a video wouldn't work (nodejs 12) Could you add some polyfill?

Error: 'globalThis' is not defined

StopGo#synchronize timed out function (n){return t.suppressPlay()?void n():(t._isPlayPending=!0,t._lastPlayType=void 0,t._lastPlaySource=H(),t._lastPlayIssuedAt=Date.now(),t._lastPlayResolvedAt=null,t._lastPlayRejectedAt=null,t.trigger("playpending",t.lastPlayInfo()),void t.ready((function(){t._calledPlay=!0,t._mozillaAtEnd()&&t.engine.setCurrentTime(0);var o={};e&&!1===t._opts.silentAutoPlay&&(o.silentAutoPlay="allow",t.trigger("clicked-play-before-ready"));var r=function(){t._isPlayPending=!1,t._lastPlayType=void 0,t._lastPlayRejectedAt=Date.now(),t.trigger("playrejected",t.lastPlayInfo()),n()};return i.default.detect.ios.version&&10.1>i.default.detect.ios.version&&!D()&&!t.engine.isInitializingFromUnmuted()?(t.notice("Play rejected because not in user context."),void r()):void(t._playPromise=t.engine.play(o).then((function(e){t._isPlayPending=!1,t._lastPlayType=e,t._lastPlayResolvedAt=Date.now(),"play-silently"!==e||t._inSilentPlaybackMode||(t._inSilentPlaybackMode=!0,t.trigger("silentplaybackmodechange",!0)),n()})).catch((function(e){t.notice(e),r()})))})))}
logger: console
arguments: ["StopGo#synchronize timed out","[Function: <anonymous>]"]

#### Expected Behavior

The player should work with Edge 17/18

#### Steps to Reproduce

1. Install the latest version of the player
2. Use some video link (wistia for example)
3. Try to open it on Edge 17 or 18 version
4. You will see infinite loading
5. Error: 'globalThis' is not defined at the console

#### Environment
- Browser: Edge 17/18
- Operating system: Windows 10

**Comment by Andrew-Jang** [comment]
I have the same issue.

**Comment by cookpete** [comment]
https://github.com/cookpete/react-player/issues/1456#issuecomment-1145780762
