### ISSUE TITLE
Allow custom props to pass through?

### ISSUE THREAD

**Issue by svu-aau** [cookpete/react-player#1221]
Hi @cookpete,

We are using a cookie compliance service (onetrust.com) that blocks all vimeo videos when a site visitor rejects our site cookies.  OneTrust's solution to get around this is to an attribute `data-ot-ignore` to vimeo's <iframe>, for example:

`<iframe src=... data-ot-ignore ></iframe>`

I was hoping I could pass this attribute into <ReactPlayer> and it could inject it into the resulting iframe returned from vimeo, but this doesn't work as expected.

Do you have any suggestions?  I need to inject this data-ot-ignore attribute before the browser renders the iframe; otherwise, the OneTrust code blocks the iframe first.

thanks,
Steve

**Comment by Yasamato** [comment]
I believe (correct me if I am wrong), that this is with the current library not possible. You can however write your own custom wrapper for Vimeo, that automatically adds your required attribute.

But can't you add the attribute `data-ot-ignore` to a parent div of react-player or will this be ignored on child elements?

**Comment by dottodot** [comment]
I've just come across the same issue, @Yasamato did you find a solution to this, currently can't play videos when all cookies are rejected as the iframe gets completely removed, and having `data-ot-ignore` has no effect

**Comment by Yasamato** [comment]
@dottodot sadly not. From my finding you cannot do anything about it without doing some hacking of the API of the Vimeo (or YT) player library or writing your own complete custom handler for playing videos from those sources.
