### ISSUE TITLE
Loading spinner keeps showing when video starts to play in a slow connection

### ISSUE THREAD

**Issue by ebru** [cookpete/react-player#1227]
#### Current Behavior

In a slow internet connection, the loading spinner is stuck even when the video starts to play. It works as expected only you start the video from the beginning when it loads for a while.

#### Expected Behavior

The loading spinner should have been shown when the video is stuck and be disabled when it starts to play again.

#### Steps to Reproduce

You can see the behavior in this screen recording

https://www.youtube.com/watch?v=Crk1iWhOJmY

 which has the following steps;

1. Go to https://cookpete.com/react-player/
2. Select Slow 3G in the network tab
3. Check `Controls`, `Light Mode` and `Files -> mp4`
4. Tap play

#### Environment
- URL attempting to play: https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/360/Big_Buck_Bunny_360_10s_1MB.mp4
- Browser: Google Chrome (Version 90.0.4430.93 (Official Build) (x86_64))
- Operating system: MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
- jsFiddle example: - 

#### Other Information

If this is not considered as a bug, is there anything to apply the expected behavior with the current API? Maybe I'm missing something.

**Comment by ouya99** [comment]
@ebru could you solve your issue

I am facing a similar issue, where i see that the buffer after some 3-4 sec of initial loading time is already filled but still i receive a loading spinner, while there is enough buffer for the video to continue playing.
