### ISSUE TITLE
How do we set starting playback at a specific timecode in vimeo

### ISSUE THREAD

**Issue by sureshdeepalh** [cookpete/react-player#1228]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior
<ReactPlayer
        className="react-player"
        width="100%"
        height="100%"
        onPlay={() => setPlaying(true)}
        onPause={() => setPlaying(false)}
        playing={playing}
        url={`${link}#t=1000s`}
        controls={true}
        onProgress={handleTime}
        onEnded={handleVideoEnd}
      />

When I inspected the page, it show like this my url
https://player.vimeo.com/video/53****679?title=0&byline=0&portrait=0&playsinline=0&autopause=0&app_id=122****3

#### Expected Behavior
Actually what I expect it like this
https://player.vimeo.com/video/53****679**#=1000s**?title=0&byline=0&portrait=0&playsinline=0&autopause=0&app_id=122****3

There should be a way to add **_#t=1000s_** end of the video id.

#### Steps to Reproduce
1. This is the vimeo resource I found to do this. [Link](https://vimeo.zendesk.com/hc/en-us/articles/360000121668-Starting-playback-at-a-specific-timecode )

**Comment by vvarda** [comment]
`onDuration={() => playerState.seekTo(<seconds>, 'seconds')}`
