### ISSUE TITLE
Light Vimeo image dimesnsions?

### ISSUE THREAD

**Issue by jackkemmish** [cookpete/react-player#1231]
Hi there,

I am using the light prop to return the Vimeo thumbnail which works fine. It is returning a small thumbnail rather than a high res one and was wondering if this is a question for here or for Vimeo? Is there an option to choose a different dimension?

#### Current Behavior
Vimeo thumbnail dimesion is tiny.

#### Expected Behavior
An option to choose, or naturally return a higher res image?

Thanks in advance for your help!

Jack

**Comment by jackkemmish** [comment]
Hi, would this be a Vimeo issue or something I can fix within the module? Thanks

**Comment by Sid-Turner-Ellis** [comment]
@jackkemmish Did you sort this out?

**Comment by jackkemmish** [comment]
Hi @Sid-Turner-Ellis I just patched the module locally, not ideal but there was no option to change the returned image dimensions unless I dug into the code.

**Comment by phil-sola** [comment]
@cookpete would you be open to revisiting this and enhancing the preview from 640 for light mode? The thumbnails are tiny & killing the look and feel of the site
