### ISSUE TITLE
webm not working on Safari Browser

### ISSUE THREAD

**Issue by elmcapp** [cookpete/react-player#1235]
I have React Application .webm videos will not play on Safari Browser. Other formats work just not .webm
All it show is a play button with line in the middle.

**Comment by goulkreek** [comment]
Same with HLS urls
(pure <video> tag working well)

**Comment by dmitrymatio** [comment]
I believe it's safari itself and not React player as I have been battling with this issue the entire week.

I'm not an expert but my finding so far is that:

Safari won't play WebM (VP9 codec) but it will play .mov (HEVC h265 codec) as type QuickTime.

Safari might play mp4 files but depends on codec as well and not necessarily with audio. 

If you need transparency, i.e., alpha channel videos, it has to be freshly exported as the previously mentioned HEVC h265 codec .mov file. If you compress/convert it there's a good chance it won't have alpha channel enabled afterward.

**Comment by sonisourabh** [comment]
Facing same issue on Safari 16

**Comment by luwes** [comment]
indeed this is the reason the url accepts an array. so you can define different formats to support all browsers.
Safari doesn't support webm, try mov or mp4.

or move to video streaming like HLS or DASH which offers more benefits.
see https://howvideo.works
