### ISSUE TITLE
The controls prop is passed as true for twitch channels

### ISSUE THREAD

**Issue by harsha2092** [cookpete/react-player#1236]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior
Even though we pass the controls options as false in the React Player, it gets passed as true for twitch streams. 
It is due to this line of code - https://github.com/cookpete/react-player/blob/master/src/players/Twitch.js#L43
I saw the comment at this line pointing to an issue that twitch does not load properly. But I checked recently that twitch is loading properly with controls set as false for streams. Can we change the logic to pass the right prop?

https://github.com/CookPete/react-player/issues/733#issuecomment-549087558

#### Expected Behavior
The prop should be passed properly for twitch streams and we should not see the controls when we pass the above flag as false

#### Steps to Reproduce

1. Pass the controls options as false for twitch stream
2. we should not see the controls but instead we will be seeing the controls

#### Environment
- URL attempting to play: https://www.twitch.tv/alliedesports
- Browser: chrome 90
- Operating system: MacOS Big Sur

**Comment by gatesyp** [comment]
It would be helpful if you could post a JSFiddle recreating the issue

**Comment by markchen555** [comment]
I think we are talking about the same issue and it hasn't been changed for months

[https://github.com/cookpete/react-player/issues/1307](url)
