### ISSUE TITLE
[Support] How to completely load a video before auto-playing to avoid buffering

### ISSUE THREAD

**Issue by rishab-sharma** [cookpete/react-player#1237]
Hi @cookpete , I am new to react and have been trying to solve this issue.
I have a list of video URLs that I want to play sequentially based on user interaction. My application can't afford to buffer so I want to play the video only when it's completely loaded.

Can you please help me in this regard. What props to pass in or how to do this thing.

I also want to look into a solution where I can pre-fetch the next 2 or 3 videos in the sequence, so the transition between video is smooth.

**Comment by maribelmai** [comment]
I would like to know if it's possible as well. Thank you.
