### ISSUE TITLE
Set Pop up Settings Position

### ISSUE THREAD

**Issue by jaypeetancero** [cookpete/react-player#1238]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior
When I click the other settings in the player the pop up appear in the middle of the video player

#### Expected Behavior
If I click the other settings the pop up must appear just above the other settings icon

#### Steps to Reproduce
1. Load the player
2. Click the other settings

#### Environment
- URL attempting to play: https://d17ru6tkeiq9n1.cloudfront.net/videos/99fe0cfc-d139-4c69-92f6-efcd4b9525186052fae1ee4ae82cf0a440b1.webm
- Browser: Google Chrome
- Operating system: Windows 10

#### Other Information
Here's the screenshot
![image](https://user-images.githubusercontent.com/18551764/119599665-09552680-be18-11eb-8036-ee76a74d3ade.png)

**Comment by somangshu** [comment]
Any update on the issue? I might have to ditch the package otherwise in my project 😢 

Let me know if there is a workaround
