### ISSUE TITLE
Only locally saved subtitles work

### ISSUE THREAD

**Issue by OleksandrFomin** [cookpete/react-player#1239]
I'm getting a link for a file with subtitles from an API that I need to insert into the video component. 
```
    <ReactPlayer
        ref={playerRef}
        width="100%"
        height="100%"
        url='https://s3.eu-central-1.amazonaws.com/dev-2-0-content/__id__/Is life meaningless_ And other absurd questions - Nina Medvinskaya (convert-video-online.com).mov'
        pip={pip}
        playing={playing}
        controls={false}
        light={light}
        loop={loop}
        playIcon={<div />}
        playbackRate={playbackRate}
        volume={volume}
        muted={muted}
        onProgress={handleProgress}
        onEnded={handleEnded}
        config={{
          file: {
            tracks: [
              {
                kind: 'subtitles',
                src:
                  'https://s3.eu-central-1.amazonaws.com/dev-2-0-content/__id__/Superman.and.Lois.S01E06.WEBRip.x264-ION10-HI.vtt',
                srcLang: 'en',
                default: true,
                label: 'eng',
              },
            ],
          },
        }}
      />
```

The code above does not give the desired outcome. However, if I download the subtitles file and then add it locally everything works as expected. Is there a way to make the remotely stored subtitles work with ReactPlayer?

**Comment by Ryan-lixuan** [comment]
file: {
                  attributes: {  
                    crossOrigin:'anonymous'
                  }
        },

**Comment by OleksandrFomin** [comment]
> file: {
> attributes: {
> crossOrigin:'anonymous'
> }
> },

Thanks for the reply. 
Unfortunately, the video itself isn't playing if I add the **crossOrigin:'anonymous'** attribute. Any idea why?

**Comment by Ryan-lixuan** [comment]
> > file: {
> > attributes: {
> > crossOrigin:'anonymous'
> > }
> > },
> 
> Thanks for the reply.
> Unfortunately, the video itself isn't playing if I add the **crossOrigin:'anonymous'** attribute. Any idea why?

I didn't have this problem

**Comment by Ryan-lixuan** [comment]
> > file: {
> > attributes: {
> > crossOrigin:'anonymous'
> > }
> > },
> 
> Thanks for the reply.
> Unfortunately, the video itself isn't playing if I add the **crossOrigin:'anonymous'** attribute. Any idea why?

But I have a problem. Do you know how to control the display and hiding of subtitles through a custom button?

**Comment by OleksandrFomin** [comment]
> > > file: {
> > > attributes: {
> > > crossOrigin:'anonymous'
> > > }
> > > },
> > 
> > 
> > Thanks for the reply.
> > Unfortunately, the video itself isn't playing if I add the **crossOrigin:'anonymous'** attribute. Any idea why?
> 
> But I have a problem. Do you know how to control the display and hiding of subtitles through a custom button?

I don't think it's right to discuss multiple issues here but here is how I do it: 

```
const video = document.getElementsByTagName('video')
video[0].textTracks[0].mode = 'hidden'
video[0].textTracks[0].mode = 'showing'
```

**Comment by Ryan-lixuan** [comment]
> video[0].textTracks[0].mode = 'hidden'

sorry,

> > > > file: {
> > > > attributes: {
> > > > crossOrigin:'anonymous'
> > > > }
> > > > },
> > > 
> > > 
> > > Thanks for the reply.
> > > Unfortunately, the video itself isn't playing if I add the **crossOrigin:'anonymous'** attribute. Any idea why?
> > 
> > 
> > But I have a problem. Do you know how to control the display and hiding of subtitles through a custom button?
> 
> I don't think it's right to discuss multiple issues here but here is how I do it:
> 
> ```
> const video = document.getElementsByTagName('video')
> video[0].textTracks[0].mode = 'hidden'
> video[0].textTracks[0].mode = 'showing'
> ```

Sorry, I'm a little worried, I asked a question, but no one answered me, so I ask you for advice, and thank you, the problem has been solved

> > > > file: {
> > > > attributes: {
> > > > crossOrigin:'anonymous'
> > > > }
> > > > },
> > > 
> > > 
> > > Thanks for the reply.
> > > Unfortunately, the video itself isn't playing if I add the **crossOrigin:'anonymous'** attribute. Any idea why?
> > 
> > 
> > But I have a problem. Do you know how to control the display and hiding of subtitles through a custom button?
> 
> I don't think it's right to discuss multiple issues here but here is how I do it:
> 
> ```
> const video = document.getElementsByTagName('video')
> video[0].textTracks[0].mode = 'hidden'
> video[0].textTracks[0].mode = 'showing'
> ```
Sorry, I'm a little worried, I asked a question, but no one answered me, so I ask you for advice, and thank you, the problem has been solved
