### ISSUE TITLE
detect if youtube doesn't play due to privacy/age-restriction

### ISSUE THREAD

**Issue by HelpfulKoala** [cookpete/react-player#1241]
#### Problem

React-player does not seem to reliably fire an error when a youtube video fails to play due to privacy settings or age restrictions.  

#### Current Behavior / Steps to reproduce

_Content heads-up: this issue references videos that are marked private and/or age-restricted.  They contain footage from events at the the U.S. Capitol building on January 6, 2021. As of the creation of this issue, these videos will not play in the react-player._

The following steps are reproducible in chrome on a mac:

1. Go to the [react player demo](https://cookpete.com/react-player/) and enter url of a video that is age-restricted ([example](https://www.youtube.com/watch?v=Zqh47NQtRPU)) or private ([example](https://youtube.com/watch?v=qhIN5E35dZc)) into the `custom URL` text input, then click `load`.  Observe that player displays an error such as one of the following:

![image](https://user-images.githubusercontent.com/77594615/119914367-ccbb2500-bf14-11eb-8b51-80eb2f84e6d9.png)

<img width="451" alt="ReactPlayer Demo 2021-05-27 17-50-47" src="https://user-images.githubusercontent.com/77594615/119914016-3129b480-bf14-11eb-8b62-a5f3fd1ef640.png">

2. Check the browser's javascript console.  Observe that no problems / errors are displayed, e.g.:
```
onReady
onDuration 312
onProgress {playedSeconds: 0, played: 0, loadedSeconds: 0, loaded: 0}
```

3. Now get the URL of a public video ([example](https://www.youtube.com/watch?v=2HFSaxIsJCE)), enter it into the `custom URL` field and click `load`.   Observe the player successfully plays the video.

4. Finally, re-enter the URL of the video in step 2 and press `load` once more.  This time, in the javascript console the message `onError 150` appears.

#### Expected Behavior

Ideally, `onError` would fire every time the video fails to play so that the application could handle it appropriately.

**Comment by HelpfulKoala** [comment]
I haven't investigated this yet but one hypothesis is that the underlying youtube player doesn't throw the error...

**Comment by gordielachance** [comment]
Probably related: https://github.com/cookpete/react-player/issues/1067
