### ISSUE TITLE
How to sync playback with scroll?

### ISSUE THREAD

**Issue by rohitnatesh** [cookpete/react-player#1242]
Hi. Is there a way to sync the playback of video file with the scrolling on the page? Like when scrolled down the video plays the amount scrolled, and the same in reverse when scrolled up.

**Comment by gatesyp** [comment]
Yes, you should be able to do something like that.

1. Calculate the start and end time of your video
2. Take a look at the accepted answer for this SO post to get what % scrolling has happened on a page: https://stackoverflow.com/questions/2387136/cross-browser-method-to-determine-vertical-scroll-percentage-in-javascript
3. Calculate what timestamp the % (from step 2) correlates to (eg your video is 30 seconds long. user is 50% scrolled down the page. you calculate that 50% of 30 seconds is 15 seconds)
4. set the onSeek prop (https://stackoverflow.com/questions/2387136/cross-browser-method-to-determine-vertical-scroll-percentage-in-javascript) to your calculated timestamp (eg 15 seconds)
 


Depending on the nature of the video file you want to use, you might find more success using a GIF.

**Comment by rohitnatesh** [comment]
Will try that, thanks!
