### ISSUE TITLE
Subtitle from remote server not working

### ISSUE THREAD

**Issue by abbes-mebrouki** [cookpete/react-player#1248]
I'm trying to use a subtitle file from another server, but the player is not showing anything.
any suggestions?

thank you.

**Comment by OleksandrFomin** [comment]
Try adding `crossOrigin: anonymous` to your ReactPlayer config. You may also need to adjust the CORS settings on the backend so that it allows cross-domain requests 
      <ReactPlayer
        config={{
          file: {
            attributes: {
              crossOrigin: 'anonymous',
            },
          },
        }}
      />
