### ISSUE TITLE
Player transitions from left of screen

### ISSUE THREAD

**Issue by yarivShamash** [cookpete/react-player#1249]
#### Current Behavior

Hey, I'm using your great video player but encountered one problem which I could not fix. The player "enters" the screen from the left.

#### Expected Behavior

I would like it to keep centered and no transition.

#### Steps to Reproduce

  All I did was to add the video player to the page.

#### Environment
- URL attempting to play: 
- Browser: Chrome, Safari
- Operating system: macOS
- Framework: Next.js version 10.2.0
- codeSandbox example: https://codesandbox.io/s/reactplayervimeoissue-281zo

#### Other Information

Things I'v tried: 
1. Wrapping it in a `<div>`, 
2. Using the `wrapper` attribute 
3. Passing `style={{transition: 'none'}}`
4. Creating .css selectors for 
    .vp-video-wrapper
    .vp-overlay-wrapper
    .vp-overlay-bg
    
     and even
    .vp-overlay-cell
    .vp-overlay-icon-wrapper
    .vp-overlay-icon
    .vp-overlay-logo
    .vp-alert
    .logo
    .hidden
    .player 
    with { transition: none }
    
    in globals.css

**Comment by yoheioka** [comment]
I ran into this issues as well. Ended up using the `onReady()` callback to toggle the visibility.
Something like this:
https://codesandbox.io/s/reactplayervimeoissue-forked-loclh?file=/src/App.js

**Comment by yarivShamash** [comment]
Thanks a lot @yoheioka, this hack handle the issue perfectly!
