### ISSUE TITLE
Show div onProgress

### ISSUE THREAD

**Issue by Deelux** [CookPete/react-player#125]
Hi, 

This is not an issue, but more a question how I should set this up.
I would like to show a div with information after the video has been playing an "x" amount of time.

Could you push me in the right direction?

Kind regards,
Dominic

**Comment by CookPete** [comment]
Hi Dominic,

The main point is to use the `onProgress` event and check the `played` property of the object it fires with, which gives you the fraction of the video that has played.

If you need to check if a number of seconds has elapsed, you also need to use `onDuration` to store the duration, then do a bit of maths to check. Below is a rough example of both checks:

```js
class App extends Component {
  duration = null
  onDuration = duration => {
    this.duration = duration
  }
  onProgress = progress => {
    if (progress.played > 0.5) {
      console.log('Half of the video has now played')
    }
    if (this.duration && progress.played > 30 / this.duration) {
      console.log('30 seconds of the video has now played')
    }
  }
  render () {
    return (
      <div className='app'>
        <ReactPlayer
          url={'https://www.youtube.com/watch?v=Mh5LY4Mz15o'}
          playing
          onProgress={this.onProgress}
          onDuration={this.onDuration}
        />
      </div>
    )
  }
}
```

Hopefully this gets you on the right track.

**Comment by Deelux** [comment]
Yes that definitely gets me in the right direction. Thanks so much for taking the time to write a reply.

**Comment by Deelux** [comment]
Still one last question:
Is there also a way to stop the video from playing when the video reaches a certain time?

**Comment by jeanmichelcote** [comment]
@CookPete In the example you provided, wouldn't the console log the string every second (every update) from the moment it has passed the half mark?:
```
if (progress.played > 0.5) {
      console.log('Half of the video has now played')
    }
```

Wouldn't it?

Let's say we want the console to log the string only once when `played === 0.5`? We know that the actual `played` value could skip `0.5` and just go from `0.487` to `0.523`. Is there a simple way you deal with that?

**Comment by Deelux** [comment]
@jeanmichelcote this is true. The console.log is triggered every second the video is above the used number.

**Comment by CookPete** [comment]
>Is there also a way to stop the video from playing when the video reaches a certain time?

Just store a `playing` boolean in state and set it to false using the same logic:

```js
class App extends Component {
  duration = null
  state = {
    playing: true
  }
  onDuration = duration => {
    this.duration = duration
  }
  onProgress = progress => {
    if (this.state.playing && this.duration && progress.played > 30 / this.duration) {
      console.log('Stop video after 30 seconds')
      this.setState({
        playing: false
      })
    }
  }
  render () {
    return (
      <div className='app'>
        <ReactPlayer
          url={'https://www.youtube.com/watch?v=Mh5LY4Mz15o'}
          playing={this.state.playing}
          onProgress={this.onProgress}
          onDuration={this.onDuration}
        />
      </div>
    )
  }
}
```

**Comment by Deelux** [comment]
Hi again, so I managed to get the div showing! Thanks a lot for your assistance! I now want to do something else which I can't seem to figure out. I have a div ontop of the player that shows a red line, this line progresses as time goes by. I managed to get it to move by linking it to a timestamp I receive from the player. 

Now I was wondering if I am able to make this line the new "progress" indicator, so when people move the line, the video also moves? 

It looks a little like this: 

![e25f79af-2ca8-4688-be53-788a23b482e1](https://cloud.githubusercontent.com/assets/4540876/20932823/451274a0-bbd6-11e6-848a-d3b023af9bc2.jpg)

**Comment by CookPete** [comment]
Hey @Deelux, there is a `seekTo` method you can run on the ReactPlayer instance. How you implement the drag and drop of the slider is up you to, but you just need the fraction of the video you want to seek to (between `0` and `1`). Hopefully this starts you on the right track:

```js
class App extends Component {
  state = {
    playing: true
  }
  onSeek () {
    const fraction = parseFloat(e.target.value)
    this.refs.player.seekTo(fraction)
  }
  render () {
    return (
      <div className='app'>
        <ReactPlayer
          ref='player'
          url='https://www.youtube.com/watch?v=Mh5LY4Mz15o'
          playing={this.state.playing}
        />
        <button onClick={this.onSeek} value={0}>Seek to start</button>
        <button onClick={this.onSeek} value={0.5}>Seek to middle</button>
        <button onClick={this.onSeek} value={0.75}>Seek to 75%</button>
      </div>
    )
  }
}
```

**Comment by Deelux** [comment]
Thank you so much for: 
1. Your great player.
2. Your amazing fast replies.
3. The way you reply, it really helps me understand and use the information in my own build.

Have a great day and do not forget to smile!

**Comment by Deelux** [comment]
Hi @CookPete, 

I managed to get the progress visualised in the <input type="range" /> element. But getting it to work to change the progress in the video is not working. Can you see what I am doing wrong?

This is my code: 
`
import React from 'react';
import ReactPlayer from 'react-player';
import CommentsListBeijing from '../containers/comments-list-beijing';
import { SparkModalBeijing } from "../components/beijing/spark-modal-beijing";
import Fullscreen from 'react-fullscreen';



class Beijing extends React.Component {
	constructor(props){
		super(props);

		this.stopVideo = this.stopVideo.bind(this);
		this.playVideo = this.playVideo.bind(this);
		this.onSeek = this.onSeek.bind(this);

		this.state = {
    		playing: true,
    		timestamp: 0,
    	}
  	}

 	duration = null
	onDuration = duration => {
		this.duration = duration
	}
	onProgress = progress => {
		if (this.duration && progress.played > 1 / this.duration) {
			const timestamp = progress.played * this.duration;
			this.setState({ timestamp })
		}
		if (this.duration && progress.played > 110 / this.duration) {
				if (this.duration && progress.played < 111 / this.duration) {
					console.log('110 seconds of the video has now played')
					this.setState({
        			playing: false
  				})
			}
		}
	}

	onSeek () {
	    const fraction = parseFloat(e.target.value)
	    this.refs.player.seekTo(fraction)
  	}

	stopVideo(){
		this.setState({
			playing: false
		})
	}

	playVideo(){
		this.setState({
			playing: true
		})
	}

   	render() {
		return (
			<div>
				<Fullscreen>
					<ReactPlayer 
						url='https://www.youtube.com/watch?v=8HK0MBLLVO8?wmode=opaque' 
						playing={this.state.playing}
						onProgress={this.onProgress}
			          	onDuration={this.onDuration} 
			          	controls={true}/>
			    </Fullscreen>
				<SparkModalBeijing className="add-spark" timestamp={this.state.timestamp} playing={this.state.playing} playVideo={this.playVideo} stopVideo={this.stopVideo} />
				<input type="range" min="0" max={this.duration} value={this.state.timestamp} onClick={this.onSeek}/>
					<CommentsListBeijing timestamp={this.state.timestamp} activeCity={this.props.activeCity}/>

			</div>
		);
	}
}

export default Beijing;
`

**Comment by CookPete** [comment]
Sorry, my mistake, I forgot to add the `e` parameter to the method definition:

```js
onSeek (e) {
    const fraction = parseFloat(e.target.value)
    this.refs.player.seekTo(fraction)
}
```

Also, don't forget to add `ref='player'` to the `<ReactPlayer />` props.

**Comment by Deelux** [comment]
Aaah of course...! What I don't understand now though, is that when I try to move the input the player goes immediatly to the complete end of the video. But when I console.log the value it does give me the right value. 
What am I missing?

**Comment by Deelux** [comment]
Actually I think I already understand. The seekTo takes % of the total time, so if I give it a big number, it goes automaticly to the end. I think I can fix it now :-)

**Comment by Deelux** [comment]
Yup that was it! Thanks for the push in the right direction, I got it working :-D
