### ISSUE TITLE
onReady is called every time a looped video starts over

### ISSUE THREAD

**Issue by fabyeah** [cookpete/react-player#1253]
#### Current Behavior
`onReady` callback runs every time a `loop` video starts over.

#### Expected Behavior
`onReady` callback only runs once

#### Steps to Reproduce
- Use `react-player/file`
- Set video to `loop`
- `console.log` in `onReady`

#### Environment
- URL attempting to play: File from Google Storage
- Browser: Google Chrome 90.0.4430.212 
- Operating system: MacOS

#### Other Information
Maybe related: https://github.com/cookpete/react-player/issues/760

I want to track views in `onReady` vs the player container component's `useEffect` so as to track only views where the user stayed on the page until the player and video was loaded.

**Comment by cookpete** [comment]
See https://github.com/cookpete/react-player/issues/760#issuecomment-573450913
