### ISSUE TITLE
[Question] Playing two videos syncrhonized

### ISSUE THREAD

**Issue by bmsan** [cookpete/react-player#1254]
Hello,

I was wondering if it is possible to play two videos synchronized (on a frame level) under the following assumptions:

Situation A: both videos are already fully loaded (videos will not stall waiting for data)
Situation B: videos are not fully loaded if one video stalls the other should wait as well

Situation B would be ideal, but I could live with Situation A. What I want to make sure is that I don't have a random delay between the two videos on each run.  I guess this means both players should have a start jitter < 1/ fps(usually 30) so <33ms

**Comment by Yasamato** [comment]
Depends on what type of video vendor you are using I guess. Twitch, YT, Soundcloud etc. you will have a time delay (a short one). I am not certain about raw video files. In theory you could force them to have nearly perfect timing but I am not sure about that. Would need further testing about that one.

What would work (don't know if react-player can) is creating a blob function, which is the source of both videos and returning the same data.

**Comment by bmsan** [comment]
@Yasamato  thanks for your input!
I did some tests(with the html5 video player, not with the react-player):

- Starting/Stopping them in javascript from the same callback showed decent results, but one in ~ 5-10 pauses would show a small desyncronization between the two.
- Using [timingsrc](https://webtiming.github.io/timingsrc/doc/online_mediasync.html) showed extremely good results. ( Without diving into the internals of the solution, I think they are resynchronizing the two sources every ~ 200ms(so every 6 frames @ 30 fps).

**Comment by luwes** [comment]
I've done some research and work on this, Safari is the difficult one not handling playbackRate very well.
I came up with this little library https://github.com/muxinc/media-group with decent results if you want to try.
