### ISSUE TITLE
Improve Core Web Vitals (performances)

### ISSUE THREAD

**Issue by Vadorequest** [cookpete/react-player#1258]
https://blogjolt.com/how-to-embed-youtube-videos-without-sacrificing-site-speed/ is a thorough analysis about how using a Youtube iframe embed affects the Core Web Vitals "Performances" stat negatively.

Currently, react-player supports the "lazy loading" mode. I've tried using it and didn't notice any score improvements whatsoever.

A few stats for Core Web Vitals "Performances":
- Without Youtube embed: 40-75
- With Youtube embed: 22-25
- With Youtube embed using react-player "lazy load" feature: 22-25

Could it be possible to add a mode using the 4th method explained in the above link? Basically don't load the youtube video at all, but display a thumbnail instead, and load the video on click on the player.

Here is a potential implementation: https://www.corewebvitals.io/pagespeed/perfect-youtube-core-web-vitals

Does such idea make sense? CWV has become more and more important and having a way to load videos without negatively affecting websites has become necessary.

**Comment by cookpete** [comment]
>Could it be possible to add a mode using the 4th method explained in the above link? Basically don't load the youtube video at all, but display a thumbnail instead, and load the video on click on the player.

This sounds exactly like what the `light` prop does. https://github.com/cookpete/react-player#light-player

**Comment by Vadorequest** [comment]
Thanks! I had missed that option. Maybe mentioning it around the "lazy load" feature would make sense? I believe it could be highlighted a bit more, as it's a good practice to use it by default, not only for its performance implication but also to reduce network usage on mobile.
