### ISSUE TITLE
TypeError: init is not a function

### ISSUE THREAD

**Issue by stv8** [cookpete/react-player#1262]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

Hello, I'm not sure what's going on, but the component simply isn't working in my `create-react-app` setup. I tried uninstalling and reinstalling all node_modules as well.

#### Current Behavior

- React is erroring whenever I try to use `ReactPlayer`
- I am using it like so
```javascript
import React from "react";
import ReactPlayer from "react-player";
import Box from "@material-ui/core/Box";

export default function Playground() {
  return (
    <Box>
      <ReactPlayer url="https://www.youtube.com/watch?v=iB2RT-hyD58" />
    </Box>
  );
}
```
And receiving this error
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/5158539/121920459-af9c9980-ccfd-11eb-8524-f22ddca5125f.png">

#### Expected Behavior

- I expected the component to work

#### Steps to Reproduce

1. I simply installed the package, imported it into a component, and it fails.

#### Environment
- URL attempting to play: see code snippet above
- Browser: Firefox 90.0b3
- Operating system: MacOS 11.2.3 (20D91)
- `"react-player": "^2.9.0"` (Create React App)
- `React: 16.13.1`

**Comment by TiagoSousa26** [comment]
Same problem but in Windows with React 16.12.0.

**Comment by Mluocheng** [comment]
遇到同样的问题
![image](https://user-images.githubusercontent.com/31057183/142830443-dd15be20-38fb-4029-9d4c-772e579cfbee.png)
这样的配置能够运行。
但是
![image](https://user-images.githubusercontent.com/31057183/142830496-83b7d5c5-05fb-4f7e-bf7c-5cc5ebf00676.png)
这样的配置就会报错：
![image](https://user-images.githubusercontent.com/31057183/142830547-6df55868-277f-4320-8762-9a165cb1c126.png)

**Comment by Adrian-stuff** [comment]
The implementation of React.lazy has changed. React16.13 has no init property，but React16.14 and React17 has init property.

my workaround for this is to fork the repo and update the react version to latest
npm install react@latest react-dom@latest
