### ISSUE TITLE
 Youtube shorts not correctly rendering when copying link from the mobile app

### ISSUE THREAD

**Issue by adrianvillen** [cookpete/react-player#1263]
**Youtube shorts don't seem to work when embedding the link from the  mobile app, they work fine when you copy the link from the desktop or mobile web browser,

This is a standard Shorts URL from the YT mobile app
e.g https://youtube.com/shorts/dlry-0801ba?feature=share**

How can I enable support from this kind of URL?

****

**Comment by rpastorelle** [comment]
I believe all they need to do is swap `shorts` for `embed` in the URL:

https://youtube.com/shorts/dlry-0801ba
becomes
https://youtube.com/embed/dlry-0801ba

**Comment by rpastorelle** [comment]
Did this fix it? https://github.com/cookpete/react-player/pull/1438
