### ISSUE TITLE
Vimeo 500 error after some times

### ISSUE THREAD

**Issue by Energizz** [cookpete/react-player#1264]
#### Current Behavior
When using a long video with Vimeo, it happens after some time (can be more than 30 minutes of videos) that the player just go back the beginning. There is an error shown in the console 500 (attached screenshot)

#### Expected Behavior
The video should keep playing without having rollback

#### Steps to Reproduce
1. Use this video https://vimeo.com/248460715
2. Let the video play for at least 1h (can be shorter)
3. The video should rollback to the beginning and show error attached, in the console 

#### Environment
- URL attempting to play: https://vimeo.com/248460715
- Browser: Chrome 91.0.4472.77 
- Operating system: Mac OS Catalina 10.15.7

#### Other Information

<img width="837" alt="Screenshot 2021-06-15 at 11 12 28" src="https://user-images.githubusercontent.com/4310553/122070777-8875c300-cdf6-11eb-93de-e55eb8819001.png">

**Comment by cookpete** [comment]
I would suggest opening an issue here: https://github.com/vimeo/player.js/issues

**Comment by Energizz** [comment]
Hello,

Thanks for your replay, just for information, a ticket has been opened : https://github.com/vimeo/player.js/issues/736
