### ISSUE TITLE
"The service worker navigation preload request was cancelled before 'preloadResponse' settled. If you intend to use 'preloadResponse', use waitUntil() or respondWith() to wait for the promise to settle."

### ISSUE THREAD

**Issue by yunusfirat** [cookpete/react-player#1265]
Can anyone explain me how can I avoid this error on the console ? I am able to view videos and everything looks good.

**Comment by cookpete** [comment]
Sorry, I don't think this has anything to do with ReactPlayer.

Possibly helpful: https://github.com/GoogleChrome/workbox/issues/2178
