### ISSUE TITLE
onReady fired after seeking file sources

### ISSUE THREAD

**Issue by legraphista** [cookpete/react-player#1268]
#### Current Behavior

onReady is fired whenever .seek() is called

#### Expected Behavior

onReady should be fired only when media is loaded

#### Steps to Reproduce

1. navigate to demo site
1. click on a demo URL that is not a file
1. onReady is only fired once the player is ready
2. click on an mp4 file
3. onReady is fired every time you seek 

#### Environment
- URL attempting to play: https://cookpete.com/react-player/
- Browser: Chrome 91
- Operating system: Linux
- jsFiddle example: -

#### Other Information

There is no event that can be used to distinguish when mp4 files have finished loading

**Comment by cookpete** [comment]
This is a side effect of using the `canplay` event for the `onReady` behaviour of files:

https://github.com/cookpete/react-player/blob/5d38f882b2a885e669fe214a80c7511d461b7601/src/players/FilePlayer.js#L65

After seeking, the video loads and another `canplay` event is fired.

Suggestions on a better way to do this are welcome. For now I supposed you could just add some logic to ignore any subsequent `onReady` calls, until the `url` changes?

**Comment by legraphista** [comment]
> Suggestions on a better way to do this are welcome. For now I supposed you could just add some logic to ignore any subsequent `onReady` calls, until the `url` changes?

Maybe [loadedmetadata event](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/loadedmetadata_event) would be more appropriate for `onReady`?
