### ISSUE TITLE
Cannot read property light of undefined/null expression

### ISSUE THREAD

**Issue by jduijm** [cookpete/react-player#1270]
We caught the following error in our Rollbar:
`TypeError: Cannot read property 'light' of undefined`

`File node_modules/react-player/lazy/ReactPlayer.js?1620385634703 line 104 col 30 in createReactPlayer
showPreview: !!_this.props.light`

#### Expected behaviour
The light prop is false by default and we do not add it as a prop. So we are not expecting this error

#### Environments
Chrome Mobile 89.0.4389
Samsung Internet 13.2

```
const playerConfig = {
  youtube: {
    playerVars: {
      showinfo: 0,
      rel: 0,
      modestbranding: 1
    }
  },
  vimeo: {
    portrait: false,
    byline: false,
    title: false
  }
}


export function VideoEmbed({ src, autoplay, muted, showControls = false }) {
  const [ready, setReady] = React.useState(false) // https://github.com/CookPete/react-player/issues/909
  const { ref, isInViewport } = useIsInViewport({ threshold: [0.66] })
  const [duration, setDuration] = React.useState(0)
  const trackProgressAt = [0.9, 0.75, 0.50, 0.25]
  const trackedProgressRef = React.useRef([])

  return (
    <div {...{ ref }} className={styles.component}>
      <ReactPlayer
        onReady={() => setReady(true)}
        url={src}
        light={false}
        playing={autoplay && ready && isInViewport}
        onStart={() => trackVideoEngage(src, 'started')}
        onProgress={(progress) => handleProgress(progress.playedSeconds)}
        onDuration={(duration) => setDuration(duration)}
        controls={showControls}
        width='100%'
        height='100%'
        config={playerConfig}
        {...{ muted }}
      />
    </div>
  )
```

Thanks for your reply!

**Comment by cookpete** [comment]
> TypeError: Cannot read property 'light' of undefined
>
>File node_modules/react-player/lazy/ReactPlayer.js?1620385634703 line 104 col 30 in createReactPlayer showPreview: !!_this.props.light

I don't understand how `_this.props` can be `undefined` here.

The built file is [here](https://unpkg.com/browse/react-player@2.9.0/lazy/ReactPlayer.js) for reference. 

Does the same problem occur when you use the non-lazy version?
