### ISSUE TITLE
Load/Capture specific timestamps of video

### ISSUE THREAD

**Issue by mikuchels** [cookpete/react-player#1271]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Expected Behavior
I've got a video in a folder which is not being played, but I want to load frames from specific timestamps/frame intervals (every 30 seconds or every 200th frame). I want to use this these frames as thumbnails. 

#### Steps to Reproduce
How should I go about doing it? 

#### Environment
- URL attempting to play: mp4
- Browser: Safari
- Operating system: MacOS Mojave 10.14
- jsFiddle example: https://jsfiddle.net/sv5x3ug1

**Comment by cookpete** [comment]
This would require some kind of static file processing. Way beyond the scope of this project. 

This might get you started: https://stackoverflow.com/a/29806483/1250405
