### ISSUE TITLE
.5px border width adds spacing between video and border

### ISSUE THREAD

**Issue by matejcsok-istvan** [cookpete/react-player#1272]
#### Current Behavior
If I add a border to `react-player` and the width of the border ends with `.5px` than there will be a spacing between the video and the border (top and left side).

#### Expected Behavior
It should display a nice border without any spacing, even if I add a `1.5px` width border

#### Steps to Reproduce
1. Just open the [codesandbox link](https://codesandbox.io/s/reactplayer-sample-forked-xc5gi?file=/src/index.js)

#### Environment
- URL attempting to play: https://vimeo.com/552793693
- Browser: Chrome 91.0.4472.114 
- Operating system: macOS Big Sur 11.4
- codesandbox example: https://codesandbox.io/s/reactplayer-sample-forked-xc5gi?file=/src/index.js

**Comment by cookpete** [comment]
This seems like a browser/CSS quirk, and not something that this library needs to solve.
