### ISSUE TITLE
playerRef TypeScript type?

### ISSUE THREAD

**Issue by franciscojs12** [cookpete/react-player#1273]
TypeScript complains `Object is possibly "null"`.

I'm initializing with `const playerRef = useRef(null);` how should I type this?
If I use type `JSX.Element` then it complains the methods don't exist.

![image](https://user-images.githubusercontent.com/31248802/123704534-1a8cbb00-d83c-11eb-9080-76776eb74aa2.png)

**Comment by cookpete** [comment]
Would `playerRef.current?.seekTo(...)` and `playerRef.current?.currentTime(...)` do the trick?

**Comment by franciscojs12** [comment]
> Would `playerRef.current?.seekTo(...)` and `playerRef.current?.currentTime(...)` do the trick?

I then get another TS complaint: `Property 'getCurrentTime' does not exist on type 'never'.`
![image](https://user-images.githubusercontent.com/31248802/123968486-a2cea580-d98d-11eb-926d-9f62ee02b264.png)
Thank you for taking the time to look into this.

**Comment by franciscojs12** [comment]
Found the solution!
I'm importing `import ReactPlayer from 'react-player';` so when initializing the Ref I need to use that as type like this: `const playerRef = useRef<ReactPlayer>(null);`

And now I get no type errors.
