### ISSUE TITLE
Preload HLS Video and cache first 3 seconds 

### ISSUE THREAD

**Issue by gorfadvijay** [cookpete/react-player#1277]
I'm making a page that has a bunch of HLS videos in a scrollable column. I'd like to be able to tell the player to preload the beginning fragment(s) of the streams of the next few videos so that when I scroll to them, they play instantly.

I can't seem to get this to work with any of the file config params. I saw that support for preload was recently removed but that seems unrelated. Am I missing something here? Thanks!

**Comment by paulincai** [comment]
Hi, what version of HLS are you using? I have just upgraded to 1.0.7(light) and I feel my videos starts lightning fast now.

You can achieve this effect with something like the react-visibility-sensor to trigger the start of preloading and the HLS option you need is described here: https://github.com/video-dev/hls.js/issues/3822#issuecomment-827020315
