### ISSUE TITLE
[Chrome/Android] Media notification persists even after player is unmounted

### ISSUE THREAD

**Issue by fabyeah** [cookpete/react-player#1280]
#### Current Behavior
When a video (longer than 5 seconds) was unmuted and then the player is unmounted, a media session notification will appear: https://developers.google.com/web/updates/2015/07/media-notifications

#### Expected Behavior
When the player is unmounted, any media session notification related to it should disappear. Ideally I don't even want it to appear in the first place.

#### Steps to Reproduce
1. Start a video (muted)
1. Unmute video
1. Navigate away (in your SPA) so player is unmounted

#### Environment
- URL attempting to play: File url
- Browser: Chrome
- Operating system: Android

**Comment by fabyeah** [comment]
As per this comment, when the player is removed, the notification should be removed, which doesn't happen: https://github.com/w3c/mediasession/issues/215#issuecomment-500530575

I also tried setting the player url to an empty string, but that doesn't remove the notification either.

**Comment by GabrielmLinassi** [comment]
Same problem. Looking for a solution as well.
