### ISSUE TITLE
After switching the flv playback address, the previous flv address has been requesting

### ISSUE THREAD

**Issue by SolitaryScripter** [cookpete/react-player#1281]
#### Current Behavior
Using the same player instance, after switching several flv videos, the switched flv addresses will request data in the background, not only the currently playing video
#### Expected Behavior
Only the currently seen flv video request data

#### Steps to Reproduce
1.`<ReactPlayer
            ref={reactPlayRef}
            width={width}
            height={height}
            muted={!state.volume}
            pip={true}
            volume={state.volume/100}
            playing={!state.paused}
            url={url}
            config = {{
              attributes: {
                crossOrigin:"anonymous"
              }
            }} />`
2. setUrl(Some different addresses) 
3. All addresses are requesting

#### Environment
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36

**Comment by adampl** [comment]
@xuehaiouyang Have you found some solution?
