### ISSUE TITLE
getDuration() returning Infinity for webm videos

### ISSUE THREAD

**Issue by ragul02** [cookpete/react-player#1283]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior
 handleDuration = (duration:any) => {
    this.setState({ duration })
  }
 Returning  **Infinity** as duration

#### Expected Behavior
Duration in seconds must be returned

#### Environment
- "react": "^17.0.1",
- Used with Ionic framework

**Comment by Thor1016** [comment]
Hello, you should set video current time to the finally (1e101). and then set video current time to 0, wow,you can get duration, just for webm format,`questionVideoDom.current.seekTo(1e101, 'seconds');
                      questionVideoDom.current.seekTo(0, 'seconds');`

**Comment by tonynguyenit18** [comment]
> Hello, you should set video current time to the finally (1e101). and then set video current time to 0, wow,you can get duration, just for webm format,`questionVideoDom.current.seekTo(1e101, 'seconds'); questionVideoDom.current.seekTo(0, 'seconds');`

This case infinite call on `onReady` sometimes
Any better idea?

**Comment by Thor1016** [comment]
> > Hello, you should set video current time to the finally (1e101). and then set video current time to 0, wow,you can get duration, just for webm format,`questionVideoDom.current.seekTo(1e101, 'seconds'); questionVideoDom.current.seekTo(0, 'seconds');`
> 
> This case infinite call on `onReady` sometimes Any better idea?
Here's my code, everything works fine, hope this helps!
`onReady={e => {
                let duration = e?.getDuration();
                if (duration === Infinity) {
                  questionVideoDom.current.seekTo(1e101, 'seconds');
                } else {
                  setVideoDuration(duration);
                }
              }}`
