### ISSUE TITLE
How Can i put a COVER IMAGE?

### ISSUE THREAD

**Issue by phantodev** [cookpete/react-player#1284]
Guys i am playing a FILE in react-player... and i want put a cover imagem in my player?

Can i?

**Comment by noahsark769** [comment]
@phantoxe I'd recommend passing a url to the poster property for the file player:

```
         config={{
            file: {
              attributes: {
                poster: placeholderImage?.src,
              },
            },
          }}
```

**Comment by itsaalexk** [comment]
Hey , we submitted a PR creating a new component that deals with a similar problem , but basically you can put a cover image adding a URL to the `light` component.
