### ISSUE TITLE
If no thumbnail, set thumbnail as a specific frame from video

### ISSUE THREAD

**Issue by devluked** [cookpete/react-player#1285]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior

I wanted to see if there is a way to automatically set the thumbnail as a certain frame from an mp4 file.

**Comment by iamdhrooov** [comment]
One thing you can try is to set the video URL with a hash time. 
```
<ReactPlayer url={`${url}#t=1.5`}/>
```
It works with HTML5 video tag, so should work here also.

**Comment by cookpete** [comment]
Grabbing an image from a video is outside of the scope of this library, but [it is possible](https://stackoverflow.com/questions/23745988/get-an-image-from-the-video).

Once you have an image, see https://github.com/cookpete/react-player/issues/1029#issuecomment-698809196
