### ISSUE TITLE
Support for HDR videos

### ISSUE THREAD

**Issue by masudhossain** [cookpete/react-player#1288]
I noticed it doesn't support HDR or 4k videos. Any way to get that working with react-player?

**Comment by andycarlson13** [comment]
bump

**Comment by masudhossain** [comment]
bump

**Comment by paulincai** [comment]
Hi, ok this is a react wrapper over the browser native player or other players (e.g. youtube, vimeo etc via their own libraries). This library doesn't play anything, its function/purpose is to wrap a player.
The question now is what do you expect to play an HDR or 4k video, that this library is supposed to wrap?
