### ISSUE TITLE
Mixcloud throws 'postMessage' on 'DOMWindow' error and invalid VidYard url doesn't fire onReady.

### ISSUE THREAD

**Issue by AbrahamLara** [cookpete/react-player#1292]
#### Current Behavior
* Passing a valid Mixcloud url to react-player throws "Failed to execute 'postMessage' on 'DOMWindow'" error message even though the player successfully loads. I noticed this same issue occurred previously with YouTube in this [ticket](https://github.com/CookPete/react-player/issues/508). I'm wondering whether or not the library can do anything about it given this [comment](https://github.com/CookPete/react-player/issues/508#issuecomment-454426112) from the author and if the same fix for YouTube can even apply here.
* Passing an invalid VidYard url to react-player doesn't fire `onReady` (as well as mixcloud) like SoundCloud for example. Also wondering if the library may or may not be able to do something about it.

#### Expected Behavior
* Mixcloud doesn't throw "Failed to execute 'postMessage' on 'DOMWindow'"
* VidYard (and Mixcloud) to call `onReady`.

#### Steps to Reproduce
1. Visit CodeSandbox link (these issues can even be reproduce in the demo site).

#### Environment
- CodeSandbox example: https://codesandbox.io/s/nostalgic-montalcini-phpkg?file=/src/App.js

#### Other Information
Mixcloud error messages:
<img width="1120" alt="mixcloud_errors" src="https://user-images.githubusercontent.com/37315075/128772589-ad4b7034-d365-408f-91f0-99e5bc8ce062.png">

Vidyard error messages:
<img width="1051" alt="vidyard_errors" src="https://user-images.githubusercontent.com/37315075/128772634-11ed85f4-0e51-470f-b691-e43d81938f7b.png">

**Comment by PieterjanDeClippel** [comment]
In case anyone would actually be looking at this...

```
<!DOCTYPE html>
<html>
	<head>
		<script src="https://widget.mixcloud.com/media/js/widgetApi.js" type="text/javascript"></script>
		<script type="text/javascript">
			function loadVideo() {
				const frame = document.getElementById("myframe");
				const player = Mixcloud.PlayerWidget(frame);
				player.ready.then(function() {
					console.warn('player loaded');
				});
			}
		</script>
	</head>
	<body>
		<button onclick="loadVideo()">Load video</button>
		<iframe id="myframe"></iframe>
	</body>
</html>
```

![image](https://github.com/cookpete/react-player/assets/9629574/7cf2773f-1056-48f2-8067-e8084808ff63)

[StackBlitz](https://stackblitz.com/edit/web-platform-n7ujxg?file=index.html)
