### ISSUE TITLE
vimeo video doesn't play

### ISSUE THREAD

**Issue by dshacham** [cookpete/react-player#1302]
Youtube is playing fine. I haven't tried other sources than yt and vimeo, and the latter doesn't even show the play button.

**Comment by AlvesJorge** [comment]
Hi Dana,
My vimeo is working fine.
Are you using a url like this one ? https://vimeo.com/273296828

**Comment by AlvesJorge** [comment]
Wouldn't bet on it, but maybe there is a way.
But i'm glad you found out the reason why it isn't working.

**Comment by keerthiyml** [comment]
Vimeo video plays in local but not in any testing environment. The `https://player.vimeo.com/api/player.js` which is used in React Player for Vimeo videos is throwing (blocked:csp) error.
URL used:  https://vimeo.com/{video_id}

`<ReactPlayer url={'https://vimeo.com/{video_id}'} />`

Any suggestions to fix this?
