### ISSUE TITLE
Full Screen Container?

### ISSUE THREAD

**Issue by mikejw** [cookpete/react-player#1306]
Hi,

This isn't a regular issue or bug report.  I'm just wondering if it's possible to have some control over the full screen mode of youtube videos.  Is it possible to provide a container for the full screen video to load into?  (So that there is a border around the playing video)?

Many thanks

**Comment by Yasamato** [comment]
You would need to have a manual container around it and disable YT-Controls (they are iframe, you have no direct control).

Maybe take a look at e.g. https://www.npmjs.com/package/screenfull

**Comment by Frikster** [comment]
@mikejw You might find [this SO question](https://stackoverflow.com/questions/69897509/keeping-react-player-full-screen-mode-between-videos) and answer useful
