### ISSUE TITLE
Twitch controls not able to hide when controls set to false

### ISSUE THREAD

**Issue by markchen555** [cookpete/react-player#1307]
#### Current Behavior
I want to hide controls from the Twitch stream channel when I set controls props to false but the controls query still shows true. 

#### Expected Behavior
The controls should be hidden when I set the controls props to false. 

#### Steps to Reproduce

1. set controls props to false 
1. inspect the iframe and you will see the controls query is still true. 
1. Twitch stream control still shows

#### Environment
- URL attempting to play:  https://cookpete.com/react-player/
- Browser:  Google Chrome Version 92.0.4515.13
- Operating system: Windows 10

#### Other Information
![Capture](https://user-images.githubusercontent.com/12524076/132069128-b9e12511-39b8-41aa-a97b-91b2d08d4032.PNG)

**Comment by AlvesJorge** [comment]
Mine works fine , when I click the  "Controls" checkbox the iframe source shows appropriately and the player also displays appropriately.

**Comment by markchen555** [comment]
> Mine works fine , when I click the "Controls" checkbox the iframe source shows appropriately and the player also displays appropriately.

If you use the Twitch Test A which is only a video then the Controls check box works fine. If you use the Test C and Custom URL with channel format, ex: twitch.tv/{channel name}, it will not work. 

in the source code:
![image](https://user-images.githubusercontent.com/12524076/132096978-01d5ecab-b300-43d1-8f76-4ce1bf8fc1f4.png)

If the URL is "twitch.tv/{channel name}" which only contains channel name, it will set the Controls props always to true.

**Comment by markchen555** [comment]
some one has the same issue as me 

[https://github.com/cookpete/react-player/issues/1236](url)
