### ISSUE TITLE
Multiple videos on one page, play will trigger all videos to play. 

### ISSUE THREAD

**Issue by MarvinVk** [CookPete/react-player#132]
Hi,

Not sure if it's me or it's really a bug.

I have a page where I load mutiple videos and they all start playing when I change the playings state each video is wrapped in its own video component. I'm using vimeo in this case and they are all different videos.

Hope this helps.

**Comment by MarvinVk** [comment]
Never mind this was my own stupid misstake.

Ik was updating a state also 'onPlay'.

**Comment by ajmccallum** [comment]
How did you get around this? I'm having the same problem and apparently making the same mistake. I have the player in a slider and need to tell all the children to stop playing when the next slide is selected.
