### ISSUE TITLE
Passing component to light param instead of image url

### ISSUE THREAD

**Issue by andrewscofield** [cookpete/react-player#1320]
I'm working on a next.js project, where images are automatically sized and optimized on the backend. Being able to pass a Component to the light parameter would be amazing to be able to use those images to help optimize between mobile and desktop.

**Comment by idiglove** [comment]
@andrewscofield What attributes would those components have? Would they be img tags or something else? Can you elaborate more? Thanks

**Comment by cookpete** [comment]
Fixed by https://github.com/cookpete/react-player/pull/1405 I think?

**Comment by andrewscofield** [comment]
Yes, this looks awesome! Thanks @idiglove for working on this and @cookpete for getting it merged and letting me know about it.
