### ISSUE TITLE
iOS video is not playing with codec H264 and mp4 format

### ISSUE THREAD

**Issue by lala3344** [cookpete/react-player#1325]
Need help to play a video on safari browser on iPad with H264 code and mp4 format
With same props video is playing fine on all other browsers except safari

and using azure storage to deploy videos and blob format

**Comment by dserna-arbolus** [comment]
I have the same issue. Any workaround?

**Comment by cookpete** [comment]
Looks like there is some nuance to H264 on iOS: https://stackoverflow.com/a/13402284
