### ISSUE TITLE
Freeze play hls-video in samsung Tizen OS

### ISSUE THREAD

**Issue by Dead-Master** [cookpete/react-player#1335]
React-player version: 2.9.0
Browser name / version: AppleWebKit / 537.36 (KHTML, like Gecko) 69.0.3497.106/5.5 TV Safari / 537.36
Tizen version: 5.5
TV Samsung: UE43TU7100UXUA

There was a problem with the react-player when playing chls files, the player loads about 1 minute (6-7 chunks), plays them, and then asks for the next one 2-3 times and stops playing anything (seen by the nginx logs). Everything works fine on the simulator in Tizen Studio.

If you need any details, tell me, I will provide

**Comment by rameshep1989** [comment]
@Dead-Master how you're using react player in tizen os as I getting some error and unable to run on simulator
