### ISSUE TITLE
Gap between sound and video

### ISSUE THREAD

**Issue by yosh1** [cookpete/react-player#1341]
Hi, developer.

#### Current Behavior / Expected Behavior
- Using `Seekto`, there is a gap between sound and video.
	```
	playerRef.current.seekTo(playerRef.current.getCurrentTime() - 5.000000, 'seconds');
	```

	```
	<ReactPlayer
              ref={playerRef}
              url={video.url}
              controls={false}
              playing={playing}
            />
	```
- In this case, the video rewinds for 5 seconds, but there is a gap of several seconds in the audio.

#### Environment
- React hooks
- Video on Firebase Cloud Storage

Do you have any solutions?　Thank you.

**Comment by LongLiveCHIEF** [comment]
when you say gap, do you mean the audio starts playing 5 seconds after video, or that they both start playing at the same time, but the audio track is 5 seconds behind the video track?

**Comment by cookpete** [comment]
@yosh1 Does this happen with other videos? Like the [sample mp4](https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/360/Big_Buck_Bunny_360_10s_1MB.mp4)? My guess is that it’s something specific to how Firebase is delivering the data to the browser.

**Comment by yarrichar** [comment]
I'm seeing a similar issue in Chrome (just tried Firefox and it was OK). Although it happens without needing to do seekTo.
There's basically a stutter at the start of the video (always), and then the video lags the audio for the entire video. Interestingly clicking around can fix it (although not if clicking in the first few seconds, seeking back to there causes it de-sync again).

The video file is an MP4, and is coming from a URL.
