### ISSUE TITLE
Missing types declaration

### ISSUE THREAD

**Issue by hoangvu12** [cookpete/react-player#1343]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior
When I try to `console.log` ref, there is `player` property on `ReactPlayer`. But when I try to access to the property, it shows `player does not exist on ReactPlayer`. 

#### Expected Behavior
It should not show the error above.

#### Steps to Reproduce
```ts
 const videoRef = useRef<ReactPlayer>();

console.log(videoRef.current.player) // `player does not exist on ReactPlayer`

  return (
        <ReactPlayer
          ref={videoRef}
        />
  );
```

**Comment by LeftyTak** [comment]
I've used useRef as follows:

`const videoRef = useRef(null)`

`<ReactPlayer
                ref={videoRef}
            />`

And to use seekTo from another class, pass the videoRef:

`<Nav player={videoRef}/>`

And then use "current" to access the seekTo function:

`props.player.current.seekTo(parseFloat(e.target.value))`

This worked for me.

**Comment by chrisdemetriad** [comment]
> Hello
> 
> I don't know this is help you, but I used `callback ref` at similar problem
> 
> ```ts
> const [videoRef, setVideoRef] = useState<ReactPlayer | null | undefined>(null);
> 
> const seekTo = () => {
>   videoRef?.seekTo(someTime);
> };
> 
> return <ReactPlayer ref={setVideoRef} />
> ```

I've done the same thing but my unit tests are failing with "Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?".

**Comment by hyesungoh** [comment]
> > Hello
> > I don't know this is help you, but I used `callback ref` at similar problem
> > ```ts
> > const [videoRef, setVideoRef] = useState<ReactPlayer | null | undefined>(null);
> > 
> > const seekTo = () => {
> >   videoRef?.seekTo(someTime);
> > };
> > 
> > return <ReactPlayer ref={setVideoRef} />
> > ```
> 
> I've done the same thing but my unit tests are failing with "Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?".

I do not know solution about your unit test env

but I recommend [this post about callback ref](https://medium.com/@teh_builder/ref-objects-inside-useeffect-hooks-eb7c15198780)

I hope this will help you
