### ISSUE TITLE
Inquiry: bundle size per player

### ISSUE THREAD

**Issue by mgoldenbe** [cookpete/react-player#1348]
I plan to mostly use the Vimeo player, but could not find information on what the bundle size would be if I include only this player. Also, what would the bundle size be if I use the lazy option and end up using only Vimeo? 

P.S. I think it would be valuable to provide a table with bundle size increase per player.

**Comment by cookpete** [comment]
This is from a fresh `create-react-app` build with `react-player/lazy` imported:

<img width="523" alt="image" src="https://user-images.githubusercontent.com/1926029/155025339-eb00058e-a435-474c-84d2-a5a2be61dda6.png">

Also maybe of interest: https://bundlephobia.com/package/react-player
