### ISSUE TITLE
Video loads, but errors and warnings in the console.

### ISSUE THREAD

**Issue by mgoldenbe** [cookpete/react-player#1349]
I get the following in the console when using the Vimeo player:  

![image](https://user-images.githubusercontent.com/24386790/140882401-33d78b26-741d-4b98-81be-30e841cc0dec.png)

Note that I am not developing an extension, but a Reactjs website.

**Comment by cookpete** [comment]
This looks like an error caused by a `video_toolbar` extension and not something that this library can fix. Maybe open an issue at https://github.com/vimeo/player.js/ ?
