### ISSUE TITLE
Style - Remove style prop - allow className for underlying components

### ISSUE THREAD

**Issue by RemyMachado** [cookpete/react-player#1350]
Css given by the `className` prop is overridden by the default style. Furthermore we can't access the underlying elements' class.

Giving this terrible code:
```typescript
 <ReactPlayer
        className={styles.videoWrapper}
        /* width & height forced by the library style */
        width="inherit"
        height="inherit"
        ...
```
```scss
.videoWrapper {
  video {
    display: block;
  }
}
```

The library should let us conveniently style every layer of the wrapper.

**Comment by cookpete** [comment]
A PR to improve this would be welcome, provided it doesn’t break existing functionality.

**Comment by idiglove** [comment]
Since we can't style iframe elements with just CSS, do we have to target these elements with vanilla js and apply styles to them?

**Comment by mikhail-fedosenko** [comment]
Passing empty string to `width`, `height` properties does the trick - inline styles are not set :)
