### ISSUE TITLE
Pip / Controls Will Not Disable

### ISSUE THREAD

**Issue by gsugambit** [cookpete/react-player#1353]
#### Current Behavior
When I hard code the `pip` and `controls` by hard coding to `false` the pip option is still visible on the screen and the play/pause can still be initiated by clicking on the video

#### Expected Behavior
The pip option would not be available inside the player

## Most of variables for not matter below they are from my source only that matter is pip and controls
import ReactPlayer from "react-player/youtube";

<ReactPlayer
            url={currentVideo.url}
            volume={volume}
            onReady={() => setPlaying(true)}
            onChange={(e) => console.error("onChange: ", e)}
            playing={playing}
            onEnded={(e) => endCurrentVideo(currentVideo, e)}
            onError={(e) => console.error("onError: ", e)}
            pip={false}
            controls={false}

#### Environment
- URL attempting to play: any youtube url
- Browser: chrome or firefox
- Operating system: ubuntu or windows

#### Other Information
Seems impossible to disable. See screenshot below for image of app with above code
/home/gsugambit/Pictures/Screenshot from 2021-11-12 00-12-50.png

**Comment by cookpete** [comment]
`pip` only applies to playing file URLs in certain browsers, as per [the readme](https://github.com/cookpete/react-player#props). We cannot control the controls of other third party libraries (like the Youtube player API).

**Comment by andresdsep** [comment]
I've found that using the `pip` prop doesn't work, but going the long way through `config => file.attributes.disablePictureInPicture = false` does

**Comment by augusta-dev** [comment]
How do we implement this

**Comment by augusta-dev** [comment]
This worked:
config={{
                    file: {
                        attributes: {disablePictureInPicture: true}}
                }}
