### ISSUE TITLE
Error load video link in mobile

### ISSUE THREAD

**Issue by thang148** [cookpete/react-player#1355]
To day. Player not working when run mobile and devtool mobile.

**Comment by PedroAlmeida21** [comment]
It works for me. At least YouTube player.

**Comment by kennethstarkrl** [comment]
Here's what I get for twitch. Works fine on desktop, errors on mobile Android and iOS
![Screenshot_20211121-163329_Chrome](https://user-images.githubusercontent.com/53270830/142781592-85dab73c-8d83-4fa9-8188-06a38f31c1bc.jpg)
