### ISSUE TITLE
onReady not firing for Vimeo Live Event video on iOS

### ISSUE THREAD

**Issue by rluttikhuizen** [cookpete/react-player#1356]
#### Current Behavior
We use the onReady hook to do some initialization (resizing based on video size, show correct background color, etc.) before showing a video. This works fine for all combinations of video sources (YouTube, Vimeo, etc.) and platforms (native Android, native iOS, web, etc.) except for the combination: Vimeo Live Event on native iOS (iPhone and iPad). In that particular combination, the onReady is not fired and therefore our initialization is not executed and the video is not shown. If we use reactplayer to show a "standard" Vimeo video, the `onReady` is fired.

iPhone / iPad with a Vimeo live link (e.g. https://vimeo.com/event/1234567890/0987654321): onReady is not fired.
iPhone / iPad with a Vimeo video link (e.g. https://vimeo.com/1234567890/0987654321): onReady is fired.

On web (also web on iPhone / iPad) and native Android, the onReady is fired for a Vimeo live link.

#### Expected Behavior
That `onReady` is fired for a Vimeo live event video on native iOS.

#### Steps to Reproduce
1. Create a Vimeo live event.
2. Copy the URL, something like https://vimeo.com/event/1234567890/0987654321 or https://vimeo.com/event/1234567890 (depending if it's a public or private video)
3. Initialize ReactPlayer with the onReady hook, e.g. `<ReactPlayer url="https://vimeo.com/event/1234567890" onReady={() => {alert("ready!")}} />`
4. Run on native iOS (iPad or iPhone).
5. The onReady hook is not fired and no alert is shown. When running on native Android or web, the hook is fired and the alert is shown.

#### Environment
React 17.0.2
Ionic React 5.6.12
ReactPlayer 2.9.0
iPhone X with iOS 15.1 or iPad 8th gen with iOS 14.6

#### Other Information
No

**Comment by cookpete** [comment]
Might be worth bringing this up in https://github.com/vimeo/player.js

Looks like there are some possibly related issues with some discussion https://github.com/vimeo/player.js/issues/738
