### ISSUE TITLE
How can we change the audio tracks

### ISSUE THREAD

**Issue by rezapr2** [cookpete/react-player#1361]
I have video file of .mp4 format. It has multiple audio tracks in-built in it.

ReactPlayer is not detecting those audio tracks. Is there any way to target particular audio track.

How to target those audio tracks and how can we change them with ReactPlayer ?

**Comment by cookpete** [comment]
ReactPlayer just renders a basic `<video>` when given an mp4 file. The [`audioTracks` API](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/audioTracks) seems to not be supported at all by major browsers. 

You are probably better off using video.js or something similar: https://docs.videojs.com/tutorial-audio-tracks.html
