### ISSUE TITLE
Progress bar does not behave correctly with dash streams

### ISSUE THREAD

**Issue by LauraGlt** [cookpete/react-player#1365]
#### Current Behavior

<img width="593" alt="Capture d’écran 2021-12-08 à 14 47 56" src="https://user-images.githubusercontent.com/8865932/145219814-42957ab4-fe89-462c-9430-c861d92a5b99.png">

Time on the progress bar is not correct. The "circle" should be almost at the end of the progress bar
And if we pause the video, wait for the livestream to load, we can't move the "circle" at the end of the progress bar to catch up  with the live (it will resume where we paused the video)

#### Expected Behavior

<img width="645" alt="Capture d’écran 2021-12-08 à 15 01 51" src="https://user-images.githubusercontent.com/8865932/145221347-90590b2f-60c2-45ed-85ea-0b0c8e6d7d23.png">

#### Steps to Reproduce

1. Try with url: https://livesim.dashif.org/livesim/periods_60/continuous_1/testpic_2s/Manifest.mpd

#### Environment
- URL attempting to play: https://livesim.dashif.org/livesim/periods_60/continuous_1/testpic_2s/Manifest.mpd
- Browser: Google Chrome Version 96
- jsFiddle example: https://jsfiddle.net/v4ytnguh/

**Comment by cookpete** [comment]
Consider using the `dash.js` suggested control bar along with ReactPlayer (or just use `dash.js` directly)

https://reference.dashif.org/dash.js/v4.2.1/samples/getting-started/controlbar.html
