### ISSUE TITLE
Nothing happens with .wmv videos

### ISSUE THREAD

**Issue by Abisar** [cookpete/react-player#1367]
#### Current Behavior
It doesn't play anything when I open a .wmv video and gives no error.

#### Environment
- URL attempting to play: https://filesamples.com/samples/video/wmv/sample_1280x720.wmv
- Browser: Chrome
- jsFiddle example: https://jsfiddle.net/5jfp26dg

**Comment by arcticfly** [comment]
What was the resolution?

**Comment by vaibhav-toddleapp** [comment]
@abisar how did you fix this issue?
