### ISSUE TITLE
Add support to streaming platform Trovo (https://trovo.live)

### ISSUE THREAD

**Issue by adrenaline681** [cookpete/react-player#1368]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior
Currently React Player doesn't seem to have support for Trovo

#### Expected Behavior
We can use React Player to play streams and videos from Trovo.live

#### Steps to Reproduce
Use one of Trovo.live streaming links in the url. For example:
https://trovo.live/RiotGames

#### Environment
- URL attempting to play: https://trovo.live/RiotGames
- Browser: Chrome
- Operating system: Windows 10

**Comment by cookpete** [comment]
PRs welcome!

https://developer.trovo.live/docs/Embedded.html#_2-embed-player-with-interactive-frame
