### ISSUE TITLE
TypeError: Vimeo.Player is not a constructor

### ISSUE THREAD

**Issue by jordanlambrecht** [cookpete/react-player#1369]
I'm getting the following error specifically with vimeo and twitch, and specifically with my code. Youtube works fine in my local environment and my vimeo link works fine on the demo page. Stack is react, typescript, tailwindcss, and nextjs. I've tried adding the URL hash as suggested elsewhere, switching between player.vimeo.com/video and vimeo.com, making sure the video is set to public with an E rating on it, removing all of the props. The error goes away when I move the url prop. File is a function component. It passes eslint with no issues. I've also tried adding   `const ref = React.createRef()` to the main component and` ref={ref}` as a react-player prop.

`Uncaught (in promise) TypeError: Vimeo.Player is not a constructor
    at eval (Vimeo.js?a009:103)`

Here's my code:
```

import React from 'react'
import next from 'next'
import Link from 'next/link'
import Image from 'next/image'
import ReactPlayer from 'react-player'

function SolaTinyChef() {
  return (
    <main className='max-w-screen'>
      <section className='my-4 lander bg-white' id=''>
        <ReactPlayer
          url='https://vimeo.com/640466563'
          controls
          width='1920'
          height='1080'
        />
      </section>
    </main>
  )
}
export default SolaTinyChef

```

**Comment by jordanlambrecht** [comment]
@cookpete Any ideas? Still getting this error

**Comment by cookpete** [comment]
Do you already have a `Vimeo` global var in your app? You may need to manually load `https://player.vimeo.com/api/player.js` into your app before rendering the player.

**Comment by yuriibut** [comment]
> Do you already have a `Vimeo` global var in your app? You may need to manually load `https://player.vimeo.com/api/player.js` into your app before rendering the player.

The same issue for me. I see  Vimeo script in the head but `window.Vimeo is null`. Fixed by adding Vimeo script manually, but I guess this is a hack and react-player should handle this.

**Comment by cookpete** [comment]
Adding the Vimeo script manually is not really a hack. It is exactly what the [`getSDK`](https://github.com/cookpete/react-player/blob/master/src/utils.js#L77) util is trying to do, but if something in your stack is preventing `window.Vimeo` from being available, I'm not sure what more can be done here.

**Comment by yuriibut** [comment]
@cookpete  this is Vimeo behaviour actually. It won't add Vimeo to global if RequireJS is available.

Check warning section here: https://github.com/vimeo/player.js/blob/master/README.md#installation 

And the code: https://github.com/vimeo/player.js/blob/ccc4d670bf81544710b23c22910ed2f75f62696f/dist/player.js#L4

So the question is:  will `react-player` support pages with RequireJS?

**Comment by yuriibut** [comment]
PS:

`if (window && window.define && window.define.amd) {
  window.require(['https://player.vimeo.com/api/player.js'], (Player) => {
    if (!window.Vimeo) {
      window.Vimeo = { Player };
    }
  });
}`
