### ISSUE TITLE
Feature Request: Styling / Styling Examples

### ISSUE THREAD

**Issue by pateljoel** [cookpete/react-player#1370]
Does react-player offer examples of styling? I can't seem to find any examples of this and the player looks very barebones.

It would be great if some styling examples would be available for the player so that one would know how to do this. 

Thanks,
Joel.

**Comment by pateljoel** [comment]
Are there any examples??

**Comment by Frikster** [comment]
I'd like to second this. Even a link to some project out there using custom styling would be fantastic

**Comment by jordanlambrecht** [comment]
Thirding this
