### ISSUE TITLE
Set YouTube playback rate to values higher than 2x

### ISSUE THREAD

**Issue by farzadmf** [cookpete/react-player#1371]
#### Current Behavior

Cannot set YouTube playback speed rate to a value higher than 2x

#### Expected Behavior

Need to be able to "force" the rate

I think this is a "limitation" of YouTube embed API, but I was wondering if there's a way to get around that limitation, the reason being that there are browser extensions being able to override that value and I was hoping to do the same with `react-player`

#### Steps to Reproduce

An example code would be like this:
```tsx
const [ytURL, setYTURL] = useState("https://www.youtube.com/watch?v=ysz5S6PUM-U");
const [rate, setRate] = useState(1);

<>
  <ReactPlayer url={ytURL} playbackRate={rate} />
  <div>
    <button onClick={() => setRate(1)}>1x</button>
    <button onClick={() => setRate(2)}>2x</button>
    <button onClick={() => setRate(3)}>3x</button>
    <button onClick={() => setRate(4)}>4x</button>
    <button onClick={() => setRate(5)}>5x</button>
  </div>
</>
```
In the example, clicking `1x` and `2x` buttons is working fine, but the other ones seem to be using `2x` as well.

#### Environment
- jsFiddle example: https://jsfiddle.net/farzadm/qs50ju4f/7/

#### Other Information
N/A

**Comment by Yasamato** [comment]
This should be a limitation of [`<iframe>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe). To access the video directly and set the  playback speed to a custom value, you need to have elevated rights (or bypass the browser JS Engine for site JS) like you have with extensions.

Besides that YouTube does not support higher playback rates and has fixed values for the api.

**Comment by farzadmf** [comment]
> you need to have elevated rights (or bypass the browser JS Engine for site JS) like you have with extensions

Can you please elaborate a bit? How can I have elevated rights? How do I bypass the browser JS Engine?

Sorry if those are stupid questions :slightly_smiling_face:

**Comment by Yasamato** [comment]
You cannot, per design, if you are already inside a loaded page. You need to have access to the web browser itself to do that or find a security bug to escape the isolated runtime of the page.

If you would be able to do that on any browser by just running JS inside a webpage, you would likely get a bug bounty by Mozilla, Google or Apple (depending on the browser).

**Comment by farzadmf** [comment]
> you would likely get a bug bounty

Wow, that seems to be serious :laughing: 

So, is there a way I can "mimic" what the extensions do myself (in a safe manner)?

**Comment by Yasamato** [comment]
While still using `<iframe>`? Pretty sure: no.

If you got the video src thou, you could make your own yt-playeresque skin and let it play there. With direct access to the `<video>`, you could do that.

If you want to know how you can extract the video url itself, maybe take a look at the project [yt-dlp](https://github.com/yt-dlp/yt-dlp) on how they do that. (Short answer: it's not that easy, YouTube doesn't like it)

**Comment by farzadmf** [comment]
> it's not that easy, YouTube doesn't like it

That's what I thought 🙁

Thank you @Yasamato for your replies, I'll close this one as this is not necessarily an issue with this library
