### ISSUE TITLE
Vidyard videos with underscore not working

### ISSUE THREAD

**Issue by vipulchadda** [cookpete/react-player#1373]
#### Current Behavior
Any videos with underscore in the UUID are not working as expected. The URL pattern matcher does not include underscore in the UUID which is resulting in wrong UUID being loaded

#### Expected Behavior
Videos should load properly even if there is an underscore in the UUID

#### Environment
- Codesandbox example: https://codesandbox.io/s/sparkling-breeze-rk3hg?file=/src/App.js

**Comment by cookpete** [comment]
Fixed in `2.10.0`
