### ISSUE TITLE
react-player demo is not working for audio files in IOS!

### ISSUE THREAD

**Issue by fpichlou** [cookpete/react-player#1376]
I'm opening demo page in IOS and it's not working in.

I have a propblem in `'play()` event of simple audio tag is react context and I decide to use react-player as a sample.
but It is not working in IOS too!

https://cookpete.com/react-player/

**Comment by cookpete** [comment]
[Things are always going to be awkward on mobile](https://github.com/cookpete/react-player#mobile-considerations). On iOS it seems like it can take a few taps of pause/play and user interaction to get working. It will never be perfect. ReactPlayer may not be the library for you if iOS is your focus.
