### ISSUE TITLE
Blocking web vitals

### ISSUE THREAD

**Issue by FlorisdeG** [cookpete/react-player#1377]
#### Current Behavior
Performing an performance test on a website which includes this library shows the website has blocking elements. Looking further into it, you'll notice that almost all requests made by the react-player library are blocking the website from loading.

#### Expected Behavior
The requests being made are less on non-blocking

#### Steps to Reproduce

1. Create a project with this library
2. Load a video from YouTube (don't know if it's YouTube specific)
3. Perform an webvitals test on the project
4. Notice the requests that are blocking, making the web-vitals slower

#### Environment
- URL attempting to play: https://www.youtube.com/watch?v=5znCkkCSU7c
- Browser: Chrome
- Operating system: Windows
- jsFiddle example: https://jsfiddle.net/3sxzqyLh/

**Comment by cookpete** [comment]
This is something the `light` prop probably helps with. We don’t have much control over how third party libraries load resources.
