### ISSUE TITLE
Console errors when loading any Soundcloud track

### ISSUE THREAD

**Issue by JClackett** [cookpete/react-player#1379]
Getting a load of these errors every time a Soundcloud track is loaded into the player, happens on the demo site as well for reference.

```
[Error] Not allowed to request resource
[Error] Cannot load http://ent/web-sourcemaps/widget-7-5e67950fc23c.js.map due to access control checks.
```

**Comment by cookpete** [comment]
This isn’t happening for me. Is it still happening for you now @JClackett ?

**Comment by JClackett** [comment]
Yeah in safari and chrome I get a load of these in the dev console on the demo site, using the example Soundcloud links. No extensions being used, no content blockers.

<img width="1159" alt="Screenshot 2022-01-21 at 10 18 05" src="https://user-images.githubusercontent.com/12549124/150510074-2e5eb6ab-70c5-4dfb-98aa-50ad6118b9fc.png">
<img width="896" alt="Screenshot 2022-01-21 at 10 17 54" src="https://user-images.githubusercontent.com/12549124/150510079-e40b3673-e622-4bac-a1ad-bc28f9f90cba.png">

**Comment by owensco** [comment]
Happening to me as well. Reproducible on the [demo site](https://cookpete.com/react-player/).
