### ISSUE TITLE
trying to add custom icon but when i click on it video doesnt play

### ISSUE THREAD

**Issue by 27vishwa** [cookpete/react-player#1380]
its not showing background image of that video also.

 <ReactPlayer
      url="https://vimeo.com/243556536"
      width="100%"
      height="500px"
      playing
      volume={1}
      controls
      playIcon={<button>Play</button>}
      light
/>

see this video : https://share.vidyard.com/watch/1nmx483jkaupN2kvBTWwED?

**Comment by cookpete** [comment]
Does `Play` contain an SVG or something that might swallow up a click event? `playIcon` is put inside a `<div onClick={…}>` so something must be preventing that `onClick` from firing.
