### ISSUE TITLE
Twitch clips fail to play

### ISSUE THREAD

**Issue by chozzz** [cookpete/react-player#1381]
This might be related to #607, #777, and #1107

#### Current Behavior
When we provide a twitch clips such as `https://clips.twitch.tv/StrangeRoughClipsdadVoteYea` as a URL, ReactPlayer parses the URL for iframe to be `https://player.twitch.tv?autoplay=false&channel=StrangeRoughClipsdadVoteYea&controls=true&height=100%25&muted=false&parent=staging.gamefaced.gg&playsinline=true&referrer=https%3A%2F%2Fexample.com%2Fnews%2Ftwitch-clips-blog&video=&width=100%25`

And the player does not do anything at all.
According to [this twitch doc](https://dev.twitch.tv/docs/embed/video-and-clips/#non-interactive-frames-for-clips), it has the correct behavior. So with the URL above + the doc, the following should work;
```
<iframe
    src="https://player.twitch.tv/?channel=StrangeRoughClipsdadVoteYea&parent=example.com&muted=true"
    height="720"
    width="1280"
    allowfullscreen="true">
</iframe>
```

But it's **NOT**.

#### Expected Behavior
The player should be able to play the media.

#### Steps to Reproduce

1. Use this as a URL `https://clips.twitch.tv/StrangeRoughClipsdadVoteYea`

#### Environment
- URL attempting to play: https://clips.twitch.tv/StrangeRoughClipsdadVoteYea
- Browser: Google Chrome
- Operating system: Ubuntu
- jsFiddle example: https://jsfiddle.net/sv5x3ug1

#### Other Information
After some digging, the only solution that works for me is the following URL; (Which I got from the `embed` code when you try to access [That original twitch clips link](https://clips.twitch.tv/StrangeRoughClipsdadVoteYea)
- `https://clips.twitch.tv/embed?clip=StrangeRoughClipsdadVoteYea&parent=staging.gamefaced.gg`

**Comment by cookpete** [comment]
If https://github.com/cookpete/react-player/issues/607#issuecomment-477496886 is still the case, there’s nothing we can do about this. Clips simply won’t worth with ReactPlayer.
