### ISSUE TITLE
is there a way to  prevent downloads

### ISSUE THREAD

**Issue by bajoski34** [cookpete/react-player#1383]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Steps to Reproduce

1.
1.
1.

#### Environment
- URL attempting to play: 
- Browser: 
- Operating system: 
- jsFiddle example: https://jsfiddle.net/sv5x3ug1

**Comment by cookpete** [comment]
https://github.com/cookpete/react-player/issues/551#issuecomment-454779788
