### ISSUE TITLE
How dont working local fideo file?

### ISSUE THREAD

**Issue by obj-QED** [cookpete/react-player#1385]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior

Local video dont working (url: blob:http://127.0.0.1:3000/5ed6d3d5-28ee-4815-af0e-b5ce1925684c)
Video dont play

#### Expected Behavior

Hash local video url

#### Steps to Reproduce

1. added local file
1.
1.

#### Environment
-  localhost:3000
- Browser: Chrome
- Operating system: Linux 
- jsFiddle example: https://jsfiddle.net/6ugmjpk0/

#### Other Information

Why when specifying a local file in video player hls does not work. How to fix it?
Video in Network is shown as downloaded and you can get url
Sandbox link: 
https://codesandbox.io/s/quirky-hypatia-qt6rc?file=/src/utils/content.js

**Comment by cookpete** [comment]
See https://github.com/cookpete/react-player/issues/521#issuecomment-440410426

**Comment by obj-QED** [comment]
> See [#521 (comment)](https://github.com/cookpete/react-player/issues/521#issuecomment-440410426)

forceHLS is true, local video dont playing

**Comment by obj-QED** [comment]
@cookpete forceHLS is true, local video not playing
