### ISSUE TITLE
Replay video after x seconds played

### ISSUE THREAD

**Issue by Danicoco** [cookpete/react-player#1386]
#### Current Behavior
I'm able to easily get the number of seconds played using the onProgress props. However, I'll like to replay the video dynamically after reaching a specific number of seconds. Such props is not available.

#### Expected Behavior
A props to replay the video from the beginning 

#### Environment
- URL attempting to play: dataURL from indexDB
- Browser: Firefox
- Operating system: Pop OS Linux

**Comment by cookpete** [comment]
I would just call the `seekTo(0)` instance method when onProgress returns whatever seconds you are after.
