### ISSUE TITLE
Loading a data uri string

### ISSUE THREAD

**Issue by emondssp** [cookpete/react-player#1387]
I would like to load a *data uri string* of the form

```data:audio/wav;base64,UklGRuR+JwNXQVZFZm10IBAAAAAB...```

string into the player. Is that possible without saving it first locally and than load it using ```src```? 

Are there any problems when loading a very long string into the player, e.g. ```1-2 GB``` (w.r.t. buffering...).

**Comment by cookpete** [comment]
Any problems would be exactly the same as loading the same string into an `<audio>` element. That is all that essentially happens when you pass in a data url.
