### ISSUE TITLE
Changing playing prop with multiple sources causes layout shift

### ISSUE THREAD

**Issue by NadiemM** [cookpete/react-player#1388]
#### Current Behavior
It seems, that when passing multiple sources the video player decides which to use based on compatibility/playability. 
If the first source is not supported by the client the second source will be used, if the second source is used. Every time the playing prop is added or removed this decision is taken again. That means if only the second source is supported there is a layout shift happening when adding the playing prop and also the video starts from the beginning. 

#### Expected Behavior
If the first source is not supported the second source will be used, if the second source is used there is supposed to be no layout shift and the video should be shown immediately.  

Instead of removing the playing prop to pause the player, the internal players play() and pause() method can be used to play or pause the player without causing a layout shift. Atleast that's how I was able to remove the problem. 

Here's the link to the fixed bug:

[https://codesandbox.io/s/interesting-brook-u84rf](https://codesandbox.io/s/interesting-brook-u84rf)

#### Steps to Reproduce
Here's the link to the bug:

[https://codesandbox.io/s/clever-carson-kqu9t](https://codesandbox.io/s/clever-carson-kqu9t)

Open the above links in IOS safari, where webm is not supported.

#### Environment
- Browser: Safari
- Operating system: Tablet
The bug is displayed especially on browsers not supporting webm. 

#### Other Information
Possible solution to fix the bug: 
The playing prop should be changed to playing={true} making the player play via the internal players play() function. In addition playing={false} should trigger the internal players pause() function. 
Because the playing prop now has another function, I would suggest to add autoplay as the "old" playing prop, that will add the autoplay attribute on the html5 video tag.

**Comment by cookpete** [comment]
Related to https://github.com/cookpete/react-player/issues/1329#issuecomment-950911520 – The problem is that fact that you are passing in a freshly instantiated array to `url` on every re-render. This is seen as a new URL which is loaded fresh. Notice that if you put `const urls = ["/bunny.webm", "/bunny.mp4"]` outside of `App` and pass in `url={urls}` then the bug does not occur.
