### ISSUE TITLE
Set the start position for playback?

### ISSUE THREAD

**Issue by schittli** [cookpete/react-player#1389]
#### Current Behavior
We would like to allow students to jump to lecture chapters / subjects and it looks like react-player does not allow playback at a predefined position.

#### Expected Behavior
It would be great if we could define the "proposed start position" for Playback.

#### Environment
- URL attempting to play:  Mainly youtube
- Browser: Mainly Chrome
- Operating system: Mainly Windows

Thanks a lot, kind regards,
Thomas

**Comment by cookpete** [comment]
For youtube videos you can use `config.playerVars.start`:

```jsx
      <ReactPlayer
        url='https://www.youtube.com/watch?v=lg8LfoyDFUM'
        playing
        controls
        config={{ playerVars: { start: 10 } }}
      />
```

https://github.com/video-dev/hls.js/
