### ISSUE TITLE
Error running npm install when trying to run the demo on Windows 7 

### ISSUE THREAD

**Issue by federicosan** [CookPete/react-player#139]
Does this really have something to do with the node version?

here is what npm is saying about this... 
------------------------------------------------------

npm WARN prefer global node-gyp@3.4.0 should be installed with -g

> node-sass@4.1.1 install C:\Users\Fede\reactplayerdemo\react-player\node_modules\node-sass
> node scripts/install.js

Cached binary found at C:\Users\Fede\AppData\Roaming\npm-cache\node-sass\4.1.1\win32-x64-48_binding.
node

> node-sass@4.1.1 postinstall C:\Users\Fede\reactplayerdemo\react-player\node_modules\node-sass
> node scripts/build.js

Binary found at C:\Users\Fede\reactplayerdemo\react-player\node_modules\node-sass\vendor\win32-x64-4
8\binding.node
Testing binary
Binary is fine
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts will run only for `npm publish`.
npm WARN prepublish-on-install (In npm@4 and previous versions, it also runs for `npm install`.)
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> react-player@0.14.1 prepublish C:\Users\Fede\reactplayerdemo\react-player
> npm run build:compile; npm run build:browser

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\b
in\\npm-cli.js" "run" "build:compile;" "npm" "run" "build:browser"
npm ERR! node v6.9.1
npm ERR! npm  v4.0.1

npm ERR! missing script: build:compile;
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Fede\reactplayerdemo\react-player\npm-debug.log

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\
fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os"
:"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\b
in\\npm-cli.js" "install"
npm ERR! node v6.9.1
npm ERR! npm  v4.0.1
npm ERR! code ELIFECYCLE
npm ERR! react-player@0.14.1 prepublish: `npm run build:compile; npm run build:browser`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-player@0.14.1 prepublish script 'npm run build:compile; npm run build:b
rowser'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-player package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:compile; npm run build:browser
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-player
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-player
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Fede\reactplayerdemo\react-player\npm-debug.log

**Comment by CookPete** [comment]
Hey @federicosan, try pulling latest `master` and try again.

**Comment by federicosan** [comment]
Hey @CookPete this was with the latest master, maybe the node version is the problem? I don't know what to do.

**Comment by federicosan** [comment]
Hi I updated to the latest node.js and npm but the error persists

C:\Users\Fede\reactplayerdemo\react-player>npm install
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts will run only for `npm publish`.
npm WARN prepublish-on-install (In npm@4 and previous versions, it also runs for `npm install`.)
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> react-player@0.14.1 prepublish C:\Users\Fede\reactplayerdemo\react-player
> npm run build:compile && npm run build:browser


> react-player@0.14.1 build:compile C:\Users\Fede\reactplayerdemo\react-player
> NODE_ENV=production babel src -d lib --ignore src/demo

'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\b
in\\npm-cli.js" "run" "build:compile"
npm ERR! node v6.9.4
npm ERR! npm  v4.1.1
npm ERR! code ELIFECYCLE
npm ERR! react-player@0.14.1 build:compile: `NODE_ENV=production babel src -d lib --ignore src/demo`

npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-player@0.14.1 build:compile script 'NODE_ENV=production babel src -d li
b --ignore src/demo'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-player package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=production babel src -d lib --ignore src/demo
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-player
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-player
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Fede\reactplayerdemo\react-player\npm-debug.log

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\
fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os"
:"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\b
in\\npm-cli.js" "install"
npm ERR! node v6.9.4
npm ERR! npm  v4.1.1
npm ERR! code ELIFECYCLE
npm ERR! react-player@0.14.1 prepublish: `npm run build:compile && npm run build:browser`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-player@0.14.1 prepublish script 'npm run build:compile && npm run build
:browser'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-player package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:compile && npm run build:browser
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-player
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-player
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Fede\reactplayerdemo\react-player\npm-debug.log

**Comment by federicosan** [comment]
The problem was that setting node_env  on windows is different than on linux, prefixing set before every node_env assigment on package.json seems to have fixed the issue.

**Comment by CookPete** [comment]
Try and pull latest `master` again @federicosan. I've added [cross-env](https://www.npmjs.com/package/cross-env) to the scripts to deal with the env variables across environments.

**Comment by federicosan** [comment]
Hi @CookPete  Thanks I wanted to suggest that, great you have already added this thank you.
