### ISSUE TITLE
Controls ON, slider not showing the real duration of a video, only showing the "loadedSeconds"

### ISSUE THREAD

**Issue by JosepSalvat** [cookpete/react-player#1390]
Is it possible to show the entire duration of a video and not the loaded seconds?

Now we've a video of 5min but its showing like this:

![image](https://user-images.githubusercontent.com/88655444/151828981-b723933c-4568-4cce-97a5-950e2dbf8a88.png)

Not showing the entire duration of the video and the "Slider" is in the end. 

Is it possible to make it different? like default way?

Thanks

**Comment by JosepSalvat** [comment]
Any updates?

**Comment by JosepSalvat** [comment]
bump

**Comment by cookpete** [comment]
This does not happen for other video files (like on the demo page). I can only assume this is related to how the video is being served to the browser?

**Comment by JosepSalvat** [comment]
The problem was playing the video in BLOB Url (once is recorded and still not uploaded). I've found that there's a bug in chromium that reads the duration as infinite.

So the trick is to use a function to get the duration of the blob video (get-blob-duration, node_module), change video.currentTime to that duration and then switch it to 0.1

That does the trick and fix the 00:10 (or whatever).
