### ISSUE TITLE
React player is working for if video "codec" type is "h.264", but it is not working for if video 'codec' type is  mpeg4. Here only audio is coming, video is not playing

### ISSUE THREAD

**Issue by kodali444** [cookpete/react-player#1394]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Steps to Reproduce

1. Take some **mp4 video**, Right-click on that video, and go to **properties**. 
2. Go to the audio/video information section.
3. check the video property of the **CODEC**  format.(In my case it is  h.264).
4. **Go to** https://www.video2edit.com/convert-from-video
5.  Upload the **mp4 video** and go to the settings related to video, and **Select video codec**:   'mpeg4' format.
6.  Start converting the video. so it will download the mpeg4 related video.
7.  <ReactPlayer playing={true} controls={false} muted={ismuted}  playsinline width="260" height="180" url='../assets/testing.mp4' />
8. I checked for both mov,mp4 types.  It's working only when **video: codec** type is  h.264  and not working if **video: code**  type is mpeg4
#### Environment
- URL attempting to play: 
- Browser: chrome
- Operating system: ubuntu
- jsFiddle example: https://jsfiddle.net/u9rzv63h/

#### Other Information

``

**Comment by hectorMarrufo** [comment]
I'm having the same issue, i'm (on purpose) using a non supported video codec, but i get no error either on the onError callback or in console, is there any way to catch 'codec not supported' errors?

**Comment by LajosPolya** [comment]
> I'm having the same issue, i'm (on purpose) using a non supported video codec, but i get no error either on the onError callback or in console, is there any way to catch 'codec not supported' errors?

That would be great, the `onError` call back usually doesn't give a lot of useful feedback.

**Comment by cookpete** [comment]
This sounds like just the browser not supporting a certain codec? We are at the mercy of how browsers handle errors with `<video>` elements. I don’t think there’s much we can do here.
