### ISSUE TITLE
[Vimeo Bug]: ReactPlayer: the attempt to load {vimeo url} is being deferred until the player has loaded

### ISSUE THREAD

**Issue by zhaoxing-msft** [cookpete/react-player#1396]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior

Vimeo fast switch bug already be fixed by set `static forceLoad = true` in commit https://github.com/cookpete/react-player/commit/6acf69a02bebe1c526ab3c05d4c6082b2cd1ea09 
but in later commit https://github.com/cookpete/react-player/commit/1752b8dc5b034910530325c1a3068c044c196f84  introduced the bug again, because lazy import can't read  `static forceLoad = true` and caused the bug

#### Expected Behavior

Vimeo fast switch bug being fixed

#### Steps to Reproduce

1. change vimeo video url fast will trigger the bug

#### Environment
- URL attempting to play: 
- Browser: 
- Operating system: 
- jsFiddle example: https://jsfiddle.net/sv5x3ug1

**Comment by cookpete** [comment]
From `2.10.0` you can use the secret `disableDeferredLoading={true}` prop to disable that behaviour completely.

**Comment by jp-albrecht** [comment]
When I use `disableDeferredLoading={true}` I get a console warning. Is there a way I can avoid this?

![image](https://user-images.githubusercontent.com/20053342/170739162-34116d95-ff82-4535-80a1-1bc1eb435bdd.png)

**Comment by EliseiNicolae** [comment]
I got the same error as @jp-albrecht.
