### ISSUE TITLE
Safari having issues With Autoplay

### ISSUE THREAD

**Issue by Aman1706** [cookpete/react-player#1398]
#### Current Behavior
From the video listing page of my website , If I click a video it will not autoplay.
However if I go back to the video listing page and click the video again it will now autoplay

#### Expected Behavior
Videos should always autoplay and not just on the second time 

#### Environment
- Browser: Safari
- Operating system: Mac OS

**Comment by zaqisilverano** [comment]
same for me, I have this issue +1

**Comment by cookpete** [comment]
Have you tried muting the video you are playing? My assumption is Safari cracking down on unmuted autoplaying videos (much like Chrome and others)

https://bitmovin.com/autoplay-policies-safari-14-chrome-64/

**Comment by Aman1706** [comment]
I have tried that but no luck

Chrome and firefox work perfectly though without mute

I think safari maybe has permission issues with the format of the videos being served.

**Comment by cookpete** [comment]
@Aman1706 Please reopen the issue when you have a jsFiddle or similar that demonstrates the problem.

**Comment by fcpauldiaz** [comment]
@Aman1706 were you able to solve the issue ?
