### ISSUE TITLE
New Direct links from vimeo is not working

### ISSUE THREAD

**Issue by mayander30** [cookpete/react-player#1399]
Vimeo changed the direct links from the api now returns like it

https://player.vimeo.com/progressive_redirect/playback/675622290/rendition/360p?loc=external&oauth2_token_id=1406393538&signature=1545279f8150f119095ae76eb3326158500e1a9f3b2df1ed271917f4e3d0af2d

this links works fine in a <video> tag html, but not works in this library..

**Comment by stanimal** [comment]
I'm seeing the same issue. React player is using the Vimeo API to fetch the video; it is returning a 404 with the new format.  This could be an issue on Vimeo's API side...

**Comment by Fyb3roptik** [comment]
Same issue here!

**Comment by mayander30** [comment]
Yes, me too, I am using the embed link, but is not the solution for me, maybe we need use other lib.

**Comment by Fyb3roptik** [comment]
Let me know if you find one

**Comment by cookpete** [comment]
This is only broken because Vimeo have decided not to include `.mp4` or some other sensible extension in their links to external video files. Very annoying. Publishing a fix shortly.

**Comment by garciabruno** [comment]
Any updates on this?

**Comment by cookpete** [comment]
I’m publishing a new version soon that includes a fix for this (plus loads of other recent fixes).

**Comment by aaronetales** [comment]
@cookpete Do you have an estimate as to the release to the master branch?

**Comment by Fyb3roptik** [comment]
I already removed this component as I cannot afford for this to happen again.

**Comment by iiKulakov** [comment]
Same issue, waiting for update...

**Comment by dohomi** [comment]
I receive following error on Vimeo videos, is that related? Vimeo videos are not loading at all while Youtube works.
```js
next-dev.js?3515:32 TypeError: t.replace is not a function
    at u (player.js:2:1049)
    at player.js:2:10858
    at new Promise (<anonymous>)
    at new Player (player.js:2:10370)
```

**Comment by Fyb3roptik** [comment]
> I receive following error on Vimeo videos, is that related? Vimeo videos are not loading at all while Youtube works.
> 
> ```js
> next-dev.js?3515:32 TypeError: t.replace is not a function
>     at u (player.js:2:1049)
>     at player.js:2:10858
>     at new Promise (<anonymous>)
>     at new Player (player.js:2:10370)
> ```

Yes

**Comment by mayander30** [comment]
@cookpete Any chance to solve this issue ?

**Comment by dohomi** [comment]
is there a workaround at the moment?

**Comment by Fyb3roptik** [comment]
> Workaround is to manually add video like so
> 
> ```
> <video
>      width="100%" height="100%"
>      controls={true}
>      autoPlay
>      src={videoUrl} />
> ```

@dohomi I posted one above

**Comment by LC43** [comment]
is it `url` right @Fyb3roptik  ?

**Comment by cookpete** [comment]
Fixed in `2.10.0`. Sorry for the delay all.

**Comment by LC43** [comment]
thank you for your hard work @cookpete !

**Comment by keerthiyml** [comment]
Facing this issue again. However vimeo videos work locally but not in any environments. Any suggestions?
