### ISSUE TITLE
MP4 file autoplays when playing props is set to false

### ISSUE THREAD

**Issue by clementoriol** [CookPete/react-player#14]
Hi,
Thanks for the player, it looks promising.

There's an issue with mp4 files, they autoplay even if `playing={false}` is passed as a prop.

It's related with the `play()` call in `players/Base.js` `componentDidMount`.
It seems required to init some players (Youtube, SoundCloud...) since they're initialized in the play method. Maybe moving the initalization part in a separate method, and calling this in `componentDidMount` could avoid this issue.

**Comment by CookPete** [comment]
Hi @clementoriol, good spot!

This will be fixed once https://github.com/CookPete/react-player/pull/13 is merged, as all the mounting/playing logic is being changed there. I'll merge it soon.

**Comment by CookPete** [comment]
Fixed in [0.3.0](https://github.com/CookPete/react-player/releases/tag/v0.3.0)
