### ISSUE TITLE
Callback conflict with multiple Vimeo ReactPlayers on the same page

### ISSUE THREAD

**Issue by nikolas** [CookPete/react-player#140]
### Expected Behavior
The onProgress and onDuration callbacks for different ReactPlayer instances don't interact with eachother.

### Actual Behavior
Any onProgress or onDuration callback gets called when multiple Vimeo ReactPlayers are on the page.

### Steps to Reproduce
Render these two components to a page:
```js
export default class PlayerA extends React.Component {
  render() {
    const url = 'https://vimeo.com/189968214';
    return <ReactPlayer url={url} onDuration={this.onDuration} />;
  }
  onDuration(duration) {
    console.log('onDuration A', duration);
  }
}

export default class PlayerB extends React.Component {
  render() {
    const url = 'https://vimeo.com/196277011';
    return <ReactPlayer url={url} onDuration={this.onDuration} />;
  }
  onDuration(duration) {
    console.log('onDuration B', duration);
  }
}
```
"onDuration A" gets called twice, once correctly, and once with the incorrect duration, coming from PlayerB.

**Comment by pwbrown** [comment]
On a similar note I am also experiencing the "onPlay" event being called on one video when another video has started playing.  This does not happen with Youtube videos, but as soon as I switched to Vimeo the interaction between multiple videos on a page starts colliding.

**Comment by CookPete** [comment]
Hopefully this is fixed by [migrating to the new Vimeo API](https://github.com/CookPete/react-player/commit/f262c1e87be887d06c01217bc86a6f55dc90085e). If not, feel free to reopen.
