### ISSUE TITLE
forceDASH does not appear to provide dash.js controls for live playback

### ISSUE THREAD

**Issue by Frikster** [cookpete/react-player#1400]
#### Current Behavior
```js
<ReactPlayer
    url={'https://livesim.dashif.org/livesim/testpic_2s/Manifest.mpd'}
    id='react-player'
    className={ `player-screen${className ? ` ${className}` : ''}` }
    height='auto'
    config={{
      file: {
        forceDASH: true,
      }
    }}
  />
```
  
This above code works and live streams the url with native controls if I set `controls={ true }`, but I do not want native controls I want to use [dash.js](http://reference.dashif.org/dash.js/v4.2.1/samples/dash-if-reference-player/index.html#)'s player which as per their example and the exact same url provides controls including a "live" button:
  
![image](https://user-images.githubusercontent.com/10172142/153962173-eb452151-1a52-4275-8848-c0a6859119a1.png)

#### Expected Behavior
I expect the following config code to provide dash.js player controls for the https://livesim.dashif.org/livesim/testpic_2s/Manifest.mpd url. Perhaps I am misunderstanding the documentation?

```
config={{
      file: {
        forceDASH: true,
      }
    }}
```

#### Steps to Reproduce
Just open the jsFiddle below and explain to me why I don't see dash.js controls. I am missing something trivial? Clarification appreciated.

#### Environment
- URL attempting to play: https://livesim.dashif.org/livesim/testpic_2s/Manifest.mpd
- Browser: Version 1.27.109 Chromium: 92.0.4515.115 (Official Build) (64-bit)
- Operating system: Pop!_OS 21.10
- jsFiddle example: https://jsfiddle.net/1ns4w0eo/ - see comment

**Comment by cookpete** [comment]
ReactPlayer uses the raw `dash.js` library to play dash streams within a regular `<video>` component. What you are referring to looks like the dash.js example with the Akamai control bar, an example of which is here: https://reference.dashif.org/dash.js/latest/samples/getting-started/controlbar.html

You should be able to use the same control bar with ReactPlayer, just replace the `<video>` in the example with a `<ReactPlayer>` with a dash stream.
