### ISSUE TITLE
How can I get metrics from React Player?

### ISSUE THREAD

**Issue by nosed07** [cookpete/react-player#1401]
I cannot check streaming metrics like bandwidth, fps or latency when watching content through React-player

#### Expected Behavior
Function/button to show/hide different metrics like bitrate, latency, fps...

#### Environment
- URL attempting to play: hls content on a remote server 
- Browser: chrome
- Operating system: windows

#### Other Information
I could not find any info in the documentation about metrics

**Comment by cookpete** [comment]
This depends entirely on the [type of video being played](https://github.com/cookpete/react-player#supported-media) and is beyond the scope of this library.

**Comment by nosed07** [comment]
Thanks for your answer, I am playing hls content. So as per your answer I am assuming I should take a look to hls.js and see how to print this metrics on screen, right?

**Comment by hoetmaaiers** [comment]
@nosed07 could you in a few words answer your own question? The hls metrics like latency would be pretty interesting. How are the availlable from react-players instance?
