### ISSUE TITLE
Vertical videos are rotated by 90degrees.

### ISSUE THREAD

**Issue by bhargavAtTTT** [cookpete/react-player#1407]
#### Current Behavior
Some vertical videos are rotated by 90 degrees while playing in react player. But not every vertical player.

#### Expected Behavior
I was expecting all the vertical players to be played vertically.

**Comment by SolidLoL** [comment]
I will make a function to know if the window is vertical or not to put the 100vw or 100vh depends on that change the width and height  .... 
`window.addEventListener("orientationchange",()=>{   /*change the state of the video width and height */ })`
