### ISSUE TITLE
Sometimes when I try to play a video I get "This ad used too many resources for your device, so Chrome removed it."

### ISSUE THREAD

**Issue by adrenaline681** [cookpete/react-player#1409]
#### Current Behavior
On some ocassions when I try to play a video using React Player I get an error in the player saying:   
`Ad removed. Details`

And when I click on Details it says:
`This ad used too many resources for your device, so Chrome removed it.`

The videos that I try to play have no ads enabled in youtube, so I'm not sure why it showing this error.

![image](https://user-images.githubusercontent.com/12194431/155685072-8d7ccd52-556a-48e7-bdc3-74d2db6097bf.png)

#### Expected Behavior
Video to play without any error

#### Steps to Reproduce
```
 <ReactPlayer
      url={`https://www.youtube.com/watch?v=aipJGb76fZY`}
      playing={true}
      controls={true}
      width={'100%'} height={'100%'}
  />
```

#### Environment
- URL attempting to play: https://www.youtube.com/watch?v=aipJGb76fZY
- Browser: Chrome
- Operating system: Windows 10

**Comment by Antongron** [comment]
Have you managed this problem?

I got the same

**Comment by manishsharma004** [comment]
@adrenaline681 @Antongron are you using any overlay over the videos due to which users is not directly able to interact with the youtube video in iframe, for example you may have created your own controls that is appearing over the react player.
