### ISSUE TITLE
Black borders (background) problem with responsive configuration.

### ISSUE THREAD

**Issue by jpresaor** [cookpete/react-player#1413]
#### Current Behavior
Configuring the player for responsive behavior, I can see black borders (black background).

#### Expected Behavior
The video fills 100% of the player without any black border.

#### Steps to Reproduce
Open responsive view in brower and decrease or increment screen size.

#### Environment
- Browser: Chrome Versión 98.0.4758.109 (Build oficial) (arm64)
- Operating system: MacOs Big Sur / Linux
- jsFiddle example: https://jsfiddle.net/e6w3rtj1/

**Comment by cookpete** [comment]
See https://github.com/cookpete/react-player/issues/1168 or https://github.com/cookpete/react-player/issues/660 or https://github.com/cookpete/react-player/issues/1003

**Comment by jpresaor** [comment]
> See #1168 or #660 or #1003

@cookpete these solutions are not working to me. I am testing it in documentation JSFidlle link too (https://jsfiddle.net/xfsc3abz/)
This code is not applying styles to 'video' element:
`config={{
      file: {
        attributes: {
          style: {
            width: "100%",
            height: "100%",
            objectFit: "cover",
          },
        },
      },
    }}`
Any idea?

**Comment by cookpete** [comment]
Ah ok I was thinking of a different issue. That config will only work with file paths. Sorry.

What version of ReactPlayer are you using? Black background were removed in `v1.13.0` – https://github.com/cookpete/react-player/commit/7779d8bae64aee4c3a4023587a4a1eacc50d2c98

**Comment by jpresaor** [comment]
I am using 2.9.0

**Comment by LucasKunz** [comment]
Hi @jpresaor, did you manage to solve the problem?

**Comment by javierdebug** [comment]
Similar issue :( , any updates or workaround to solve it?
