### ISSUE TITLE
Nextjs - Optimized Light video preview using Image component or something like that 

### ISSUE THREAD

**Issue by santyas** [cookpete/react-player#1414]
#### Current Behavior
Workin with Nextjs, `light` preview image is loading at the beginning of page load like a normal image but not caching or when it's on the viewport as expected using next/image.

#### Expected Behavior
Maybe add an Image component to `boolean | string`

#### Steps to Reproduce
Im not able to reproduce it sorry

https://nextjs.org/docs/basic-features/image-optimization

**Comment by VitalikMelnyk** [comment]
Yeah
I have the same issue, need to help with this.

**Comment by kb1995** [comment]
I'd love to have this feature as well. Maybe the ability to add a custom component to the light prop. Something like:

```
light={<Image src={video.thumbnail_url} />}
```

**Comment by brianpmaher** [comment]
Looks like this might be possible, just not documented: https://github.com/cookpete/react-player/blob/master/src/Preview.js#L62
