### ISSUE TITLE
How to change the subtitles' style with React Player?

### ISSUE THREAD

**Issue by kinson603** [cookpete/react-player#1422]
With native HTML video element you can just use simple css (i.e.: video::cue) to adjust the styles for the subtitles, like font size, color, line height, etc.

How do you do that with react player? the "style" prop only adds an inline style to the video itself and does not affect the track elements

**Comment by cookpete** [comment]
Just use the `className` prop and do 

```css
.my-player-class video::cue { 
  color: red; 
}
```

Example: https://jsfiddle.net/5me7gf4y/
