### ISSUE TITLE
Issue on Dailymotion link regex

### ISSUE THREAD

**Issue by Maxou44** [cookpete/react-player#1430]
#### Current Behavior
This valid link is not recognized as a Dailymotion link and the React Player fallback on the video element:

http://www.dailymotion.com/video/xdni1e_l-histoire-etrange-1_creation#.UXRVsbXwn90

#### Expected Behavior
Ignore dot or # character in the Dailymotion regex, to display it correctly.

**Comment by RobertoLlopis** [comment]
Hello. 

We are a team from Alicante (Spain) enjoying hacktober fest and chose your repo to try to give our little contribution.

Hope everything is ok with that.

**Comment by Maxou44** [comment]
Same issue with a "?" character on this URL: "http://www.dailymotion.com/video/x4sznp_henri-edmond-le-nouveau-voisin-uk-s_creation?search_algo=2#.UZ-XHYJ1ZGE". For Dailymotion, I think we should remove anything after the "?" or "#".

**Comment by Maxou44** [comment]
Thanks for the fix!

**Comment by cookpete** [comment]
Published in `v2.11.1`
