### ISSUE TITLE
Support for TikTok vidoes

### ISSUE THREAD

**Issue by OrenMag** [cookpete/react-player#1434]
#### Current Behavior
No support for tikTok vidoes

#### Expected Behavior
Support them

#### Steps to Reproduce
Add tiktok video
Error is received.

#### Environment
- URL attempting to play:  https://www.tiktok.com/@synthezaofficial/video/7066882335261674753?is_from_webapp=1&sender_device=pc
- Browser: Chrome
- Operating system: Mac

**Comment by cookpete** [comment]
Duplicate of https://github.com/cookpete/react-player/issues/1193
