### ISSUE TITLE
Warning: Allow attribute will take precedence over 'allowfullscreen'.

### ISSUE THREAD

**Issue by magnattic** [cookpete/react-player#1444]
#### Current Behavior
Using the lib in nextjs with react 18, I get the following warning in the browser console:

> Allow attribute will take precedence over 'allowfullscreen'.

This is the code:

```
<ReactPlayer
  url={source}
  loop
  muted
  playing
  playsinline
  controls={false}
  className={styles.video}
  width="100%"
  height="100%"
  data-chromatic="ignore"
/>
```

#### Expected Behavior
No warning

#### Environment
- Browser: latest Chrome
- NextJS: 12.1.5
- react-player: 2.10.0
- react: 18.0.0

#### Other info
This might be relevant: https://stackoverflow.com/questions/57665508/how-to-resolve-allow-attribute-will-take-precedence-over-allowfullscreen-warni

**Comment by cookpete** [comment]
Fixed in `2.10.1`
