### ISSUE TITLE
cannot use pip mode on android chrome

### ISSUE THREAD

**Issue by WindBise** [cookpete/react-player#1445]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior

There is no pip button on android chrome while there is pip button on mac chrome

#### Expected Behavior

Threre should be pip button and can enter to pip mode

#### Steps to Reproduce

1. open chrome on android 11
2. open https://cookpete.com/react-player/
3. there is no pip button 

#### Environment
- URL attempting to play: 
- https://cookpete.com/react-player/
- Browser: 
- chrome 100
- Operating system: 
- android 11

**Comment by cookpete** [comment]
[This](https://caniuse.com/picture-in-picture) covers all the support and nuances of pip in various browsers.
