### ISSUE TITLE
Play a video a specified number of times

### ISSUE THREAD

**Issue by jf133** [cookpete/react-player#1446]
Hello -- 

Is there a way to play a video a specified number of times? i.e. 3 times and then stop?

If so, is there a way to provide a sample of how?

Much appreciated!
JF

**Comment by cookpete** [comment]
You could use the `onEnded` callback prop to `seekTo(0)` and increment a count stored in local state. Then when the count gets to a certain number, just don’t call `seekTo`.

**Comment by jf133** [comment]
Why not build support for this ?
