### ISSUE TITLE
React.StrictMode breaks youtube player

### ISSUE THREAD

**Issue by samburgers** [cookpete/react-player#1447]
#### Current Behavior
Youtube Video doesn't play when using `React.StrictMode`

#### Expected Behavior
Expect video to play

#### Steps to Reproduce

1. Wrap ReactPlayer (or entire App) in `<React.StrictMode>`
2. Add custom buttons to toggle `playing` prop
3. Attempt to start video by clicking custom play button

#### Environment
- URL attempting to play: https://www.youtube.com/watch?v=oUFJJNQGwhk
- Browser: Chrome + Firefox latest
- Operating system: MacOS
- sandbox example: https://codesandbox.io/s/proud-butterfly-jk25fr?file=/src/App.tsx

#### Other Information
Vimeo and direct mp4 URL's seem to work ok. Just youtube

**Comment by sutt** [comment]
+1
Seeing this behavior on a similar library: https://github.com/tjallingt/react-youtube 
(as of this week)

**Comment by jmaguirrei** [comment]
Same issue here

**Comment by cookpete** [comment]
I believe this is fixed in `react@18.1.0` and `react-dom@18.1.0`. Reopen with more details if this is not the case.

**Comment by sutt** [comment]
I believe I have and continue to be on 18.1
```
{
  "name": "frontend-v2",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@react-icons/all-files": "^4.1.0",
    "@testing-library/jest-dom": "^5.16.4",
    "@testing-library/react": "^13.1.1",
    "@testing-library/user-event": "^13.5.0",
    "react": "^18.1.0",
    "react-dom": "^18.1.0",
    "react-scripts": "5.0.1",
    "react-youtube": "8.3",
    "web-vitals": "^2.1.4"
  },
```

**Comment by samburgers** [comment]
Have updated to React 18.2 and seems to be fixed. Thanks

https://codesandbox.io/s/falling-sunset-pwudld?file=/src/App.tsx
