### ISSUE TITLE
Is there a way to have Dynamic Thumbnails when hovering over the progress bar 

### ISSUE THREAD

**Issue by akshit-dev101** [cookpete/react-player#1451]
I am trying to implement the dynamic thumbnails when the user hovers over the progress bar, just like on youtube, is there any method or a workaround or is this feature planned for future. 
![image](https://user-images.githubusercontent.com/67471383/167090180-6554415c-2e0f-4f2e-a015-051a5d4c302d.png)

**Comment by cookpete** [comment]
This library is just a proxy for various different third party players. The only controls are whatever is provided by the third party player library. Something like this is beyond the scope of ReactPlayer.

This might help you achieve it with something like `video.js`: https://stackoverflow.com/questions/59444862/how-to-generate-video-thumbnails-and-preview-them-while-hovering-on-the-progress
