### ISSUE TITLE
ref methods not working when using dynamic import with nextjs

### ISSUE THREAD

**Issue by inderrr** [cookpete/react-player#1455]
Current code=>
```javascript
import dynamic from "next/dynamic";
const ReactPlayer = dynamic(() => import("react-player/lazy"), { ssr: false });

          <ReactPlayer
              config={config}
              ref={player}
              width="100%"
              height="600px"
              url="//vjs.zencdn.net/v/oceans.mp4"
              muted={true}
              playing={playing}
              controls={true}
              onProgress={}
             />
```
#### Current Behavior
Ref methods like `player.current.getCurrentTime();` are not working when using dynamic imports with nextjs. Whenever I use methods which are available by assigning ref, I get this error
`TypeError: player.current.getCurrentTime is not a function`

#### Expected Behavior
expecting ref methods to work.

#### Steps to Reproduce
1. Nextjs app with `next@12.1.6`, `react@18.1.0` , `react-dom@18.1.0` and `react-player@2.10.0` . I've already tested with `react-player@2.10.1`. Not working in that version as well.

#### Environment
- Browser:  Chrome

**Comment by LuLue7775** [comment]
Same issue here. I'm using useRef to access ReactPlayer, and somehow it's returing retry() instead of any other instance methods.

**Comment by b4s36t4** [comment]
Can anybody share a codesandbox Or stackblitz link would be helpful to work ok this issue.

**Comment by minhtc** [comment]
This issue is related to dynamic import behaviour instead of react-player package.
You can simply wrap the ReactPlayer in a custom component then use a custom props to pass the player ref to parent.

**Comment by inderrr** [comment]
> Same issue here. I'm using useRef to access ReactPlayer, and somehow it's returing retry() instead of any other instance methods.

I've added 2 workarounds for this problem above. You can use them for now.

**Comment by davidkhierl** [comment]
> 

why not use forwardRef here?

**Comment by Multiply** [comment]
We're having the same issue at our end as well.

Opting out of lazy loading is not an option due to the size of the library, and the solutions above doesn't seem to address it correctly.

I'll be happy to test any other proposals, if there are any.

**Comment by inderrr** [comment]
The only solution so far is to wrap the player in another component and import that component. Then we can use dynamic imports and the ref methods work as expected.

```javascript
// components/VideoPlayer.js
import ReactPlayer from "react-player/lazy";

function VideoPlayer({ playerRef }) {
  return (
    <ReactPlayer
        ref={playerRef}
        muted
        playing
        controls        
      />
  );
}

// pages/index.js
import dynamic from "next/dynamic";
const VideoPlayer = dynamic(() => import("../components/VideoPlayer"), {ssr: false});

function Home(){
 const playerRef=useRef();
 
 return <VideoPlayer playerRef={playerRef} />

}
```

**Comment by vincentwinkel** [comment]
With your method @inderrr , `playerRef.currrent` is always undefined.

**Comment by geminiyellow** [comment]
> The only solution so far is to wrap the player in another component and import that component. 

one years later, some plant to fix it?

**Comment by vasabigreencolor** [comment]
this is due to the fact that the word ref is reserved by the react itself and apparently the developers didn’t think about this moment, so with a dynamic improte for the ref you need to create a wrapper with the forwardedRef prop and in turn pass it as a normal prop


```
import React, { RefObject } from 'react'
import AppModal, { IAppModalProps, IAppModalRef } from '.'

export interface IDynamicAppModalProps extends IAppModalProps {
  forwardedRef?: RefObject<IAppModalRef>
}

const DynamicAppModal: React.FC<IDynamicAppModalProps> = (props) => {
  const { forwardedRef, ...args } = props
  return <AppModal ref={forwardedRef} {...args} />
}

export default DynamicAppModal
```

**Comment by rendi12345678** [comment]
> The only solution so far is to wrap the player in another component and import that component. Then we can use dynamic imports and the ref methods work as expected.
> 
> ```js
> // components/VideoPlayer.js
> import ReactPlayer from "react-player/lazy";
> 
> function VideoPlayer({ playerRef }) {
>   return (
>     <ReactPlayer
>         ref={playerRef}
>         muted
>         playing
>         controls        
>       />
>   );
> }
> 
> // pages/index.js
> import dynamic from "next/dynamic";
> const VideoPlayer = dynamic(() => import("../components/VideoPlayer"), {ssr: false});
> 
> function Home(){
>  const playerRef=useRef();
>  
>  return <VideoPlayer playerRef={playerRef} />
> 
> }
> ```

![screenshot-20240828-080842Z-all](https://github.com/user-attachments/assets/7483c804-1fde-4c39-84c8-f0bbe4e4de8e)
it works thanks 
![screenshot-20240828-080835Z-all](https://github.com/user-attachments/assets/2823a4c5-7400-4b48-8dcc-2fdd88f8080b)

**Comment by rendi12345678** [comment]
![screenshot-20240828-080825Z-all](https://github.com/user-attachments/assets/f586de66-9653-4ce2-a387-b7f0d84a9650)
