### ISSUE TITLE
Wistia player infinite loading

### ISSUE THREAD

**Issue by lordlpua** [cookpete/react-player#1456]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior
React player for Wistia - infinite loading in some cases.
<img width="744" alt="Screenshot 2022-05-16 at 16 32 00" src="https://user-images.githubusercontent.com/17593086/168604266-119e6661-0f5c-4463-a8db-910451aaf406.png">
<img width="857" alt="Screenshot 2022-05-16 at 16 32 13" src="https://user-images.githubusercontent.com/17593086/168604286-091fad99-a39c-4029-9187-ef1e6c6cb4b5.png">

#### Expected Behavior

Video play without any loading

#### Steps to Reproduce
1. Can't reproduce it every time, out of 10 attempts it can be reproduced 1 time

#### Environment
- Browser: Chrome 99, 101
- Operating system: Windows 10 Windows 8.1

#### Other Information
For users, it looks like a black screen with infinite round loading. If you will update the web page, it disappears.

From the session record, I see an error in the console

StopGo#synchronize timed out ƒ (r){e.suppressPlay()?r():(e._isPlayPending=!0,e._lastPlayType=void 0,e._lastPlaySource=F(),e._lastPlayIssuedAt=Date.now(),e._lastPlayResolvedAt=null,e._lastPlayRejectedAt=null,e.trigger("playpending"…

Maybe anyone knows something about that. It randomly happens for users. Also, Wistia support knows nothing about it.

**Comment by cookpete** [comment]
Possibly the same issue as https://github.com/cookpete/react-player/issues/1219

**Comment by lordlpua** [comment]
A small update, I found on git the StopGo part, they answered me yesterday - There was recently a fix pushed to the Wistia player that solved a playback stall issue that looked similar console error you posted. It might be worth checking your site again and clearing your local cache just in case.

**Comment by lordlpua** [comment]
The issue was on the Wistia side, they are fixed. Thanks and pls close this issue and #1219
