### ISSUE TITLE
Do not work showPreview

### ISSUE THREAD

**Issue by AnastasiiaBardyuzha** [cookpete/react-player#1458]
Hi! 
`
export const GallerySwiper: FC<GallerySwiperProps> = ({
	initialImg,
	gallery
}) => {
	const playerRef = useRef<ReactPlayer>(null);

	const [swipe, setSwipe] = useState<SwiperCore>();
	const [stepImg, setStepImg] = useState<number>(initialImg ? initialImg + 1 : 1);

	const onBeforeInit = (swipeData: SwiperCore) => {
		setSwipe(swipeData);
	};

	const handledNext = () => {
		swipe?.slideNext();
		swipe && setStepImg(swipe?.realIndex + 1);
	};
	const handledPrev = () => {
		swipe?.slidePrev();
		swipe && setStepImg(swipe?.realIndex + 1);
	};
  
	useEffect(
		() => {
			if (playerRef && playerRef?.current) {
				playerRef.current.showPreview();
			}
		},
		[stepImg]
	);

	return (
    <Box sx={galleryModalStyles.swiperWrapper}>
      <Swiper
        slidesPerView={1}
        spaceBetween={30}
        loop={true}
        onBeforeInit={onBeforeInit}
        initialSlide={initialImg ?? 0}
      >
        {
          gallery.map((
            img, index
          ) => (
            <SwiperSlide key={`${img?.id}_${index}`}>
                <Box
                  sx={galleryModalStyles.mediaSwiperWrapper}
                >
                    <ReactPlayer
                      url={img.url}
                      ref={playerRef}
                      light={img.thumbnailUrl}
                      playing={index === stepImg - 1}
                      controls
                      width="inherit"
                      height="inherit"
                    />
                </Box>
            </SwiperSlide>
          ))
        }
      </Swiper>
      <Box
        sx={galleryModalStyles.paginationWrapper}
      >
        <Button
          variant="default"
          onClick={handledPrev}
          sx={galleryModalStyles.paginationButton}
        >
          <ArrowBackIosNewIcon />
        </Button>
        <Button
          variant="default"
          onClick={handledNext}
          sx={galleryModalStyles.paginationButton}
        >
          <ArrowForwardIosIcon />
        </Button>
      </Box>
    </Box>
	);
};
`

I was expecting that when I switch to another video, showPreview() returns to the preview overlay in the previous video like here https://codesandbox.io/s/react-player-light-mode-jczfx?file=/src/App.js:928-1020 . But it's not. In my case, when I turn back to previous video it keeps playing. Please tell me what am I doing wrong?

I'm using:
"react": "18.0.0",
"react-player": `"^2.10.1"`

**Comment by Barruchou** [comment]
Hello, I have the same problem, did you find a solution?

Thank you
