### ISSUE TITLE
video is not loaded with vite dev when use cdn overrides sdk

### ISSUE THREAD

**Issue by ljwrer** [cookpete/react-player#1459]
I need to use cdn to load hls.js from cdn due to GFW block  
After following <https://github.com/cookpete/react-player#sdk-overrides>  
It's not work with vite dev but works fine with vite build  
I think the main reason is usage of JavaScript modules via script tag

#### Current Behavior
video not loaded

#### Expected Behavior
video should be loaded

#### Steps to Reproduce
see <https://github.com/ljwrer/react-player-cdn-vite-dev-issue>

**Comment by tdammy92** [comment]
@ljwrer where you able to resolve this isse ?
