### ISSUE TITLE
Cannot update controls

### ISSUE THREAD

**Issue by sverhagen** [CookPete/react-player#146]
It is not possible to dynamically update `controls`.

For example in [the demo application](http://cookpete.com/react-player/), add the following to "Custom config": `{"controls": true}` or `{"controls": false}`.

Expected result: toggling of the controls.

Whereas constructs like `{"playing": true}` or `{"playing": false}` have the expected result.

My use case here is that I'd like to show controls while in full-screen, and hide them while in small view (having my video there almost at thumbnail size).

The above observations apply to YouTube.

Thank you.

**Comment by CookPete** [comment]
Hey @sverhagen, unfortunately this would require the YouTube player API to support dynamically changing the controls param after initialising a player, and judging by the lack of response to [this StackOverflow post](http://stackoverflow.com/questions/31583395/hide-youtube-player-controls-dynamically), it seems like this isn't possible.

Weirdly, there is a `setOption` player method, but for some reason only the `captions` option is currently supported.

**Comment by sverhagen** [comment]
Thanks for your answer, it would've been neat, but let's move on and away from this; closing the issue.

**Comment by kresli** [comment]
just an idea here. On controls update get current timestamp and force to reload the url. Soon as url is reloaded, controls works as expected.
