### ISSUE TITLE
Wistia player doesn't play in popover

### ISSUE THREAD

**Issue by rashmin31** [cookpete/react-player#1464]
#### Current Behavior

I have 3 tabs created where on each tab I show some videos based on the tab selected, I want to show them in popover (https://wistia.com/support/developers/popover-customization#popover-true). However, the video plays in the popover for 1st tab only and when switched to another tab the video doesn't play in the popover but plays inline.
I am passing popover as  true in config when using ReactPlayer.

```js
import ReactPlayer from "react-player/wistia";
```
```jsx
         <ReactPlayer
            className="help_center_play"
            url="https://bhanderirashmin31.wistia.com/medias/fnhzrk4ncb"
            width="100%"
            height="100%"
            controls
            config={{
              options: {
                fullscreenOnRotateToLandscape: false,
                popover: true
              }
            }}
          />
```

#### Expected Behavior
The videos should be played in the popover and not inline.

#### Steps to Reproduce

Please have a look at the video attached to reproduce the issue: https://drive.google.com/file/d/1P2Xt7B_xJSeWT2YiUHy74sFUPo1zKi_1/view?usp=sharing

#### Environment
- URL attempting to play: 
- Browser: Chrome
- Operating system: Linux
- codesandbox example:  https://codesandbox.io/s/unruffled-breeze-xsspy4?file=/src/App.js

**Comment by luwes** [comment]
this seems to be resolved
