### ISSUE TITLE
Problem launching the second video on an MP4 format

### ISSUE THREAD

**Issue by thomaslasky** [cookpete/react-player#1466]
#### Current Behavior
When i send an array of URL with MP4 path the player read the first MP4 path, but at the end it don't switch to the second URL.
It work with Youtube URL, but not with MP4 url.

#### Expected Behavior
After read the first MP4 URL Video, it switch to the second one auto

#### Steps to Reproduce
1. Create the player with an array of 2 URL with MP4 files

#### Environment
- URL attempting to play: url={["http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4", "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4"]} it just sample url just for test my app
- Browser: Firefox 102.0b6
- Operating system: Windows 11 (last version)
- jsFiddle example: https://jsfiddle.net/0wz8nred/4/

#### Other Information
It work perfectly with youtube URL

**Comment by hernandiazz9** [comment]
Hi there, I'm working on this issue, and I find one way to do it. 
I will do a Pull Request and hopefully will be fixed soon. 

Cheers

**Comment by RobertoLlopis** [comment]
PR Code: #1518
