### ISSUE TITLE
onEnded reset back to Poster Image

### ISSUE THREAD

**Issue by ChazUK** [cookpete/react-player#1468]
Hi,

I've been trying to reset the player back to the poster image once the video ended. I have tried the following code because I can't see any other method that would offer this functionality.

```javascript
  const handledOnEnded = useCallback(() => {
    playerRef.current.showPreview();
  }, []);
```

**Comment by JeanPSF** [comment]
I am experiencing something alike,  where on the end of the video, the youtube player stops 1  seconds before the video actually end, which causes the onEnded callback to not be called.

**Comment by MdMahfuzRana** [comment]
[ChazUK](https://github.com/ChazUK) hallow it is a feature that while video ended it will show you some suggestion.
so you want it to not to suggest right?

**Comment by MdMahfuzRana** [comment]
so you should use this 


`  const playerRef = useRef(null);

  const handleEnded = (e) => {
    playerRef?.current?.showPreview();
  };`

**Comment by RobertoLlopis** [comment]
Hello! We have one proposal to include the requested feature under name endWithPreview prop

**Comment by RobertoLlopis** [comment]
PR Code: #1517

**Comment by luwes** [comment]
thanks for the feedback but this feature will not be supported by default.

it's possible to accomplish this by using the event callbacks and overlaying the player with a poster image or resetting the video to it's initial state...
