### ISSUE TITLE
Unable to play a video fetched from strapi.js localhost

### ISSUE THREAD

**Issue by muben88** [cookpete/react-player#1472]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior

I couldn't get the video to play in my localhost environment but it is working perfectly on jsfiddle. The video url is fetched from strapi as a backend on my local machine.
#### Expected Behavior

I would like to play a file fetched from strapi.js.

#### Environment
- URL attempting to play:  http://localhost:1337/uploads/video_url.mp4
- Browser: Chrome
- Operating system: windows / react

#### Other Information

When I run it in my localhost on chrome, I get a blank screen, but when I run the same code on jsfiddle on the same browser it works.

**Comment by luwes** [comment]
this is pretty hard to debug. do you see any errors?
