### ISSUE TITLE
Events don't seem to fire when playing a `Kaltura` video in an iOS WebView

### ISSUE THREAD

**Issue by bkwhite** [cookpete/react-player#1473]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior
The video embeds and plays correctly.  It uses the native iOS video player.  The callback provided to `onReady` seems to fire just fine; however, `onPlay`, `onPause`, etc do not get called.

#### Expected Behavior
The video event callbacks get called properly. 

#### Steps to Reproduce
1. Add a `<ReactPlayer>` using a Kaltura video to a page
2. Open the page in an iOS WebView
3. Wire up the `on` callbacks with debug statements
4. Inspect the console using Safari and notice how no events seem to be getting fired

#### Environment
- URL attempting to play: https://cdnapisec.kaltura.com/p/2507381/sp/250738100/embedIframeJs/uiconf_id/44372392/partner_id/2507381?iframeembed=true&playerId=kaltura_player_1605622074&entry_id=1_jz404fbl'
- Browser: iOS WebView (Safari)
- Operating system: iOS 14

**Comment by bkwhite** [comment]
My solution to this issue ended up being returning back to our custom Kaltura player.  This version uses Kaltura's `kWidget` API.

Kaltura Player: https://gist.github.com/bkwhite/90a18f8269c94f0d27d7b9dc12db4f6a
Types: https://gist.github.com/bkwhite/1364b370bc220c5e66b2efd01d777712

**Comment by bkwhite** [comment]
After a deepish-dive into this issue, it seems like `embed.ly` itself has a problem getting the events to propagate while inside of the `WebView`. Not really sure what this problem is exactly.

**Comment by cookpete** [comment]
I’ll close this as it seems to be an issue specifically with `embed.ly` and nothing we can really do. I’m happy to review a PR that updates this library to use the `kWidget` API if that works.
