### ISSUE TITLE
How do I change auto-assiged class vp-center to vp-top? 

### ISSUE THREAD

**Issue by amunrarara** [cookpete/react-player#1479]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior

As I scale down my browser's screen size, a huge amount of padding is added to the top of the video player area. Upon inspection, this can be resolved favorably-enough by changing the <body class="vp-center"> to <body class="vp-top">. If that padding can be reduced, that would be more ideal, otherwise I simply want to set that class!

#### Expected Behavior
I don't want so much vertical on smaller screens.

#### Steps to Reproduce
This is a NextJS project.
1. npm install react-player
2. import ReactPlayer from 'react-player';
3. Within a React Functional Component, return( whatYouSeeInTheJSfiddle )

#### Environment
- URL attempting to play: https://ecosystem-omega.vercel.app
- Browser: Chrome
- Operating system: MacOS Big Sur 11.6.4
- jsFiddle example: https://jsfiddle.net/5xgvz2Lc/

#### Other Information

<img width="922" alt="Screen Shot 2022-07-18 at 3 19 45 PM" src="https://user-images.githubusercontent.com/21048358/179627876-1c056646-67a5-4744-9ea9-3ebf36282213.png">
<img width="915" alt="Screen Shot 2022-07-18 at 3 20 02 PM" src="https://user-images.githubusercontent.com/21048358/179627880-ec6a5b7a-5790-489b-af0e-16060204a425.png">

**Comment by vtrikoupis** [comment]
Going through the same issue, really need to assign vp-top. Any way we can attach css through ReactPlayer

**Comment by luwes** [comment]
sorry this is out of the hands of ReactPlayer because vp-center is a part of the Vimeo player embed and it's in an iframe which can't be manipulated by outside scripts.
