### ISSUE TITLE
MP4 Video pauses when tab is out of focus

### ISSUE THREAD

**Issue by tusharsamyama** [cookpete/react-player#1481]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior
We are showing MP4 video in react-player. When we focus out of the tab by clicking different tab in browser it pauses the video in previous tab.

#### Expected Behavior
Video should not pause when we focus out of the tab

#### Steps to Reproduce

1. Play MP4 video in one tab
1. Click on the different tab in the same brower
1. Check video is paused

#### Environment
Chrome: Version 103.0.5060.114 (Official Build) (x86_64)
OS: MAC OS Monetary, 12.4
- jsFiddle example: https://jsfiddle.net/ornagqwp/

**Comment by arrmani88** [comment]
same problem when playing a youtube embed video, when switching to another Desktop (on MacOs Mojave) the video pauses
