### ISSUE TITLE
Can't play base64 audio

### ISSUE THREAD

**Issue by geniux-dev** [cookpete/react-player#1482]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Steps to Reproduce

1.
1.
1.

#### Environment
- URL attempting to play: 
- Browser: 
- Operating system: 
- jsFiddle example: https://jsfiddle.net/sv5x3ug1

**Comment by Taar** [comment]
Would it be possible to provide an example? I've haven't heard of base64 audio before, can you provide some documentation or a specification? When it comes to audio, react-player uses the `audio` element so if base64 audio isn't supported by the element then there is nothing react-player can do to support the format/codec. [Here is the list](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Audio_codecs#codec_details) of supported codecs.
