### ISSUE TITLE
Is it possible to open h265 file?

### ISSUE THREAD

**Issue by danskonieczny** [cookpete/react-player#1483]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior
Application is not opening h265 file

#### Expected Behavior
Application opening h265 file

#### Steps to Reproduce

1. Change url to h265 file (local or external) and doesn't work

#### Environment
- URL attempting to play: 
- Browser: 
- Operating system: 
- jsFiddle example: https://jsfiddle.net/sv5x3ug1

**Comment by cookpete** [comment]
ReactPlayer is just a proxy for `<video>` when playing file URLs. Support for H265 will be based on [whether the browser supports it](https://caniuse.com/hevc), many of which don’t.
