### ISSUE TITLE
Hi Pete. How to write syntax for triggering onPlay props inside onReady props in react player

### ISSUE THREAD

**Issue by rmanikam** [cookpete/react-player#1484]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Steps to Reproduce

1.
1.
1.

#### Environment
- URL attempting to play: 
- Browser: 
- Operating system: 
- jsFiddle example: https://jsfiddle.net/sv5x3ug1

**Comment by cookpete** [comment]
Sorry, I don’t understand the question. Can you be more specific or give code examples?
