### ISSUE TITLE
Failed to load Facebook SDK

### ISSUE THREAD

**Issue by BuddyLim** [cookpete/react-player#1486]
#### Current Behavior
Hello, currently facebook videos aren't being loaded properly which throws a "Failed to load [https://connect.facebook.net/en_US/sdk.js](https://connect.facebook.net/en_US/sdk.js) error" . In this https://developers.facebook.com/docs/plugins/embedded-video-player/#2--load-javascript-sdk, videos are loaded just fine but in the demo site, https://cookpete.com/react-player/, facebook videos aren't loaded properly

#### Expected Behavior
Facebook videos are loaded properly

#### Steps to Reproduce

1. Insert facebook video urls into the src

#### Environment
- URL attempting to play:  https://www.facebook.com/FacebookDevelopers/videos/10152454700553553/
- Browser:  Chrome 103.0.5060.134 (Official Build) (64-bit)
- Operating system:  Windows 10

**Comment by cookpete** [comment]
Looks like this was a temporary issue or a specific problem with your browser.

**Comment by JefinDX** [comment]
Tracking Prevention blocked a Script resource from loading https://connect.facebook.net/en_US/sdk.js

![image](https://github.com/cookpete/react-player/assets/56828393/d0ddbe57-9c46-47d5-aa4f-37409d01558e)
