### ISSUE TITLE
React Player rendering empty div

### ISSUE THREAD

**Issue by lumenwrites** [cookpete/react-player#1487]
#### Current Behavior
My video component looks like this:

```javascript
// https://github.com/cookpete/react-player/issues/1428
import dynamic from 'next/dynamic'
const ReactPlayer = dynamic(() => import('react-player/lazy'), { ssr: false })

export default function Video({src}) {
  return <ReactPlayer src={src} />
}
```

I use it like this:
```javascript
<Video src="https://www.youtube.com/watch?v=grHP-de1p-U" />
```

Instead of seeing the video rendered on my page, I'm getting a blank div, in my dev tools I see:

```html
<div src="https://www.youtube.com/watch?v=grHP-de1p-U" style="width: 640px; height: 360px;"></div>
```

#### Expected Behavior
See the video rendered on my page.

#### Environment
- URL attempting to play: https://www.youtube.com/watch?v=grHP-de1p-U
- Browser: Any.
- Operating system: OSX

**Comment by cookpete** [comment]
Can anyone provide an example repo? This behaviour implies a problem with the URL matching logic, but I can load https://www.youtube.com/watch?v=grHP-de1p-U in the [demo page](https://cookpete.com/react-player) without a problem.

**Comment by TotalLag** [comment]
I am trying to use this with Remix.run and running into the same issue. I have a barebones repro here: https://github.com/TotalLag/reactplayer-remix-repro

if you run `pnpm dev` or `yarn dev` that should get things running.

**Comment by Seanom** [comment]
I could be wrong but the supplied example uses `src`, not `url` when defined in React Player

Does the following work?
```
// https://github.com/cookpete/react-player/issues/1428
import dynamic from 'next/dynamic'
const ReactPlayer = dynamic(() => import('react-player/lazy'), { ssr: false })

export default function Video({src}) {
  return <ReactPlayer url={src} />
}
```

I am experiencing an empty src in my video tag similar to @daniele-sarnari-blinkoo when trying to use a local file but all remote URLs appear to be working correctly (I'm using 2.11.0)

**Comment by daniele-sarnari-blinkoo** [comment]
> I could be wrong but the supplied example uses `src`, not `url` when defined in React Player
> 
> Does the following work?
> 
> ```
> // https://github.com/cookpete/react-player/issues/1428
> import dynamic from 'next/dynamic'
> const ReactPlayer = dynamic(() => import('react-player/lazy'), { ssr: false })
> 
> export default function Video({src}) {
>   return <ReactPlayer url={src} />
> }
> ```
> 
> I am experiencing an empty src in my video tag similar to @daniele-sarnari-blinkoo when trying to use a local file but all remote URLs appear to be working correctly (I'm using 2.11.0)

I always used `url` property.
In my case the problem was React Strict Mode https://reactjs.org/docs/strict-mode.html.

**Comment by PandukaNandara** [comment]
This package is a trash if you are using this with NextJS. not working at all. 
![image](https://github.com/cookpete/react-player/assets/37260467/da2028cd-c896-4e6b-af98-e466c0b43053)

This is what renders in the page.

**Comment by benomatis** [comment]
I had a similar issue in 2.13.0, I was using it with a file and the `lazy` option, when I clicked the play button the window simply vanished, it showed 0 for height in dev tools.

I resolved it by simply removing `height` form the `ReactPlayer` options, I originally had it set to `100%` to make it responsive, but apparently having only `width` at `100%` makes it responsive without a problem.

```js
<ReactPlayer
    // ...
    light={image}
    width='100%'
    // height='100%' <-- removed this line
    // ...
  />
```
