### ISSUE TITLE
Safari autoplay with "light" prop enabled

### ISSUE THREAD

**Issue by mokontainer** [cookpete/react-player#1488]
#### Current Behavior
Currently in Safari videos will not start autoplaying with the `playing` prop set to `true` when the `light` prop is `true`
It might be related to https://webkit.org/blog/6784/new-video-policies-for-ios/

The reason this happens might happen here
https://github.com/cookpete/react-player/blob/d86f0e09ad19416d561a6c1c1702f97f91c450d6/src/ReactPlayer.js#L176
so since the video is not rendered, the user event is never accepted in safari, which makes you need to click again before being able to start your video(s) - this only happens the first time you want to play your video

#### Expected Behavior
Video should start playing when you press your play button

#### Steps to Reproduce

1. Set light to true and have your poster on the video
2. Press play button
3. Video will pause itself after load

#### Environment
- URL attempting to play: 
- Browser: Safari
- Operating system: MAC v12.2.1

**Comment by cookpete** [comment]
There’s not much we can do about this. If browsers require a user interaction to play a video, that video needs to be rendered for the user to interact with it. The whole point of `light` is to _not_ render the video (and not load third party scripts) until the user clicks or taps.

The answer I guess is to not use the `light` prop and experiment with adding some overlay elements that set `playing` to `true` on click (which should work as the video will be rendered at the point of user interaction)
