### ISSUE TITLE
Inaccurate duration and, therefore, inaccurate progress 

### ISSUE THREAD

**Issue by AlexisN94** [cookpete/react-player#1489]
#### Current behaviour

The duration is inaccurate.

#### Steps to reproduce
1. Open the [fiddle](https://jsfiddle.net/7q14u83n/3/) and check the duration. Everything seems right: the value from `onDuration` matches the duration displayed in the video controls. 
2. Open the same [video on Youtube](https://m.youtube.com/watch?v=2JrkxfDNabk) and compare. It's off by 1 second.

#### Implications

`progress` never reaches 1. It gets stuck at 0,9974958217.

#### Environment
- URL attempting to play: https://m.youtube.com/watch?v=2JrkxfDNabk
- Browser: Chrome
- Operating system: macOS
- jsFiddle example: https://jsfiddle.net/7q14u83n/3/

#### Additional comments
It would be great if we could get the duration in milliseconds, for higher precision.

**Comment by kaylendog** [comment]
After doing some digging, I found the [Youtube IFrame API](https://developers.google.com/youtube/iframe_api_reference#Retrieving_video_information). Reading the description for `player.getDuration()`:

> Returns the duration in seconds of the currently playing video. Note that getDuration() will return 0 until the video's metadata is loaded, which normally happens just after the video starts playing.

So this is the fault of the Youtube IFrame API. It seems possible to read off the duration of the video from the `<video>` component itself, and can probably be PR'd.

**Comment by kaylendog** [comment]
On further digging, that would require modification of the YT embed script, or asking YouTube to add `Access-Control-Allow-Origin *` which obviously isn't something anyone should do. I suspect it is impossible to access a more accurate duration, unless YouTube modifies their API to expose a higher accuracy value.

**Comment by AlexisN94** [comment]
@kaylendog You're right, this is actually a problem with the Youtube IFrame API and unrelated to react-player. My bad. I'm closing the issue here.

**Comment by heyfixit** [comment]
> 

I've noticed that after playing a YouTube clip, calling `getDuration` will give you an accurate duration. If you seek however, then the inaccurate duration comes back and sticks.

Although this is a bit convoluted, you could have a bit of a warm-up sequence before displaying the video where you'd mute, play, and grab an accurate duration in an `onPlay` callback. Then seek back to start and display the video as normal.
