### ISSUE TITLE
Cannot enable PIP with custom controls

### ISSUE THREAD

**Issue by ImaginaSergio** [cookpete/react-player#1492]
#### Current Behavior
I'm working with vimeo videos and a custom control bar that I've made, so my props at <ReactPlayer /> are:

` <ReactPlayer ref={player} pip={true} controls={false} config={{ vimeo: { playerOptions: { quality, responsive: true, pip: true } } }} ...rest of props /> `

If I change de controls prop to `controls={true}` and do not render my custom props, the PIP icon appears and it works well:

![Captura de pantalla 2022-08-17 103707](https://user-images.githubusercontent.com/32952029/185074242-e03632ca-64c4-44f8-affd-a3da033715ca.png)

But If I use my custom controls and disable the vimeo ones, when I press the PIP button it gives me this error on console:

![image](https://user-images.githubusercontent.com/32952029/185074504-4078fc28-cc83-4168-9437-50c8c20461d2.png)

My onClick code is:
```
const handleOnEnterPIP = async () => {
    // Player is set at <ReactPlayer ref={player} ... />
    let video = player.current.getInternalPlayer();

    if (document.pictureInPictureEnabled) {
      try {
        video.requestPictureInPicture();
      } catch (error) {
        console.log('❌ Error', { error });
      }
    } else {
      console.log('Your browser cannot use picture-in-picture right now');
    }
};
```

#### Expected Behavior
I want to now how to avoid this exception when I press my custom PIP control.

**Comment by sergio-ob** [comment]
Any update on this? 😕
