### ISSUE TITLE
Stop react-player to load HLS video on onPause()

### ISSUE THREAD

**Issue by DarpanVats007** [cookpete/react-player#1494]
#### Current Behavior
HLS video stream keeps loading the media in the network tab of DevTools. Current format is .m3u8 and I am using BrowserStack to test on Android and iOS.

#### Expected Behavior
Stop the media loading on onPause() props

#### Environment
- URL attempting to play: 
- Device: iPhone 12-13 and Samsung Galaxy S22 (BrowserStack)
- Operating system: iOS (15, 15.4, 15.5, 15.6, 16(beta)) and Android (10, 11, 12)
- CodePen example: https://codesandbox.io/s/frosty-varahamihira-m2ihmk?file=/src/App.js

**Comment by cookpete** [comment]
Related issue here: https://github.com/video-dev/hls.js/issues/542

There might be a `hls.js` setting for this. Maybe try `maxBufferSize`?
