### ISSUE TITLE
How can i have only one instance of <ReactPlayer />

### ISSUE THREAD

**Issue by w1redl4in** [cookpete/react-player#1499]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

Most likely more a doubt than a issue itself

#### Current Behavior
When frontend changes route creates a new instance of `<ReactPlayer />` and it starts to stack instances playing multiple sounds

#### Expected Behavior
I would like to have a single instance of `<ReactPlayer />` along all frontend routes and when the route changes, use the same instance instead of recreating a new ones

#### Environment
- URL attempting to play: `/`, `/projects`, `/articles`
- Browser: Chrome
- Operating system: Mac OS

#### Other Information
- Project: using Nextjs

**Comment by cookpete** [comment]
Sounds like something weird is going on with your implementation if videos continue playing after the route is unmounted.

If you still wanted one instance you would have to render `<ReactPlayer />` outside of your route system somehow, and update the props when the route changes. How this works exactly will depend on your implementation and routing library used.
