### ISSUE TITLE
Vimeo bug, playing: true prop does not trigger video to play inside iframe

### ISSUE THREAD

**Issue by jmancherje** [CookPete/react-player#150]
I am working on an app with ReactPlayer rendering inside of an iFrame. All video sources work as expected except for Vimeo. Passing `playing: true` to the video player does not start the video player. I forked the repo and modified the demo to illustrate the issue using two video players.

https://github.com/jmancherje/react-player/tree/iframe-bug

Steps to reproduce:
- clone this fork
- `npm i` to get react-frame-component
- Select a Vimeo video
- click the `Play` button to send the prop to both video players
- only the second video player (non-iFrame) will play correctly
- (try with any other video source and it will work as expected for both video players)

Does anyone have any insight as to what is causing this discrepancy with Vimeo vs the other video sources? I'm happy to submit a PR once the issue is isolated.

**Comment by CookPete** [comment]
Hey @jmancherje, have you tested your app using the `vimeo` branch of `react-player`? It's a branch I have been intending to merge soon that uses the newer Vimeo API, which hopefully solves the majority of existing problems with Vimeo videos.

**Comment by jmancherje** [comment]
@CookPete Thanks for pointing me to your Vimeo branch. Unfortunately the Vimeo player still does not work inside of an iFrame. I get the following error from this call on line 62 of Vimeo.js
`this.player = new Vimeo.Player(this.playerId, {...DEFAULT_OPTIONS,      ...this.props.vimeoConfig.playerOptions, id, loop: this.props.loop})`

![image](https://cloud.githubusercontent.com/assets/13545128/22807096/2cffc8a4-eeda-11e6-9764-7ee42255d7fb.png)

**Comment by CookPete** [comment]
The `vimeo` branch has now been merged and published. @jmancherje feel free to reopen this if the problem still occurs.

**Comment by jmancherje** [comment]
@CookPete Thanks for the update. I just updated the example using react-player 0.16.0 and it seems like vimeo videos are still not rendering correctly within an iframe. I made a new branch for this demo and updated the link the original issue:
https://github.com/jmancherje/react-player/tree/iframe-bug

Can you please reopen this issue?

**Comment by CookPete** [comment]
Thanks for the updated demo. Looks like this is an issue with the Vimeo API and how it sends, receives and filters messages: https://github.com/vimeo/player.js/issues/16

Based on the discussion there, I'm not sure there is anything that we can do apart from wait for a fix on their end.
