### ISSUE TITLE
How to set the iframe allow='autoplay' attribute?

### ISSUE THREAD

**Issue by steveasmyle** [cookpete/react-player#1503]
#### Current Behavior
I'm using react-player as a Mixcloud player. I'd like to make use of PR 1467 to set the allow='autoplay' attribute on the Mixcloud iframe, but I don't know how to do this. The rendered iframe element in the DOM looks like this:
<iframe src="https://www.mixcloud.com/widget/iframe/?hide_cover=1&amp;feed=/whatever" frameborder="0" style="width: 100%; height: 100%;"></iframe>

#### Expected Behavior
I'd like it to look like this:
<iframe src="https://www.mixcloud.com/widget/iframe/?hide_cover=1&amp;feed=/whatever" frameborder="0" style="width: 100%; height: 100%;" allow="autoplay"></iframe>

Is there an attribute or config object I should pass to the ReactPlayer component?

#### Environment
This is a React/Node/TypeScript ES6 project

**Comment by cookpete** [comment]
I think this is just because I’ve been very neglectful and forgot to release a new version with all the merged changes from the last few months. Apologies. I will publish shortly.

**Comment by cookpete** [comment]
Done! Fixed in `2.11.0`.

**Comment by steveasmyle** [comment]
Thank you! Confirmed that this works for me following the update.
