### ISSUE TITLE
Playback not working after upgrading to 2.11 on nextjs

### ISSUE THREAD

**Issue by helderjbe** [cookpete/react-player#1507]
#### Current Behavior
After upgrading to 2.11, local video and audio files (using URL.createObjectURL) do not work anymore. No output or errors are thrown whatsoever.
I'm using nextjs latest version along with nx monorepo

#### Expected Behavior
Local files should work properly as it did in 2.10.1.

#### Steps to Reproduce
1. Upgrade to 2.11
2. Profit

#### Environment
- URL attempting to play: 
- Browser: Chrome
- Operating system: MacOS Monterey

**Comment by QuentinFontenay** [comment]
I have the same problem on NextJS

**Comment by kevin-guertin** [comment]
I have the same problem in a simple Create React App using local video files.

**Comment by Rashair** [comment]
It does work in the exported mode (as static HTML files)

**Comment by tarikhamilton** [comment]
Same issue. 2.10 works fine.

**Comment by renanblamas** [comment]
Same issue here, just create a new Next JS project and install react-player last version to see it happening.
Just downgraded the version to 2.10 and worked just fine.

**Comment by Rashair** [comment]
I think it's an issue with strict mode again - it works without it

**Comment by cookpete** [comment]
Hopefully fixed by #1538
