### ISSUE TITLE
mp4 webm URL are not loading at all 

### ISSUE THREAD

**Issue by waelbenmustapha** [cookpete/react-player#1509]
#### Current Behavior
when loading an mp4 url in the src nothing appears even in the reactplayer live demo it's not working for me,
but what's weird is that it's working for my friend .

#### Expected Behavior
previously it loaded normally using URL files

is it just me ?

**Comment by dw-herrmann** [comment]
Same for me, but I found out, when I have an empty state as a placeholder and fill it with an url after it completely loaded, for example via input field, which updates the state, it loads instantly

**Comment by blockchain5992** [comment]
But it's not working for me.

**Comment by luwes** [comment]
fixed in ^^
