### ISSUE TITLE
Iphone and android | And progress time and remaining time is not there on the React player

### ISSUE THREAD

**Issue by ghost** [cookpete/react-player#1515]
Iphone and android | And progress time and remaining time is not there on the React player

**Comment by itsaalexk** [comment]
I observed this issue happens when searching youtube videos. If you try with MP4 , that issue disappears and it works fine.

**Comment by itsaalexk** [comment]
Im not sure if its a Youtube thing or something related to the player. The code goes as follows : `
import { h } from 'preact';
import ReactPlayer from 'react-player';
import style from './style.css';

const Home = () => (
	<div class={style.home}>
		<h1>Home</h1>
		<p>This is the Home component.</p>
		<ReactPlayer url="https://www.youtube.com/watch?v=sbykKJWADuA" 
		playing = {true}
		controls = {true}
		/> 
	</div>
);

export default Home;

`

In the url prop just try a video that has a MP4 format and It should work
