### ISSUE TITLE
Is there any way to add a poster for an audio file?

### ISSUE THREAD

**Issue by jordanlambrecht** [cookpete/react-player#1521]
This is kind of boring to look at:
 
<img width="767" alt="Screen Shot 2022-10-13 at 02 06 26" src="https://user-images.githubusercontent.com/54866853/195525866-78ccc5eb-78f6-404e-a24f-a76a3fc556ee.png">

**Comment by mikhailmtion** [comment]
@jordanlambrecht 
Hi! Maybe this will help you.
https://developer.mozilla.org/en-US/docs/Web/API/MediaMetadata/MediaMetadata
