### ISSUE TITLE
Feature Request: Know whether an event was emitted by the user interaction or by ReactPlayer props change

### ISSUE THREAD

**Issue by Abdullah0991** [cookpete/react-player#1528]
#### Current Behavior
ReactPlayer events are fired by both user interaction and `ReactPlayer` properties change.
For example, if the user clicked pause then the `onPause` event is fired, and also the same if I changed the `playing` prop to `false`.

#### Expected Behavior
I want to know if an event like `onPause` for example, is fired by the user (the user clicked on the pause button) or by changing the prop `playing` to `false`.

1. I am expecting a parameter in the event payload to tell me if the event is fired by the user or by code.
2. Or, the `ReactPlayer` ref to have additional methods like `play`, and `pause` which have a parameter to allow me to control whether to fire the corresponding event or not.

#### Other Information
I am working on a 'Watch-Together' like app, so I need to synchronize the player events between the peers and it's hard to do this now because I don't know whether the event is fired by the user interaction or by the code.

**Comment by juniorforlife** [comment]
+1.  I also need this feature
