### ISSUE TITLE
Waveform for audio files

### ISSUE THREAD

**Issue by ktalebian** [CookPete/react-player#153]
Is there a way to show the waveform of audio files? Something like [this](http://justwave.beotiger.com/demo1.php)?

**Comment by CookPete** [comment]
ReactPlayer is merely to make it easy to play files. Generating a waveform for an audio file is a whole other task with it's own problems to solve. You may want to look at:
* https://github.com/bbc/peaks.js
* https://github.com/andrewrk/node-waveform
* https://www.javascripting.com/view/wavesurfer-js

**Comment by oyeanuj** [comment]
@ktalebian Did you end up integrating any waveform library with react-player? or did you arrive on a different solution?

**Comment by CookPete** [comment]
>Did you end up integrating any waveform library with react-player? or did you arrive on a different solution?

No. See my [comment above](https://github.com/CookPete/react-player/issues/153#issuecomment-282240242). ReactPlayer's focus is to play things from various sources, not to dynamically generate waveforms for audio files. I agree that this would be a cool feature, but it is way beyond the scope of what ReactPlayer should provide.

**Comment by oyeanuj** [comment]
@CookPete Oh, I totally understand. Sorry, if it wasn't clear but my comment was aimed at OP @ktalebian wondering what solution he ended up with. I understand this is outside the scope of the library :)

**Comment by ktalebian** [comment]
@oyeanuj I haven't done any further research on this just yet. If I do come up with anything, I will ping you.

**Comment by oyeanuj** [comment]
@ktalebian cool, thank you. 

And I'll add another library to the list to consider incase someone else is looking for this as well - https://github.com/klambycom/react-waveform

**Comment by CookPete** [comment]
>Sorry, if it wasn't clear but my comment was aimed at OP @ktalebian wondering what solution he ended up with.

@oyeanuj Oh yeah! My brain totally skipped over the `@ktalebian`. Sorry about that :)
