### ISSUE TITLE
v2.11.0 not playing MP4 URL files

### ISSUE THREAD

**Issue by jlalmes** [cookpete/react-player#1530]
#### Current Behavior
Does not play `.mp4` links.

#### Expected Behavior
It works

#### Steps to Reproduce
1. Downgrade to `v2.10.1`
2. Confirm it works
3. Upgrade to `v2.11.0`
4. Confirm it does not work

#### Other Information
Bizarrely there are no errors, nor any callbacks to the `onError` function.

**Comment by jlalmes** [comment]
OK found the issue. 

It was introduced here: https://github.com/cookpete/react-player/pull/1360

Seems to break because of React strict mode's double mount. Hence I can fix this by disabling strict mode.

**Comment by frannale** [comment]
Same here, this issue is not replicated in a previous version

**Comment by dohomi** [comment]
I bumped into this in my NextJS application as well. I use strictMode, downgrade to v2.10.1 works fine.

**Comment by karlhorky** [comment]
@cookpete what do you think about this issue? Seems like `react-player@2.11.0` broke video playing... Maybe #1538 could be reviewed / merged? (or an alternative fix instead)

**Comment by fgadau** [comment]
Any updated on this?

**Comment by yingshaoxo** [comment]
Same error confirmed.

___


```typescript
                        <ReactPlayer
                            url="https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/360/Big_Buck_Bunny_360_10s_30MB.mp4"
                            controls={true}
                            width={"100%"}
                            height={"80%"}
                            playing={true}
                            onError={() => {
                                console.log("Something went wroung...")
                            }}
                        />
```

**Comment by Nicopa** [comment]
This fix works: https://github.com/cookpete/react-player/pull/1538/files
