### ISSUE TITLE
How to get the current state on standalone player? - like is playing, is muted, is paused ect

### ISSUE THREAD

**Issue by onigetoc** [cookpete/react-player#1540]
I use this method from @cookpete (and thank you for that) to control my standalone player.  https://github.com/cookpete/react-player/issues/783#issuecomment-576930938

I want to create a skin with controls but i have to know some player states to make a working progress bar, seeking, to seek and showing the current time, the duration ect and show it in the player skin.

For example to get the player state if true or false.
- is playing
- is paused
- is muted
- ect.....

I started the script based on a very basic video player (I need to update this with the React standalone player like getting live current time, getDuration ect)
https://castv.top/scripts/1-MegaPlayer/V4/src/mgplayer.js

Only click on the firsts fiew Demo: link:
MP4 | Spotify | Facebook 1 | Facebook 2 |
(There's a lot of live streaming video and i will hide the time, progress bar and some functions will not trigger and will only show a LIVE text and some controls like play pause);

Just to get a idea here, i know if it's paused and ended with the standalone version?
```
function togglePlay() {
  if (video.paused || video.ended) {  // like here, How can i know if it's paused and ended with the standalone version?
    video.play();
//    myplayer1.playPlayer();
//    myplayer1.internalPlayer.playPlayer()
//    console.log("Play")
  } else {
//     console.log("Pause")
    video.pause();
//    myplayer1.internalPlayer.pausePlayer();
//    myplayer1.pausePlayer();
  }
}
```

Or update this code elapsed time ect.
```
function updateTimeElapsed() {
  const time = formatTime(Math.round(video.currentTime));
// const time = formatTime(Math.round(getCurrentTime()));
  timeElapsed.innerText = `${time.minutes}:${time.seconds}`;
  timeElapsed.setAttribute('datetime', `${time.minutes}m ${time.seconds}s`)
}
```

I hope it's clear ;)

**Comment by luwes** [comment]
this can be accomplished via the callbacks documented here https://github.com/cookpete/react-player#callback-props
hope this helps!
