### ISSUE TITLE
Incompatibilty with NextJS 13.0.2 and React 18.2.0 for .mkv video url

### ISSUE THREAD

**Issue by aspian-io** [cookpete/react-player#1542]
I am currently using react-player with NextJS 13.0.2 and React 18.2.0 development environment. 
Whenever url attribute of the component sets with an address of .mkv file it does not play the file and by opening chrome dev tools and inspecting the video tag you can see src without any url. I've used .mp4 url and YouTube url and it works as expected, the problem only occurs while using a url of .mkv file. Finally, I changed `reactStrictMode` value from true (default) to false in `next.config.js`, and after that video player worked fine with .mkv file. I think this is an incompatibility issue.

**Comment by karlhorky** [comment]
Maybe same issue as this:

- #1530

Apparently may be fixed by https://github.com/cookpete/react-player/pull/1538
