### ISSUE TITLE
YouTube videos not playing when changing playing to True

### ISSUE THREAD

**Issue by UltimoDragao** [cookpete/react-player#1543]
#### Current Behavior
I have an React (17.0) Application which is using react-player (2.10) on some of it's screens to load and play videos. After getting some event triggers, I change playing to true (the screen loads with playing set to false), but the video doesn't play, just blanks into black and stays in place.

#### Expected Behavior
Videos should start playing when parameter playing is set to true;

#### Steps to Reproduce
1. React app receives trigger from api
2. Parameter Playing is changed to true
3. Video doesn't start

#### Environment
- URL attempting to play: Youtube
- Browser: Chromium/Brave (had problems on both)
- Operating system: Ubuntu/Windows (had problems on both)

Thanks in advance!

**Comment by MadsFrost** [comment]
I experience this aswell, I have to toggle isPlaying twice, some useEffect messing up?

**Comment by UltimoDragao** [comment]
> 

Could you please show me how you do it?
Also, I don't think that it's useEffect messing it up. You see, not only the videos will (randomly) play sometimes after being called by the same useEffect, they blank and don't load when they don't play, meaning that the command to play the video happened, but YouTube denied it.

**Comment by MadsFrost** [comment]
@UltimoDragao What is your player setup like? Usually when I get it to play I wait for the callback “onReady” and then setPlaying to true.

**Comment by cookpete** [comment]
This sounds like it’s potentially an issue with browsers preventing autoplay? Because the trigger for playing the video is _not_ a user gesture. Modern browsers are getting clever around preventing autoplaying videos that were not started by the user.

Is it possible to prove this theory by turning off any autoplay settings in Chrome/Brave?
