### ISSUE TITLE
Question: Ref.seekTo is not a function 

### ISSUE THREAD

**Issue by yek99kr** [cookpete/react-player#1548]
I am using react-player with my next.js site and am having trouble using seekTo function. It results in error saying: "playerRef.seekTo is not a function"

I tried "playerRef.current.seekTo(parseFloat(e.target.value))" as well but same error occurs

This was my code:

```
import { useRef } from "react";
 const ReactPlayer = dynamic(() => import("react-player"), { ssr: false });

 const Player = ({url}) => {

 const playerRef = useRef();

 const [player, setPlayer] = useState({
     playing: true,
     muted: true,
     played: 0,
     loaded: 0,
     duration: 0,
     seeking:false
   });

 const handlePlayPause = function () {
 setPlayer({ ...player, playing: !player.playing });
};

const handleMuted = () => {
   setPlayer({ ...player, muted: !player.muted });
};

const handleSeekMouseDown = (e) => {
 setPlayer({ ...player, seeking: true });
};

const handleSeekChange = (e) => {
 setPlayer({ ...player, played: parseFloat(e.target.value) });
};

const handleSeekMouseUp = (e) => {
 setPlayer({ ...player, seeking: false });
 playerRef.seekTo(parseFloat(e.target.value));
};

const handleProgress = (state) => {
 if (!player.seeking) {
   setPlayer(state);
 }
};

return (
 <div
   className={`relative justify-center content-center w-full`}
  
 >
   <ReactPlayer
     ref={playerRef}
     className="absolute rounded"
     width="100%"
     height="100%"
     url={url}
     volume={1}
     playIcon={<></>}
     playing={player.playing}
     loop={true}
     muted={player.muted}
     onProgress={handleProgress}
   ></ReactPlayer>

   <div
     className={"absolute w-full h-full"}
     onClick={handlePlayPause}
   ></div>

   <div>
     <input
       type="range"
       min={0}
       max={0.999999}
       step="any"
       value={player.played}
       onMouseDown={handleSeekMouseDown}
       onChange={handleSeekChange}
       onMouseUp={handleSeekMouseUp}
     />
   </div>
 </div>
);
};
 
export default Player;
```

Even when I copy paste exact code from demo(https://github.com/cookpete/react-player/blob/master/src/demo/App.js), same error shows, I'm not sure why it happens :(

**Comment by GOATS2K** [comment]
I had to specify the type info to get the ref to work properly.

```javascript
const playerRef = React.useRef<ReactPlayer>(null);
```

**Comment by Abdullah0991** [comment]
You need to call it like this: `playerRef.current.seekTo()`.

**Comment by yek99kr** [comment]
> I had to specify the type info to get the ref to work properly.
> 
> ```js
> const playerRef = React.useRef<ReactPlayer>(null);
> ```

I'm not using typescript :(

**Comment by yek99kr** [comment]
> You need to call it like this: `playerRef.current.seekTo()`.

Yes I've tried but same error occurs

**Comment by pszopa-tl** [comment]
Same issue but with `showPreview()` method. The only thing that is under `playerRef.current` is a mysterious function `retry()`.

I'm using `react-player@2.11.0`

**Comment by yanckst** [comment]
> I had to specify the type info to get the ref to work properly.
> 
> ```js
> const playerRef = React.useRef<ReactPlayer>(null);
> ```

I tried, but still have the issue

**Comment by inderrr** [comment]
Try this solution

https://github.com/cookpete/react-player/issues/1455#issuecomment-1207154843

**Comment by yanckst** [comment]
> Try this solution
> 
> [#1455 (comment)](https://github.com/cookpete/react-player/issues/1455#issuecomment-1207154843)

I tried the solution describe in the comment. I needed to adapt the code a bit because I got compilation error using  `typescript@4.7.4` and `next@12.2.5`

Here's the code for anyone interested:

``` typescript
// main file
import dynamic from "next/dynamic";

const ReactPlayerComponent = dynamic<ReactPlayerProps>(
    () => import("./ReactPlayer").then(r => r.ReactPlayerComponent),
    {
        ssr: false
    }
);

// ReactPlayer.tsx
const ReactPlayerComponent: React.FC<ReactPlayerProps> = ({
  playerRef,
}) => {
  return (
    <ReactPlayer
      ref={playerRef}
    />
  );
};
```
