### ISSUE TITLE
onPause is triggered incorrectly (before onReady) when loading a new video from pause state

### ISSUE THREAD

**Issue by juniorforlife** [cookpete/react-player#1549]
#### Current Behavior

I'm building an app with a Youtube player and a playlist. `playing` prop is controlled by state.
When I **pause** the video player and select a different video from the playlist, `playing` will be updated to `true` programmatically so that the new video will be played automatically.
Then these events will be triggered: `onPlay` -> `onPause` -> `onReady`. 
I can somewhat understand why `onPlay` is triggered because `playing` is changed from `false` to `true` but I believe it should be triggered after `onReady`. However, `onPause` trigger doesn't make any sense to me.

#### Expected Behavior

`onReady` -> `onPlay` and no `onPause`

#### Steps to Reproduce

1. pause react-player
2. load a new video (update video id via state) and update `loading` state to `true`
3. the order of callbacks called: onPlay-> onPause -> onReady

#### Environment

"react-player": "^2.11.0"

<img width="572" alt="Screen Shot 2022-11-24 at 23 10 16" src="https://user-images.githubusercontent.com/68360917/203828016-a4eb6251-7868-4456-8359-c2ecc69d7713.png">

**Comment by juniorforlife** [comment]
@cookpete can you help take a look please 🙏

**Comment by cookpete** [comment]
This comes down to the behaviour of the third party library. The Youtube player API is calling `onPlay` from the `playing` change, then `onPause` as part of switching to a new video. I guess it counts "pausing" the currently playing video before switching in the new one. I’m not sure what we can do about this, other than add logic to your app to ignore any `onPause` within a certain ms of a video change.
