### ISSUE TITLE
Fullscreen doesn't work in mobile browser

### ISSUE THREAD

**Issue by iam-peekay** [CookPete/react-player#155]
hi @CookPete - not sure if this is a known issue or something I need to configure. Fullscreen functionality works great on desktop but doesn't seem to work in mobile browsers. I tried Chrome and Safari and neither seem to work. Any chance you know why?

**Comment by nikolas** [comment]
Which mobile browsers and which devices have you tried this on? Fullscreen functionality on mobile OS's is a lot different than on the desktop, so I'm not surprised that there are issues.

**Comment by iam-peekay** [comment]
@nikolas Chrome and Safari. iOS

**Comment by CookPete** [comment]
Fullscreen functionality is a separate beast from the ReactPlayer library. The [demo page](cookpete.com/react-player) uses [screenfull.js](https://github.com/sindresorhus/screenfull.js) as an example of how to use the JS fullscreen API with ReactPlayer (which is [not supported](http://caniuse.com/#feat=fullscreen) by iOS or Android) and the fullscreen buttons inside the player are powered by the various different APIs for each video type, which are out of our control.

Alternatively, this might be solved by just adding the `allowfullscreen` attribute in the right places.

**Comment by iam-peekay** [comment]
@CookPete yep, feel free to close this issue. I learned that iOS Safari does not support the native Fullscreen API http://caniuse.com/#search=fullscreen (which is what screefull.js uses underneath to implement it's API).
