### ISSUE TITLE
How to fetch HTMLVideoElement from react-player

### ISSUE THREAD

**Issue by rohitatcosm** [cookpete/react-player#1555]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior
I want to fetch HTMLVideoElement from react-player instance.. How can i do that ? I have tried below options but not working as expected.

 const play: HTMLVideoElement | undefined = document.getElementsByTagName(
      'video'
    )[0] as HTMLVideoElement;

  const player: HTMLVideoElement | undefined =
      props.reference.current?.getInternalPlayer() as HTMLVideoElement;
[Passed reference of reactplayer as props]

**Comment by swathijayavel31** [comment]
Any update here? I am trying to do the same thing

**Comment by smarsy** [comment]
Is there any answer on this? I'm trying to do the same thing

**Comment by luwes** [comment]
see https://github.com/cookpete/react-player#instance-methods
see the https://github.com/cookpete/react-player/blob/master/examples/react/src/App.js for an example

it should be `yourRef.current?.getInternalPlayer()`
