### ISSUE TITLE
Help: Is it possible to send multiple hls URLs as an array in props?

### ISSUE THREAD

**Issue by harsh-aumhum** [cookpete/react-player#1556]
Help: Is it possible to send multiple hls URLs as an array in props?

**Comment by luwes** [comment]
@harsh-aumhum I believe this isn't possible. see https://github.com/cookpete/react-player/blob/master/src/players/FilePlayer.js#L177

if the goal is creating a playlist to play videos one after the other, you will have to implement that logic yourself out of ReactPlayer and dynamically change the src when switching.

Hope this helps
