### ISSUE TITLE
Dash .mpd files not playing on iOS (Safari or Chrome Mobile Browsers)

### ISSUE THREAD

**Issue by iRSK** [cookpete/react-player#1557]
#### Current Behavior
DASH videos are not playing on iPhone devices in any mobile browser

#### Expected Behavior
HLS videos are playing perfectly fine but DASH videos are not.

#### Steps to Reproduce
1. Directly check on the Demo Page itself. Open https://cookpete.com/react-player/ - on an iPhone device either on Safari or Chrome Mobile Browsers
2. Select "DASH (mpd)" in the Files option. It will automatically load a sample .mpd file
3. The video won't play.

#### Environment
- URL attempting to play:  https://cookpete.com/react-player/
- Browser: Safari on iPhone 12 Pro Max
- Operating system: iOS

#### Other Information
HLS videos are playing fine but not DASH videos - what can be done to resolve this?

**Comment by luwes** [comment]
@iRSK this is expected. playing back DASH videos requires MSE (media source extensions) which is a browser feature that is not supported on iOS. 

mobile Safari (iOS) has native support for HLS (.m3u8) which should be used to play adaptive streams on iPhones.
