### ISSUE TITLE
CORB (Cross-Origin Read Blocking) blocks requests to Loom Video

### ISSUE THREAD

**Issue by rutanshuj** [cookpete/react-player#1559]
#### Current Behavior
Trying to reproduce a Loom URL the player fails and doesn't load the video.

#### Expected Behavior
Be able to reproduce the video.

#### Steps to Reproduce
Have attached the JS Fiddle below

#### Environment
- URL attempting to play: https://www.loom.com/embed/dbe00c413a714839992e7548704fe576 
- Browser: Chrome 
- Operating system: MacOS 
- jsFiddle example: https://jsfiddle.net/rutanshu/476g2p1t/11/

#### Other Information

Check the Chrome Dev console

Chrome

Cross-Origin Read Blocking (CORB) blocked cross-origin response https://www.loom.com/embed/dbe00c413a714839992e7548704fe576 with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.

**Comment by luwes** [comment]
it looks like Loom is not supported, see here https://github.com/cookpete/react-player/tree/master/src/players

also Loom doesn't provide a player API so it's not that useful to implement it in react-player. we wouldn't be able to control play / pause, volume, playback rate etc via the API. it's restricted by the iframe which has to be used to embed the Loom player.

https://dev.loom.com/docs/embed-sdk/api
