### ISSUE TITLE
Failed to execute 'postMessage' on 'DOMWindow': The target origin (https://....) provided does not match the recipient window's origin ('https://...')

### ISSUE THREAD

**Issue by sadashiv-sumasoft** [cookpete/react-player#1573]
React player showing following console error message When We provides `url`  of  youtube videos.

Can you suggest how can i fix this?

![DifferentOriginIssue](https://user-images.githubusercontent.com/89510166/217461740-6425a362-672d-47b1-8dc5-627f3a36cec8.PNG)

**Comment by wadehammes** [comment]
Im also seeing this, I tried to add the `origin` property to the youtube args but it didnt work.

**Comment by cookpete** [comment]
Duplicate of #508

**Comment by paulincai** [comment]
I fixed this by updating my browser Content-Security-Policy. I added  https://www.youtube.com/ to the frame-src
