### ISSUE TITLE
fix: breaking update v2.11.1

### ISSUE THREAD

**Issue by glpecile** [cookpete/react-player#1574]
#### Current Behavior

Project doesn't compile.

#### Expected Behavior

To compile correctly.

#### Steps to Reproduce

1. Compile with version `2.11.1`
2. Boom

#### Other Information

Trace:

```
./node_modules/react-player/es6/ReactPlayer.jsx
--
19:45:31.464 | Module parse failed: Unexpected token (140:8)
19:45:31.464 | You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
19:45:31.464 | \|       const { light, playIcon, previewTabIndex, oEmbedUrl } = this.props
19:45:31.464 | \|       return (
19:45:31.464 | >         <Preview
19:45:31.464 | \|           url={url}
19:45:31.464 | \|           light={light}
19:45:31.464 |  
19:45:31.464 | Import trace for requested module:
19:45:31.464 | ./node_modules/react-player/es6/ReactPlayer.jsx
19:45:31.464 | ./node_modules/react-player/es6/index.js
19:45:31.464 | ./components/chats/FloatingVideoPlayer.tsx
19:45:31.465 | ./components/chats/DisplayFloatingVideoPlayer.tsx
19:45:31.465 |  
19:45:31.465 | ./node_modules/react-player/es6/players/DailyMotion.jsx
19:45:31.465 | Module parse failed: Unexpected token (116:6)
19:45:31.465 | You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
19:45:31.465 | \|     }
19:45:31.465 | \|     return (
19:45:31.465 | >       <div style={style}>
19:45:31.465 | \|         <div ref={this.ref} />
19:45:31.465 | \|       </div>
19:45:31.465 |  
19:45:31.466 | Import trace for requested module:
19:45:31.466 | ./node_modules/react-player/es6/players/DailyMotion.jsx
19:45:31.466 | ./node_modules/react-player/es6/players/index.js
19:45:31.466 | ./node_modules/react-player/es6/index.js
19:45:31.466 | ./components/chats/FloatingVideoPlayer.tsx
19:45:31.466 | ./components/chats/DisplayFloatingVideoPlayer.tsx
19:45:31.466 |  
19:45:31.466 | ./node_modules/react-player/es6/players/Facebook.jsx
19:45:31.466 | Module parse failed: Unexpected token (109:6)
19:45:31.466 | You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
19:45:31.467 | \|     }
19:45:31.467 | \|     return (
19:45:31.467 | >       <div
19:45:31.467 | \|         style={style}
19:45:31.467 | \|         id={this.playerID}
```

**Comment by ralcant** [comment]
Same error here

**Comment by tandrasi** [comment]
same

**Comment by Lornz-** [comment]
Same here

**Comment by jordanhudgens** [comment]
Same for me, the app wouldn't compile, but the error was related to not being able to find a `DailyMotion` dependency

**Comment by minhvuong37** [comment]
same here
you may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
| export default class Kaltura extends Component {
>   static displayName = 'Kaltura'
|   static canPlay = canPlay.kaltura
|   callPlayer = callPlayer

**Comment by ralcant** [comment]
I know this isn't ideal but I just rolled it back in `package.json` from `^2.11.0` to `2.11.0` and it works

**Comment by jordanhudgens** [comment]
@ralcant that's what I did as well to get it working

**Comment by maolaoban** [comment]
same
![image](https://user-images.githubusercontent.com/52857733/217729622-d09f9edb-9a1d-4e4b-bf09-ae6dbd214b05.png)

**Comment by muhammedogz** [comment]
Stream Chat React using this Library, So I can't lower the version.
It seems they are using the latest version.

**Comment by peterpangpeter** [comment]
same here, 
found a workaround using resolutions in yarn.
This may help if some other library of yours is using this library, in other words this is the dependency of a dependency. 
https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/

**Comment by muhammedogz** [comment]
If you have a dependency that relias on this dependency, you can solve this with npm overrides.
https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides

Thanks @peterpangpeter for sharing the yarn solution.

**Comment by manojsingh7** [comment]
same issue, i am facing.

**Comment by ku997** [comment]
same with ^2.10.1. it happens after i up my webpack to 5

**Comment by danblacklist** [comment]
+1, facing the same issue:
```
Failed to compile.

./node_modules/react-player/es6/players/Kaltura.jsx 10:21
Module parse failed: Unexpected token (10:21)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders 
| 
| export default class Kaltura extends Component {
>   static displayName = 'Kaltura'
|   static canPlay = canPlay.kaltura
|   callPlayer = callPlayernpm ERR! code ELIFECYCLE
npm ERR! errno 1`

**Comment by sheikx1221** [comment]
2.11.0 works fine

**Comment by masudhossain** [comment]
Not working for us either. Was thinking it was us...

**Comment by aayushnarang** [comment]
> Not working for us either. Was thinking it was us...

Yes, I understand, I too faced difficulties for over two hours, believing that the error was on our end.

**Comment by Lalit-Joshi** [comment]
> Not working for us either. Was thinking it was us...

Yes, I understand, I too faced difficulties for over two hours, believing that the error was on our end.

**Comment by AkshayKrJha** [comment]
I am also facing this issue with v2.9.0 (few days back, it was fine).
![image](https://user-images.githubusercontent.com/49342317/217915167-f938582a-750b-410a-bbf2-0eeb6e8a2a4d.png)

Replacing ^2.9.0 with 2.9.0 in package.json worked.

**Comment by eatyourgreens** [comment]
Same problem here. The new unbundled JSX distribution breaks our Webpack 5 builds. 
https://github.com/cookpete/react-player/pull/1537

**Comment by xbeakmanx** [comment]
Same problem.

**Comment by JandenMa** [comment]
Same problem here

> +1, facing the same issue:
> 
> ```
> Failed to compile.
> 
> ./node_modules/react-player/es6/players/Kaltura.jsx 10:21
> Module parse failed: Unexpected token (10:21)
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders 
> | 
> | export default class Kaltura extends Component {
> >   static displayName = 'Kaltura'
> |   static canPlay = canPlay.kaltura
> |   callPlayer = callPlayernpm ERR! code ELIFECYCLE
> npm ERR! errno 1`
> ```

**Comment by JandenMa** [comment]
I added a resolution to solve it:
```json
"resolutions": {
    "react-player": "2.11.0"
}
```

**Comment by rushi-nonstopio** [comment]
@cookpete please look into this issue urgently for all of us

**Comment by eatyourgreens** [comment]
If you’re building a NextJS app (we are) you might need to add `react-player` to `transpilePackages` in order to transpile the new JSX distribution to JS. 
https://nextjs.org/blog/next-13-1#built-in-module-transpilation-stable

**Comment by cookpete** [comment]
Looks like I should have tested [this suggestion](https://github.com/cookpete/react-player/pull/1537#issuecomment-1311935448) more thoroughly. Apologies all. I’ll remove `"module": "es6/index.js"` from `package.json` and publish `v2.11.2`. People using `vite` etc can still import from `react-player/es6` for the time being.

@wallw-teal any suggestions?
