### ISSUE TITLE
vid.me url video are not playing

### ISSUE THREAD

**Issue by jasan-s** [CookPete/react-player#158]
i.e: I replaced the TestA video url to https://vid.me/gjMy another vid.me video link and it does not work.
The demo original video urls work just fine. has vid me changed something that broke the component?

streamable links work fine.

**Comment by CookPete** [comment]
Good spot. It's a dodgy regex for the `canPlay` check.

**Comment by CookPete** [comment]
Fixed in `0.14.3`

**Comment by jasan-s** [comment]
Sweet. caseinsensitive check. :)
