### ISSUE TITLE
Offline mode and hls.js

### ISSUE THREAD

**Issue by sharon2469** [cookpete/react-player#1582]
I have an environment that creates a playlist (m3u8), everything works smoothly until the moment I disconnect from the Internet.
My system continues to generate a playlist and I continue to listen to it with the help of the ReactPlayer library, the problem starts with the fact that the library uses hls.js and it tries to take data from: https://cdn.jsdelivr.net/npm/hls.js@1.1.4/dist/ hls.min.js

I did GOOGLE about it and thought that if I download the HLS.JS to my project and load it it will solve the problem, but I can't figure out how I can transfer the HLS.JS I downloaded to the ReactPlayer library.
I checked the API of the library and it mentions hlsOptions but without much explanation as to how I can transfer an instance of the current location of the HLS.JS
(I need my system to work OFFLINE as well !!!(
can someone please suggest how can I solve it?

**Comment by mislavmiocevic** [comment]
@cookpete if we still want to add `hls.js` locally, is this how you would do it?:
``` // _app.tsx in Next.js
import Hls from 'hls.js';

...

if (typeof window !== 'undefined' && !window.Hls) {
   window.Hls = Hls;
}

return (...);
```

I am using Next.js
