### ISSUE TITLE
The standalone version is not working

### ISSUE THREAD

**Issue by orlandovallejos** [cookpete/react-player#1584]
#### Current Behavior
I tried to use the standalone version and I can't make it work, then I looked at the Fiddle example provided in the repository, and it's not working either. [https://jsfiddle.net/krkcvx9s/](https://jsfiddle.net/krkcvx9s/ )

#### Expected Behavior
The example should work

#### Steps to Reproduce
1. Go to the example and just try it

#### Environment
- URL attempting to play: 
- Browser: Chrome
- Operating system: MacOS

And I think the link provided should have the version in the name, otherwise, when it breaks, it breaks everywhere:
https://cdn.jsdelivr.net/gh/CookPete/react-player@master/dist/ReactPlayer.standalone.js

**Comment by melotte25** [comment]
@orlandovallejos - Here's the link to the Fiddle I created for the PR. This should work if you'd like to test the latest code until the next version is released.

`https://transfer.sh/URCfCh/ReactPlayer.standalone.js`
