### ISSUE TITLE
Config not updating when value changes

### ISSUE THREAD

**Issue by leinierperez** [cookpete/react-player#1587]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior
When a value is changed in the config of the player. It doesn't update it.

#### Expected Behavior
If a value is changed in the config of the player, it should reflect that change.

[this](https://github.com/video-dev/hls.js/issues/3822) is what i am trying to achieve

saw some issues ([1](https://github.com/cookpete/react-player/issues/1178), [2](https://github.com/cookpete/react-player/issues/1162)) not sure if there have been updates since then or any more info about this.
```tsx
import ReactPlayer from 'react-player/file';

function App() {
  const [buff, setBuff] = useState(1);

  const updateBuff = () => {
      setBuff(800);
  };

  return (
    <div className="App">
      <ReactPlayer
        url="https://vz-95150ef3-4c1.b-cdn.net/66aeb8f8-788d-4298-90e1-53efeb4ea451/playlist.m3u8"
        controls
        muted
        onPlay={updateBuff}
        config={{
          forceHLS: true,
          hlsOptions: {
            maxMaxBufferLength: buff,
          },
          attributes: {
            preload: 'metadata',
          },
        }}
      />
    </div>
  );
}
```

**Comment by leinierperez** [comment]
Was able to get it working by doing this to change it when i want. Not sure if theres another way i should be doing this or this is fine.
```tsx
const player = playerRef.current.getInternalPlayer('hls');
player.config.maxMaxBufferLength = 30;
```

**Comment by Tpleme** [comment]
I am a bit to late but i faced a similar problem and came out with a hacky solution for changing subtitles dynamically.

First you need to have the ReactPlayer ref, and then create a function that is called by some button you have to change the subtitles.

```
const changeSubtitle = sub => {
	if (videoRef.current) {
		const videoPlayer = videoRef.current.getInternalPlayer();
		const tracks = videoPlayer.textTracks;
		for (let i = 0; i < tracks.length; i++) {
			if (tracks[i].language === sub) {
				tracks[i].mode = "showing";
			} else {
					tracks[i].mode = "disabled";
			}
		}
	}
};
```

This way we can get the tracks and manually show/hide them based on the value recieved by this function
