### ISSUE TITLE
DASH compatibility

### ISSUE THREAD

**Issue by aiko929** [cookpete/react-player#1589]
#### Current Behavior
Is the DASH/mpd file support disabled or broken?
Even in the demo version the DASH example isnt working. I tried multiple browsers but nothing changed. 
Self hosted i cant seem to get a video stream up and running. 

#### Expected Behavior
The video player should provide a video.

#### Steps to Reproduce
1. Look at own demo link. (https://cookpete.com/react-player/)
2. Or try following example:
3. `<ReactPlayer url="https://dash.akamaized.net/envivio/EnvivioDash3/manifest.mpd"
        playing="true" controls="true"/>`

#### Environment
- URL attempting to play: https://dash.akamaized.net/envivio/EnvivioDash3/manifest.mpd
- Browser: Google Chrome
- OS: Ubuntu 22

**Comment by cookpete** [comment]
It looks like https://dash.akamaized.net/envivio/EnvivioDash3/manifest.mpd just isn’t available any more. The files from https://reference.dashif.org/dash.js/nightly/samples/ work so I’ll switch to one of those. Good spot.
