### ISSUE TITLE
Is there a default controls css?(question)

### ISSUE THREAD

**Issue by jasan-s** [CookPete/react-player#159]
I wanted to build a custom play,pause, progressbar/(instagram like circular) and a logo watermark to my videos. Is there any starting css from where i can customize from to add such overlays on hover?

**Comment by CookPete** [comment]
There is no starting CSS for custom controls. There is a [player overlay example jsFiddle](https://jsfiddle.net/kbzzhubs/) and the [demo app controls](https://github.com/CookPete/react-player/blob/master/src/demo/App.js#L122-L160) that should get you started.
