### ISSUE TITLE
Wistia Timed Out and video not loading

### ISSUE THREAD

**Issue by nrochatvc** [cookpete/react-player#1591]
#### Current Behavior
When you enter a Wistia URL with query params like [](https://fast.wistia.net/embed/iframe/8w4r87tvt9?videoFoam=true&wvideo=8w4r87tvt9)

![Screenshot 2023-03-03 at 15 25 09](https://user-images.githubusercontent.com/102604816/222821902-5c3e8c46-4db0-44c8-910b-862a683defb0.png)

The video is not loaded and in the console, you get the error:
`Timed out fetching http://fast.wistia.com/embed/medias/8w4r87tvt9?videoFoam=true&wvideo=8w4r87tvt9.json`

![Screenshot 2023-03-03 at 15 29 03](https://user-images.githubusercontent.com/102604816/222822770-219e59e6-ff9f-4546-a190-35fc72bcfc0e.png)

#### Expected Behavior
The video should load properly after entering the URL with query params. Sometimes users grab the entire URL

#### Steps to Reproduce
1. Go to https://cookpete.com/react-player/
2. Open the browser console
3. Enter the video URL `https://fast.wistia.net/embed/iframe/8w4r87tvt9?videoFoam=true&wvideo=8w4r87tvt9`
4. The Time out error should apear

#### Environment
- URL attempting to play: https://fast.wistia.net/embed/iframe/8w4r87tvt9?videoFoam=true&wvideo=8w4r87tvt9
- Browser: Chrome
- Operating system: Mac

**Comment by Billbastos** [comment]
I am also having this error.
It seems a regex issue.
<img width="617" alt="Screen Shot 2023-03-06 at 11 19 52 AM" src="https://user-images.githubusercontent.com/1039836/223209367-09f4afd8-2b41-4811-855e-722f439b1700.png">
And it is sending the video key as `/medias/8w4r87tvt9` that is being concatenated twice
<img width="666" alt="Screen Shot 2023-03-06 at 11 07 33 AM" src="https://user-images.githubusercontent.com/1039836/223209622-a09d798f-50b7-4a0f-a593-f3fb51d37dd4.png">
It seems a bug happening on this line https://github.com/cookpete/react-player/blob/master/src/patterns.js#L9
