### ISSUE TITLE
Not able to use Audio Player using m3u8 file format.

### ISSUE THREAD

**Issue by ranveersequeira** [cookpete/react-player#1592]
#### Current Behavior
I'm using next12.1 and react18 to play audio which is coming from backend and is in m3u8 (hls) format.

#### Expected Behavior
It should show Audio player on page. But it's showing blank.
Its only rendering <div style="width: 100%; height: 100%;"></div> when I use m3u8 file otherwise its working fine.
` <ReactPlayer
                url={audioSrc}
                // url='https://www.youtube.com/watch?v=ysz5S6PUM-U'
                forceAudio
                forceHLS
                width='100%'
                height='100%'
            />`
            
            
 I have tried this also 
`   <ReactPlayer
                url={audioSrc}
                // url='https://www.youtube.com/watch?v=ysz5S6PUM-U'
                config={{
                    file: {
                        forceAudio: true,
                        forceHLS: true
                    }
                }}
                width='100%'
                height='100%'
            />`
I'm using like this.

#### Environment
- URL attempting to play: https://verito-user-data.s3.ap-south-1.amazonaws.com/6288/79cdb3bc9c4a9e073111b1beba7c4662_af94d79a-03dd-4ecc-bc55-74e027259880.m3u8
- Browser: Edge(latest)
- Operating system: windows 11

**Comment by cookpete** [comment]
You can see a CORS error in the console. You’ll have to update the CORS settings on the s3 bucket.

<img width="1402" alt="image" src="https://user-images.githubusercontent.com/1926029/224048407-30852ff0-693f-4c16-af55-e529facee475.png">

**Comment by ranveersequeira** [comment]
is the syntax for the file config is right?
Thanks for you time.

**Comment by cookpete** [comment]
Your second example is correct, although you can also do:

```jsx
<ReactPlayer
    url={audioSrc}
    config={{
        forceAudio: true,
        forceHLS: true
    }}
    width='100%'
    height='100%'
/>
```

**Comment by ranveersequeira** [comment]
I dont think there is issue with CORS.
Because I have played 
URL - https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8
Mentioned on Official Website on my local using this syntax. 
Its blank in browser although its showing audio element in elements tab.
![image](https://user-images.githubusercontent.com/26397867/224235821-938a89aa-1081-4822-83f2-5c0091113184.png)
