### ISSUE TITLE
onPause event calls when user seeks in an audio player`s timeline

### ISSUE THREAD

**Issue by mavlikwowa** [cookpete/react-player#1595]
I use react-player for plaing of audio files. I should call an event when user clicks the stop control.
However, onPause event calls when user seeks  in an audio player`s timeline.

```
<ReactPlayer
  playing
  onPause={() => console.log('It calls on timeline`s seeking!')}
  width="100%"
  height={42}
  controls
  url={`${process.env.STATIC_SERVER}/${audio}`}
/>
```

#### Environment
- "react-player": "^2.10.1",
- Browser: Chrome
- Operating system: Windows 

My question is:
How can I call this event when user clicks exactly the stop control?

**Comment by cookpete** [comment]
What type of audio file are you playing? I can’t reproduce this in the demo when playing the sample mp3.
