### ISSUE TITLE
Autoplaying on mobile browsers

### ISSUE THREAD

**Issue by jasan-s** [CookPete/react-player#160]
Is it possible to pass the following props: 

> {muted autoplay playsinline}

 to Reactplayer similar to HTML5 player so it does autplay on mobile browsers.

**Comment by jasan-s** [comment]
Or how can add iphone-inline-video lib to React-player

**Comment by DVassilev** [comment]
@CookPete Any feedback on this?

**Comment by CookPete** [comment]
Attributes can be added to the HTML5 players like so:

``` js
<ReactPlayer
  url='file.mp4'
  fileConfig={{ attributes: { controls: true } }}
/>
```

However, beware of [mobile considerations](https://github.com/CookPete/react-player#mobile-considerations) with regards to autoplaying stuff.
