### ISSUE TITLE
HLS (m3u8) not working on iOS devices 

### ISSUE THREAD

**Issue by janrembold** [cookpete/react-player#1600]
#### Current Behavior
Loading the demo page https://cookpete.com/react-player/ and selecting `HLS (m3u8)` doesn't play the video.
- iOS - iPhone 13 Pro: shows at least the first frame as background
- MacOS Chrome - Dev Tools set to iPhone 12: shows error event and no image at all - player is not loaded

#### Expected Behavior
Player initializes and loads HLS video

#### Steps to Reproduce
1. Go to https://cookpete.com/react-player/ (use iOS mobile phone or Dev Tools set to iPhone)
2. Click on `HLS (m3u8)` 
3. Video does not load/start

This seems to only occur on iOS devices. Setting the user agent to e.g. Samsung S20 everything works fine. Might be related to https://github.com/cookpete/react-player/issues/1330 that was never resolved but the error now occurs even on your own demo page @cookpete - maybe this helps to track down this issue. 

![react-player-ios](https://user-images.githubusercontent.com/4015313/226172671-bd5f5522-8cc0-4b81-b080-7324662570da.png)

**Comment by janrembold** [comment]
Small update... it seems that on iPhone it loads and plays the HLS video but only on the second click and only in fullscreen mode. Our integration turned out as a CORS problem and is fixed now. Therefore closing this issue

**Comment by joshephan** [comment]
Is there no other option for iOS playing HLS file? In my case, react-player can't load proper video data from cloudfront and then return nothing.
