### ISSUE TITLE
Disable caching of video files

### ISSUE THREAD

**Issue by halilguler** [cookpete/react-player#1605]
I am using React-Player to play videos in my web application. I am using a CDN to serve the videos, but I have noticed that when I refresh the page, the video is not downloaded again, so the cached video is played, even if it is not the latest version. This causes issues as the video may no longer be representative of the video it is meant to play.

I would like to disable caching of the video files so that they are always downloaded from the server when the page is refreshed. Is there a way to do this in React-Player?

![image](https://user-images.githubusercontent.com/26625428/228661987-72fdf837-9e01-4512-a405-08411a92448c.png)

**Comment by cookpete** [comment]
This isn’t really anything to do with this library. You could just add `?cachebust=[timestamp]` to the video URL?
