### ISSUE TITLE
Google Chrome Device Mode Simulation iOS Device Not Working - onError DOMException: The element has no supported sources.

### ISSUE THREAD

**Issue by akbortoli** [cookpete/react-player#1615]
#### Current Behavior
I am getting a weird behavior when simulating mobile devices in device mode on Chrome (Version 112.0.5615.49).

#### Expected Behavior
For Audio/Video to play normally as it would when not in device mode.

#### Steps to Reproduce
1. Go to https://cookpete.com/react-player/ on Google Chrome
2. Open the developer tools
4. Click on device mode
5. Select an apple device from the emulated device list e.g: iPhone 12 Pro
6. Add the following URL to the Custom URL input field: https://stream.mux.com/uNbxnGLKJ00yfbijDO8COxTOyVKT01xpxW.m3u8
7. Click load, video/audio won't play. An error will be thrown with Event object
8. Click pause/play gives you the following error message: onError DOMException: The element has no supported sources.

#### Environment
- URL attempting to play:  https://stream.mux.com/uNbxnGLKJ00yfbijDO8COxTOyVKT01xpxW.m3u8
- Browser: Google Chrome (Version 112.0.5615.49)
- Operating system:  MacOS
- jsFiddle example: N/A

#### Other Information

**Enable device mode**
<img width="1502" alt="enable-device-mode" src="https://user-images.githubusercontent.com/642163/232736237-a8218a11-dcd5-4d00-9acf-0a052e574f3a.png">

**When not in device mode**
<img width="1508" alt="Screen Shot 2023-04-18 at 7 40 04 pm" src="https://user-images.githubusercontent.com/642163/232737770-008391bc-b74d-4767-9f0a-e7febe3e21f9.png">

**Device mode enabled**
<img width="1512" alt="Screen Shot 2023-04-18 at 7 39 18 pm" src="https://user-images.githubusercontent.com/642163/232737838-fe3ab673-5836-444f-8e86-cd357a7e9606.png">

**Safari**
<img width="1624" alt="Screen Shot 2023-04-18 at 7 36 44 pm" src="https://user-images.githubusercontent.com/642163/232736752-b0d3d784-7c39-4cb4-8326-e9798b491ef7.png">

**Safari iOS - iPhone 14**
![IMG_0034](https://user-images.githubusercontent.com/642163/232738526-7eb0be8d-08a6-4091-a612-300df9cf5aa7.PNG)

**Comment by jurahalas** [comment]
any updates for this ?
