### ISSUE TITLE
Title: HLS source not working on iPhone, including demo page

### ISSUE THREAD

**Issue by seveun** [cookpete/react-player#1619]
Current Behavior
React Player does not seem to work with HLS sources on iPhone devices, even on the demo page: https://cookpete.com/react-player/

Expected Behavior
React Player should be able to play HLS sources on iPhone devices without issues.

Steps to Reproduce
Visit https://cookpete.com/react-player/ on an iPhone
Attempt to play an HLS source
Observe that the player fails to load the HLS source
Environment
URL attempting to play: Any HLS source on https://cookpete.com/react-player/
Browser: Safari (latest version)
Operating system: iOS (latest version)
Other Information
This issue seems to be specific to iPhone devices, as the HLS sources play without issues on other devices and platforms.

**Comment by joshephan** [comment]
Still no answer?? same problem..
