### ISSUE TITLE
'Video unavailable' when trying to load certain youtube videos 

### ISSUE THREAD

**Issue by james-gulland** [cookpete/react-player#1621]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior
Once deployed to heroku, I try and load a youtube video using react-player but it comes back with 'video unavailable - watch on youtube'.  On localhost it worked fine.

![image](https://user-images.githubusercontent.com/119734574/234647261-7e63cc71-52d5-4ece-b9dd-c24da63e165c.png)

It works OK for some videos, i.e. https://www.youtube.com/watch?v=15Nqbic6HZs&t=1176s&ab_channel=AlfaMist
But for most videos, I get the aforementioned error.  i.e. https://www.youtube.com/watch?v=Beld090NIoo&t=376s&ab_channel=MyAnalogJournal 

Is this something related to copyright for embedded videos?

#### Expected Behavior
It should load all videos without issue.

#### Steps to Reproduce

1. Try and load a video that does not work, i.e. https://www.youtube.com/watch?v=Beld090NIoo&t=376s&ab_channel=MyAnalogJournal - it comes back with 'video unavailable - watch on youtube'
2. Try and load a video that does work, i.e. https://www.youtube.com/watch?v=15Nqbic6HZs&t=1176s&ab_channel=AlfaMist - it works fine and no error message.

#### Environment
- URL attempting to play: 
- An example of a youtube video that does load: https://www.youtube.com/watch?v=15Nqbic6HZs&t=1176s&ab_channel=AlfaMist
An example of a youtube video that doesnt load: https://www.youtube.com/watch?v=Beld090NIoo&t=376s&ab_channel=MyAnalogJournal
- Browser: Chrome latest
- Operating system: Mac OS Monterey
- jsFiddle example: https://jsfiddle.net/sv5x3ug1

#### Other Information
In the console, I do also get the following errors, although not entirely sure if relevant:
![image](https://user-images.githubusercontent.com/119734574/234646991-669ac664-0ba6-40ed-b334-83c57d5193ee.png)

**Comment by JetShen** [comment]
Did you find a solution?

**Comment by james-gulland** [comment]
> Did you find a solution?

yes, I did.  Found it here: https://stackoverflow.com/questions/51424578/embed-youtube-code-is-not-working-in-html

By adding `SECURE_REFERRER_POLICY = "no-referrer-when-downgrade"` it worked after then.

**Comment by dennisat** [comment]
Just add somewhere in the `<head>` this

```
<meta name="referrer" content="no-referrer-when-downgrade">
```
