### ISSUE TITLE
Multiple sources for video not working (url as array of string)

### ISSUE THREAD

**Issue by duranmla** [cookpete/react-player#1624]
#### Current Behavior
Valid video doesn't play when passing a url as array, therefore, we can't take advantage of video element API to fallback to different video sources depending on what the browser can play

It seems like src="undefined" is set on the video and perhaps that can be part of the issue? You seem to have a PR for that https://github.com/cookpete/react-player/pull/1622 

Check code sandbox below to check the behavior:

https://codesandbox.io/embed/loving-mcclintock-vefv65?fontsize=14&hidenavigation=1&theme=light

#### Expected Behavior

I will expect to behave as the video HTML tag such as: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video in which if the first source is wrong or resolve error then goes to the following.

**Comment by duranmla** [comment]
Far from ideal but just for the record what I am doing right now is to handle the iteration of different sources until no error found manually:

```tsx
const handleOnError = useCallback(
  (_error: Error) => {
    if (currentUrlIndex < urls.length - 1) {
      setCurrentUrlIndex(currentUrlIndex + 1);
      return;
    }

    ...
  },
  [/*...*/]
);

<ReactPlayer
    key={urls[currentUrlIndex]} // Important so we are able to 'change' the player on every change of the url to render
    ref={videoRef}
    url={urls[currentUrlIndex]}
    ...
/>
```

**Comment by martavis** [comment]
Since `2.11.1` is the reason for this issue, I downgraded to `2.10.0` and it works well.

**Comment by luwes** [comment]
fixed in https://github.com/cookpete/react-player/pull/1612
please comment if not solved on your end.

**Comment by duranmla** [comment]
Hey! It seems we have drop the possibility to throw errors with this last fix, if you check https://codesandbox.io/embed/condescending-water-m6qdjr?fontsize=14&hidenavigation=1&theme=dark you will see I am using the latest version of the library and there is no `console.log` of errors despite both video URLs have the "BAD" suffix for them to fail.

**Comment by duranmla** [comment]
Trying the above issue at https://github.com/cookpete/react-player/issues/1692
