### ISSUE TITLE
Vimeo video not playing on mobile

### ISSUE THREAD

**Issue by adamalexandru4** [cookpete/react-player#1626]
#### Current Behavior
Video is autoplaying on desktop but not playing on mobile devices

#### Expected Behavior
Working on all kind of devices

#### Steps to Reproduce
```
<ReactPlayer 
          url={videoUrl}
          config={{
             vimeo: {
                 playerOptions: {
                     controls: false,
                     byline: false,
                     playing: true,
                     autoplay: true,
                     title: false,
                     portrait: false,
                     responsive: true,
                     volume: 0.5,
                     playsinline: true,
                     quality: '4k'
                 }
             }
          }}
          width={"100%"}
          height={"auto"}/>
```

#### Environment
- URL attempting to play: https://player.vimeo.com/video/758313778
- Browser: Chrome/Safari (desktop/mobile)
- Website link:proteintogo.ro

**Comment by KimeraMoses** [comment]
Same issue happening for Youtube videos only on mobile

  <ReactPlayer
            className='react-player'
            url='https://www.youtube.com/watch?v=Jb-DbFutM7M'
            width='100%'
            height='100%'
          />

**Comment by mikhailmtion** [comment]
@adamalexandru4 , @KimeraMoses , @PedroTiagoSimao  
Hi, I can't test on Safari browser. Try **autoplay= false, volume = 0, muted.**

**Comment by adamalexandru4** [comment]
You could try on my landing page: https://proteintogo.ro. They're a "See video" button and you could check. @mikhailmtion

**Comment by mikhailmtion** [comment]
@adamalexandru4 Can you send an you example to codesanbox?
