### ISSUE TITLE
m3u8 not working on Safari Desktop

### ISSUE THREAD

**Issue by EzequielVegaOrigin** [cookpete/react-player#1627]
I have a Next.js application in it using the ReactPlayer to play a streaming, this streaming comes with the m3u8 format. But when I run it in Safari Desktop it fires the onError event and in it shows the error "hlsError".

![Captura de pantalla 2023-05-04 a la(s) 10 37 24](https://user-images.githubusercontent.com/110006360/236221999-a6a270f9-3195-4aee-8bf5-23c328144ef7.png)

#### Environment
- URL attempting to play:  https://playerservices.streamtheworld.com/api/livestream-redirect/XHFOFMAAC.m3u8?dist=web-radiodisney
- Browser: Safari Desktop 16.4 (18615.1.26.11.23)
- Operating system: macOS

#### Other Information
When trying to play the URL in the [example page](https://cookpete.com/react-player/), the stream plays for about a minute and then the stream is cut, I checked the console logs and found that the following error was triggered

<img width="440" alt="Captura de pantalla 2023-05-04 a la(s) 10 45 04" src="https://user-images.githubusercontent.com/110006360/236224903-c8293aad-2ba5-489b-a887-4997d9e11837.png">

**Comment by karlhorky** [comment]
I think we're experiencing this same issue too - @cookpete can you confirm that this is a current bug in ReactPlayer?

**Comment by karlhorky** [comment]
@cookpete looking through the ReactPlayer changelog, it seems that `forceSafariHLS` was introduced in https://github.com/cookpete/react-player/pull/1560 by @nabeards, but as mentioned in the comment below, was meant to force usage of the native HLS capabilities instead of using `hls.js`:

> @cookpete Was about to integrate the changes, but I just realized that I think you reversed the logic here. The idea is to force the _native_ HLS player on macOS Safari. Instead, you've made it force the _hls.js_ player.

https://github.com/cookpete/react-player/pull/1560#issuecomment-1477246742

Maybe adding this feature as originally intended by @nabeards would actually allow for resolution of this #1627 issue as well, if you consider my point above about `<video>` working as intended.

**Comment by karlhorky** [comment]
## Workaround

In the meantime, I am going to investigate using other solutions for HLS videos, including [`@ducanh2912/react-hls-player`](https://www.npmjs.com/package/@ducanh2912/react-hls-player), a maintained version of [`react-hls-player`](https://www.npmjs.com/package/react-hls-player). Seems like simpler code (with fewer features than ReactPlayer) and more updated.

**Comment by karlhorky** [comment]
Hm, after digging deeper, it does indeed seem to be an (intermittent) issue related to HLS.js - only the Safari native player can play the videos:

- https://github.com/video-dev/hls.js/issues/5709

**Comment by karlhorky** [comment]
@cookpete So maybe it's indeed best to [add an option disable HLS.js for Safari on macOS / iOS / iPadOS](https://github.com/cookpete/react-player/issues/1627#issuecomment-1656089038), as @nabeards intended to do with #1560

**Comment by karlhorky** [comment]
@luwes this was closed as "not planned" - does this mean that it doesn't fit the goals of ReactPlayer to have an option to disable HLS.js for Safari on macOS, iOS and iPadOS?

#1560 was merged but [the logic was reversed before the PR merge](https://github.com/cookpete/react-player/pull/1560#issuecomment-1477246742) - so the change was actually never made.

**Comment by luwes** [comment]
have you tried using `forceDisableHls` on Safari Desktop? I think that should disable hls.js and use native HLS instead

**Comment by karlhorky** [comment]
Ah, I didn't see the PR by @ablackoff in April 2023 adding this 😮

- https://github.com/cookpete/react-player/pull/1625

That sounds like it could work, thanks!
