### ISSUE TITLE
Origin errors on Youtube videos

### ISSUE THREAD

**Issue by marcelcaferati** [cookpete/react-player#1628]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior
When you try to load a youtube video you get spammed with the following error: 

`Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('https://cookpete.com').
q`

#### Expected Behavior

Not getting the error

#### Steps to Reproduce

1. Didn't do much, just load the player on localhost and got that error, then i checked cookpete.com and the same error happened

#### Environment
- URL attempting to play: https://www.youtube.com/watch?v=oUFJJNQGwhk
- Browser: Chrome
- Operating system: MacOS 

#### Other Information
![image](https://user-images.githubusercontent.com/9299583/236315840-55c1cce5-ddfd-435f-b04e-e585d94dd77b.png)

**Comment by jahtomini** [comment]
I've got the same issue

**Comment by luwes** [comment]
thanks for the feedback!

React player can't do anything about that, it's coming from the internal YT scripts.
the official YT demo also has these errors.

https://developers.google.com/youtube/youtube_player_demo

it's nothing to worry about because the errors are handled in a try / catch...
