### ISSUE TITLE
video freezes when started on ABR

### ISSUE THREAD

**Issue by newskys** [cookpete/react-player#1635]
#### Current Behavior

The video freezes when the first video chunk is playing while the audio is normally playing.
It plays fine from the next chunk onwards.

#### Expected Behavior

The video plays seamlessly

#### Steps to Reproduce

1. open https://cookpete.com/react-player/
2. press "Stop" button (to prevent autoplay when video is loaded)
3. put https://video.mathflat.com/concept/sample/sample.m3u8 (ABR) to sample url input and press "Load" button.
4. press "Play" button
5. The issue will be shown

#### Environment
- URL attempting to play: https://video.mathflat.com/concept/sample/sample.m3u8
- Browser: Chrome
- Operating system: Mac

#### Other Information

I found That other ABR video(https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8) seems to work fine. inside that m3u8 file, `#EXT-X-VERSION` is written `1`. otherwise, our sample's version is `3`.
Is this version related to this issue?

**Comment by luwes** [comment]
on my end it seems to play normally. is this still an issue on your end?
