### ISSUE TITLE
Lazy loading for YouTube video doesn't work for me (neither play button with light)

### ISSUE THREAD

**Issue by levipadre** [cookpete/react-player#1643]
#### Current Behavior
I'm trying to lazy-load a youtube video, but neither `light` or `lazy` version seems to be working.

#### Expected Behavior
For the `light` version, I need to click on the actual play button again to start the video, but this is working well on the test site.
The lazy version doesn't work at all. When I check on the Network tab (Doc) I can see that the video loads immediately, even if it's below the fold.

#### Environment
For `light` version: https://codesandbox.io/s/immutable-dust-gdwyxr?file=/src/App.js
For `lazy` version: https://codesandbox.io/s/elegant-blackburn-lwsl68?file=/src/App.js

#### Other Information
For lazy loading can't you add simply loading="lazy" to the iframe? It's supported now on every browsers.

**Comment by TomHennessy** [comment]
Try loading the `react-player` like this instead:
```javascript
const ReactPlayer = lazy(() => import('react-player'))
```

replacing:
```javascript
import ReactPlayer from "react-player/lazy";
```

The built in lazy loading didn't work for me either but this method does. Our use cases are different however as I don't want mine to play on load. Hopefully it helps!

**Comment by luwes** [comment]
this is working as expected.

React player lazy is different than iframe lazy. 
see https://react.dev/reference/react/lazy
and https://developer.mozilla.org/en-US/docs/Web/Performance/Lazy_loading#images_and_iframes

for the light mode to autoplay when clicking, set `muted` to true and `playing` to true

hope this helps
