### ISSUE TITLE
Disable the context menu on entire React player component 

### ISSUE THREAD

**Issue by edotappstore** [cookpete/react-player#1644]
Hi there

I want to know whether we can disable the context menu on entire ReactPlayer component, I can see there is one config setting to achieve this for  file as below
`
<ReactPlayer
          url='http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4'
          playing
          config={{ 
            file: { 
              attributes: {
                onContextMenu: e => e.preventDefault()
              } 
            } 
          }}
        />
` 

but can this be done for entire ReactPlayer component?

Thank You

**Comment by luwes** [comment]
thank you for the question but this problem is out of scope for ReactPlayer.
search for disabling context menu on Google or Stackoverflow.
https://stackoverflow.com/questions/381795/how-to-disable-right-click-context-menu-in-javascript
