### ISSUE TITLE
Watch Later, Description , suggestion video - want to hide that

### ISSUE THREAD

**Issue by sarojghalan** [cookpete/react-player#1646]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior
while setting controls={false} all the  content like watch later , description suggestion video are showing

#### Expected Behavior

After setting controls={false} i was expecting all content wont show
#### Steps to Reproduce

1.
1.
1.

#### Environment
- URL attempting to play: https://youtu.be/fg_5chxKCHo?t=437
- Browser: google
- Operating system: Window 11
- jsFiddle example: https://jsfiddle.net/sv5x3ug1

**Comment by vivekvdwivedi** [comment]
Youtube no longer allows this.
