### ISSUE TITLE
Is there a way to have the thumbnail show until the video starts autoplaying?

### ISSUE THREAD

**Issue by juhojung-milanlaser** [cookpete/react-player#1649]
I'm aware that you are able to have the property, 'light' to have a thumbnail before the video plays. 

However, you have to click on the thumbnail to play the video.

I want to see if there is a way to display the thumbnail for a second before the video is loaded in.

Here's what it looks like currently.
`        <ReactPlayer
          className="limit-height"
          playing={true}
          loop={true}
          controls={false}
          muted={true}
          width="100%"
          height="100%"
          playsinline={true}
          url="https:/example.video.m3u8"
        />`

**Comment by TomHennessy** [comment]
Can you do something manually using the `onStart` callback? You could have something like this:
```
{!hideImage && <img src='/image.png' />}
<ReactPlayer className="limit-height" playing={true} loop={true} controls={false} muted={true} width="100%" height="100%" playsinline={true} url="https:/example.video.m3u8" onStart={hideImage} />
```
With a handler like:
```javascript
const hideImage = () => setHideImage(true)
```

I've done something similar so I hope this helps!

**Comment by cookpete** [comment]
@TomHennessy is correct. The best way is to use `onStart` and show/hide the thumbnail/player based on the state.

**Comment by joseph-allen** [comment]
Great workaround, but a bit annoying to need to do this for each image in my project when I already have light set up
