### ISSUE TITLE
Question: Mobile browser workaround for audio

### ISSUE THREAD

**Issue by briansayles** [CookPete/react-player#165]
I am aware of the issues surrounding mobile browsers. My app needs to play a sound (using filePlayer) based on a timer, like an alarm clock. Wondering what method you would recommend for this. My proposed method is essentially:

1. Set soundReady state to true when the sound loads. On mobile, this won't automatically happen, even when preload is set to true.    onReady={() => this.setState({soundReady: true})}
2. Use the fact that soundReady won't be true on mobile to show an "enable sound" button.
3. When "enable sound" is clicked, load the sound:   this.endOfRoundMP3.player.load("/0226.mp3"); 
4. When the timer detects that the sound should play, set another state variable that gets used by the "playing" prop:    playing={this.state.playingEndOfRound}

I've been unable to get this working, though. The first 3 steps work fine. In fact, when the "enable sound" button is clicked, I can trigger both the load() and play() functions. But calling play() in the timer or setting the playing prop via a state variable (as shown in 4 above) doesn't work. Any help would be greatly appreciated.

If we can get this working, I'd be willing to offer to write up the technique that you could include in your documentation.

**Comment by CookPete** [comment]
One big problem with some mobile browsers is that they are specifically programmed to only play audio/video as a result of a user interaction (ie a tap on the screen). Consider this bit from the [Safari HTML5 docs](https://developer.apple.com/library/content/documentation/AudioVideo/Conceptual/Using_HTML5_Audio_Video/Device-SpecificConsiderations/Device-SpecificConsiderations.html):

>This means the JavaScript play() and load() methods are also inactive until the user initiates playback, unless the play() or load() method is triggered by user action. In other words, a user-initiated Play button works, but an onLoad="play()" event does not.

You could try playing and then immediately pausing an audio file as a user clicks to enable audio, then the player is "primed" by the browser as a valid audio source, and calling `play()` some time later might work.

If you can get delayed audio playback to work on mobile, then an example would definitely be appreciated, and worthy of adding to the docs.

**Comment by CookPete** [comment]
Closing this off, assuming this is a browser restriction and not a fault with ReactPlayer.
