### ISSUE TITLE
Disabling PIP mode with Vimeo

### ISSUE THREAD

**Issue by Cochonours** [cookpete/react-player#1652]
#### Current Behavior
Whether I do not set the pip attribute in the config or set it to false, it doesn't matter as on my Android phone I get the PIP option in my vimeo videos. Maybe it's true for other websites, but I just tried with Vimeo.

#### Expected Behavior
I don't want the PIP option to be available at all.

#### Steps to Reproduce
1. `<ReactPlayer url="https://vimeo.com/759911151" />`
2. Check on phone (I'm using a Samsung and Chrome based browser)
3. You see the PIP option in the video.

#### Environment
- URL attempting to play: https://vimeo.com/759911151
- Browser: any Chrome based browser
- Operating system: Android

#### Other Information
Additionnaly, the PIP doesn't work as when I click on it the video opens up in PIP mode, but doesn't start automatically (and clicking in the PIP video doesn't start it either).

**Comment by Cochonours** [comment]
It seems that using playsinline={true} fixes the PIP window. Not sure that should be the way..

**Comment by cookpete** [comment]
Did you try `config={{ playerOptions: { pip: false }}}`?

https://jsfiddle.net/y1p6fde9/1/
