### ISSUE TITLE
The audio does not auto play when we refresh the Page.

### ISSUE THREAD

**Issue by DhavalAlbiorix** [cookpete/react-player#1658]
import React, { useState, useEffect } from "react";
import ReactPlayer from "react-player";

const App = () => {
  // Get the stored playback state from localStorage
  const storedPlaybackState = localStorage.getItem("playbackState");

  // Initialize the isPlaying state based on the stored state
  const [isPlaying, setIsPlaying] = useState(storedPlaybackState === "playing");

  useEffect(() => {
    // Update localStorage when the isPlaying state changes
    if (isPlaying) {
      localStorage.setItem("playbackState", "playing");
    } else {
      localStorage.setItem("playbackState", "paused");
    }
  }, [isPlaying]);

  return (
    <div className="App">
      <button onClick={() => setIsPlaying(!isPlaying)}>
        {isPlaying ? "Pause" : "Play"}
      </button>
      <ReactPlayer
        url={"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3"}
        playing={isPlaying}
        controls={true}
      />
    </div>
  );
}

export default App;

Versions : 
"react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-player": "^2.12.0",
    "react-scripts": "5.0.1",

**Comment by luwes** [comment]
could you provide a code sandbox online? or what do the browser logs output?

autoplay with sound in modern browsers is not allowed, it requires a user gesture (click).
that might be causing this...
