### ISSUE TITLE
No autoplay when loading page

### ISSUE THREAD

**Issue by killerburn69** [cookpete/react-player#1660]
i just found out this warning, how can i fix it?
Unmuting failed and the element was paused instead because the user didn't interact with the document before.
thanks you
could you give me example code to fix it using reactjs

**Comment by IsaacMCarter** [comment]
Did you add "playing" to the ReactPlayer Component?
<ReactPlayer
playing
>

**Comment by luwes** [comment]
see https://github.com/cookpete/react-player#autoplay
