### ISSUE TITLE
Video quality is not good for few initial seconds 

### ISSUE THREAD

**Issue by deepak626k** [cookpete/react-player#1663]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Steps to Reproduce

1.
1.
1.

#### Environment
- URL attempting to play: 
- Browser: 
- Operating system: 
- jsFiddle example: https://jsfiddle.net/sv5x3ug1

**Comment by luwes** [comment]
React player will render the browser's native video player when using progressively downloaded mp4's so there is nothing React player can do about the quality. I recommend using video streaming like hls.js or Dash to get better quality video.
