### ISSUE TITLE
Sponsored issue: The volume control doesn't work.

### ISSUE THREAD

**Issue by drokbers** [cookpete/react-player#1665]
## Priority Support

- @drokbers is using  [Mintycode](https://mintycode.io) to fund this issue.
- You can receive ![amount](https://imageupload.io/ib/zwkd2EaAY6YpPsg_1693209112.png) if you provide priority support to @drokbers. 
- To view the support request and terms go to  [Mintycode](https://mintycode.io/profile?action=CREATOR_SUPPORT_MODAL&requestId=c1ee038a-773d-4a2d-914f-4b26c6d2a3de&owner=cookpete&name=react-player).
- Thank you in advance for helping.

[![mintycode](https://imageupload.io/ib/LvxMwrPxam1JW9e_1693210482.png)](https://mintycode.io)

**Comment by luwes** [comment]
might not be related but software volume control on mobile is rarely supported. on iOS it is not.
