### ISSUE TITLE
FilePlayer not working with URL array

### ISSUE THREAD

**Issue by IgoP02** [cookpete/react-player#1669]
#### Current Behavior

Passing a source array to ReactPlayer's url prop results in an undefined src tag in the rendered `<video>` element.
Passing a single string works perfectly.
#### Expected Behavior

The provided files should be played correctly
#### Steps to Reproduce

Create react app
Import ReactPlayer from "react-player"
Add component
```
<ReactPlayer
          width="100%"
          height="100%"
          url={[
            {
              src: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
              type: "video/webm",
            },
            {
              src: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
              type: "video/mp4",
            },
          ]}
          controls
        />

```
#### Environment
- URL attempting to play: http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4
- Browser: Chrome Version 116.0.5845.110 x64
- Operating system: Linux Mint x64

#### Other Information
Already tried downgrading to 2.10.1 as seen in https://github.com/cookpete/react-player/issues/1508#issuecomment-1264387346
Already disabled StrictMode

Event
![image](https://github.com/cookpete/react-player/assets/40871105/90602fc4-113e-4564-8397-346be0a38ef3)
HTML element
![image](https://github.com/cookpete/react-player/assets/40871105/7ebe4a13-04c1-43fb-98e0-6644c8e86586)

**Comment by luwes** [comment]
could you provide a code sandbox online? thank you
