### ISSUE TITLE
Facebook video control not hide

### ISSUE THREAD

**Issue by usama78621** [cookpete/react-player#1670]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior
When I pass a Facebook video URL to the React Player and set the controls prop to false or attempt to hide the controls using CSS, the video controls are still visible and do not hide as expected.

#### Expected Behavior
I expect that when I pass a Facebook video URL to the React Player and set the controls prop to false or apply CSS to hide the controls, the video controls should be hidden to provide a clean video viewing experience.

#### Steps to Reproduce

1.first go this demo link  https://cookpete.com/react-player/
2. pass any Facebook video or click Test A Facebook
3. click controls false check it's still here

#### Environment
- URL attempting to play: 
- Browser:  chrome
- Operating system: window
- jsFiddle example: https://cookpete.com/react-player/

#### Other Information
i make custom player and custom controls it's work which all videos and YouTube but not work on Facebook video's

**Comment by luwes** [comment]
thanks for the feedback! 

unfortunately Facebook doesn't allow hiding the controls of their video embeds anymore.
see https://developers.facebook.com/docs/plugins/embedded-video-player#settings

there's not much that can be done about that in this project as it embeds the FB video via an iframe.
