### ISSUE TITLE
Load Vimeo Asynchronously 

### ISSUE THREAD

**Issue by dotdev-nikolaj** [cookpete/react-player#1671]
Is it possible to defer/async load the vimeo `https://f.vimeocdn.com/p/4.24.30/js/player.module.js` ?

Just wondering as it's lowering our lighthouse performance score.

Thanks!!! :)

**Comment by dotdev-nikolaj** [comment]
Bump! :)

**Comment by luwes** [comment]
yep with light mode https://github.com/cookpete/react-player#props

or with lazy mode https://github.com/cookpete/react-player#usage
