### ISSUE TITLE
Caption language options do not appear correctly with DASH format

### ISSUE THREAD

**Issue by jbrachtie** [cookpete/react-player#1675]
I believe there is an issue with the way React Player displays the language options for captions on DASH videos.

#### Current Behavior
When viewing a DASH video in the player that has captions, the available languages for captions show as numbers.
<img width="247" alt="captions-as-numbers" src="https://github.com/cookpete/react-player/assets/5508511/96282920-097f-42cb-b626-9d020f3d8cbf">

#### Expected Behavior
The available languages for captions should show the correct language names.

#### Steps to Reproduce
1. Find a url for a DASH video. I am using this one in my screenshots: https://rdmedia.bbc.co.uk/testcard/vod/manifests/avc-full.mpd taken from the [DASH reference client website](https://reference.dashif.org/dash.js/nightly/samples/dash-if-reference-player/index.html)  
1. Go to the react-player [demo site](https://cookpete.com/react-player/) and make sure to select the "Controls" checkbox.
1. Paste the mpd video link from above and click "Load"
1. With the video loaded, click the caption options (3-dot menu in Chrome, then "Captions")
1. The menu will show numbers instead of languages

#### Environment
- URL attempting to play: https://rdmedia.bbc.co.uk/testcard/vod/manifests/avc-full.mpd (or any mpd with captions)
- Browser: Chrome (115.0.5790.102), Firefox (117.0.1). I did not test others.
- Operating system: MacOS Ventura 13.4

#### Other Information
The expected behavior can be seen on other players, such as the [DASH reference player website](https://reference.dashif.org/dash.js/nightly/samples/dash-if-reference-player/index.html), or [Theo player test stream](https://www.theoplayer.com/test-your-stream-hls-dash-hesp)

**Comment by luwes** [comment]
React player has no control over this. Maybe bundled dash.js library needs a newer version.
