### ISSUE TITLE
PlaysInline does not work on iOS for Vimeo vidoes

### ISSUE THREAD

**Issue by bounddigital** [cookpete/react-player#1681]
#### Current Behavior
I have playsInline={true} set for all of our videos in our Ionic React app (we use Vimeo for all of our vidoes). If I enable autoplay, the videos play inline immediately on Android, which is perfect. However, on iOS, the video loads and then goes full screen immediately. If I change autoplay to false, on both iOS and Android, the video goes full screen when you press play. 

#### Expected Behavior
I expect the video to play inline as requested.

#### Steps to Reproduce
1. Set Vimeo videos as playsInline={true} in an Ionic React app. 
2. Set playing={true}
3. View the video on Android, note that it plays inline
4. View the video on iOS, note that it opens full screen
5. Change playing={false}
6. View the video on iOS or Android
7. Press play
8. Note the video opens full screen

#### Environment
- URL attempting to play: Mobile app
- Browser: N/A
- Operating system: iOS

#### Other Information
N/A

**Comment by luwes** [comment]
the docs mention it's all lowercase `playsinline`. could you try that out?
