### ISSUE TITLE
How can I make control always visible when playing?

### ISSUE THREAD

**Issue by tylim88** [cookpete/react-player#1697]
#### Current Behavior
Control is not visible if mouse is not hovering it

#### Expected Behavior
Control is visible if mouse is not hovering it

#### Steps to Reproduce

1. go to the demo site https://cookpete.com/react-player/
2. select mp4 video
3. turn on the control
4. play it
5. control disappear if no mouse is hovering it

#### Environment
- URL attempting to play: the mp4 video on the demo site
- Browser: google chrome
- Operating system: window 11
- jsFiddle example: none, i play it on the demo site

**Comment by luwes** [comment]
React player doesn't control that UI aspect of the player. It's the browser native player and UI.

I think the easiest solution  is to turn off controls on React Player and wrap it with your own custom video controls like provided in Media Chrome where you have full control of the player UI. https://github.com/muxinc/media-chrome
