### ISSUE TITLE
When minified, only one player component is mounted

### ISSUE THREAD

**Issue by Fauntleroy** [CookPete/react-player#17]
I'm having a bit of an odd issue here:

When I use `react-player` in my project, then minify the project bundle, only one of the players will mount (the YouTube player). I have a hunch that `displayName` is somehow involved (since all `react-player` components are shown as `t` in the React DevTools).

<img width="354" alt="screen shot 2015-12-27 at 9 05 25 am" src="https://cloud.githubusercontent.com/assets/507047/12010756/07868ada-ac79-11e5-8a70-c03dfe8f394f.png">

#### Steps to replicate

- Create a project that uses browserify
- Use `react-player` in that project
- Browserify your code
- Minify your code
- When the player is mounted, you should only see one player type mounted inside of it

#### Ideas

- Try minifying `react-player` in the test page and see if we can replicate the issue there
- Try manually setting `displayName` for every component

**Comment by Fauntleroy** [comment]
It looks like if you add a `displayName` to every component, the problem is resolved:

<img width="533" alt="screen shot 2015-12-27 at 9 20 37 am" src="https://cloud.githubusercontent.com/assets/507047/12010811/290386de-ac7b-11e5-81fa-50f2ad16e29f.png">

**Comment by CookPete** [comment]
Thanks for this @Fauntleroy! I'll add a quick commit and publish a patched version now.

**Comment by Fauntleroy** [comment]
![bro_arms](https://cloud.githubusercontent.com/assets/507047/12011941/78664972-aca9-11e5-93e5-d8e5a0d27560.gif)

**Comment by CookPete** [comment]
Fixed in [v0.3.1](https://github.com/CookPete/react-player/releases/tag/v0.3.1)

![Thumbs up](http://38.media.tumblr.com/1b2bf8f295427a9b5199e9f27bfe3d72/tumblr_inline_nnwohoB1d31roifue_500.gif)
