### ISSUE TITLE
It doesn't load youtube shorts 

### ISSUE THREAD

**Issue by natigGit** [cookpete/react-player#1700]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior
I put the link from youtube short video and it does not work.

#### Steps to Reproduce

1.
1.
1.

#### Environment
- URL attempting to play: 
- Browser: 
- Operating system: 
- jsFiddle example: https://jsfiddle.net/sv5x3ug1

**Comment by luwes** [comment]
I don't see any YT url in the example
