### ISSUE TITLE
Super expression must either be null or a function react player on Nextjs 13

### ISSUE THREAD

**Issue by itsaalexk** [cookpete/react-player#1701]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior

App crashes when trying to render video component from youtube , it  shows the following error: Super expression must either be null or a function react player

#### Expected Behavior

I expect the video to be rendered correctly

#### Steps to Reproduce

1. Install the library and create a component that renders a youtube video from https url
1. Render the component inside page.tsx file 

#### Environment
- URL attempting to play: https://www.youtube.com/watch?v=m8Icp_Cid5o
- Browser: Googcle Chrome 
- Operating system: Windows 11

#### Other Information

I think I know where the issue comes from, if its something that happens to anyone else , it would be nice to fix it on the next release

**Comment by luwes** [comment]
dup of #1565
related #1474
