### ISSUE TITLE
Error: Super expression must either be null or a function

### ISSUE THREAD

**Issue by jvialoux** [cookpete/react-player#1712]
#### Current Behavior

Using ReactPlayer as 

import ReactPlayer from 'react-player'; 

`<ReactPlayer ur={videoUrl} />`

 const videoURL returns .mp4 extension file hosted on contentful.

Nextjs 14 
React: 18.2.0

Error screenshot
<img width="960" alt="Screenshot 2023-11-15 at 17 12 45" src="https://github.com/cookpete/react-player/assets/108396993/60e10121-b0d3-404f-b2f2-b3cc0100caae">

**Comment by luwes** [comment]
dup of https://github.com/cookpete/react-player/issues/1565
