### ISSUE TITLE
Maintain aspect ratio

### ISSUE THREAD

**Issue by DVassilev** [CookPete/react-player#172]
My videos are portrait and I want to maintain aspect ratio of the video without having the element unnecessarily wide. I tried to use react-rectangle to keep the aspect ratio whilst setting width and height to 100% to make sure the element fills up the parent container but this didn't quite result in what I expected. Any tips on how to make the video keep a portrait aspect ration (9:16) and ensure that the element's width and height wrap the video?

**Comment by CookPete** [comment]
Does [this fiddle](https://jsfiddle.net/567rneoe/1/) get you anywhere? This looks like a similar problem to https://github.com/CookPete/react-player/issues/145

**Comment by DVassilev** [comment]
@CookPete That's how I ended up getting it working, thanks.
