### ISSUE TITLE
How To Disable Scrolling To The Top Of The Page After Existing FullScreen While Playing A Youtube Video in A NextJs Project

### ISSUE THREAD

**Issue by DevYemi** [cookpete/react-player#1723]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior

Hi there, thanks for providing this adorable package.
So I'm using the React-player in my NextJs project to play some YouTube video and everything works fine but when a user enables the YouTube full-screen feature and closes it the page is scrolled to the top of the page which is a bad user experience.

#### Expected Behavior

A user enables full screen while watching an embedded YouTube video and disables it, I want the scroll position to be persisted

#### Steps to Reproduce

1. Use the React-player to Embed a YouTube in the middle of a long webpage.
1. Enable full-screen feature.
1. Now exist the full-screen feature.

#### Environment
- URL attempting to play: https://youtu.be/8HD58SzwuBo
- Browser:  chrome
- Operating system: windows 11 64-bit operating system, x64-based processor
- jsFiddle example: "I'm finding it difficult to set up fiddle with nextJs and sandcodebox has the fullscreen feature disabled by default"

#### Other Information

Please Note: I'm using Next 13 and not just plain React

**Comment by DevYemi** [comment]
To anyone who might be facing this same issue in the future, it turns out that this happened because of a particular css style in my body:

````
body {
overflow: auto
}
````
I was able to fix this by refactoring it to:

````
body {
overflow: visible
}
````

**Comment by chenxu-javascript** [comment]
hi。Determine when to switch states Listen for fullscreenchange ？ and others
