### ISSUE TITLE
SoundCloud Playcounts?

### ISSUE THREAD

**Issue by a-s-f** [CookPete/react-player#173]
Does anyone know if songs played with react-player using soundcloud links adds to playcounts on soundclound?

**Comment by CookPete** [comment]
All ReactPlayer does is grab the `stream_url` for a track via JSONP and then set the `src` of an `<audio>` element. However, it does require a `client_id` to be appended to the `stream_url` path so it may be possible that the "play" is still registered with Soundcloud. 

I guess the only way to truly know would be to upload your own track to Soundcloud and play it only using ReactPlayer, and see if the play count goes up.

I'll close the issue as it is nothing to do with ReactPlayer, but @a-s-f feel free to update this issue if you manage to find anything out.
