### ISSUE TITLE
The player has an inconsistent look in different browsers

### ISSUE THREAD

**Issue by zverbatim** [CookPete/react-player#174]
Hi,

Attached are the screens of the player in different browser.
Chrome:
![chrome](https://cloud.githubusercontent.com/assets/4423975/24302362/60032850-1080-11e7-9162-efc2d63449e1.png)

Firefox:
![firefox](https://cloud.githubusercontent.com/assets/4423975/24302363/60051aca-1080-11e7-8fd9-95f408482689.png)

Safari:
![safari](https://cloud.githubusercontent.com/assets/4423975/24302361/60032440-1080-11e7-81cf-46e4d064ff9b.png)

Curious to know why it looks inconsistent and if there is a workaround to make it look the same.

Thanks

**Comment by DVassilev** [comment]
I'd imagine the difference is due to the each browser having it's own design for controls when you don't specify your own custom controls. Here are two links for building your own custom controls:
- https://developer.mozilla.org/en-US/Apps/Fundamentals/Audio_and_video_delivery/cross_browser_video_player
- http://blog.teamtreehouse.com/building-custom-controls-for-html5-videos

**Comment by zverbatim** [comment]
@DVassilev would you suggest to make a custom component that will render the
- play/pause button
- "timeline"
- volume control
- download icon
this way through css one can ensure the styling is consistent?

**Comment by DVassilev** [comment]
@zverbatim If that's what you want to do, sure

**Comment by zverbatim** [comment]
@DVassilev probably i'll have to make my own component. This one relies on `<audio>` tag.
Example:
```
<audio preload="auto" controls="" webkit-playsinline="" src="audio.wav" style="width: 100%; height: 100%; display: block;"></audio>
```

**Comment by CookPete** [comment]
Any raw video/audio URL passed in to ReactPlayer is played using native `<video>` or `<audio>` elements to let each browser load and display the media as they see fit. The difference you see is simply a result of each browser's native controls looking different.

This has the advantage of avoiding any bugs or constraints of custom controls (eg how would you support Safari's AirPlay with custom controls?), but you can always use `controls={false}` and render your own using some sort of internal state (like the [demo page](https://github.com/CookPete/react-player/blob/master/src/demo/App.js)). The library is deliberately flexible in this regard and gives you the freedom to control it (or not control it) as you wish.
