### ISSUE TITLE
Full Screen mode not working in Iphone

### ISSUE THREAD

**Issue by vishaljkk** [cookpete/react-player#1742]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior
I'm unable to open full screen in ios
![image](https://github.com/cookpete/react-player/assets/43497345/474f4578-14c5-46ae-b1a6-0be59cf2cf68)

#### Expected Behavior
![image](https://github.com/cookpete/react-player/assets/43497345/fe08764f-99c8-41de-ab3a-2ad0c87047af)

#### Steps to Reproduce
1. open https://cookpete.com/react-player/ in iphone and start the video in full screen mode

#### Environment
- URL attempting to play: https://youtu.be/Ji_HOZgoRBI?feature=shared
- Browser: Safari
- Operating system: IOS 
- live example: https://cookpete.com/react-player/

**Comment by luwes** [comment]
duplicate https://github.com/cookpete/react-player/issues/155
