### ISSUE TITLE
Loading a list of <audio>

### ISSUE THREAD

**Issue by zverbatim** [CookPete/react-player#175]
Hi,

I have more than a dozen of audio files displayed using this component in one page.
The files take some time to load. As a result the user sees first a blank page than how those players get rendered randomly.

Wonder if there is a way to show a _loading ..._ state until all the audio files are fetched and than display al the players.

Thanks

**Comment by DVassilev** [comment]
Use the onReady callback to know when a player is ready. Use the hidden prop to hide player before it's ready and show custom message.

**Comment by zverbatim** [comment]
Is there a way to have a `onReady` for all the players in the list?
If i'll use `onReady` for each individual player than they will display randomly.
Expected behavior to show them at once.

**Comment by zverbatim** [comment]
Here is a gif:
![audios](https://cloud.githubusercontent.com/assets/4423975/24464334/1866c996-146f-11e7-8a1d-f5594bdb5792.gif)

**Comment by CookPete** [comment]
You could use `onReady` but increase a counter every time a player is ready. Once the count matches the number of audio files you're loading, you can show the players. This would also let you show `x of y files loaded`, or a progress bar.

You'll still need to render the players for them to load, so I guess you'll need to use `opacity: 0` or similar until they are all ready.

**Comment by zverbatim** [comment]
Thanks. That will work.
