### ISSUE TITLE
react-player not playing avi, wmv , mov type format 

### ISSUE THREAD

**Issue by nareshallakonda** [cookpete/react-player#1760]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior
  <ReactPlayer
           url= {`data:${mimetypefiles};base64,${previewPath}`}
           controls
           width="100%"
           height="100%"
          />

#### Expected Behavior
I am trying above way , its not play above 5MB videos and not playing avi, wmv, mov type format.?

**Comment by luwes** [comment]
if the browser doesn't support these formats, React player can't play them
