### ISSUE TITLE
Support needed for KillerPlayer as just embed code is generated but using the src from embed code as url does not work.

### ISSUE THREAD

**Issue by nagarajay** [cookpete/react-player#1770]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.
I did search for issue with KillerPlayer but seems this is not supported. This is not a promotion of KillerPlayer neither I work or own the company. I just have bought their product and liked the idea of hosting my videos on Youtube and use them on my website.

#### Current Behavior

KillerPlayer give an embed code iframe obviously and there is no way to link the same to ReactPlayer. 

#### Expected Behavior

Hoping that as we have for Vimeo or other players we will be either be able to link or run the same using ReactPlayer.

#### Steps to Reproduce

1. KillerPlayer is free so just try converting a youtube video and then take the Embed Code.

#### Other Information
I have a nextjs 14 project and am able to get Vimeo to work but unable to get KillerPlayer to work. Have added the a snippet of an example of the embed code that is produced.
<iframe style='display:block;margin:auto;width:745px;max-width:100%;aspect-ratio:1.7780429594272076;' src='https://killerplayer.com/watch/video/dc291539-1edb-47fb-bac6-ccf8bde9ea1e' frameborder="0" allow="autoplay; gyroscope; picture-in-picture;" allowfullscreen></iframe>

I tried running the url given in src i.e. https://killerplayer.com/watch/video/dc291539-1edb-47fb-bac6-ccf8bde9ea1e' it works but linking it to react player url does not work.

**Comment by luwes** [comment]
thanks for the feedback but killerplayer will not be added to React player.

you can add custom players yourself via the API provided 
https://github.com/cookpete/react-player#adding-custom-players
