### ISSUE TITLE
react-player attempts to call `this.player.getDuration()` before method is available

### ISSUE THREAD

**Issue by Fauntleroy** [CookPete/react-player#18]
If you tell the YouTube player to seek before the SDK has finished loading, `react-player` will attempt to call `getDuration()` and throw. I haven't checked into this with the other players yet.

Should be a simple fix: add a flag for whether or not the SDK has loaded yet. If the flag is false, don't try to call any methods provided by that SDK. Might also want to wrap the SDK methods with something normalized that does that check before calling the real method.

(Sorry about making issues with recommendations but not pull reqs—it's a bit difficult to get the full flow going while on holiday)

**Comment by CookPete** [comment]
I'm surprised the function doesn't [return here](https://github.com/CookPete/react-player/blob/master/src/players/YouTube.js#L95) in that case. Maybe that check needs to be better than just whether `this.player` exists.

> Sorry about making issues with recommendations but not pull reqs—it's a bit difficult to get the full flow going while on holiday

No problem. Stop developing on holiday! :beers:
