### ISSUE TITLE
no support for Loom videos

### ISSUE THREAD

**Issue by shushy245** [cookpete/react-player#1856]
#### Current Behavior
Loom videos aren't supported

#### Expected Behavior
Loom videos should be supported

#### Steps to Reproduce
use Loom URL
observe it as it does not work

would be very happy because my company are trying to find a workaround and we'd rather not abandon your player as it's very nice to use
thanks! :)

**Comment by luwes** [comment]
thanks for the feedback!
unfortunately the Loom player doesn't have a public playback API so it wouldn't be any more useful as a simple iframe embed.
