### ISSUE TITLE
m.youtube.com/<videoId> URLs cause 'Unable to post message' error, player doesn't load

### ISSUE THREAD

**Issue by jtewright** [CookPete/react-player#186]
Simple workaround is to grab the videoId from the URL and make a youtu.be/ or youtube.com/ url, you could do the same with the url passed to the component.

**Comment by CookPete** [comment]
The video ID is already extracted from the URL, but `m.youtube.com` wouldn't work anyway as it doesn't match the [regex for youtube URLs](https://github.com/CookPete/react-player/blob/master/src/players/YouTube.js#L10). It can be easily added though.

**Comment by CookPete** [comment]
The video ID is already extracted from the URL, but `m.youtube.com` wouldn't work anyway as it doesn't match the [regex for youtube URLs](https://github.com/CookPete/react-player/blob/master/src/players/YouTube.js#L10). It can be easily added though.
