### ISSUE TITLE
music.youtube gets Video Unavailable post build or from 127.0.0.1

### ISSUE THREAD

**Issue by cowdude679** [cookpete/react-player#1878]
#### Current Behavior
After building with vite and providing a youtube music url, the player shows 'Video Unavailable'. Same behavior when using 127.0.0.1 or local lan 192.x.x.x. Possibly a problem with trying to access videos via ip address?
https://music.youtube.com/watch?v=auQxNYJ07Lc&si=XaZP4i0EaRec8IQ1

#### Expected Behavior
Like when running in dev mode, I'd expect the video to play

#### Steps to Reproduce
1. Build project
2. Try to play a music.youtube video

#### Environment
- URL attempting to play: https://music.youtube.com/watch?v=auQxNYJ07Lc&si=XaZP4i0EaRec8IQ1
- Browser: Chrome 128.0.6613.84 (Official Build) (64-bit)
- Operating system: Windows 11 Pro 
- vite 5.3.1
- react-player 2.16.0 and 3.0.0-canary.3

#### Other Information
``` 
export const Player = () => {
  const [wss, setWSS] = useState(undefined);
  const [togglePlay, setTogglePlay] = useState(false);
  const [playlist, setPlaylist] = useState([]);
  const [nowPlaying, setNowPlaying] = useState("");

  useEffect(() => {
    const ws = new WebSocket("ws://" + ITS_ME);
    ws.addEventListener("open", () => {
      ws.addEventListener("message", (messageEvent) => {
        const message = JSON.parse(messageEvent.data);
        switch (message.event) {
          case "queue":
            setPlaylist(message.queue);
          default:
            null;
        }
      });
    });

    setWSS(ws);

    return () => {
      ws.close();
    };
  }, []);

  useEffect(() => {
    setNowPlaying(playlist[0]?.url);
    setTogglePlay(true);
  }, [playlist]);

  const ended = () => {
    setTogglePlay(false);
    fetch(baseUrl("/api/next"));
  };

  return (
    <>
      <ReactPlayer
        url={nowPlaying ?? ""}
        playing={togglePlay}
        muted={!togglePlay}
        controls={true}
        onEnded={ended}
        onError={(error) => {
          console.error(error);
        }}
      />
      {playlist.length == 0 && <div>Nothing here boss</div>}
      {playlist.length > 0 && (
        <ol>
          {playlist.map((e, idx) => {
            return (
              <li key={idx}>
                <div style={{ fontWeight: 800 }}>[{e.url}]</div>{" "}
                <div style={{ marginLeft: "2rem" }}>
                  as suggested by {e.user}
                </div>
              </li>
            );
          })}
        </ol>
      )}
    </>
  );
};

```

**Comment by cardmajor** [comment]
having same issue too video unable, where you able to resolve? @cowdude679

**Comment by cowdude679** [comment]
yeh man. I needed to get a domain or use 127.0.0.1 for local development. Whatever reason youtube music doesn't like ip addresses

**Comment by cardmajor** [comment]
okay thanks, i just use ngrok to serve it work @cowdude679

**Comment by luwes** [comment]
this is how the YT player iframe behaves in local development. `localhost` might work instead of `127.0.0.1`
