### ISSUE TITLE
onError not firing when playing a locked youtube video

### ISSUE THREAD

**Issue by nmqanh** [CookPete/react-player#191]
I am trying to play a video such as `https://www.youtube.com/watch?v=229K5n_PRJA` but that video is locked so it can't play but the callback `onError` never fired.
I want to handle onError on this case so the player can play next song automatically rather than just stopping there.

**Comment by CookPete** [comment]
Not sure why `onError` is not firing for you, but it is for me. Trying playing it in the [demo app](http://cookpete.com/react-player/) and check the console.
