### ISSUE TITLE
Splitting channels

### ISSUE THREAD

**Issue by olegafx** [CookPete/react-player#194]
Is it possible to process each audio channel separately?  For example, mute only first channel.
Web audio api contains `ChannelSplitterNode` description for similar cases.

@CookPete, thanks for your work, btw

**Comment by CookPete** [comment]
I don't know much about the Web Audio API, but you can get the `<audio>` element from ReactPlayer like so:

```js
class Player extends Component {
  componentDidMount () {
    const audio = this.refs.rp.player.player
    console.log(audio) // Logs the <audio> element
  }
  render () {
    return (
      <ReactPlayer ref='rp' playing url='file.mp3' />
    )
  }
}
```

You should be able to do any sort of processing from there.
