### ISSUE TITLE
Custom audio

### ISSUE THREAD

**Issue by ayxos** [CookPete/react-player#197]
Is there any way to play a youtube video using a custom audio file? any example?

**Comment by CookPete** [comment]
You could render a Youtube video with `volume={0}` and another `ReactPlayer` with `url='your-file.mp3', like so:

```jsx
<div>
  <ReactPlayer
    url='https://www.youtube.com/watch?v=Y_hc07rAQlc'
    playing
    volume={0}
  />
  <ReactPlayer
    url='https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3'
    playing
  />
</div>
```

See [example jsFiddle](https://jsfiddle.net/99ee3atp/4/)
