### ISSUE TITLE
Better handling of YouTube methods before player is ready

### ISSUE THREAD

**Issue by CookPete** [CookPete/react-player#20]
@Fauntleroy has found that `play()` can sometimes be called before `this.player.playVideo` exists. https://github.com/CookPete/react-player/commit/f18792a2da3167f775d48481aa8eae150b747d4d prevents errors for the time being, but doesn't really fix the problem.

From [this discussion](https://github.com/CookPete/react-player/commit/ef17dcc732d282f027aa3bddf8f91cbb05998cc8#commitcomment-15231248).

**Comment by Fauntleroy** [comment]
@CookPete I think I found the culprit: `this.getSDK()` can get called more than once. It's initially called for the blank video load, but it will be called again if you load another video before the SDK loads.
