### ISSUE TITLE
Ted talks support

### ISSUE THREAD

**Issue by mvpspl619** [CookPete/react-player#202]
Is there any plan for supporting Ted videos? All the Ted talk urls(https://www.ted.com/talks/jeremy_rifkin_on_the_empathic_civilization) can literally be converted to iframe embeds by replacing the "www" with "embed". 

So https://www.ted.com/talks/jeremy_rifkin_on_the_empathic_civilization would become https://embed.ted.com/talks/jeremy_rifkin_on_the_empathic_civilization.

**Comment by CookPete** [comment]
The point of the library is to play _and control_ media from various different URLs. As far as I can see, there is no TED player SDK and it looks like the [open API is now closed](http://developer.ted.com/). 

It seems a bit pointless for ReactPlayer to just render an iframe and ignore all other props that normally play/pause/seek and provide callbacks. You might as well just render the `<iframe>` yourself.

On the other hand, it would open the window to support many more sites/URLs (albeit without controls) to remove the guesswork for developers trying to render video. We would need to add something to the readme to list what sites are "fully supported" and which are just iframes.
