### ISSUE TITLE
ReactPlayer autoplay muted video on mobile

### ISSUE THREAD

**Issue by Thargarius** [CookPete/react-player#203]
I can't manage to autoplay video on mobile browser, I dont have any audio and there is my code :
```
<div className="react-video" ref={el => this.videoWrapper = el}>
    <ReactPlayer width={this.state.width} height={this.state.height}
        url='https://atmost.fr/assets/video/yosemite720.webm' fileConfig={{ attributes: { "muted": "true", "autoPlay": "true" } }} muted playinline playing={this.state.playing} loop autoplay />
</div>
```

But when I inspect my page I only see this :
`<video src="https://atmost.fr/assets/video/yosemite720.webm" preload="auto" loop autoplay style="width: 100%; height: 100%; display: block;"></video>`

What is the problem ?

**Comment by besarthoxhaj** [comment]
have the same issue, apparently ios policy (and implementation) does not allow you to autoplay.

**Comment by CookPete** [comment]
This problem is [addressed in the readme](https://github.com/CookPete/react-player#mobile-considerations). We are at the mercy of how mobile browsers behave, and they tend to deliberately prevent autoplay to stop users from unnecessarily using mobile data.

I am open to any straightforward, reliable, cross-browser solutions but this will be an ongoing battle with mobile browsers in general.

**Comment by PiotrSzlagura** [comment]
@CookPete I guess this issue os about the fact, that in `attributes` there is: `"muted": "true"` but it doesn't show in the video tag. I just ran into the same issue right now and can't find solution.

**Comment by admin-logochemist** [comment]
Please use this some function that below 
import setting :
import RetPlayer from 'react-player'
code 👍 
<RetPlayer 
                playing="playing"
                preload="true"
                autoplay="true" 
                controls="true"
                url={video}
                onReady={() => console.log('onReady Callback')}
                onStart={() => console.log('onStart Callback')}
                onPause={() => console.log('onPause Callback')}
                onEnded={() => console.log('onEnded Callback')}
                onError={() => console.log('onError Callback')}
                />
