### ISSUE TITLE
propTypes Deprecated from react

### ISSUE THREAD

**Issue by jawetzel** [CookPete/react-player#204]
In my React projects using this library I am getting an error message on lib > ReactPlayer.js Line 15 saying "Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead."

**Comment by CookPete** [comment]
Are you using the latest version of ReactPlayer? https://github.com/CookPete/react-player/commit/950713c85ef9765b3d6b42f99bfbc36df33cadbb should have solved this.

Line 15 of `lib/ReactPlayer.js` in the latest version is an unrelated line:

```
var _lodash = require('lodash.omit');
```
