### ISSUE TITLE
Chrome problem

### ISSUE THREAD

**Issue by omaressameldin** [CookPete/react-player#205]
The player was working perfectly for me but then suddenly it's not working on chrome anymore for me even though it's still working on edge, and I was wondering if someone could help with that
this is a link to my react app:
https://spotify-replica.herokuapp.com/
this is the repo link:
https://github.com/omaressameldin/spotify-replica

**Comment by CookPete** [comment]
It is very difficult to know what the problem is without more information. What URL are you trying to play? Do any errors appear in the JS console when the problem happens?

**Comment by omaressameldin** [comment]
@CookPete  no errors appeared in the console but weird enough it started working again yesterday. I think maybe it was a problem with chrome or something and is fixed now. Thanks anyways
