### ISSUE TITLE
Question: preload video from next known time

### ISSUE THREAD

**Issue by regisfrias** [CookPete/react-player#206]
Hi,

I've been searching for the answer to this for a while now, but no luck :(

On the YouTube player, is it possible to start loading from a specific portion of the video while this or another video is playing? The idea is to get rid of the loading gif. In this context, I know the next play time beforehand.

Thanks,

Régis

**Comment by CookPete** [comment]
The only way to do this seamlessly would be to load two instances of `ReactPlayer`, with one hidden player that is preloaded with another video at the right time. Then hide the first and show the second.

Any attempt to do this in one player will result in a delay (as you have seen) whilst the second video loads, which could be very short or very long depending on your connection.

**Comment by regisfrias** [comment]
Thanks a lot for the answer!
