### ISSUE TITLE
Facebook Loaded progress not working

### ISSUE THREAD

**Issue by dsslimshaddy** [CookPete/react-player#207]
In the demo the Loaded progress is not moving. stays at 0.

loaded	0.000
duration	0:00
elapsed	0:00
remaining	0:00

**Comment by CookPete** [comment]
There is no way to get the loaded progress from the [Facebook Player API](https://developers.facebook.com/docs/plugins/embedded-video-player/api#control-reference), so this will never work until the API provides `loaded` information. At the moment they only provide `getCurrentPosition` and `getDuration`.
