### ISSUE TITLE
Width and Height properties affecting layout

### ISSUE THREAD

**Issue by MaxwellGover** [CookPete/react-player#208]
I guess this component has a height and width on it? I've been trying to override the height and width w/ my own css but it's not working. What's the best way to go about getting rid of this? 

<img width="1355" alt="screen shot 2017-06-21 at 3 24 47 pm" src="https://user-images.githubusercontent.com/11525891/27402844-21c806e4-5696-11e7-9a65-14e451edc475.png">

**Comment by CookPete** [comment]
Just pass in a `width` and `height` prop to ReactPlayer:

```js
<ReactPlayer url={...} width='0px' height='0px' />
```
