### ISSUE TITLE
How do I pause a video for specified amount of time/ How do I start it after a particular time

### ISSUE THREAD

**Issue by sauravmawandia** [CookPete/react-player#210]
How do I pause a video for specified amount of time/ How do I start it after a particular time.

Is there any thing I can do with the controls.

**Comment by CookPete** [comment]
>How do I pause a video for specified amount of time/ How do I start it after a particular time.

The control of the player is down to you. Pausing/playing videos is down to whether the `playing` prop you pass in is true or false. If you want to pause for a certain amount of time, just set `playing` to false for a certain amount of time.

See [jsFiddle example](https://jsfiddle.net/99ee3atp/5/)

>Is there any thing I can do with the controls.

To enable controls, just pass in prop `controls={true}` to ReactPlayer and the controls will be shown for whatever player is loaded.
