### ISSUE TITLE
Support for end parameter

### ISSUE THREAD

**Issue by danny-toi** [CookPete/react-player#217]
The YouTube Embedded Player supports a `end` parameter, which specifies the time when the player should stop playing the video.

Now the library supports a `start` parameter and I wonder if it was intentional to drop the support for `end` parameter.

**Comment by CookPete** [comment]
The library supports whatever the Youtube iframe API supports. The library did not drop support for `end`, it just does not work correctly with the API.

It does seem to work when using `playerVars`, which can be injected via `youtubeConfig`:

```jsx
// Play video from 00:20 to 00:40
<ReactPlayer
  playing
  controls
  url='https://www.youtube.com/watch?v=Mh5LY4Mz15o'
  youtubeConfig={{ playerVars: { start: 20, end: 40 }}}
/>
```

From https://github.com/CookPete/react-player/issues/152#issuecomment-279852310
