### ISSUE TITLE
How to disable pausing on the player?

### ISSUE THREAD

**Issue by kitce** [CookPete/react-player#218]
I want to disable the pause function on the player. (also seeking function, if possible)

Before using this library, I listen to YouTube player's `onStateChange` event, if the video is paused, I invoke `playVideo()` immediately to achieve this behaviour.

But now I cannot do this because I have no access to the original `event` object or any wrapped `player` instance in those callbacks.

**Comment by kitce** [comment]
Finally, I managed to do this in a strange way : Setting `state.playing` to `false` and `true`.

Note : `dispatch` is a method from `react-redux` to manage state
```
function onEnded () {
  dispatch(setPlaying(false));
  dispatch(setPlaying(true));
}
```

Although it works, I think this is very stupid.

**Comment by CookPete** [comment]
The easiest way to do this is to simply do not show `controls` and set `pointer-events: none;` on the player:

```jsx
<ReactPlayer
  url='https://www.youtube.com/watch?v=Y_hc07rAQlc'
  playing
  style={{ pointerEvents: 'none' }}
/>
```

Example [jsFiddle](https://jsfiddle.net/99ee3atp/6/).
