### ISSUE TITLE
In the mobile broadcast HLS

### ISSUE THREAD

**Issue by XindaSayHi** [CookPete/react-player#219]
On the PC and the mobile end play mp4 files such as the effect is very good, in HLS, PC play is normal, but the mobile end can't play, what is the reason, what should I do?thank you

**Comment by oktayla** [comment]
same issue

**Comment by oktayla** [comment]
@XindaSayHi Did you solve the problem?

**Comment by CookPete** [comment]
[hls.js](https://github.com/video-dev/hls.js) is used to play HLS files inside ReactPlayer. If there is an issue with playing HLS streams specifically on mobile, open an issue in that repo, or see the [various existing issues around mobile streaming](https://github.com/video-dev/hls.js/search?q=mobile&type=Issues&utf8=%E2%9C%93) with hls.js.
