### ISSUE TITLE
Will this component support onSeek callback?

### ISSUE THREAD

**Issue by kitce** [CookPete/react-player#222]
It will be great to use the original player controls and listen to the `onSeek` event.

**Comment by CookPete** [comment]
If you are playing files, you could use the HTML5 `onseeked` attribute like so:
```jsx
<ReactPlayer 
  playing
  controls
  url='http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4' 
  fileConfig={{ attributes: {
    onSeeked: e => console.log(e.target.currentTime)
  }}}
/>
```

It looks like Vimeo and Wistia players also support seek event listeners, so a universal `onSeek` prop might make sense, although Facebook and Youtube players don't seem to support it.
