### ISSUE TITLE
Vimeo not playing

### ISSUE THREAD

**Issue by mheilemann** [CookPete/react-player#223]
With the following sample code, Vimeo does not play:

```js
import ReactPlayer from 'react-player';

definejs('Video', function create () {
   return {
       createComponent: function (React, Component) {
           return class Video extends Component {
               render () {
                   return <ReactPlayer url='https://vimeo.com/220391589'/>;
               }
           }
       }
   }
});
```

**Comment by CookPete** [comment]
The `playing` prop must be set for videos to play:
```jsx
return <ReactPlayer url='https://vimeo.com/220391589' playing />;
```

**Comment by mheilemann** [comment]
I have tried it with playing and without.

It crashes with the latest version of the library.  It does however work properly with version react-player@0.14.3

**Comment by CookPete** [comment]
Can you provide more information about the problem? Things like:

* Any JS console errors
* React version
* ReactPlayer version
* Browser version
* Operating system
* A jsFiddle to reproduce the issue ([here's one to get you started](https://jsfiddle.net/8o97yzas/))

**Comment by bdevika** [comment]
Im getting this issue
player.js:2 GET https://vimeo.com/api/oembed.json?url=https%3A%2F%2Fvimeo.com%2F90509568&url=https%3A%2F%2Fvimeo.com%2F90509568&autoplay=false&muted=false&loop=false&playsinline=false&controls=false&autopause=false&byline=false&portrait=false&title=false 403 (Forbidden)
