### ISSUE TITLE
Seamless Looping

### ISSUE THREAD

**Issue by edencorbin** [CookPete/react-player#224]
The plugin works great. I'm trying to find a good solution for seamlessly looping video. For local files specifically, does this plugin provide any benefit over a standard html5 video (in chrome) in terms of seamlessly looping video with otherwise standard settings?

**Comment by CookPete** [comment]
ReactPlayer does nothing special when it comes to looping HTML5 video. The `loop` prop is simply set on the `<video>` element that it renders.

You could listen for the `onEnded` callback and run `seekTo(0)` for a more verbose loop, but I'm not sure this would perform any better.

**Comment by edencorbin** [comment]
Thanks for the follow up, good to know.
