### ISSUE TITLE
Access YT Player.mute() to make autoplay on IOS

### ISSUE THREAD

**Issue by blobinabottle** [CookPete/react-player#225]
Is there a way to access the Youtube player ref and then access the mute method? 
Because this way it's autoplayable on IOS.

Look at an non-react-player example here:
http://jsfiddle.net/BFDKS/1228/

Thanks

**Comment by CookPete** [comment]
It is a bit convoluted, but it is possible:

```jsx
<ReactPlayer
  ref={rp => this.rp = rp}
  url='https://www.youtube.com/watch?v=Y_hc07rAQlc'
  playing
  onReady={() => this.rp.player.player.mute()}
/>
```
https://jsfiddle.net/99ee3atp/9/

**Comment by blobinabottle** [comment]
awesome. Thanks!
