### ISSUE TITLE
soundclound.js file updates are not reflecting in folder

### ISSUE THREAD

**Issue by jayesh10** [CookPete/react-player#226]
Hi ,
I m not able to see the file update of widget api in file.

**Comment by CookPete** [comment]
I'm not sure exactly what the problem is here, but keep in mind that you need to run 
```
npm run build:compile
```
To compile the source files from `src` into the `lib` folder to be used/imported by other projects.

You also may want to run
```
npm run build:browser
```
To compile the library and update the files in `dist`.
