### ISSUE TITLE
Checking whether a url 'resolves' before setting it as a prop

### ISSUE THREAD

**Issue by titusf** [CookPete/react-player#227]
As far as I can tell, the only way to check for whether a url is going to be successfully loaded when passed to the ReactPlayer is to listen for the onError callback _after_ the erroneous url prop has already been set. 

I think it would be useful to be able to check against whichever functions are validating those urls and causing the onError callback to fire before having to set the url prop. This would prevent needing to switch the player to a broken state for urls that don't resolve correctly.

**Comment by CookPete** [comment]
As of `0.24`, the `ReactPlayer.canPlay` static method is [back](https://github.com/CookPete/react-player#static-methods), which can be used to check if a URL matches any of the regex patterns of the various players.

In most cases, it's impossible to know whether a URL is going to error without loading the player first, which requires the URL to be passed in and the SDK to be loaded either way. Nothing that we control is causing `onError` callbacks for problematic URLs; the errors come from the different player APIs and ReactPlayer just passes them through to the `onError` callback.

You could just hide the appropriate UI or show a loading spinner until the `onReady` prop is called? `onReady` is a fairly good indication that the URL is good.
