### ISSUE TITLE
Is it possible to set custom thumbnail to video for youtube url? 

### ISSUE THREAD

**Issue by jasan-s** [CookPete/react-player#228]
I wanted to use a different image than the the one uploaded to youtube as thumbnail. is it possible?

**Comment by CookPete** [comment]
There is nothing in the [API docs](https://developers.google.com/youtube/iframe_api_reference) that mentions changing the thumbnail to use. I would suggest overlaying an `<img>` that plays the video on click, then listen for player `onPlay` and hide the image.
