### ISSUE TITLE
Volume only gets set after players are loaded

### ISSUE THREAD

**Issue by Fauntleroy** [CookPete/react-player#23]
If you set the volume of `ReactPlayer` when you instantiate it, (at least) the YouTube and SoundCloud players will not respect it (and seem to use `0.8`). I imagine this is because `setVolume` calls are currently stopped instead of queued when the player isn't ready yet.

**Comment by Fauntleroy** [comment]
To replicate:

- Set `volume` to "0" in the `state` block of  `App.js`
- Go to http://localhost:3000/
- Play a YouTube video
- The YouTube video will be audible
- Change the volume using the volume slider
- The YouTube video's volume will change as expected

**Comment by Fauntleroy** [comment]
With this is looks like we have a number of method calls which may need to be queued before execution. Maybe we should add a `queue` method which stores these calls until `onReady`, then executes them all in order?

**Comment by CookPete** [comment]
Hopefully this is sorted in `0.3.5`.

Inside `onReady`, `isReady = true` was happening _after_ `setVolume()`, which bails if `isReady === false`.

**Comment by Fauntleroy** [comment]
There are still some volume issues appearing (though less consistently than before). I'll try and get a more cohesive test case together later, but a brief look this morning suggests that the volume isn't properly respected when new YouTube videos are loaded into an existing player.

**Comment by CookPete** [comment]
>volume isn't properly respected when new YouTube videos are loaded into an existing player.

Hm. I wonder if we should just set volume every time `onPlay` fires..

**Comment by CookPete** [comment]
Ah I believe the behaviour you are seeing is because [`volume` is not sent through if the player is not active](https://github.com/CookPete/react-player/blob/master/src/ReactPlayer.js#L59-L61). Perhaps `volume` should be sent to all players, active or not, and they can adjust accordingly in the background.

**Comment by CookPete** [comment]
I've had a further look at this. The YouTube player happens to be the only player that _doesn't_ call `onReady` when loading subsequent videos, so hopefully 5895663 sorts this. Published in `0.3.6`.
