### ISSUE TITLE
Support for `controlsList` attribute missing

### ISSUE THREAD

**Issue by jaqua** [CookPete/react-player#232]
As I would like to prevent showing the download icon in the player, I need to add `controlsList='nodownload'` attribute to `<video>` element. As far as I can see, there is no support for this right now...

**Comment by CookPete** [comment]
You can use the `config` prop to add additional attributes to the file player:

```jsx
<ReactPlayer
  url='http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4'
  controls
  config={{ file: { attributes: { controlsList: 'nodownload' }}}}
/>
```
However, `controlsList` is currently stripped by React and so this will only work when https://github.com/facebook/react/issues/9594 lands, which apparently will be in `15.6.2`. Until then this will not work, and there is a console warning:

> Warning: Unknown prop `controlsList` on `<video>` tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop

**Comment by jdolle** [comment]
This issue still exists after 15.6.2

**Comment by jdolle** [comment]
Nevermind, yarn upgrade did not actually upgrade...

**Comment by JenniferFuBook** [comment]
Thanks, @CookPete!
