### ISSUE TITLE
this.player is undefined

### ISSUE THREAD

**Issue by jaqua** [CookPete/react-player#233]
I'm trying to call some methods, but `this.player` is `undefined`.

This is how my component looks like:

    import ReactPlayer from 'react-player'

    class VideoPlayer extends Component {

      constructor () {
        super()
        this.state = {
          duration: 0,
          played: 0
        }
      }

      render () {
        const { src } = this.props

        console.log(this.player.getDuration())

        return (
          <div>
            <ReactPlayer
              url={src}
              controls
              playing
            />
            <SomeOtherComponents />
          </div>
        )
      }
    }

I'm calling it like this: `<VideoPlayer src='http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4' />`

**Comment by CookPete** [comment]
Video duration is not available before or immediately after rendering `ReactPlayer`. It takes some time for the browser to load video information.

The `onDuration` callback prop returns the duration of the media in seconds as soon as it's available:

```js
import ReactPlayer from 'react-player'

class VideoPlayer extends Component {
  render () {
    const { src } = this.props

    return (
      <div>
        <ReactPlayer
          url={src}
          controls
          playing
          onDuration={seconds => console.log(seconds)}
        />
        <SomeOtherComponents />
      </div>
    )
  }
}
```

If you still need a reference to the player instance (ie `this.player`), you need to use [`ref`](https://facebook.github.io/react/docs/refs-and-the-dom.html) like in the [demo app](https://github.com/CookPete/react-player/blob/f6b7a0ac55b2203c978013e4a929b947073d67b2/src/demo/App.js#L121).

**Comment by jaqua** [comment]
Still facing the same problem. I've added `ref`, but `this.player` is still undefined:

    import ReactPlayer from 'react-player'

    class VideoPlayer extends Component {

      constructor () {
        super()
        this.state = {
          duration: 0,
          played: 0
        }
      }

      ref (player) {
        console.log(player) // <-- undefined
        this.player = player
      }

      onSeekMouseUp (event) {
        this.setState({ seeking: false })
        console.log(this.player) // <-- undefined
        this.player.seekTo(parseFloat(event.target.value))
      }

      render () {
        const { src } = this.props

        return (
          <div>
            <ReactPlayer
              ref={this.ref}
              url={src}
              controls
              playing
            />
            <SomeOtherComponents />
          </div>
        )
      }
    }

**Comment by CookPete** [comment]
Something else must be going on here. What URL are you trying to play? I have copied your code into a [jsFiddle](https://jsfiddle.net/99ee3atp/21/) and it logs the player instance correctly, although `this.player = player` does not work because the `ref` function is not bound, and so `this` is `undefined`.

**Comment by jaqua** [comment]
Could you please show me how I should do that? "...because the ref function is not bound".

I'm using `gridfs-stream` and `Meteor-Files` in my meteor application. And with that I got this problem, but I really don't see the issue...
