### ISSUE TITLE
Excellent Script! How could I install it on a AWS Fedora Server?

### ISSUE THREAD

**Issue by inglesuniversal** [CookPete/react-player#236]
I am running a server with Amazon and wish if I could install this player on my server.

I am barely new to react, so I don't have a clue on how to install or run react on my server and also your script which would be a great benefit for our students. Would you kindly give me a head start on the steps to follow?

Thanks, and we also would be glad to contribute more features.

**Comment by CookPete** [comment]
ReactPlayer isn't really something that runs on a server. It is a client-side library for React that runs in the browser. To use it you just need to load the library into a browser and render it using React.

I would suggest brushing up on React in general first: 

* https://facebook.github.io/react/docs/hello-world.html
* https://www.codecademy.com/learn/react-101

And then:

* Read the [readme](https://github.com/CookPete/react-player/blob/master/README.md)
* Check out a really basic example in [this jsFiddle](https://jsfiddle.net/99ee3atp/22/)
* Check out the [source code](https://github.com/CookPete/react-player/tree/master/src/demo/App.js) of the [demo app](cookpete.com/react-player)
