### ISSUE TITLE
Switch to Streamable iFrame player

### ISSUE THREAD

**Issue by lawlmart** [CookPete/react-player#237]
We’ve removed the files attribute from our API. In the future all videos must be played using our iframe player (similar to YouTube). The embed code is now returned by the API.

**Comment by CookPete** [comment]
@lawlmart This is quite a shame.. Is there a way to programmatically control the iframe player and receive events? Otherwise there is not much point for ReactPlayer to support Streamable videos.

**Comment by lawlmart** [comment]
Yes, we support player.js.

https://github.com/embedly/player.js/

**Comment by CookPete** [comment]
Thanks @lawlmart. I've just hooked it up but annoyingly there is a bug in `player.js` when calling `play()` after the `ready` event where the thumbnail overlay remains on top of the playing video. It requires a user click to remove the overlay.

See [example fiddle](https://jsfiddle.net/zoxtog56/) using pretty much the exact example code from the [player.js readme](https://github.com/embedly/player.js/#playerjs).

**Comment by lawlmart** [comment]
Thanks for catching that, I’ll get that fixed ASAP.

**Comment by lawlmart** [comment]
Fiddle looks good now.

**Comment by CookPete** [comment]
Nice work on the fix @lawlmart. Next issue is that the player seems to fail karma tests when run in Travis (see [failing build](https://travis-ci.org/CookPete/react-player/builds/276018886)). I've had to skip the tests for the time being. The tests seem fine when run locally. That are pretty straightforward tests that pass on certain events/callbacks (see [example test](https://github.com/CookPete/react-player/blob/master/test/specs/ReactPlayer.js#L97-L120)). Any ideas why this would happen?

**Comment by lawlmart** [comment]
What browser are you testing in?

**Comment by CookPete** [comment]
CI tests currently run in `Chromium 60.0.3112` on Ubuntu.

**Comment by lawlmart** [comment]
I'd figure one of the events isn't being called judging by the timeout, but it's hard to tell which. The player is passing the playerjs tester so I'm not sure what the issue is on our end. Which URL are you testing it with?
