### ISSUE TITLE
SoundCloud player does not work in Safari

### ISSUE THREAD

**Issue by Fauntleroy** [CookPete/react-player#24]
These two errors appear when attempting to play a SoundCloud track in Safari:

<img width="790" alt="screen shot 2016-01-03 at 12 14 02 pm" src="https://cloud.githubusercontent.com/assets/507047/12080561/8a9eabec-b213-11e5-9562-a7b3b6c29d86.png">

**Comment by Fauntleroy** [comment]
https://github.com/soundcloud/soundcloud-javascript/issues/27

**Comment by rbarman** [comment]
+1. Is anything being done to fix this or will this component not entirely work in Safari?

**Comment by CookPete** [comment]
A possible fix would be to host a modified version of the SDK somewhere, which replaces any use of `api.soundcloud.com` with a purpose-built proxy, to circumvent the incorrect header errors.

That said, this would be an extravagant fix for something that seems incredibly easy to fix on Soundcloud’s backend.

**Comment by heybenji** [comment]
Is this an http/https issue?

**Comment by CookPete** [comment]
> Is this an http/https issue?

@heybenji Not as far as I know. I get the same error from a `https` page too.

**Comment by denisflorkin** [comment]
Hello, I was a bit annoyed by the sdk not working on safari, so I tried using soundcloud-audio instead and it seems to work properly. I'd really appreciate some feedback, and if you feel there's value, I'd be happy to prep a clean PR.
Heres' the code : https://github.com/denisflorkin/react-player

And here's just the "player/soundcloud.js" revisited "with soundcloud-audio" : https://github.com/denisflorkin/react-player/blob/master/src/players/SoundCloudAudio.js

soundcloud-audio => https://github.com/voronianski/soundcloud-audio.js

**Comment by CookPete** [comment]
Nice work @denisflorkin. It looks like the only reason `soundcloud-audio` works is that it uses JSONP (which the SC endpoint happens to support) so a much simpler fix could be just to use JSONP to make requests instead. Should be a quick fix that I'll do today.

In fact, I realise now that `soundcloud-audio` literally just grabs the `stream_url` from the `resolve.json` endpoint and then just sets the source of an `audio` element. Perhaps it would be sufficient for `ReactPlayer` to also do this rather than have to load the full SC SDK, especially considering it already supports files via `FilePlayer`.

**Comment by denisflorkin** [comment]
Thanks @CookPete. To make sure I'm following, are you saying you'd get rid of the `SoundCloud` entirely and repatriate its logic into the `FilePlayer` ? Or something (slighly) different ?

**Comment by CookPete** [comment]
Pretty much. `SoundCloud` could just extend `FilePlayer` and change the `play` function to make the resolve call, then set the player `src` to the track's `stream_url`. This would remove a lot of code and give us all the control we get when playing files (like native controls).

**Comment by denisflorkin** [comment]
I looked at it but I'm not really getting anywhere close something good, I leave it there for now as I think I need to get back in the react doc. Thanks for all the work on react-player :)

**Comment by CookPete** [comment]
>I looked at it but I'm not really getting anywhere close something good

No problem, I'm happy to look at this. I'll open a new issue.
