### ISSUE TITLE
hi-res music

### ISSUE THREAD

**Issue by neo125874** [CookPete/react-player#242]
Hi, is the library support flac, ape, etc?
Would this player just deliver digital signal to the Headphone, 
or it will Decrease the bit/khz inside the player then to the end device?

thanks for answering.

**Comment by CookPete** [comment]
ReactPlayer just renders an `<audio>` element when passed an audio file. FLAC should work as long as the [browser supports it](caniuse.com/#search=flac), although it will render as `<video>` unless it's added to the [audio file extensions constant](https://github.com/CookPete/react-player/blob/v0.25.0/src/players/FilePlayer.js#L6). It should still work though. You can always test custom URLs on the [demo page](http://cookpete.com/react-player/).

As for whether the bitrate decreases, I have no idea. I guess it depends on the browser you're using and how it handles lossless audio.

**Comment by neo125874** [comment]
thank you, 
as you mentioned constant, if i want to play flac or some other types, 
i have to add them to the audio extensions myself, right?
