### ISSUE TITLE
Edge Browser, Fileplayer - unhandled error

### ISSUE THREAD

**Issue by reergymerej** [CookPete/react-player#244]
react-player@0.25.0

Using Fileplayer on Edge 14/15, there's an unhandled error that prevents changing the playing state.

```
Unable to get property 'catch' of null reference
Fileplayer.js (171, 1)
```

Once this error is thrown, the player blows up and either won't render again or just stops responding to new props.  Here is a create-react-app repo with a super-simple example.

https://github.com/reergymerej/react-player-bug-repro/blob/master/src/App.js

I don't think this is a usage issue as it works in other browsers.

Please let me know if you need any more detail.

**Comment by reergymerej** [comment]
FWIW, it looks like `<video />` elements return a Promise from `.play()` in [good browsers] and `undefined` in [Edge].

[good browsers]: https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/play
[Edge]: https://msdn.microsoft.com/en-us/library/ff975194(v=vs.85).aspx

**Comment by reergymerej** [comment]
Here's a way to monkey-patch from the library's consumer while you're waiting for a fix.

https://github.com/reergymerej/react-player-bug-repro/blob/monkey-patch/src/App.js#L17

It just tells the `<video />` element to return a Promise if it doesn't already.

**Comment by reergymerej** [comment]
Just saw ff422195b5447340d6fe55dcfab050552c85af67. 🤐

**Comment by reergymerej** [comment]
Was there a problem with the last build to npm?  I've cleared my cache, tried Yarn and npm, various versions of Node and npm, several VM and I still get this problem.  Any advice?

**Comment by CookPete** [comment]
Should be sorted in `0.25.1` 👍
