### ISSUE TITLE
className props was removed

### ISSUE THREAD

**Issue by polco** [CookPete/react-player#247]
I saw in the last update that 'className' was removed from the props in the typescript types. That property was very important since it allows to access and manipulate the style of the `ReactPlayer` component. Is there a preferred way to deal with this ? i would rather not create another div (since the component already creates 2 of those) around it just to style it.

**Comment by CookPete** [comment]
As of, d8df671478105165ca396716a4c8328bc78a70c1, any props not specified in [`props.js`](https://github.com/CookPete/react-player/blob/master/src/props.js) get applied to the ReactPlayer wrapper div. So `className` still works as before, but just isn't specified as it just gets passed through with any other extra props.

I guess I need to update the typings file to include an indexer, to allow for any other props? Correct me if I'm wrong – I am not too clued up on TypeScript typings:

```ts
export interface ReactPlayerProps {
  url?: string | string[] | SourceProps[];
  playing?: boolean;
  loop?: boolean;
  // ...
  [otherProps: string]: any;
}
```

**Comment by polco** [comment]
I tried adding the actual attributes types from the react types package, but a few properties of the ReactPlayer props (onProgress, onError, ...) conflicts with the DOMAttributes interface which has different definitions for those. So I guess you general indexer is our only solution for now :/
