### ISSUE TITLE
Requires two clicks to play on iOS

### ISSUE THREAD

**Issue by sarutole** [CookPete/react-player#249]
Please advice what is the right way to unlock <audio> element on user gesture as required by iOS. I have the following in my code (shortened for brevity), works without a hitch on Android/Windows/MacOS, but on iOS requires two clicks.

```
    componentDidMount() {
        document.addEventListener('click', this.onPageClick);
    }

    componentWillUnmount() {
        document.removeEventListener('click', this.onPageClick);
    }

    onPageClick(e){
        const $el = $(e.target).closest('a[data-playable]');
        const url = $el.attr('href')
        
        if( $el.length ){ //check if a "playable" link was clicked
            e.preventDefault();
            this.play(url);
            return false;
        }
    }

    play(url) {
       const newState = {
            url,
            played: 0,
            loaded: 0,
            playing: true
        };
        this.setState(newState);
    }

```

**Comment by sarutole** [comment]
Adding `autoplay="true"` to `<audio>` element for iOS devices fixes the "two-clicks" issue. (By the way, currently the react-player demo also has this problem.)
```
            fileConfig: {
                attributes: { autoPlay: /iPad|iPhone|iPod/.test(navigator.userAgent) && !window.MSStream }
            },
```

**Comment by kpennell** [comment]
@sarutole Did you just put autoPlay={true} or use a the config prop or something else entirely?

**Comment by sarutole** [comment]
@kpennell just adding that line to `fileConfig` fixed the issue for me. 
But that was a while ago, I have not tested it with any recent version of react-player.

**Comment by kpennell** [comment]
Thanks, that was really helpful.

**Comment by GIGLproject** [comment]
I also face the same issue and it's work for me by setting the volume =0 for iphone as in iphone volume can't be control via js

**Comment by sangroya** [comment]
I also face the same issue and it's work for me by setting the volume =0 for iphone as in iphone volume can't be control via js

**Comment by ambojialur** [comment]
> Adding `autoplay="true"` to `<audio>` element for iOS devices fixes the "two-clicks" issue. (By the way, currently the react-player demo also has this problem.)
> 
> ```
> fileConfig: {
>      attributes: { autoPlay: /iPad|iPhone|iPod/.test(navigator.userAgent) && !window.MSStream }
> },
> ```

Where can I add it
