### ISSUE TITLE
Config prop dont work as expected

### ISSUE THREAD

**Issue by lehnavid** [CookPete/react-player#256]
I'm testing the config prop for a vimeo vid.

config:
```
const config = {
    vimeo: {
      playerOptions: {
        title: false,
        portrait: false,
        byline: false,
        color: "#c63843",
        height: "100px",
        width: "100px"
      }
    }
  };
```

I have 2 react players to see the difference:
```
return (
    <div>
      <ReactPlayer
        url="https://vimeo.com/90509568"
      />
      <ReactPlayer
        url="https://vimeo.com/14628833"
        config={ config }
      />
    </div>
  );
```

I expected to see any impact from the config. But both players are looking 100% identical.

Do i use it wrong?

**Comment by bstst** [comment]
From the "props" description in the homepage:

> Note: Vimeo, Twitch and Wistia player controls are not configurable and will always display [controls]

**Comment by CookPete** [comment]
There is quite a lot going on here so I'll try to clear it up as best I can (based on some very quick tests):

The `color` option doesn't seem to work with a `#` prefix. The [example in the docs](https://github.com/vimeo/player.js#embed-options) does not have a `#` (although this is a bit weird considering the [`setColor`](https://github.com/vimeo/player.js#setcolorcolor-string-promisestring-contrasterrortypeerrorerror) method requires a `#`). The bottom player will not change color, even with the same config.

Further to this, some players seem to have a hard coded color (maybe set by the video owner?) that `color` will not override. See [this in action](https://jsfiddle.net/nwbqh9L9/) using your example config.

There are some [default player options](https://github.com/CookPete/react-player/blob/master/src/props.js#L108-L114) set in `props.js`, so some of your config (eg setting `portrait` and `byline` to false) will be doing nothing.

Width and height are set using the top level props, eg:

```jsx
<ReactPlayer url={url} width={100} height={100} />
```

Any `width` or `height` set in `playerOptions` will be overridden, as all internal frames are set to `100%` width and height, to fill the container.

**Comment by lehnavid** [comment]
@CookPete @bstst Thanks guys, you helped me out!
