### ISSUE TITLE
Ajax request URL

### ISSUE THREAD

**Issue by DangerZoneIO** [CookPete/react-player#258]
Hey,
I am pulling the URL to the React Player from the server using ajax and untill then displaying a "placeholder" for the url.
if there isn't a url in the server database, react should keep the placeholder, if there is a url, pass it to React Player as url.

Code:
```
import React from "react";
import { observer } from "mobx-react";
import ReactPlayer from 'react-player'

import ProfileStore from "./ProfileStore";

@observer
export default class Video extends React.Component{
    render(){
        if(ProfileStore.player.video != ""){
            return(
                <div class="video">
                    <ReactPlayer url={ProfileStore.player.video} playing={false} width={100+"%"} height={100+"%"} style={{position: "absolute"}} />
                </div>
            );
        }
        else
            return(
                <div class="videoUpload">
                    <div class="upload">
                        <img src="https://storage.googleapis.com/placeholder.png"/>
                        placeholder
                        <br/>
                        placeholder
                    </div>      
                </div>  
            );
    }
}
```

When I do that, I am facing an issue that the React Player already got into his "<video>" state, and twitch/other platforms videos can't be displayed.

I have tried to "this.forceUpdate()" the component when a url is passed, but I am getting this error:
"Uncaught Error: Minified React error #185; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings."

I am out of ideas on how to fix this.

**Comment by CookPete** [comment]
I'm struggling to understand what exactly is going wrong here. I've put together a [jsFiddle](https://jsfiddle.net/7rftme2e/) of your example code (although the `ProfileStore` is replaced with basic component state). The button updates the fake store and the ReactPlayer appears. 

What are you expecting to happen and what is actually happening?

**Comment by DangerZoneIO** [comment]
I think the issue is that after the url update, the  ReactPlayer already rendered a <video> tag.
and when I am putting in a twitch stream for example, the ReactPlayer just straps the url in the video tag, insted of rerendering it as an iframe.

thats pretty much it.

**Comment by CookPete** [comment]
What exact twitch URL are you trying? It sounds like it isn't matching the [Twitch video URL patterns](https://github.com/CookPete/react-player/blob/master/src/players/Twitch.js#L8-L9) and is falling back to `FilePlayer`.

**Comment by DangerZoneIO** [comment]
ahh I had the channel name as caps, thats why it didn't work
