### ISSUE TITLE
Vimeo fails, freezes entire application

### ISSUE THREAD

**Issue by Redmega** [CookPete/react-player#259]
Every so often Vimeo will fail to render/fetch a video, resulting in the following error:

> You must pass either a valid element or a valid id.

This error causes the rest of our application to break, as react routing no longer works and other functionality freezes.

We've boiled it down to the id differing between the iframe and the vimeo player.js internally. The hash which it creates to fetch the blob does not match with the video id provided.

This error is incredibly sporadic, and we've only been able to replicate a handful of times, but never with a resolution. I'm opening an issue with vimeo player.js shortly but I thought to ask here first to see if anyone else has experience with this error and how to solve it.

**Comment by CookPete** [comment]
Hey @Redmega, are you using `ReactPlayer` inside a frame? Looks like a similar problem to https://github.com/CookPete/react-player/issues/150#issuecomment-297780947 and https://github.com/vimeo/player.js/issues/16.

**Comment by Redmega** [comment]
@CookPete Nope, we're rendering the `<ReactPlayer>` directly in the app. I believe Vimeo's `player.js` is creating an `<iframe>` for its own player, but it works _most_ of the time, so I don't think it's an iframe related thing.

It also works _most_ of the time for the same id which will fail _sometimes_. It's not an issue with a specific video, either.

Like I said, very hard to replicate. Once I get it to happen again I'll post details of the video and the DOM.

**Comment by CookPete** [comment]
The error being logged is [here](https://github.com/vimeo/player.js/blob/d953eadc5a82ce46ff48b984e1688210c40f08bd/src/player.js#L40) in the Vimeo player source, which implies that the first argument passed to `new Vimeo.Player()` is not a dom element (or an ID of an element). The only place that happens in ReactPlayer is here:

https://github.com/CookPete/react-player/blob/d5ba064a42f3b0abfa4c0d78324305ef20120f54/src/players/Vimeo.js#L40

So `this.container` is not an element. Could it be that the component is unmounted before the SDK finishes loading, and `ref` is being called with `null` which sets `this.container = null`?

Maybe it's as simple as just bailing before `new Vimeo.Player()` runs if the component has unmounted.

**Comment by Redmega** [comment]
I am seeing on server-side render we get the following error

`ReactPlayer: Vimeo player could not call unload – The player was not ready`

However the video still plays properly in most cases. I haven't been able to replicate the `id` issue as of yet.

Could be that during SSR it's failing to mount, or something like that?

**Comment by Redmega** [comment]
My coworker was able to replicate, strangest thing is that the video itself is still playable and works fine. It's just the rest of our app that breaks.

**Comment by CookPete** [comment]
>I am seeing on server-side render we get the following error
>
>`ReactPlayer: Vimeo player could not call unload – The player was not ready`

This is just a warning that can happen when the component unmounts (and calls `stop()`) before the player is ready. The same thing that can cause the `You must pass either a valid element or a valid id` error. Pretty sure the two errors are based on the same problem.

**Comment by CookPete** [comment]
FYI, I've just published `v1.0.0-beta.0` under the tag `next` (it was time). It might be worth upgrading and seeing if that makes any difference:

```bash
npm install react-player@next
```

It's a pretty big refactor so would be great to test it in the wild before release.

**Comment by CookPete** [comment]
I think 979e639 should fix this. Part of `1.0.0-beta.1`

**Comment by Redmega** [comment]
Ok thanks we'll give it a try.

**Comment by Redmega** [comment]
@CookPete Just wanted to give you an update, it seems after releasing `1.0.0-beta.3` to the wild earlier today, we've seen a drastic reduction in those errors. Safe to say near-zero now...

![screen shot 2017-11-03 at 2 06 26 pm](https://user-images.githubusercontent.com/662951/32389391-db86b84a-c0a0-11e7-8b9e-2794503e0d51.png)

Thanks!
