### ISSUE TITLE
Unreliable karma tests in Travis

### ISSUE THREAD

**Issue by CookPete** [CookPete/react-player#26]
It seems like the browser inside the Travis CI machines isn't quite good enough to safely test in Travis. See an [example build log](https://travis-ci.org/CookPete/react-player/jobs/101529441) where one test fails, which I can't reproduce locally. Perhaps in Travis we should revert to just the shallow render tests, and just run `karma` tests locally when building/releasing.

**Comment by Fauntleroy** [comment]
I've had success running my tests in multiple browsers during CI with https://saucelabs.com/. Might be worth a shot.
