### ISSUE TITLE
TypeError: Cannot read property 'addEventListener' of null in jest

### ISSUE THREAD

**Issue by konsumer** [CookPete/react-player#260]
I get this error:
```
 at FilePlayer.addListeners (node_modules/react-player/lib/players/FilePlayer.js:107:18)
      at FilePlayer.componentDidMount (node_modules/react-player/lib/players/FilePlayer.js:74:12)
      at node_modules/react-test-renderer/lib/ReactCompositeComponent.js:262:25
      at measureLifeCyclePerf (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:73:12)
      at node_modules/react-test-renderer/lib/ReactCompositeComponent.js:261:11
      at CallbackQueue.notifyAll (node_modules/react-test-renderer/lib/CallbackQueue.js:74:22)
      at ReactTestReconcileTransaction.close (node_modules/react-test-renderer/lib/ReactTestReconcileTransaction.js:34:26)
      at ReactTestReconcileTransaction.closeAll (node_modules/react-test-renderer/lib/Transaction.js:207:25)
      at ReactTestReconcileTransaction.perform (node_modules/react-test-renderer/lib/Transaction.js:154:16)
      at batchedMountComponentIntoNode (node_modules/react-test-renderer/lib/ReactTestMount.js:67:27)
      at ReactDefaultBatchingStrategyTransaction.perform (node_modules/react-test-renderer/lib/Transaction.js:141:20)
      at Object.batchedUpdates (node_modules/react-test-renderer/lib/ReactDefaultBatchingStrategy.js:60:26)
      at Object.batchedUpdates (node_modules/react-test-renderer/lib/ReactUpdates.js:95:27)
      at Object.render [as create] (node_modules/react-test-renderer/lib/ReactTestMount.js:126:18)
      at Object.test (node_modules/@storybook/addon-storyshots/dist/test-bodies.js:26:44)
      at Object.<anonymous> (node_modules/@storybook/addon-storyshots/dist/index.js:145:21)
          at Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

with code tested in jest:

```js
<ReactPlayer url='http://techslides.com/demos/sample-videos/small.mp4' />
```

I think jsdom (which is loaded by jest) doesn't have the `this.player.addEventListener` (an also no `this.player.removeEventListener`.)

Some possible solutions:

* fix jsdom/jest: Figure out what's wrong with jsdom's video (this is probly a very big undertaking mocking out all the APIs.) It might also be fixable with jsdom's `{ runScripts: "dangerously" }` to allow setting event-handlers externally
* guard: `if (this.player && this.player.addEventListener)`
* fix/guard local: add shims for those functions if they don't exist.

Do you have any other strategies for testing react-player with native video in jsdom?

**Comment by CookPete** [comment]
What is the actual error? You have only posted the stack.

ReactPlayer is highly dependent on a full browser environment to be tested in due to the amount of external script loading, refs and dom interaction required. I use Karma to test it, and I wouldn't be surprised if there are problems with other frameworks that do not mock and entire browser environment.

The higher level question is: why are you trying to test ReactPlayer with jest in your project? ReactPlayer should be mocked just to confirm that it's being rendered in your project, to avoid actually rendering it in jsdom.

**Comment by konsumer** [comment]
The error is in the title: `TypeError: Cannot read property 'addEventListener' of null`

I can make a PR for a guarded version of react-player that won't throw an error, but it's a question of whether you want the extra lines checking if their is a regular DOM behind the native video element. If I use a youtube video URL it doesn't throw because their API guards more stuff, like there not being basic DOM functions like `addEventListener`.

If you are saying you would rather not guard against basic DOM stuff (that I agree really should be there, in a real DOM) that is totally valid. I thought I would check here for interest in a PR, as it might help other people who test like this. I can work around it by mocking the data in my stories to have all youtube URLs when in testing (so visually we will see react-player with correct urls, but tests are against youtube.) This seems a bit hacky, but so is a lot of unit-testing (mocking out interfaces of things that don't need to be tested.)

I'll answer your last question, but I have a feeling it's a testing style question that can't be easily resolved without quite a bit of opinion that disagrees with your opinions on testing (I looked at how you are testing, with karma, in headless chrome.) I also looked at your other projects, and see you favor karma.

Our strategy is different. We use storybook to make "stories" that are display-only versions of the usage of our over 50 components. Each story is a snapshot in state, so we can make lots of stories for every component to test it in various situations. It allows us to visually test components and make them work well, without redux or application code. All state is passed via props (so it can be used with redux or passed from parent component.) We can develop them in isolation, and make sure they look right, before attaching them to real data or state. It also serves as nice documentation for exactly how to use state with the components. 

Storybook has a plugin called [storyshots](https://github.com/storybooks/storybook/tree/master/addons/storyshots) that will auto-generate `expect(result).toMatchSnapshot()` tests for every story.  So, we use the stories for visual testing and getting everything styled right and documenting all the props and how the components work, and also generating the tests. It has worked really well for us for every component that doesn't have any DOM dependencies (none of our other components do.) A bonus of using jest this way is that we don't have to write stories and separate unit-tests. Since we test all of our permutations of state (we have 98% coverage) in various visual stories, it's a bit redundant to also make unit-tests.  jest is smart about only running tests for things that changed, and it's much faster than karma + chrome (probly due in no small part to jsdom.) 

I am totally aware that it'd be much more complete testing in a browser, but the overhead of writing all the unit-tests on top of stories, for our project, is too much, when we get the same for free for most of our components.

I will say that, as a sidenote, it's not that preposterous to add guards against that sort of thing, though. A lot of js libraries that are distributed on npm have these sort of guards (node doesn't have a DOM.)

**Comment by CookPete** [comment]
> The error is in the title: TypeError: Cannot read property 'addEventListener' of null

Duhh. Sorry!

>I will say that, as a sidenote, it's not that preposterous to add guards against that sort of thing, though. A lot of js libraries that are distributed on npm have these sort of guards (node doesn't have a DOM.)

It's hosted on npm but ReactPlayer is only ever going to be used in a browser. It's not preposterous in terms of the amount of code to add, but my issue is that if `this.player` is null in a browser then that _should_ cause an error, as something has gone wrong and ReactPlayer will not work correctly.

>I'll answer your last question, but I have a feeling it's a testing style question that can't be easily resolved without quite a bit of opinion that disagrees with your opinions on testing (I looked at how you are testing in this project and others, with karma, in a "real" browser.)

I don't feel strongly about karma. It's more of a necessary evil with the amount of external stuff going on when loading SDKs and playing videos.

Two suggestions:

- It looks relatively easy and non-intrusive to [mock components in storyshots](https://github.com/storybooks/storybook/issues/962#issuecomment-297603508).
- If mocking doesn't work or fit your test pattern, I suppose we could guard against `this.player` being null when `FilePlayer` mounts, but add a console warning that can be ignored when testing. Something like `The component mounted but the media element was unavailable, player events will not work correctly`

**Comment by konsumer** [comment]
No prob. I can mock react-player in my project. I like that a lot better than mocking the url (but youtube does also work ok.) I should have thought of that first, as I have mocked other stuff in jest.

I'd prefer to not get console.errors in my unit-tests, but the other solution fits great, and I think resolves everything perfectly.

Thanks for your time, and this awesome & useful component!
