### ISSUE TITLE
Unable to load beta

### ISSUE THREAD

**Issue by Redmega** [CookPete/react-player#263]
React: `16.0.0`
ReactPlayer version: `1.0.0-beta.2`

I can confirm it works fine with `1.0.0-beta.1`, so there might be something wrong with the .2 release.

**Comment by Redmega** [comment]
Never mind, seems yarn was having issues with cache or something. Remove node_modules and yarn-lock and running `yarn install` fixed the issue.

**Comment by Redmega** [comment]
Never mind, seems the caching issue was caching `beta.1`. `beta.2` definitely doesn't work, tried it on two different machines.

Error: `Module not found: Error: Can't resolve 'react-player' in '/workspace/**project**/common/components'`.

I'm importing via `import ReactPlayer from 'react-player'`.

**Comment by SkinyMonkey** [comment]
I had to go in the node_modules/react-player folder and do a npm run build:lib in order to make it work if that helps

**Comment by Redmega** [comment]
@SkinyMonkey Definitely helps. I think @CookPete might have forgotten to build before publishing to npm ;)

**Comment by CookPete** [comment]
>I think @CookPete might have forgotten to build before publishing to npm ;)

Correct. I published on a machine using npm `<4.0` so `prepublishOnly` didn't run :(

Should be sorted in `1.0.0-beta.3`

**Comment by dehypnosis** [comment]
Wooops.

happens again.

**Comment by CookPete** [comment]
Fixed in `1.1.1`.
