### ISSUE TITLE
Warning with pass value CSS properties width and height

### ISSUE THREAD

**Issue by AtNovember** [CookPete/react-player#266]
Warning: a `div` tag (owner: `ReactPlayer`) was passed a numeric string value for CSS property `width` (value: `260`) which will be treated as a unitless number in a future version of React.

```
<ReactPlayer
   url={video.link}
   height="180"
   width="260"
/>
```

**Comment by Redmega** [comment]
@AtNovember use 180px instead of 180, etc.

**Comment by CookPete** [comment]
You should pass in numeric values like `width={260} height={180}` or, as @Redmega says, add units to the strings like `width="260px" height="180px"`
