### ISSUE TITLE
[0.25.x] Updating className does not trigger an update

### ISSUE THREAD

**Issue by Tenga** [CookPete/react-player#268]
Versions before `1.0.0` [seem to have a fairly restrictive `shouldComponentUpdate`](https://github.com/CookPete/react-player/blob/v0.25.3/src/ReactPlayer.js#L49) which prevents `className` prop from triggering an update.

Is there any chance of a `0.25.x` patch release for this issue while we wait for `1.0.0` stable? :)

**Comment by CookPete** [comment]
@Tenga Is there anything specific preventing you from using the `1.0.0` beta? It is quite stable now.

**Comment by Tenga** [comment]
@CookPete Not really, I assumed `1.0.0` was unstable and in flux due to `beta`, but then again, it's not like `0.x.x` designates stable either. :stuck_out_tongue:
