### ISSUE TITLE
Redux local storage

### ISSUE THREAD

**Issue by markolofsen** [CookPete/react-player#269]
**After installing "redux-localstorage" I got many errors. Need to wrap in persist() ?**

`
warning.js?8a56:33 Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're accessing the property `nativeEvent` on a released/nullified synthetic event. This is set to null. If you must keep the original synthetic event around, use event.persist(). See https://fb.me/react-event-pooling for more information.
`

**Comment by CookPete** [comment]
@markolofsen I'm not sure how this relates to ReactPlayer. Do you have some example code, or a jsFiddle, or any steps to reproduce the errors?

**Comment by CookPete** [comment]
Feel free to reopen with more details.
