### ISSUE TITLE
Weird behavior after ended youtube video

### ISSUE THREAD

**Issue by hcuong** [CookPete/react-player#271]
Problem
When a youtube video is ended. We can't replay by clicking play button or youtube play button. 

Reproduce in demo app.
1. Choose an youtube video
2. Play or seek to the end.
3. Click play button or youtube play button
4. The video will not play until we click play again.

It seems that when we click play button youtubeStateChanged send an event pause after that. 
I'd thought it related to #265. But when it was closed the problem still happen.

**Comment by CookPete** [comment]
I'm pretty sure this was because the internal `isPlaying` flag wasn't being set to `false` when a video ends. Published a fix in the latest `1.0.0` beta so give it a go: `npm install react-player@1.0.0-beta.5`
