### ISSUE TITLE
Error event not fired for soundcloud tracks not available in country

### ISSUE THREAD

**Issue by abali96** [CookPete/react-player#273]
If I try to play a song like https://soundcloud.com/ariana-grande-official/a-little-more-homework-single from Canada, the onError prop that I pass doesn't get called although I do see the following in the embedded player.
![image](https://user-images.githubusercontent.com/5098093/32619801-bb73c6b2-c549-11e7-89cd-bceaf9bfdd23.png)

Is there any way that I can know when something fails to play because of this or related errors? This is a great package - thanks!

**Comment by CookPete** [comment]
Try loading the song in the [widget playground](https://w.soundcloud.com/player/api_playground.html). Does anything appear in the event log that we could listen for? I can't reproduce the issue as the song loads fine for me (in the UK).

**Comment by CookPete** [comment]
I was able to reproduce the issue, but there is no event that the widget SDK outputs that we can hook into. Seems like this is not fixable for the time being.
