### ISSUE TITLE
seekTo always goes back to the beginning of the video

### ISSUE THREAD

**Issue by allenylzhou** [CookPete/react-player#275]
I'm using react-player 0.25.3 with react 15.6.1

I can't reproduce this locally, but when I build my app on a server, using npm run build (create-react-app), it can always be reproduced. I checked my package dependencies and node versions, everything seems to be the same; very frustrating.

I have a 8 second long mp4 video wrapped in react player, and when I call seekTo(3/8) or seekTo(3), it just seeks back to the beginning of the video.  Has anyone encountered issues of this sort before?

**Comment by CookPete** [comment]
I've deployed a basic `create-react-app` build here to try and reproduce the issue:

http://cookpete.com/react-player-seek-bug

Everything seems to work ok.

All I've done is installed `react-player` and added the following to `App.js` of the boilerplate `create-react-app`:

```js
        <ReactPlayer
          ref={rp => this.rp = rp}
          playing
          url="http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4"
        />
        <button onClick={() => this.rp.seekTo(0)}>seekTo(0)</button>
        <button onClick={() => this.rp.seekTo(3)}>seekTo(3)</button>
        <button onClick={() => this.rp.seekTo(3/8)}>seekTo(3/8)</button>
```

All `seekTo()` does for mp4 videos is `videoElement.currentTime = newTimeInSeconds`, so it's very hard to tell what is going wrong without seeing the code, or seeing the video you are using.

**Comment by CookPete** [comment]
Feel free to reopen if you can reproduce the issue in a jsFiddle or repo.

**Comment by allenylzhou** [comment]
I discovered the source of the issue. The server that was serving the video file was not set up properly to support 206 requests. When I served the video file from amazon s3, it worked perfectly.

**Comment by cl-aviram-rnd** [comment]
anyone has a clue on how to resolve this without changing something in the server? why can't be just seek to position in the video itself only without making a request?
