### ISSUE TITLE
Fullscreen mode does not work

### ISSUE THREAD

**Issue by markolofsen** [CookPete/react-player#277]
Check fullscreen mode in mobile (Chrome, IOS) — nothing happens, but in desktop all ok.
Also, mute & playbackRate mode does not work too in mobile browser.

**Comment by CookPete** [comment]
See [mobile considerations](https://github.com/CookPete/react-player#mobile-considerations) in the readme. Most mobile browsers have their own rules about autoplaying, fullscreen and volume that override anything that we can do with JS.

Note that `playbackRate` only works with Youtube, Wistia, and files, and only on desktop (and any mobile browsers that support it). See [compatibility table](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/playbackRate#Browser_compatibility).

Also see [iOS device specific considerations](https://developer.apple.com/library/content/documentation/AudioVideo/Conceptual/Using_HTML5_Audio_Video/Device-SpecificConsiderations/Device-SpecificConsiderations.html):

>On iOS devices, the audio level is always under the user’s physical control. The `volume` property is not settable in JavaScript. Reading the volume property always returns 1.

>Setting `playbackRate` is not currently supported on iOS.

If there is a specific feature that you think _should_ work on mobile according to an article or documentation somewhere, then feel free to reopen this issue (or create a new one) with an example of what you are trying to acheive, or a code snippet that you expect to work.

**Comment by markolofsen** [comment]
> Most mobile browsers have their own rules about autoplaying, fullscreen and volume that override anything that we can do with JS.
Thanks.
