### ISSUE TITLE
Get the time remaining on a video/audio 

### ISSUE THREAD

**Issue by Conrad777** [CookPete/react-player#28]
Hi @CookPete maybe I'm just missing it, but I can't find a way to check how much time is still left on a song or the total length of the clip? Is that because there is no way to do it yet or did I just over look it?

**Comment by CookPete** [comment]
Hey @Conrad777, there actually isn't a way to get it from the player yet, but this is a good idea. Perhaps it should be part of the `onProgress` callback? A direct method like `getDuration` could be too problematic if it was called before the player had any duration information.

Maybe this even warrants a new callback prop, `onDuration` or something

**Comment by Conrad777** [comment]
I agree with making it a callback... You're only ever going to need it after the clip has loaded anyway. `onDuration` sound cleaner to me than making it part of `onProgress` don't you think? 

I am basically just agreeing with you, not even sure if its helping.

**Comment by CookPete** [comment]
Yeah, at first I was reluctant to add yet another `onSomething` prop, but it doesn't really belong in `onProgress`.

> I am basically just agreeing with you, not even sure if its helping.

Any feedback is a great help :)

**Comment by CookPete** [comment]
Fixed in `v0.5.0`, thanks @Conrad777!
