### ISSUE TITLE
How to run the file after it was received after the request

### ISSUE THREAD

**Issue by dffpm** [CookPete/react-player#282]
Good day.
Excuse me for my incompetence first of all.
I have to make request with Authorization header for getting file. How can i set response file into the react-player component after request completed?

**Comment by CookPete** [comment]
Hey @dffpm,

If your file server supported CORS, you could use `fetch` and `URL.createObjectURL`:

```js
const source = 'http://example.com/cors-enabled-video.mp4'
const options = {
  headers: {
      Authorization: 'Basic blahblahblah'
  }
}
fetch(source, options)
  .then(response => response.blob())
  .then(blob => {
      this.setState({
      url: URL.createObjectURL(blob)
    })
  })
```

See an [example jsFiddle](https://jsfiddle.net/44e53oo4/). Note that it doesn't work, because I couldn't find an example MP4 file on a CORS-supported server, but it _should_ work with the correct setup.

Alternatively, you could amend your file server behaviour to accept an authorisation query parameters, and use `http://example.com/file.mp4?auth=blahblahblah`

**Comment by dffpm** [comment]
It works,  thank you!

**Comment by ttiras** [comment]
Hello,
I implemented this code for auth headers on s3. It works fine but large video files are taking too long to load. 
I would appreciate if you have an advice to tackle this.

**Comment by ARFayyaz** [comment]
> 

Same problem. It downloads the whole file and then loads it. Need to find a way to stream data alongwith authorization

**Comment by ttiras** [comment]
> > 
> 
> Same problem. It downloads the whole file and then loads it. Need to find a way to stream data alongwith authorization

I achieved it with hls file. Here is my code:

`<ReactPlayer
          width="100%"
          height="100%"
          url={path}
          config={{
            file: {
              forceHLS: true,
              hlsOptions: {
                xhrSetup: function (xhr, url) {
                  xhr.open("GET", url, true);
                  xhr.setRequestHeader(
                    "Authorization",
                    `Bearer ${accessToken}`
                  );
                },
              },
              attributes: { 
                poster: process.env.PUBLIC_URL + "/assets/img/academy.png"
              }
            },
          }}
          controls
          onDuration={onDuration}
          onEnded={onEnded}
        />`

**Comment by ARFayyaz** [comment]
> config={{
>             file: {
>               forceHLS: true,
>               hlsOptions: {
>                 xhrSetup: function (xhr, url) {
>                   xhr.open("GET", url, true);
>                   xhr.setRequestHeader(
>                     "Authorization",
>                     `Bearer ${accessToken}`
>                   );
>                 },
>               },
>               attributes: { 
>                 poster: process.env.PUBLIC_URL + "/assets/img/academy.png"
>               }
>             },
>           }}

Tried your code, the call is made fine, with the token. I can also see that I get response from the back-end in the network tab. But the video player keeps showing the loading spinner, and doesnt play.

**Comment by ttiras** [comment]
I am on version 2.10.0 and it works like a charm with a graphql backend.

**Comment by ARFayyaz** [comment]
@ttiras I am trying to access an .mp4 video behind a protected endpoint, not an HLS video

**Comment by ttiras** [comment]
But you can't achieve what you want with mp4.

**Comment by ARFayyaz** [comment]
Why so?

My server delivers an mp4 file in chunked data (using ranges).

On the client side, I want to achieve that as soon as video starts downloading, the video is playable, and it keeps buffering as the next range of data becomes available. 

That cant be achieved with mp4?

**Comment by ttiras** [comment]
AFAIK with react player you need hls file format to achieve streaming. I don't know how to stream mp4s so maybe an expert would help you, if you don't want to deal with hls, which by the way is an easy step to convert mp4s.
