### ISSUE TITLE
hls video fails when src is defined as an attribute of an array definition

### ISSUE THREAD

**Issue by iambumblehead** [CookPete/react-player#283]
hls video fails when src is defined as an attribute of an array definition

does not play
```jsx
            <ReactPlayer
                ref={this.ref.bind( this )}
                url={srcarr}
```

does play
```jsx
            <ReactPlayer
                ref={this.ref.bind( this )}
                url={srcarr.length ? srcarr[0].src : null}
```

**Comment by CookPete** [comment]
HLS is not currently supported when part of an array, as it gets [handled differently in the `load` method](https://github.com/CookPete/react-player/blob/61db28ef96aec268a2394ef5f586b64011b1cb60/src/players/FilePlayer.js#L89-L95) and there would be no way of knowing whether or not to use the other sources in the array or the HLS file. Arrays are mainly for [natively supported file types](https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats#File_Formats) to let the browser decide which is best to use.
