### ISSUE TITLE
IE11 compilation issue

### ISSUE THREAD

**Issue by viczam** [CookPete/react-player#284]
Before anything, thank you very much for the library.

I'm facing some issues with compiling the library for IE 11.

I use the following babel configuration:

```
{
  "presets": [
    "next/babel",
    [
      "env",
      {
        "targets": {
          "node": "current",
          "browsers": ["ie >= 10", "last 2 versions"]
        },
        "useBuiltIns": true
      }
    ],
    "react",
    "stage-0"
  ],
  "plugins": [
    "transform-object-rest-spread",
    "transform-class-properties",
    "transform-runtime",
    ["styled-components", { "ssr": true, "displayName": true, "preprocess": false }]
  ]
}
```

And I get the following error in IE - https://www.dropbox.com/s/nkcfbiun3eqw65f/Screenshot%202017-11-23%2002.25.44.png?dl=0

Any ideas on how to fix it?

**Comment by CookPete** [comment]
Hey @viczam, are you using a polyfill? IE11 requires `babel-polyfill` or similar to work correctly. See https://github.com/CookPete/react-player/issues/239.

**Comment by viczam** [comment]
You're right, it worked with babel-polyfill. Thank you!
