### ISSUE TITLE
iframe.contentWindow giving <undefined> to me : Chrome Version 62.0.3202.94

### ISSUE THREAD

**Issue by mehulpangtey** [CookPete/react-player#285]
![screen shot 2017-11-27 at 3 48 29 pm](https://user-images.githubusercontent.com/2527530/33261944-9ba9a7d0-d38a-11e7-899e-803811bdcd38.png)

```js
import React, { Component } from 'react'
import ReactPlayer from 'react-player'

class App extends Component {
  render () {
    return <ReactPlayer url='https://www.youtube.com/watch?v=ysz5S6PUM-U' playing />
  }
}
```

**Comment by CookPete** [comment]
Hey @mehulpangtey do you have a jsFiddle or example repo where this happens?

**Comment by CookPete** [comment]
Feel free to reopen with more details.
