### ISSUE TITLE
switching hls url values during video play causes video player to freeze

### ISSUE THREAD

**Issue by iambumblehead** [CookPete/react-player#287]
switching hls url values during video play causes video player to freeze

**Comment by CookPete** [comment]
What URLs are you using? I can't reproduce this.

The [demo page](http://cookpete.com/react-player) seems to work fine when switching between:

- http://qthttp.apple.com.edgesuite.net/1010qwoeiuryfg/sl.m3u8
- https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8

**Comment by trops** [comment]
this works on the web, and does not work via mobile (iPhone). Running tethered to Safari, the error looks like something with hls.min.js.

**Comment by iambumblehead** [comment]
```bash
"react-player": "^1.0.0-beta.7"
```
my hls issues seem to have gone away since I started using the beta version this morning.
