### ISSUE TITLE
HLS not working on IE11

### ISSUE THREAD

**Issue by brunolucena** [CookPete/react-player#295]
I'm trying to use the demo in IE11, and it works really good with all types of videos, expect HLS.
Is there any problem with the demo?

**Comment by CookPete** [comment]
ReactPlayer uses [`hls.js`](https://github.com/video-dev/hls.js/) for HLS videos. Does the video you are trying to play work in the [hls.js demo page](https://video-dev.github.io/hls.js/demo/) in IE11? If not it is a problem with hls.js and not ReactPlayer.

**Comment by brunolucena** [comment]
I'm trying to play the video from the sample page:
https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8

But I get an error: "your Browser does not support MediaSourceExtension / MP4 mediasource".
So, it doesn't work on IE11?

**Comment by CookPete** [comment]
The video from the sample page does not work for me on the hls.js demo page in IE11:

https://video-dev.github.io/hls.js/demo/?src=https%3A%2F%2Fbitdash-a.akamaihd.net%2Fcontent%2FMI201109210084_1%2Fm3u8s%2Ff08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8&enableStreaming=true&autoRecoverError=true&enableWorker=true&dumpfMP4=false&levelCapping=-1&defaultAudioCodec=undefined

It seems like HLS just does not work on IE11. Even [other HLS players](http://players.akamai.com/hls/) do not work for me on IE11. Feel free to create an issue with [hls.js](https://github.com/video-dev/hls.js/).
