### ISSUE TITLE
twitch match regex not working

### ISSUE THREAD

**Issue by maticrivo** [CookPete/react-player#296]
twitch is not matching the url correctly if the url doesn't have `www.`

i.e:
https://twitch.tv/channel_id doesn't match with the MATCH_CHANNEL_URL regexp while https://www.twitch.tv/channel_id does

is that an expected behaviour? or should i open a PR to fix the regex? maybe other vendors have the same issue, didn't check..

**Comment by CookPete** [comment]
This is fixed in the `1.0.0` beta (which is stable and will be released soon). Use that for the time being:

`npm install react-player@next`
