### ISSUE TITLE
how to set preload as false

### ISSUE THREAD

**Issue by Liaohuanle** [CookPete/react-player#300]

**Comment by CookPete** [comment]
If you are talking about the `preload` prop for YouTube/SoundCloud/Vimeo/DailyMotion, this is set to `false` by default.

If you are talking about the `preload` attribute when playing files, you can use `config.file.attributes` to override any attributes on the `<video>` element:

```jsx
<ReactPlayer
  url='file.mp4'
  config={{
    file: { 
      attributes: { 
        preload: 'none' 
      } 
    } 
  }}
/>
```

**Comment by thienbao12a2** [comment]
> If you are talking about the `preload` prop for YouTube/SoundCloud/Vimeo/DailyMotion, this is set to `false` by default.
> 
> If you are talking about the `preload` attribute when playing files, you can use `config.file.attributes` to override any attributes on the `<video>` element:
> 
> ```js
> <ReactPlayer
>   url='file.mp4'
>   config={{
>     file: { 
>       attributes: { 
>         preload: 'none' 
>       } 
>     } 
>   }}
> />
> ```
I am having an issue with react-player where on Ipad IOS 14 and below, it doesn't automatically play the video when the page first loads, if I add a controller then I would have to click Play for it to start playing the video. I noticed that by removing the preload attribute completely from Element Inspection, the video starts playing automatically. I also tried to set preload to "none" as you suggested, but that didn't work. Could you please help?

**Comment by prasenjit-paul-prosperitas** [comment]
Despite setting the `'preload'` attribute to `'none'`, the player continues to preload videos.
