### ISSUE TITLE
how can i add poster for this video?

### ISSUE THREAD

**Issue by Liaohuanle** [CookPete/react-player#301]

**Comment by CookPete** [comment]
For files, you can use the `config.file.attributes` prop:

```jsx
<ReactPlayer
  url='file.mp4'
  config={{
    file: { 
      attributes: { 
        poster: 'poster.jpg' 
      } 
    } 
  }}
/>
```

Anything in `config.file.attributes` will just get [added to the `<video>` element when playing files.](https://github.com/CookPete/react-player/blob/master/src/players/FilePlayer.js#L174)
