### ISSUE TITLE
Remove youtube logo

### ISSUE THREAD

**Issue by newturok** [CookPete/react-player#303]
![image](https://user-images.githubusercontent.com/5757827/34817002-55919494-f6bf-11e7-9a57-ce757bad2390.png)

Can i somehow remove youtube logo at the start?

**Comment by CookPete** [comment]
There is a [`modestbranding`](https://developers.google.com/youtube/player_parameters#modestbranding) player param that will show the logo when paused, but hide the logo when the video has been playing for a second or two. Add it to your `config`:

```jsx
<ReactPlayer
  url={url}
  config={{
    youtube: {
      playerVars: { modestbranding: 1 }
    }
  }}
/>
```

I may add this to the default config in future versions, as it looks much cleaner.

**Comment by newturok** [comment]
For help, there is also [iv_load_policy: 3](https://developers.google.com/youtube/player_parameters#iv_load_policy)
```
<ReactPlayer
  config={{
    youtube: {
      playerVars: { modestbranding: 1, iv_load_policy: 3}
    }
  }}
/>
```
thats turn off all annotations.

**Comment by joemarieandres** [comment]
Hi, @cookpete 
I would like to remove the Youtube logo and subtitle at the top in react-player.
```
config={{
    youtube: {
      playerVars: { modestbranding: 1 }
    }
  }}
```
It doesn't works for me at the moment.
How can we remove the Youtube logo and sub title at the top?
Hope to hearing from you soon.
Thank you.

**Comment by cookpete** [comment]
@joemarieandres

- https://github.com/cookpete/react-player/issues/1009#issuecomment-689056369
- https://github.com/cookpete/react-player/issues/893#issuecomment-630614277
- https://github.com/cookpete/react-player/issues/469

**Comment by joemarieandres** [comment]
Thanks for your reply. @cookpete 
So for now, there is no way to remove the Youtube and sub title at the top.
Am I right?

**Comment by valenciaHQ** [comment]
hi! any news about this? i guess there is not way right?

**Comment by viancamaulion** [comment]
As of 2023, modestBranding won't take effect anymore:

[deprecation announcement](https://developers.google.com/youtube/player_parameters#release_notes_08_15_2023)

![image](https://github.com/user-attachments/assets/14d0461e-2cb7-4f83-9f91-0f2b6fd58bee)
