### ISSUE TITLE
Youtube autoplay warning

### ISSUE THREAD

**Issue by johnandblue** [CookPete/react-player#306]
I'm using `react-player` for some youtube videos, but the console throws a warning about `autoplay`. 
I tried to figure out why, but the docs for the youtube iframe only specify that it needs the prop `enablejsapi` set to 1. 

After trying all the possibilities this is my component and below the error that I'm getting:
Any idea why this warning is happening?

```js
const ReactPlayer = props => (
  <Media
    key={ props.title }
    playing={ props.playing }
    url={ props.url }
    controls={ props.controls }
    height={ props.height }
    width={ props.width }
    config={ {
      file: {
        attributes: {
          poster: props.poster,
        },
      },
      youtube: {
        playerVars: {
          showinfo: 0,
          autoplay: 0,
          color: 'white',
          enablejsapi: 1,
        },
      },
    } }
  />
);
```

<img width="1440" alt="screen shot 2018-01-15 at 17 23 05" src="https://user-images.githubusercontent.com/21159524/34952121-f259961c-fa18-11e7-969f-e5be46c386dd.png">

**Comment by CookPete** [comment]
This error is happening on the [Youtube player demo page](https://developers.google.com/youtube/youtube_player_demo) as well as the [ReactPlayer demo page](http://cookpete.com/react-player), so I don't think it's anything to do with ReactPlayer or your implementation. It is probably related to the [upcoming autoplay policy changes in Chrome](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes) and the Youtube player SDK is being adjusted accordingly.

Also, there are default `playerVars` used by ReactPlayer, so most of your config is unnecessary:

https://github.com/CookPete/react-player/blob/5952b4c52f1496291f4cff3b49f13c0cf7522959/src/props.js#L84-L91

**Comment by johnandblue** [comment]
Thanks for the clarification! Cheers.
