### ISSUE TITLE
seems that progressFrequency does not work correctly

### ISSUE THREAD

**Issue by IzaGz** [CookPete/react-player#307]
tried to set it as progressFrequency={2000}, progressFrequency={500}, it does fire the onProgress={this.onProgress} as expected

**Comment by CookPete** [comment]
Note that `onProgress` will not be called if there is no change from the previous values (like when the video is paused) to prevent unnecessary re-renders of an app. Could this be what is happening? What URL are you seeing this happen with?

**Comment by IzaGz** [comment]
@CookPete i use just any youtube video, it is playing, but  progressFrequency not called correctly.

**Comment by CookPete** [comment]
Are you using `0.25`? If so I would try the `1.0.0` beta:

```bash
npm install react-player@next
```

If this doesn't fix things then you'll have to provide an example repo or jsFiddle where this happens. I can't reproduce the issue myself.
