### ISSUE TITLE
getCurrentTime() is not a function

### ISSUE THREAD

**Issue by againksy** [CookPete/react-player#308]
Calling getCurrentTime() as in example `https://github.com/CookPete/react-player/blob/master/src/demo/App.js` for this.player. Using youtube video url. Cant get current playing time.

**Comment by againksy** [comment]
@CookPete  also onProgress i receive the object only with {loaded} property. Trying to get current playing time like here `https://github.com/CookPete/react-player/issues/163` but progress.played is undefined

**Comment by CookPete** [comment]
Hey @againksy are you using `0.25`? If so I would try the `1.0.0` beta:

```bash
npm install react-player@next
```
