### ISSUE TITLE
Updating playing prop doesn't hide or show youtube controls

### ISSUE THREAD

**Issue by gitwik** [CookPete/react-player#310]
I am using react-player for playing youtube videos
```javascript
<ReactPlayer
            height="100%"
            width="100%"
            onPause={this.onPause}
            onPlay={this.onPlay}
            playing={this.props.videoIsPlaying}
            url={this.props.url}
            controls={this.props.videoIsPlaying}
            {...this.props.config} />
```
Now updating the prop value doesn't hide or show the youtube player controls

**Comment by CookPete** [comment]
See https://github.com/CookPete/react-player/issues/146#issuecomment-275467484. The `controls` player param is set on player initialisation, and sadly there isn't any API methods to update it.
