### ISSUE TITLE
"Unrecognized feature: 'autoplay'." warning when mounting a YouTube player.

### ISSUE THREAD

**Issue by jahed** [CookPete/react-player#312]
I keep seeing this error when ReactPlayer gets mounted with a YouTube URL (without autoplay).

Here's how I'm using it:

```js
<div className={styles.GameDescription__Video}>
    <ReactPlayer url={video} width="100%" height="100%" />
</div>
```

Here's the message:

```
www-widgetapi.js:110 Unrecognized feature: 'autoplay'.
jb @ www-widgetapi.js:110
W @ www-widgetapi.js:98
Y @ www-widgetapi.js:118
(anonymous) @ YouTube.js:92
Promise resolved (async)
load @ YouTube.js:90
componentDidMount @ Player.js:123
commitLifeCycles @ react-dom.development.js:8770
commitAllLifeCycles @ react-dom.development.js:9946
callCallback @ react-dom.development.js:542
```

It is just a warning and it still works fine, though it's spamming the console.

Probably related to this `autoplay` prop, which may not be supported by YouTube?

https://github.com/CookPete/react-player/blob/c0eae2231be087bbcaeea440f475fa02d8111954/src/props.js#L86

I'm not familiar with the YouTube API to propose a fix but I can look deeper into it if needed.

**Comment by CookPete** [comment]
>This error is happening on the [Youtube player demo page](https://developers.google.com/youtube/youtube_player_demo) as well as the [ReactPlayer demo page](http://cookpete.com/react-player), so I don't think it's anything to do with ReactPlayer or your implementation. It is probably related to the [upcoming autoplay policy changes in Chrome](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes) and the Youtube player SDK is being adjusted accordingly.

From https://github.com/CookPete/react-player/issues/306#issuecomment-357872732
