### ISSUE TITLE
React Player not working on mobile devices :(

### ISSUE THREAD

**Issue by avj2352** [CookPete/react-player#314]
I have deployed a heroku app which uses React Player. Works great on desktops but on mobile its doesnt stream from youtube.

you can find the link: https://puja-weds-sourav.herokuapp.com

Please help !!

**Comment by CookPete** [comment]
Hi @avj2352, see the readme section on [mobile considerations](https://github.com/CookPete/react-player#mobile-considerations). Unfortunately mobile browsers deliberately restrict videos, especially autoplaying videos that are not actually displayed on screen, like in your example.

**Comment by avj2352** [comment]
Actually ReatPlayer does work on mobile. it was the URL which was a youtube url, I switched the url on client recommendation from youtube to soundcloud and it worked like magic...

P.S: You lib rocks !! (superlike)

**Comment by mazenchami** [comment]
@avj2352 can you please provide your code snippet on how you got it to work on React-Native?
i get the following error: `Invariant Violation: View config not found for name div`
