### ISSUE TITLE
The progressFrequency is actually a period

### ISSUE THREAD

**Issue by ThoAppelsin** [CookPete/react-player#317]
The `progressFrequency` prop is actually a period. Wasn't a problem for me, since I have first seen it on the [readme#props](https://github.com/CookPete/react-player#props), where the description says that it is in milliseconds. A default of 1kHz refresh rate would also be too high for a video player, which ascertained me that it really was just a misnomer.

You may consider renaming it to `progressPeriod`, or make it function as a frequency instead. Or just hope that nobody is mislead by it, at least not for too long.

**Comment by CookPete** [comment]
I think if it were to change it should be `progressInterval`, as it quite closely matches the behaviour of the well-known `setInterval`. However, I also think the chances are very small of someone seeing `progressFrequency` in the readme but not actually checking what the prop does.

**Comment by ThoAppelsin** [comment]
> I also think the chances are very small of someone seeing `progressFrequency` in the readme but not actually checking what the prop does

This is true, but I was thinking that maybe someone could find out what props the component has without the readme. For example, my editor (VSCode) somehow knows about them, such that when I type "p" for an additional prop in your demo application, it recommends me the `playsInline` and the `progressInterval`:

![vscodeknows](https://user-images.githubusercontent.com/6666524/35721634-fd3e1bcc-0803-11e8-8de2-14144287c868.png)

Then again, I also am not sure if it would be beneficial to make any of the two changes I have suggested. It would be good for the newcomers, sure, but would it worth it to make a breaking update for it?

If you are going to take any action, I think renaming the prop would be better, so that it actually breaks for whoever updates, and so they know.

**Comment by CookPete** [comment]
>Then again, I also am not sure if it would be beneficial to make any of the two changes I have suggested. It would be good for the newcomers, sure, but would it worth it to make a breaking update for it?

If I do change it I'll keep `progressFrequency` working and log a deprecation warning to the console, then remove it whenever `2.0` happens.
