### ISSUE TITLE
YouTube player occasionally does not preload properly

### ISSUE THREAD

**Issue by Fauntleroy** [CookPete/react-player#32]
I'm still trying to get to the bottom of this one, but I have a theory for why it might not work properly 100% of the time:

- Player starts with a valid SoundCloud URL
- SoundCloud player is rendered before the YouTube iframe is rendered and ready
- YouTube iframe does not have whatever focus token Chrome gives it
- This tab/window loses focus
- YouTube videos will not autoplay until window attains focus

**Comment by CookPete** [comment]
Hey @Fauntleroy, do you have steps to reproduce this? I can see the problem but only when changing to another tab _before_ the blank YT preload video has started playing (that is, quite quickly after initial load), which makes sense, and is something that can't really be fixed.

**Comment by CookPete** [comment]
Anything further on this @Fauntleroy?

**Comment by CookPete** [comment]
Closing this due to age. Feel free to re-open with steps to reproduce the issue.
