### ISSUE TITLE
Hello, which way can i set custom cuntrols styles, or hide some controls? 

### ISSUE THREAD

**Issue by againksy** [CookPete/react-player#323]
How to hide, style, add, customise controll buttons? For example, now i want to hide the download button .

**Comment by CookPete** [comment]
@againksy what URL are you playing? ReactPlayer does not provide custom controls, but allows you to render your own.

**Comment by againksy** [comment]
@CookPete i play from local file served by url , so i need to customise the player look styles

**Comment by CookPete** [comment]
Playing files just uses the native browser controls. This avoids a bunch of potential cross-browser issues. See https://github.com/CookPete/react-player/issues/174 for more info.

**Comment by CookPete** [comment]
To remove the download button you can use `controlsList` like so:

```jsx
<ReactPlayer
  controls
  url='http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4'
  config={{ file: { 
    attributes: {
      controlsList: 'nodownload'
    }
  }}}
/>
```

https://jsfiddle.net/ycq1g7rw/

**Comment by yangzeyanlove** [comment]
Ok, thanks

**Comment by GidaeYeo** [comment]
@CookPete You saved my time! Thank you a lot! :-)

**Comment by EdenLiang** [comment]
Thanks you
@CookPete 
My attributes
```
<ReactPlayer config={{
     file: {
       attributes: {
         onContextMenu: e => e.preventDefault(),
         controlsList: 'nodownload'
       }
      }
    }} controls url='xx' />
```

**Comment by Talha-Aftabb** [comment]
config={{
              file: {
                attributes: {
                  controlsList: 'nodownload', //<- this is the important bit
                },
              },
            }}

**Comment by ramandeep-dezerv** [comment]
Using this way, if the user edit the html by inspecting the page and removes this attribute to prevent from download, user gets the option back to download.
