### ISSUE TITLE
Hls Config

### ISSUE THREAD

**Issue by jgoggles** [CookPete/react-player#325]
Is it (or would it be) possible to pass configuration to the Hls object as stated in the Hls.js [documentation](https://github.com/video-dev/hls.js/blob/master/doc/API.md#fine-tuning)?

**Comment by CookPete** [comment]
As of `1.1.2` you can do:

```jsx
<ReactPlayer
  url={url}
  config={{
    file: {
      hlsOptions: { 
        // options here
      }
    }
  }}
/>
```

**Comment by jgoggles** [comment]
Thank you @CookPete!

**Comment by amanpwl92** [comment]
I tried to change the hls configuration to add authorization header but does not seem to work for me.
`<ReactPlayer url={url}
                             config={{
                                 file: {
                                     forceAudio: true,
                                     hlsOptions: {
                                         forceHLS: true,
                                         debug: false,
                                         xhrSetup: function(xhr, url) {
                                                 xhr.setRequestHeader('Authorization', `Bearer ${token}`)
                                         },
                                     }
                                 }
                             }}/>`

**Comment by tbrent** [comment]
I don't think this is currently working, at least on 2.6.2. My implementation is identical to @amanpwl92 with no success. Has anyone been able to this to work?

**Comment by lucid3v** [comment]
> I don't think this is currently working, at least on 2.6.2. My implementation is identical to @amanpwl92 with no success. Has anyone been able to this to work?

Something must have changed because the above wasn't working for me either. 
I had to change the location of `forceHLS` (moved it up under `file` instead of under `hlsOptions`) and it seems to work now...

`` config={{
          file: {
            forceHLS: true,
            hlsOptions: {
              //forceHLS: true,
              debug: false,
              xhrSetup: function (xhr, url) {                
                xhr.setRequestHeader("Authorization", `Bearer ${token}`);                
              },
``
