### ISSUE TITLE
eats key handlers?

### ISSUE THREAD

**Issue by wmertens** [CookPete/react-player#326]
Strange issue: when we use the latest react-player, our global key handlers no longer work. However, I can't find any place where it is binding keys 🤔

**Comment by CookPete** [comment]
ReactPlayer does no key binding itself, but the player SDKs that are loaded in probably do. The YouTube player, for example, once you have clicked in to the player, will play/pause when you hit `space` and will swallow up the usual keypress event.

What types of URL are you playing?

**Comment by wmertens** [comment]
Wistia, but when I disable the URL and just load the player it still has
issues. Good to know it's not react-player, I'll keep digging.
