### ISSUE TITLE
Cannot force a youtube video to show captions.

### ISSUE THREAD

**Issue by soorajvnair** [CookPete/react-player#327]
Hey there,

Great job on the library, i was wondering if cc_load_policy is supported in youtube playerVars? For some reason, i'm unable to force a youtube video to show captions, even after setting cc_load_policy to 1. Any ideas?

![cc_load_policy](https://user-images.githubusercontent.com/4268932/35988087-8ae9fca6-0d23-11e8-961d-86e4d7aa9a46.png)

here's a reproduction of the issue. https://jsfiddle.net/n46m0qv7/

**Comment by soorajvnair** [comment]
Okay i think i found out why it was not working. Turns out, cc_load_policy : 1 wouldn't enable automatically generated captions, it only enables captions that are manually added to videos.

Again great work @CookPete, such an amazing library. 👍

**Comment by tomByrer** [comment]
FYI @soorajvnair, you can access the auto-generated captions via YouTube's API.  
To [include text formatting, I forked](https://github.com/tomByrer/youtube-captions-scraper) a JS script from [Algolia](https://github.com/algolia/youtube-captions-scraper), but both are essentially the same.

**Comment by soorajvnair** [comment]
hey @tomByrer thanks for the info. Good stuff and that's really helpful.
