### ISSUE TITLE
Loop is not working for YouTube

### ISSUE THREAD

**Issue by rayrw** [CookPete/react-player#328]
When `loop` props is set to `true` and the video ends,
it can go back and play for only 1 second.
However, if I switch to another tab in my browser, it continues to play.
This happens in the demo website as well.
I'm using react-player 1.1.2, Chrome and macOS 10.13.2.

**Comment by CookPete** [comment]
@rayrw Do you have more details on how to reproduce this, or a jsfiddle or example repo? I can't cause any problems with youtube looping, whether or not the tab is in focus.

**Comment by rayrw** [comment]
I've just tested in an Incognito Window and it works.
It might be just some extension conflicts with YouTube.
Anyway, thank you.
