### ISSUE TITLE
The mp3 link in demo fails with MediaError 4 => MEDIA_ERR_SRC_NOT_SUPPORTED

### ISSUE THREAD

**Issue by dolbyarun** [CookPete/react-player#330]
The link for mp3 seems to be wrong. 
http://www.sample-videos.com/audio/mp3/crowd-cheering.mp3 
redirects to 
http://play.leadzupc.com/?m=URWWBANDOO2=930&a=9007&afc_count=1

**Comment by CookPete** [comment]
Fixed in `1.1.3` 👍

**Comment by dolbyarun** [comment]
Thanks
