### ISSUE TITLE
Abstracted methods?

### ISSUE THREAD

**Issue by matthew-dean** [CookPete/react-player#331]
Are there not abstracted methods for media like `play()`, `pause()` `mute()` `seek()` etc?

**Comment by seleckis** [comment]
I think it is possible using ref to video, or?

**Comment by CookPete** [comment]
The idea of the component is that methods are inferred from the [props](https://github.com/CookPete/react-player#props) given to the player, to match React's declarative style. For example, changing the `playing` prop from `true` to `false` will cause `pause()` to be called internally. Setting the `muted` prop to `true` will mute the player. This logic can be seen in the `Player` component:

https://github.com/CookPete/react-player/blob/1f158d1b8bb353553ea5680ed9041db26055da53/src/Player.js#L28-L51

For seeking there is a `seekTo` method that is [outlined in the readme](https://github.com/CookPete/react-player#instance-methods).

If you really want to call the methods yourself, you could use `ref` and call `getInternalPlayer()`, which will let you call any method you like on the player instance, like so:

```jsx
class App extends React.Component {
  ref = player => {
    this.player = player
  }
  render() {
    return (
      <div>
        <ReactPlayer
          ref={this.ref}
          url='http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4'
          playing
          controls
        />
        <button onClick={() => this.player.getInternalPlayer().play()}>Play</button>
        <button onClick={() => this.player.getInternalPlayer().pause()}>Pause</button>
      </div>
    );
  }
}
```

https://jsfiddle.net/p56tp1ex/1/

Generally I would advise against doing this, as you will become out of sync with any props passed to the player, and you will be more prone to bugs and getting mixed up with your player state.
