### ISSUE TITLE
Pass video dimensions, or element as part of onReady/onLoaded

### ISSUE THREAD

**Issue by G-Rath** [CookPete/react-player#337]
I'm working with a messaging application that uses a virtualized infinite list, that renders elements based on scroll position, using the combined heights of the items in the list. To do this, the list needs to calculate the height of each item in the list, before it can render select items within the scroll window.

Due to the way react renders, this is can be troublesome with content such as video and images, as their content has to be loaded before their size can be determined, which is an async process.

I can work around this with <img> as it's onLoad event has the original element (as the `target` property); Once the image has loaded, I can calculate the images size quickly via just `target.clientWidth` and `target.clientHeight`, and then pass those values to the list, which repositions them.

However, react-player doesn't pass any event details when calling `onReady`, making this process a lot more complicated, since I have to try and somehow measure the components size without causing a re-render until I have that components size (otherwise it becomes a very annoying render-re-render loop as React mounts and unmounts the components, changing their sizes in the process).

Would it be possible to pass either the dimensions of the video that's just been loaded, or a reference to the video element itself?

Sorry if this doesn't make much sense; I'm a bit burnt out after a long work day. Let me know if there's anything you'd like me to clarify.

(Also: I know I could possibly use ReactDOM to work around this, but I'd prefer to not use it if I can avoid it).

**Comment by CookPete** [comment]
I'm a bit confused by your issue. The `height` is predetermined by the prop you pass to the player, and the [default is 360px](https://github.com/CookPete/react-player/blob/b604ded0f59671e3e8c7cb4baa882146ed90101a/src/props.js#L70). Unless you are playing a file and passing `height='auto'`?

Either way, you can always get the height using a `ref` to the player and grabbing the `wrapper`:

```jsx
<ReactPlayer 
  ref={player => this.player = player}
  url='http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4'
  onReady={() => console.log('player height:', this.player.wrapper.clientHeight)}
  width='100%'
  height='auto'
/>
```

https://jsfiddle.net/Ld3Lnqf3/

**Comment by G-Rath** [comment]
@CookPete as I said, I'm trying to get the dimensions of the video. Well, the resolution. 

And using a ref might not work, since the ref isn't guaranteed to exist when the onReady function is called, depending on where React is in it's rendering cycle.

**Comment by G-Rath** [comment]
The resolution does matter when I'm controlling the size of the element. I'd like the element to be as big as possible without stretching the video. If I fix the size of the element, then when I query for the size of the element, I'll get that fixed size - so the only way to programmatically know what the "prefered size" of the video is (aka it's native resolution) is to let it be as big as it wants initially.

I'll toy around with the `ref` thing, but the problem is about while yes `ref` should always point to a component, I've had issues in the past with `onScroll` events that get called on components that have been unmounted (thus assigning ref to null, or even a different element if React manages to remount the component) before the event is fired, due to the event being async and JS's single-threaded nature.

In fairness, it could be more stable with components than it is with elements. 

Either way, thank you for your time. It's been a long day for me, so I apologise if I've come across a bit rough around the edges :)

**Comment by CookPete** [comment]
>The resolution does matter when I'm controlling the size of the element. I'd like the element to be as big as possible without stretching the video. If I fix the size of the element, then when I query for the size of the element, I'll get that fixed size - so the only way to programmatically know what the "prefered size" of the video is (aka it's native resolution) is to let it be as big as it wants initially.

So I assume you are indeed using `width='auto' height='auto'` to acheive this? Otherwise the size is always fixed, as you say.

>I'll toy around with the ref thing, but the problem is that while yes ref should always point to a component, I've had issues in the past with onScroll events that get called on components & elements that have been unmounted (thus assigning ref to null,

You could avoid your ref from ever being null with something like:

```jsx
<ReactPlayer 
  ref={player => {
    if (player) this.player = player
  }
  // etc
/>
```

>or even a different element if React manages to remount the component quickly enough) before the event is fired, due to the event being async and JS's single-threaded nature.

If React has indeed remounted another instance, wouldn't you want to use the height of the new one anyway?

**Comment by G-Rath** [comment]
Actually, I'm using height null. I've never expressly set 'auto' anywhere, but yes that's the idea.

> If React has indeed remounted another instance, wouldn't you want to use the height of the new one anyway?

Depends on the reason why it's remounted. If it's remounted because it thinks it has the correct height, and then forces the height... then leads me back to square one. It's honestly as annoying as it sounds confusing -- and also as confusing as it sounds.

I've been dealing with this for the last couple of days with images. I tested it out with the `ref`, and it does seem to be nice and stable, which does make sense: React should have more control over components than native DOM elements; I was just left a bit cynical after having to deal with stupid misfiring events for so long, and figured it'd be a similar story with this component.

Thanks for the help, and the awesome player :)
