### ISSUE TITLE
playing prop is not working in Safari

### ISSUE THREAD

**Issue by seleckis** [CookPete/react-player#338]
This is not working for me in Safari. Chrome starts video immediately. Safari not.
```jsx
<ReactPlayer playing={true} url={videos} />
```

**Comment by CookPete** [comment]
What is `videos` in your example?

**Comment by seleckis** [comment]
```js
import video_mp4_1280 from './1280.mp4';
import video_mp4_640 from './640.mp4';
import video_webm_1280 from './1280.webm';
import video_webm_640 from './640.webm';

const videos = [
	{
		src: video_webm_1280,
		type: 'video/webm',
		media: '(min-device-pixel-ratio:2), (-webkit-min-device-pixel-ratio:2)',
	},
	{
		src: video_webm_640,
		type: 'video/webm',
	},
	{
		src: video_mp4_1280,
		type: 'video/mp4',
		media: '(min-device-pixel-ratio:2), (-webkit-min-device-pixel-ratio:2)',
	},
	{
		src: video_mp4_640,
		type: 'video/mp4',
	},
];
```
This produces:
```html
<video preload="auto" style="width: 100%; height: 100%;">
	<source src="/static/media/1280.9e882287.webm" type="video/webm" media="(min-device-pixel-ratio:2), (-webkit-min-device-pixel-ratio:2)">
	<source src="/static/media/640.a06678e3.webm" type="video/webm">
	<source src="/static/media/1280.23e52731.mp4" type="video/mp4" media="(min-device-pixel-ratio:2), (-webkit-min-device-pixel-ratio:2)">
	<source src="/static/media/640.c06decc4.mp4" type="video/mp4">
</video>
```
Video is displayed in Safari, but is not playing from the very beginning. If I add controls and hit play button it starts playing. But I need it to play on load. In Chrome, Firefox it plays. But not in Safari.

**Comment by seleckis** [comment]
Oh! The solution is to add `autoPlay` prop to the component:
```
<ReactPlayer autoPlay playing={true} url={videos} />
```
Now everything works. Would be great to add this information in readme.

**Comment by CookPete** [comment]
>Oh! The solution is to add autoPlay prop to the component:
>```
><ReactPlayer autoPlay playing={true} url={videos} />
>```

I'm really confused as to why this has fixed it. Adding `autoPlay` to `ReactPlayer` will just add that attribute to the wrapper div, not the `<video>` itself. Unless Safari is also looking for `autoPlay` attributes on any parent element of a given `<video>`? I can't reproduce this issue myself.

**Comment by pugson** [comment]
I believe Safari stopped autoplaying videos that are not muted by default in Safari 11. If you add the `muted` prop to the `ReactPlayer` component, the video will start playing automatically.

**Comment by tquiroga** [comment]
I have the same problem with audio player. It doesn't play songs, if I use mute it does play, what would be a way to unmute the song immediately after it starts playing?
