### ISSUE TITLE
progressInterval default to 0?

### ISSUE THREAD

**Issue by RoelVB** [CookPete/react-player#339]
First, thanks you for this great library!

Second, I have a problem with the `progressInterval` property. Looks like the interval defaults to 0.
Only setting (the deprecated) `progressFrequency` creates an interval.

**Comment by CookPete** [comment]
Good spot! The `progressInterval` logic was lost in https://github.com/CookPete/react-player/commit/42a030e6cfa721eb15c6af2b27c828160ebcae25.

Fixed in version `1.2.1`
