### ISSUE TITLE
Can't use FilePlayer

### ISSUE THREAD

**Issue by ktabori** [CookPete/react-player#34]
Hello, 

Maybe it's me but, I can't implement the File Player, I got the following error message:

![screenshot 2016-01-25 02 24 38](https://cloud.githubusercontent.com/assets/2427061/12540537/15bc1932-c30b-11e5-85e5-253fe8f0d61e.png)

Do you have any idea?

**Comment by CookPete** [comment]
Hey @ktabori, what props are you passing in when you get this error?

**Comment by ktabori** [comment]
I have fixed it, Thank you for the fast REACTion :) I have just updated my react module and it works fine.
