### ISSUE TITLE
Programatically setting playing to true or false does nothing

### ISSUE THREAD

**Issue by phil-andrews** [CookPete/react-player#344]
I want to use the player with custom controls so I've set `controls` to false and set `playing` equal to a state variable. Changing the variable does nothing, neither does just setting `playing` to true. Even if initialized with `playing` set to true there is no audio.

```
import React from 'react'
import { connect } from 'react-redux'
import ReactPlayer from 'react-player'

class Player extends React.Component {
  
  componentWillReceiveProps(nextProps) {
    console.log(nextProps)
   // logs as expected
  }
  
  render() {
    
    const { audioPlayer } = this.props

    return (
      <ReactPlayer
        url='https://s3.amazonaws.com/*************/30rocktheme.mp3'
        playing={audioPlayer.isPlaying}
      />
    )
  }
}

export default connect(store => ({
  audioPlayer: store.audioPlayer,
}))(Player)
```

**Comment by jp3492** [comment]
I would also like to know how to programatically play and pause the player object, im switching between different players on a page and through rerendering and setting the playing props to false, doesnt make it pause

**Comment by CookPete** [comment]
On what device/browser are you seeing this happen? Changing the `playing` prop from `true` to `false` should pause the media, and the opposite should play it.

If you are both trying to play things on mobile devices, keep [mobile considerations](https://github.com/CookPete/react-player#mobile-considerations) in mind. Mobile browsers are prone to not allowing media to be played (or played with audio) without deliberate user interaction.

If either of you have an example repo or jsFiddle where the issue is occuring consistently, feel free to reopen the issue.

**Comment by artemis-prime** [comment]
Why is this closed??  I'm experiencing this on Chrome / Linux.

`export default ({ url, showCloseButton, onStart }: VideoProps) => {
  
  const s = useStyles()

  const [playing, setPlaying] = useState(false)
  return (
    <div className={s.outer}>
      <ReactPlayer
        allowFullScreen="allowFullScreen"
        frameBorder="0"
        className={s.player}
        url={url}
        width='100%'
        height='100%'
        playing={playing}
        config={{
          youtube: {
            playerVars: {
              controls: 1,
              allowFullScreen: 1,
              showinfo: 1,
              playsinline: 1,
            }
          }
        }}
        onStart={onStart}
      />
      {showCloseButton && (
        <IconButton aria-label="delete" className={s.button} onClick={() => {setPlaying(false)}}>
          <CancelIcon />
        </IconButton>
      )}
    </div>
  )
}`

**Comment by amanChaturvedi7** [comment]
I am facing the same issue, did you solve it ? @artemis-prime

**Comment by cookpete** [comment]
>Why is this closed?

Explained in [my previous comment](https://github.com/cookpete/react-player/issues/344#issuecomment-373335250):

>If either of you have an example repo or jsFiddle where the issue is occuring consistently, feel free to reopen the issue.

It's much harder for me to help if I can't easily recreate the issue myself.
