### ISSUE TITLE
onSeek always returns 0 if streamed from gridFS

### ISSUE THREAD

**Issue by jaqua** [CookPete/react-player#345]
I cannot use the onSeek function, as it always return zero:

    const src='http://localhost:3000/video/5a9bd4ecdfb06d6dbd037f2e'

    <ReactPlayer
      url={src}
      onSeek={e => console.log('onSeek', e)}
    />

Every seek will result in a console output of `onSeek 0`

The server sends the video file from gridFS storage using `gfs-stream` like this:

    res.writeHead(200, { 'Content-Type': file.contentType })
    gfs.createReadStream({ _id: id })
      .on('data', (chunk) => { res.write(chunk) })
      .on('end', () => { res.end() })
      .on('error', (err) => { throw err })

`file.contentType` is `"video/mp4"`

**Comment by CookPete** [comment]
The `onSeek` prop just gets given the `<video>` element's `currentTime` property:

https://github.com/CookPete/react-player/blob/d0334a2f55ce8258f38a7ac06a3b4799f8c2bb93/src/players/FilePlayer.js#L77-L79

If `gridfs-stream` is messing this up then I'm not sure what can be done about this within ReactPlayer.

**Comment by CookPete** [comment]
Feel free to reopen the issue if there is a specific problem that can be pinned to the ReactPlayer library.
