### ISSUE TITLE
Add support for playing fs ReadStream pipes

### ISSUE THREAD

**Issue by ridhwaans** [CookPete/react-player#347]
I've followed this nodejs tutorial from @daspinola (https://medium.com/@daspinola/video-stream-with-node-js-and-html5-320b3191a6b6) to setup a ReadStream pipe that streams mp4 from the back to html5 video. 
I have the video stream to a localhost url endpoint that maps the video to the local filesystem, but react-player in not playing the video when it takes in the url as a prop. Instead it shows a black screen.

i.e.
this works
```
<video id="videoPlayer" controls>
  <source src="http://localhost:5000/video/524" type="video/mp4">
</video>
```
this doesnt work
```
...
return(
...
<div className="ExpandedDetailPlayerDiv" style={ExpandedDetailPlayerDivStyle}>
<ReactPlayer url="http://localhost:5000/video/524" className="ExpandedDetailPlayerStyle" style={ExpandedDetailPlayerStyle}/>
</div>
...
)
...
```
problem
![capture](https://user-images.githubusercontent.com/1103336/36947644-02d3d7c4-1f9d-11e8-9ebc-953c7d7cc97a.PNG)

**Comment by CookPete** [comment]
My guess is that you need to specify the media `type` for it to work. Try passing an array to the `url` prop to specify the `type` on the `<source>`, like so:

```jsx
<ReactPlayer
  playing
  controls
  url={[
    { src: 'http://localhost:5000/video/524', type: 'video/mp4' }
  ]}
/>
