### ISSUE TITLE
minified / concatenated js

### ISSUE THREAD

**Issue by ioRekz** [CookPete/react-player#35]
Hi, I'm trying to build a minified version of react player so I can use it from clojurescript.

I'm not familiar with buildpack so I'm not sure how I should do it from the sources.

**Comment by CookPete** [comment]
Hey @ioRekz, see the [`library`](https://github.com/CookPete/react-player/tree/library) branch I just pushed with a [commit](https://github.com/CookPete/react-player/commit/11197a6f1868134a8404a9a2414b40a4e0887a0e) to try and solve this. You should be able to `npm run build:browser` that creates `dist/ReactPlayer.js`, which just does `var ReactPlayer = function(){...}`.

Does this do the trick? If so I will tidy it up a bit and merge it in. I'm not familiar with clojurescript so I'm not sure exactly what output you need.

**Comment by ioRekz** [comment]
I'm trying out today, that should be ok thx !
