### ISSUE TITLE
 a better way to obtain information about emitted errors?

### ISSUE THREAD

**Issue by iambumblehead** [CookPete/react-player#352]
I began logging errors emitted from react-player and do not find useful information there. Is there a better way to obtain information about emitted errors?

``` javascript
onError = e => console.log(e);
```

ex output,
```javascript
{
  bubbles: false,
  cancelBubble: false,
  cancelable: true,
  composed: false,
  currentTarget: null,
  defaultPrevented: false,
  eventPhase: 0,
  isTrusted: true,
  path: [ ... ],
  returnValue: true,
  srcElement: video#videochild,
  target: video#videochild,
  timeStamp: 3126.1000000013155,
  type: "error",
  __proto__: Event
}
```

**Comment by CookPete** [comment]
The error from a `<video>` should just be a standard [`MediaError`](https://developer.mozilla.org/en-US/docs/Web/API/MediaError) that has a `code` and a `message` that you can use.
