### ISSUE TITLE
onSeek callback not working on youtube player

### ISSUE THREAD

**Issue by jp3492** [CookPete/react-player#356]
It seems that the onSeek callback is working with vimeo and dailymotion in my app, but it is not working with youtube videos. Any idea how to solve that?

**Comment by CookPete** [comment]
The [YouTube player API](https://developers.google.com/youtube/iframe_api_reference) does not provide an `onSeek` event, so this isn't currently possible.

**Comment by AlvesJorge** [comment]
@cookpete Hi Pete! Can we include this detail on the main page? I struggled with this issue today and I had a hard time to find the reason why.
Thank you for your work with this project.

**Comment by taketec** [comment]
i got around this by getting the time using playerRef, the thing is playerRef was giving the time before the seek event was called, so i added a delay to the whole thing and this is how it looks
```
  const handle_seek = async(seconds) => {
    if (get_global_time() - lastUpdated.current > THRESH_IGNORANCE_SEEK ){
      let timestamp;
      await new Promise((resolve) => {
        setTimeout(() => {
          timestamp = playerRef.current.getCurrentTime();
          resolve();
        }, 50); // gives time before the seek event, thus the delay is needed
      });
      

        video_timestamp = seconds-0.05,//removing the delay 
}
```
