### ISSUE TITLE
how do i play from local storage?

### ISSUE THREAD

**Issue by rasselll** [CookPete/react-player#360]
as the title suggests.

**Comment by CookPete** [comment]
How are you planning on storing/retrieving media using localStorage? The player should play [Data URLs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs) and [Object URLs](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL) without any problems, both of which can be created from audio/video files. However, the general consensus is to [not use localStorage for storing media](https://stackoverflow.com/a/43816332).

**Comment by CookPete** [comment]
See [example jsFiddle](https://jsfiddle.net/0pn9avov/) for an example of playing a video using `URL.createObjectURL()`, which might help achieve what you are aiming for.
