### ISSUE TITLE
ReactPlayer Module causing issues on Internet Explorer Version 11

### ISSUE THREAD

**Issue by MRMTC** [CookPete/react-player#363]
Hi @CookPete,

Firstly, thanks for the great library!  I've incorporated it into my project, and its working like a charm :)

One issue I have picked up is that my code works correctly on Chrome and Firefox; but on Internet Explorer when I try load my site; I get the following errors in the console:
![image](https://user-images.githubusercontent.com/26508189/37892800-5d4c38e8-30d9-11e8-8b43-11662c726c5e.png)

The code lines its referring to above, are as follows.  Line 104 is where I include the "<ReactPlayer..." tag.
`  	render () {
		return (
			
			<div className="Audio">

				<Fab style={{ right: '20px', bottom: '20px' }}>
				  <FabButton>
				    ♫
				  </FabButton>
				  <FabActions>
				    <FabAction
				      className={`button button-royal glyphicon glyphicon-${volume_sign}`}
				      onClick={this.toggleMuted}
				      //tooltip="Mute Sound"
				      //place text below
				    ></FabAction> 
				    <FabAction
				      className={`button button-balanced glyphicon glyphicon-${play_sign}`}
				      onClick={this.playPause}
				      //tooltip="Play Sound"
				      //place text below
				    ></FabAction>
				  </FabActions>
				</Fab>

		    	{this.renderAudio()}  {/*Dont really need this, was just figuring out how it worked :)  This can be used if you need if/then loops in your returns*/}

			</div>

		)//end return
  	}//end render

  	renderAudio() {
		const { playing, autoplay, volume, muted, loop, playsinline, song } = this.state
				    
		return (
		    <div>
		    	{/*This module causes errors on IE?*/}
		  	
			    <ReactPlayer
					ref='reactPlayer'
					className='react-player'
					width='100%'
					height='100%'
					url= {song}
					playing={playing}
					loop={loop}
					volume={volume}
					muted={muted}	
					playsinline={playsinline}
					onEnded={this.onEnded}
					onError={e => console.log('onError', e)}
					fileConfig={{ attributes: {autoPlay: {autoplay} }}}
				/>
			</div>
		);
  	}//end renderAudio`

At the moment this seems to be a Browser issue because all works well on the other Browsers.  I saw a closed issue with respect to the YouTube playback, but it doesn't seem to be related?  Can you please have a look and advise?  I am currently using Internet Explorer V11.2068.14393.0 to test this.

Please let me know if you need any further information in order to assist.

Thanks.

Tony.

**Comment by BrooklynKing** [comment]
Hi @MRMTC . I'm just curious, how you adding ReactPlayer in your codebase? You take builded bundle and adding it with `<script>` or 
`import ReactPlayer from 'react-player'`?

**Comment by MRMTC** [comment]
Hi @CookPete,

Thanks for the quick feedback.  I currently import it using the following: 
`import ReactPlayer from 'react-player';`

Please let me know if you need any further information in order to assist.

Thanks.

**Comment by BrooklynKing** [comment]
@MRMTC source of problem - you don't have polyfills for some functionality, that used inside react-player. As it mentioned in README

> Polyfills
If you are using npm and need to support browsers without Promise you will need a Promise polyfill.
To support IE11 you will need to use babel-polyfill or a similar ES2015+ polyfill.

**Comment by MRMTC** [comment]
Thanks so much @BrooklynKing!  Apologies for missing that in the README.

I followed the guide here: https://mycodesmells.com/post/add-ie11-support-to-your-react-apps; and all is working well in IE now.

Thanks again.
