### ISSUE TITLE
suggestion: getInfo callback

### ISSUE THREAD

**Issue by ykorach** [CookPete/react-player#366]
I am using ReactPlayer to extract duration of video using "onDuration" in order to change field automatically in form in my website, I would like to extract another meta information of the video such as title description .
is it possible?

**Comment by CookPete** [comment]
It depends what type of URL you are playing. Each player SDK (listed in [the readme](https://github.com/CookPete/react-player#supported-media)) has a different set of methods and properties available. You can always use [`getInternalPlayer()`](https://github.com/CookPete/react-player#instance-methods) to get the raw SDK player of whatever URL is playing, and call methods on that (if such a method exists).
