### ISSUE TITLE
Not showing mp4 video on Android Chrome

### ISSUE THREAD

**Issue by JairAviles** [CookPete/react-player#368]
I am using this React component within a web app built with the Meteor.js framework.
I am defining it as follows 

```
<ReactPlayer
             url={[
                    {src: this.props.category.preview_file, type: 'video/mp4'},
              ]}
              config={{ file: { attributes: { autoPlay: true, controls: false } }}}
              playing={true}
              loop={true}
              width='100%'
              height='100%'
/>
```
The below code generates the following html tags, which is the expected result

```
<video preload="auto" loop autoplay style="width: 100%; height: 100%;">
    <source src = "/video/food.mp4" type="video/mp4"
</video>
```

It plays the video perfectly in Chrome using Desktop, laptops or even iOS devices (iPhone and iPad) as its shown in this gif ([http://g.recordit.co/kBcSNIillD.gif](http://g.recordit.co/kBcSNIillD.gif))

However, when I am using Chrome on Android devices it doesn't show the video even though it is rendered. Look on the Chrome Dev tools for remote devices debugging and it is not throwing any exception on the console, which is pretty weird.

![Remote device chrome debbuging](https://udemy-images.s3.amazonaws.com:443/redactor/raw/2018-04-03_17-07-15-7b814a91fa0ecee207a42918f1ce31cf.png)

Are there any suggestions for my problem, please?

PD. I visited your [demo page ](https://cookpete.com/react-player/) using Android Chrome and wasn't able to play any of those available media files (mp4, ogv, webm, mp3, Multiple)

**Comment by CookPete** [comment]
Unfortunately I don't have an Android device to try and debug this. A similar bug has been reported [here](https://bugs.chromium.org/p/chromium/issues/detail?id=299009). 

Even the [Video for Everybody test page](http://camendesign.co.uk/code/video_for_everybody/test.html) has a rather salty warning about Android:

>HTML5 video on Android is badly broken. Resolution support varies from one handset to the next (often just 480x360), the fallback image usually doesn’t show and the code requires special adjustments. The Android emulator is completely useless as it doesn’t represent any real hardware and does not play HTML5 video. THERE IS NO WAY TO TEST ON ANDROID WITHOUT A PHYSICAL PHONE. BLAME GOOGLE.

Do you get any errors or warnings in the console?

**Comment by CookPete** [comment]
Also see:
- https://stackoverflow.com/questions/39892713/google-chrome-does-not-play-html5-video-on-mobile
- https://www.broken-links.com/2010/07/08/making-html5-video-work-on-android-phones/

**Comment by JairAviles** [comment]
@CookPete thank you for your sooner response, seems to be a problem with Chrome and the decoders. I've tried to add the event listeners and still not playing video. Anyway, will try another type of video editing. For now, I will close this issue. Thank you so much.

**Comment by DSteinmann** [comment]
I just had a similar problem. In my case, the problem was the enabled data-saver in Chrome on Android. After switching that off, the video played as intended.
