### ISSUE TITLE
Players don't cleanup if loaded quickly

### ISSUE THREAD

**Issue by jasongornall** [CookPete/react-player#377]
Example: 
![](https://i.gyazo.com/182278d9130194320566463ecc108ca7.gif)

Just Click Test A then Test B

**Comment by jasongornall** [comment]
Youtube appears to explode too 

![](https://i.gyazo.com/d12b0b3ca06700b1d423f9f524511c04.gif)

**Comment by CookPete** [comment]
This should be sorted in `1.6.0`. A warning will be logged to the console if the loading of a URL is being deferred until the player is ready.
