### ISSUE TITLE
support to subtitle?

### ISSUE THREAD

**Issue by juanpablocs** [CookPete/react-player#378]
support to files .srt?

great job!

**Comment by CookPete** [comment]
There is a [readme section](https://github.com/CookPete/react-player#multiple-sources-and-tracks) regarding adding `<track>` elements when playing files.

**Comment by juanpablocs** [comment]
not support .srt files and remote files

**Comment by cookpete** [comment]
https://stackoverflow.com/questions/26968759/does-html5-video-support-srt-texttrack
