### ISSUE TITLE
FilePlayer getSecondsLoaded doesn't account for multiple buffered ranges

### ISSUE THREAD

**Issue by mryarbles** [CookPete/react-player#381]
getSecondsLoaded () {
    if (this.player.buffered.length === 0) return 0
return this.player.buffered.end(0)
  }

As soon as a user seeks that buffered object will have a second range.  The index 0 range will be fixed and the second range will now receive the updates, which leads to an incorrect or misleading value in progress events.

**Comment by CookPete** [comment]
Fixed by #380
