### ISSUE TITLE
Browser lags if seekTo called on multiple videos

### ISSUE THREAD

**Issue by basitsattar** [CookPete/react-player#384]
Hi
I am using react-player to play two videos and to keep them sync. I have refs to both players in an array and I call this function for seek

```
 onSeekMouseUp(e) {
        var value = parseFloat(e.target.value);
        this.setState({ seeking: false })
        this.players.map(function (player) {
            player.seekTo(value);
        })
    }


```
with requestAnimationFrame : 
 ```
onSeekMouseUp(e) {
        var value = parseFloat(e.target.value);
        this.setState({ seeking: false })
        this.players.map(function (player) {
            requestAnimationFrame(() => player.seekTo(value));
        })
    }
```

The problem is after I seek, the browser (this webpage) becomes unresponsive for few seconds until the videos have seeked and their onseek function is called. After that it becomes normal. Any solution to this?  Can seekTo function be called asynchronously or with combination of requestAnimationFrame etc.?  Any solution to this?

**Comment by CookPete** [comment]
What URLs are you trying to play/seek? I've written a very simple jsFiddle to try and reproduce the issue but I'm seeing no lag at all when calling `seekTo` on several videos at once: https://jsfiddle.net/6ebqr9m1/

**Comment by basitsattar** [comment]
I don't know why but the loop was causing the problem. I was iterating over players object. I removed the array and its working fine now. Thanks a lot :). This is my code now

```
onSeekMouseUp(e) {
        var value = parseFloat(e.target.value);
        this.setState({ seeking: false })
        this.players[0].seekTo(value);
        this.players[1].seekTo(value);
    }
 
```

**Comment by CookPete** [comment]
Not sure why the loop would cause a problem, but glad you sorted it!
