### ISSUE TITLE
Set Fallback Image

### ISSUE THREAD

**Issue by DSteinmann** [CookPete/react-player#385]
Hi, 

thanks for this project :) I'm using it to display a autoplaying background image on my site. The problem is, as I found out, that the video will not even show up if the data-saver Option in Chrome on Android is enabled. For this case, I'd like to add a Img within the src Array to display that to those users, who enabled the feature. 

Is there a possibility to do that? 

Thanks for your work!

**Comment by CookPete** [comment]
>I'd like to add a Img within the src Array to display that to those users, who enabled the feature.

There is a [section in the readme](https://github.com/CookPete/react-player#multiple-sources-and-tracks) about using multiple file sources. Does this help? If it fixes it for Android with data-saver mode, it would be good to add to the readme as it seems people are starting to have this problem more: https://github.com/CookPete/react-player/issues/368#issuecomment-383297492

**Comment by CookPete** [comment]
Hopefully the multiple sources support (and possibly [using the `poster` attribute](https://github.com/CookPete/react-player/issues/301)) will do the trick.
