### ISSUE TITLE
seekTo() Youtube bug 	

### ISSUE THREAD

**Issue by bennylin77** [CookPete/react-player#386]
Hi,

I set playing attribute to false. The video will autoplay after calling the seekTo(amount) method, even when the playing attribute is still false. This issue happened when I use Youtube URL.

**Comment by CookPete** [comment]
Do you have an example repo or jsFiddle where this is happening? The [demo page](http://cookpete.com/react-player/) does not play after seeking when a youtube video is paused.

**Comment by CookPete** [comment]
Feel free to reopen with an example of this happening.

**Comment by Tek123456** [comment]
Hi,

have the exact same issue (also happens with older versions) and yes, it is working fine on the demo page, but I don‘t know why it works there. 
Here you have an example: https://codesandbox.io/s/0xryy1xk6l

After clicking on the "SeekTo" below the video it jumps to the specified position and starts.
 
Thanks for your help!

**Comment by CookPete** [comment]
See https://github.com/CookPete/react-player/issues/601
