### ISSUE TITLE
HLS library sometime fails to load.

### ISSUE THREAD

**Issue by mryarbles** [CookPete/react-player#387]
One of our Devs in Ukraine just reported that the hls library often fails to load causing player failure. http://recordit.co/yCiANSRO1V

I'm going to fix the issue by importing hls from npm instead of loading it from CDN. 

Let me know if you'd like me to create PR with my changes.

**Comment by CookPete** [comment]
>I'm going to fix the issue by importing hls from npm instead of loading it from CDN.

Importing from npm would include the entire hls.js library for anyone using ReactPlayer, even if they never play HLS streams. 

Perhaps better would to be able to override the `HLS_SDK_URL` in the FilePlayer config, so that you could host it locally, or pick a more reliable CDN?

**Comment by mryarbles** [comment]
Yeah, I thought of that after posting.  I'll figure out a better solution and update when I have time.

**Comment by CookPete** [comment]
Would be good to eventually know the reason for this. It's not ideal if the external libraries are failing to load under certain conditions.
