### ISSUE TITLE
Player does not expose OnFullScreen event.

### ISSUE THREAD

**Issue by yuchuan1** [CookPete/react-player#390]
Player does not expose OnFullScreen event.

**Comment by CookPete** [comment]
What URL are you playing? We can only hook into events that the relevant SDK provides. The [YouTube player SDK](https://developers.google.com/youtube/iframe_api_reference#Events), for example, does not provide an event when going into fullscreen mode.

You may also want to check out https://github.com/rafrex/fscreen, but I have no idea if it'll work for each player.
