### ISSUE TITLE
When mounting multiple players, multiple load requests are made in parallel resulting in duplicate script copies

### ISSUE THREAD

**Issue by arwinsardana** [CookPete/react-player#391]
Mounting 2 or more instances of the player at once results in multiple calls to the `load` and `getSDK` functions and ultimately results in multiple copies of the same `<script>` in the head. I was wondering if this could be fixed to avoid duplicate scripts in the document head? 

https://jsfiddle.net/e6w3rtj1/376/

![image](https://user-images.githubusercontent.com/16921577/39488574-becc3436-4d50-11e8-9332-9e16790cc9c8.png)

**Comment by CookPete** [comment]
This should be sorted in `1.6.0`
