### ISSUE TITLE
Content Security Policy guidelines

### ISSUE THREAD

**Issue by byronanderson** [CookPete/react-player#392]
I noticed that this library (directly or indirectly, not sure which) will load external javascript (on www.youtube.com and s.ytimg.com, for example) to support some video formats.  I am having difficulty quantifying *all* the places that this code can come from, which would be nice to have in order to have a `Content-Security-Policy` header.

Do you happen to have a list of all the locations from which video player scripts can be loaded?

**Comment by CookPete** [comment]
[Searching for `SDK_URL`](https://github.com/CookPete/react-player/search?utf8=%E2%9C%93&q=SDK_URL&type=) should get you started with all the player SDKs that are loaded. There's also the `hls.js` and `dash.js` SDKs loaded by [FilePlayer](https://github.com/CookPete/react-player/blob/master/src/players/FilePlayer.js). However, there's no way to know what _other_ resources are loaded from other domains by those SDKs (like `s.ytimg.com`) without just playing the videos and seeing what domains are hit.
