### ISSUE TITLE
Override Video Player Controls?

### ISSUE THREAD

**Issue by MDrooker** [CookPete/react-player#394]
Does anyone have a good example/existing library that overrides the video player controls?

We need to drop bookmarks on the timeline scrubber to show "things of interest" in a video.

**Comment by CookPete** [comment]
The [source for the demo page](https://github.com/CookPete/react-player/blob/master/src/demo/App.js) should be a good starting point for external controls, including a timeline scrubber. Judging by the lack of response, I guess no-one has anything they are willing to share. One day I'd like to put together a more robust example with some proper custom controls.

**Comment by MDrooker** [comment]
@CookPete Thanks for the response.  We are creating a reference app todo the ask.
