### ISSUE TITLE
Error report  and previous video displayed 

### ISSUE THREAD

**Issue by sbroadhurst** [CookPete/react-player#399]
i have a home screen with mutiple videos that when clicked opens up a new route that displays the video with other information. if you go back to home screen then select another video it displays the previously selected video and i get this error report. How would i go about fixing this? any ideas? 

refreshing the page loads the correct video

![error](https://user-images.githubusercontent.com/34989416/40189910-8ad50cf2-59cb-11e8-85f3-a466949b5aaa.png)

**Comment by EugeneHerasymchuk** [comment]
Provide some jsfiddle examples for this issue. It's quite hard to reproduce it

**Comment by CookPete** [comment]
@sbroadhurst Feel free to reopen with more information, an example repo or a jsFiddle.
