### ISSUE TITLE
customize player skin

### ISSUE THREAD

**Issue by asela-wijesinghe** [CookPete/react-player#400]
My player is like this at the moment after using vimeo url pattern "https://player.vimeo.com/external/sample.mp4"

![image](https://user-images.githubusercontent.com/23404276/40193226-5d876bce-5a24-11e8-8e75-a052723b36a4.png)

I am trying to style the control container with some custom icons and css.Since this repo is mainly concentrated on the embed player, instructions on this html5 player is hard to find.So can you kindly point me what should be my steps to create a custom player and integrate here with the minimal effort or customize the styling of this player?

**Comment by CookPete** [comment]
There is no out-of-the-box custom controls for ReactPlayer (yet). The HTML5 player is simply styled using the native controls of each browser. The [demo app](https://github.com/CookPete/react-player/blob/master/src/demo/App.js) has a basic example of what is possible in terms of external controls, including a range input for seeking and volume control. It is simply a case of using CSS to overlay the buttons/inputs on top of the video in the correct position, and including the relevant icons.
