### ISSUE TITLE
updated to latest version 1.6.1, player autoplays hls, even when using `playing={false}` attribute

### ISSUE THREAD

**Issue by iambumblehead** [CookPete/react-player#405]
updated to latest version 1.6.1, player autoplays hls, even when using `playing={false}` attribute

**Comment by iambumblehead** [comment]
version 1.5.0 seems to be the last version that respects the playing attribute

**Comment by kumarharsh** [comment]
It's Chrome 66 which is blocking autoplay. Autoplay works for v1.6.1 in Firefox, etc.

https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

**Comment by CookPete** [comment]
@kumarharsh I think the problem is that it _is_ autoplaying, not that it _is not_ autoplaying.

**Comment by kumarharsh** [comment]
oh, I see. Sorry for the misunderstanding. But still, it seems to be working as expected for me (try changing the props in the fiddle above).

**Comment by CookPete** [comment]
@iambumblehead do you have a jsFiddle or example URL where this is happening? What browser are you using? This doesn't happen on the [demo app](http://cookpete.com/react-player/) on Chrome. Click `Pause` to set playing to false, then `HLS (m3u8)`, and the video does not play.

**Comment by iambumblehead** [comment]
@CookPete unfortunately I don't have a jsFiddle and I don't believe the demo app can be used to test this scenario. The right test scenario would load using the react-player component with an hls video source and playing={false}

**Comment by CookPete** [comment]
@iambumblehead How about https://jsfiddle.net/xymyj0e1/ – this doesn't play for me on any browser.

**Comment by iambumblehead** [comment]
@CookPete the jsfiddle link doesn't play for me either. I'll paste this in to my own application and see if I can get to the bottom of things now.

**Comment by iambumblehead** [comment]
I'm using firefox and if I paste that into my application using 1.6.1 react-player, the video autoplays 
```jsx
        <ReactPlayer
          url='https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8'
          className='react-player'
          playing={false}
          width='100%'
          height='100%' />
```

I don't know the demo page is not autoplaying

**Comment by iambumblehead** [comment]
The jsfiddle page uses react-player sources here: https://unpkg.com/react-player@1.0.0-beta.5/dist/ReactPlayer.js

Specifcally, a react-player version greater than 1.5.0 should be used

**Comment by CookPete** [comment]
Good spot.

It still doesn't autoplay for me when using `1.6.1`: https://jsfiddle.net/6fo1cn5x/

**Comment by iambumblehead** [comment]
strange. The demo page does not autoplay when I load it. Locally, when I use 1.6.1 and paste the react-player component jsx from the demo page into my own app it does autoplay. I'm not seeing any scripted play calls in my own sources and will try to narrow things down further by remove everything else from my app.

**Comment by iambumblehead** [comment]
It autoplays in both firefox and chrome and this is very strange. I notice that when the <video> element appears it always shows autoplay="false". I believe autoplay must not be defined unless autoplay is truthy
```
 autoplay: autoplay || undefined,
```
The <video> element in the demo page _does not_ have an autoplay attribute

**Comment by jasongornall** [comment]
I'm seeing this myself on youtube
