### ISSUE TITLE
User agent = iOS playBackRate is not working

### ISSUE THREAD

**Issue by uchidayuma** [CookPete/react-player#406]
It is a problem with react-dom.
If the user agent is iOS, the playback rate can not be changed.
Is this a bug? Is there a way to avoid it?

I verified that the width of the device is irrelevant, it seems to be a user agent problem.
Browser is safari and chrome.

**Comment by CookPete** [comment]
What URL are you trying to play? It may just be that the player API does not support playback rate, or HTML5 video playback rate is not supported on iOS.

**Comment by uchidayuma** [comment]
@CookPete
comment thanks.
I play youtube & vimeo .
Can playback rate support desktop & youtube only ?

**Comment by CookPete** [comment]
According to [this StackOverflow reply](https://stackoverflow.com/questions/45816248/playback-rate-not-working-on-ios-youtube-ytplayerview#comment78614487_45816248), it looks like the YT player on iOS simply doesn't support changing the playback rate.

The Vimeo player does not support playback rate at all.

**Comment by hoducha** [comment]
It's possible to change the playback rate of an HTML5 video directly. Please have a look at this Chrome extension that works for most sites using HTML5 video: https://github.com/igrigorik/videospeed
