### ISSUE TITLE
Feature request: pass back player instance in event callbacks

### ISSUE THREAD

**Issue by matthew-dean** [CookPete/react-player#407]
So, in our app, unfortunately, we need to wrap components with https://github.com/faceyspacey/react-universal-component, including `react-player`. Unfortunately because of the way React works, setting a `ref` property to a universal-wrapped component does not pass the ref to the underlying component like it does other props.

This means that we can't ever attach a reference to `react-player` (without forking/rewriting the library). What would be nice is if `onReady()` / `onPlay()` callbacks, etc passed back the player instance, so that we can use instance methods. Without any sort of callback mechanism, none of the instance methods are callable.

By the way, this isn't specific to `react-universal-component`, but will be the case with any higher-order component that wraps `react-player`.

**Comment by CookPete** [comment]
Fixed in `1.6.2`. Sorry for the delay @matthew-dean!

**Comment by matthew-dean** [comment]
@CookPete No worries, thanks so much!
