### ISSUE TITLE
Mobile-friendly?

### ISSUE THREAD

**Issue by nathanandersen** [CookPete/react-player#41]
On mobile, the ReactPlayer just buffers and buffers and buffers and will not play YouTube videos. Is this a function of mobile or of the youtube api?

**Comment by CookPete** [comment]
Unfortunately ReactPlayer is at the mercy of the [YouTube iFrame API](https://developers.google.com/youtube/iframe_api_reference#Mobile_considerations), so if that doesn't work on a particular browser or device, then ReactPlayer won't work either. 

I do need to add a note that it isn't fully supported on mobile browsers, as @mandarinx pointed out [here](https://github.com/CookPete/react-player/issues/39#issuecomment-189244562), although it is usually OS-level issues out of our control (eg no autoplay or inline playback on iOS)
