### ISSUE TITLE
Not firing `onError` properly when `playing` (autoplay) is true with Vimeo

### ISSUE THREAD

**Issue by Silviu-Marian** [CookPete/react-player#411]
Hey there. Lovely work

I have a problem with this video https://player.vimeo.com/video/196716639

Code
```
<Player 
    url="https://vimeo.com/video/196716639" 
    playing 
    onError={() => console.warn('aaaa')} />
```

should warn. it doesn't. instead, if you try to pause and play it again, only then you get the following

```
player.js:2 Uncaught (in promise) Error: The video is private.
    at player.js:2
    at Array.forEach (<anonymous>)
    at y (player.js:2)
    at u (player.js:2)
```

I'm also tracking the problem here

https://github.com/vimeo/player.js/issues/165

Not sure at this point if it's a problem with `vimeo` or `react-player`

**Comment by CookPete** [comment]
This definitely seems like a problem with the Vimeo Player API. ReactPlayer is already doing the `ready().catch()` suggestion from https://github.com/vimeo/player.js/issues/165#issuecomment-333454988

https://github.com/CookPete/react-player/blob/cfc0e2c9f510de6614d08f8f571b3de21bac1043/src/players/Vimeo.js#L35-L39

As well as binding to the `error` event:

https://github.com/CookPete/react-player/blob/cfc0e2c9f510de6614d08f8f571b3de21bac1043/src/players/Vimeo.js#L50

**Comment by CookPete** [comment]
>They fixed it yesterday. Can we update to 2.6.2 please?

@Silviu-Marian This should happen automatically. The latest Vimeo SDK is always loaded.
