### ISSUE TITLE
A few instanceof errors on IE 11 and Safari

### ISSUE THREAD

**Issue by dancrew32** [CookPete/react-player#415]
First off, thanks for making this great player!

Getting a few error logs at my ErrorBoundary around `ReactPlayer` in IE 11 and Safari/Safari Mobile/Chrome for iOS.

Current version in package.json is `"react-player": "^1.6.1"`

IE 11:
```Invalid operand to 'instanceof': Function expected```

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.1.2 Safari/603.3.8
Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_3 like Mac OS X) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.0 Mobile/14G60 Safari/602.1

```Right hand side of instanceof is not an object```

While attempting to load an `.mp4` file, I believe this error comes from this `MediaStream` `instanceof` check here:

https://github.com/CookPete/react-player/blob/9618272e6e4b518e493d3130b96dd2ebeb97b506/src/players/FilePlayer.js#L17-L19

I'll try and do a bit more debugging, but was wondering if you've experienced this on similar platforms.

Should I make a PR to chain another `typeof window.MediaStream !== 'undefined'` before the `instanceof` check?

**Comment by jhk115** [comment]
Having the same issue. But for me it's iOS 10. Works fine with iOS 11...

**Comment by CookPete** [comment]
9618272e6e4b518e493d3130b96dd2ebeb97b506 should fix this but I haven't published a new version yet. I will do shortly.

**Comment by dancrew32** [comment]
Thanks!
