### ISSUE TITLE
Add named exports for individual players

### ISSUE THREAD

**Issue by seaneking** [CookPete/react-player#421]
Minor thing, but it'd be nice to add named exports for each individual player to the main entrypoint, so you could consume them through ES6 destructuring rather than explicitly importing the source file

```js
import { Vimeo } from 'react-player'
```

Would be an easy and non-breaking change to add, along the lines of tacking this onto `ReactPlayer.js`

```js
export { default as Vimeo } from './players/Vimeo'
// Repeat for each player
```

**Comment by CookPete** [comment]
@seaneking This is an interesting suggestion, but I'm trying to see why would someone do 

```js
import { Vimeo } from 'react-player'
```

and include the whole library into their bundle, when they can already import a single player:

```js
import Vimeo from 'react-player/lib/players/Vimeo'
```

which includes only the code for that player.

**Comment by seaneking** [comment]
Because (using any modern bundler) that doesn't import the whole library, just the module you've specified. That's what destructuring does (`{ ... }`)

**Comment by CookPete** [comment]
The issue is that `import { Vimeo } from 'react-player'` will import `ReactPlayer.js`, which imports all players:

https://github.com/CookPete/react-player/blob/7b2784d7d3a4a62b17fa8b46f62a9741e4d97c3d/src/ReactPlayer.js#L5

Is tree-shaking good enough these days to not import all the players when doing it like this?

**Comment by seaneking** [comment]
Yep AFAIK, because you're only importing that named module (and its direct/used deps). Could include your whole library into one file, consuming just one function should tree shake the rest out. 

Rollup (and pretty sure Webpack 2+) can tree shake out unused functions and consts from within a module, so wouldn't have any probs here.

**Comment by seaneking** [comment]
That said it's hardly a big deal either way, just some  light syntax sugar, so 🤷‍♂️

**Comment by CookPete** [comment]
@seaneking Would this still work considering the source code would get [compiled](https://github.com/CookPete/react-player/blob/7b2784d7d3a4a62b17fa8b46f62a9741e4d97c3d/package.json#L14) into something like:

```js
var _YouTube = require('./players/YouTube');

Object.defineProperty(exports, 'YouTube', {
  enumerable: true,
  get: function get() {
    return _interopRequireDefault(_YouTube)['default'];
  }
});

var _SoundCloud = require('./players/SoundCloud');

Object.defineProperty(exports, 'SoundCloud', {
  enumerable: true,
  get: function get() {
    return _interopRequireDefault(_SoundCloud)['default'];
  }
});
```

as opposed to `export` statements?
