### ISSUE TITLE
m3u8 from vimeo doesnt load to the player

### ISSUE THREAD

**Issue by asela-wijesinghe** [CookPete/react-player#423]
i am adding videos to the player with the following structure https://player.vimeo.com/external/%3Cvideo_id%3E.m3u8?s=%3Csecret%3E&oauth2_token_id=%3Coauth_key%3E, but i get an error on fetching the video eventhough same URL 100% working on **HL.js demo page**  with correct oauths and keys, but in react-player appears this error

![image](https://user-images.githubusercontent.com/23404276/41363210-fdc4a0ca-6f50-11e8-9a1a-61345e830ae6.png)

**Comment by CookPete** [comment]
I think the fact that `player.vimeo.com` is in the URL means the Vimeo player is trying to play it rather than the FilePlayer.

Have you tried importing the standalone `FilePlayer` and using that instead?

```jsx
import FilePlayer from 'react-player/lib/players/FilePlayer'

<FilePlayer url='https://player.vimeo.com/...' />
```

**Comment by asela-wijesinghe** [comment]
Yes it is working thanks <3
