### ISSUE TITLE
Vimeo events are not fired anymore

### ISSUE THREAD

**Issue by marcusgraf** [CookPete/react-player#424]
I dont get any events from the videoplayer anymore. 

The videos are included from Vimeo but the onProgress and the onEnded event is not fired anymore.

I also checked the vimeo api docs but i can see a change regarding that. 

I also havnt changed the video implementation so far:

` <VideoPlayer
            width="100%"
            height="100%"
            controls
            onProgress={this.handleProgress}
            onEnded={this.handleVideoEnded}
            url={videoId}
            style={{backgroundColor: `#fff`}}
          />`

**Comment by CookPete** [comment]
@marcusgraf What URL are you trying to play?

**Comment by CookPete** [comment]
@marcusgraf If you can provide an example or jsFiddle where this happens, feel free to re-open this issue. Vimeo events appear to be working correctly under normal circumstances.

**Comment by bradstiff** [comment]
I have the same issue. The onEnded event doesn't fire.
