### ISSUE TITLE
Height is not working

### ISSUE THREAD

**Issue by sachiner** [CookPete/react-player#425]
Height for react player is not working 
I am using the video height as 
`<ReactPlayer url="https://www.facebook.com/PrinceEa/videos/10156905097874769/UzpfSTEwMDAwMDM5NzE2NjM4MjoxODc0ODE5NDUyNTQxMjc1/" height='360px' width='640px'  controls />`  
But the size of the player exceeds according to size of video 
And if I use another video from facebook [https://www.facebook.com/nickcannonwildnout/videos/1798746903548304/](url)
it is working fine without doing anything. 

How can a get a video fitted into the same player container height i.e 360px and width 640px

![screen shot 2018-06-20 at 3 16 08 pm](https://user-images.githubusercontent.com/24804734/41651030-1b06024a-749d-11e8-8b5a-305ac49be908.png)
![screen shot 2018-06-20 at 3 17 06 pm](https://user-images.githubusercontent.com/24804734/41651031-1b55bba0-749d-11e8-9b63-a7344fc48160.png)

**Comment by CookPete** [comment]
The Facebook video player seems to [not support a height parameter](https://developers.facebook.com/docs/plugins/embedded-video-player#settings). The player window will always match the aspect ratio of the source video, according to the width passed in.
