### ISSUE TITLE
Who faced such a mistake? Wistia player

### ISSUE THREAD

**Issue by Xurma2** [CookPete/react-player#426]
```
E-v1.js:12 Could not find element with ID "wistia-1hajzzqeiv-1" in DOM. 
Failed to initialize video "ve7pzy0d3y".
E-v1.js:12 Error: Could not find element with ID "wistia-1hajzzqeiv-1" in DOM. 
Failed to initialize video "ve7pzy0d3y".
```

**Comment by CookPete** [comment]
@Xurma2 do you have any more information about how you get this error? It looks like something is affecting the DOM before the Wistia player API can create a video.

**Comment by c-adeshmukh** [comment]
I am also getting same issue @cookpete 
                  <ReactPlayer
                    className="thumbnail wistia_embed wistia_async_e4a27b971d popover=true popoverContent=link popoverOverlayOpacity=0.8 popoverSize=640x360 popoverAnimateThumbnail=true"
                    url="https://home.wistia.com/medias/e4a27b971d"
                    light={temp}
                    playing
                    controls
                  />
                  I have used like this could you help me to solve this.

**Comment by cookpete** [comment]
@c-adeshmukh Your exact code works fine for me in jsFiddle, although the behaviour is a bit strange.

https://jsfiddle.net/y163pvda/

![image](https://user-images.githubusercontent.com/1926029/102534897-5f6eb280-409f-11eb-88b4-8565615cb61e.png)

**Comment by c-adeshmukh** [comment]
@cookpete thank you for a quick reply. Is there any way to pass wistia_async_Id as an option or props.
