### ISSUE TITLE
Can't test with Enzyme: "'instanceof' is not an object"

### ISSUE THREAD

**Issue by mileshenrichs** [CookPete/react-player#427]
My experience using react-player has been very pleasant so far, but I've run into a problem trying to test a component that contains `<FilePlayer />`.  Here is my component structure:

```
class Player extends Component {

        <div className="Player__container">
          <FilePlayer 
            ref={node => this.reactPlayer = node}
            className="Player__ReactPlayer"
            url="https://archive.org/download/BigBuckBunny_124/Content/big_buck_bunny_720p_surround.mp4"
            ...
          />
        </div>
}
```

Here is my test (it's just one line using Enzyme's `mount()`):

```
    it('mounts', () => {
      const wrapper = mount(<Player />);
    });
```

And here is the error it returns in the test console (`npm test`):

```
TypeError: Right-hand side of 'instanceof' is not an object
   at Function.canPlay (node_modules/react-player/lib/players/FilePlayer.js:75:11)
   at SinglePlayer.render (node_modules/react-player/lib/singlePlayer.js:87:27)
   ...
```

**Comment by CookPete** [comment]
`FilePlayer` assumes there is a `window` object with a `MediaStream` object and `URL.createObjectURL` function. Note in the tests for FilePlayer that I've added some basic mocks for this:

https://github.com/CookPete/react-player/blob/488f82da421ac9a27c2e52137767d19cc7f47a3e/test/players/FilePlayer.js#L12-L18

I imagine you'll need to do a similar thing in your tests.

**Comment by mileshenrichs** [comment]
Alright, thanks for the reply!
