### ISSUE TITLE
Vimeo autoplay fails with new policy

### ISSUE THREAD

**Issue by pikilon** [CookPete/react-player#428]
The iframe generated by Vimeo player doesn't have `allow="autoplay"` so or you mute it or autoplay will fail.
In the other hand youtube's one works with this attribute.
I've been diggin a little bit in the code and Vimeo Player allows to ref an Iframe itlself so it could be a good way of control this attribute **before** put it into the DOM (if you do it later it will fail to autoplay too)

**Comment by CookPete** [comment]
The problem with using a rendered iframe is that Vimeo shared URLs do not work (ie `https://vimeo.com/yannickcerrutti/annecydroneinmotion`) whereas generating a fresh embed lets you use any Vimeo URL. The "proper" solution is to fix the Vimeo API, which I see you've created an [issue for](https://github.com/vimeo/player.js/issues/271) already. I think we just need to wait for Vimeo to fix it.

Also, it's worth noting that [recent versions of Chrome will not autoplay Vimeo videos anyway.](https://github.com/CookPete/react-player/issues/395)
