### ISSUE TITLE
Customize FilePlayer

### ISSUE THREAD

**Issue by asela-wijesinghe** [CookPete/react-player#429]
I am trying to add a video quality control button to the  **FilePlayer** 
  `import FilePlayer from "react-player/lib/players/FilePlayer";`.This is playing a **.m3u8** file yet i am not getting a control to change the quality in the player customize the skin a little.any areas to focus?

**Comment by CookPete** [comment]
ReactPlayer doesn't provide any standard controls (yet). The default player controls show you pass in `controls={true}`. In the case of FilePlayer it's just the standard browser controls for HTML5 video, which don't support quality switching.

You may be better off using `video.js` or something similar. They have an example of a quality switcher: https://kmoskwiak.github.io/videojs-resolution-switcher/
