### ISSUE TITLE
Custom URL not loading the first time on mobile

### ISSUE THREAD

**Issue by Conrad777** [CookPete/react-player#43]
Hey,

I've noticed some strange behaviour when trying to load a custom .mp3 on mobile. All the state behaviour obviously changes correctly, but the audio clip doesn't play(load) the first time. When I press pause and play again then it works. 

I've spent a good 2 hours trying to trouble shoot the issue in my app when I decided to check if it does the same on your demo... And it does.

Do you have any ideas as to why this could happen? It works fine on desktop browsers, but does has this bug on iOS Safari and Chrome as well as Android Chrome.

Thanks.

**Comment by CookPete** [comment]
Hey @Conrad777,

Autoplay on mobile (at least on iOS Safari) requires user interaction to load properly. This is an OS-level restriction to prevent unwanted downloads:

>Warning: To prevent unsolicited downloads over cellular networks at the user’s expense, embedded media cannot be played automatically in Safari on iOS—the user always initiates playback.

From [Apple's documentation on media tags](https://developer.apple.com/library/safari/documentation/AudioVideo/Conceptual/Using_HTML5_Audio_Video/AudioandVideoTagBasics/AudioandVideoTagBasics.html#//apple_ref/doc/uid/TP40009523-CH2-SW8).

The reason it works after pausing is that the subsequent interaction to play is done by the user. Maybe a possible solution would be to initialise the player with `playing={false}`, and then settings `playing={true}` once the user has actually tapped something?

This weirdness is covered in the readme for `ReactPlayer` under [mobile considerations](https://github.com/CookPete/react-player#mobile-considerations).

**Comment by Conrad777** [comment]
Awesome, thanks for letting me know!! I guess I should've read the manual first.

**Comment by MRMTC** [comment]
Hi @Conrad777,

Did you ever find a solution to get it to play without the user having to make an interaction on the mobile device?  I managed to get it to work, but only on user input as suggested by @CookPete.

Thanks.

**Comment by Conrad777** [comment]
Hey @MRMTC, it's been way to long ago to remember to be honest. Sorry for not being useful to you.

**Comment by CookPete** [comment]
@MRMTC There was a solution posted here a while back: https://github.com/CookPete/react-player/issues/76#issuecomment-228393613 that apparently works on Android and iOS 9.3.x, although every iOS release tends to include an update to prevent any autoplay hacks from working, so this may no longer work.

**Comment by MRMTC** [comment]
Thanks for the feedback @Conrad777 and @CookPete.  Will check out the link above to see the solution works for me.
