### ISSUE TITLE
Trying to mute currently playing vimeo videos doesn't work in iOS

### ISSUE THREAD

**Issue by AceBunny** [CookPete/react-player#432]
Hi, I have a problem with videos from vimeo in iOS devices.

I'm trying to change a muted state on or off in a custom control and pass it through props in the ReactPlayer while the video is playing, but it doesn't seems to work only for iOS devices and vimeo videos. Videos from YouTube or other sources work nicely in iOS and different devices without iOS and with vimeo videos work correctly.

I can replicate this in the demos you provide, setting the Muted checkbox on or off while the vimeo video is playing in a iOS device doesn't have any effect on the sound.

**Comment by jmgirao** [comment]
Hi! I have same problem!
Please help!

**Comment by pemasora** [comment]
Same problem :( 

Can someone help please????

**Comment by CookPete** [comment]
Sorry guys. The [Vimeo player API](https://github.com/vimeo/player.js) does not have a method for muting/unmuting a player, and so ReactPlayer uses `setVolume` as a fallback. The problem with this is:

>Most mobile devices (including iOS and Android) do not support setting the volume because the volume is controlled at the system level. An error will not be triggered in that situation.

https://github.com/vimeo/player.js#setvolumevolume-number-promisenumber-rangeerrorerror

There is an issue for this here: https://github.com/vimeo/player.js/issues/236 – not much more we can do I'm afraid.

**Comment by aproni34f** [comment]
Is this a joke? You can set volume with html5 video and with youtube player no problem. How its possible that vimeo player has such bugs in the code?

**Comment by iaheck** [comment]
hello @cookpete! thank you so much for your repo. I've seen that the issue is solved in the Vimeo Player API but it's not here. Is there a way for us to use `setVolume(0)` directly with react player? thank you and have a great day!

**Comment by LucidNinja** [comment]
Is this not it? https://github.com/vimeo/player.js#setmutedmuted-boolean-promiseboolean-error

**Comment by LucidNinja** [comment]
Hey @cookpete - any chance we can reopen this issue - the Vimeo player API does now support mute/unmute, as described above. I have also tested this here: https://codepen.io/LucidNinja/pen/RwYRmJM, and it works on iOS. Thanks!

**Comment by LucidNinja** [comment]
@cookpete - I have created a PR for this here: https://github.com/cookpete/react-player/pull/1588. This has been tested and works in iOS.
