### ISSUE TITLE
Start player from specific time

### ISSUE THREAD

**Issue by msbir** [CookPete/react-player#433]
Hey, Great work!

How can I make the player start from a specific time?

Thanks =)

**Comment by CookPete** [comment]
See https://github.com/CookPete/react-player/issues/115, although the config example is outdated:

``` js
<ReactPlayer
  url='https://youtu.be/qv6UVOQ0F44'
  config={{ 
    youtube: {
      playerVars: {
        start: 33
      }
    }
  }}
/>
```

**Comment by msbir** [comment]
Thank you!

**Comment by CookPete** [comment]
No problem!

**Comment by worksintriton** [comment]
how can i write the config for  a normal file?

**Comment by wuahi** [comment]
> how can i write the config for a normal file?

I am wondering about this too. Tried a couple of ways, for example seeking when onReady, but the player just resets played to zero.

**Comment by breth84** [comment]
for me as well, how I can set a starting time? seeking onStart and onReady will be start from 0 once is loaded

Thanks

**Comment by breth84** [comment]
I've found a solution that may help someone using media fragment

**Media Fragments**
Adding a media fragment to the media URL, you can specify the exact portion you want to play. To add a media fragment, you simply add #t=[start_time][,end_time] to the media URL

<ReactPlayer
 ref={this.ref}
 url={`${source}#t=${this.state.duration * this.props.played}`}
/>

I'm passing **played** as prop to the player component, that I retrieve from the db stored

**Comment by breth84** [comment]
> > how can i write the config for a normal file?
> 
> I am wondering about this too. Tried a couple of ways, for example seeking when onReady, but the player just resets played to zero.

I've found a solution that may help someone using media fragment

Media Fragments
Adding a media fragment to the media URL, you can specify the exact portion you want to play. To add a media fragment, you simply add #t=[start_time][,end_time] to the media URL

<ReactPlayer
ref={this.ref}
url={${source}#t=${this.state.duration * this.props.played}}
/>

I'm passing played as prop to the player component, that I retrieve from the db stored

**Comment by MdMehedi-Hasan** [comment]
hey,

**Comment by MdMehedi-Hasan** [comment]
hey,
what is the configuration to start the video at a specific time on Vimeo?
