### ISSUE TITLE
Not able to play player in full-screen?

### ISSUE THREAD

**Issue by daiict218** [CookPete/react-player#436]
Hi, I'm using `react-player` in my project and I'm facing issue when I try to play video in full-screen. When I try to full-screen the player, it does work but it gets returned to the previous size. What can be possible causes for this?

**Comment by CookPete** [comment]
@daiict218 do you have any example code or a repo where this is happening?

**Comment by bradywestveer** [comment]
Are you trying to fullscreen the player element you are rendering to or using the platform APIs to go fullscreen?

**Comment by CookPete** [comment]
I'm gonna close this off due to lack of further information from @daiict218. The fullscreen example in the app works, and any native player fullscreen problems is most likely outside of ReactPlayer's control.
