### ISSUE TITLE
Youtube video starts playing after seekTo 

### ISSUE THREAD

**Issue by Tek123456** [CookPete/react-player#437]
#386 
Hi,

sorry to open this issue here, I thought by adding a comment to the other one it would reopen it.
About the problem:
When I execute seekTo on a player that has a Youtube video loaded, the video starts even though playing is false. Strangely it is not happening on the demo page.
Here you have an example: https://codesandbox.io/s/0xryy1xk6l

After clicking on the "SeekTo" below the video it jumps to the specified position and starts.

Thanks for your help!

**Comment by vheuken** [comment]
@Tek123456 I found a solution in my project: `config={{ youtube: { preload: true } }}`
