### ISSUE TITLE
Recommended CSP Settings

### ISSUE THREAD

**Issue by oyeanuj** [CookPete/react-player#439]
Hi everyone! I was going to add a [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) profile to my app, and realized that each of the supported service will probably have a few settings that will need to be added.

I assume someone has already done this for this library? If yes, I'd appreciate if you can paste your settings here and I'm also happy to make a PR to add to the library since I assume others in the future will follow security recommendations and need to add CSP settings.

**Comment by CookPete** [comment]
See https://github.com/CookPete/react-player/issues/392 for some wisdom on this. @byronanderson may have more to add based on his findings.

**Comment by oyeanuj** [comment]
Not sure how I didn't stumble upon that issue - thanks @cookPete!
