### ISSUE TITLE
Setting `[Player].playing = false` does not pause playback

### ISSUE THREAD

**Issue by matthew-dean** [CookPete/react-player#441]
The docs say on the `playing` property:

> Set to true or false to pause or play the media

However, setting to true or false on the `react-player` instance doesn't change the player state. Is this supposed to mean "Set to true to autoplay. Set to false to _start_ in a paused state"? If so, this is confusingly worded, along with other similar options. The wording seems to imply that this is how you control the player instance after it has been created.

**Comment by CookPete** [comment]
`playing` is a [React prop](https://reactjs.org/docs/components-and-props.html#rendering-a-component) that you pass when rendering ReactPlayer, not a property of the instance.

Here's a basic example to demonstrate `playing` and controlling it via state: https://jsfiddle.net/hzdnpx28/

**Comment by matthew-dean** [comment]
@cookpete Ohhh derp, of course, I didn't think about tying it to state to get React to re-render. I was confused about how to think about the problem because there are other cross-platform methods like `seekTo()`, but no method for `play()` or `pause()`.

**Comment by realadamsmith** [comment]
@cookpete Do you think you could refactor this https://jsfiddle.net/hzdnpx28/ as a functional component for the people who haven't been able to set it up that way?

If you're available.

e.g.
```
const Player = () => {
    const [state, setState] = useState({playing:true})
    return (
    	<div className='player-wrapper'>
        <ReactPlayer
          url='https://vimeo.com/243556536'
          className='react-player'
          playing={this.state.playing}
          onPlay={() => setState({ playing: true })}
          onPause={() => setState({ playing: false })}
        />
        Playing prop: {this.state.playing ? 'true' : 'false'}
        <br />
        <button onClick={() => setState({ playing: true })}>Play</button>
        <button onClick={() => setState({ playing: false })}>Pause</button>
      </div>
    ) 
```

**Comment by cookpete** [comment]
Very quick example but should be enough to get you started:

```jsx
const Player = () => {
  const [playing, setPlaying] = React.useState(false)
  const play = () => setPlaying(true)
  const pause = () => setPlaying(false)
  return (
    <div className='player-wrapper'>
      <ReactPlayer
        url='https://vimeo.com/243556536'
        className='react-player'
        playing={playing}
        onPlay={play}
        onPause={pause}
      />
      Playing: {playing ? 'true' : 'false'}
      <br />
      <button onClick={play}>Play</button>
      <button onClick={pause}>Pause</button>
    </div>
  )
}
```

https://jsfiddle.net/3qseuk91/

**Comment by JH175** [comment]
@cookpete thanks for that snippet... also, this package is amazing... solid work!

**Comment by ManigandanRaamanathan** [comment]
Hi @cookpete , found that using light prop preventing the play state using playing true/false value

**Comment by zengeternalmando** [comment]
<Modal
                        maskClosable={true}
                        open={previewVisible}
                        onCancel={handleCancel}
                        footer={null}
                        width={900}
                        bodyStyle={{ height: '500px', overflow: 'auto' }}
                    >
                        {filePath && fileType && (
                            <div>
                                {fileType === '1' ? (
                                    <ReactPlayer url={filePath} playing={isPlaying} muted={isPlaying} controls={true} />
                                ) : (
                                    <DocViewer documents={docs} pluginRenderers={DocViewerRenderers}  />
                                )}
                            </div>
                        )}
                    </Modal>
                      const handleCancel = () => {

        setIsPlaying(false);
        setPreviewVisible(false); // 关闭模态框

    };
    我关闭了窗口，浏览器还是会有声音
