### ISSUE TITLE
Flash fallback for Win 7 IE 11 HLS?

### ISSUE THREAD

**Issue by cslansing** [CookPete/react-player#449]
HLS content doesn't load on Win 7 IE 11 since MSE is not implemented.
https://github.com/video-dev/hls.js#compatibility
https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/dev-guides/dn594470(v=vs.85)

Could/should we implement a Flash fallback here or would that be better suited as a custom player? There's still a good bit of people using Win 7 IE 11, unfortunately.

**Comment by CookPete** [comment]
This is definitely a case for a custom player (or another library entirely) considering the effort/package bloat required to support a slowly dying OS and browser. If `hls.js` doesn't support it natively, I don't see a reason why `ReactPlayer` should.
