### ISSUE TITLE
[Feature Request] Support Fragment for wrapper.

### ISSUE THREAD

**Issue by rockmandash** [CookPete/react-player#451]
Thank you for this wonderful library!
This library is awesome, I was wondering if we can add <Fragment /> for wrapper prop like this.
```javascript
<ReactPlayer
  wrapper="Fragment"
/>
// or
import { Fragment } from 'react';

<ReactPlayer
  wrapper={Fragment}
/>
```
I don't know what do you think.
Thank you very much!

**Comment by CookPete** [comment]
Hey @rockmandash, does this not already work?

**Comment by rockmandash** [comment]
@CookPete I'm so sorry, it does work, my bad!
