### ISSUE TITLE
Not able to see subtitles on webm video

### ISSUE THREAD

**Issue by pelagia** [CookPete/react-player#453]
I am trying to add captions from a file to the video. 
Based on the documentation I followed the steps and I have the following code:
```
 <ReactPlayer
          ref={this.ref}
          width='100%'
          height='646px'
          url={[
              { src: 'http://dl3.webmfiles.org/big-buck-bunny_trailer.webm', type: 'video/webm' },
          ]}
          playing={playing}
          onPlay={this.onPlay}
          onPause={this.onPause}
          controls
          volume={volume}
          muted={muted}
          cc_load_policy
          config={{
            file: {
              tracks: [
                  { kind: 'subtitles', src: './big-buck-bunny_trailer.vtt', srcLang: 'en', default: true }
              ]
            }
          }
          }
        />
```
Do I missing anything? Is there any dependency between the video and the captions I dont get?

**Comment by CookPete** [comment]
Hey @pelagia,

You may need a `crossOrigin` attribute as the subtitles you've specified are relative links and are likely on a different domain. Check out [this jsFiddle](https://jsfiddle.net/1ma6kdrL/) from #443 to get you started.

Also, unrelated but I don't think the `cc_load_policy` prop is doing anything.

**Comment by CookPete** [comment]
Are you sure your `vtt` file is accessible at the right place relative to the page you are loading ReactPlayer on? If the example code you posted is running at `http://example.com/test` then your subtitle file needs to be at `http://example.com/test/sintel-en.vtt`.

You should be able to see the `vtt` file successfully load in the `Network` tab of your dev tools.

**Comment by pelagia** [comment]
But that means  that the vtt should always come through Network through http?
 
If for example, I have my website on http://example.com and I want to load a video and subtitles from the folder media/examples on my project directory: 
video src url ->       src="/media/examples/stream_of_water.webm">
video caption src -> src="/media/examples/stream_of_water.vtt"/>

Is not possible?

**Comment by CookPete** [comment]
>But that means that the vtt should always come through Network through http?

Note sure what you mean. The example you gave had a relative link for the subtitles, which will use whatever protocol the page is using.

>If for example, I have my website on http://example.com and I want to load a video and subtitles from the folder media/examples on my project directory:
video src url -> src="/media/examples/stream_of_water.webm">
video caption src -> src="/media/examples/stream_of_water.vtt"/>

Yeah this is possible but be careful about your URLs – here you are now using absolute URLs for your video and caption examples, which will act differently.

If your player is on `http://example.com` and you use the `src url` you suggested, you will need to make the video available at `http://example.com/media/examples/stream_of_water.webm` and the captions available at `http://example.com/media/examples/stream_of_water.vtt`

**Comment by pelagia** [comment]
Thanks CookPete, anyway I get it to work.
