### ISSUE TITLE
Facebook videos not working in Chrome 68

### ISSUE THREAD

**Issue by AndyBarron** [CookPete/react-player#455]
*Repro*: Go to https://cookpete.com/react-player/ and select one of the Facebook presets.

*Bug*: Video is a black screen. Inspecting the `iframe` element shows that something is adding `visibility: hidden` to the inline styles. ([Screenshot](https://i.gyazo.com/866d9568601c206b56413839d57d33c7.png)) Manually removing the rule via JS or the inspector fixes the issue.

These issues only appear on Chrome 68; Chrome 67 is unaffected.. All tests were running macOS.

**Comment by CookPete** [comment]
Does the same problem occur when you mute the player beforehand? This could just be Chrome's new default autoplay policy. See #395.

**Comment by cyrdax** [comment]
Still occurs with mute on our demo page

**Comment by LeGuit** [comment]
I have the same issue with facebook videos but only on mobile (debugger mode).
It seems that facebook video link are redirected to m.facebook.com/link_to_my_video.

Then I have also the black screen. Could the issue came from FB ?

**Comment by CookPete** [comment]
See my answer to another issue here: https://github.com/CookPete/react-player/issues/454#issuecomment-409121874

My guess is that Facebook have updated their autoplay logic, possibly hiding the player if it detects that autoplay has been disabled (either by a mobile browser or a recent Chrome)? I have no idea why they would do this but it is out of ReactPlayer's control.
