### ISSUE TITLE
Seek input slider does not work on mobile

### ISSUE THREAD

**Issue by Southgarden116** [CookPete/react-player#457]
Hey!
First of all, thanks for this player! It looks really great, I just have one issue on mobile (Safari on iOS and Chrome on Android): the seek slider doesn't seem to work on those browsers, not even on the Demo page (https://cookpete.com/react-player/). It shows my slider thumb being dragged, but when I let go, it goes back to the pre-dragged position. On iOS Safari I can't even tap on the slider to seek to the tapped position.
Is this a known issue? Is there some workaround for this?

**Edit:** I could make it work with dragging the slider by using onTouchStart and onTouchEnd on the input tag. However, tapping somewhere on the input slider (not dragging the thumb) to move the thumb still doesn't work on Safari on mobile.

**Comment by CookPete** [comment]
The slider in the demo is just an example using a very basic `<input type='range' />` and not related to ReactPlayer itself. There are several decent libraries for mobile-friendly sliders that you could hook up to ReactPlayer:

https://www.google.co.uk/search?q=mobile+friendly+range+slider

**Comment by shahzaib-mobitising** [comment]
Hello CookPete,

Below function are not working on mobile devices kindly help, we can't manage range slider with library or not with library.

**onBuffer
onSeek
onReady**

**Comment by spostad7** [comment]
same issue here
any updates on this problem?
