### ISSUE TITLE
Alternatives to setState, refs, static methods, etc for standalone non-React version?

### ISSUE THREAD

**Issue by bradywestveer** [CookPete/react-player#458]
Does the non-React version of react-player support everything the React version does? If so, how can I access setState, refs, the static methods of ReactPlayer, etc?

**Comment by CookPete** [comment]
The standalone player simply renders a `<ReactPlayer>` instance into a given DOM container:

https://github.com/CookPete/react-player/blob/52d98adedb31898448bb7e84c3d674a2d4b8d67d/src/standalone.js#L5-L7

If by `setState` you just mean updating the props, you have to call `renderReactPlayer` again with the new props (see [example jsFiddle](https://jsfiddle.net/krkcvx9s/85/)). If you want to use `ref` or static methods etc, just use React.

**Comment by sebastianrueckerai** [comment]
I am using the standalone version in a mobile context. I would like the video to start a a certain second. Normally I would use "seekTo", but for that I need a reference to the player which I don't have. Is there any way to do this with the standalone version?

**Comment by cookpete** [comment]
@sebastianrueckerai I would take advantage of the fact that the `onReady` callback returns the player instance:

```js
renderReactPlayer(container, { 
  url, 
  playing: true, 
  muted: true,
  controls: true,
  onReady: player => {
    console.log(player)
    setTimeout(() => player.seekTo(0.5), 2000)
  }
})
```

https://jsfiddle.net/6v47frhL

**Comment by sebastianrueckerai** [comment]
Awesome, thanks!
