### ISSUE TITLE
Help a rookie

### ISSUE THREAD

**Issue by franz976** [CookPete/react-player#46]
Hi Pete
I'm soooo interested in react-player, but I'm not an experienced programmer so I'm having some issues with npm, node.js and so on.

I've read that for platforms that don't support npm, the minified ReactPlayer.js will do the trick. Unfortunatly it seems that reactplayer.js has a dependency on React.

What Im trying to reach is just something like

root
-- ReactPlayer.js
-- ReactPlayer.js.map
-- index.html

where index.html is something like
```
<html>
<head>
<script src='ReactPlayer.js'></script>
</head>
<body>
    
    <script>
    ReactDOM.render(
      "<ReactPlayer url='https://www.youtube.com/watch?v=d46Azg3Pm4c' playing />",
      document.getElementById('container')
    );
    
  </script>
    
    <div id="container"></div>
</body>
</html>
```
which of course doesn't work....

Be kind, help a rookie!
Thank you

Francesco

**Comment by CookPete** [comment]
Hi @franz976,

You are correct in thinking that `ReactPlayer.js` assumes that `React` and `ReactDOM` is available globally. You will need to include those files too. Luckily, Facebook [provides hosted versions](https://facebook.github.io/react/downloads.html#individual-downloads) for easy development use.

I'm gonna make things slightly easier by starting with the [React starter kit example HTML](https://facebook.github.io/react/docs/getting-started.html#quick-start-without-npm). A working HTML file would be something like:

```html
<!DOCTYPE html>
<html>
  <head>
    <script src='https://fb.me/react-0.14.8.min.js'></script>
    <script src='https://fb.me/react-dom-0.14.8.min.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.8.23/browser.min.js'></script>
    <script src='https://rawgit.com/CookPete/react-player/master/dist/ReactPlayer.js'></script>
  </head>
  <body>
    <div id='container'></div>
    <script type='text/babel'>
      ReactDOM.render(
        <ReactPlayer url='https://www.youtube.com/watch?v=d46Azg3Pm4c' playing />,
        document.getElementById('container')
      );
    </script>
  </body>
</html>
```

See it in action at [codepen](http://codepen.io/anon/pen/RajyEv?editors=1000).

You can see that we're now pulling in JS files for `react` and `react-dom`, and also a `babel-core` file that lets us use JSX properly within `<script>` tags. Before, you were wrapping the JSX in quotes, which is incorrect. I'm also using [rawgit](https://rawgit.com) to serve `ReactPlayer.js`, but you can of course change this to use a local `ReactPlayer.js` build if you like.

Hopefully this helps in getting you started! Good luck.

**Comment by franz976** [comment]
Thank you very much Pete, now it works! ;)
