### ISSUE TITLE
Autoplay isn't working every time

### ISSUE THREAD

**Issue by Aarbel** [CookPete/react-player#460]
Hi @CookPete,

I'm facing some issue with autoplay and basic prop `playing={true}`.

This happens when the navigator opens from an external link
 
To reproduce : 
- Click on your app link from outside your navigator (for me i clicked from VScode, and that opens the link inside Chrome) - The video doesn't autoplay and is in paused mode, even if the prop `playing` is `true`.
- Reload the page - The autoplay works

How could i force `play` ?

**Comment by yoiang** [comment]
@Aarbel I had the same issue and a quick search turned this up, which helped me out! 

Autoplay Policy Changes in Chrome: #395 

**TLDR**: Chrome makes you choose to either not autoplay or autoplay muted, so web developers are building pages that can annoy their users. Adding `muted` to my **react-player** tag works consistently!

**Comment by Aarbel** [comment]
thanks a lot @yoiang, did you found a workaround to allow both autoplay and not muted ?

**Comment by yoiang** [comment]
I haven't explored that yet!

**Comment by MatanBobi** [comment]
@Aarbel Unfortunately there is no such way. An unmuted video can be played (for 100% of the use cases) only after a user interaction.

**Comment by CookPete** [comment]
Even if there was a hack to enable unmuted autoplay, soon enough Chrome would release a patch so the hack would no longer work. 

I agree that unmuted autoplay can be useful when used responsibly, but the unfortunate reality is that the majority of companies use it to create a negative, annoying experience for the user that needlessly uses up bandwidth. Safari on iOS started the trend, Chrome is catching up, and eventually the rest will too.

**Comment by softmarshmallow** [comment]
adding muted tag does not allow safari / mobile chrome to autoplay.
Any alternative theory?

```tsx
<ReactPlayer
            url="https://www.youtube.com/watch?v=RIZjZFoDhRc&ab_channel=Bridged"
            width="100%"
            height="100%"
            playing
            loop
            muted
            onStart={handleOnYoutubePlayStart}
            onEnded={handleOnYoutubePlayEnd}
            config={{
              file: {
                attributes: {
                  preload: "auto",
                },
              },
            }}
          />
```

**Comment by muchirajunior** [comment]
my player cannot auto play still even when i sett playing to true

**Comment by codebravotech** [comment]
Add the `playsinline` attribute to your ReactPlayer instance (make sure it's all lowercase- the react-player module doesn't follow the camel case React convention in this case 👍🏻)

**Comment by muchirajunior** [comment]
okey thank you
