### ISSUE TITLE
Error when removing file based video during onProgress function

### ISSUE THREAD

**Issue by zzh8829** [CookPete/react-player#463]
If we remove a video after an onProgress call is queued, a strange null pointer error will happen.
The null error happens at [Player.getCurrentTime](https://github.com/CookPete/react-player/blob/52d98adedb31898448bb7e84c3d674a2d4b8d67d/src/Player.js#L87) in the progress callback. The [FilePlayer.getCurrentTime](https://github.com/CookPete/react-player/blob/52d98adedb31898448bb7e84c3d674a2d4b8d67d/src/players/FilePlayer.js#L165) call might fail because FilePlayer.player is already removed from Dom and there is no null check inside of FilePlayer.

**Comment by CookPete** [comment]
How exactly are you causing this to happen? 

The real solution here would be to [unmount](https://github.com/CookPete/react-player/blob/master/src/Player.js#L25) your player correctly to prevent any further progress callbacks from firing. If you are removing nodes from the DOM outside of the React rendering lifecycle you are asking for errors like this.

**Comment by CookPete** [comment]
Should be fixed in `1.6.5` which includes https://github.com/CookPete/react-player/pull/465
