### ISSUE TITLE
onBuffer callback not working with HLS

### ISSUE THREAD

**Issue by ryndshn** [CookPete/react-player#466]
i'm trying to use `onBuffer` to show a loading spinner while the video buffers, however the callback is never fired. the following is my component call 
```
         <ReactPlayer
            ref={this.ref}
            style={style}
            url={this.props.url}
            width={'100%'}
            height={'100%'}
            playing={this.state.playing}
            onDuration={(i) => this.onDurationHandler(i)}
            onProgress={(i) => this.onProgressHandler(i)}
            onBuffer={() => this.onBufferHandler()}
            onPlay={() => this.onPlayHander()}
          />
```
then higher up in my component i have the following: 
```
          onBufferHandler() {
            console.log('onBufferHandler');
            this.setState({isBuffering: true});
          }
```
this occurs when trying to play an hls file. the file plays fine, and the other callbacks appear to work the way i expect. is this something i need to do by exposing the hls.js player?

**Comment by superbuggy** [comment]
I'm experiencing this, too. Should it be defined in `src/Player.js`?

**Comment by maxim-xu** [comment]
Same issue.

**Comment by CookPete** [comment]
`onBuffer` is not currently hooked up to any event when initialising `hls.js`. In fact the only event we currently listen for is `ERROR`:

https://github.com/CookPete/react-player/blob/52d98adedb31898448bb7e84c3d674a2d4b8d67d/src/players/FilePlayer.js#L106-L111

If anyone can figure out from the [rather long list of `hls.js` events](https://github.com/video-dev/hls.js/blob/master/docs/API.md#runtime-events) what we can use for `onBuffer` I'm happy to add it. I don't know enough about HLS to determine what event to use.

**Comment by ryndshn** [comment]
@CookPete would you accept a PR for this?

**Comment by CookPete** [comment]
@ryndshn Sure 👍

**Comment by srameshr** [comment]
Anything on this?
