### ISSUE TITLE
Supported files

### ISSUE THREAD

**Issue by jcsabado** [CookPete/react-player#467]
Hi @CookPete , I'm using react-player on my project and I'm facing issue when I try to load/play MOV or MPEG/MPG files, the sounds is playing but no display and when I try to load MP4 files the plugin is working well. 

I also try to load this file `https://s3.ap-southeast-1.amazonaws.com/fitfil.assets/stage/2018/August/16/%20e233f00fd996ed7e644610bf8822441b.mov` on your demo and I encounter the same issue.

Any suggestion or thoughts about this. 

Thanks

**Comment by CookPete** [comment]
ReactPlayer just uses a `<video>` tag to play file paths. If the browser you are using doesn't not support the video/audio codec, it will not play. See [supported media formats on MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats).

The link you provided gives a [`MEDIA_ERR_SRC_NOT_SUPPORTED`](https://developer.mozilla.org/en-US/docs/Web/API/MediaError/code) error when trying to play, which is: 

>The associated resource or media provider object (such as a MediaStream) has been found to be unsuitable.
