### ISSUE TITLE
Access to player elements HTML

### ISSUE THREAD

**Issue by joshuaiz** [CookPete/react-player#472]
I'm using this only for audio and am I correct to assume that this only wraps the browser's HTML5 players in React? 

I'm trying to access individual parts of the player(s) to set widths — in my particular case, I am inserting a waveform image under the range slider and want to set this to be the slider width. 

While I have that working in Chrome, there's no HTML structure other than user agent/pseudo elements from the browser so making that work across all browsers responsively would be a bit challenging.

Is there another way to go about this?

**Comment by CookPete** [comment]
I think trying to insert a waveform underneath a native browser range slider is going to be a pain. Not only are the positions and widths of the sliders different across different browsers, but a newer or older version of each browser may have a different slider, or different pseudo-elements completely.

You are better off starting with a cross-browser `<input type='range' />` or [some other slider](https://www.google.co.uk/search?q=mobile+friendly+range+slider) and inserting a waveform image underneath that.
