### ISSUE TITLE
SoundCloud doesn't autoplay even if muted

### ISSUE THREAD

**Issue by bradywestveer** [CookPete/react-player#473]
The SoundCloud player doesn't autoplay even if `muted` is set to true

**Comment by CookPete** [comment]
The SoundCloud player simply does not allow autoplay, unless the domain you're on has a high enough [media engagement index](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes#mei) that Chrome has added.

Setting `muted` to true seems pointless as SoundCloud is audio only..

**Comment by bradywestveer** [comment]
Is there anyway to autoplay the media with `muted` set to true? I need the player to be synchronized with another client, and if they don't play/pause when they are supposed to everything becomes unsynchronized. I see that https://watch2gether.com has a working autoplay system for SoundCloud, and I don't think they even need to mute their player.

**Comment by CookPete** [comment]
`watch2gether` does not autoplay soundcloud for me. Go to `chrome://media-engagement` and see if `https://watch2gether.com` is high up in your MEI list. Sites that you use often will allow autoplay but everything else requires user interaction to play.

**Comment by bradywestveer** [comment]
Watch2Gether is not on my media engagement list. Also, if they didn't autoplay their videos, how would they sync the players between clients?
