### ISSUE TITLE
How to get Dailymotion player to autoplay like in the react-player demo?

### ISSUE THREAD

**Issue by bradywestveer** [CookPete/react-player#474]
The Dailymotion player in the demo of react-player can autoplay without being muted. If I try playing a Dailymotion video, it doesn't play unless I set `muted` to true. How can I replicate the behavior of the demo app.

**Comment by CookPete** [comment]
Assuming you are using Chrome, you may have a [media engagement index](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes#mei) that is high enough on the demo page to autoplay unmuted dailymotion videos, but not on another site or locally running app. Check out `chrome://media-engagement` and look for the `Is High` flag for each domain. Any domain with a high enough MEI will allow autoplay of videos.
