### ISSUE TITLE
No support for autoplay Promises

### ISSUE THREAD

**Issue by bradywestveer** [CookPete/react-player#475]
Since there is no support for checking Promises returned from autoplay calls as detailed in https://developers.google.com/web/updates/2017/09/autoplay-policy-changes, there is no way for me to detect if a user can have videos autoplay using react-player.

**Comment by CookPete** [comment]
If `play()` returns a promise, FilePlayer will catch it and call the `onError` callback with the error returned:

https://github.com/CookPete/react-player/blob/52d98adedb31898448bb7e84c3d674a2d4b8d67d/src/players/FilePlayer.js#L129-L134

You should be able to listen to `onError` for an error related to autoplay.

This is assuming you are playing a file URL. Other URLs like YouTube/Vimeo etc have their own player SDKs with their own autoplay behaviour.

**Comment by CookPete** [comment]
Feel free to reopen with more info if this doesn't solve your issue.
