### ISSUE TITLE
Implement chromecast

### ISSUE THREAD

**Issue by patrickdronk** [CookPete/react-player#476]
Hi, I like the react-player so far.
But at the moment I'm stuck. I would like to cast my "file" videos to my chromecast.
How can I achieve this? 
A hint in a direction would be fine as well :)

Thanks

**Comment by yogrammer** [comment]
I don't know what the maintainers think about adding Chromecast support since it adds a lot of extra code not relevant to the core player functionality. If you want a starting point for further implementation, check out my PR which covers the basics: https://github.com/video-react/video-react/pull/293

**Comment by CookPete** [comment]
From https://github.com/video-react/video-react/pull/293:

>Thank you for submitting such a high-quality PR! However, at this moment I don't think it's a good idea to add a component in video-react just for Google Cast since it's not widely used. Video-react is highly customizable at many levels, so users can add the feature to support Google Cast by creating their own components.

I think I share the same sentiment. This is a great idea, but would be quite a big undertaking and stretch the scope of the library somewhat. That said, it would be great if someone created a wrapper component as a separate npm package that uses `ReactPlayer` with Chromecast support. Not something I have time for currently, however.

**Comment by stolinski** [comment]
I would greatly disagree with the comment saying that it's not largely used. I agree that this can be an addon, saying that it's not widely adopted is very inaccurate.

**Comment by Impre-visible** [comment]
Hi, I want to know if the idea to implement the chrome casting has been reviewed. Cause it's an important feature for one of my project, I want to use only something that answers my requirements

**Comment by cookpete** [comment]
Nothing has changed since my previous comment. 

> I would greatly disagree with the comment saying that it's not largely used.

I’m not saying it isn’t widely used. My point was that it is probably a large, time-consuming feature that is beyond the scope of this library.
