### ISSUE TITLE
Soundcloud track url not being recognized

### ISSUE THREAD

**Issue by oyeanuj** [CookPete/react-player#477]
Hi @CookPete, maybe another regex thing:

https://soundcloud.com/user-54249915/qdghostsofthesonora/s-JBXhA doesn't work for SoundCloud. I also tried putting it as a url in the textbox on the demo site and it doesn't seem to work.

**Comment by CookPete** [comment]
Not sure what we can do here @oyeanuj – Even the [official widget playground](https://w.soundcloud.com/player/api_playground.html) refuses to build a widget with that URL.

Possibly worth bringing it up in https://community.soundcloud.com/ somewhere?
