### ISSUE TITLE
Play/Pause without re-rendering?

### ISSUE THREAD

**Issue by ruaneg** [CookPete/react-player#480]
Hi,

Is it possible to Play/Pause a video without re rendering? Im trying to get around autoplay issues but can only manage to play pause by toggling the 'playing' attribute and re rendering.

Much appreciated and great plugin btw :) 
Gary

**Comment by ruaneg** [comment]
No worries, found the answer in the source code

**Comment by PlanetIrata** [comment]
Hi @ruaneg, I'm trying to do this also (play/pause programmatically without re-rendering by using an element ID or a className), could you post the code here to do it ?

Thanks
