### ISSUE TITLE
doesn't support for fullscreen? How can I add it for youtube player?

### ISSUE THREAD

**Issue by jhta** [CookPete/react-player#484]

**Comment by CookPete** [comment]
Pass the `controls` prop into the player and the fullscreen button should appear in the native YouTube controls. Alternatively, double click a playing youtube video to go into fullscreen mode. Alternatively, see the [demo app](https://github.com/CookPete/react-player/blob/master/src/demo/App.js#L92) for an example on how to use `screenfull` to add support using the Fullscreen API.

**Comment by jhta** [comment]
Nice, I used `screenfull` and works fine, thanks.
