### ISSUE TITLE
Cross tab support

### ISSUE THREAD

**Issue by carloquilala** [CookPete/react-player#485]
able to add support for cross tabs? when I play/stop on first tab, second tab also plays/stops?

just like https://github.com/noderaider/redux-idle-monitor did, tabs are synced

**Comment by CookPete** [comment]
I don't think `redux-idle-monitor` is "syncing" between tabs in the way you think. It looks like it just calls certain events when it knows a tab has been idle for a certain amount of time.

You could build a system using a server and websockets to sync playing/pausing between two tabs/browsers/devices. Also see [some solutions here that use cookies or `localStorage`](https://stackoverflow.com/questions/4079280/javascript-communication-between-browser-tabs-windows). However, this is easily outside of the scope of ReactPlayer.
