### ISSUE TITLE
Azure streaming URL

### ISSUE THREAD

**Issue by goldenbowl88** [CookPete/react-player#486]
Hi, 
I encounter an issue.  Streaming video encoded from Azure media service  can  be played successfully in Edge but not in Chrome.
How to fix this?
Thanks.

**Comment by dannsam** [comment]
@goldenbowl88 AFAIK, react-player detects the format form the streaming URL extension. Azure streaming URL does not have an extension. You might need to configure it to `forceDash` or `forceHLS` depending on your encoding.

**Comment by johanbuys** [comment]
Hi, don't want to resurrect an old issue but, if any one else is having trouble with this. 

``<ReactPlayer
   controls
   playsinline
   config={{
            file: {
              forceHLS: true,
            }
          }}
    url={`${azureUrl}(format=m3u8-aapl)`}
    width="100%"
    height="100%"
/>``

So you need to add the `forceHLS` as suggested but also add `(format=m3u8-aapl)` including the `(` and `)` to the end of the published url. I think the stream defaults to Smooth Streaming format hence why it worked in edge.

See here for more
https://docs.microsoft.com/en-us/azure/media-services/previous/media-services-deliver-content-overview#URLs

**Comment by CookPete** [comment]
Interesting workaround, thanks @johanbuys 👍
