### ISSUE TITLE
Have separate parameters for wrapper vs. inner element width/height

### ISSUE THREAD

**Issue by thomasjm** [CookPete/react-player#487]
Thanks for this great package.

I noticed that `singlePlayer.js` takes a `width` and `height` parameter and passes them directly into the `style` dict of the wrapper element. 

https://github.com/CookPete/react-player/blob/c50320a51ff152bfe8e1b01f9e17195da496c42c/src/singlePlayer.js#L53

Then it passes the exact same props down to the inner "player" element, where they are also applied to that element. 

https://github.com/CookPete/react-player/blob/c50320a51ff152bfe8e1b01f9e17195da496c42c/src/singlePlayer.js#L55

The fact that both the wrapper and the inner element have identical linked width and height makes it hard to customize them individually.

I'm not sure how to change this without altering the API, but here's a couple suggestions:
* Add extra parameters `playerWidth` and `playerHeight` for the player, while `width` and `height` remain applied to the wrapper.
* Stop passing `width` and `height` entirely, since they're redundant and we can already pass a `style` dict. It would be nice and clean to pass `wrapperStyle` or `playerStyle` to customize the two independently.

**Comment by thomasjm** [comment]
I should mention this seems specific to `FilePlayer`.

The approach I used in https://github.com/codedownio/react-player/commit/4002d927938aa0f00693cb6e6ac09715e1589bb9 is another option, but might break some existing uses.

**Comment by CookPete** [comment]
>The fact that both the wrapper and the inner element have identical linked width and height makes it hard to customize them individually.

Why would you ever want to do this? The wrapper element is just to keep functional and structural consistency between `singlePlayer` players and the normal `ReactPlayer` usage. I can't see why you would ever want to set different sizes for the wrapper and the inner player. If you want another wrapper, just wrap `<ReactPlayer>` itself?

Assuming you are using FilePlayer (based on your approach) if you really wanted to, you could use `config.file.attributes` to override the `style` prop passed to the `<video>`: https://github.com/codedownio/react-player/commit/4002d927938aa0f00693cb6e6ac09715e1589bb9#diff-7d5478b0f54cb055a5a4a823ab6461baR231

```jsx
<ReactPlayer
  playing
  url='foo.mp4'
  config={{ file: {
    attributes: {
      style: {
        width: '640px',
        height: '480px'
      }
    }
  }}}
/>
```

**Comment by thomasjm** [comment]
I'm trying to do something simple: let the player pick its own height based on the normal video element height (for example, when it's used in a dialog). See this example using my fork for what it should look like:

https://codesandbox.io/s/r5j2189n0n

On the other hand, this is hard to accomplish without my fork or `config.file.attributes`. In addition to the fact that width and height are linked, the video element width is set like this: `width: width === 'auto' ? width : '100%'`, so it can only be `auto` or `100%`, which is a weird constraint. 

Here's a sandbox with the original version for playing around with: https://codesandbox.io/s/j94lq4q99

Anyway, I'm happy with my various workarounds but I think this API would be nicer if these things were cleaned up/decoupled. I think my fork ended up in a reasonable place, although it's a breaking change to remove `width` and `height`: https://github.com/CookPete/react-player/compare/master...codedownio:no-lib?expand=1
