### ISSUE TITLE
Duration does not work well

### ISSUE THREAD

**Issue by ciokan** [CookPete/react-player#488]
You can see even in the demo page https://cookpete.com/react-player/. Go load a song from soundcloud (don't know if it's related to sc but I doubt it) then enter a new url and load that. The duration will not change and remains one step behind (shows the duration of the previous url).

**Comment by CookPete** [comment]
@ciokan What browser are you using and what URLs are you trying to load? Duration is updating correctly for me:

![rp-duration](https://user-images.githubusercontent.com/1926029/46543298-6216d000-c8b8-11e8-9cae-3dfe61ba8702.gif)

**Comment by ciokan** [comment]
Chrome 68. You're updating by clicking the buttons which may behave differently. Just copy paste 2 custom url's to test what I'm reporting.

**Comment by CookPete** [comment]
>You're updating by clicking the buttons which may behave differently.

Clicking the buttons does the exact same thing as the Custom URL field: it just sets the `url` prop passed in to the demo player.

If you can send some exact URLs where this happens, feel free to reopen the issue.
