### ISSUE TITLE
Methods

### ISSUE THREAD

**Issue by franz976** [CookPete/react-player#49]
If I don't want to use react, how can I access to ReactPlayer methods"traditionally"?

I need something like:

ReactPlayer.load(url)
ReactPlayer.stop()
ReactPlayer.play()
ReactPlayer.volume(volumeLevel)
ReactPlayer.seekTo(position)

Thank you!

**Comment by CookPete** [comment]
Hi @franz976,

If you don't want to use React, unfortunately it makes no sense to use ReactPlayer. It may be possible to abstract the logic of the player interactions to a vanilla JS library, but this would be a large undertaking and is definitely outside of the scope of this repo.
