### ISSUE TITLE
Tracking issue

### ISSUE THREAD

**Issue by krise96** [CookPete/react-player#491]
Hi,
we are using your library, thanks for it
can you please explain what exactlly this library tracks on our page - this is what we found with ghostery

**Comment by CookPete** [comment]
The ReactPlayer library itself does no tracking at all, but it loads SDKs depending on what URL you are passing in, that will all have some sort of tracking. The list of all SDKs used is [at the bottom of the readme](https://github.com/CookPete/react-player#supported-media).
