### ISSUE TITLE
Add crossOrigin to <video> ?

### ISSUE THREAD

**Issue by jerlam06** [CookPete/react-player#499]
I get this error when I try to load subtitles: 

> Text track from origin 'http://localhost:5000' has been blocked from loading: Not at same origin as the document, and parent of track element does not have a 'crossorigin' attribute. Origin 'http://localhost:3000' is therefore not allowed access.

Is there a way to add the props: crossOrigin="anonymous" to the <video> element?

**Comment by jerlam06** [comment]
Ok, I fixed my issue thanks to this fiddle: https://jsfiddle.net/1ma6kdrL/
But now, I have a new question, is it possible to customize the way subtitles ar shown ? For instance, change the background-color and opacity?

**Comment by CookPete** [comment]
>is it possible to customize the way subtitles ar shown ?

Looks like `::cue` is what you're after: https://developer.mozilla.org/en-US/docs/Web/Apps/Fundamentals/Audio_and_video_delivery/Adding_captions_and_subtitles_to_HTML5_video#Styling_the_displayed_subtitles

**Comment by belgattitude** [comment]
right... If it helps I had to use  `&::cue`, `&::-webkit-media-text-track-container`, `&::-webkit-media-text-track-display` to achieve the styling I want for FF and Chrome.

As an example, see this gist: https://gist.github.com/belgattitude/2ca14f510314d2db4a8fba8e2c657de3

**Comment by jerlam06** [comment]
Thanks guys, I will have a look when I have time :)
