### ISSUE TITLE
onProgress is inconsistent when tab is not focused (Chrome)

### ISSUE THREAD

**Issue by Fauntleroy** [CookPete/react-player#5]
In Chrome the `onProgress` event fires irregularly, I assume due to some of Chrome's more... [interesting behaviors](https://codereview.chromium.org/6577021) related to `setTimeout` and `setInterval` in inactive tabs.

I'm going to try and resolve this issue myself at some point this week, but I'd love to know if you have any ideas. Obviously, relying on the events that the providers' players emit would be ideal, but I'm pretty certain at least one of them doesn't emit the event we need.

**Comment by Fauntleroy** [comment]
There's a chance this problem is related to a detail in my use of React Player, and not the player itself. I'll update this issue once I've found the root cause of my problem.

**Comment by CookPete** [comment]
Any movement on this @Fauntleroy?

**Comment by Fauntleroy** [comment]
Issue resolved on my end. I do advise that you use each player's own `onProgress` or what-have-you event when possible to avoid issues with `setTimeout` & `setInterval` performance down the line.

**Comment by CookPete** [comment]
>I do advise that you use each player's own onProgress or what-have-you event when possible

My only issue with that is the lack of control we then have over the frequency of progress functions being called. What if one SDK suddenly decides to `onProgress` every `100ms`? People probably don't want (or need) their app to be constantly re-rendering that often.

**Comment by Fauntleroy** [comment]
I'd say use something like lodash's `throttle` method... but that uses `setTimeout` itself. In my head I'm thinking there might be a way to implement something like a throttle method without `setTimeout`, but I don't have it quite yet.
