### ISSUE TITLE
Duration not working

### ISSUE THREAD

**Issue by bukkysos** [CookPete/react-player#506]
Unable to install Duration: showing me E404.

**Comment by CookPete** [comment]
If you are referring to the `Duration` component from the demo app, the demo app is not included in the package. You will have to copy it over into your project.

**Comment by bukkysos** [comment]
Thanks for your response.Could you, however, be as kind as to direct me to
where I can copy it?

**Comment by CookPete** [comment]
https://github.com/CookPete/react-player/blob/master/src/demo/Duration.js
