### ISSUE TITLE
Incompatibility problem with linux

### ISSUE THREAD

**Issue by MichaelSin2018** [CookPete/react-player#510]
Whenever I tried to install on linux(ubuntu),
there was error messages like the following.
Is there anyone having trouble with using it on linux, ubuntu?

error fsevents@1.2.4: The platform "linux" is incompatible with this module.
error Found incompatible module

**Comment by CookPete** [comment]
This looks like a problem with Ubuntu and `fsevents` rather than a problem with the ReactPlayer library.
