### ISSUE TITLE
add suppport for Deezer player?

### ISSUE THREAD

**Issue by moon004** [CookPete/react-player#515]
I'm working on to add support for Deezer player, but i found out that google chrome blocks flash by default, [https://stackoverflow.com/questions/32267506/deezer-audio-player-after-sept-1-when-chrome-start-blocking-flash](url). So does anyone have any idea on how to work this out or am i getting this wrong?

**Comment by CookPete** [comment]
Support for Deezer could still be added, but there is nothing we can do about browsers starting to dislike flash. If Deezer only supports a flash player, Chrome users will have to allow flash to be used if they want the player to work.

There is a similar problem with autoplay and iOS, and recent versions of chrome.

**Comment by moon004** [comment]
I'm glad that you responded, the only work around i have without having to allow flash is to import and use their Deezer player (<deez-root> DOM) and modify it from there, where the attributes are limited.
