### ISSUE TITLE
Accessibility suppport. 

### ISSUE THREAD

**Issue by VoroshilovMax** [CookPete/react-player#516]
Hi every one! Can I implement custom accessibility to this video player? Like "Esc" to stop video or "enter" to open on full screen? And it's will support of all of video source like "YouTube", "Facebook" and so on. Any suggestion will very helpful ! Thank you a lot :)

**Comment by CookPete** [comment]
There's no reason you couldn't use a keyboard shortcut library or basic keypress event listeners in your app to control ReactPlayer, just listen to key events and update your app state, which gets fed into the ReactPlayer props.

Be aware that some players will automatically override any keyboard events for their own controls. The YouTube player uses space bar for play/pause, etc.
