### ISSUE TITLE
React Player won't render in Chrome 70

### ISSUE THREAD

**Issue by RhyminTyman** [CookPete/react-player#517]
After Chrome 70 rolled out, the React Player won't render. The wrapper still shows up on the page but the player itself doesn't show. We are just playing MP3's hosted in S3 and this works in other browser fine.

**Comment by CookPete** [comment]
The mp3 example in the [demo page](http://cookpete.com/react-player/) works for me on Chrome 70. Do you have any more details about what exactly is going wrong? Any error logs? Does the `<audio>` element appear in the DOM?

**Comment by CookPete** [comment]
Good to know – thanks Joe. Possibly something around `height: 100%` and audio tags differing across browsers. I'll close this off as it seems to be an issue with styling and not a problem with ReactPlayer.
