### ISSUE TITLE
onDuration returns null for HTML5 player

### ISSUE THREAD

**Issue by whitegrey** [CookPete/react-player#52]
onDuration will return null if you programmatically set playing={true} immediately after the component mounts. The video will still play. This problem doesn't exist for youtube sources.

I assume this is because onDuration is being called before the video has fully loaded because putting playVideo() in a timeOut will fix the problem.

**Comment by CookPete** [comment]
I've just taken a look and it looks like the `oncanplay` HTML5 player event is being called _after_ the `onplay` event when you set `playing={true}` like you describe. I guess we need a better way of knowing when duration is ready (the call has already moved from `onReady` to `onPlay` in 8ef84fb67236 to fix an issue with Youtube)

**Comment by CookPete** [comment]
Fixed in `0.7.2`
