### ISSUE TITLE
How can i use it for live videos?

### ISSUE THREAD

**Issue by alimot22** [CookPete/react-player#522]
I wanted to use react-player to show live videos. does it have an attribute for that?

**Comment by CookPete** [comment]
HLS streams are supported, either by passing a URL with a `.m3u8` extension, or [setting `forceHLS` in config](https://github.com/CookPete/react-player/issues/521#issuecomment-440410426) if the stream path does not include `.m3u8`.

Live videos on YouTube, Facebook and Twitch should also be supported natively by just passing the live video URL into the `url` prop.

If there is a specific URL you think should work but doesn't, feel free to reopen the issue.

**Comment by alimot22** [comment]
Hello Pete,
I have another question about React-Player.
My client asked me to add bitrate selector to the player. I need to know,
how can I change bitrates manually? as far as I know, React-Player change
bitrates based on bandwidth speed, is that correct?

Wishes and thanks


Ali Asghar Mottaghian-

full stack developer at Narinco.com
----------------------------------------------------------------------------------
contact me at *Linkedin
<https://www.linkedin.com/in/ali-mottaghian-1b3a73102/> *or Telegram id:
@ali_mot
