### ISSUE TITLE
Select Bitrates Manually 

### ISSUE THREAD

**Issue by alimot22** [CookPete/react-player#523]
Hello Pete,
My client asked me to add bitrate selector to the player. I need to know,
how can I change bitrates manually? as far as I know, React-Player change
bitrates based on bandwidth speed.

**Comment by mmaloon** [comment]
if you're using an HLS stream, once the player has loaded (`onLoad` event), you can use the `getInternalPlayer('hls')` method to get the hlsPlayer instance.  Then you can access all the available levels (streams) from `hlsPlayer.levels`, and you can manually set the level with `hlsPlayer.currentLevel = ...` or `hlsPlayer.nextLevel = ...`

https://github.com/video-dev/hls.js/blob/master/docs/API.md#quality-switch-control-api

**Comment by oseisaac** [comment]
> currentLevel

Worked perfectly for me

**Comment by dalalRohit** [comment]
> if you're using an HLS stream, once the player has loaded (`onLoad` event), you can use the `getInternalPlayer('hls')` method to get the hlsPlayer instance. Then you can access all the available levels (streams) from `hlsPlayer.levels`, and you can manually set the level with `hlsPlayer.currentLevel = ...` or `hlsPlayer.nextLevel = ...`
> 
> https://github.com/video-dev/hls.js/blob/master/docs/API.md#quality-switch-control-api

is this available for DASH streams also?

**Comment by mrjelveh** [comment]
@dalalRohit also it's my question too, but HLS is different from [dash.js](https://github.com/Dash-Industry-Forum/dash.js).
based on the DASH document I used `autoSwitchBitrate: { video: false }` and `setQualityFor` to change quality manually but it doesn't work.

```
ref.current.player
            .getInternalPlayer("dash")
            .updateSettings({
              streaming: { abr: 
              { autoSwitchBitrate: 
                { video: false } 
              } }
            });
```
and then:
`ref.current.player.getInternalPlayer("dash").setQualityFor("video", qualityIndex);`

@cookpete any idea?

**Comment by buzzie-bee** [comment]
Just to throw my hat in the ring. This Dash bitrate setting is something I'm looking to implement also.

**Comment by Parv-gugnani** [comment]
I Will try
