### ISSUE TITLE
blows up when using react-remove-prop-types

### ISSUE THREAD

**Issue by contra** [CookPete/react-player#525]
https://www.npmjs.com/package/babel-plugin-transform-react-remove-prop-types is a pretty standard plugin to trim proptypes out in production builds. it seems that this library is relying on proptypes existing, so this blows up: https://github.com/CookPete/react-player/blob/master/src/singlePlayer.js#L7

suggested fix is to replace any reference to proptypes with the list of attributes, will send a PR if you give the thumbs up.

**Comment by CookPete** [comment]
I can build the library with `react-remove-prop-types` and things work as expected. Is there something else going on?

**Comment by contra** [comment]
@CookPete I would have to look at the code to confirm but IIRC all references to the `prop-types` module are removed, as well as any static named `propTypes` defined on a class.

**Comment by CookPete** [comment]
@contra feel free to reopen this if you can figure out what's going on here. As far as I can tell, `react-remove-prop-types` doesn't break things.
