### ISSUE TITLE
it is not working the onSeek function

### ISSUE THREAD

**Issue by carrizo88** [CookPete/react-player#526]
Hi, I am trying to transmit an audio and keep it live but when I put pause and resume the following seconds, it is not calling the onSeek function, the console log sometimes appears the first time but then never again, or never appears. I wanted to know if this is a mistake in the way to call onSeek or is it an issue?
I've already tried calling it from an onClick of a button, same result.
I have also tried to call it in the render, without getting results, the time of the method getCurrentTime (), it is according to the seekTo, the transmission does not and its value returns to the one it has at the time of putting play again

UPDATE: On safari never call the onSeek, in Chrome is calling on Seek, But in both cases the onSeek does not work, it sets the time that I send for the seekTo but it does not really start from that second, and then it redials the second one before calling the seekTo

> 	<ReactPlayer
							ref={player => (this.player = player)}
							url="//142.44.143.140:9382/;"
							playing={playing}
							width="0px"
							height="0px"
							volume={volume}
							playsinline={true}
							progressInterval={100}
							onSeek={() => {
								console.log("onSeek");
							}}
							onPlay={() => {
								console.log("play");
								this.player.seekTo(1);
								if (!playing) {
									this.setState({
										playing: true
									});
								}
							}}
							onPause={() => {
								if (playing) {
									this.setState({
										playing: false,
										fristTime: false
									});
								} else {
									this.setState({ fristTime: false });
								}
							}}
						/>

> 

Package.json

>	"prop-types": "^15.6.2",
		"react": "^16.6.0",
		"react-dom": "^16.6.0",
		"react-player": "^1.7.0",
		"react-redux": "^5.1.0",
		"react-router-dom": "^4.3.1",
>

**Comment by CookPete** [comment]
When playing files or streams, the `onSeek` callback is simply [bound to the `seeked` event](https://github.com/CookPete/react-player/blob/db7bb5c63ca6063a4e344702ef9307474037c85c/src/players/FilePlayer.js#L73) that gets fired by the `<audio>` or `<video>` instance that ReactPlayer renders. If you aren't getting any `onSeek` logs then for whatever reason, that `seeked` event isn't being fired.

Also note that you are calling `seekTo(1)` which will seek to the first second of the audio, eg `00:01`. Is that what you intended? Any number that is `1` or higher will assuming seconds. If you want to seek to the very end of the audio then try `seekTo(0.99999)`

**Comment by vidann1** [comment]
@CookPete I have a problem with seekTo also. It sometimes ignores the value it was given and sets it to 0

**Comment by carrizo88** [comment]
> When playing files or streams, the `onSeek` callback is simply [bound to the `seeked` event](https://github.com/CookPete/react-player/blob/db7bb5c63ca6063a4e344702ef9307474037c85c/src/players/FilePlayer.js#L73) that gets fired by the `<audio>` or `<video>` instance that ReactPlayer renders. If you aren't getting any `onSeek` logs then for whatever reason, that `seeked` event isn't being fired.
> 
> Also note that you are calling `seekTo(1)` which will seek to the first second of the audio, eg `00:01`. Is that what you intended? Any number that is `1` or higher will assuming seconds. If you want to seek to the very end of the audio then try `seekTo(0.99999)`

Actually I'm trying to keep streaming live, using seekTo (getSecondsLoaded ()) but it does not work, the same thing happens if I use seekTo (1) or another value

**Comment by CookPete** [comment]
Does anyone have an example URL/repo/jsFiddle where this happens? It's very difficult to fix something that I can't reproduce myself.

**Comment by CookPete** [comment]
Feel free to reopen with an example URL/repo/jsFiddle to reproduce the problem.

**Comment by mahipal999** [comment]
const check = React.useRef(null);


 <ReactPlayer
          url={location.state.url}
          playing={true}
          controls={true}
          ref={check}
          className="react-player"
          onPlay={(e) => {
              check.current.seekTo(100));
          }}
        />

its works for me
