### ISSUE TITLE
Could not play HLS

### ISSUE THREAD

**Issue by mohsalxedflix** [CookPete/react-player#529]
Version: 1.6.6

I was trying out the player and it's been fantastic playing mp4 files.
I tried to play a hls video - https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8

Inside onError, I'm getting this

`
hlsError 
{…}
​
details: "internalException"
​
err: TypeError: "URL.createObjectURL is not a function"
	onMediaAttaching https://cdnjs.cloudflare.com/ajax/libs/hls.js/0.9.1/hls.min.js:1:164060
	onEventGeneric https://cdnjs.cloudflare.com/ajax/libs/hls.js/0.9.1/hls.min.js:1:6615
	onEvent https://cdnjs.cloudflare.com/ajax/libs/hls.js/0.9.1/hls.min.js:1:6326
	emit https://cdnjs.cloudflare.com/ajax/libs/hls.js/0.9.1/hls.min.js:1:17599
	trigger https://cdnjs.cloudflare.com/ajax/libs/hls.js/0.9.1/hls.min.js:1:56794
	attachMedia https://cdnjs.cloudflare.com/ajax/libs/hls.js/0.9.1/hls.min.js:1:58507
	load http://localhost:3000/static/js/0.chunk.js:72897:11
​
event: "hlsMediaAttaching"
​
fatal: false
​
type: "otherError"
​
<prototype>: Object { … }
`

Any solution for this?

**Comment by CookPete** [comment]
`URL.createObjectURL is not a function` indicates that you're using an old browser. See [the `hls.js` compatibility table](https://github.com/video-dev/hls.js#compatibility) to see what browsers are supported.

**Comment by mohsalxedflix** [comment]
I'm using Firefox 63.0.3 actually. And I also noticed that it has loaded hls.js version 0.9.1. I tried overriding the version with the config
`{
    file: { hlsVersion: '0.10.1' }
}`

but, it does not work. It is still loading 0.9.1.

**Comment by CookPete** [comment]
Try updating to `1.7.0`. That's the version that upgrades to HLS `0.10.1` and supports `config.file.hlsVersion`

**Comment by mohsalxedflix** [comment]
Yes. Upgrading to 1.7.0 fixes it. Thanks.
