### ISSUE TITLE
Proper error codes

### ISSUE THREAD

**Issue by CookPete** [CookPete/react-player#53]
Further to #44, there is a need for more robust `onError` return values to align the different problems that can occur with the different players.

**Comment by rijk** [comment]
Also, the `onError` is not called when the URL returns a 404 (example: "https://vimeo.com/235229611").

**Comment by rijk** [comment]
Above possibly related to https://github.com/vimeo/player.js/issues/57

**Comment by rijk** [comment]
Here's a way to catch those errors: https://github.com/vimeo/player.js/issues/165#issuecomment-333326356

Should I make a PR?

**Comment by CookPete** [comment]
>Also, the onError is not called when the URL returns a 404

This is now sorted by https://github.com/CookPete/react-player/commit/d34d2286239bbf5caf1236fa4f6fa58bcb8a801e, but there is still a bug with the Vimeo API that renders the player useless after the initial error occurs: https://github.com/vimeo/player.js/issues/166.

**Comment by rijk** [comment]
Yeah, the Vimeo player is pretty crap. I submitted like 4 issues in the last week 😛

**Comment by CookPete** [comment]
Closing this off for now as it is a very old issue that doesn't serve much of a purpose any more. Each player has an entirely different set of errors and things that can possibly go wrong. The current behaviour of just passing these errors through to `onError` is good enough for nearly 100% of use cases. The effort required to try and reconcile every possible error from every player into a common set just doesn't seem to justify the benefit.

If any problems come up regarding a specific error, then people can open a separate issue for it. PRs to improve error handling are always welcome.
