### ISSUE TITLE
Insecure Content Warning

### ISSUE THREAD

**Issue by lexe11** [CookPete/react-player#534]
Using react-player on a https site with Wistia I get the following error:

> Mixed Content: The page at 'https://www.speedwright.com/' was loaded over HTTPS, but requested an insecure resource 'http://fast.wistia.com/embed/iframe_shim?domain=com'. This request has been blocked; the content must be served over HTTPS.

My code:

```
<ReactPlayer
className={styles.reactPlayer}
url="https://speedwright.wistia.com/medias/17luu6ucce"
// playing
width="100%"
height="100%"
/>
```

**Comment by lexe11** [comment]
Please close, the issue was in a react prerenderer.

**Comment by joshephan** [comment]
@cookpete How to solve problem? I used Next.js and got same problem.
