### ISSUE TITLE
Is there a way to enableTextTrack()?

### ISSUE THREAD

**Issue by clouditinerary** [CookPete/react-player#535]
Hello - thank you for your awesome work on this package... In the Vimeo player SDK there is a function `enableTextTrack() `that allows the programmer to programmatically trigger the subtitles/captions track on a video - is this possible through react-player? I do not see this option in the docs

Thanks again,
G

**Comment by CookPete** [comment]
You can use `getInternalPlayer` to get the internal player of the URL you are playing. In the case of Vimeo URLs, you get the Vimeo player instance where you can call `enableTextTrack()` and any other methods:

```jsx
<ReactPlayer
  ref={rp => this.rp = rp}
  url='https://vimeo.com/303752260'
  controls
  playing
  onReady={() => console.log(this.rp.getInternalPlayer().enableTextTrack)}
  // I'm just logging out the function to prove it exists rather than calling it
/>
```

Demo: https://jsfiddle.net/octwug5L/
