### ISSUE TITLE
Play from specific timepoint.

### ISSUE THREAD

**Issue by thunderkid** [CookPete/react-player#536]
Great library!
I'm trying to build a media bookmark manager where each bookmark consists of a url plus a timepoint. When the user clicks one, it should start playing from that timepoint. So the list might be like this:
```
youtube url1            t=200
youtube url2            t=100
youtube url2            t=150
soundcloud url1         t=50
soundcloud url1         t=150
soundcloud url2         t=10
mp4 url1                t=30
```
(Note that the list may contain multiple streaming providers, and any one may occur with with multiple urls. A particular url may occur with multiple timepoints.)

When an item is selected, ReactPlayer loads that url, and it seems I then need to call `seekTo` separately. Then problem is when to call it - switching timepoints on the same url vs switching urls for the same provider vs switching providers all seem to require it to be called differently and I'm getting inconsistent behavior where the video occasionally just starts playing from zero. 

Right now my best solution is a very hackish one - I call `seekTo` immediately when the list item changes, again on the next `onReady`, and again on the next `onProgress` (where I only call it if `played==0` to try to catch those random errors.) This seems to work around 90% of the time, and the remaining 10% of the time it still starts playing from zero. 

Is there a better way to do this?

**Comment by CookPete** [comment]
Does waiting for `onPlay` to seek help? There's not much that can be done here on ReactPlayer’s side.  `seekTo` is simply calling the relevant seek method for each player SDK, each of which may behave differently.

**Comment by thunderkid** [comment]
Thanks, yes you're right - waiting for `onPlay` seems the most robust way to do this. However, there's an interesting case where you want to, say, open a youtube video at `t=22:00` but leave it in the paused state. In that case the best solution I've found is to render `ReactPlayer` with `playing={true}`, wait for `onPlay`, then perform a `seekTo` and immediately re-render with `playing={false}`.

**Comment by gracjan-op** [comment]
Hello guys. I have similar problems with ReactPlayer. I need to use seekTo to proper fragment in audio record. Slider (input with type="range") is working properly but if i run playerRef.current.seekTo(number) from for example different component then my player is jumping to proper place but what im hearing is wrong. I should hear different fragment of audio so i assume that running seekTo directly is wrong ? What did you mean by saying "Does waiting for onPlay to seek help" ?

**Comment by thunderkid** [comment]
@gracjan-op It means you need to wait until the `onPlay` callback is fired before you call `seekTo`. So you can build your own wrapper around react-player, with a property like `myDesiredSeekPoint`. When your wrapper receives the `onPlay` callback from react-player, it only then calls `seekTo(myDesiredSeekPoint)`.

**Comment by skrohon** [comment]
For custom player with hls stream you can do seekTo() in the handleDuration() function. This works for me.
handleDuration = (duration) => {
    // console.log('onDuration', duration)
    this.props.setPlayer({
      ...this.props.playerSlice,
      duration: duration,
    })
    this.player.seekTo(this.props.playerSlice.played)
  }
