### ISSUE TITLE
Player will stop working after reload on mobile

### ISSUE THREAD

**Issue by LukePenkava** [CookPete/react-player#539]
Hi,

 first of all thanks for great plugin. To the issue at hand. Everything is working perfectly on desktop. No issue whatsoever. On mobile in web browser in react Web App, on first load of the application everything works just fine. Multiple videos load just fine and all play. However when i go to the second page of the app, where are more videos ( firebase call happens, videos are downloaded ), none of the video plays. The player appears, but there is black screen and the play button is crossed. This happens on all next pages. When i reload, the first page works fine again.
 This does not happen on pc, next pages work just fine there, its not working only on mobile, so there got to be some issue with the way i am using ReactPlayer i am guessing.

Here is the code i am using to play the videos

```
<ReactPlayer
   className="videoFrame"
   url={postObject.url}
   config={{
   youtube: { playerVars: { showinfo: 1 } },
   facebook: { appId: '12345' }
   }}
   playing
  controls
/>
```

Edit: I did some more testing and this issue seems to be happening only on iPhone, on Android, its working fine.

Thanks
Luke

**Comment by digitalwire360** [comment]
Was this issue ever solved? I have the same problem and the issue was closed, so im just curious as to the solution.
Thank you.
