### ISSUE TITLE
Safari requests http instead of https://www.youtube.com/iframe_api

### ISSUE THREAD

**Issue by vermiliongrey** [CookPete/react-player#54]
On safari, the youtube API will request the non-SSL version. This bug doesn't appear on firefox or chrome.

The result is the following error: 

```
[Error] Unable to post message to http://www.youtube.com. Recipient has origin https://www.youtube.com.

	postMessage
	K (www-widgetapi.js:98:345)
	O (www-widgetapi.js:95)
	(anonymous function)

```

I managed to hack together a fix by forcing the https version by prepending "https:" to SDK_URL on line 35 of lib/players/YouTube.js.

Strangely, I can't seem to replicate this on the demo.

**Comment by CookPete** [comment]
This was fixed in `0.5.7` (https://github.com/CookPete/react-player/commit/c05bd9dff3a8595c5bb2e53c33ddaf8db8c894de)
