### ISSUE TITLE
HLS Streams don't play on Samsung Internet

### ISSUE THREAD

**Issue by boba1007** [CookPete/react-player#540]
- React-player version: 1.8.0
- Hls.js version: tested with 0.10.1 as well as the latest version.
- Browser name/version: Samsung Internet 8.2.01.2
- OS name/version: Android 7.0

**Expected behavior**
HLS Video plays 

**Actual behavior**
HLS Video doesn't play. (Console shows 'hlsError' on demo page)
I thought this might be a hls.js issue but this browser is relatively new and should be supported.

Thanks for your help in advance!

**Comment by CookPete** [comment]
Does the [`hls.js` demo page](https://hls-js.netlify.com/demo/) work on Samsung Internet? If not there is nothing that we can do, as it simply isn't supported by `hls.js`.

**Comment by boba1007** [comment]
Yeah it doesn't seem to work either. I will file a ticket on their repo instead then. Thank you!
