### ISSUE TITLE
Playing from file not working

### ISSUE THREAD

**Issue by hariria** [CookPete/react-player#542]
I can't play the song for some reason. It's stored locally. Would you mind commenting below an example of what it would look like. Right now, I have:

`<ReactPlayer playing={true} controls={true} className='react-player' url='../public/moldau.mp3' width='100%' height='100%'/>`

**Comment by jjarrett21** [comment]
I'm having this same issue and I've even tried using the full path but it doesn't work

**Comment by jjarrett21** [comment]
The file isn't hosted anywhere it's local only.

**Comment by CookPete** [comment]
Chrome (and possibly other browsers) don't let you access your local file system by default, for security reasons. See [this StackOverflow thread](https://stackoverflow.com/questions/18586921/how-to-launch-html-using-chrome-at-allow-file-access-from-files-mode) for information on allowing local file access with Chrome, but be wary of the security risks. A safer bet would be to run a simple [web server locally](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/set_up_a_local_testing_server).

**Comment by jjarrett21** [comment]
I went the local server route, didn't even think of that. Thank You!
