### ISSUE TITLE
Autoplay not working(iOS)

### ISSUE THREAD

**Issue by denishrana09** [CookPete/react-player#547]

**Comment by CookPete** [comment]
Please see https://github.com/CookPete/react-player#mobile-considerations

**Comment by denishrana09** [comment]
I have given "playing={true}" as attribute.
it's working in all devices except iOS.

**Comment by CookPete** [comment]
@denishrana09 iOS requires user interaction before playing. Same with the latest version of Chrome. There is nothing that can be done about this.

**Comment by FahadAly05** [comment]
You need **playsinline** attribute for iOS autoplaying. You can pass as prop in react-player
