### ISSUE TITLE
Version 0.5.7 is not on npm

### ISSUE THREAD

**Issue by primeminister** [CookPete/react-player#55]
Hi Pete,

Are you going to release 0.5.7 on https://www.npmjs.com/package/react-player ?

Thanks
- Charlie

**Comment by CookPete** [comment]
Apologies @primeminister! This slipped my mind after pushing. `0.5.7` is now published :)

**Comment by primeminister** [comment]
Great! Thanks man. Any plans to update to React 15?

**Comment by CookPete** [comment]
https://github.com/CookPete/react-player/issues/56#issuecomment-211810332 ;)
