### ISSUE TITLE
Vimeo Starting playback at a specific timecode

### ISSUE THREAD

**Issue by khalil1608** [CookPete/react-player#554]
Hello :-) 

How can I make the player start from a specific time for vimeo provider?

I already tried with : 

`
<ReactPlayer
              
            
                width="100%"
                height="100%"
                url= {"https://vimeo.com/{id-video}"+"#t=10s"}
                playing={this.state.playing}
                controls={true}
                onPlay={this.play}
                onPause={this.pause}
                onStart={this.props.onStart}
                muted = {this.state.muted}
                config={{
                    vimeo: {
                        playerOptions: {
                            t: '10s',
                            start: '10s',
                        }
                    }
                }}`

Thanks you very much :-)

**Comment by CookPete** [comment]
There are no options in the [Vimeo player docs](https://github.com/vimeo/player.js) to start videos at a certain time (that I can see). Your best bet is to listen for the `onReady` callback and then call `seekTo()` on the player instance.

```jsx
<ReactPlayer
  ref={player => { this.player = player }}
  url='https://vimeo.com/243556536'
  playing
  onReady={() => this.player.seekTo(10)}
/>
```

https://jsfiddle.net/5vzka1b8/

**Comment by eduludi** [comment]
Is not in the  Vimeo player docs. Here are some official help docs showing how to start videos at a certain time: https://vimeo.zendesk.com/hc/en-us/articles/360000121668-Starting-playback-at-a-specific-timecode

Example:
```
https://vimeo.com/81400335#t=1m2s
```

**Comment by nicolaswendling** [comment]
> There are no options in the [Vimeo player docs](https://github.com/vimeo/player.js) to start videos at a certain time (that I can see).
[setCurrenTime(number)](https://github.com/vimeo/player.js#setcurrenttimeseconds-number-promisenumber-rangeerrorerror) in Vimeo Player API. Maybe it is new, I put it for people.
