### ISSUE TITLE
Providing to wrapper prop a React.forwardRef component output an error in console

### ISSUE THREAD

**Issue by rdbmax** [CookPete/react-player#555]
I need to provide a stateless component to the `wrapper` prop, but `ReactPlayer` try to attach a ref to this component and it's not possible.

So to be able to provide a stateless component I wrap it inside `React.forwardRef`
https://reactjs.org/docs/forwarding-refs.html

Now I have a new console error about the `wrapper` prop-type.

So I propose this modification to fix it in `src/props.js` :

```javascript
wrapper: oneOfType([ string, func ]),
```

to be

```javascript
wrapper: oneOfType([
  string,
  func,
  shape({ render: func.isRequired })
]),
```

because `forwardRef` component is of type `object`

**Comment by CookPete** [comment]
Fixed in `1.9.0`
