### ISSUE TITLE
light mode won't show the thumbnail

### ISSUE THREAD

**Issue by keiichiwatanuki** [CookPete/react-player#558]
I have a problem, where light set to true, won't show the thumbnail, because chrome thinks it's an insecure request, as it's not loaded with https, I think it can be solved by changing the fetch call to noembed in Preview.js to https, or is there a reason to keep it as http?

**Comment by CookPete** [comment]
Should be fixed in `1.9.1`

**Comment by Sunimali** [comment]
can I know this feature is added or not still?

**Comment by cookpete** [comment]
@Sunimali Light mode has been a feature since Dec 2018. https://github.com/cookpete/react-player/commit/8453dfc017a2889c11707c9427920c1d84205653

**Comment by Sunimali** [comment]
@cookpete i meant still i can't see thumbnail of video in light mode.is it added feature or not?

**Comment by cookpete** [comment]
@Sunimali See https://github.com/cookpete/react-player/issues/1130#issuecomment-760184940
