### ISSUE TITLE
Upgrade to react 15

### ISSUE THREAD

**Issue by primeminister** [CookPete/react-player#56]
Hi, Would be nice if the react-player will also require 15.0.1 (at the time of writing) and not depend only on 0.14.
Thanks!

**Comment by CookPete** [comment]
I have upgraded to latest React locally and I've had to fix a couple of issues that came up. I also wasn't sure what to do about `peerDependencies` to prevent warning for people who want to remain on `0.14.0`. For now I've used `"react": "^15.0.1 || ^0.14.0"` which hopefully does the job. I suppose `"react": "*"` would work too, like [karma-mocha does](https://github.com/karma-runner/karma-mocha/blob/master/package.json#L50) with `mocha`.

**Comment by primeminister** [comment]
ah ok! That is indeed the best way. So is that already in 0.5.7 version of react-player?

**Comment by CookPete** [comment]
>So is that already in 0.5.7 version of react-player?

Nope, I haven't pushed that yet. I want to make sure everything works ok, and I'm rejigging some of the test structure while I'm at it. Once I'm happy I'll push `0.5.8`, or maybe `0.6.0` because of all the dependency changes.

**Comment by primeminister** [comment]
Nice work man! Let me know if I can help you with something on my fork.

**Comment by CookPete** [comment]
`0.5.8` has been published 👍

**Comment by primeminister** [comment]
WoW! 👍  That was quick and Thanks!

**Comment by CookPete** [comment]
I couldn't see any more problems, and I didn't want to sit on it for too long ;)
