### ISSUE TITLE
CORS problems with captions in another domain

### ISSUE THREAD

**Issue by santiq** [CookPete/react-player#561]
Hi! 👋 
  
I have my videos on `http://videos.mydomain.com`  and my captions on `https://captions.mydomain.com` like this: 

```javascript
<VideoPlayer
  url="https://videos.mydomain.com/hello.webm"
  config={{
    file: {
      tracks: [
        { kind: 'subtitles', src: 'https://captions.mydomain.com/hello.vtt', srcLang: 'en', default: true },
      ]
    }
  }}
/>
```
But I'm having this error on console: 

```
Unsafe attempt to load URL https://captions.mydomain.com/hello.vtt from frame with URL http://localhost:3000/my-app. Domains, protocols and ports must match.
```

I tried adding the attribute `crossOrigin: 'true'` and `crossOrigin: anonymous` like this: 
 
```javascript
<VideoPlayer
  url="https://videos.mydomain.com/hello.webm"
  config={{
        file: {
          attributes: {
            crossOrigin: "anonymous"
          },
          tracks: [
            { kind: 'subtitles', src: 'http://localhost:57217/sample.vtt', srcLang: 'en', default: true },
          ]
        }
      }}
/>
```

Which give me this error

```
Access to text track at 'https://captions.mydomain.com/hello.vtt' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

Any sugestions?  😄

**Comment by CookPete** [comment]
[This jsFiddle example](https://jsfiddle.net/1ma6kdrL/) from https://github.com/CookPete/react-player/issues/443 seems to work using `crossOrigin: 'true'`. Is there anything you are doing differently? Is it possible that you need to enable CORS on the server that provides the captions, eg add `Access-Control-Allow-Origin` headers to responses from `https://captions.mydomain.com`?

**Comment by hoangpmhe130495** [comment]
Hi i try 'crossOrigin: 'true' but it give me an error : 'Resource interpreted as TextTrack but transferred with MIME type application/octet-stream: "https://taphuan-staging-api.csdl.edu.vn/ufiles/2020/e/09/5142da1a9c513f4a09000018/5f6c2f2ff221f378163540b0.vtt" '

**Comment by portikM** [comment]
@hoangpmhe130495 not sure if it's not too late, but I had the similar MEME problem. You need to be uploading captions file with `contentType: 'text/plain'`.
