### ISSUE TITLE
[Question] How i can access the download method using Ref ?

### ISSUE THREAD

**Issue by TITAN9389** [CookPete/react-player#563]
i want to disable the controls from videoplayer , but i want to enable download by another button outside of player, couldn't find a way to access the method using ref.

**Comment by CookPete** [comment]
Why not just use the [`download`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#Attributes) attribute of an `<a>` tag?

```jsx
const url = 'file.mp4'

<ReactPlayer url={url} />
<a href={url} download />
```

Although it looks like it only works when the file is the same origin as your page. If not, maybe try [`FileSaver.js`](https://github.com/eligrey/FileSaver.js/)
