### ISSUE TITLE
Need to update Daylimotion regex to work with playlists

### ISSUE THREAD

**Issue by jeffersonlicet** [CookPete/react-player#567]
Hi @CookPete The player is not working with urls like the following one: https://www.dailymotion.com/embed/playlist/x69070
It does not pass the regex, I can send a PR if you want. 

Thanks.

**Comment by CookPete** [comment]
The [DailyMotion Player API](https://developer.dailymotion.com/player#player-api) does not support playing playlists by the looks of it, so unfortunately this is not supported for now.

**Comment by Abdullah0991** [comment]
> The [DailyMotion Player API](https://developer.dailymotion.com/player#player-api) does not support playing playlists by the looks of it

As of nowadays, it looks like it supports playlists!
[How to embed a playlist](https://faq.dailymotion.com/hc/en-us/articles/360035190734-How-to-embed-a-playlist-)
