### ISSUE TITLE
play or pause video when visible on viewport

### ISSUE THREAD

**Issue by denishrana09** [CookPete/react-player#569]
I have used [react-on-screen](https://www.npmjs.com/package/react-on-screen) npm(which has isVisible functionality, which says if particular section is visible or not). I have done something like whenever "isVisible" is true, set "playing" attribute "true" or else "false". Now problem is when video is buffering on viewport, and we scroll down, so that "isVisible" will be false, and so "playing" must become "false" but video still plays. This problem is only occurred first time when website loads because of buffering, after that, the "isVisible" functionality works fine, means it play or pause video whenever visible on viewport.

**Comment by arronhunt** [comment]
I am doing this using [react-waypoint](https://github.com/brigade/react-waypoint), it seems to work well.

```jsx
import React, { useState } from 'react';
import { Waypoint } from 'react-waypoint';

const AutomaticPlayer = function(props) {
  let [shouldPlay, updatePlayState] = useState(false);

  let handleEnterViewport = function() {
    updateShouldPlay(true);
  }
  let handleExitViewport = function() {
    updateShouldPlay(false);
  }

  return (
    <Waypoint 
      onEnter={handleEnterViewport}
      onLeave={handleExitViewport}
    >
      <ReactPlayer
        playing={shouldPlay}
        {...props}
      />
    </Waypoint>
  )
}
```

Note you'll also want to handle user play/pause and update the state using `onPlay` and `onPause`

**Comment by CookPete** [comment]
Good answer from @arronhunt – I gave a similar answer [here](https://github.com/CookPete/react-player/issues/382).

**Comment by winstonma** [comment]
Hi I have a very similar question so I wonder if it can be asked here.

I have a video Carousel and I would like to pause the video while the carousel item is inactive. However I don't want the video starts playing while it is active. But

```
  const [index, setIndex] = useState(0);
  ...
  {videos.map((video, itemIndex) => (
      <ReactPlayer
        playing={itemIndex === index}
        {...props}
      />
  )}
```

starts playing the video when the carousel is active, which I would like to avoid. So I am not sure what is the best way to deal with this. Thanks for the help

**Comment by keerthiyml** [comment]
Hi @winstonma I'm facing a similar issue. Was curious to know if you were able to solve this?

**Comment by winstonma** [comment]
@keerthiyml You could try following the gist inside https://github.com/cookpete/react-player/issues/569#issuecomment-467687063

I am using carousel and check the carousel index. The video is paused when the carousel is inactive. It is working.

**Comment by Rajdeepc** [comment]
> Good answer from @arronhunt – I gave a similar answer [here](https://github.com/CookPete/react-player/issues/382).

This is valid when there is one element at a time but for a list of elements updating state will cause multiple refreshes.
