### ISSUE TITLE
Is it possible to support PeerTube videos?

### ISSUE THREAD

**Issue by DaneSirois** [CookPete/react-player#570]
I was curious if anyone has put any thought into supporting links to PeerTube videos?

**Comment by CookPete** [comment]
I'm wary of adding built-in support for more players that aren’t likely to be needed by the majority of users, as it bloats the package size. [Custom players](https://github.com/CookPete/react-player#adding-custom-players) are supported, though.

**Comment by rzr** [comment]
Peertube worth to be reconsidered as it's the main streaming video platform for freedom lovers.

Relate-to: https://mastodon.social/@rzr/105202653295120991

**Comment by Utopiah** [comment]
@cookpete what would be the process then to add a custom player for PeerTube then share it back with the community?

**Comment by rzr** [comment]
I've been told that now Peertube is supported by BigBlueButton 

Relate-to: https://github.com/bigbluebutton/bigbluebutton/issues/9226#
