### ISSUE TITLE
Accessibility: frameborder="0" with vimeo

### ISSUE THREAD

**Issue by dw235** [CookPete/react-player#571]
Hi.

An accessibility check of pages that use react-player and vimeo-background videos gives an accessibility error, "1.3.1 HTML is used to format content". This is caused by the resulting vimeo iframe containing a frameborder="0" attribute.

I'm trying to understand where the frameborder attribute is being added so that I can eliminate it. Is it being added by react-player? If it is can you tell me where in the code this happens? Thank you!

Here is how I'm using the react-player component:
```
<ReactPlayer
  url='https://vimeo.com/235408320'
  config={{
    vimeo: {
      playerOptions: {
        background: true
      }
    }
  }}
/>
```
The resulting iframe:
```
<iframe 
  src="https://player.vimeo.com/video/235408320?title=0&amp;byline=0&amp;portrait=0&amp;autopause=0&amp;loop=0&amp;background=1&amp;app_id=122963" 
  title="Untitled" 
  allow="autoplay; fullscreen" allowfullscreen="" 
  data-ready="true" 
  style="width: 100%; height: 100%;" 
  width="640" 
  height="360"
  frameborder="0">
</iframe>
```

**Comment by CookPete** [comment]
Unfortunately Vimeo uses oembed (called [here](https://github.com/vimeo/player.js/blob/master/src/lib/embed.js#L88)) to build the iframe that gets rendered. There's not much that can be done, apart from perhaps manually removing the attribute from the iframe after it renders?
