### ISSUE TITLE
onEnded fires directly vimeo clip starts

### ISSUE THREAD

**Issue by emrys77** [CookPete/react-player#572]
Hi I have an issue playing a vimeo clip. onEnded fires as soon as the video loads. Player works fine otherwise. Code looks like this:

```
step ?
               ( <div className="intro">
                    <div className="VideoIntro" dangerouslySetInnerHTML={{ __html: this.props.videoIntroText }}></div>  
                    <button onClick={() => this.showVideo()}>
                        <FontAwesome name="play" size="2x" />
                    </button>
                </div>
              ) : (
                <div className="player-wrapper">
                    <ReactPlayer 
                        url={'https://player.vimeo.com/video/' + this.props.vimeoCode } className="react-player"
                        width='100%'
                        height='100%'
                        onEnded={alert('movie ended')}
                    />
                </div>
              )
```
The alert pops as soon as the 'play video' button is clicked after the intro and fires showVideo()

**Comment by CookPete** [comment]
Do you have an example repo or jsFiddle showing the problem happening? I can’t reproduce this myself.

**Comment by emrys77** [comment]
Hi Pete
Thank you for your response, much appreciated.
The repo is here:
https://bitbucket.org/emrys_hughes/sar/src/video-forward-at-end/

In this file:

https://bitbucket.org/emrys_hughes/sar/src/video-forward-at-end/src/components/Video/Video.jsx

I call the ReactPlayer component you can see the commented out alert which fires as soon as the video starts?



If you click forward you will get to a video around step4

**Comment by CookPete** [comment]
Ah, I didn't spot this before.. You are passing `alert(...)` to the `onEnded` prop, this will call the `alert` function immediately and pass the result of that function to the prop. What you want to do is pass a function to the prop, eg `onEnded={() => alert('movie ended')}`
