### ISSUE TITLE
Trying to pass current time into a label and it comes back empty

### ISSUE THREAD

**Issue by jjarrett21** [CookPete/react-player#573]
Trying to use the get current time function but it just passed in an empty object
Code: 

`div className='player'>
                    <ReactPlayer
                        ref={this.ref}
                        url={'http://127.0.0.1:8887/LexusGarage150.mp4'}
                        playing={playing}
                        controls={false}
                        onPlay={this.onPlay}
                        duration={duration}
                        onPlayPause={this.onPlayPause}
                        onDuration={this.onDuration}
                        onProgress={this.onProgress}
                        getCurrentTime={this.getCurrentTime}
                    />
                    <button onClick={this.playPause}>{playing ? <FaPause /> : <FaPlay />}</button>
                    <label>{this.getCurrentTime}</label>`

**Comment by jjarrett21** [comment]
Figured out the issue wasn't binding properly, however is there a way to get this in fps or adjust the rate the current time updates?

**Comment by aydinkn** [comment]
You can set the progressInterval value (default 1000 = 1 sn) and get playedSeconds on onProgress callback prop.
