### ISSUE TITLE
playsinline not working on vimeo

### ISSUE THREAD

**Issue by jisaacks** [CookPete/react-player#574]
The vimeo player doesn't appear to set the playsinline attribute. I have tried setting it to various values but it just gets ignored.

Vimeo does support this value: https://help.vimeo.com/hc/en-us/articles/360001494447-Using-Player-Parameters

Does it need to be added to the vimeo player, or perhaps am I doing something wrong?

**Comment by aydinkn** [comment]
I think playsinline not included in the Vimeo player.
So, for now you can use Vimeo specific player options instead of ReactPlayer playsinline prop like this:

`
<ReactPlayer
  url={url}
  config={{
    vimeo: {
      playerOptions: { playsinline: 1 }
    }
  }}
/>
`
