### ISSUE TITLE
[QUESTION] How to make light player load fullplayer / play onHover ?

### ISSUE THREAD

**Issue by TITAN9389** [CookPete/react-player#576]
i created onHover method to play with the full player , but now after switching to light i can't play it anymore with same method , how can i access the method to load the full player onHover and not onClick ? so once i hover on lightplayer it loads full player and starts playing.
Thanks in advance.

**Comment by TITAN9389** [comment]
i've managed to do it somehow but i don't know if its good approach or not 
accessed ref of the player then setting onHover
`this.playerRef.state.showPreview = false`

**Comment by CookPete** [comment]
`onHover` should now work in light mode because of the fix for #584, published in `v1.10.0`
