### ISSUE TITLE
Export canPlay

### ISSUE THREAD

**Issue by streamich** [CookPete/react-player#578]
I am looking for a way to play an URL with `react-player`, but if `react-player` cannot play, render something else in that place.

Also, I would like to load dynamically `react-player` only if I know it can play the URL.

Is there a way to do it? I could do a PR to export a `canPlay()` function. Would that be something welcome?

```js
import canPlay from 'react-player/lib/canPlay';
```

**Comment by CookPete** [comment]
`canPlay` is currently baked in to each player as a static method. I don't think moving all of the `canPlay` logic is practical, or worth the benefit of being able to check if a URL can be played without loading the players. The library isn't really that big ([`13.2kB` gzipped](https://bundlephobia.com/result?p=react-player@1.9.3)) compared to a thumbnail or few seconds of video.
