### ISSUE TITLE
[Question] Play a clip and stop, preload the next clip.

### ISSUE THREAD

**Issue by erros84** [CookPete/react-player#579]
I'm using React-player In an environment where I sometimes have no control over the data structure or ability to re-encode. In some cases, I need to play lots of clips back to back. Sometimes I will need to play a short clips of a local media file.

~~I see in #152 that you have a "end" feature for youTube, is there a precise way to instruct react to play a local file from, for example, 5.000s to 7.000s and stop, or do I have to watch the OnProgress events and try to catch the next event after my endpoint?~~

I know that for back-to-back files, there is an onEnded event I can listen for before queuing up the next clip. Is there a way I can preload the next audio clip in a single player, or should I load up a new player and wait for the onEnded?

~Matthew Lee

Update:
As shown here: https://stackoverflow.com/questions/9845565/in-html5-video-how-to-play-a-small-clip-from-a-long-video
Adding "#t=30,45" to the URL allows me to play a clip of a local file.

**Comment by CookPete** [comment]
You would need to render two ReactPlayer instances, one hidden, and use `onEnded` to hide the current player and immediately show and play the hidden player.
