### ISSUE TITLE
onProgress no longer called after seeking

### ISSUE THREAD

**Issue by darobin** [CookPete/react-player#58]
This is with the YT HTML5 player in Firefox, with the controls turned on in the YT options.

I have a simple `onProgress` that logs the progress at 100ms intervals. After seeking using YT's own timeline `onProgress` is never called again (even after pausing/replaying the video). I haven't debugged extensively but I get the impression that maybe the `setTimeout` stops being called.

The information is there. I'm working around this in my parent component by polling `this.refs.player.refs.player.player.getCurrentTime()` (sic) and that keeps on working.

**Comment by CookPete** [comment]
Do you have any more information on how to reproduce this? I'm seeking multiple times in the YT HTML5 player in Firefox 45.0.2 on Mac OS X 10.11.2 and can't make this happen.

**Comment by darobin** [comment]
So I've narrowed this down to being a problem with coreaudiod. Somehow it got into an "interesting" state after connecting/disconnecting with a Bluetooth output. Everything that used sound had some slightly strange behaviour, not just Firefox (but I didn't make the link right away). After killing it, I can't repro anymore. Sorry for the weirdness!
