### ISSUE TITLE
Differentiate between user pause and programatic pause

### ISSUE THREAD

**Issue by arronhunt** [CookPete/react-player#580]
Does anyone know if there is a good method for differentiating between a user pausing a video, and a video being programmatically paused? I have an event that stops a video but I need to detect if it's the user hitting "pause" or the event that's causing it.

**Comment by CookPete** [comment]
I assume you are talking about the `onPause` event. The only way would be to measure the time between your custom event occurring and the `onPause` callback, and if it's within a certain time, it can be assumed to be a programmatic pause.
