### ISSUE TITLE
Support for adding tabIndex attribute to iframe?

### ISSUE THREAD

**Issue by mmafe** [CookPete/react-player#581]
I'm currently using the ReactPlayer to play a background Vimeo video on a Gatsby site.  I've found the player works great in Chrome and Safari, however in Firefox, I'm running into a glitch that only seems solvable by adding a `tabIndex='-1'` to the iframe.

Does this player support adding a `tabIndex` attribute to the iframe?

This may relate to #571.

**Comment by CookPete** [comment]
As with #571, we can't control the frame that the Vimeo API renders. You would have to manually set `tabIndex` after the frame renders, maybe after the `onReady` callback fires.
