### ISSUE TITLE
React Hooks changing src prop doesn’t reload video player 

### ISSUE THREAD

**Issue by RusseII** [CookPete/react-player#582]
https://stackoverflow.com/questions/41303012/updating-source-url-on-html5-video-with-react/47382850#47382850

I fixed it by setting the key field to be equal to the url 

Working
 `<ReactPlayer src={url} key={url}/>`

Broken
 `<ReactPlayer src={url}>`

triggered by event 
```
const [url, setUrl] = useState("https://testurl1")
setUrl("newUrlHere")
```

**Comment by CookPete** [comment]
`<ReactPlayer src={url}>` would never work as the prop for the URL is `url`, not `src`.
