### ISSUE TITLE
360 video on mobile?

### ISSUE THREAD

**Issue by fustkilas** [CookPete/react-player#583]
360 video on iOS safari doesn't render as 360, but instead as a stretched out 2D video

the same website when visited on OS X Chromium and/or Firefix works fine

why is this?

**Comment by CookPete** [comment]
Assuming you are talking about YouTube 360 videos:

> YouTube supports uploading and playback of 360° spherical videos on computers in Chrome, Firefox, MS Edge and Opera browsers. In order to upload a 360° video file, you'll need to modify the file with an app or script before uploading.
>
> You can also watch 360° videos on the YouTube app. 

https://support.google.com/youtube/answer/6178631?hl=en-GB

iOS Safari is apparently not supported. You will have to use the YouTube app as suggested.

**Comment by mgw-sbic** [comment]
FYI Safari plays 360 video just fine when using the Bitmovin COTS player.

Michael Glenn Williams
CEO SmartBlonde Experiential Corp (SBEX)
President Smart Blonde Corp (Productions)
805.499.1994
www.smartblondeexperiential.com
