### ISSUE TITLE
Config prop forces autoplay [VIMEO]

### ISSUE THREAD

**Issue by AdiBakija** [CookPete/react-player#589]
<ReactPlayer
          ref={this.ref}
          className='react-player'
          width='100%'
          height='100%'
          url={url}
          playing={playing}
          loop={loop}
          playbackRate={playbackRate}
          muted={muted}
          onReady={() => console.log('onReady')}
          onStart={() => console.log('onStart')}
          onBuffer={() => console.log('onBuffer')}
          onSeek={e => console.log('Seeking', e)}
          // onEnded={this.onEnded}
          onError={e => console.log('onError', e)}
          onProgress={this.onProgress}
          // onDuration={this.onDuration}
          config={{
            vimeo: {
              playerOptions: { background: 1 }
            }
          }}
        />
`

I wanted to disable the controls showing up on the player so I had to use the vimeo config prop to do this.  However, when I pass the vimeo config prop it seems to override the playing prop to true no matter the case (_it actually seems to ignore it entirely considering it never changes from false to true_).  I've also tried to pass in autoplay: 0  to the playerOptions and had no luck with it either.

Commenting out the config prop displays the controls again (what I was trying to avoid) but returns the intended functionality of having the player in a stopped state when the player is loaded.

Any suggestions on how to get around this?

**Comment by CookPete** [comment]
>`background` – Enable the player's background mode which hides the controls, autoplays and loops the video (available to Plus, PRO, or Business members).

https://github.com/vimeo/player.js/#embed-options

The `background` mode overrides any `autoplay` or `loop` config. As far as I know there is no way to override this.

What we really need is for the Vimeo guys to add an options to hide controls without having to use `background`. There is an issue for this already: https://github.com/vimeo/player.js/issues/197
