### ISSUE TITLE
Vimeo doesn't seem to trigger callbacks anymore

### ISSUE THREAD

**Issue by dbismut** [CookPete/react-player#590]
Hey, it looks like Vimeo released new version of their API, which I believe breaks react-player callbacks.
https://github.com/vimeo/player.js/releases/tag/v2.8.1

**Comment by CookPete** [comment]
Thanks for the heads up. This really sucks, especially if they still don't provide a way to load a specific version of the SDK. Last time I looked they only provided `https://player.vimeo.com/api/player.js` and if that is now breaking older implementations of the player, that is really bad news. I'll look into this soon.

**Comment by dbismut** [comment]
I guess you could use their GitHub lib here: https://github.com/vimeo/player.js/
I've looked at your demo page to check if I wasn't messing the implementation but indeed, Vimeo doesn't get event updates. I'll have a look in a minute to check on their lib.

**Comment by dbismut** [comment]
@CookPete Turns out... I was using Brave as my browser, and clearly the API bug is because of it. It works properly on Chrome and Safari. Closing as unrelated to this lib. Sorry!

**Comment by CookPete** [comment]
😅
