### ISSUE TITLE
seekTo( this.getDuration() ) results in blank frame in Safari

### ISSUE THREAD

**Issue by rijk** [CookPete/react-player#592]
From #591. `seekTo( this.getDuration() )` should jump to the last frame of the video. However, in Safari it seems to jump too far, and shows nothing.

Fiddle: https://jsfiddle.net/uniti/uoysz8mh/1/

**Comment by CookPete** [comment]
What browser/OS are you using @rijk? On macOS 10.14.3 with Safari 12.0.3 this behaves as expected for me:

![safari-bug](https://user-images.githubusercontent.com/1926029/54190959-d4fe2580-44ac-11e9-8d14-f26ec5da5a6e.gif)

**Comment by rijk** [comment]
In your capture it is not working. The with getDuration() button is not working for me even in Chrome (in Chrome it just starts playing from the beginning if I press it). With the first button, it should look like this:

![image](https://user-images.githubusercontent.com/159500/54191150-9f116f00-44b5-11e9-9363-7235c1d50704.png)

This frame with the two logos is the last frame of the video.

In Safari, when pressing the Seek to end button, it either looks like this (if you click it while playing):

![image](https://user-images.githubusercontent.com/159500/54191262-db44cf80-44b5-11e9-8ed9-8e687f4a1fa1.png)

(which is just the frame you were on when pressing the button), or like this (if you click it while paused):

![image](https://user-images.githubusercontent.com/159500/54191315-f6174400-44b5-11e9-8381-a3813dd2a385.png)

I am using Safari Version 12.0.3 (14606.4.5) on MacOS 10.14.3.

**Comment by rijk** [comment]
For reference, I added a Seek to end button that does work in Safari (with `0.999` instead of `0.9999999`).

**Comment by CookPete** [comment]
Is Safari just weird with setting `currentTime` to the exact duration of the video? In the jsFiddle example, the duration is `42.70933333333333` seconds.. I would try a bunch of different seeks, eg:

```js
seekTo(42.70933333333333) // I assume won't work as it's the same as seekTo(this.getDuration())
seekTo(42.7093333333)
seekTo(42.709333)
seekTo(42.709)
seekTo(42.7)
seekTo(42)
```
to find out more about Safari and how it deals with seeks.

It looks like [you aren't the first person to have problems with Safari and setting `currentTime` in React](https://teamtreehouse.com/community/setting-videocurrenttime-in-componentdidmount-with-reactjs-html5-video-element-not-working-in-safari).

**Comment by rijk** [comment]
Yeah, I've [messed around with this](https://jsfiddle.net/uniti/uoysz8mh/8/) and found that somewhere between `42.65` and `42.7` it stops working. Which feels completely arbitrary of course.

**Comment by CookPete** [comment]
I'm gonna close this off as I don't think there's anything the library can do about this. ReactPlayer is correctly seeking to the end of the video, but Safari obviously doesn't play ball when seeking within a certain range of the end of the video. I guess the solution here is to use `onDuration` to fetch the duration, then something like `player.seekTo(Math.min(amount, duration - 0.5))`
