### ISSUE TITLE
change black background-color on child div of the root container

### ISSUE THREAD

**Issue by kendallstrautman** [CookPete/react-player#593]
The problem - the first child of the root wrapper container i.e. the div that is the actual parent of the iframe has a background-color: black on it and I don't see any way to edit this inline style. 

I have tried - adding inline styles to the parent container (which didn't affect the child background-color obviously) and hacking the height of the parent container (i.e. the root of React_Player) so that the black background is covered up...but on resize you can see the black background and at certain sizes it has an ever-so-slight black border. 

Any advice on how to alter this background-color? Seems like such a simple thing, but I didn't see anything in the documentation about being able to access the styles on this child div that houses the iframe.  

See screen shot for a more specific target of the div in question. 

<img width="656" alt="Screen Shot 2019-03-12 at 3 03 58 PM" src="https://user-images.githubusercontent.com/36613477/54239643-fffe6e80-44d8-11e9-83a5-0f505e3dede6.png">

**Comment by CookPete** [comment]
That div is rendered by the vimeo SDK, which we have no direct control over.

However, wouldn't this CSS do the job?

```css
.video-player > div { 
  background-color: transparent !important; 
}
```

**Comment by kendallstrautman** [comment]
yes that worked! the !important is key. thank you!

**Comment by CyrilleNoel** [comment]
perfect it to work for me :-)
