### ISSUE TITLE
DRM/widevine support? 

### ISSUE THREAD

**Issue by yuchuan1** [CookPete/react-player#596]
Does it support DRM? How do I set it up?

**Comment by CookPete** [comment]
It does not support DRM out of the box, however, when playing files it simply renders a `<video>` which can be accessed with the `getInternalPlayer()` instance method, so I assume any other frameworks could be used on the media element? Although at that point you might as well render a `<video>` natively in react.

I would recommend using [`video.js`](https://github.com/videojs/video.js) instead, which has a plugin for DRM: https://github.com/videojs/videojs-contrib-eme
