### ISSUE TITLE
react-player can't pause when video loop mode？

### ISSUE THREAD

**Issue by luojinghui** [CookPete/react-player#598]
Hi, First of all, this plugin is very good, but I have a problem now. 
In IE 10+ browser, React-player cannot be paused by setting the playing field in loop mode when play ends again？

This is a must-have question。What went wrong?

**Comment by CookPete** [comment]
Support for IE10 ended [a long time ago](https://www.xfive.co/blog/stop-supporting-ie10-ie9-ie8/) so ReactPlayer does not support it.

If you can reproduce the problem in a jsFiddle or example repo, please reopen this issue.
