### ISSUE TITLE
adding Uploading tracks/closed captioning button

### ISSUE THREAD

**Issue by sdb1228** [CookPete/react-player#599]
👋 Wondering how people are handling uploading closed caption/tracks? I don't see any ability in the package itself to add a button for it but see the ability to show them.  Wondering if it would be valuable to fork and add that ability?

**Comment by sdb1228** [comment]
So looking into this more (sorry kinda new to this whole video playing) The controls shown here are the video tag controls that are presented by the browser.  There is no way to customize them outside of building your own (super unfortunate given that I just need 1 button to meet product needs) but I think ill try to find a workaround in the product to add them rather than trying to make custom controls on the video player itself.

**Comment by rlyawesome** [comment]
@sdb1228 Hey! Did you solve this problem? I also need a custom button for captions.

**Comment by sdb1228** [comment]
@rlyawesome do you need a custom button for captions or just the ability to add captions?

**Comment by oseisaac** [comment]
> @rlyawesome do you need a custom button for captions or just the ability to add captions?
The ability to add a custom closed caption button

**Comment by raad-work** [comment]
here's an example how to add it 
```javascript
<div className='player-wrapper'>
        <ReactPlayer
          url={['https://iandevlin.github.io/mdn/video-player-with-captions/video/sintel-short.mp4']}
          className='react-player'
          controls
          playing
          width='100%'
          height='100%'
          config={{ file: {
            attributes: {
	            crossOrigin: 'true'
            },
            tracks: [
              {kind: 'subtitles', src: 'https://iandevlin.github.io/mdn/video-player-with-captions/subtitles/vtt/sintel-en.vtt', srcLang: 'en', default: true},
              {kind: 'subtitles', src: 'https://iandevlin.github.io/mdn/video-player-with-captions/subtitles/vtt/sintel-de.vtt', srcLang: 'de'},
              {kind: 'subtitles', src: 'https://iandevlin.github.io/mdn/video-player-with-captions/subtitles/vtt/sintel-es.vtt', srcLang: 'es'}
            ]
          }}}
        />
      </div>
```
https://jsfiddle.net/5me7gf4y/
