### ISSUE TITLE
When onEnded triggers, I would also like to exit fullscreen, but no method exists.

### ISSUE THREAD

**Issue by bobbydp** [CookPete/react-player#60]
I currently have a "bug" when a video plays to it's completion and the user also has the player in full screen mode. It seems that I should force the player to exit full screen before changing the state of my React app. The containing div does not seem to revert to it's state before it was in full screen, and wreaks the layout. Is this a quirk of the Vimeo embed? Or do I not have hardy enough CSS? Please advise. You can visit an example at: http://www.bobbylam.com and playing a video, entering full screen, and skipping to the end to see the unintended behavior.

**Comment by vermiliongrey** [comment]
you can programatically trigger exit full screen once the video ends.

here's a sample code:

	```
enterFullScreen: function(){
		var elem = document.documentElement; //selects the entire document
		if (elem.requestFullscreen) {
		  elem.requestFullscreen();
		} else if (elem.msRequestFullscreen) {
		  elem.msRequestFullscreen();
		} else if (elem.mozRequestFullScreen) {
		  elem.mozRequestFullScreen();
		} else if (elem.webkitRequestFullscreen) {
		  elem.webkitRequestFullscreen();
		}
	},
	exitFullScreen: function(){

		if(document.exitFullscreen) {
			document.exitFullscreen();
		} 
		else if(document.mozCancelFullScreen) {
			document.mozCancelFullScreen();
		} 
		else if(document.webkitExitFullscreen) {
			document.webkitExitFullscreen();
		}

	},


```

**Comment by CookPete** [comment]
Working from what @vermiliongrey said, you could use both like so:

Cross-browser `exitFullscreen` function pulled from [this blog post](https://davidwalsh.name/fullscreen):

```js
function exitFullscreen() {
  if(document.exitFullscreen) {
    document.exitFullscreen();
  } else if(document.mozCancelFullScreen) {
    document.mozCancelFullScreen();
  } else if(document.webkitExitFullscreen) {
    document.webkitExitFullscreen();
  }
}
```

Then just use `onEnded` to execute this when media finishes:

```js
<ReactPlayer
  url={url}
  playing={true}
  onEnded={exitFullscreen}
/>
```

Or, as I see you are doing on your site now, run it when the player has played a certain percentage of the video.

**Comment by bobbydp** [comment]
awesome, much appreciated guys. I tried to implement onEnded but sadly it still won't escape in time for the box model to fail on me. (It seems that the exiting of the full screen still triggers at the same time that I change back to the thumbnail, and so it's rendered incorrectly).

This is why I now have to trigger it right before the video ends. I wonder if this is just a browser quirk or if I'm really doing something wrong..

I think I will use the webkit code you guys introduced me to to simply let the video stop naturally...and then force the user to manually escape out of full screen on their own.
