### ISSUE TITLE
Seeking causes player to start by itself

### ISSUE THREAD

**Issue by thunderkid** [CookPete/react-player#601]
I'm finding that with some players (especially Vimeo and Wistia), merely seeking can cause the player to randomly start on its own.

You can see this on the demo page by pasting in the following url:
[https://vimeo.com/198241759](url)
Load it, then click the external pause button. Now click rapidly back and forth on the external seek bar. After maybe a dozen rapid clicks, you'll find the player starts playing on its own.
This is probably a vimeo/wistia bug, but it's one I'd like to suppress. In these cases I notice that the player is firing an `onPlay` event, so I'm thinking I this requires a hack where if `onPlay` is received while internal controls are disabled then the internal `player.stop()` is automatically called. Is there a better way to do this or should something like this be added to `react-player`?

**Comment by thunderkid** [comment]
So the above method seems to work to fix this problem, but my wrapping code is calling:
```(this.player as any).player.player.pause()```
Is there a nicer way to access this function?
Or should this just be done inside the `react-player` code so the user never has to worry about it?

**Comment by CookPete** [comment]
Yeah unfortunately it looks like the only way to tackle this is to pause after `onPlay` as you described. I'm not sure there's anything we can do in ReactPlayer that wouldn't be really hacky. 

You can use the `getInternalPlayer()` instance method to avoid the `player.player.player` business.
