### ISSUE TITLE
onReady doesn't always get called (SSR?)

### ISSUE THREAD

**Issue by thehappycoder** [CookPete/react-player#602]
I am writing a next.js web app using react-player and I noticed that seekTo doesn't always work. After some debugging and checking the code of react-player, I realised that onReady isn't always called.

I have a feeling that it's broken when the player is rendered on the server side.

**Comment by CookPete** [comment]
The player relies purely on client-side behaviours (dynamic script loading) so isn't likely to work correctly when rendered with SSR.

If you can provide details of the error you are seeing, or an example that reproduces the bug, feel free to reopen this issue.
