### ISSUE TITLE
Captions not working with HLS

### ISSUE THREAD

**Issue by naheller** [CookPete/react-player#604]
#### Current Behavior
The `track` element appears in the DOM, but is not visible on the page.

#### Expected Behavior
Captions appear over the video.

#### Steps to Reproduce

1. Load an HLS video into `react-player`
2. Add subtitles:
```
{ 
    kind: 'subtitles', 
    src: 'http://localhost:8080/captions/caption.vtt', 
    srcLang: 'en', 
    default: true 
}
```
3. Play video.

#### Environment
- URL attempting to play: HLS video file
- Browser: Chrome
- Operating system: MacOS

#### Other Information
DOM output:
![Screen Shot 2019-03-25 at 11 32 17 AM](https://user-images.githubusercontent.com/18204925/54945050-23baaf00-4ef2-11e9-9093-215caeb4f648.png)

**Comment by MihailDemchenko** [comment]
Hi @naheller. 
I have the same issue. 
Did you find some solution?

**Comment by BijanRegmi** [comment]
same issue

**Comment by huqiyao** [comment]
Hi @naheller Did you know the solution?

**Comment by somewonderfulguy** [comment]
Why on earth is it closed? It is still an issue!

**Comment by jonathanlal** [comment]
yeah not working with HLS... guess will have to make an overlay for now

**Comment by someguy9** [comment]
I guess there is still not fix?
