### ISSUE TITLE
Twitch Clips Do Not Show Up in React Player

### ISSUE THREAD

**Issue by aaronkchsu** [CookPete/react-player#607]
#### Current Behavior
Currently, twitch clips link https://clips.twitch.tv/ExquisiteTrappedHerbsTBTacoRight do not work in the player! Do you think getting these links to work will be hard? It's cool that full stream links on twitch currently work!

#### Steps to Reproduce

1. Insert a twitch clip link into react player such as https://clips.twitch.tv/ExquisiteTrappedHerbsTBTacoRight
2. Notice that the video does not load

**Comment by CookPete** [comment]
>Embedding a clip is different than embedding a live stream or VOD. The embedded clips player uses a different set of query parameters and does not support the JavaScript interactive embed.

https://dev.twitch.tv/docs/embed/video-and-clips/#non-interactive-frames-for-clips

We can't control a non-interactive frame, so you'll have to use the direct `iframe` embed:

```html
<iframe
    src="https://clips.twitch.tv/embed?clip=<slug>"
    height="<height>"
    width="<width>"
    frameborder="<frameborder>"
    scrolling="<scrolling>"
    allowfullscreen="<allow full screen>">
</iframe>
```
