### ISSUE TITLE
index.d.ts not updated for new seekTo parameter.

### ISSUE THREAD

**Issue by thunderkid** [CookPete/react-player#608]
The new `seekTo` parameters are not compiling under typescript because of outdated typings.

Its entry in `index.d.ts` should be changed to 
  ```seekTo(fraction: number, type: 'seconds' | 'fraction'): void;```

(Is there some webpack plugin to generate `index.d.ts` automatically? Might save some time in the future.)

**Comment by CookPete** [comment]
>Its entry in index.d.ts should be changed to
`seekTo(fraction: number, type: 'seconds' | 'fraction'): void;`

I guess it should be `type?` as it's optional?

>(Is there some webpack plugin to generate index.d.ts automatically? Might save some time in the future.)

I did consider this but haven't looked yet.. it would be great but I don't know how it would work.

**Comment by thunderkid** [comment]
Yes, you're right - I missed that. For back compatibility should be

```seekTo(fraction: number, type?: 'seconds' | 'fraction'): void;```

I suppose to generate `index.d.ts` automatically you'd need to be using typescript from the ground up otherwise the plugin wouldn't know the type info. If you're using js, I could imagine a plugin that at least checks the number of args and alerts you to any inconsistency, but that would only be a partial help, and I couldn't find anything like this with a quick search.

**Comment by CookPete** [comment]
Looks like this was sorted in `v1.11.0` ae0c0ba9
