### ISSUE TITLE
suggestion: onStart handler

### ISSUE THREAD

**Issue by whitegrey** [CookPete/react-player#61]
onStart handler that runs only once at the beginning of video playing (and no other time, unless video ID changes). 

It's a pretty simple handler so I'm sure there's many uses, but my specific use cases are: 
- an UI effect that fades in the player as a video begins playing.
- fade in the volume gradually as the video begins playing.

The handler can technically be emulated with onPlay and setState, but it's rather verbose for a relatively fundamental act.

**Comment by CookPete** [comment]
Added in `0.6.0`
