### ISSUE TITLE
IE11, playing not working

### ISSUE THREAD

**Issue by kudorori** [CookPete/react-player#610]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior

If the video is ended, After using seekTo, playing not working

#### Expected Behavior

playing in worked

#### Steps to Reproduce

1. goto https://cookpete.com/react-player/
2. click [files] -> [mp4]
3. SeekTo 59s, 
4. wait end
5. SeekTo 30s
6. now playing not working

#### Environment
- URL attempting to play: http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4
- Browser:  IE11
- Operating system:  window 10

**Comment by CookPete** [comment]
There's a similar issue [here](https://social.technet.microsoft.com/Forums/en-US/d94e68d8-903b-4cae-9291-266215e0d4de/problem-with-html5-video-ended-event-ie11ie10-and-ie9?forum=ieitprocurrentver) that suggests this has been a problem for years. This seems like an inherent bug with IE11, and I'm not sure what can be done about it.
