### ISSUE TITLE
Does not allow video URLs without an extension

### ISSUE THREAD

**Issue by marnusw** [CookPete/react-player#611]
#### Current Behavior
Playing an mp4 video from a URL that does not contain an extension does not work. This is because `FilePlayer.canPlay` only considers the URL extension.

#### Expected Behavior
Should work if the mp4 mime type is provided.

Currently the player doesn't accept a `mime` or `type` prop, but if an array is passed to the `url` prop it spreads onto a `<source/>` element which means `url={[{src: '...', type: 'video/mp4'}]}` can technically be used (and does when overriding `canPlay`). 

#### Steps to Reproduce

1. Try playing URL below with the `FilePlayer`

#### Environment
- URL attempting to play: https://dmfh1dh7sl8i1.cloudfront.net/c8548bc0-420c-4702-908e-f711f412cdb3/trailers/eb5c984f-adb8-410e-b690-07d68a7494e1

#### Other Information
I would like to submit these proposed changed which I will happily create a PR for if they make sense and a strategy can be agreed upon:

1. The `FilePlayer`, i.e. `canPlay`,  should support having the MIME type specified along with the URL
1. If the `url` is an array of objects, both the `src` and `type` should be considered
1. An optional `mime` prop should be added for use alongside a string `url`

The question of which, MIME type or extension, should take precedence if both are present arises. I would recommend giving the MIME type precedence.

**Comment by CookPete** [comment]
I'm assuming you are only getting this issue with the standalone `FilePlayer` import, as the normal `ReactPlayer` falls back to `FilePlayer` if `canPlay` is false for all available players.

There is a `config.file.forceVideo` prop that will skip the `canPlay` check for standalone players:

```jsx
<FilePlayer
  url='https://dmfh1dh7sl8i1.cloudfront.net/c8548bc0-420c-4702-908e-f711f412cdb3/trailers/eb5c984f-adb8-410e-b690-07d68a7494e1'
  config={{ file: { forceVideo: true } }}
/>
```

**Comment by marnusw** [comment]
Excellent, thank you for clarifying.
