### ISSUE TITLE
Upgraded to React 16.8.6 causes error

### ISSUE THREAD

**Issue by texas697** [CookPete/react-player#620]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior
After updating dependencies in my project I am getting an error when trying to play videos from vimeo.  The video starts to appear in the player but becomes blurred and this is the error message. 

player.js:2 Uncaught TypeError: Cannot assign to read only property 'play' of object '#<HTMLMediaElement>'
    at player.js:2
    at player.js:2
(anonymous) @ player.js:2
(anonymous) @ player.js:2
268017403?title=0&byline=0&portrait=0&playsinline=0&autopause=0&app_id=122963:273 Uncaught TypeError: VimeoPlayer is not a constructor
    at HTMLScriptElement.script.(player.vimeo.com/video/anonymous function) (https://player.vimeo.com/video/268017403?title=0&byline=0&portrait=0&playsinline=0&autopause=0&app_id=122963:273:36)

#### Expected Behavior
Play videos.

#### Steps to Reproduce

1.
1.
1.

#### Environment
- URL attempting to play: 
- Browser: Chrome
- Operating system: Ubuntu
- jsFiddle example: https://jsfiddle.net/sv5x3ug1

#### Other Information
I have searched for the specific error and nothing comes up related to my problem. I did find one match with someone using wordpress. But there was no solution the problem.

https://wordpress.org/support/topic/not-rendering-vimeo-videos/

**Comment by redraushan** [comment]
@texas697, I am having the same issue with React 16.8, did you manage to solve the issue?

**Comment by texas697** [comment]
Yes. I updated to the latest release of react-player and it started working again. Didn't look into the actual changes

**Comment by redraushan** [comment]
> Yes. I updated to the latest release of react-player and it started working again. Didn't look into the actual changes

I am having issue with "version": "1.11.0"

**Comment by CookPete** [comment]
Upgrading to `16.8.6` works fine for me. It looks like a problem with the Vimeo player, which should be reported [here](https://github.com/vimeo/player.js) instead.
