### ISSUE TITLE
Large file stops buffering and doesn't play

### ISSUE THREAD

**Issue by TheFridgeMaster** [CookPete/react-player#624]
#### Current Behavior
Smaller files play perfectly and I can change between sources with easy, however when I selet the source with a 600mb+ local file, it begins buffering and then dies out.

#### Expected Behavior
I would hope it is able to play a local file of that size. I guess possible solutions would be to host the file on youtube and playback the youtube link? but I would much rather a native function.

#### Steps to Reproduce

1. Upload large file (600mb) to server, causing a page refresh
2. Player begins to load the file, loading stops and no playback occurs
3. switch to other, smaller video files, works fine.

#### Environment
- URL attempting to play: 
- Browser: Version 73.0.3683.103
- Operating system: Windows 10 1809

#### Other Information
I'm not really sure if this is a limitation of this library or maybe the file encoding is weird? I am using the same encoding for the large file as the smaller files. It's all just through ffmpeg. The large file plays fine through VLC on my rig and the likes.

**Comment by TheFridgeMaster** [comment]
My bad. The video file exported was of jpeg encoding. I adjusted my ffmpeg parameters and set it to h264 and now it works perfectly. Apologies for wasting your time. Fantastic library!

**Comment by XTechHub** [comment]
> My bad. The video file exported was of jpeg encoding. I adjusted my ffmpeg parameters and set it to h264 and now it works perfectly. Apologies for wasting your time. Fantastic library!

getting issue loading large video files how to set to h264.thanks
