### ISSUE TITLE
Support for Microsoft Stream

### ISSUE THREAD

**Issue by riosn-n** [CookPete/react-player#625]
I'm considering adding support for Microsoft Stream using the approach [described here](https://docs.microsoft.com/en-us/stream/portal-embed-video). Since MS Stream does not have a public JS SDK many of the options won't be available. As per the documentation, the way to embed a video is using an iframe that accepts certain parameters. 

@CookPete, would you mind taking a quick look at the documentation and letting me know if it would make sense to add MS Stream support to the project? I'm happy to do the work if you think it's valuable.

**Comment by mgw-sbic** [comment]
Hi All, I've been lurking here. Are there other iframe based use cases
already supported? if so, we'd like to add TotalVU embeds as well.

Thank you!

All the best,
Michael Glenn Williams
CEO SmartBlonde Experiential Corp (SBEX)
President Smart Blonde Corp (Productions)
805.499.1994
www.totalvu.tv

**Comment by mgw-sbic** [comment]
Any more updates on this issue?

**Comment by CookPete** [comment]
I'm not sure there's any value in supporting players that just require an iframe to be rendered.  None of the supported props would work if there isn't an API to hook in to. You're better off just rendering the iframe yourself in React?
