### ISSUE TITLE
Improve HLS error details

### ISSUE THREAD

**Issue by naheller** [CookPete/react-player#627]
#### Current Behavior
HLS errors logged by the ReactPlayer are just the string "hlsError"

#### Expected Behavior
HLS errors logged by the ReactPlayer are more verbose, describing the nature of the error to allow for better troubleshooting

#### Steps to Reproduce
1. Implement ReactPlayer component with `onError={e => console.log(e)}`
2. Encounter an HLS Error
3. View log in console as the string "hlsError"

**Comment by CookPete** [comment]
`onError` gets fired with 4 params when playing HLS files. The second of which is an error data object:

https://github.com/CookPete/react-player/blob/f1ba67a7e534ae9f1e9934469eec7ef334f80791/src/players/FilePlayer.js#L129-L131

More info on the data object here: https://github.com/video-dev/hls.js/blob/master/docs/API.md#fifth-step-error-handling

You also get given the HLS instance and the HLS global, for things like 

```js
if (data.details === Hls.ErrorDetails.FRAG_LOAD_ERROR) {
  // ...
}
```

**Comment by yurguis** [comment]
@CookPete I was using v1.5.0 and catching hlsErrors just fine but then I upgrade to latest (v1.11.0) and I am getting undefined for all 4 params that you mention in your previous post. So `onError` is just giving me hlsError string as @naheller described.
Is there something extra that should we do to catch these hls errors?
