### ISSUE TITLE
anyway not to play the entire url - only want to play 30 seconds

### ISSUE THREAD

**Issue by Ilene0413** [CookPete/react-player#631]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Steps to Reproduce

1.
1.
1.

#### Environment
- URL attempting to play: 
- Browser: 
- Operating system: 
- jsFiddle example: https://jsfiddle.net/sv5x3ug1

**Comment by ninjaPixel** [comment]
If you're playing YouTube then you can do the following:

```
<ReactPlayer
     url="https://www.youtube.com/watch?v=U3soLrp3rl0"
     youtubeConfig={{ playerVars: { end: 30 } }}
/>
```

**Comment by CookPete** [comment]
@ninjaPixel is right.. some players have params to set a play boundary. Alternatively, you could use `onProgress` and check the `playedSeconds` amount, and set the `playing` state to false when it reaches 30.
