### ISSUE TITLE
How to pass MediaStream to React_player

### ISSUE THREAD

**Issue by swarnimsuman** [CookPete/react-player#637]
I'm trying to use React-Player with the video call service that we have implemented. I'm able to get MediaStreamTracks but not able to pass that in "url" section of React-Player.

const mediaStream = new MediaStream();
mediaStream.addTrack(track.mediaStreamTrack);
```<ReactPlayer url={mediaStream} />```

Failing with the below error: 
Type 'MediaStream' is not assignable to type 'string | string[] | SourceProps[] | undefined'.
  Type 'MediaStream' is missing the following properties from type 'SourceProps[]': length, pop, push, concat, and 28 more.ts(2322)
index.d.ts(73, 3): The expected type comes from property 'url' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<ReactPlayer> & Readonly<{ children?: ReactNode; }> & Readonly<ReactPlayerProps>'

Thanks in advance

**Comment by CookPete** [comment]
This looks like a problem with typings rather than with the actual code of the player?

@swarnimsuman how are your `MediaStream` objects types in other parts of your app? It seems like the fix is simple updating this line to support `MediaStream`s:

https://github.com/CookPete/react-player/blob/f1ba67a7e534ae9f1e9934469eec7ef334f80791/index.d.ts#L73

**Comment by swarnimsuman** [comment]
Thanks @CookPete, it's working now. i'll checkin the code as part of this bug.

I've one more doubt, i understand that it's a "video/audio player" not "video call" but is it possible to change the controls to suit my requirement like "disconnect the call" and "mute the video" and having react-players audio controls

**Comment by swarnimsuman** [comment]
@CookPete My video stream is working fine but not able to control audio through default controls, I just need to pass both the streams to react-player and it will take care of everything right...?

**Comment by CookPete** [comment]
>I've one more doubt, i understand that it's a "video/audio player" not "video call" but is it possible to change the controls to suit my requirement like "disconnect the call" and "mute the video" and having react-players audio controls

There are no built in controls in ReactPlayer. Anything custom you will have to build yourself.

>My video stream is working fine but not able to control audio through default controls, I just need to pass both the streams to react-player and it will take care of everything right...?

I think you are overestimating what this library does. Passing in a `MediaStream` to the `url` prop simply updates the `srcObject` of the rendered `<video>`. If you have multiple streams that you want to control in sync, you might need another library.
