### ISSUE TITLE
Capture frames from video

### ISSUE THREAD

**Issue by Pieterism** [CookPete/react-player#638]
Is it possible to capture frames from the video ? I tried 
`const frame = captureVideoFramethis.player.getInternalPlayer())`

but it results in captureVideoFrame is not defined no-undef. 

any suggestions on how to handle the problem?

**Comment by CookPete** [comment]
> but it results in captureVideoFrame is not defined no-undef.

Make sure you include the [`capture-video-frame.js`](https://github.com/ilkkao/capture-video-frame/blob/master/capture-video-frame.js) code somewhere in your app. Note that the jsFiddle solution in https://github.com/CookPete/react-player/issues/341#issuecomment-368820250 includes it in the `Resources` list.

**Comment by Namyalg** [comment]
The const frame = captureVideoFramethis.player.getInternalPlayer()) doesnt update, even after seeking to a new time in the video using this.player.seekTo()

**Comment by devsirius44** [comment]
Once I use this, I could resolve this issue.
Actual code is below:

    function captureVideoFrame(video, format, quality) {
        if (typeof video === 'string') {
            video = document.getElementById(video);
        }

        format = format || 'jpeg';
        quality = quality || 0.92;

        if (!video || (format !== 'png' && format !== 'jpeg')) {
            return false;
        }

        var canvas = document.createElement("CANVAS");

        canvas.width = video.videoWidth;
        canvas.height = video.videoHeight;

        canvas.getContext('2d').drawImage(video, 0, 0);

        var dataUri = canvas.toDataURL('image/' + format, quality);
        var data = dataUri.split(',')[1];
        var mimeType = dataUri.split(';')[0].slice(5)

        var bytes = window.atob(data);
        var buf = new ArrayBuffer(bytes.length);
        var arr = new Uint8Array(buf);

        for (var i = 0; i < bytes.length; i++) {
            arr[i] = bytes.charCodeAt(i);
        }

        var blob = new Blob([ arr ], { type: mimeType });
        return { blob: blob, dataUri: dataUri, format: format };
    };

**Comment by Jimitriev** [comment]
> Once I use this, I could resolve this issue. Actual code is below:
> 
> ```
> function captureVideoFrame(video, format, quality) {
>     if (typeof video === 'string') {
>         video = document.getElementById(video);
>     }
> 
>     format = format || 'jpeg';
>     quality = quality || 0.92;
> 
>     if (!video || (format !== 'png' && format !== 'jpeg')) {
>         return false;
>     }
> 
>     var canvas = document.createElement("CANVAS");
> 
>     canvas.width = video.videoWidth;
>     canvas.height = video.videoHeight;
> 
>     canvas.getContext('2d').drawImage(video, 0, 0);
> 
>     var dataUri = canvas.toDataURL('image/' + format, quality);
>     var data = dataUri.split(',')[1];
>     var mimeType = dataUri.split(';')[0].slice(5)
> 
>     var bytes = window.atob(data);
>     var buf = new ArrayBuffer(bytes.length);
>     var arr = new Uint8Array(buf);
> 
>     for (var i = 0; i < bytes.length; i++) {
>         arr[i] = bytes.charCodeAt(i);
>     }
> 
>     var blob = new Blob([ arr ], { type: mimeType });
>     return { blob: blob, dataUri: dataUri, format: format };
> };
> ```
Awesome It was very helpful.
Thank you for you article.
I expect you do best continue.
