### ISSUE TITLE
Use HTML5 audio for SoundCloud tracks

### ISSUE THREAD

**Issue by CookPete** [CookPete/react-player#64]
After https://github.com/CookPete/react-player/issues/24#issuecomment-220315123, it looks like we can stop dealing with the SoundCloud SDK completely and just add the `stream_url` we get from the SC endpoint to an `<audio>` element, something we already do with `filePlayer`

**Comment by denisflorkin** [comment]
Hello, I managed to get something working that pretty much empty `SoundCloud` of all its code and have it inherit from `FilePlayer`, as you suggested.
The test are passing (in chrome only thought).
So here it is : https://github.com/CookPete/react-player/pull/65
