### ISSUE TITLE
Size according to video dimensions

### ISSUE THREAD

**Issue by pinkhoodie** [CookPete/react-player#641]
Is there any way to have the size of the video frame be the dimensions of the actual video? I'm trying to display videos of different dimensions (phone size, square, widescreen, etc.) without having the black margins on the side. I know how to resize the video, but not in a fashion that takes into consideration each videos initial dimensions. 

See attached image below to see what I mean by 'black margins'. I'd like react-player to inherit the dimensions of the video itself, in this case, landscape phone video. 

<img width="1202" alt="Screen Shot 2019-05-08 at 5 25 02 PM" src="https://user-images.githubusercontent.com/36429880/57409438-4826ce00-71b6-11e9-93e4-74da228b13e8.png"> 

Thanks!!

**Comment by CookPete** [comment]
You should be able to set `height='auto'` to just use the natural height of the video. Example: https://jsfiddle.net/8qbswxgh/
