### ISSUE TITLE
Offline Live stream Twitch permanent loading state

### ISSUE THREAD

**Issue by luiscerqueira** [CookPete/react-player#643]
#### Current Behavior
After passing an offline twitch stream url as a prop, the player will not switch/update to any other twitch video/stream url passed after it.

#### Expected Behavior
After passing an offline twitch stream url, it should be possible to play any other twitch video/stream url passed in the props.

#### Steps to Reproduce
1. Go to the demo page [#Demo](https://cookpete.com/react-player/)
2. Select Twitch `Test B` video
3. Select Twitch `Test C` stream
4. Select Twitch `Test B` video again

Step 3 forward, every url we pass to the component, the player will not change because he is stuck in an infinite loading state

#### Environment
- URL attempting to play:  
- Browser: Opera/Chrome/Firefox
- Operating system: Windows 10

#### Other informations
The Player only throw the onEnded event for the offline live stream.
Warning `ReactPlayer: the attempt to load https://www.twitch.tv/videos/12783852 is being deferred until the player has loaded` is appearing in the browser console

**Comment by luiscerqueira** [comment]
@CookPete 

I made a pull request (#657) with an implementation for this issue.
Would you please be able to take a look?

**Comment by CookPete** [comment]
Fixed in https://github.com/CookPete/react-player/pull/657
