### ISSUE TITLE
hide youtube player title, watch later and share icon

### ISSUE THREAD

**Issue by knowBalpreet** [CookPete/react-player#644]
Hi @CookPete , need help with the following points:
1. When using this player for youtube video I can see title, watch layer and share icon on youtube. is there a way to hide these?
2. Is there a way to disable onclick on the video element. I don't want to play pause a video by clicking on it. I want to do this with some external button.
3. Also, is there a way to disable keyboard shortcuts for youtube video? like for forward, rewind, volume, etc?

Thanks in advance!

**Comment by CookPete** [comment]
Completely hiding the title, share icon is not possible. As of August 2018 the `showinfo` player parameter was deprecated:

> The showinfo parameter, which indicates whether the player should display information like the video title and uploader before the video starts playing, is also being deprecated. Following the change, the channel avatar and video title will always display before playback begins, when playback is paused, and when playback ends. The avatar being displayed is new behavior that will be consistent across all embedded players.

https://developers.google.com/youtube/player_parameters#release_notes_08_23_2018

To disable any mouse interactions, try adding `pointer-events: none;` to a div that wraps the player.

To disable keyboard shortcuts, try [`disabledkb: 1`](https://developers.google.com/youtube/player_parameters#disablekb) in the playerVars:

```jsx
<ReactPlayer
  url='...'
  config={{ youtube: { playerVars: { disablekb: 1 } } }}
/>
```

**Comment by nitindaffodil** [comment]
Hi @cookpete , need help with the below points:

Can i disable right click option from mouse interactions
