### ISSUE TITLE
Some youtube videos does not provide thumbnail

### ISSUE THREAD

**Issue by sashberd** [CookPete/react-player#648]
#### Current Behavior
Thumbnail is not seen for https://youtu.be/wLzUSgnPuyc in light mode

#### Expected Behavior
Thumbnail is seen

#### Steps to Reproduce
I you pass the URL above to you component you will get 401 unauthorised from https://noembed.com/embed?url=https://www.youtube.com/embed/wLzUSgnPuyc

![Screen Shot 2019-05-21 at 11 05 25](https://user-images.githubusercontent.com/11975561/58078973-a2f9f580-7bb8-11e9-8d59-bac7fb1f6b08.png)

If you try to get this url  https://noembed.com/embed?url=https://www.youtube.com/watch?v=wLzUSgnPuyc you will not get this error and get valid JSON answer

- URL attempting to play:  https://youtu.be/wLzUSgnPuyc
- Browser: Chrome

**Comment by CookPete** [comment]
This works for me? Is there something else going on here? I don't know why it would try to use the `/embed/` URL to get the thumbnail from noembed.

![image](https://user-images.githubusercontent.com/1926029/58989986-e2415c80-87dc-11e9-937b-c7f50751cd92.png)

**Comment by sashberd** [comment]
@CookPete Look, the issue was from Youtube side. The customer adds this video as private and then changed it to public. In this case we got from this video such error. When the customer uploaded video directly as public all worked well. Thanks for your help
