### ISSUE TITLE
forceHLS not playable

### ISSUE THREAD

**Issue by pohsiu** [CookPete/react-player#649]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior

return src element is not rendering in properly
#### Expected Behavior

Use HLS to verify token and return video element.

#### Steps to Reproduce

```
<ReactPlayer
            url={`https://localhost:8443/api/roomVideos/${roomId}/csr.webm`}
            controls
            config={{
              file: {
                forceHLS: true,
                hlsOptions: {
                  xhrSetup: function(xhr, url) {
                    xhr.withCredentials = true
                    xhr.setRequestHeader('auth', 'value');
                  },
                }
              }
            }}
          />
```

#### Environment
- URL attempting to play: 
- Browser: 
- Operating system: 
- jsFiddle example: https://jsfiddle.net/sv5x3ug1

**Comment by CookPete** [comment]
There is not enough information here. What errors are you getting? Is this a problem with ReactPlayer or should an issue be opened with [`hls.js`](https://github.com/video-dev/hls.js/)?

**Comment by pohsiu** [comment]
@CookPete If I use forceHLS to get video source, that will not playable,
But it works fine in normal way
