### ISSUE TITLE
Making the player invisible play in the background

### ISSUE THREAD

**Issue by NinjaOnRails** [CookPete/react-player#650]
Passing height and width = 0% to SoundcloudPlayer as props throws the error below, though it kind of works and the player can't be seen. Should it be done by selecting the elements of the HTML the component generates and add CSS instead? Thank you

`Failed to execute 'createPattern' on 'CanvasRenderingContext2D'`

**Comment by CookPete** [comment]
I would suggest `visibility: hidden` or `opacity: 0` and `pointer-events: none` for an invisible player. Using a `0%` size or `display: none` can cause browsers to deem the media as invisible and not play.

However, be aware that modern browsers are slowly adopting a no-autoplay policy, so an invisible player could soon be useless, as it would require user interaction to play.
