### ISSUE TITLE
StrictMode warnings for unsafe lifecycle methods

### ISSUE THREAD

**Issue by rares-lupascu** [CookPete/react-player#651]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior
```react
Warning: Unsafe lifecycle methods were found within a strict-mode tree:
    in StrictMode (at src/index.tsx:54)

componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: Player

componentWillUpdate: Please update the following components to use componentDidUpdate instead: ReactPlayer
```

#### Expected Behavior
No warning :)

#### Steps to Reproduce

1. Add the player under <React.StrictMode>

#### Environment
- URL attempting to play: n/a
- Browser: n/a
- Operating system: n/a
- jsFiddle example: no need

#### Other Information
n/a

**Comment by jaytula** [comment]
I've created a pull request #692 implement the two instances of `componentWillUpdate` as `componentDidUpdate`.
