### ISSUE TITLE
Playing multi videos not working

### ISSUE THREAD

**Issue by seeatend** [CookPete/react-player#656]
The multiple videos are not played in react-player
#### Current Behavior
I passed the url as array but it plays only one video

#### Expected Behavior
I'd like to play two videos continuously

#### Environment
- URL attempting to play: 'http://techslides.com/demos/sample-videos/small.webm'
- Browser: Chrome
- Operating system: mac OS
- jsFiddle example: 
https://jsfiddle.net/maz128/gqe6tmvk/2/ or https://jsfiddle.net/maz128/gqe6tmvk/6/

Please give me any tips asap
Thank you

**Comment by CookPete** [comment]
There is no native support for this. You would need to store an array index in state, and cycle through the array to update the `url` of the player in your app.

Quick and dirty example: https://jsfiddle.net/g8x9pjma/

**Comment by Domino987** [comment]
@CookPete Hi I would like to try this and need your example.
But the link does not work anymore. Can you maybe share your code here?

**Comment by CookPete** [comment]
It was only the `VIDEOS` array that was broken. Updated with a couple of random youtube videos: https://jsfiddle.net/2tr1fshc/
