### ISSUE TITLE
you tube play/pause controls not working on Chrome

### ISSUE THREAD

**Issue by keoki33** [CookPete/react-player#661]
#### Current Behavior
You tube play/pause controls not working on Chrome. Works in firefox and safari

#### Expected Behavior
able to play pause videos with prop change

#### Steps to Reproduce
Tested on both my react project and your demo website:
https://cookpete.com/react-player/
clicking play button, I receive this error:
utils.js:133 ReactPlayer: YouTube player could not call playVideo – The method was not available

#### Environment
all test videos in demo website for youtube in chrome browser

**Comment by husseindebel** [comment]
the demo website seems to work as expected on my chrome browser.

my version of chrome: Version 74.0.3729.169

What was your version of chrome when you tested it?

**Comment by keoki33** [comment]
Thank you for testing this. I am using latest version 75.0.3770.80 on both mac and pc. I am closing this, all works fine if I am in incognito mode. Will continue to troubleshoot on my end, I am assuming an extension is causing the issue. Thank you again and sorry for wasting your time. Lesson learned, test with all add ons and extensions disabled.
