### ISSUE TITLE
No audio from Facebook Test A and B in Chrome 

### ISSUE THREAD

**Issue by mgw-sbic** [CookPete/react-player#663]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior

Facebook Test A and test B on the test page do not play audio on latest chrome.
#### Expected Behavior

Video plays with audio track.
#### Steps to Reproduce

1. Visit https://cookpete.com/react-player/ in chrome 74.0.3729.169 (Official Build) (64-bit)
2. Click the Facebook A test. Video plays with no sound.
3. Click the Facebook B Test. Video plays with no sound.

#### Environment
- URL attempting to play: 
https://cookpete.com/react-player/ 
- Browser: 
chrome 74.0.3729.169 (Official Build) (64-bit)
- Operating system: 
MacOS Mohave 10.14.5
- jsFiddle example: https://jsfiddle.net/sv5x3ug1

**Comment by CookPete** [comment]
Working fine for me..

- Chrome 75.0.3770.90 (Official Build) (64-bit)
- macOS Mojave 10.14.4

**Comment by mgw-sbic** [comment]
Hey I updated to your Chrome release:

Google Chrome is up to date
Version 75.0.3770.90 (Official Build) (64-bit)
as I said I'm on 10.14.5.

Still not working, no audio.

**Comment by CookPete** [comment]
Is there anything else that might be preventing audio from playing?

The weird thing about audio in Facebook videos is that when autoplay is enabled they are muted by default, so we manually unmute here:

https://github.com/CookPete/react-player/blob/ad5d6df62635497137a184cf93a9c43ba6b08fbb/src/players/Facebook.js#L44-L47

My guess is that this step is failing on your machine, but I have no idea why.

@mgw-sbic Does muting and unmuting on the demo page fix the problem?

**Comment by cullanshewfelt** [comment]
I'm having the same issue on Chrome Version 75.0.3770.90 (Official Build) (64-bit).

I tried toggling the mute but the problem persisted. 
All other audio players worked for me.

**Comment by mgw-sbic** [comment]
Clicking the mute/unmute button does nothing. Clicking the "controls" button brings up the audio control which shows muted. Unmuting that control starts the audio track.

**Comment by CookPete** [comment]
I'm gonna need some detailed steps on how to reproduce this. I can't really attempt to fix this without being able to make this happen on my machine.
