### ISSUE TITLE
video not play using google drive url

### ISSUE THREAD

**Issue by ianrajs** [CookPete/react-player#665]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Steps to Reproduce

1.
1.
1.

#### Environment
- URL attempting to play: 
- Browser: 
- Operating system: 
- jsFiddle example: https://jsfiddle.net/sv5x3ug1

**Comment by CookPete** [comment]
Please use the issue template.

**Comment by Tikam02** [comment]
React Player not able to load Google Drive Videos

**Comment by abrahamvallez** [comment]
Is this still currently unavailable? @cookpete??
