### ISSUE TITLE
[Question] Is there any way to set a ref to internal video element?

### ISSUE THREAD

**Issue by AtaruOhto** [CookPete/react-player#666]
Hi @CookPete 

Thank you for the great library. Our developer team are trying to implement an education application with react-player.
Implementing with raw video element tag really tormented us due to the low compatibility among browsers and react-player saved us.

Our system has fullscreen feature and we'd like to rely on react-use because this library has fallback feature for fullscreen video on iOS.
react-use requires setting a ref to video element directly (RefObject<HTMLVideoElement>) to call webkitEnterfullscreen() via the ref in their library.

https://github.com/streamich/react-use/blob/master/docs/useFullscreen.md
https://github.com/streamich/react-use/blob/master/src/useFullscreen.ts#L47

But it seems that react-player wrapped ref doesn't have webkitEnterfullscreen() and can't call this method inside react-use and we can't implement fullscreen feature on iOS.
We would greatly appreciate if there are ways to set a ref to internal video element directly in ReactPlayer and you tell us.

Best regards,

```
import React, { useRef } from 'react'
import Video from 'react-player'

import useFullscreen from 'react-use/lib/useFullscreen'
import useToggle from 'react-use/lib/useToggle'

export const OurPlayer: React.FC = () => {
  const videoRef = useRef<Video>(null)
  const [fullscreenOn, onFullscreenChange] = useToggle(false)
  const isFullscreen = useFullscreen(null, fullscreenOn, {
    onClose: () => onFullscreenChange(false),
    /* this ref need to be the ref to videoElement and has webkitEnterfullscreen */
    video: videoRef,
  })

  return (<Video
    controls={false}
    height="100%"
    playsinline
    /* here we set ref */
    ref={videoRef}
    url={src}
    width="100%"
  />)
}
```

#### Current Behavior
RectPlayer can't set a ref to video element directly.
ReactPlayer wrapped ref doesn't have webkitEnterfullscreen method.

#### Expected Behavior
ReactPlayer can set a ref to video element directly or ReactPlayer wrapped ref has webkitEnterfullscreen method.

#### Environment
- Browser: iOS (Mobile Safari)
- Operating system: iOS

**Comment by CookPete** [comment]
You should be able to use `getInternalPlayer()` on the ReactPlayer ref to return the `<video>` element?

https://github.com/CookPete/react-player#instance-methods

**Comment by AtaruOhto** [comment]
@CookPete 
Thank you and sorry for late response.
We'll manage to pass the video element to react-use by invoking getInternalVideo().
But it requires some code lines and might not be straightforward.
In our opinion, if we were able to call video element method like webkitEnterFullscreen() directly via ReactPlayer ref, it would be helping.

I'll close the issue.
Thank you for your kind support.
