### ISSUE TITLE
Issues with initial play of facebook video in Chrome

### ISSUE THREAD

**Issue by mikaelengstrom** [CookPete/react-player#667]
#### Current Behavior
Setting the prop "playing" to `true` do not start to play the video if it have not been played before in chrome. Its kind of a schrödinger bug which does not always reproduce, but at least for me it is consistent in chrome incognito mode.

#### Expected Behavior
Setting the prop "playing" to `true` should start playing the video as it does in other browsers.

#### Steps to Reproduce
1. Go to `https://cookpete.com/react-player/` in Chrome incognito mode
2. Click Facebook "Test A"
3. Click `Play` – It does not play

If you from here click the video it will start playing and after that everything works as expected

#### Environment
- URL attempting to play: https://cookpete.com/react-player/
- Browser: Chrome
- Operating system: OSX

**Comment by mikaelengstrom** [comment]
After some research I have figured out that this happens due to Chrome autoplay policy and is tightly coupled with this issue: https://github.com/CookPete/react-player/issues/663. 

Everything works as expected if this part is removed:
https://github.com/CookPete/react-player/blob/ad5d6df62635497137a184cf93a9c43ba6b08fbb/src/players/Facebook.js#L44-L47

However the video will obviously be muted when doing so. Also if you unmute the video via the player API after it starts playing, Chrome will stop playing the video and dump the following in console:
`Unmuting failed and the element was paused instead because the user didn't interact with the document before. https://goo.gl/xX8pDD`

So according to the autoplay policy, Chrome will not allow you to play the video with sound without interacting with the actual `<video>` element first.

This is very problematic for a library like this and I have no idea what to do with this. However, I think it would be better to play muted videos than to violate auto play policy and is therefore in favour of removing the unmute logic referenced above.

Any ideas from maintainers?

**Comment by CookPete** [comment]
>However, I think it would be better to play muted videos than to violate auto play policy and is therefore in favour of removing the unmute logic referenced above.

The problem is that this policy is (currently) only the case in recent versions of Chrome. Removing the `unmute` step will break non-muted autoplaying facebook videos on all other browsers, where videos play without issue. 

If you want to avoid the problem, just pass in `muted={true}` by default and set it to `false` when a user interacts with the video.

> This is very problematic for a library like this

[Yep.](https://github.com/CookPete/react-player/issues?utf8=%E2%9C%93&q=autoplay) It's even [mentioned in the readme](https://github.com/CookPete/react-player#autoplay).

**Comment by mikaelengstrom** [comment]
Thanks for reply. Did miss that entry in readme since Im not doing autoplay and therefore thought it did not address my problem :)  Would you mind if I attempted to restructure the readme in a way that hopefully will catch the eye for people with similar problems?

Im thinking something like:

##known issues and limitations
### polyfills
### autoplay
### facebook player
blablabla

**Comment by CookPete** [comment]
>Would you mind if I attempted to restructure the readme in a way that hopefully will catch the eye for people with similar problems?

This sounds like a good idea, although I am quite particular about readmes, so don't be offended if I add more changes :)
