### ISSUE TITLE
Loop prop not working as intended on Vimeo Player

### ISSUE THREAD

**Issue by burkel24** [CookPete/react-player#668]
#### Current Behavior
The loop prop does not seem to currently be working for the Vimeo player. Specifically, I'm setting loop to false but the video element still has the loop attribute set.

```
// Video elm still has loop set to true
<ReactPlayer
	url={VIDEO_URL}
    ref={this.playerRef}
    loop={false}
/>
```

I've been able to work around this by setting the loop prop to true initially, then setting it to false once the video is ready, forcing setLoop to be called.

```
// constructor
this.state = { loop: true };

...

// renderPlayer
const onReady = () => {
	setTimeout(() => this.setState({ loop: false }));
}

<ReactPlayer
	url={VIDEO_URL}
    ref={this.playerRef}
    onReady={onReady}
    loop={loop}
/>
```

#### Expected Behavior
The loop prop should be respected if it is initially set to false. From looking at player.js it seems like setLoop needs to be called after the onReady callback fires

#### Steps to Reproduce
1. Set loop prop to false with vimeo url (haven't tested other platforms)
2. Play video
3. Inspect video element inside iFrame
4. Observe loop attribute is set on <video>

#### Environment
- Browser: Chrome Version 74.0.3729.169
- Operating system: MacOS 10.14.5

#### Other Information
Thanks for maintaining this project, its been super helpful.

**Comment by CookPete** [comment]
Do you have a `jsFiddle` example of this happening? I'm trying to reproduce this myself but I can't see `loop` being set anywhere if it's set to false.
