### ISSUE TITLE
Warning: Failed propType: Invalid prop 'volume' of type 'string' supplied to 'Vimeo', expected 'number'. Check the render method of 'ReactPlayer'.

### ISSUE THREAD

**Issue by bobbydp** [CookPete/react-player#67]
I seem to always get this warning even though the volume works property works fine. Am I writing this incorrectly? Here is how I have it inside my React Component:

`<ReactPlayer className="react-player" url={videoLink} playing width="100%" height="100%" volume="1" onEnded={this.handleStop} />;`

This seems minor seeing as the volume property works flawlessly.

**Comment by gridsane** [comment]
Props in quotes is always strings. Use curly braces to pass exact type:

```jsx
<ReactPlayer volume={1} />
```

**Comment by bobbydp** [comment]
Thank you! I am learninggggg...
