### ISSUE TITLE
Activating auto-generated subtitles in youtube

### ISSUE THREAD

**Issue by nirber** [CookPete/react-player#671]
According to:
https://support.google.com/youtube/answer/171780?hl=en&ref_topic=3014330
it's possible to specify caption language by adding for example: "&cc_lang_pref=es&cc_load_policy=1"

To have Sapnish caption, such as:
https://www.youtube.com/embed/hahvUXwTXE4?cc_lang_pref=vi&cc_load_policy=1&autoplay=1

Is it possible to specify caption language in a similar way to the embed?

Thanks!

**Comment by CookPete** [comment]
Any player parameters can be set using `config.youtube.playerVars`, including `cc_lang_pref` and `cc_load_policy`:

```jsx
<ReactPlayer
  url={url}
  config={{
    youtube: {
      playerVars: { 
        cc_lang_pref: 'vi',
        cc_load_policy: 1
      }
    }
  }}
/>
```

More info [in the readme](https://github.com/CookPete/react-player#config-prop).
