### ISSUE TITLE
Documentation update - getInternalPlayer()

### ISSUE THREAD

**Issue by paulincai** [CookPete/react-player#672]
Not sure but it might be that the documentation (Readme) needs to be updated with this: https://github.com/CookPete/react-player/issues/393#issuecomment-386569395

**Comment by CookPete** [comment]
Since that issue was closed I've updated `getInternalPlayer` to allow you to access the hls.js instance easily:

> Use `getInternalPlayer('hls')` to get the hls.js player

This is [in the readme already](https://github.com/CookPete/react-player#instance-methods). I'll update the original issue too.
