### ISSUE TITLE
Upgrade from version 1.2.1 to 1.11.1

### ISSUE THREAD

**Issue by eTheMan80** [CookPete/react-player#675]
I have upgraded the player from 1.2.1 to 1.11.1. There's an issue when trying to play Youtube videos, it instead plays Vimeo videos.

I expect all Youtube and Vimeo vidos to play depending on the url.

On the current version 1.2.1, I get a 404 error on the network tab using Chrome for this 'https://vimeo.com/api/oembed.json?url=https%3A%2F%2Fvimeo.com%2F127250231&autopause=false&autoplay=false&byline=false&portrait=false&title=false&url=https%3A%2F%2Fvimeo.com%2F127250231&loop=false'

**Comment by CookPete** [comment]
>There's an issue when trying to play Youtube videos, it instead plays Vimeo videos.

What URL are you trying to play? What props are you using? Can you recreate the problem in a forked jsFiddle? https://jsfiddle.net/sv5x3ug1

>I get a 404 error on the network tab using Chrome

This looks like an issue with [vimeo/player.js](https://github.com/vimeo/player.js) rather than this library. The error is from `vimeo.com/...` – ReactPlayer has no control over what the Vimeo player API requests.

**Comment by eTheMan80** [comment]
@cookPete The issue is the preload set to true was breaking Youtube videos playing. I've recreated the issue on https://jsfiddle.net/m2yv8L4s/3/

**Comment by eTheMan80** [comment]
@CookPete to give context, I'm dynamically passing urls from a server so in config I've got preload for both Youtube and Vimeo videos. In this case when loading Youtube videos, the preload video for Vimeo is also loading.

**Comment by thunderkid** [comment]
I've just noticed something that may be related. In updating from 1.11.0 to 1.11.1, I suddenly start seeing a (distorted and pixellated) soundcloud player where I'd expect a youtube player.

@eTheMan80 : Have you tried version 1.11.0 instead?
