### ISSUE TITLE
Error : Super expression must either be null or a function after building

### ISSUE THREAD

**Issue by Energizz** [CookPete/react-player#676]
#### Current Behavior
When I build my app with react-player I've got this error :
Uncaught TypeError: Super expression must either be null or a function
Just : import { ReactPlayer } from "react-player"; Lead to this error

#### Expected Behavior
Should not print this error (It's working with start with webpack dev server)

#### Steps to Reproduce
1. Add react-player into package json
2. Build using webpack
3. App cannot start because of error (Work properly if I remove react-player from my package.json)

#### Environment
- Browser: Chrome 75.0
- Operating system: Mac OS X Mojave 10.14.5 

#### Other Information
Maybe related to different react version ? 
Can be related to webpack configuration ?

Thanks ! :)

**Comment by cyberwookiee** [comment]
Seeing the same thing.  Changing webpack mode from production to development seems to fix the issue, but not a long-term solution...

**Comment by CookPete** [comment]
Hopefully this thread helps: https://github.com/airbnb/react-dates/issues/1456

It looks like a problem with older versions of `uglifyjs` and the webpack plugin for it.
