### ISSUE TITLE
IE11 Issue - Error when playing clip [object Event]

### ISSUE THREAD

**Issue by adrianmiles** [CookPete/react-player#677]
#### Current Behavior
I have a React-Table with one of the columns having a react-player component in it.
The component doesn't play when clicking play in IE 11. The component updates to the "playing" state visually but no sound is played back and progress doesn't change either.

On page load the error below is thrown for every react-player component on the page
```
Error when playing clip [object Event]
   "Error when playing clip"
   {
      [functions]: ,
      __proto__: {
         [functions]: ,
         __proto__: { },
         AT_TARGET: 2,
         bubbles: <Permission denied>,
         BUBBLING_PHASE: 3,
         cancelable: <Permission denied>,
         cancelBubble: <Permission denied>,
         CAPTURING_PHASE: 1,
         constructor: { },
         currentTarget: <Permission denied>,
         defaultPrevented: <Permission denied>,
         eventPhase: <Permission denied>,
         isTrusted: <Permission denied>,
         srcElement: <Permission denied>,
         target: <Permission denied>,
         timeStamp: <Permission denied>,
         type: <Permission denied>
      },
      AT_TARGET: 2,
      bubbles: false,
      BUBBLING_PHASE: 3,
      cancelable: false,
      cancelBubble: false,
      CAPTURING_PHASE: 1,
      constructor: {
         [functions]: ,
         __proto__: { },
         AT_TARGET: 2,
         BUBBLING_PHASE: 3,
         CAPTURING_PHASE: 1,
         prototype: { }
      },
      currentTarget: { },
      defaultPrevented: false,
      eventPhase: 2,
      isTrusted: true,
      srcElement: { },
      target: { },
      timeStamp: 1562846999679,
      type: "error"
   }

```
#### Expected Behavior
Expected clip to play when play is clicked

#### Steps to Reproduce

1. Using IE 11 with babel polyfill
2. Using [react-table](https://github.com/tannerlinsley/react-table/tree/v6/docs/src/examples) with column that has voice clip component in it 
3. Clip is a mp3 file

#### Environment
- URL attempting to play: any, even tried the default provided on the [react-player site](https://cookpete.com/react-player/)
- Browser: IE 11
- Operating system: Windows 10
-React-player is imported with 
`import ReactPlayer from 'react-player';`

**Comment by CookPete** [comment]
Are you sure the `mp3` you are trying to play is in the correct encoding etc? It looks like this is a problem with IE11, not with ReactPlayer, judging by the [various search results for this problem](https://www.google.com/search?rlz=1C5CHFA_enGB790GB790&ei=y9NOXZycEcGD8gLy0oXQDQ&q=ie11+mp3+cannot+play&oq=ie11+mp3+cannot+play&gs_l=psy-ab.3..0i71l8.0.0..6813...0.0..0.0.0.......0......gws-wiz.U51DDMirkVU&ved=0ahUKEwjcreL5wPjjAhXBgVwKHXJpAdoQ4dUDCAo&uact=5).
