### ISSUE TITLE
Change YouTube control color

### ISSUE THREAD

**Issue by ScottAgirs** [CookPete/react-player#678]
Hey there, great work on the package!

Trying to change the color on YouTube controls:

```javascript
 <ReactPlayer
               ..
            config={{
              youtube: {
                  playerVars: {
                    color: 'white',
                    controls: 1,
                    rel: 0
                  }
              },
              ..
          }}
/>
```

does this seem right? Am I missing something?

Many thanks in advance!

**Comment by CookPete** [comment]
Config looks good. It's working for me: https://jsfiddle.net/oktj09nm/

The only real difference I can see is the initial play button and the seeker dot. What else are you expecting to change?
