### ISSUE TITLE
[Chrome] Unmounted player can be played when unmounted, using media keys

### ISSUE THREAD

**Issue by burtyish** [CookPete/react-player#682]
#### Current Behavior
Scenario:
After the player has started playing, using the global media play key will cause it to start playing agin. You will be able to hear the audio.

#### Expected Behavior
Once the player is unmounted, I expect that the video will not be able to play anymore.

#### Steps to Reproduce

1. Player is mounted and starts playing video
1. Player **unmounted**
1. When I click the <kbd>play</kbd> media key on my keyboard or touchbar (▶️ or  ⏯), the video's audio start to play! On Chrome, I can see the sound  icon on the tab.

#### Environment
- URL attempting to play: http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4
- Browser: Chrome 75.0.3770.142
- Operating system: MacOS Mojave 10.14.5
- codesandbox example: https://codesandbox.io/s/react-player-cs6xk

#### More info
- The issue did not reproduce on Safari or Firefox. So this might be a Chrome bug.
- Related to Chrome's Hardware Media Key Handling, which is enabled by default since Chrome 73.

**Comment by CookPete** [comment]
The thorough issue report is appreciated, but unfortunately I don't think there's anything we can do about this. Maybe [file a bug with Chromium](https://www.chromium.org/for-testers/bug-reporting-guidelines)?

**Comment by leovivanco** [comment]
Hi @burtyish, did you find any solution to this?

**Comment by burtyish** [comment]
Not really. I ended up disabling hardware media controls on Chrome. So I
can't say if it's been solved or not right now.
