### ISSUE TITLE
Funny behavior on iOS in combination with MediaDevices.getUserMedia

### ISSUE THREAD

**Issue by silently** [CookPete/react-player#684]
#### Steps to Reproduce
* A video is started with ReactPlayer, then the native back button is pressed
* The back event is catched by react-router (so the webpage is not refreshed) and I go to another route that renders: a component enabling the mobile device video stream with MediaDevices.getUserMedia
* Safari asks for permission
* If I say yes: the sound of the previously started video is played!

#### Environment
- Browser: safari on iOS 12.3.1 (not happening on Android devices)

I guess this is more an iOS bug, but here is the workaround I've found and I am willing to share if it helps someone else: force `this.setState({ playing: false})` before the ReactPlayer is unmounted. The problem is the `playing` state used to control the player is *in* the render method, and while unmounting the render may not be called afterwards... That is why I find it would be nice to have `play` `pause` instance methods (on the reachable player *ref*) like `seekTo`.

Thanks!

**Comment by CookPete** [comment]
You can use `getInternalPlayer()` if you want to manipulate the internal player instance, including calling `play` and `pause`, if they are available.

This does sound like an iOS-specific bug. If the ReactPlayer is unmounted the video or audio should never be playable later on, as everything should be destroyed.

@silently What URL are you playing initially? Are there any player methods that will help to destroy the instance of whatever is play, that we can call when unmounting?

**Comment by silently** [comment]
Hello, I'll close the issue since indeed, it does not look like a ReactPlayer bug.
The URL points to a media file (m4a video).

I've tried `this.playerRef.current.getInternalPlayer().pause();` when the component unmounts with not success (the iOS bug remains).

Here is the workaround that worked:
* MyComponent renders (simplified) `<ReactPlayer playing={ this.state.playing } ...>`
* I have access to a history props thanks to [withRouter](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/withRouter.md)
* I can thus catch a native back event and stop playing:
```js
props.history.block((location, action) => {
  if (action === 'POP') {
    this.setState({ playing: false });
  }
});
```

Changing `this.setState({ playing: false });` in `componentWillUnmount` dit not work (since the component does not re-render after unmounting, changing the state had not effect).
