### ISSUE TITLE
Changing audio output destination?

### ISSUE THREAD

**Issue by toschlog** [CookPete/react-player#685]
Is is possible to change the audio output destination?  I think I could do it if I had access to an <audio> or <video> elements, but I'm not sure if that's possible here.

Thanks.

**Comment by CookPete** [comment]
I'm not sure exactly what you mean, but when playing a file URL you can access the raw `<video>` or `<audio>` element with the `getInternalPlayer()` instance method: https://github.com/CookPete/react-player#instance-methods
