### ISSUE TITLE
Could not set progress of mp3 sometimes

### ISSUE THREAD

**Issue by wufeng87** [CookPete/react-player#686]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior

![image](https://user-images.githubusercontent.com/1686808/62337883-008bb600-b509-11e9-9182-c207bf65ca44.png)

#### Expected Behavior
Could set progress by draging the ProgressBar

#### Steps to Reproduce
render three instance of Player that play mp3 file.

#### Environment
- URL attempting to play: 
- Browser:  chrome lastest
- Operating system:  mac os

**Comment by CookPete** [comment]
This works ok for me on latest Chrome, even when playing simultaneously: https://jsfiddle.net/gsqkrm1x/

Feel free to reopen if you can make a jsFiddle that demonstrates the problem.
