### ISSUE TITLE
Cannot play live stream video from facebook

### ISSUE THREAD

**Issue by nakinthorn** [CookPete/react-player#688]
I try to enter facebook live video URL into React-Player
ex: https://www.facebook.com/therealagusrianzz/videos/699427433836005/
but it not work!!!!

(Twitch live is work fine)

**Comment by CookPete** [comment]
This is working for me: https://jsfiddle.net/gnqdx8pa/

It is possibly because the user was not live at the time you checked?

Feel free to reopen if you can create a jsFiddle to demonstrate the problem.
