### ISSUE TITLE
CORB (Cross-Origin Read Blocking) blocks requests to vimeo/youtube videos

### ISSUE THREAD

**Issue by tini2n** [CookPete/react-player#689]
#### Current Behavior
Every time, when video changes (vimeo), CORB warn goes to console. On third time – request didn't come at all. So video didn't changing.

![image](https://user-images.githubusercontent.com/10106572/62713728-e28cec80-ba05-11e9-8ecf-b9ba5504a7d5.png)

I use 1.7.1 version

**Comment by CookPete** [comment]
Check out https://github.com/vimeo/player.js/issues/420
