### ISSUE TITLE
Unable to play black background color, and want to play video in native size

### ISSUE THREAD

**Issue by connektind** [CookPete/react-player#691]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Steps to Reproduce

1.
1.
1.

#### Environment
- URL attempting to play: 
- Browser: 
- Operating system: 
- jsFiddle example: https://jsfiddle.net/sv5x3ug1

**Comment by connektind** [comment]
I am trying to remove black background color and trying to play video in native size like youtube. but unable to remove it.
Please anyone can suggest me how can I achieve it .
Thanks

**Comment by CookPete** [comment]
Please use the issue template if you want to reopen this. It's there for a reason. 

>I am trying to remove black background color

What URL are you trying to play? Pretty much every player API loads with a black background by default, so I'm not sure anything can be done about this.

> trying to play video in native size like youtube. but unable to remove it.

Have you seen the readme section on styling a [Responsive Player](https://github.com/CookPete/react-player#responsive-player)?
