### ISSUE TITLE
Youtube IOS Controls

### ISSUE THREAD

**Issue by paulincai** [CookPete/react-player#702]
Looking for a suggestion other than disable controls/player and link to Youtube app on the phone or Youtube website.

#### Current Behavior
Youtube Player info  and share button cover IOS top controls. Image attached.
![IMG_517FDE2F9784-1](https://user-images.githubusercontent.com/26188915/63558212-0ea78200-c55d-11e9-9589-7fab741cf7fe.jpeg)

#### Expected Behavior
Obviously would like to be able to unmute

#### Environment
Latest version React Player, Iphone 6, IOS 12.3

**Comment by CookPete** [comment]
This is how the Youtube Player API behaves on iOS. There is nothing this library can do about this. I would suggest posting with the `youtube-iframe-api` tag on StackOverflow as suggested here: https://developers.google.com/youtube/players/support
