### ISSUE TITLE
No volume in Chrome for youtube player

### ISSUE THREAD

**Issue by aaadamgo** [CookPete/react-player#707]
#### Current Behavior
I've got a video component in my react application, I'm using Chrome 76. I'm not autoplaying the video. Looks like a standard youtube embed. It is not muted. But, if I click to play, there's no sound. However, in Firefox, the sound is heard fine.

Here's the code for my component.

```
import React from 'react';
import ReactPlayer from 'react-player/lib/players/YouTube';

import { Jacket } from './moduleVideoStyles';

export default class ModuleVideoPlayer extends React.Component {
    render() {
        return (
            <>
                <Jacket>
                    <ReactPlayer
                        url={this.props.source}
                        width="100%"
                        height="100%"
                        config={{
                            youtube: {
                                playerVars: {
                                    volume: 1,
                                    muted: false,
                                    autoPlay: 0,
                                    playinline: 1,
                                    modestbranding: 1,
                                }
                            },
                        }}
                    />
                </Jacket>
            </>
        )
    }
}
```

I previously had this instead...
```
<ReactPlayer
     url={this.props.source}
     width="100%"
     height="100%"
     autoplay={false}
     controls
     playsinline
     volume={1}
/>
```
But this does the same thing. Tried searching for hours for solutions and can't find anything. Any help would be appreciated.

**Comment by CookPete** [comment]
This seems very strange.. Does the same thing happen on the demo page?

**Comment by aaadamgo** [comment]
@CookPete Demo page works perfectly fine in Chrome, but my local version has just has no sound output. However, a friend of mine said it worked fine for him (when he viewed through vsliveshare).

**Comment by CookPete** [comment]
Sounds like something weird going on locally with your machine/specific setup?

**Comment by mpkelly** [comment]
For posterity: check the tab in Chrome and see if it has a muted icon as you could have muted the site by mistake like I did just now.
