### ISSUE TITLE
Cant catch click event on embedded player

### ISSUE THREAD

**Issue by jp3492** [CookPete/react-player#708]
#### Current Behavior
I click on the embedded Youtube player and "click" event on document nor window is being called

#### Expected Behavior
When i click on the embedded player that i can somehow get that click event

I want to have shortcuts to control the player, but when i focus the embedded player no events are being captured by my js

Also, my ref on the player is the correct player object, but when calling player.getInternalPlayer() i always get undefined

This is my player Comp, nothing special
<ReactPlayer
      onPlay={() => setPlaying(true)}
      onPause={() => setPlaying(false)}
      playing={playing && selected}
      className={selected ? "player-selected" : ""}
      width="100%"
      height="100%"
      config={playerVars}
      url={url}
      ref={player => addPlayer(url, player)}
      onReady={() => updateLinkStatus(url, TAB_LOADING_STATUS.READY)} />

I also tried to addEventListeners to all iframes in my document, but also click events are not captured

My goal is it to change focus from the embedded player everytime its focused, so i can capture all document click and keydown events.

Any suggestions on that issue?

Thanks a lot in advance

**Comment by CookPete** [comment]
I'm pretty sure iframe clicks will be consumed by the iframe content, and not make it to the containing document. See [here](https://gist.github.com/jaydson/1780598) for a potential hack to detect an iframe click.

**Comment by RusseII** [comment]
I'm not sure if this is the same issue that you were having but I had a similar issue where clicking on the player didn't pause/play the video 

example of issue - https://codepen.io/Geczy/pen/MWWpaoL (Can't click on the video to play it in Chrome)

To fix it, add webkitallowfullscreen mozallowfullscreen allowfullscreen to the iframe

fix - https://codepen.io/svenwritescode/pen/ExxWVMP
