### ISSUE TITLE
Light mode - return to custom poster onEnded?

### ISSUE THREAD

**Issue by lonepalmus** [CookPete/react-player#709]
#### Expected Behavior
It would be nice to have an option to return to the poster image after video has ended playing if possible?

#### Steps to Reproduce

1. Set light prop to image URL.
2. Play video to end.

#### Environment
- Browser: Chrome
- Operating system: macOS Mojave

**Comment by paulincai** [comment]
Check this recent commit: https://github.com/CookPete/react-player/commit/59586caae8f224c668a95768fbcb344c42f41097

On video ended, call the set of preview.

**Comment by CookPete** [comment]
Yep, basically what @paulincai said:

```jsx
<ReactPlayer 
  url={url}
  ref={p => this.p = p}
  onEnded={() => this.p.showPreview()}
/>
```

**Comment by Receiver412** [comment]
i add this 
  ref={p => this.p = p}
  onEnded={() => this.p.showPreview()}
in my ReactPlayer component:

      <ReactPlayer
        className='react-player'
        url= {url}
        controls={true}  
        width={"100%"}
        height={"400px"}
        fluid={true}
        playing
        playIcon={<img src={playIcon} alt="playIcon" />}
        light={Img1}
        config={{ file: { 
          attributes: {
            disablepictureinpicture: 'false',
            crossorigin: 'anonymous',
            controlsList: 'nodownload noremoteplayback'
          }
        }}}
        ref={p => this.p = p}
       onEnded={() => this.p.showPreview()}

  />
But it gives me this Message:
TypeError: Cannot set property 'p' of undefined

**Comment by CookPete** [comment]
@Receiver412 Are you using a functional component? The use of `this` will only work with a class-based component. For functional component you'll need to use `createRef` to keep a reference to the player instance.

**Comment by Receiver412** [comment]
I use function component

**Comment by kaond001** [comment]
how to increase poster height in react player before video start playing

**Comment by n9exorcist** [comment]
I have totally 4 div's(className="image") with the same code, but found out the overlay image is appearing only in the last video of the Carousel. For the first three div's, on ended is triggered, but overlay image is not showing up.

const ref = React.useRef(null);

  <div className="image">
          <div
            className="vimeo-container"
            style={{
              height: "100%",
            }}
          >
            <ReactPlayer
              id="react-playerid"
              ref={ref}
              className="react-player"
              url={url}
              width="100%"
              height="70%"
              controls={true}
              playing={true}
              loop={false}
              light={placeHolderImage}
              pip={false}
              playIcon={false}
              onEnded={() => ref.current.showPreview()}
            />
          </div>
        </div>

**Comment by anusingh-cue** [comment]
The above solution seems fine but trying to access the current instance of ref throws error.
ref.current.showPreview()
error - Object is possibly 'null'.

**Comment by tomi1368** [comment]
I´m using forwardRef and useImperativeHandle for use player functions in parent component. I need to know in the parent video duration. 

When I call getDuration function It returns undefined, but if  I make another interaction before. Function returns the video duration 


```
<CustomPlayer
                                videoCurrent={videoCurrent}
                                ref={ref}
                                playerHeight="419px"
                                video={videoCurrent.preview}
                                CustomPlay={TrianglePlay}
                                lightImage="https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/800px-Image_created_with_a_mobile_phone.png"/>
```
Player Component:

```
let playerRef: any = useRef(null);
useImperativeHandle(
      ref,
      () => ({
        resetLight: () => {
          console.log("peron");
          if (playerRef.current) playerRef.current.showPreview();
          setLightOn(true);
        },
        getDuration: () => {
          if (playerRef.current) {
            console.log("aaxxxxx", playerRef.current.getDuration());
            return playerRef.current.getDuration();
          }
        },
      }),
      [playerRef]
    );

<Player
          controls={false}
          width={"100%"}
          height={"100%"}
          ref={playerRef}
          url={video}
          playIcon={
            <LightWrapper onClick={() => setLightOn(false)}>
              <CustomPlay onClick={() => setLightOn(false)}></CustomPlay>
            </LightWrapper>
          }
          light={lightImage}
          playing={isPlayed}
          muted={isMuted}
          volume={volume}
          onSeek={onSeek}
          onProgress={handleOnProgress}
          onClick={(ev) => {
            playerWapperRef.current.focus();
          }}
          onEnded={() => {
            if (playerRef.current) {
              playerRef.current.seekTo(0);
              setCurrentSeek(0);
              setIsPlayed(false);
            }
          }}
          onDuration={(e) => {
            getDuration(e);
          }}
          onBuffer={handleBufferStart}
          onBufferEnd={handleBufferEnd}
          onReady={(player) => (playerRef.current = player)}
        />



```

**Comment by cHoMpDiSs** [comment]
this worked for me

const VideoPlayer = () => {

    const ref = useRef(null)

    return (
        
        <ReactPlayer 
        playing={true}
        loop={false}
        muted
        light="images/susaf.png"
        poster="images/susaf.png"
        url="videos/susaf.mp4"
        width='100%'
        height='100%'
        controls = {true}
        ref={ref}
        onEnded={() => ref.current.showPreview()}
        />
