### ISSUE TITLE
Support srcset for thumbnail in light mode

### ISSUE THREAD

**Issue by jhodges10** [CookPete/react-player#712]
I'm using react player with Gatsby, and I've love to be able to use the srcset created by gatsby-image-fluid for the thumbnail in the player's light mode.

**Comment by CookPete** [comment]
The light mode thumbnail uses `background-image` in order for the thumbnail to fill the player regardless of width or height.

There's no reason you couldn't implement your own light mode, with a `srcset` image that is switched with a `<ReactPlayer>` on click?

**Comment by jhodges10** [comment]
I'll give that a shot @CookPete
