### ISSUE TITLE
About m4v, m4a support.

### ISSUE THREAD

**Issue by KevinChien** [CookPete/react-player#72]
Hi All,
    Would you add "m4v" and "m4a" into the extension condition:
    const VIDEO_EXTENSIONS = /\.(mp4|og[gv]|webm|mov)($|\?)/i
    const AUDIO_EXTENSIONS = /\.(mp3|wav)($|\?)/i
    Which in file: 
               src/players/FilePlayer.js
    Because I assign src *.m4a and *.m4v, the <video> and <audio> cannot add type="video/mp4|audio/mp3"
    
    Thanks a lots.
Regards
Kevin.Chien

**Comment by CookPete** [comment]
Fixed in `0.7.2`
