### ISSUE TITLE
YouTube Lightmode - Increase noembed thumbnail resolution

### ISSUE THREAD

**Issue by Jebble** [CookPete/react-player#720]
#### Current Behavior
Enabling light mode on a YouTube embed without a custom image url currently loads the thumbnail from YouTube using the hqdefault.jpg thumbnail which is 480p wide. Even for today's high-end smartphones this is a small resolution.

#### Expected Behavior
I expect a bigger resolution image to be loaded, which is 
http://i.ytimg.com/vi/<video_id>/maxresdefault.jpg

**Comment by olistic** [comment]
@CookPete Would you accept a PR for this?

**Comment by Jebble** [comment]
I did just find out that a maxresdefault.jpg is not always available and then throws a 404. Something to consider.

**Comment by CookPete** [comment]
Yeah it's hard when `maxresdefault.jpg` might not be available. If there was a way to know without too much hackery then that would be ideal, but as it's done via `backgroundImage` it seems a bit tricky.

**Comment by sashberd** [comment]
@CookPete This one was closed cause was fixed?

**Comment by CookPete** [comment]
@sashberd This can't really be fixed. See my previous comment. We can't know if `maxresdefault.jpg` is available so I'm not sure what can be done. You can always pass in your own thumbnail src to the `light` prop if you can figure out a way of doing it yourself.

**Comment by sashberd** [comment]
@CookPete I just return to solve this issue in our app.
I found this solution works for us, maybe it will work for you too
 ```
const [imageFileName, setImageFileName] = useState('maxresdefault');
  useEffect(() => {
    new Promise((resolve, reject) => {
      if (youtubeMovieId) {
        const img = new Image();
        img.onerror = () => resolve();
        img.src = `https://img.youtube.com/vi/${youtubeMovieId}/maxresdefault.jpg`;
      } else {
        reject();
      }
    }).then(() => {
      setImageFileName('hqdefault');
    });
  }, []);
```

**Comment by TristanWiley** [comment]
Here's the solution I ended up with which uses some help from @sashberd 's logic. However unfortunately onerror won't happen since an image is always returned. So we want to check the width/height of the image

```
  const [hasHQImage, setHasHQImage] = useState(true);

  const youtubeMovieId = "bla";

  useEffect(() => {
    const checkImage = () => {
      const img = new Image();

      img.onload = () => {
        if (img.naturalWidth === 120 && img.naturalHeight === 90) {
          setHasHQImage(false);
        }
      };

      img.src = `https://img.youtube.com/vi/${youtubeMovieId}/maxresdefault.jpg`;
    };

    checkImage();
  }, [youtubeMovieId]);
```

Then if there's a HQ image available, I use that URL in the `light` prop. Otherwise I default to `true` and let `ReactPlayer` handle it

```
light={
  hasHQImage
    ? `https://img.youtube.com/vi/${youtubeMovieId}/maxresdefault.jpg`
    : true
}
```

**Comment by zehawki** [comment]
For whose who search for this, and reach here, here's an update:

1. Regular YT videos - highest res thumbnail is found at `https://i.ytimg.com/vi/${videoID}/maxresdefault.jpg`
2. Shorts - highest res thumbnail is found at `https://i.ytimg.com/vi/${videoID}/oardefault.jpg`
