### ISSUE TITLE
Livestream Issiue

### ISSUE THREAD

**Issue by picklerick66** [CookPete/react-player#721]
Hello There :)

I tried to enter Livestream link from livestream.com it not work... It works when I enter another livestream links like in issue #688.

[click for example for livestream.com link](https://livestream.com/accounts/7475784/events/8817566)

I also tried to give as a custom URL in react-player demo page... still no response.

The last thing that I tried is changing the iframe s src attribute It works sometimes but not always... I don't get why this is happening is there any special case?

https://jsfiddle.net/order66/2ya1xgL3/7/

**Comment by CookPete** [comment]
Hey! Unfortunately ReactPlayer doesn't support Livestream.com videos. It will fallback to the file player if it can't play a URL with any of the [supported players](https://github.com/CookPete/react-player#supported-media).
