### ISSUE TITLE
Get subtitles from the video to show separately in my site?

### ISSUE THREAD

**Issue by sontek** [CookPete/react-player#722]
This is more of a question than a bug report.   I'd like to display the transscript / subtitles on my site and not on the player itself (I don't like the way the youtube subtitles look).   Is it possible to get this information similar to how we get the time and all that?

**Comment by CookPete** [comment]
I think for this you'd have to call the YouTube Data API separately to fetch the caption data. This might get you started: https://developers.google.com/youtube/v3/guides/implementation/captions#captions-download

I can't see anything in the [YouTube Player API](https://developers.google.com/youtube/iframe_api_reference) that enables you to access or intercept the caption data.
