### ISSUE TITLE
Configureable Seek Time for Arrow Keys

### ISSUE THREAD

**Issue by yuvi17** [CookPete/react-player#724]
#### Current Behavior

Currently, when the player is in focus, pressing the left or right arrow keys seeks the video to -2 and +2 seconds respectively.

Is there a way to configure this duration (or override this behaviour)

P.S.: I tried adding an event listener of `onKeyDown` and doing a `seekTo(currentTime+10)`, but this would do a seek to +12 seconds (10 by this code and 2 by the player).
Doing a +8 seems like a very bad hack to me. 

Any thoughts on this?

**Comment by CookPete** [comment]
Could you `e.preventDefault()` to stop the normal 2 second seek? Then your `seekTo(currentTime+10)` will be correct?

**Comment by yuvi17** [comment]
@CookPete Hey, thanks for the suggestion. However, there seems to be something off with `e.preventDefault()` and React. There are many articles on the internet with respect to binding on the content of `this`, but I feel that should not be an issue with function components.  I tried with arrow functions as well but it still seeks to `12` secs instead of 10
Here is the code snippet if it may help:
```javascript
import React from 'react';
import FilePlayer from 'react-player/lib/players/FilePlayer';

function ContentPlayer(props) {
  // some props handling

  let player;
  // I know this should be 10, but the player natively adds a 2 sec seek
  // that I am unable to configure, so this extremely stupid(but working) hack.
  // const SEEK_DURATION = 8;
 const SEEK_DURATION = 10; // FOR THIS TEST

 

  function ref(playerInstance) {
    player = playerInstance;
  }

  function onStart() {
    // handle onStart
  }

  function onPause() {
    // handle pause
  }

  function onEnded() {
    // handle end
  }

  const handleKeyPress = (event) => {
    const currentTime = player.getCurrentTime();
    console.log(event);
    console.log(event.preventDefault()); // this is undefined
    if (event.which === 39) {
      event.preventDefault();
      player.seekTo(currentTime + SEEK_DURATION);
    } else if (event.which === 37) {
      event.preventDefault();
      player.seekTo(currentTime - SEEK_DURATION);
    }
  };

  return (
    <div className="">
      <FilePlayer
        ref={ref}
        url="https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8"
        controls
        onKeyDown={handleKeyPress}
        onStart={onStart}
        onPause={onPause}
        onEnded={onEnded}
        pip={false}
      />
    </div>
  );
}

export default ContentPlayer;
```
I'm slightly new to React, so please pardon anything that sounds silly or stupid. 
Once again, thanks a lot for your help.

**Comment by CookPete** [comment]
I think you're right about `preventDefault`. I can't seem to stop it from skipping ahead one second more than I specify (Chrome 78 on macOS). See example here (right button only, not left): https://jsfiddle.net/jdc4nv80/

Just a weird browser quirk maybe?

**Comment by EmptyCrown** [comment]
Was there a resolution for this? As far as I can tell, the default increment always runs.

**Comment by dinhkellie** [comment]
Interested in finding a resolution for this! `event.preventDefault()` isn't consistent for me so I have to resort to +- 8 seconds in order to achieve 10 seconds
