### ISSUE TITLE
Is it possible to move the video controls below the player?

### ISSUE THREAD

**Issue by kaloraat** [CookPete/react-player#726]
I know almost all media players on the internet have done it the same way as you guys. The **video controls are in the bottom of the player**, as we hover they appear/disappear.

But I want to **move the controls below the actual player** so that even when i play, pause, volume... whatever i do, **it will not block the actual video**. This is specially great for coding tutorials.
I wonder why no have actually done it this way. Anyways if it is possible, I would be very happy to know. Thanks!

**Comment by yuvi17** [comment]
@kaloraat Not a maintainer here but you can implement almost all the controls below the players using the methods and callback events provided. You can just put `controls=false` and implement your own `play`, `pause`, `fullscreen` and `seek` methods below the player without much difficulty.

**Comment by CookPete** [comment]
The player controls you see when the `controls` prop is true are simply the built in controls for whatever URL you are playing. @yuvi17 is right in that you can simply not set the `controls` prop, and build your own controls using the various props and callback. The [demo app](https://github.com/CookPete/react-player/blob/master/src/demo/App.js) is a rough example of this.
