### ISSUE TITLE
`style` prop does not get applied

### ISSUE THREAD

**Issue by coreyward** [CookPete/react-player#727]
The documentation includes a `style` prop for passing an inline style object to the element, but at least the FilePlayer doesn't honor this:

https://github.com/CookPete/react-player/blob/1e41ce5ce5e2d6946701723f60e74326385df92d/src/players/FilePlayer.js#L312-L324

It would be useful to have a `className` prop passed down if there's some reason for `style` to be withheld.

**Comment by CookPete** [comment]
The `style` prop applies to the wrapper div, that the `<video>` element is inside:

https://github.com/CookPete/react-player/blob/1e41ce5ce5e2d6946701723f60e74326385df92d/src/ReactPlayer.js#L159-L161

You can override the `style` of the `<video>` (or add a className) with `config.file.attributes`:

https://github.com/CookPete/react-player/blob/1e41ce5ce5e2d6946701723f60e74326385df92d/src/players/FilePlayer.js#L321-L331

For example:

```jsx
class Player extends React.Component {
  render () {
    return (
      <div className='player-wrapper'>
        <ReactPlayer
          url='http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4'
          playing
          config={{ 
            file: { 
              attributes: {
                className: 'video-player',
                style: { width: '480px', height: '360px' }
              } 
            } 
          }}
        />
      </div>
    )
  }
}
```

**Comment by coreyward** [comment]
Ah, so the style prop doesn’t work if you’re importing a single player as suggested in the README.

**Comment by CookPete** [comment]
It should work in the same way, by applying `style` to the wrapper div:

https://github.com/CookPete/react-player/blob/1e41ce5ce5e2d6946701723f60e74326385df92d/src/singlePlayer.js#L60-L63
