### ISSUE TITLE
React , HLS : Detaching player before changing source  

### ISSUE THREAD

**Issue by ahmad-crossplatform** [CookPete/react-player#729]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior
 I am using React-Player to play hls videos , when I change the source from one video to another , I alway get some errors from hls,js , nothing fatal but still annoying , things like `bufferAppendError` and other. 

I looked at the hls.js github [here](https://github.com/video-dev/hls.js/issues/1858)  and it seems that i need to 

> detach -> change src-> attach;

How can I do that ? please have some code samples  or describe with some steps because I am a beginner in the react/ web development world . 

#### Expected Behavior

 When changing the srouce of the media , the player should be detached and attached somehow in the player . 
#### Steps to Reproduce

1. Have multiple sources for hls media for example 

2. Change the source in the player , in my case  i bound the source with hooks 
3.  Open up the developer console on chrome (F12) 

#### Environment
- URL attempting to play: 
```
	const sources = [
		"https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8",
		"https://mnmedias.api.telequebec.tv/m3u8/29880.m3u8",
		"http://qthttp.apple.com.edgesuite.net/1010qwoeiuryfg/sl.m3u8"
	];
```
- Browser: Chrome 
- Operating system:  MacOs 

- CodeSandbox  example: https://codesandbox.io/s/react-player-toggle-different-hls-soruces-jrj2q

#### Other Information
I have created a sandbox sample for that , and I suggest you guys use Sandbox to show samples which is better than jsfiddle imho .

**Comment by ahmad-crossplatform** [comment]
So I found the solution  but watching a conference about hooks , as i am using hooks to change the source , i can use the same state for the `key` of the reacplayer element , so every time the source changes , the key would recreate a new instance of the player and would play that new source.  
Me as a person coming from C# world would never guess that :) 
I am have wrote the solution  for the same example  [here ](https://codesandbox.io/s/react-player-toggle-different-hls-soruces-dpbnx)

**Comment by subvertallchris** [comment]
@ahmad-crossplatform, thank you for sharing this! It described my use case, the problem, and the solution perfectly. Thank you!
