### ISSUE TITLE
videos from vimeo won't play on mobile devices

### ISSUE THREAD

**Issue by capaj** [CookPete/react-player#73]
I have tested this on chrome 51 on android.
The error I get is:
player.js:10 Uncaught (in promise) DOMException: play() can only be initiated by a user gesture.

So just disabling autoplay could fix this, right?

**Comment by CookPete** [comment]
Yeah this sounds about right. See the [mobile considerations](https://github.com/CookPete/react-player#mobile-considerations) part of the readme. Most mobile browsers strictly prevent autoplay on mobile to reduce unwanted mobile data usage.

**Comment by capaj** [comment]
@CookPete thanks, I did not read readme.md, I was mostly just looking at the examples before implementing. I needed autoplay on desktop, so in the end I solved it by:

```
class Video extends React.Component {
  state = {
    url: null,
    playing: typeof window.orientation === 'undefined',
    volume: 0.8,
    played: 0,
    loaded: 0,
    duration: 0
  }

```

**Comment by CookPete** [comment]
Perhaps there should be a mobile browser check within the library that warns when attempting to autoplay..

**Comment by capaj** [comment]
@CookPete that is what I was thinking as well. That error can be caught and video could be initialized with a state of `playing: false` and warning could be shown.

This error could catch some people like me off guard, because everybody develops on desktop, not mobile.
