### ISSUE TITLE
Error rendering Twitch demo video

### ISSUE THREAD

**Issue by SiroDiaz** [CookPete/react-player#733]
#### Current Behavior
When i set the demo Twitch url in my local project the player is not rendered. With YouTube, Vimeo and Dailymotion it works. I'm using the latest version of react-player (1.13.0).

#### Expected Behavior
Render the player and the video normally.

#### Steps to Reproduce

1. Using a localhost alias, for example example.test create a React project with nginx as reverse proxy.
2. Inside a component, create a simple log methods this.onDuration and this.onProgress and write:
```jsx
<ReactPlayer
  ref={this.ref}
  className="watch__embed-container"
  controls={true}
  width='100%'
  height='100%'
  url={`https://www.twitch.tv/videos/106400740`}
  playing
  onDuration={this.onDuration}
  onProgress={this.onProgress}
/>
```
#### Environment
- URL attempting to play: https://www.twitch.tv/videos/106400740
- Browser: Google Chrome 78
- Operating system: Windows 10
- jsFiddle example: I don't know how to import ReactPlayer with jsFiddle.

#### Other Information
![error](https://user-images.githubusercontent.com/7469286/67761562-d54f2f00-fa43-11e9-9044-664658ebcbfe.png)

**Comment by CookPete** [comment]
This can happen when `playerId` is not correct here:

https://github.com/CookPete/react-player/blob/1e41ce5ce5e2d6946701723f60e74326385df92d/src/players/Twitch.js#L32

`playerID` should be `twitch-player-` plus a random string:

https://github.com/CookPete/react-player/blob/1e41ce5ce5e2d6946701723f60e74326385df92d/src/players/Twitch.js#L18

Is the ID not being set correctly in your DOM?

**Comment by SiroDiaz** [comment]
The random string id is well generated in my DOM. For example `twitch-player-8rn47`, as you can see.
![Anotación 2019-10-29 234559](https://user-images.githubusercontent.com/7469286/67815169-753da480-faa6-11e9-827c-29cc0a799a30.png)

**Comment by jackhenry** [comment]
I'd just like to chime in and say that I'm experiencing the same issue with all Twitch embeds. [Here's a codesandbox if this helps.](https://codesandbox.io/s/upbeat-hopper-kiqqt?fontsize=14)

**Comment by CookPete** [comment]
@SiroDiaz There must be something wrong with your specific environment or implementation. Your example code works fine for me in jsFiddle with `v1.13.0`: https://jsfiddle.net/gx5802o9/

@jackhenry Your example doesn't work because https://www.twitch.tv/p/watch/esfand isn't a valid Twitch URL. Visiting it gives me a 301 redirect to https://www.twitch.tv/p/watch/esfand which then returns a 404 page.

**Comment by SiroDiaz** [comment]
@CookPete i think the same. I'm going yo try others things. If i don't solve the problem i will notice you more about muy environment

**Comment by jackhenry** [comment]
@CookPete Sorry, I was in a rush. [Try this](https://jsfiddle.net/3ruhp71e/3/)

I've double checked that link and that's the same format for the twitch urls I've been using.

The issue is with the controls property. If set to false, I just get a black screen. If it's set to true, it works. You can replace the url with any other url and the issue should be the same.

Also note, I've only got this issue with embedded twitch live streams. Not embedded twitch videos.

**Comment by CookPete** [comment]
>The issue is with the controls property. If set to false, I just get a black screen. If it's set to true, it works. You can replace the url with any other url and the issue should be the same.

So it only breaks for live streams when `controls={false}`? I can add a note to the readme but this seems like a bug with the twitch player.

**Comment by jackhenry** [comment]
@CookPete You're probably right. The Twitch Dev team is notorious for introducing breaking bugs without any notice.

It appears to be an issue with the format of the url used for the iframe.

This doesn't work: [https://player.twitch.tv/?allowfullscreen&video=&channel=yogscast&!playsinline&!autoplay&!muted&!controls&origin=http%3A%2F%2Flocalhost%3A3000](https://player.twitch.tv/?allowfullscreen&video=&channel=yogscast&!playsinline&!autoplay&!muted&!controls&origin=http%3A%2F%2Flocalhost%3A3000)

This does work [https://player.twitch.tv/?allowfullscreen&video=&channel=yogscast&!playsinline&!autoplay&!muted&origin=http%3A%2F%2Flocalhost%3A3000](https://player.twitch.tv/?allowfullscreen&video=&channel=yogscast&!playsinline&!autoplay&!muted&origin=http%3A%2F%2Flocalhost%3A3000)

The only difference between the two is ```!controls``` is present in the url that doesn't work, and it isn't present in the one that works.

The first url is what React-Player generates if the controls property is set to false.

**Comment by SiroDiaz** [comment]
I found the error @CookPete . I'm using next.js for server side rendering. When the player is rendered in the browser Twitch works perfectly, but when the page is reloaded, it says:

![server-side-error-rendering-twitch](https://user-images.githubusercontent.com/7469286/68124501-d84c9280-ff0f-11e9-8479-7500f7946d86.png)

So, what conclusion? I'm going to investigate if my server is wrong (for example render twice or redux error with second rendering) but could you check if something in react-player has incompatibilities with server side rendering with nextjs?
Thanks

**Comment by SiroDiaz** [comment]
Example here: [nextjs with Twitch video](https://github.com/SiroDiaz/sample-next-react-player-app)
