### ISSUE TITLE
Feature request: Add Vidyard and Hubspot Video Support

### ISSUE THREAD

**Issue by josephfung** [CookPete/react-player#735]
It would be fantastic if support for Vidyard (which also powered Hubspot Video) were added. Happy to collaborate on making it happen as well.

In case it would help, here are some of the documentation pieces I would recommend referencing:

[Vidyard Player API (responsive player layout)](https://knowledge.vidyard.com/hc/en-us/articles/360019034753), or
[Vidyard Legacy Player API (non-responsive)](https://knowledge.vidyard.com/hc/en-us/articles/360009871054-How-to-use-the-Vidyard-Player-API)

**Comment by JohnMusleh** [comment]
any plans or updates for this?

**Comment by CookPete** [comment]
I don't want to add support for other types of video before I refactor a bit to enable lazy loaded players. Right now the default export includes the code to play all types of URL, even if you are only ever using one type.

Just a case of getting enough free time...

**Comment by josephfung** [comment]
@CookPete Thanks for the explanation, that's helpful to understand.

I realize this is a side-project, would something like a bounty be of help?

FWIW I checked, but didn't see any Patreon, buymeacoffee, or other sponsorship links on your profile...happy to be pointed that way 👍

**Comment by CookPete** [comment]
@josephfung I've been meaning to for a long time. Just set one up now: https://www.patreon.com/cookpete

**Comment by josephfung** [comment]
Great! Done!! Thanks again for the great component!

**Comment by CookPete** [comment]
@josephfung Try out some Vidyard URLs with `react-player@2.0.0-alpha.1` and let me know if they work. 🎉

**Comment by josephfung** [comment]
@CookPete Amazing! thank you! 🙏 Works perfectly! 

I see there were a lot of changes to incorporate that lazy-loading too - both sets of changes are very much appreciated!

**Comment by CookPete** [comment]
Yeah the lazy players was a result of #738 so I figured the 2.0 alpha would be a good way to quickly get something working to you. 

Glad to hear it's working. Thanks so much for becoming a patron! If you know any other formats of Vidyard URL that people may use, let me know so I can adjust the regex. 👍

**Comment by josephfung** [comment]
Thanks - I'll check with the team.

Off the top of my head, the only variation I know of, is that people can set a vanity URL (so other than `share.vidyard.com` the domain could be something like `videos.mydomain.com`). Not as many people do that, though, so I'm not sure if it's really a big use-case.

Either way - this is great, thanks! We have a PR in code review already incorporating the new version :D

**Comment by CookPete** [comment]
@josephfung `v2.0.0` is here!
