### ISSUE TITLE
Native player controls ignoring 'playing' prop

### ISSUE THREAD

**Issue by cdreier** [CookPete/react-player#737]
I want to use the native controls, but also pause the player with the `playing` prop. I have a few timestamps within my video and i want to jump to them and pause the player.

```jsx
const playerRef = useRef<ReactPlayer>()
const [playing, setPlaying] = useState(false)

useEffect(() => {
  setPlaying(false)
  playerRef.current.seekTo(playhead, 'seconds')
},        [playhead]) // playhead is set on click on a timestamp

<ReactPlayer
  ref={playerRef}
  playing={playing}
  url={url}
  controls={true}
  />
```

#### Current Behavior

if the player is started from the native controls, it ignores the `playing` prop.

if i control the player only with the `playing` prop, everything is working

#### Expected Behavior

regardless of the type of controls i use, the video should play and pause according the `playing` prop.

#### Environment
- Browser: Version 78.0.3904.87
- Operating system: Fedora 31

**Comment by CookPete** [comment]
@cdreier What URL are you trying to play? And do you get the same problem with other types of URLs (ie other players) or just the one?

**Comment by cdreier** [comment]
Hi @CookPete , 

thanks for your fast response!

i tested with hls and dash streams - both with the same behaviour - and i think i found a hint: 

* the video starts with native controls - i cannot pause ith with `setPlaying(false)`
* while the video is playing, i set the flag `setPlaying(true)` and `setPlaying(false)` after - its working as intended, perhaps the internal state not aligned with the native controls?

i made a small video, showing my issue a bit better :) 

https://streamable.com/9jnnr

**Comment by CookPete** [comment]
Ah, my guess is that the internal [`isPlaying`](https://github.com/CookPete/react-player/blob/6d57ef35c4fc8469bb006a9aacfd15a5ba57fb71/src/Player.js#L14) flag is getting messed up, because you aren't updating your `playing` state on the play/pause events. If you pause using native controls and don’t update your own `playing` state, you're still passing `playing={true}` to the player, so clicking your own play button will do nothing.

Try keeping your `playing` state up to date with `onPlay` and `onPause`:

```jsx
<ReactPlayer
  ref={playerRef}
  playing={playing}
  url={url}
  controls={true}
  onPlay={() => setPlaying(true)}
  onPause={() => setPlaying(false)}
/>
```

**Comment by cdreier** [comment]
will test it, but the two buttons had plain booleans in it, not the playing flag itself

```jsx
<button onClick={() => setPlaying(false)} >pause</button>
<button onClick={() => setPlaying(true)} >start</button>
```

**Comment by cdreier** [comment]
your solution with the `onPlay` and `onPause` callbacks are working! 

thanks a lot :+1:

**Comment by cdreier** [comment]
as i think the additional callbacks are more a workaround, read a bit through the code 

in https://github.com/CookPete/react-player/blob/master/src/Player.js#L55 are checks for the `prevProps.playing` and if it toggled - but the native controls, does not change the props. Can we just remove the `prevProps.playing` checks?

if the new props want the player to pause, why not just pause?

**Comment by CookPete** [comment]
> callbacks are more a workaround

The callbacks aren't really a workaround. They are the only way to keep your `playing` state accurate (and avoid bugs) if you show native controls. If you are passing `playing={true}` to the player and it may or may not be playing, that sort of breaks the whole declarative nature of ReactPlayer (and React in general).

>in https://github.com/CookPete/react-player/blob/master/src/Player.js#L55 are checks for the prevProps.playing and if it toggled - but the native controls, does not change the props. Can we just remove the prevProps.playing checks?

I don't think this makes any sense. We want to `pause()` the player only when `playing` changes from `true` to `false`. Same for all other methods. If we stopped looking at `prevProps` the component would become very trigger happy with calling methods, and likely introduce more problems. Do we really want to `play()` or `pause()` every time any prop changes? Even volume?

**Comment by cdreier** [comment]
Hi @CookPete ,

thanks a lot for your time and this project!

i agree with you, in alomst all points :) 

i try to write some code to better clarify what i wanted to say

``` js
// started, player is not playing
// let's play with `playing` props
// prevProps.playing = false  playing = true  this.isPlaying = false
if (!prevProps.playing && playing && !this.isPlaying ) {
  // success
  this.player.play()
}

// pause also works fine
// prevProps.playing = true  playing = false  this.isPlaying = true
if (prevProps.playing && !playing && this.isPlaying) {
  // success
  this.player.pause()
}

// now let me start it with native controls, no props are changing, 
// only this.isPlaying = true
// now i want to pause the started player with the playing prop

// prevProps.playing = false  playing = false  this.isPlaying = true
if (prevProps.playing && !playing && this.isPlaying) {
  // no pause :( 
  this.player.pause()
}
```

in the last statement, the player is still playing, because the check of `prevProps.playing` fails, so we cannot pause it.

the callbacks are not aligning my state with the internal controls, but setting the `prevProps.playing` to a state that fits the current logic

if we just ignore the prevProps

``` js
if (!playing && this.isPlaying) {
  this.player.pause()
}
```
we do check the current playing prop and we do also only pause if the player is playing!

from a declarative point of view,i would assume that if i pass in a `playing = false` prop, that the player pauses, independent from the past props

```jsx
<ReactPlayer
  playing={false}
/>

// player still playing -> ???
```

what i read so far, you could just remove `prevProps.playing` without breaking anything?

**Comment by CookPete** [comment]
I understand your point, but removing the `prevProps.playing` check just brings bugs:

- Initialise a player with `controls={true}`
- `playing` defaults to `false`
- Start playing the player with native controls (internal `isPlaying` becomes `true`)
- Change the volume of the player via the `volume` prop
- Player will pause.. because you are still passing `playing={false}` even though the video is being controlled natively.

**Comment by cdreier** [comment]
Alright, so thanks a lot for the discussion :)

As we have a solution and will not change anything, I close this issue.

Best regards,
Christian
