### ISSUE TITLE
Feature request: lazy players

### ISSUE THREAD

**Issue by trurl-master** [CookPete/react-player#738]
Motivation: On my page I don't know what player will be used in each particular case and many of the players will never be used, so I would like to lazily load only one player in each particular case.

Something like this:

```javascript
import React, { Suspense, lazy } from 'react'
import { whichPlayerCanPlay } from 'react-player'

const players = {
  youtube: () => import('react-player/lib/players/YouTube'),
  vimeo: () => import('react-player/lib/players/Vimeo'),
  file: () => import('react-player/lib/players/FilePlayer')
}

const MyPlayer = (props) => {
  const { url } = props

  const playerName = whichPlayerCanPlay(url, { players: ['youtube', 'vimeo', 'file'] })

  if (!playerName) {
    return null
  }

  const LazyPlayer = lazy(players[playerName]);

  return (
    <Suspense fallback={<div>Loading...</div>}>
      <LazyPlayer {...props} />
    </Suspense>
  )
}

```

The problem here is that the `canPlay` logic is inside of each individual player file and to know whether a player is capable of playing the url I need to download it. Could the `canPlay` logic be extracted from each individual player to a separate file?

**Comment by CookPete** [comment]
Hey @trurl-master, yeah this has been on my radar for a long time. It would reduce the bundle size massively and essentially render the single player imports redundant. I can look at implementing this, but don't have an exact timeline.

**Comment by CookPete** [comment]
I've pushed my first attempt at this as an alpha version of `2.0.0` (as there are a few breaking changes). Try it out with:

```
npm install react-player@2.0.0-alpha.0
```

**Comment by ramlez** [comment]
> (as there are a few breaking changes)

Hi, @CookPete could you please let know what braking changes are in 2.0 version? I've successfully added the alpha version to my project and haven't spotted any breaking changes or problems yet.

**Comment by CookPete** [comment]
@ramlez Namely the single player functionality eg 

```js
import YouTubePlayer from 'react-player/lib/players/YouTube'
```

becomes pretty much redundant, as only the Youtube player will be loaded if you only ever use a Youtube URL.

I should be able to get a bit closer to releasing this in the next couple of days.

**Comment by CookPete** [comment]
I'm also considering removing the `preload` functionality and leaving it as a legacy feature in older versions – autoplay policies are making it redundant, and it's a fairly hacky feature anyway.

**Comment by dbismut** [comment]
Hey @CookPete @trurl-master, until `Suspense` and `lazy` support SSR rendering, maybe you could consider using [Loadable Components](https://loadable-components.com/) instead?

**Comment by CookPete** [comment]
`v2.0.0` is now here, which includes lazy loading players using `lazy` and `Suspense`. @dbismut unfortunately I had written all the lazy logic before your comment. 

Is there much benefit to including the lazy player code in SSR? Most of the time the only thing rendered is a single `div` or `iframe`, which is populated on the client when the third party player API loads.

**Comment by dbismut** [comment]
@CookPete it's not so much that SSR actually makes sense in this case, but rather than using `Suspense` and `lazy` will break SSR. In other words, if you have a look at[ this sandbox using Gatsby](https://codesandbox.io/s/fast-monad-iu37p?file=/src/pages/index.js:300-370 ), and if you try to build it, you will have the following error.

<img width="642" alt="image" src="https://user-images.githubusercontent.com/5003380/80291128-2ae26b00-874b-11ea-9ccc-dab13aa1a3eb.png">

... which redirects to this page: https://reactjs.org/docs/error-decoder.html/?invariant=294

Let me know if you prefer that I open a separate issue for this, as someone will open it sooner or later.

**Comment by tubbo** [comment]
^ i also had the above issue, wondering what to do about it...

**Comment by CookPete** [comment]
Is there a quick fix for Suspense to just not render anything during SSR, rather than breaking things? This seems like a stupid problem to have when ReactPlayer doesn’t really benefit from rendering anything on the server.

**Comment by dbismut** [comment]
Well, I guess you could detect if you're server-side:

```jsx
const isBrowser = (typeof window !== 'undefined' && window.document)
return <div>{ isBrowser && <Suspense /> }</div>
```

**Comment by ericnation** [comment]
It's also breaking my Gatsby build with the same exact error posted by @dbismut. Wondering exactly how to get around this?

**Comment by tubbo** [comment]
@ericnation I downgraded to 1.15.3 and that fixed the build and got me past this issue, but I don't really need any of these lazy/suspense features, so YMMV.

**Comment by winstonma** [comment]
@ericnation I guess you can use the method mentioned by @dbismut to get rid of the problem.

Just wonder if `(typeof window !== 'undefined' && window.document)` would be included in react-player?

**Comment by dbismut** [comment]
> Just wonder if (typeof window !== 'undefined' && window.document) would be included in react-player?

That’s the idea indeed!

**Comment by CookPete** [comment]
This should be fixed in `v2.0.1`

**Comment by milesalex** [comment]
Can you add this to the docs? Im trying to figure out how to improve load time.

**Comment by CookPete** [comment]
Note that from `v2.2.0`, the lazy loading version of ReactPlayer has moved to `react-player/lazy`. See [MIGRATING.md](https://github.com/CookPete/react-player/blob/master/MIGRATING.md) for more info.

I'm not considering it a breaking change as things won't actually break – the only impact will be a slightly bigger bundle size until you start importing from `react-player/lazy`.

I've added clarification to the readme to only use it if your build pipeline supports dynamic `import()` statements.

**Comment by alex-major-digital** [comment]
> @cookpete it's not so much that SSR actually makes sense in this case, but rather than using `Suspense` and `lazy` will break SSR. In other words, if you have a look at[ this sandbox using Gatsby](https://codesandbox.io/s/fast-monad-iu37p?file=/src/pages/index.js:300-370), and if you try to build it, you will have the following error.
> 
> <img alt="image" width="642" src="https://user-images.githubusercontent.com/5003380/80291128-2ae26b00-874b-11ea-9ccc-dab13aa1a3eb.png">
> 
> ... which redirects to this page: https://reactjs.org/docs/error-decoder.html/?invariant=294
> 
> Let me know if you prefer that I open a separate issue for this, as someone will open it sooner or later.

I'm getting this error - I'm on version 2.11.2.

Any ideas?

**Comment by cookpete** [comment]
@alex-major-digital Are you importing `react-player` or `react-player/lazy`? The check for `IS_BROWSER` in https://github.com/cookpete/react-player/commit/54f48c06cb06786ba8344dee5d8abee8dfa1bd2c isn’t perfect so I would guess `IS_BROWSER` is `true` for whatever platform you are using, so it’s trying to render `Suspense` which is not supported.

It’s been over three years now since I added the `lazy` stuff. Clearly it is not written in the best way. If you can figure out why `IS_BROWSER` is true, a PR with a fix would be very welcome.

**Comment by alex-major-digital** [comment]
> @alex-major-digital Are you importing `react-player` or `react-player/lazy`? The check for `IS_BROWSER` in [54f48c0](https://github.com/cookpete/react-player/commit/54f48c06cb06786ba8344dee5d8abee8dfa1bd2c) isn’t perfect so I would guess `IS_BROWSER` is `true` for whatever platform you are using, so it’s trying to render `Suspense` which is not supported.
> 
> It’s been over three years now since I added the `lazy` stuff. Clearly it is not written in the best way. If you can figure out why `IS_BROWSER` is true, a PR with a fix would be very welcome.

Hi @cookpete, I get the error when importing both ### react-player & ### react-player/lazy. My site uses SSG, so isBrowser is true.
