### ISSUE TITLE
Player ignores the playing prop, but only when going from true to false

### ISSUE THREAD

**Issue by lmartins** [CookPete/react-player#739]
#### Current Behavior
I have a player inside a modal, that modal emits an event causing the video `playing` prop to change from false to true. This does successfully start the video, however when I close the modal I see the property on the `ReactPlayer` changing from `true` to `false` as expected, however the video keeps playing in the background (since the modal is now closed). 

I've been using the library for a while, and it is the first time I've seen this behaviour, so a little confused as to why might be causing it.

#### Other Information
The current implementation looks like this:

The console log updates as the component state does, and as mentioned above as the `ReactPlayer` component props do too in the React inspector tool.

```js
  render() {
    const { mediaUrl, playing } = this.state;
    console.log(playing);
    return (
      <ReactPlayer
        className="media-player"
        url={mediaUrl}
        playing={playing}
        width="100%"
        height="100%"
        config={{
          youtube: {
            playerVars: {
              modestbranding: 1,
              showinfo: 0
            }
          },
          vimeo: {
            playerOptions: {
              responsive: true
            }
          }
        }}
      />
    );
  }
```

Anything I could try here? Thank you!

**Comment by CookPete** [comment]
What type of URL are you trying to play? The issue template is there for a reason. It's hard to know what's going on without knowing the type of player being initialised.

I'm confused as to how things are still playing when the modal is closed. ReactPlayer should be unmounted when the modal closes, which calls `stop()` assuming the player has called `onReady` previously:

https://github.com/CookPete/react-player/blob/6d57ef35c4fc8469bb006a9aacfd15a5ba57fb71/src/Player.js#L29-L31

Not all players do things on `stop()`, but the containing div/iframe that the player sits in is destroyed when the player unmounts, so something strange must be going on for it to continue playing in the background.

**Comment by lmartins** [comment]
@CookPete sorry for not mentioning it, but I did tried both with YouTube and Vimeo players, both showing the same behaviour. This modal does not destroy the component as it closes, it is only toggling CSS properties.

What led me to believe it could be a problem in the library itself was the fact that in the React Inspector tool, I see the `playing` property go from `false` to `true` and the video starts playing, but when I close the modal and it goes from `true` to `false`, the video doesn't stop. 

I'll see if I can find any additional information that I can add to this.

**Comment by CookPete** [comment]
I wonder if the browser is deliberately preventing hidden videos from being controlled, to stop the playing of potentially intrusive videos that the user can't see? Can you update your logic to dismount the player first, before hiding the modal?

**Comment by lmartins** [comment]
@CookPete that's an interesting idea, unfortunately it made no difference. I'll keep looking. Thank you.

**Comment by lmartins** [comment]
@CookPete actually, it wasn't exactly the hypothesis you've mentioned, but it led me to the problem. The modal was originally set to `display: none;`, and while the video component appeared to initialise properly, showing state and everything normally mounted on the inspector, if I just control the modal visibility with the CSS `visibility` and `z-index` properties then it behaves as expected, complying with the current status of the `playing` property.

So while it is pretty strange that it ends up in this state, this does solve my specific problem here.

Thanks again Pete for the feedback and help provided here.
