### ISSUE TITLE
Need callback for 'loading/buffering' state.

### ISSUE THREAD

**Issue by andschdk** [CookPete/react-player#74]
When internet connection is bad playback can stop before video is totally loaded. Here no callback is supplied.

This can be useful for showing a spinner when playback stops to buffer more.

I find no way to achieve this from current callbacks.

**Comment by CookPete** [comment]
`onBuffer` will be called when a video has to stop to load before resuming. When it resumes, `onPlay` will be called.

If you are looking to show a spinner when first loading a video, just set `showSpinner: true` or whatever in your initial state and then use the `onStart` callback to set `showSpinner: false`

**Comment by andschdk** [comment]
@CookPete is this also the case if streaming from an URL?
I'm only able to see the behaviour you describe when using youtube/vimeo...

**Comment by andschdk** [comment]
I found these events from `<video>` to be useful.
https://github.com/joblicate/react-player/commit/c42318a085c7c7584b6e9351c759d1654e68df3d

I just need to make a nice way to observe when to display a loading indicator and when to remove it again.

Maybe a callback `onLoadingChange(loading: bool)` where `loading` bool will be true after either a `onwaiting` or `onstalled` event.  `onLoadingChange(loading: bool)` could then report false after `onplaying` event.

Don't know if this makes sense, will look further into it..

**Comment by CookPete** [comment]
Nice spot with `onwaiting` and `onstalled`. I'm happy to accept a PR with those changes (although the `e` param is unused in those listeners).

I think `onBuffer` and `onPlay` is enough to get you the behaviour you want. Just hold `showSpinner: true` (or something) in your state, then:

```js
<ReactPlayer
  url={url}
  playing
  onPlay={() => this.setState({ showSpinner: false })}
  onBuffer=(() => this.setState({ showSpinner: true })}
/>
```

**Comment by andschdk** [comment]
Unfortunately this is very bad supported :-(

`onwaiting` and `onstalled` can be used to know when video needs to buffer the time from playback stops till the event is fired differs from browser to browser. Found one SO post where one claims that the events is not fired in some cases http://stackoverflow.com/questions/21399872/how-to-detect-whether-html5-video-has-paused-for-buffering.

I rely on `onwaiting` and `installed` however, but will consider rewriting this in future. Detecting buffer state based on played progress value can be error prune I think.

When enough data is loaded `onplaying` event should be fired according to the docs at least.. https://developer.mozilla.org/en-US/docs/Web/Events/playing
Unfortunately this is not the case in Chrome. Therefore it is hard to tell when buffering is done.

What seemed to be a simple issue to solve turns out this is complex due to lack in browser implementation. 

Instead of `onplaying` I've added state in `FilePlayer` and a `progress` callback which is called by `ReactPlayer`'s progress time loop.
This allows me to perform a check:
```javascript
progress (progress) {
    if (progress.played && this.state.buffering) {
      this.setState({
        buffering: false
      })
      this.onPlay()
      return
    }

    if (progress.loaded && this.state.buffering) {
      if ((!progress.played || progress.played == 0.0) && progress.loaded > 0.0) {
        this.setState({
          buffering: false
        })
        this.onPlay()
        return
      }
    }
  }
```

- Buffer state can only be present if player has played something, will exit initial buffer state when `loaded` > 0
- Will exit from buffer state if in buffer state and player is playing (`played`)

I've updated the branch. Don't know if this is too much for a PR / out of scope for your component, but there is definitely an issue here... I can not guarantee that this doesn't raise other issues regarding buffering state, but it allows me to show an activity spinner while video is buffering.

**Comment by oyeanuj** [comment]
@andschdk The above link to your example seems to be broken. Do you have a branch/fork with that logic that one could try?

@CookPete Another issue I see mentioned in this thread is that the `onBuffer` being present only for Youtube. Is that a limitation of other services/general players?

**Comment by CookPete** [comment]
>Another issue I see mentioned in this thread is that the onBuffer being present only for Youtube. Is that a limitation of other services/general players?

Pretty much, yeah. If the player API supports a callback or event for when a video starts to buffer, then it's easy enough to hook up to the `onBuffer` prop. I just haven't seen that callback/event for players (other than YouTube) when hooking things up, and the HTML5 players (as you can see from this thread) are just too unreliable across different browsers to know what is going on.

**Comment by andschdk** [comment]
@oyeanuj Sorry, the company is closed and the repo has been closed :-(

Regarding `onBuffer` I was able too do a "hack" to detect buffering using a timer and comparing the current played progress with a previous one.

**Comment by CookPete** [comment]
Not sure there is much else to do here. We are at the mercy of the player APIs when it comes to knowing if a player is buffering or not and HTML5 players aren't good enough for a consistent hook. There is always the `fileConfig.attributes` prop for adding custom callbacks,
