### ISSUE TITLE
light mode not working in IE11

### ISSUE THREAD

**Issue by markhats** [CookPete/react-player#741]
`light` mode doesn't seem to be working in IE11. The preview image works and also the 'play' icon is displayed but clicking on the preview does nothing. Everything is fine when not in `light` mode. 

I'm using using the Babal polyfill and it's a YouTube video I'm trying to play.

**Comment by CookPete** [comment]
Seems to work fine for me:

![rpie11](https://user-images.githubusercontent.com/1926029/72661435-e881f300-39d1-11ea-89cc-7982123f4553.gif)
