### ISSUE TITLE
'playing' prop not working correctly?

### ISSUE THREAD

**Issue by spiral2k** [CookPete/react-player#743]
when 'playing' prop is false the stream is not pausing,
how to use 'palying' correctly?

`      <ReactPlayer
        playing={playing}
        ref={playerRef}
        className={"player-container"}
        url={url}
        onReady={onReady}
        onPlay={onPlay}
        onStart={onStart}
        onPause={onPause}
        onBuffer={onBuffer}
        onError={onError}
        volume={props.volume}
      />`

**Comment by CookPete** [comment]
Whatever you're playing should pause when `playing` turns from true to false. What URL are you playing? And how are you updating the `playing` state?

**Comment by spiral2k** [comment]
@CookPete when the user click on the pause button i'm triggering the onPause function with "playerRef.current.player.handlePause" function and then im changing the state.

the url: http://01.solumedia.com.ar:8446/stream.aac

what is the correct way to do that with custom controls?

**Comment by CookPete** [comment]
You should be keeping your own `playing` state (either in a hook or in component state) and then changing the value from `true` to `false` using `setState()`.

You can see this in action if you dig around the [demo app](https://github.com/CookPete/react-player/blob/master/src/demo/App.js#L46-L48).

Trying to calling `onPause` using refs is definitely not the way to go, and very prone to bugs like this.

**Comment by whynesspower** [comment]
I was having the same issue, what you need to do is -
wherever you  are setting the value of `playing` state as false
first change the same playing set to `true` and then immediately on the next line set it to `false` again. 

It will work. Thanks
