### ISSUE TITLE
Please help to understand if I can use react-player for my needs.

### ISSUE THREAD

**Issue by v-margko** [CookPete/react-player#746]
Hi, could you please help me to understand if I can use a react-player in my case? What I need:

1. start playing before the whole track is loaded
2. start playing before the whole track is loaded not just from the beginning but from any random point without a necessity to handle this process of piece by piece loading manually
3. load a track from a storage that requires authorization
4. consume a track without specifying an exact file extension

If the react-player is not an option because of any point above maybe you have a clue for me what else I can try?

**Comment by CookPete** [comment]
Honestly this sounds like you just need a simple `<audio>` element with some configuration. You'd need to make the authenticated request separately, then pipe the result into the `src` of the `<audio>`. Then listen for the `canplay` event and set `currentTime` to seek to a certain point. It should work regardless of file extension if you also pass in a media type.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio
