### ISSUE TITLE
Controls display odd values for live dash streams

### ISSUE THREAD

**Issue by zakgof** [CookPete/react-player#747]
When playing live dash streams with controls enabled, the following issues are seen:

1. Current playing position is displayed as a very big value **437243:59:09** Expected: for live streams, it's more common to show time offset from the live edge.
2. Total video time is displayed at **-14:-8**. Expected: this should omitted for infinite live streams
3. Seek slider position is always at the beginning. Expected: seek slider should be in the end, as a user is not able to seek into the future, but should be able to seek back from the live edge.

![image](https://user-images.githubusercontent.com/8456072/69050849-8295e100-0a0b-11ea-94f4-81802938834c.png)

This is how the dash.js reference player's (https://reference.dashif.org/dash.js/v3.0.0/samples/dash-if-reference-player/index.html) controls look like when playing live video:
![image](https://user-images.githubusercontent.com/8456072/69051244-73636300-0a0c-11ea-9c1a-c90501faf98d.png)

#### Steps to Reproduce
Open the following DASH-IF reference live stream in the demo page at https://cookpete.com/react-player/
https://vm2.dashif.org/livesim-chunked/chunkdur_1/ato_7/testpic4_8s/Manifest300.mpd

#### Environment
- URL attempting to play:  https://vm2.dashif.org/livesim-chunked/chunkdur_1/ato_7/testpic4_8s/Manifest300.mpd
- Browser: Chrome 78.0.3904.97 
- Operating system: Win10

**Comment by CookPete** [comment]
This is just the native HTML5 player controls. There's nothing ReactPlayer can really do about this. The dash player has it's own duration/controls logic. The same thing could be achieved with custom controls that listen to `onProgress` etc.
