### ISSUE TITLE
playIcon gets removed after pause

### ISSUE THREAD

**Issue by avokrado** [CookPete/react-player#748]
#### Current Behavior
After pressing pause, `react-player__preview` class gets removed

#### Expected Behavior
thumbnail with custom icon should be shown after pressing pause, therefore `react-player__preview` shouldnt get removed

**Comment by CookPete** [comment]
Light mode is just a placeholder for until the full player loads, not an overlay for when the video is paused. If you really wanted, you could listen to `onPause` and show an overlay that sets `playing={true}` when clicked.
