### ISSUE TITLE
playing prop not pausing youtube

### ISSUE THREAD

**Issue by pdewouters** [CookPete/react-player#749]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior

When `playing` prop value changes to `false`, the video still plays, however if I pause the video manually then the prop changes to `true` it does start playing 
So, only the false state is not working as expected

#### Expected Behavior

When my wrapper component sets the `playing` state to `false` the video should stop playing

#### Steps to Reproduce

1.
1.
1.

#### Environment
- URL attempting to play: https://www.youtube.com/watch?v=YxPRZ9S-qbI
- Browser: chrome 78
- Operating system: mac os
- React 16.8.4
```
import React, { useEffect } from 'react';
import PropTypes from 'prop-types';
import { __ } from '@wordpress/i18n';
import YouTubePlayer from 'react-player/lib/players/YouTube'
import { Waypoint } from 'react-waypoint';

const Youtube = ( { youtubeId } ) => {
	const [ paused, setPaused ] = React.useState( true );

	return (
		<Waypoint
			onLeave={ () => setPaused( true ) }
			onEnter={ () => setPaused( false ) }
		>
			<div>
				{console.log(paused)}
				<YouTubePlayer
					url='https://www.youtube.com/watch?v=YxPRZ9S-qbI'
					controls
					playing={ ! paused }
					// onPause={ () => setPaused( true ) }
					// onPlay={ () => setPaused( false ) }
					// onStart= { () => setPaused( false ) }
					// onReady={ () => setPaused( true ) }
					// onEnded={ () => setPaused( true ) }
				/>
			</div>
		</Waypoint>
	);
};

Youtube.propTypes = {
	youtubeId: PropTypes.string.isRequired,
};
```

#### Other Information
I see the `playing` prop change correctly when scrolling in the React devtools.

**Comment by pdewouters** [comment]
Same if I use a Component
```
import React, { Component } from 'react';
import PropTypes from 'prop-types';
import YouTubePlayer from 'react-player/lib/players/YouTube'
import { Waypoint } from 'react-waypoint';

class Youtube extends Component {
	state = { isPaused: false };

	render() {
		return (
			<Waypoint
				onLeave={ () => this.setState( { isPaused: true } ) }
			>
				<div>
					<YouTubePlayer
						url='https://www.youtube.com/watch?v=5meXTa10c5g'
						controls
						playing={ ! this.state.isPaused }
						onPause={() => this.setState( { isPaused: true } )}
						onPlay={() => this.setState( { isPaused: false } )}
						onStart={() => this.setState( { isPaused: false } )}
						// onReady={ () => setPaused( true ) }
						// onEnded={ () => setPaused( true ) }
					/>
				</div>
			</Waypoint>
		);
	}
};

Youtube.propTypes = {
	youtubeId: PropTypes.string.isRequired,
};

export default Youtube;
```

**Comment by lmartins** [comment]
Seeing the same behaviour with Vimeo videos. Setting the `playing` prop to true in the inspector will start the video, but then setting it back to `false` does nothing.

@pdewouters were you able to figure out the reason for this behaviour in your test case?

**Comment by pdewouters** [comment]
@lmartins no, I gave up and just built a component myself

**Comment by CookPete** [comment]
I have no idea why this would happen. If the `onPlay` event somehow doesn't fire, then the internal `isPlaying` flag never gets set to true and so pausing won't work.

That or it's something to do with `react-waypoint` and pausing the video when outside of the viewport? Feel free to reopen with more detailed steps to reproduce (pasting a code snippet isn't hugely useful as I still can't reproduce the issue locally).

**Comment by lmartins** [comment]
It is a fair assumption, although I do suspect something else may be going on. The case where I've seen this problem was not using `react-waypoint`, but regardless the `isPlaying` prop could be seen changing without `react-player` reacting to it, despite that being the value passed down as the `playing` prop.

**Comment by AlfredoSequeida** [comment]
I experienced the same behavior, a way to circumvent this is by getting the internal player instance and then pausing it that way:

`this.player.getInternalPlayer().pauseVideo();`

**Comment by pdewouters** [comment]
This works, from a stackoverflow answer
```	// Pause the video _on-demand_
	const pauseVideo = () => {
		const videoFrame = ref.current;
		videoFrame && videoFrame.contentWindow.postMessage && videoFrame.contentWindow.postMessage( '{"event":"command","func":"pauseVideo","args":""}', '*' );
	};```

**Comment by AlfredoSequeida** [comment]
> This works, from a stackoverflow answer
> 
> ```
> 	const pauseVideo = () => {
> 		const videoFrame = ref.current;
> 		videoFrame && videoFrame.contentWindow.postMessage && videoFrame.contentWindow.postMessage( '{"event":"command","func":"pauseVideo","args":""}', '*' );
> 	};```
> ```

I was just going to post a solution I came up with. Similar to this:

```
  pause() {
    playerId = this.pause(this.player.getInternalPlayer().f.id);
    const iframe = document.getElementById(playerId);
    iframe.contentWindow.postMessage(
      '{"event":"command","func":"pauseVideo","args":""}',
      "*"
    );
  }
```
