### ISSUE TITLE
Can Varnish be configured with this player?

### ISSUE THREAD

**Issue by elieobeid7** [CookPete/react-player#750]
I'm trying to follow this tutorial to increase the number of wowza concurrent streams by configuring varnish

https://medium.com/@_wmconsulting/building-live-hls-stats-for-varnish-82891be3df66

Videos.js / Clappr.io

The player need to send the cookie created into each request, if are using a player based on hls.js library we need to add this configuration:

```
hlsjsConfig: {
	xhrSetup: (xhr, url) => { xhr.withCredentials = true }
}
```

Can the same be done with this player?

**Comment by CookPete** [comment]
Looks like this will help? https://github.com/CookPete/react-player/issues/319#issuecomment-364036156

**Comment by elieobeid7** [comment]
will give it a try
