### ISSUE TITLE
Cannot play youtube video 

### ISSUE THREAD

**Issue by bashby44** [CookPete/react-player#751]
#### Current Behavior

Trying to call playVideo and set it true on a YouTube video and receiving this error.
We're using version 1.14.2
![image](https://user-images.githubusercontent.com/16347373/69567120-e5402d00-0f75-11ea-89cc-6b4120923e6b.png)

#### Expected Behavior

Wanting the video to play

#### Steps to Reproduce

1. Wrapping this component in our custom component and simply setting trying to play the video

#### Environment
- Browser: Chrome 78
- Operating system: MacOS Mojave

**Comment by CookPete** [comment]
It looks like you are trying to call `playVideo` too early. Use the `onReady` callback to know when methods can be called.

**Comment by loolooii** [comment]
Just for people searching for a solution, for me disabling https://poperblocker.com/ did the job. Even after excluding that specific domain, it still kept blocking YouTube videos from auto playing for me. So if you have this or similar extensions, try to turn all off and turn them on one-by-one to see which one causes it.

**Comment by dk-rp** [comment]
> It looks like you are trying to call `playVideo` too early. Use the `onReady` callback to know when methods can be called.

How to trigger playVideo using onReady
