### ISSUE TITLE
Can we use AES encryption with this player?

### ISSUE THREAD

**Issue by elieobeid7** [CookPete/react-player#752]
Each HLS chunks need to be encrypted with AES, how to go about implementing that?

**Comment by CookPete** [comment]
This is probably a question for the guys at https://github.com/video-dev/hls.js/ – ReactPlayer is essentially just a wrapper around `hls.js` when a HLS stream is passed in. You can use [`getInternalPlayer('hls')`](https://github.com/CookPete/react-player#instance-methods) to access the `hls.js` instance.
