### ISSUE TITLE
Can I extract the download button of the player?

### ISSUE THREAD

**Issue by Deivbid** [CookPete/react-player#753]
Hey! is it possible to extract or make a handler of the button to download the video ? 

I just want to make my custom button in a corner  of the screen but make the same behaviour that the download button of the player 

I'm rendering a File video coming from an Url 
Example: `https://storage.googleapis.com/m-infra.appspot.com/public/res/Sirena/f3c8/fb1b/c3f0/2560/59d5/00c0/d1c5/8f5d/f3c8fb1bc3f0256059d500c0d1c58f5d.mp4`

What can I do ?

**Comment by CookPete** [comment]
Regarding a custom download button, see https://github.com/CookPete/react-player/issues/563.

To disable the native download button, see https://github.com/CookPete/react-player/issues/323#issuecomment-364357541
