### ISSUE TITLE
Where is 'seeking' variable in src/demo/App.js?

### ISSUE THREAD

**Issue by KKambi** [CookPete/react-player#754]
#### Code line having problem
- https://github.com/CookPete/react-player/blob/master/src/demo/App.js#L107
#### Current Behavior
- I'm implementing my own custom player with React-player `through functional component` (not class component)
- i followed demo and i found there is no variable, `seeking` in `src/demo/App.js`
- But `App class` of demo/App.js updates `seeking` with setState( )
- For example, `handleSeekMouseDown` or `handleSeekMouseUp`
- And in `handleProgress`, it calls the variable from `this.state.seeking` 

#### Expected Behavior

- Maybe, there should exists state named `seeking` in `App class`

#### Other Information
- I followed demo with functional component, but it doesn't work normally with `seeking state` because `state setter is asynchronous -> if (!this.state.seeking) doesn't check normally`
- So, i assgin `let seeking = false;` outside the app class.

**Comment by CookPete** [comment]
The only use of `seeking` state in the demo app is to prevent `onProgress` from updating the UI whilst the user is using the seek bar. This doesn't need to be (and probably shouldn't be) stored in state, and could be just set on the class as `this.seeking`.

It is indeed confusing that `seeking` is not set in the initial state [here](https://github.com/CookPete/react-player/blob/7592fdbe2d3b3ef99dbf99662e58682facc23dab/src/demo/App.js#L22-L34), but it's not required for the app to work. I am planning on rewriting the demo soon anyway.
