### ISSUE TITLE
How to get Hls programDateTime of the first fragment ?

### ISSUE THREAD

**Issue by superphung** [CookPete/react-player#757]
Hi, I am trying to get the EXT-X-PROGRAM-DATE-TIME of the first fragment from a hls video.
What I did so far is:

```js
const hlsInstance = refVideo.current.player.getInternalPlayer('hls');
hlsInstance.once(window.Hls.Events.FRAG_CHANGED, function (event, data) {
    //data.frag.programDateTime
});
```
The code above works if the event is trigger but sometimes it is not fire.
Is there an another way to retrieve it without listening to the event ?
Thanks.

**Comment by CookPete** [comment]
This is probably a question for the guys at https://github.com/video-dev/hls.js/ – ReactPlayer is essentially just a wrapper around `hls.js` when a HLS stream is passed in.
