### ISSUE TITLE
How can I use speed audio feature in case of mp3?

### ISSUE THREAD

**Issue by Gouravjafrain** [CookPete/react-player#759]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Steps to Reproduce

1.
1.
1.

#### Environment
- URL attempting to play: 
- Browser: 
- Operating system: 
- jsFiddle example: https://jsfiddle.net/sv5x3ug1

**Comment by CookPete** [comment]
You can use the `playbackRate` prop to affect the speed of playing a file.
