### ISSUE TITLE
Vimeo playback doesn't work

### ISSUE THREAD

**Issue by jarekpelczynski** [CookPete/react-player#762]
Vimeo player stopped working without any changes. Youtube video works.
I use react-player v1.14.2. 

Vimeo player is loaded (https://player.vimeo.com/api/player.js) and video's placeholder is embedded but video files are missing in source code.

Vimeo has changed something or kind of bug in react-player?

**Comment by malik-sahab** [comment]
Having the same issue. In `Vimeo.js`

> Error: `Vimeo.js:124 Uncaught (in promise) TypeError: Cannot read property 'Player' of undefined`

**Comment by shayanalis** [comment]
same issue as @malik-sahab

**Comment by joeyparis** [comment]
I'm experiencing this issue as well. It has something to do with the URL parameters added to the iframe source as removing them embeds the player as normal.

**Comment by CookPete** [comment]
Can someone try to reproduce this in a jsFiddle? Hard to debug if I can't make it happen. Things seem ok here: https://jsfiddle.net/z2kmhdfp/

**Comment by jarekpelczynski** [comment]
It works for me if I add `controls` prop.
I don't remember exactly but previously, without this prop player shows play button at the center of the video. Currently, it shows a full control bar.

**Comment by joeyparis** [comment]
It also works for me if add the controls prop, which was not required
before.

**Comment by CookPete** [comment]
Again, can anyone reproduce this in an example repo or jsFiddle? [This fiddle](https://jsfiddle.net/z2kmhdfp/) has a vimeo URL played using `v1.14.2`, which seems to work fine both with or without `controls` prop.

ReactPlayer loads the player SDK from `https://player.vimeo.com/api/player.js` (a non-versioned URL, so presumably gets the latest version of the SDK every time), which is open sourced at https://github.com/vimeo/player.js, so it may well be a problem on that end. Support for `controls` was only recently added to the Vimeo SDK and added to ReactPlayer in https://github.com/CookPete/react-player/commit/74bc8e0f9b40444be6d9d0b76bdc392dd1010a04

**Comment by jarekpelczynski** [comment]
@CookPete can not reproduce.

**Comment by lulitd** [comment]
Sorry to open this up. I just encounter this issue in v1.14.2.  

Some videos work fine without the controls prop, others do not. 

- Does **NOT** work without controls prop https://vimeo.com/159748388
- Works without controls props https://vimeo.com/243556536

**Comment by CookPete** [comment]
https://vimeo.com/159748388 works fine for me without `controls`:

![image](https://user-images.githubusercontent.com/1926029/74823263-59346c00-52fe-11ea-9d08-7289f97e6e54.png)

**Comment by lulitd** [comment]
@CookPete  Thanks for the quick reply. You're correct, it does play without the controls props. 

The inconsistency between the two videos when controls prop is not included threw me off.

https://vimeo.com/243556536 shows the controls without using controls prop, whereas https://vimeo.com/159748388 does not show the controls.   I am presuming this has to do with the video settings set by the Vimeo user but will have to double-check. 

This is what happens when I code past midnight.

**Comment by AnderAmorim** [comment]
Here I still get this error, even passing controls = {false}.

My version is 1.15.3

My code:
`<ReactPlayer
     className='react-player'
     url={`https://vimeo.com/243556536`} 
     controls={false}
     playing
  />`

Any other suggestions on how to make it work?

**Comment by bariscigim** [comment]
I would set the speed to true in the source code of the react-player, speed  false by default 

![IMG_20210325_145703](https://user-images.githubusercontent.com/7601532/112469789-ec01ce80-8d7a-11eb-8170-a05bc72840f4.jpg)

**Comment by Tuguldur007** [comment]
@cookpete Hello.

Lately playback doesn't work in our web, so I tried https://cookpete.com/react-player/ demo to play Vimeo video link which is currently used on my web. Youtube link is okay with 2x play speed but the Vimeo link is not working. I am using latest React-player version
