### ISSUE TITLE
Possible for PIP to persist while navigating away from current react-router route?

### ISSUE THREAD

**Issue by sunweiyang** [CookPete/react-player#765]
I'm using react-player and react-router in my web app, and a react-player video (with PIP as an option) can be accessed in one of my routes. I need users in my app to be able to keep a PIP video in the browser while freely navigating to different routes. Right now, the PIP does not persist if a user navigates away from the video route.

Is there a way to have PIP persist while the user navigates to other routes in my app?

**Comment by CookPete** [comment]
You would have to always render `ReactPlayer` regardless of what route you're on, and show/hide it (possibly with `opacity` based on the route you're on). I'm not sure exactly how but I'm sure you can get creative 😉
