### ISSUE TITLE
react-player__preview style need config  `background-size: 100%`

### ISSUE THREAD

**Issue by Talbot3** [CookPete/react-player#766]
#### Current Behavior

can't config preview style when light attribute has image url
#### Expected Behavior
can config preview style

#### Steps to Reproduce

1. just config light with image url

#### Environment
- Browser: Chrome
- Operating system:  macos

#### Other Information
run inspect  with mobile style

**Comment by CookPete** [comment]
`cover` feels like a better value than `100%` for fitting the preview image on the screen. There's nothing stopping you from adding `.react-player__preview { background-size: 100% !important; }` to the CSS of your app.
