### ISSUE TITLE
onEnded called when seeking in fullscreen

### ISSUE THREAD

**Issue by SampsonCrowley** [CookPete/react-player#767]
#### Current Behavior

`onEnded` is being fired when seeking in fullscreen mode

#### Expected Behavior

`onEnded` is only triggered when video ends

#### Steps to Reproduce

1. Youtube Video embed
2. Open Fullscreen
3. Seek to halfway through video

#### Environment
- URL attempting to play: https://www.youtube.com/embed/IVFjarUcsSk?rel=0&enablejsapi
- Browser: Chromium | 79.0.3945.88 (Official Build) 
    - Revision | c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
    - OS | Linux
    - JavaScript | V8 7.9.317.32
    - Flash | 32.0.0.303 /usr/lib/PepperFlash/libpepflashplayer.so
    - User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
    - features=HardwareMediaKeyHandling --flag-switches-end --disable-webrtc-apm-in-audio-service
- Operating system: Arch Linux (64-bit)

#### Other Information

Does not matter where I seek to.  If I close full screen, the `onPause` and `onPlay` event is called correctly as appropriate

**Comment by SampsonCrowley** [comment]
Tested on Windows Chrome, and Android Chrome, and the problem does not appear

**Comment by CookPete** [comment]
This is unfortunate, but I'm not sure what this library can do about this. It might be worth posting the issue on StackOverflow with the `youtube-iframe-api` tag, according to [this page](https://developers.google.com/youtube/players/support).
