### ISSUE TITLE
Is hls.js version 0.13.0 supported?

### ISSUE THREAD

**Issue by iambumblehead** [CookPete/react-player#768]
A cloudforge link for hls.js 0.13.0 does not seem to be available

https://cdnjs.cloudflare.com/ajax/libs/hls.js/0.13.0/hls.min.js

**Comment by CookPete** [comment]
This isn’t anything that can be solved in this library. Feel free to create an issue here: https://github.com/video-dev/hls.js/issues or even [update CDNJS yourself](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#c-updating-an-existing-library).

**Comment by CookPete** [comment]
A PR to add `0.13.0` to CDNJS is here: https://github.com/cdnjs/cdnjs/pull/13647

**Comment by iambumblehead** [comment]
@CookPete thanks for that. I hope the too-much-recursion errors go away there :)
