### ISSUE TITLE
How to set multiple resolution source of the same video and choose between them?

### ISSUE THREAD

**Issue by Shaker-Hamdi** [CookPete/react-player#770]
Hello, this is a question not a bug. But I couldn't find any example of setting multiple resolution sources of the same video file and choose between them via the controls popup menu.

I found this example of setting multiple VTT subtitles and choosing between them, but how can I do the same thing with the video itself?

https://jsfiddle.net/1ma6kdrL/

**Comment by CookPete** [comment]
This is not possible with ReactPlayer. The subtitle switcher is a native HTML5 video feature, but resolution switching is now.

This plugin from `video.js` might be what you're after? https://kmoskwiak.github.io/videojs-resolution-switcher/

**Comment by Aniket-Singla** [comment]
@CookPete can videojs-resolution-switcher be embeded with react-player?

**Comment by mrjelveh** [comment]
I think it's a really useful feature and there should be a way to solve this problem.

**Comment by moussa32** [comment]
Is there any new update about this interesting feature?
