### ISSUE TITLE
Light mode: is full player loaded?

### ISSUE THREAD

**Issue by aepp** [CookPete/react-player#772]
In light mode, how to "find out" whether the full player is already loaded or not? I could of course just check if the element `.react-player__preview` is present on the page, but may be there is a "cleaner" way?

**Comment by CookPete** [comment]
Could you just use `onClick` on the main player?

```jsx
<ReactPlayer
  url='https://vimeo.com/243556536'
  playing
  light
  onClick={() => console.log('player has been clicked so full player is now showing')}
/>
```
