### ISSUE TITLE
playIcon should be all lower case

### ISSUE THREAD

**Issue by antoniopacheco** [CookPete/react-player#773]
#### Current Behavior
When using playIcon prop you'll get react-warning:
`Warning: React does not recognize the `playIcon` prop on a DOM element
`
#### Expected Behavior
playIcon prop should be renamed into playicon

**Comment by CookPete** [comment]
Please reopen with the issue reproduced in a jsFiddle or similar. I can’t reproduce it here: https://jsfiddle.net/p2z8tc45/3/
