### ISSUE TITLE
React Native Support

### ISSUE THREAD

**Issue by batuhansahan** [CookPete/react-player#774]
Current Behavior
React Native Support

Environment
- Operating system: Android,IOS

Other Information
Is there any future plan to add React Native support or how could i do that any tips on that?

**Comment by CookPete** [comment]
All of the logic behind ReactPlayer is built on browser-based markup and libraries (see [Supported Media](https://github.com/CookPete/react-player#supported-media)). It just isn't feasible (or practical) to port this to React Native. It would just be a completely different library.

**Comment by Gerst20051** [comment]
I am also interested in having support for React Native. Are you aware of anything existing or would it still need to be built? Have you thought about working on it yet? @cookpete

**Comment by cookpete** [comment]
My thoughts haven’t changed since my previous comment, sorry.

There are several libraries for [youtube](https://www.npmjs.com/search?q=react%20native%20youtube) and [vimeo](https://www.npmjs.com/search?q=react%20native%20vimeo) and probably others.
