### ISSUE TITLE
Enhancement: Add Media Session API

### ISSUE THREAD

**Issue by Sensiblemnd** [CookPete/react-player#776]
https://developers.google.com/web/updates/2017/02/media-session

**Comment by CookPete** [comment]
@Sensiblemnd What exactly would you like ReactPlayer to do with the media session API? It looks like the YouTube player already supports it:

![image](https://user-images.githubusercontent.com/1926029/73027314-154b6580-3e2b-11ea-9516-38594e7a7435.png)
