### ISSUE TITLE
[Bug] Twitch clip fails to play

### ISSUE THREAD

**Issue by joseph1125** [CookPete/react-player#777]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior
Tried to play a twitch video using a specific url, react-player fails to play 

#### Expected Behavior
Expected to play normally

#### Steps to Reproduce

1. Provide "https://www.twitch.tv/stylishnoob4/clip/AnnoyingColdEggplantPanicVis" for url

#### Environment
- URL attempting to play: https://www.twitch.tv/stylishnoob4/clip/AnnoyingColdEggplantPanicVis
- Browser: Google Chrome
- Operating system: macOS

**Comment by CookPete** [comment]
According to [this page](https://dev.twitch.tv/docs/embed/video-and-clips#non-interactive-iframes-for-clips), interactive frames are not available for Twitch clips. You'll have to use a non-interactive frame I'm afraid:

```html
<iframe
    src="https://clips.twitch.tv/embed?clip=<slug>"
    height="<height>"
    width="<width>"
    frameborder="<frameborder>"
    scrolling="<scrolling>"
    allowfullscreen="<allow full screen>">
</iframe>
```
