### ISSUE TITLE
stop doesnt work correctly for mp4 files

### ISSUE THREAD

**Issue by 831bryanlee** [CookPete/react-player#78]
in the demo click on the mp4 example, play then hit stop and the video will continue playing.

this also occurs on the page I'm making where I started an mp4, then switch the source to youtube and then the mp4 will play alongside the youtube video. pausing or nulling the mp4 doesnt fix it.

**Comment by CookPete** [comment]
Good spot. This is probably a regression from a recent update. I'll look into this shortly.

**Comment by CookPete** [comment]
Fixed in `0.7.4`. Apparently this has been a [problem for a while](http://stackoverflow.com/questions/9045440/audio-continues-after-removing-video-element-in-chrome).
