### ISSUE TITLE
Is it possible to get the standalone version not compressed?

### ISSUE THREAD

**Issue by onigetoc** [CookPete/react-player#781]
Is it possible to get the standalone version not compressed?

If i want to add some video services. it's really hard to modify the code even after using beautify.

thanks

**Comment by CookPete** [comment]
This should get you started:

```bash
git clone https://github.com/CookPete/react-player
cd react-player
```
Delete or comment out [these lines](https://github.com/CookPete/react-player/blob/7592fdbe2d3b3ef99dbf99662e58682facc23dab/webpack/production.babel.js#L19-L27).
```bash
yarn build:standalone
```

Alternatively, edit the ReactPlayer source to add the video services you want, then `yarn build:standalone`.

There is also support for [custom players](https://github.com/CookPete/react-player#adding-custom-players).

**Comment by onigetoc** [comment]
about Yarn.
I installed yarn, build from react folder then: 
yarn build:standalone
i had a error: error Command failed with exit code 1.

**Comment by CookPete** [comment]
Does the same thing happen with `npm`?

Try `npm install` then `npm run build:standalone`
