### ISSUE TITLE
Standalone player - controle multiple players and more.

### ISSUE THREAD

**Issue by onigetoc** [CookPete/react-player#783]
Hi, 
I'm not got with react and i want tu use the standalone version.

In did a example based on your own: https://jsfiddle.net/onigetoc/0y374z9m/
i see that we can create functions to interact with the player and access the player informations.
Like many others video players do.

Plyr player: https://jsfiddle.net/onigetoc/rLkazct6/
Videojs: https://jsfiddle.net/onigetoc/hq5x1c90/

I would like to use myplayer.playplayer() to target the right player and create multiple players and create a way to manipulate video functions.

In the plyr example i did a console.log() and it return all player functions.
It would be interesting to access all control options and more with the stand alone reak player.

I see that there's already have video control options here, why don't use theme for the stand alone.
https://github.com/CookPete/react-player/blob/b7b2b1c9385826b6bca4ea838bdb8bc214791e07/src/players/Facebook.js
play, pause, seek ect...

sorry for the long text but i really like your player.

**Comment by CookPete** [comment]
Does this help at all? https://jsfiddle.net/1mz9gpce/

I’ve tidied up your example a bit to demonstrate multiple players.  Basically you need to use `this` inside the `loadVideo` function (that you were treating as a class rather than a normal function – I renamed it to `VideoPlayer`).

The `options` you were passing through now just map to the `props` of the player, so you can add anything you like when defining players.

**Comment by onigetoc** [comment]
Wow, perfect, I was close sometime with testing with "this" 1 day long but i never succeed.
thank a lot. ;)

If you have time helping me how to use listener like, onSeek, onEnd ect.
it will take me two days and you probably 5 .min
i will try to create a players with control, like seek, play/pause, seekto, track, mute/unmute, 
like: 
```
myplayer1.on('ended', function(event) {
      // do something like: playing the next video
 });
```
OR
```
myplayer1.on('timeupdate', function(time) {
  console.log('Current Time: ' + myplayer1.currentTime());
});
```
Or onbuffer add a loading animation ect..

How to add a responsive wrapper too.

i will try to reproduce your demo example with the 
ReactPlayer Standalone multiple players Example to learn how to use it fully.

Can you explain me the 3 dots before options? ...options

You may add this example jsfiddle link your readme file for the standalone.

and later handling error.

Lot of fun.... or work to do to come. 
The best html5 player.

**Comment by onigetoc** [comment]
I tryed hard but get no success to get, set and other infos and control the player with the standalone player.
Like seekTo, canPlay, onPlay ect.
-  [Instance Methods](https://github.com/CookPete/react-player#instance-methods) 
-  [Callback ](https://github.com/CookPete/react-player#callback-props)
-  [Config prop](https://github.com/CookPete/react-player#config-prop)
-  [Static Methods](https://github.com/CookPete/react-player#static-methods)

http://jsfiddle.net/onigetoc/twc0nuqd/411/

Any help just to get me started with each method?

**Comment by CookPete** [comment]
@onigetoc jsFiddle isn't letting me save but this should help. I've added quick examples of instance methods, callback props and config prop (just copy and paste into jsFiddle):

```js
function VideoPlayer(container, url, options) {

  this.options = options
	//this.props = null
  
  /***** DEFAULT *****/
  this.options.style = {background: 'black'};
  this.options.playsinline = true; 
  /***** DEFAULT *****/
 
  this.render = function () {
  	renderReactPlayer(document.querySelector(container), { 
    	url, 
      // Use ref to grab the internal player and save it as this.internalPlayer
      ref: player => { this.internalPlayer = player },
      ...options 
     });
  }
  
 /* DON'T KNOW HOW TO CONTROL
 https://github.com/CookPete/react-player#callback-props
 https://github.com/CookPete/react-player#config-prop
 https://github.com/CookPete/react-player#static-methods
 https://github.com/CookPete/react-player#instance-methods
 */
  
/*   this.ref
  
  this.render = function () {
        renderReactPlayer(document.querySelector(container), {  ...props });
      }
    
    this.seekTo = function (num, type) {
    this.seekTo(num, type)
    this.render() ;
  }
  
  this.canPlay = function () {
    this.canPlay(url);
    this.render();
  } */
  // https://github.com/CookPete/react-player/blob/7592fdbe2d3b3ef99dbf99662e58682facc23dab/src/standalone.js#L6

	/* Props */
  
  this.playPlayer = function () {
  	this.options.playing = true;
    this.render();
  }

  this.pausePlayer = function () {
    this.options.playing = false
    this.render()
  }
  
  this.mute = function () {
  	this.options.muted = true;
    this.render();
  }
  this.unmute = function () {
  	this.options.muted = false;
    this.render();
  }
  
  this.playbackRate = function (num) {
  	this.options.playbackRate = parseFloat(num);
  	this.render();
  }
  
  this.volume = function (num) {
  	this.options.volume = num;
  	this.render();
  }
  
  // Basic method that just calls the internal player seekTo method
  // Or, you could just call the internal method directly eg:
  // myplayer1.internalPlayer.seekTo(20, "seconds")
  // myplayer1.internalPlayer.getCurrentTime()
  // myplayer1.internalPlayer.getSecondsLoaded()
  // myplayer1.internalPlayer.getDuration()
  // etc
  this.seekTo = function (num) {
  	this.internalPlayer.seekTo(num)
  }
  
  /* Instance Methods */
  /* Callback */
  /* Config prop */
  /* Static Methods */

	this.render()
}


/*************************************************/
// https://www.youtube.com/watch?v=TMQxpj3kTKE
window.myplayer1 = new VideoPlayer('#container1','https://www.youtube.com/watch?v=oygrmJFKYZY', { 
  playing: true,
	/* playbackRate: .5, */
  width: '640px',
  height: '360px',
  // Example config prop usage
  config: {
  	youtube: {
    	playerVars: {
      	controls: 1,
        fs: 0
      }
    }
  },
  // Example callback usage
  onPause: () => alert('onPause called!')
});

window.myplayer2 = new VideoPlayer('#container2','https://www.dailymotion.com/video/xgz4t1', {
	playing: true, // set to true for automatic video start after poster/play button click
  light: true, // video poster only with play button won't play until clicked
  width: '320px',
  height: '180px'
});

/* myplayer1.on('onPlay', function() {
  alert("video is started");
}); */

console.log(myplayer1);

/* myplayer1.setplaybackRate(5); */

/* console.log(myplayer1.getDuration); */



/* RANGE SLIDER */
var slider = document.getElementById("myRange");
var output = document.getElementById("demo");
output.innerHTML = slider.value;

slider.oninput = function() {
  output.innerHTML = this.value;
}


```

**Comment by CookPete** [comment]
It's worth adding that you are probably causing yourself more problems by not using React at this point. The logic of your app is becoming quite confusing and sort of breaks the intended pattern of using this library.

Also note that in standalone mode you don't get access to the static methods.

**Comment by fehmi** [comment]
> ```js
> myplayer1.internalPlayer.getCurrentTime()
> ```

Respect!
