### ISSUE TITLE
onReady doesn't work for Facebook in ssr (different playerID)

### ISSUE THREAD

**Issue by shaulgo** [CookPete/react-player#788]
Hey, onReady doesn't work for FB player when loaded in ssr. 
From debugging I found that two playerIDs are generated, one in ssr and one in client. 
@CookPete What do you think about adding 
`componentDidMount() {
  this.playerId = ref.id
 }`
If it was loaded in ssr it will change the playerId to the one the div has. Otherwise it will have no affect.
I can make pr for this.

Quick workaround is to remount reactPlayer in client (changing the key in componentDidMount)

**Comment by shaulgo** [comment]
Thanks for the fix. And amazing project (I've been using it for years). 
The given solution fixes the problem. However only if you are aware of the problem and add code to use it.
It seems to me that it can be easily fixed without adding code from the outside. But maybe I'm missing something?

**Comment by CookPete** [comment]
Sorry, I should’ve followed this up after merging. 

I'm not sure `componentDidMount` would solve the problem? Once the component is mounted it has an `id` set in the DOM already, and setting `this.playerId` won't update the DOM before the Facebook SDK `load` logic kicks in.

It could maybe be fixed without additional code by using `react-uid` within the player, but I don't really want to include `react-uid` in the bundle for everyone (even if you're not using Facebook URLs).

Lazy players are coming in `v2.0` so I could maybe include it then.
