### ISSUE TITLE
Autoplay in IOS13 (ipad) safari

### ISSUE THREAD

**Issue by arch-stefanozanetti** [CookPete/react-player#789]
video player doesn't work in autoplay on IOS 13 safari
Is there a whay to let  it start automatically even on IOS?

**Comment by CookPete** [comment]
Autoplay on iOS [has never worked](https://github.com/CookPete/react-player/issues/165#issuecomment-285879036) and probably will never work. If there ever has been a hack to make it work, it's been patched in later versions of iOS.

More info: https://webkit.org/blog/6784/new-video-policies-for-ios/
