### ISSUE TITLE
Feature Request: Lazy loading videos w/ Intersection Observer

### ISSUE THREAD

**Issue by brandondurham** [CookPete/react-player#790]
#### Current Behavior
All videos on the page are instantiated at the same time.

#### Desired Behavior
Videos could be “lazy loaded” as they enter the viewport.

Is this currently possible, or would I have to wrap the videos in my own intersection observer? I have dozens of videos on a single page and it takes a bit to get loaded initially.

**Comment by CookPete** [comment]
Yeah I think this is outside the scope of this library. You could use `react-waypoint` or similar. Although watch out for [issues with autoplay](https://github.com/CookPete/react-player#autoplay) on some browsers.

**Comment by brandondurham** [comment]
Makes sense to me. I thought I’d share my solution here in the event that someone else comes along asking.

I used [react-intersection-observer](https://github.com/researchgate/react-intersection-observer) and put it together like this:

```javascript
import React from 'react'
import ReactPlayer from 'react-player'
import { useInView } from 'react-intersection-observer'

// Styles
import style from './index.module.css'

function Article({
	director,
	entryNumber,
	isPlaying,
	poster,
	slug,
	title,
	url,
	year,
}) {
	const [isLoaded, setIsLoaded] = React.useState(false)
	const [ref, inView] = useInView({
		threshold: 0.5,
	})

	React.useEffect(() => {
		if (inView) { setIsLoaded(true) }
	}, [inView])

	return (
		<article
			className={ [
				style.Article,
				isPlaying === slug ? style['Article--activeVideo'] : null,
			].join(' ') }
			key={ slug }
			ref={ ref }
		>
			<header>
				<h2>{ entryNumber }. { title } ({ year })</h2>
				<div className={ style.Director }>Directed by <strong>{ director }</strong></div>
			</header>
			<div className={ style.PlayerWrapper }>
				{
					inView || isLoaded ? (
						<ReactPlayer
							controls
							className={ style.ReactPlayer }
							height="100%"
							light={ `/posters/${ poster }` }
							url={ url }
							width="100%"
						/>
					) : null
				}
			</div>
		</article>
	)
}

export default Article
```
