### ISSUE TITLE
Autoplay interrupts scrubbing

### ISSUE THREAD

**Issue by pwillcode** [CookPete/react-player#792]
#### Current Behavior
While I click and drag on the video progress bar of an autoplaying video, the moment I stop moving the mouse, the video starts playing from that point, even if the video has been manually paused.
As a result, it is not possible to get a good look at a particular point in the video.

#### Expected Behavior
Click and drag on the video progress bar to scrub smoothly through the video.

#### Steps to Reproduce
Set the "playing" prop on a ReactPlayer.

#### Environment
- URL attempting to play: any mp4 file
- Browser: Chrome 79.0.3945.130 (Official Build) (64-bit)
- Operating system: Mac OS X Catalina 10.15.2 (19C57)
- jsFiddle example: https://jsfiddle.net/sv5x3ug1 (this default example does exhibit the behavior for me)

#### Other Information
Note that scrubbing behavior is exactly as I would expect if the "playing" prop is not set.

**Comment by CookPete** [comment]
Adding `onSeek={() => this.setState({ playing: false })}` seems to do the trick.

Example: https://jsfiddle.net/4cyLp83e/ 

I've also added `onPlay` and `onPause` handlers to keep `playing` state in sync.
