### ISSUE TITLE
Get type of match in canPlay()

### ISSUE THREAD

**Issue by sapkra** [CookPete/react-player#795]
#### Current Behavior
Currently `canPlay()` can just return `true` or `false` but in my use case I have to know which player has matched to apply different stylings.

#### Expected Behavior
It would be nice if `canPlay()` could return an an object of details for the current match or a string with the `displayName`.

e.g.
### Breaking:
```typescript
static canPlay = url => {
  for (const Player of [...customPlayers, ...players]) {
    if (Player.canPlay(url)) {
      return {
        type: Player.displayName
      }
    }
  }
  return false
}
```

or 
### Non breaking:
```typescript
static canPlay = (url, details = false) => {
  for (const Player of [...customPlayers, ...players]) {
    if (Player.canPlay(url)) {
      if (details) {
        return {
          type: Player.displayName
        }
      }
      return true;
    }
  }
  return false
}
```

Or simplified by returning the player and use of ES6:
```typescript
static canPlay = (url, details = false) => {
  const player = players.find((Player) => Player.canPlay(url));
  if (player) {
    if (details) { return player; }
    return true;
  }
  return false;
};
```

**Comment by CookPete** [comment]
Another static method probably makes more sense. `getPlayerForURL` or similar.

**Comment by sapkra** [comment]
In this case I have to use two loops (because both functions are using loops) which decreases the performance or misuse the `getPlayerForUrl` to check if I can use the URL. But maybe it's intended by your suggestions to use `getPlayerForUrl` for it instead, so it would return `null` or something similar to tell if a working player is available.

**Comment by CookPete** [comment]
`getPlayerForUrl` returning `null` when there is no player makes sense, so you could use either function. I'm not sure there would any practical difference in performance.

**Comment by sapkra** [comment]
There won't be any performance difference when I just use the new function. There would only be a difference when I'd use both.

btw. We can also just close this issue and I can continue using my internal helper function. 🤗
