### ISSUE TITLE
When mounting multiple players, multiple load requests are made in parallel 

### ISSUE THREAD

**Issue by Neskua** [CookPete/react-player#796]
Hi,

#### Current Behavior
I have many youtube players on my page.
For each instance of the player, it is re-downloaded 

#### Expected Behavior
Download player only one time 

It seems it supposed to work (https://github.com/CookPete/react-player/issues/391)

#### Environment
- Browser: Chrome
- Operating system: Windows 10

#### Other Information
This screen shows that the page try to download 2 times the youtube player 
![Player](https://user-images.githubusercontent.com/14198918/73836587-e7452880-480f-11ea-9806-f7411c548f1f.PNG)

There is something i dont understand with the use of `window`.
In my react component which render page i have done this: (just a test to make it work)

```javascript
if(!window.YT){
console.log(window)
 return <YouTubePlayer
        url={url}
    />;
}
return ...;
```

The `if` condition is alway true but in the console the field `YT` is present in the object `window`

Thanks for the lib
Regards

**Comment by CookPete** [comment]
The Youtube Frame API (`iframe_api`) is only loaded once for multiple players:

![image](https://user-images.githubusercontent.com/1926029/74191727-0bf43280-4c4c-11ea-83aa-efa0fb736091.png)

This shows the logic of 5604414989f53ee989751d3ce53e8ae79a7be24d working correctly.

However, once the API is loaded and the players are instantiated, they exist as individual iframes with no knowledge of each other, and they each load `base.js` into their iframe. There's no way for the frames to share this data, although the browser will cache it, which should help.

More info: https://wordpress.stackexchange.com/questions/245422/preventing-youtube-embeds-loading-multiple-instances-of-player-js

**Comment by Neskua** [comment]
Ok, i didnt know.

Thank you, and sorry for the inconvenance.
