### ISSUE TITLE
Prevent users from starting youtube video by clicking on it?

### ISSUE THREAD

**Issue by Balhut** [CookPete/react-player#797]
Hey, is it possible to prevent users from starting youtube video by clicking on the video itself? I'm trying to write something similar to video-sync and I'd like to make starting and pausing the video possible only by websockets.

Thanks in advance, and great repo! :)

**Comment by CookPete** [comment]
You could probably add `pointer-events: none;` to the player?

See also: https://github.com/CookPete/react-player/issues/218
