### ISSUE TITLE
NOT AN ISSUE - Youtube Music

### ISSUE THREAD

**Issue by paulincai** [CookPete/react-player#799]
I did some naive tests and I am not able to scrap an Youtube Music (this not related to React-Player)
The response is in this image. All Youtube Videos work fine.

I believe Youtube also restricts playing of Youtube Music outside Youtube. React Player returns something like ... the link is restricted.

If this restriction is validated by others, perhaps a comments in the Read Me would save many from some efforts.

![Screen Shot 2020-02-07 at 20 11 00](https://user-images.githubusercontent.com/26188915/74045384-0eede980-49e6-11ea-9cdc-337504bb421e.png)

**Comment by CookPete** [comment]
What browser are you using? Youtube Music URLs work fine for me:

![image](https://user-images.githubusercontent.com/1926029/74190703-b0757500-4c4a-11ea-8f92-0cbc9c7266f0.png)

```
https://music.youtube.com/watch?v=2i2khp_npdE&list=RDCLAK5uy_mhiYP7MG5kXEyeYIm8wpQYjGKeYOxB36k
```
