### ISSUE TITLE
 fullscreen error

### ISSUE THREAD

**Issue by GreatState** [CookPete/react-player#800]
#### Current Behavior
In chrome dev tools - mobile emulation I get 

caught (in promise) TypeError: fullscreen error

 
#### Environment
- URL attempting to play: www.greatstate.co
- Browser: Chrome
- Operating system: 

#### Other Information

   "gatsby": "2.7.5",  "react-player": "^1.14.2",

My player code looks like
```

     <ReactPlayer
        ref={videoRef}
        className={css.reactPlayer}
        url={url}
        width="100%"
        height="100%"
        muted
        playing
        loop
        controls={false}
        onDuration={duration => {
          handleDuration(duration)
        }}
        onReady={() => {
          setVideoIsReady(true)
        }}
      />
```
I have trieda few vimeo config options

`vimeoConfig={{ iframeParams: { fullscreen: 0 } }}`

and

` vimeoConfig={{ playerOptions: { fullscreen: 0 } }}`

**Comment by CookPete** [comment]
Seems like the error is caused by the page trying to go fullscreen without user interaction: https://github.com/sindresorhus/screenfull.js/issues/122#issuecomment-468225643

Either way this looks like an issue with [vimeo/player.js](https://github.com/vimeo/player.js) rather than ReactPlayer.

**Comment by maddyahmad** [comment]
did anyone find solutions to this?? I am using Vimeo videos URL, and using react with typescript.

**Comment by maddyahmad** [comment]
Thanks, that worked for me. Even though I have to add vimeo in configuration. Now my react player looks like : 
 <ReactPlayer
          className="react-player"
          style={{ pointerEvents: "none" }}
          url={roundThreeVideo}
          pip={true}
          stopOnUnmount={false}
          onEnded={() => roundThreeQuiz()}
          playing
          config={{
            vimeo: {
              playerOptions: {
                playsinline: true,
              },
            },
          }}
        />

**Comment by maddyahmad** [comment]
Thanks, that worked for me. Even though I have to add vimeo in configuration. Now my react player looks like :
```
**<ReactPlayer
className="react-player"
style={{ pointerEvents: "none" }}
url={roundThreeVideo}
pip={true}
stopOnUnmount={false}
onEnded={() => roundThreeQuiz()}
playing
config={{
vimeo: {
playerOptions: {
playsinline: true,
},
},
}}
/>**
```

**Comment by EdenLiang** [comment]
playerOptions: {
  playsinline: true
}
That works, Thanks
