### ISSUE TITLE
Cannot use seek with Custom URL

### ISSUE THREAD

**Issue by mrwadepro** [CookPete/react-player#801]
#### Current Behavior
When using the following URL 
https://productionstemulistorage.blob.core.windows.net/stemuli/kid_cudi/Hi%2C%20I%27m%20Scott%20_%20Scott%20Mescudi%20_%20TEDxSHHS.mp4
I am unable to skip through the video, it just restarts.

#### Expected Behavior
When using the track seeker it should play from the correct placement.

#### Environment
- URL attempting to play: https://productionstemulistorage.blob.core.windows.net/stemuli/kid_cudi/Hi%2C%20I%27m%20Scott%20_%20Scott%20Mescudi%20_%20TEDxSHHS.mp4
- Browser: Google Chrome
- Operating system: 
- [Example](https://codesandbox.io/s/laughing-water-hkxol)

**Comment by CookPete** [comment]
This doesn't seems to be an issue with ReactPlayer, but with the video file itself. The same problem occurs when you open the link directly in Chrome, with the native player.

Doesn't seem to happen in Firefox or Safari, so this must be a Chrome bug with this specific video format.

See also: 
- https://github.com/videojs/video.js/issues/1031
- https://stackoverflow.com/questions/8088364/html5-video-will-not-loop/9549404#9549404
