### ISSUE TITLE
how to block vimeo fullscreen?

### ISSUE THREAD

**Issue by jungpaeng** [CookPete/react-player#804]
https://github.com/CookPete/react-player/issues/33#issuecomment-174451505

I want to turn off the 'Vimeo' FullScreen Option, but it won't turn off.

```jsx
<ReactPlayer
  url='http://vimeo.com/...'
  vimeoConfig={{ iframeParams: { fullscreen: 0 } }}
/>
```

**Comment by CookPete** [comment]
It looks like this is no longer an option, sorry: https://github.com/vimeo/player.js#embed-options

Maybe create an issue in that repo?
