### ISSUE TITLE
Facebook is missing display props  when styling

### ISSUE THREAD

**Issue by stonehz** [CookPete/react-player#807]
Checking the other players, 
we pass `props.display` when styling.

on Facebook, we don't pass it.
https://github.com/CookPete/react-player/blob/master/src/players/Facebook.js#L102
 
example from YouTube (https://github.com/CookPete/react-player/blob/master/src/players/YouTube.js)
```
    const { display } = this.props
    const style = {
      width: '100%',
      height: '100%',
      display
    }
```

**Comment by CookPete** [comment]
The `display` prop is only used for players that support `preload` config, which doesn't include Facebook.

You can just use `<ReactPlayer style={{ display: 'whatever' }} />` and it will be applied to the element that wraps the Facebook player.
