### ISSUE TITLE
how to play with websocket source?

### ISSUE THREAD

**Issue by lamvananh** [CookPete/react-player#809]
I have a stream source in format "ws://cdn1-xxxxxxxx".
Can you tell me how to play this source using this player?

**Comment by CookPete** [comment]
ReactPlayer just renders a `<video>` for playing files and stream URLs. If the browser doesn't natively support playing a websocket URL in a `<video>`, it won't play.

This looks like an interesting read: https://phoboslab.org/log/2013/09/html5-live-video-streaming-via-websockets
