### ISSUE TITLE
Question: Is there a way to add few html5 source tags?

### ISSUE THREAD

**Issue by antongorodezkiy** [CookPete/react-player#81]
Hello @CookPete 

Thanks for the nice lib!

Is there a way to add few html5 source tags or the only option is to use `url` prop for single source?

**Comment by CookPete** [comment]
Currently only a single `src` is supported, however it would be good to support multiple `source` tags, so I'll leave this open.

How would it work? Perhaps `ReactPlayer` could have child nodes that are added to `video` and only rendered when `playing` is true? Something like:

```js
<ReactPlayer playing={true}>
  <source src='foo.webm' type='video/webm'>
  <source src='foo.ogg' type='video/ogg'> 
  <source src='foo.mov' type='video/quicktime'>
</ReactPlayer>
```

The trouble is that the `children` would exist for all the players, but only be used in `FilePlayer` which is a little strange. If we don't require a `type` we could take an array of sources in the `url` prop:

```js
<ReactPlayer
  playing={true}
  url={['foo.webm', 'foo.ogg']}
/>
```

Or if we still want to specify a `type` we could take an array of objects:

```js
<ReactPlayer
  playing={true}
  url={[
    {src: 'foo.webm', type: 'video/webm'},
    {src: 'foo.ogg', type: 'video/ogg'}
  ]}
/>
```

**Comment by willbowling** [comment]
This would be awesome. Any movement on this?

**Comment by CookPete** [comment]
I've pushed a possible fix for this to the [`multiple-sources`](https://github.com/CookPete/react-player/tree/multiple-sources) branch. Feel free to try it out.

**Comment by briansayles** [comment]
Would love to see that multiple-sources branch get pulled in to the master.
