### ISSUE TITLE
Player resizing during load.

### ISSUE THREAD

**Issue by mike-ugg** [CookPete/react-player#810]
#736 ## Current Behavior
I have react player with a vimeo video link and set the width and height set to 100% within a div with a fixed width and height. On loading the player will flash a smaller size before the full size is filled. Is there a way for it to start at the max size?

#### Expected Behavior
Expecting the video to be at max width on first load.

#### Steps to Reproduce
1. Set ReactPlayer component to 100% width and height. 
2. Put component in a div container with width: 600 and height: 338.
3. When loading the page the video will flash for an instant before hitting max size.

#### Environment
- URL attempting to play: it's a private vimeo video, but any public video have the same effect.
- Browser: Google Chrome Version 79.0.3945.130 (Official Build) (64-bit)
- Operating system: MacOS
- jsFiddle example: none

**Comment by CookPete** [comment]
This is a problem with the Vimeo player API where the `width` and `height` of the iframe that is rendered will _always_ be in pixels. Passing in `100%` will become `width='100' height='100'`.

The original issue I raised with Vimeo (nearly 2 years ago) is here: https://github.com/vimeo/player.js/issues/38

The workaround to set the `width` and `height` after the fact is here: 

https://github.com/CookPete/react-player/blob/9be7a9c9d24d08801b1f31f93bdfabf45ea1bf83/src/players/Vimeo.js#L38-L42

**Comment by farah-web** [comment]
Hello,  I am facing the similar issue of Player resizing during load. I am using an .mp4 video file url. Everything is working fine but the player flashes a smaller size and then fills the div with full size.
Kindly suggest as to how I can make the player with max size on load.

**Comment by cordial** [comment]
how do we apply this workaround?

**Comment by nidhinkumar06** [comment]
> This is a problem with the Vimeo player API where the `width` and `height` of the iframe that is rendered will _always_ be in pixels. Passing in `100%` will become `width='100' height='100'`.
> 
> The original issue I raised with Vimeo (nearly 2 years ago) is here: [vimeo/player.js#38](https://github.com/vimeo/player.js/issues/38)
> 
> The workaround to set the `width` and `height` after the fact is here:
> 
> https://github.com/CookPete/react-player/blob/9be7a9c9d24d08801b1f31f93bdfabf45ea1bf83/src/players/Vimeo.js#L38-L42

@cookpete  Could u pls let me know what should be done for this resizing issue still i am facing that issue

**Comment by jamesryan-dev** [comment]
+1 for an example on how to fix this - finding this issue with vimeo when using react-player :/

**Comment by ddr-fe** [comment]
In case anybody else is struggling with this, I fixed it with the following CSS...
`.react-player iframe {
	width:100%;
	height:100%;
}`
