### ISSUE TITLE
Unable to play SoundCloud files

### ISSUE THREAD

**Issue by mitchell-bu** [CookPete/react-player#811]
#### Current Behavior
When providing a src URL to a file hosted by SoundCloud, the player does not load the audio and instead shows 'You have not provided a valid SoundCloud URL'.

#### Expected Behavior
The player should play audio hosted by SoundCloud feeds.

#### Steps to Reproduce
1. Go to the demo site: https://cookpete.com/react-player/  Or create a vanilla page with a standalone ReactPlayer component.
2. Use a SoundCloud URL, such as http://feeds.soundcloud.com/stream/589508247-mtqs-podcast-amir-fassihi-amnion-life.mp3

#### Environment
- URL attempting to play: http://feeds.soundcloud.com/stream/589508247-mtqs-podcast-amir-fassihi-amnion-life.mp3
- Browser: Chrome
- Operating system: Windows and Linux 

#### Other Information
The player is redirecting the request to https://w.soundcloud.com/player/?url=http://feeds.soundcloud.com/stream/589508247-mtqs-podcast-amir-fassihi-amnion-life.mp3&visual=true&buying=false&liking=false&download=false&sharing=false&show_comments=false&show_playcount=false&callback=true

**Comment by sebbean** [comment]
@mitchell-bu i think you need to paste a soundcloud frontend url not an mp3 file url

**Comment by mitchell-bu** [comment]
I ultimately forked this repo and since I don't care if I show the SoundCloud player, I just changed the MATCH_URL regex so feeds.soundcloud.com goes to the generic player.
`const MATCH_URL = /(\/soundcloud\.com|snd\.sc)\/.+$/`
May want to update this repo too to make the mp3 file URL not get routed to the SoundCloud player.

**Comment by CookPete** [comment]
Fixed in `v2.0.1`
