### ISSUE TITLE
feature request: addEventlistener onTimeUpdate

### ISSUE THREAD

**Issue by victororlyk** [CookPete/react-player#813]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior

Currently there is no way to get to this listener only via querySelector and then adding you listener

#### Expected Behavior

I would like to have access to this event directly through your api

#### Steps to Reproduce

1.
1.
1.

#### Environment
- URL attempting to play: 
- Browser: 
- Operating system: 
- jsFiddle example: https://jsfiddle.net/sv5x3ug1

#### Other Information

currently you may do something like this 
```
	useEffect(() => {
		if (isPlaying) {
			const el = document.getElementById(id);
			const v = el.querySelector('video');
			v.addEventListener('timeupdate', handleTimeUpdate);
			handleTimeUpdate();
			return () => {
				v.removeEventListener('timeupdate', handleTimeUpdate);
			};
		}
	}, []);
```
but it is kinda big

**Comment by CookPete** [comment]
You can use `config.file.attributes.onTimeUpdate`: 

```jsx
<ReactPlayer
  url='http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4'
  playing
  controls
  config={{ file: { attributes: { onTimeUpdate: a => console.log(a) }}}}
/>
```

https://jsfiddle.net/aLruv94m/

**Comment by ShahriarDhruvo** [comment]
I want to remove this onTimeUpdate attribute after I have finished my function then how will I do that here?

For example in raw js we can addEventListener and removeEventListener like this:
`var pausing_function = function(){
    if(this.currentTime >= 5 * 60) {
        this.pause();

        // remove the event listener after you paused the playback
        this.removeEventListener("timeupdate",pausing_function);
    }
};

video.addEventListener("timeupdate", pausing_function);`
