### ISSUE TITLE
Modify Colors of seek bar

### ISSUE THREAD

**Issue by ehsunshahid** [CookPete/react-player#814]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior
Simple Seek bar

#### Expected Behavior
Modify color of seek bar for certian time periods

**Comment by CookPete** [comment]
Vimeo has [support for a color param](https://github.com/vimeo/player.js#embed-options) but I'm not sure any other players do.

ReactPlayer doesn't have any custom controls. It simply loads the relevant player API and initialises a player with [whatever options are available](https://github.com/CookPete/react-player#supported-media).

There is nothing stopping you from overlaying your own controls on top of a player with `controls={false}`
