### ISSUE TITLE
getSdk failed in some environments

### ISSUE THREAD

**Issue by zhu** [CookPete/react-player#815]
#### Current Behavior

throw an Exception: xxx is not a constructor

#### Expected Behavior

no exception

#### Steps to Reproduce

1.some framework will add exports (or other vars that the sdk may consider that some module system works) to window
2.some sdk that will detect module system and not export to window (hls.js for example)
3.

#### Environment
- URL attempting to play: 
- Browser: 
- Operating system: 
- jsFiddle example: https://jsfiddle.net/hwcu84fg/

**Comment by CookPete** [comment]
It can't be ReactPlayer's responsibility to support every possible output of every third party library. If something is interfering with `window.Hls` being available, that things needs to be fixed.

You could load `<script src='https://cdn.jsdelivr.net/npm/hls.js'></script>` before any frameworks that set the `exports` global. ReactPlayer will use the already-loaded `hls.js` and won't load it again.
