### ISSUE TITLE
HLS video data keeps loading if player stopped/unmounted before start playing

### ISSUE THREAD

**Issue by SentretC** [CookPete/react-player#817]
#### Current Behavior
If the player is asked to play an HLS video, then stopped/unmounted after the .m3u8 file is loaded but before the first .ts file is loaded, the browser keeps downloading the .ts files afterwards.

#### Expected Behavior
No video data should bu requested if the player is stopped/unmounted.

#### Steps to Reproduce

1. Visit the official demo site: https://cookpete.com/react-player/
1. Open the browser's inspector tool
1. Click the _HLS (m3u8)_ button, then click the _Stop_ buton shortly afterwards
1. Check the inspector to see the .ts files continue to get downloaded (or try again if the stop button is not clicked at the correct time)

#### Environment
- URL attempting to play: <Official HLS demo file>
- Browser: Firefox 73.0, Chrome 80.0
- Operating system: Windows 10 1903

**Comment by scottyeung** [comment]
Did you try to override `hlsOptions` autoStartLoad?

**Comment by SentretC** [comment]
> 
> 
> Did you try to override `hlsOptions` autoStartLoad?

Thanks for the advice, but it prevents the video from playing (without further customization).

Then I tried calling `getInternalPlayer('hls').destroy()` manually, which seems to fix the issue.
I think ReactPlayer should be responsible to properly destroy what's underlying, but I'm not experienced enough to commit a PR for this, could someone please help?
