### ISSUE TITLE
Support Youtube WebP image?

### ISSUE THREAD

**Issue by winstonma** [CookPete/react-player#818]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior

I am showing the react-player light on my webpage. By default it is displaying hqdefault.jpg. Youtube server now serves WebP images so I wonder if WebP image could be supported.

e.g. [WebP](https://i.ytimg.com/vi_webp/bb5CIh5h-Do/hqdefault.webp) and [JPEG](https://i.ytimg.com/vi/bb5CIh5h-Do/hqdefault.jpg)

Not sure if [Using WebP Images in CSS](https://css-tricks.com/using-webp-images/) could help.

#### Steps to Reproduce

1.
1.
1.

#### Environment
- URL attempting to play: 
- Browser: 
- Operating system: 
- jsFiddle example: https://jsfiddle.net/sv5x3ug1

**Comment by CookPete** [comment]
Light mode uses the `thumbnail_url` provided by [noembed](https://noembed.com), eg https://noembed.com/embed?url=https://www.youtube.com/watch?v=jNgP6d9HraI

If it provides a JPG as the `thumbnail_url` then that's what will get rendered.

You can always pass in an image url to `light` to override the thumbnail that gets used, eg 

```js
<ReactPlayer light='https://i.ytimg.com/vi_webp/bb5CIh5h-Do/hqdefault.webp' />
```
