### ISSUE TITLE
Unable to add custom data-attributes to video tag

### ISSUE THREAD

**Issue by scottyeung** [CookPete/react-player#820]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior

Using react-fullpage with the player to play videos in the background, but paused by react-fullpage automatically as long as the video leaves the screen. Added 'data-keepplaying' to the video tag directly in the Google Chrome console manually to make it work. Is there anyway I can add custom data attributes to the video tag via ReactPlayer?

**Comment by CookPete** [comment]
Use `config.file.attributes`:

```jsx
<ReactPlayer
  url='http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4'
  playing
  config={{ 
    file: { 
      attributes: {
        'data-test': '123'
      } 
    } 
  }}
/>
```

https://jsfiddle.net/ro23xbc4/1/
