### ISSUE TITLE
Does it support delay?

### ISSUE THREAD

**Issue by debotos** [CookPete/react-player#822]
The src is an array and I want to delay 5 seconds before playing the second one. Is there is any way to achieve it?
```js
<ReactPlayer playing url={['one.mp3', 'two.mp3', 'three.mp3']} />
```

**Comment by CookPete** [comment]
An array of URLs like that will not work. Arrays are used to provide multiple different source files in different format/encoding: https://github.com/CookPete/react-player#multiple-sources-and-tracks

What you want is to store an array of videos, keep an `index` in state, and increase the index to change the `url` that you pass in to `ReactPlayer`. Just use `setTimeout` if you want to wait 5 seconds before incrementing the `index` state. Very basic example: https://jsfiddle.net/01s8a4yv/
