### ISSUE TITLE
Can you play local files?

### ISSUE THREAD

**Issue by Pauly24** [CookPete/react-player#823]
Can you play local files? ie url={'./movie.mpg'} or something of the sort?

**Comment by d33pak-singh** [comment]
Is this supported yet??

**Comment by CookPete** [comment]
If you are running a React app locally (or just opening a local index.html file in chrome), just put the video in the same folder as the app and set `url` to the name of the video.

![image](https://user-images.githubusercontent.com/1926029/77582428-47cf1880-6ed7-11ea-872b-e292d32429d5.png)

If you try to play a __local file from a hosted app or local web server__, Chrome (and probably others) will give you a security error along the lines of `Not allowed to load local resource`

![image](https://user-images.githubusercontent.com/1926029/77582716-b7dd9e80-6ed7-11ea-9aa8-fe3831520b8e.png)

You can get around this by [launching Chrome with `--allow-file-access-from-files`](https://stackoverflow.com/questions/18586921/how-to-launch-html-using-chrome-at-allow-file-access-from-files-mode), but this will only enable file access on your machine, when opening Chrome in this specific way.

**Comment by genc6541** [comment]
If we launch with --allow-file-access-from-files command on chrome , will it play the video without doing any other things?

**Comment by genc6541** [comment]
@cookpete Hi could you answer me please?

**Comment by whawker** [comment]
@genc6541 jeez mate, have a bit of patience, it's called open source, not customer support. 

I suggest you Google what that flag does, and come back with a constructive question rather than a, "hey, have you done this for me yet?!"

**Comment by genc6541** [comment]
Hi , mate I only wonder one thing. Does this player can play video from spesific path?(Yes or No) Answer of this question very simple for develper of this component. I had opened issue about this topic 3 day ago and it was cloesed without any response and redirected me this page. I had tried the open with the chrome command and searched google for another options but video could not play from path. If this player not supported this kind of playing I want to know this only.

**Comment by cookpete** [comment]
>Hi could you answer me please?

I have a family and a full time job. Maintaining this repo is a hobby that I don’t get paid for. Please try and be patient.

>will it play the video without doing any other things?

This is a very unclear question.

>Does this player can play video from spesific path?(Yes or No) Answer of this question very simple for develper of this component.

This is not a simple yes or no question. Chrome and other browsers do not allow access to local files for security reasons. You can get around the restriction in Chrome by launching with `--allow-file-access-from-files` but this will only work for your locally running version of Chrome and will not work if you want to deploy your app somewhere.

I recommend using [`serve`](https://www.npmjs.com/package/serve) to run your application locally, and putting your local video file in the same directory as your app.

**Comment by wacelalorshe** [comment]
> Can you play local files? ie url={'./movie.mpg'} or something of the sort?

**Comment by wacelalorshe** [comment]
[Bein](http://mynetworks.info:80//live/TestFD1015/DF1015FBBE447/1644.m3u8) 
![Uploading PhotoRoom-٢٠٢٣٠٤٠٦_٠٢٢٢٢٤.png…]()
