### ISSUE TITLE
On Safari audio is not playing second time

### ISSUE THREAD

**Issue by debotos** [CookPete/react-player#824]
I have a button and by clicking on that button it starts playing an audio. Then I have a setTimeout call of 5 seconds. After that timeout, I am changing the src of the audio.

Now the situation is when I am clicking on that button it works fine and starts playing. But after 5 seconds it's in the playing mode but not going to play the sound until I manually click on the play/pause button.

It's only happening on Safari but works in chrome. In Safari, I need to manually click on the play/pause button.

**Comment by CookPete** [comment]
@debotos Does it happen for you in this example? It seems ok for me in Safari: https://jsfiddle.net/d3rjxbaf/

Click `Next` to load the first mp3 and then after 5 seconds it will switch to another mp3.
