### ISSUE TITLE
Can't play mp4 video that requires authentication

### ISSUE THREAD

**Issue by Tam66662** [CookPete/react-player#825]
I would like to see an example of how I can play an mp4 file from my local NextCloud server through the react-player.

This is for demo purposes, so security isn't a priority unless it is mandated by react-player.

When I hardcode my url as "http://(user):(pass)@(ip):(port)/dav/files/(user)/myvideo.mp4", it gives me a "503 (Service unavailable)" response.  But if I type that same URL into VLC Player, it will play the file without issue.

Are there any examples of how to use react-player with basic auth credentials?

Any help would be greatly appreciated.

**Comment by CookPete** [comment]
ReactPlayer will just render a basic `<video>` element behind the scenes, with your hardcoded URL as the `src`. If a standard `<video>` can't play it, then ReactPlayer won't be able to either.

I imagine `VLC Player` has much more logic behind it to resolve authed URLs compared to a browser.
