### ISSUE TITLE
Custom URL, not playing

### ISSUE THREAD

**Issue by KahyeAhn** [CookPete/react-player#828]
#### Current Behavior
I'm trying to play a video from custom url.
It works with thumbnail, but it doesn't play anything.

#### Expected Behavior
It should play my video

#### Steps to Reproduce
      <ReactPlayer
        url="http://v.kr.kollus.com/Wplj7tdp"
        light="http://v.kr.kollus.com/poster/Wplj7tdp.jpg"
        playing
        controls={true}
      />
This is the element that I wrote for playing a video. You can check if this video plays well on the website by clicking URL directly.
#### Environment
- URL attempting to play: http://v.kr.kollus.com/Wplj7tdp
- Browser: Chrome
- Operating system: Windows 10

**Comment by Imlus** [comment]
This video requires flash player to be played, this is in no way a react player issue :)
