### ISSUE TITLE
Couldn't get hls levels by using getInternalPlayer('hls')

### ISSUE THREAD

**Issue by jacksun0124** [CookPete/react-player#829]
I have a video website, and I am using m3u8 file as video source. I want to add a resolution switch button to my project, but I could get hls levels from getInternalPlayer('hls').  Can anyone help?

#### My code 

```
import './App.css';
import React, { Component } from 'react'
import ReactPlayer from 'react-player'

class VideoApp extends Component {

    constructor(props) {
        super(props);
        this.state = {
            loaded: true,
        };
    }

    ref = player => {
        this.player = player
        console.log("Player info");
        console.log(this.player);
        console.log("hls info");
        console.log(this.player.getInternalPlayer('hls'));
    }
    
    render() {
        if (this.state.loaded) {
            return (
                <div>
                    <ReactPlayer
                        playing={false}
                        controls
                        ref={this.ref}
                        pip={false}
                        config={{
                            file: {
                                attributes: {
                                    controlsList: 'nodownload',
                                    disablePictureInPicture: true
                                },
                            }
                        }}
                        url={"https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8"}

                    />
                    <div>
                    </div>
                </div>
            );
        } else {
            return (
                <div></div>
            );
        }

    }
}
export default VideoApp;
```

#### Current Behavior

```
ref = player => {
        this.player = player
        console.log("Player info");
        console.log(this.player);
        console.log("hls info");
        console.log(this.player.getInternalPlayer('hls'));
}
```
console.log(this.player) does show me some video information.

console.log(this.player.getInternalPlayer('hls')) shows undefined.

#### Expected Behavior

console.log(this.player.getInternalPlayer('hls')) shows level information.

#### Environment
- Browser: 
Chrome
- Operating system: 
MacOS 
- node --version
v10.16.3
- react-player
1.15.2

**Comment by alcbotta** [comment]
instead of  `console.log(this.player.getInternalPlayer('hls'))`, what does `console.log(this.player.current.getInternalPlayer('hls'))` display? if it shows the player, you should be able to access the levels by doing something like: `hlsInstance.levels[0]`

**Comment by CookPete** [comment]
You're trying to use `getInternalPlayer` too early. The player isn't ready when your `ref` method is running. Use `onReady` to know when you can run the various player methods: https://jsfiddle.net/uad16v5s/
