### ISSUE TITLE
Support for RTSP Stream from IP CAM

### ISSUE THREAD

**Issue by dfuchs2512** [CookPete/react-player#83]
Hello,

I have a question and maybe its already working. Does the player support also URLs with rtsp stream from IP Cameras or do you plan to integrate this. I was trying with the demo page but when I use a URL from a RTSP stream its not showing up the video.

Any plans on this to implement or is there a solution already which I did not see?

Thx

Daniel

**Comment by CookPete** [comment]
What does the stream URL look like? If it works in a regular `<video>` tag then adding support is as easy as updating the [supported extensions regex in FilePlayer](https://github.com/CookPete/react-player/blob/a76daa27eaf9dba7013f9868664fa4fdb9fb3407/src/players/FilePlayer.js#L5-L6)

**Comment by CookPete** [comment]
Should be fixed in `0.7.5`

**Comment by CookPete** [comment]
Ah, this fix was rather shortsighted of me. It seems like RTSP streams are generally not supported very well (or at all) by HTML5 media elements right now. Fixing this properly would involve some sort of additional flash/VLC/webRTC plugin.

http://stackoverflow.com/questions/1735933/streaming-via-rtsp-or-rtp-in-html5
