### ISSUE TITLE
Light mode vs autoplay

### ISSUE THREAD

**Issue by dbismut** [CookPete/react-player#830]
Hi! Sorry for not using the issue template, but this is just a question: shouldn't the video autoplay once light mode preview disappears?

**Comment by CookPete** [comment]
If you are passing in `playing={true}` then yes, it should autoplay. Although note that [autoplay is dying](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes), and will not work fully on some browsers. I'm not sure if the click on the light mode thumbnail counts as an interaction that will enable autoplay, as the element playing the media won't have loaded at that point.

**Comment by dbismut** [comment]
Hm it actually skips the preview and goes into autoplay mode. If this is not considered normal behavior I’ll submit a proper bug report with a sandbox.
