### ISSUE TITLE
[feature request] Add prefetch hints when preload is true

### ISSUE THREAD

**Issue by seaneking** [CookPete/react-player#831]
When `preload` is `true`, it would be great if react-player added a prefetch hint (could use `react-helmet` to make it easier) to increase preloading perf even more.

```
<link rel="prefetch" href={iframeVideoSrc} />
```

**Comment by seaneking** [comment]
Also adding `dns-prefetch` hints to all the players used would help as well

```
<link rel="dns-prefetch" href="https://player.vimeo.com/" />
```

**Comment by CookPete** [comment]
I feel like this is probably overkill for the scope of this library, and very easy for developers to add to their apps if they want. Do you have any benchmarks for how much faster a player loads with these hints? 

I'm not even sure I'm going to include preload behaviour in 2.0. It is becoming redundant as more browsers disable autoplay by default, and it's quite hacky behaviour to solve a very specific edge case.
