### ISSUE TITLE
Youtube videos no longer play on Chrome

### ISSUE THREAD

**Issue by grant-davidson** [CookPete/react-player#834]
#### Current Behavior
YouTube videos are no longer playing if an Ad-blocker is active.  

They fail with YouTube displaying the error:
"An error occurred. Please try again later. (Playback ID: xxxx-xxxxxxx)

#### Expected Behavior
The video should play without an error.

#### Steps to Reproduce
1.  Go to https://cookpete.com/react-player/
2.  Enable an ad-blocker (Adblock Plus)
3.  Click on the YouTube Test A or Test B button

#### Environment
- Browser: Chrome 
- Operating system: Windows 10

#### Other Information
The YouTube demo is working fine from Firefox
The videos play fine directly from YouTube.
The videos were playing fine a few days ago so maybe this is just a YouTube problem related to system overloading

**Comment by CookPete** [comment]
This certainly is a problem, but I don't think it's anything ReactPlayer can fix.

**Comment by grant-davidson** [comment]
It would be great if react-player could detect that it was being blocked. We could then ask the user to turn off their ad blocker

**Comment by grant-davidson** [comment]
Using the onError event to display seems like a reasonable solution to this problem.
Thanks Pete for your response.
