### ISSUE TITLE
ReactPlayer inside Angular

### ISSUE THREAD

**Issue by friksa** [CookPete/react-player#835]
Just wanted to give you a shout out and thank you for a great project.  We are using your Javascript only version inside of an Angular SPX and it works great.  It is now part of our web conferencing solution and allows synchronized video playback for all users in the meeting.

We hope that you will keep your pure Javascript support for future versions of the project.

Would there be value to open source the Angular Directive for ReactPlayer (after version 2 is released)?

**Comment by CookPete** [comment]
>We are using your Javascript only version inside of an Angular SPX and it works great.

This is pretty awesome, but must add quite a big chunk to the bundle size? The standalone mode basically includes the entire `react` and `react-dom` library in a big file and isn't very practical for use at scale. Have you considered just using [whatever player API ReactPlayer is using in the background](https://github.com/CookPete/react-player#supported-media) and hooking into that directly?

>Would there be value to open source the Angular Directive for ReactPlayer (after version 2 is released)?

There is no Angular version of ReactPlayer that I'm aware of. Nothing stopping someone from creating `AngularPlayer` though ;)
