### ISSUE TITLE
Playing HLS files from s3 bucket

### ISSUE THREAD

**Issue by devnantes44** [CookPete/react-player#836]
#### Current Behavior
In my s3 bucket I have two objects:

1. https://mybucketname.s3-eu-west-1.amazonaws.com/public/myfilename.m3u8
2. https://mybucketname.s3-eu-west-1.amazonaws.com/public/myfilename_360.ts

Because I'm using Storage.get from AWS Amplify, I'm able to get a signed url. So when I'm requesting the signed .m3u8 link in my front-end using the react-player, everything works fine.
However, the player executes automatically a get request to the .ts url so I've got a 403 forbidden error because this URL is not signed.

#### Expected Behavior
Before the player executes automatically the get request to the .ts file, I would like to be able to sign it using Storage.get (or to be able to do any other logic), from AWS Amplify then only after, to execute the get request with this signed .ts url.

**Comment by CookPete** [comment]
Looks like a similar problem to https://github.com/CookPete/react-player/issues/442. I'm not sure what ReactPlayer can do about this. There might be a `hls.js` feature that's useful? https://github.com/video-dev/hls.js/blob/master/docs/API.md#xhrsetup
