### ISSUE TITLE
FilePlayer is not rendering

### ISSUE THREAD

**Issue by beqaMeqvabishvili** [CookPete/react-player#837]
#### Current Behavior
while importing and using FilePlayer from "react-player/lib/players/FilePlayer", it fails to render a new player. no error logs in the console and no html elements rendered in its place. Using `ReactPlayer` component instead works as expected.

#### Expected Behavior
should render and play file url.

#### Steps to Reproduce
1. import `FilePlayer`
2. use `URL.createObjectURL()` on mp4 file and use returned value as url prop for FilePlayer

#### Environment
- URL attempting to play: `"blob:http://localhost:3000/9bb258c9-b914-4ab1-b4a0-808b347725ea"`
- Browser: Chrome, Firefox
- Operating system: windows 10
- npm version: ^1.15.2
- ~jsFiddle~ codeSandbox example: https://codesandbox.io/s/admiring-bush-umu0z

Edit: tried on ogv file and the same thing happened.

**Comment by CookPete** [comment]
`ReactPlayer.js` has the logic to fall back to `FilePlayer` if `canPlay` returns false for all players. `FilePlayer` is missing that logic.

Try add ```config={{ file: { forceVideo: true } }}``` to your `FilePlayer`  which will skip this check:

https://github.com/CookPete/react-player/blob/9be7a9c9d24d08801b1f31f93bdfabf45ea1bf83/src/singlePlayer.js#L55-L59
