### ISSUE TITLE
Changes to width and height props are ignored

### ISSUE THREAD

**Issue by claus** [CookPete/react-player#84]
Is there any reason why changing the width and height props are not triggering a render?

I am working on an app that uses react-player in an overlay that spans the entire viewport, where the react-player component is supposed to adjust to viewport size when the browser window is resized. After setting the initial values for width/height, later changes are ignored due to the implementation of ReactPlayer.shouldComponentUpdate(). To work around that, i have to call this.refs.reactPlayer.forceUpdate(), which works just fine. It would be much nicer to just test width/height in ReactPlayer.shouldComponentUpdate(), in addition to url/playing/volume.

https://github.com/CookPete/react-player/blob/master/src/ReactPlayer.js#L20-L26

**Comment by CookPete** [comment]
Good spot. This should be an easy fix.

**Comment by sarjford** [comment]
I'm having a similar issue. The width is not adjustable. Please let me know if there's something I'm missing. Thanks.

**Comment by CookPete** [comment]
Should be fixed in `0.7.5`
