### ISSUE TITLE
Seek is not working on mobile devices

### ISSUE THREAD

**Issue by SoldierCorp** [CookPete/react-player#840]
Hi,

Even with your https://cookpete.com/react-player, the seek is not working in any mobile browser.

**Comment by CookPete** [comment]
The [code for the demo seeker](https://github.com/CookPete/react-player/blob/master/src/demo/App.js#L216-L222) is admittedly not great. Using `mouseDown` and `mouseUp` events will make things pretty choppy on mobile. I plan to updated this.. soon.

I'm sure a mobile-friendly slider like [`react-range`](https://github.com/tajo/react-range) would work fine when hooked up to ReactPlayer's methods.
