### ISSUE TITLE
Does it support audio sprite?

### ISSUE THREAD

**Issue by debotos** [CookPete/react-player#841]
Audio Sprite similar to - https://howlerjs.com/#sprite | https://github.com/goldfire/howler.js#define-and-play-a-sound-sprite | https://github.com/goldfire/howler.js#sprite-object-

**Comment by CookPete** [comment]
This has been asked a couple of times already: 
- https://github.com/CookPete/react-player/issues/153 
- https://github.com/CookPete/react-player/issues/472
