### ISSUE TITLE
Unable to play Vimeo with sound and fullscreen in iOS

### ISSUE THREAD

**Issue by webartistse** [CookPete/react-player#842]
#### Current Behavior
The vimeo thumbnail appears but does not play the video.

#### Expected Behavior
Start play the video in fullscreen with sound.

#### Steps to Reproduce
This setting does not work in iOS:
videoOptions.vimeo = { autoplay: true, playsinline: false }

Works but no sound and inline player:
videoOptions.vimeo = { autoplay: true, background: true, playsinline: true }

#### Environment
- iOS 13.3.1
- Safari

**Comment by JenniferFuBook** [comment]
I cannot play fullscreen on Firefox 76.0.1 for any video.
I cannot load mp4 on Safari.

**Comment by CookPete** [comment]
See https://github.com/CookPete/react-player#mobile-considerations

iOS and other browsers are slowly killing autoplay – most now require user interaction (ie a click or tap directly on the page or video) to play the video with sound.

iOS has always been very limited in how much control you have over how video plays. This is not likely to change any time soon.
