### ISSUE TITLE
Wistia JSON schema markup

### ISSUE THREAD

**Issue by milesalex** [CookPete/react-player#843]
Is it possible to get the JSON schema markup for wistia videos via this player?

Here's my config

```js
const CONFIG = {
            wistia: {
              options: {
                videoFoam: true,
                playerColor: '4948EE',
                seo: true,
              },
            },
          };
```

**Comment by CookPete** [comment]
@milesalex I'm not sure what exactly you're after, sorry. 

The list of possible options you can pass in is here: https://wistia.com/support/developers/embed-options#list-of-all-options if that helps?
