### ISSUE TITLE
Feature Request: React Hooks

### ISSUE THREAD

**Issue by jakobsuckow** [CookPete/react-player#844]
Hi, 
first of all, I really like the simplicity of your component. It is super easy to use and make streaming music on an app really easy. 

As the state of react progresses and classes become obsolete, I would very much appreciate the introduction of hooks for react-player. 
As my whole app is written with hooks I feel more comfortable integrating the react-player module with useState and useEffect. 

Thank you for your help.

Kind regards,
Jakob

**Comment by CookPete** [comment]
I recently attempted to rewrite the entire library using hooks, but it didn't go very well. There is still a need for a player instance that methods can been called on, and there is a huge reliance on third party scripts that require refs to DOM elements, which can't be done with functional components.

>As my whole app is written with hooks I feel more comfortable integrating the react-player module with useState and useEffect.

You are able to use `useState` and `useEffect` in your app regardless of ReactPlayer's internals. Feels like you are needlessly limiting yourself if you insist on only using libraries written using hooks.

>As the state of react progresses and classes become obsolete

This is not true, according to the [hooks docs](https://reactjs.org/docs/hooks-intro.html#gradual-adoption-strategy):

>There are no plans to remove classes from React.
>
>...
>
>We will keep supporting class components for the foreseeable future. At Facebook, we have tens of thousands of components written as classes, and we have absolutely no plans to rewrite them.

That said, I plan to completely rewrite the demo app using hooks at some point in the future.

**Comment by CookPete** [comment]
I still plan on rewriting the library using hooks. However, the logic you describe is simple enough to not need to reverse engineer the demo. Here's a rough example with a play/pause button and a next button:

```jsx
const VIDEOS = [
  'https://www.youtube.com/watch?v=C0DPdy98e4c',
  'https://www.youtube.com/watch?v=Mxesac55Puo'
]

const Player = () => {
  const [index, setIndex] = React.useState(0)
  const [playing, setPlaying] = React.useState(false)
  
  return (
    <div>
      <ReactPlayer
        url={VIDEOS[index]}
        playing={playing}
        controls
        onPlay={() => setPlaying(true)}
        onPause={() => setPlaying(false)}
        onEnded={this.nextVideo}
        />
      <button onClick={() => setPlaying(playing => !playing)}>
        {playing ? 'Pause' : 'Play'}
      </button>
      <button onClick={() => setIndex(index => index + 1)}>
        Next
      </button>
    </div>
  )
}
```

https://jsfiddle.net/kx12hq5s/

**Comment by gordielachance** [comment]
Hi and thanks for [that example](https://jsfiddle.net/kx12hq5s/) !
But I get an error (not on your demo page), it returns

`TypeError: Cannot read property 'nextVideo' of undefined

`
Have you got an idea of what it could be ?
Thanks !

**Comment by gordielachance** [comment]
PS I found out using a Ref !

    export const Player = () => {
    	const [index, setIndex] = React.useState(0)
      const [playing, setPlaying] = React.useState(false)
      const playerComponent = React.createRef();

      const handleOnEnded = state => {
        playerComponent.current.nextVideo();
      }

      return (
        <div>
          <ReactPlayer
            ref={playerComponent}
            url={VIDEOS[index]}
            playing={playing}
            controls
            onPlay={() => setPlaying(true)}
            onPause={() => setPlaying(false)}
            onEnded={handleOnEnded}
            />
          <button onClick={() => setPlaying(playing => !playing)}>{playing ? 'Pause' : 'Play'}</button>
          <button onClick={() => setIndex(index => index + 1)}>Next</button>
        </div>
      )
    }
