### ISSUE TITLE
Hls not auto playing sometime

### ISSUE THREAD

**Issue by wkpuy** [CookPete/react-player#847]
onReady not working when video not auto play  but if click play in control video it play normal

`
              <ReactPlayer url={this.state.link_streaming}
                width="50%"
                height="30%"
                controls={true}
                ref={p => { this.p = p }}
                //light="true"
                // style={{ borderStyle: "solid" }}
                onReady={() => this.setState({ playing: true })}
                onStart={() => this.setState({ visible_button_refresh: true })}
                onSeek={e => console.log('onSeek', e)}
                onEnded={() => console.log("end")}
                onDuration={this.handleDuration}
                onProgress={this.handleProgress}
                onBuffer={() => console.log('onBuffer')}
                onError={e => this.onErrorPlayer(e)}
                allowFullScreen
                playing={this.state.playing}

`

**Comment by CookPete** [comment]
This needs more detail, sorry.

**Comment by BrodaNoel** [comment]
@CookPete when you have a `light` defined, if you click on PLAY-icon, then you need to click on PLAY-controls to play the video

**Comment by BrodaNoel** [comment]
If you have this:
```
          <ReactPlayer
            controls
            url={url}
            light={videoThumb}
            width="100%"
            height="100%"
          />
```

First you click on the PLAY-icon, and you'll see how to video loads, but it's not playing.

Hapenning in Chrome

**Comment by CookPete** [comment]
> Shouldn’t the library programmatically call “play” in that situation?

This doesn’t make sense when you consider the [declarative nature of React](https://stackoverflow.com/a/33656983/1250405). Calling `play()` would result in a video playing even though the `playing` prop is false, which breaks the declarative pattern and is prone to bugs.

**Comment by BrodaNoel** [comment]
So we should handle the “onThumnailClick” and there switch “playing” to “true” and even there the video is not gonna be played?

That idea feels like: “this is a video-player that doesn’t allow to play videos”.
There should be a way to fix it. If not... it doesn’t makes any sense to use “light” if the video can not be reproduced (with audio)

Broda Noel
