### ISSUE TITLE
how to display a button on video after video ends

### ISSUE THREAD

**Issue by pavinduLakshan** [CookPete/react-player#848]
### Current Behavior
I am developing a e-learning application and I want to display a button on video so that user can go to the next lesson on click of the button. I also posted a question regarding this on SO, but had no answers to this day and therefore I decided to open an issue.

#### Expected Behavior
I want to display a button after video ends on the video itself

#### Environment
- Browser: Chrome
- Operating system: Windows 

#### Other Information
The link to SO question: https://stackoverflow.com/questions/60973531/how-to-display-a-button-on-the-video-after-video-ends-with-react-player

**Comment by CookPete** [comment]
Looks like this was answered [here](https://stackoverflow.com/questions/60973531/how-to-display-a-button-on-the-video-after-video-ends-with-react-player#comment108143030_61100320) with [this example](https://codesandbox.io/s/lively-cherry-y08uy). Shout out to to `nnals` for the answer, wherever you are.
