### ISSUE TITLE
Hide Download, Picture in Picture and onContextMenu but none of it seems to work

### ISSUE THREAD

**Issue by charleslouis** [CookPete/react-player#850]
#### Current Behavior

I want to hide Download, Picture in Picture and onContextMenu but none of it seems to work.

![image](https://user-images.githubusercontent.com/2117081/79040675-cd023f00-7bf2-11ea-9db1-ae8d32c06786.png)

I've looked at https://github.com/CookPete/react-player/issues/551 or https://github.com/CookPete/react-player/issues/323#issuecomment-364357541

#### Expected Behavior
Hide Download, Picture in Picture and onContextMenu

#### Steps to Reproduce
```
        <ReactPlayer
          urlVideo={urlVideo}
          sound={sound}
          config={{
              file: {
                attributes: {
                  onContextMenu: e => e.preventDefault(),
                  controlsList: 'nodownload nofullscreen noremoteplayback',
                  play: () => alert('movie played'),
                  ended: () => alert('movie ended')
                }
              }
          }}
          />
```

note : I have also tried onEnded and onPlay 

```
        <ReactPlayer
          urlVideo={urlVideo}
          sound={sound}
          onPlay: () => alert('movie played'),
          onEnded: () => alert('movie ended
          config={{
              file: {
                attributes: {
                  onContextMenu: e => e.preventDefault(),
                  controlsList: 'nodownload nofullscreen noremoteplayback',')
                }
              }
          }}
          />
```

#### Environment
- URL attempting to play: `http://clips.vorwaerts-gmbh.de/VfE_html5.mp4`
- Browser: chrome
- Operating system: MacOS
- jsFiddle example: https://jsfiddle.net/cw1kfny8/2/

#### Other Information
None of the `config.file.attributes` is working
Sound on/off is working

![image](https://user-images.githubusercontent.com/2117081/79040841-11420f00-7bf4-11ea-9679-d530a75fae8c.png)

**Comment by CookPete** [comment]
This works for me on Chrome 81, macOS 10.15.3: https://jsfiddle.net/r74opd0m/2/

Your examples have some JSX syntax errors:

```jsx
<ReactPlayer
  urlVideo={urlVideo}
  sound={sound}
  onPlay: () => alert('movie played'),
  onEnded: () => alert('movie ended
```

This is invalid syntax. It should be:

```jsx
<ReactPlayer
  urlVideo={urlVideo}
  sound={sound}
  onPlay={() => alert('movie played')}
  onEnded={() => alert('movie ended')}
```

Please re-open if you can create a jsFiddle that fully demonstrates a problem.

**Comment by charleslouis** [comment]
Hi @CookPete 

Thanks for the quick feedback.
Indeed the syntax was invalid due to a quick copy/paste as I tried to setup onPlay/onEnded in `file.attribute`.

Mainly, the issue was that the `<ReactPlayer>` was actually calling a `<HomeMadeReactPlayer>` that in turn was calling the `<ReactPlayer>` from node_modules. 

In my current file : 
But `<HomeMadeReactPlayer>` was called `<ReactPlayer>`  too. 
`// import ReactPlayer from '../../components/VideoPlayer/VideoPlayer';`
that in turn calls `import ReactPlayer from 'react-player';`

So any props that was not passed from `<HomeMadeReactPlayer>` too `<REALReactPlayer>` was dismissed.

Makes sense ?

Cheers
