### ISSUE TITLE
Feature Requested: Option for changing video quality for youtube videos

### ISSUE THREAD

**Issue by mahmodHammad** [CookPete/react-player#852]
This work is really awesome and saved my days of hard work , Thank you for that .
the only thing i need is the ability to changing video quality for youtube videos.

![image](https://user-images.githubusercontent.com/41790090/79469885-05de5180-8001-11ea-9b40-a429b8b73dba.png)

**Comment by CookPete** [comment]
Unfortunately it looks like this hasn't been possible for a while now:

>The documentation has been updated to reflect the fact that the API no longer supports functions for setting or retrieving playback quality. As explained in this YouTube Help Center article, to give you the best viewing experience, YouTube adjusts the quality of your video stream based on your viewing conditions.
>
>The changes explained below have been in effect for more than one year.

https://developers.google.com/youtube/iframe_api_reference#release_notes_10_24_2019
