### ISSUE TITLE
Need help for CSP issues about my browser extension using React-Player

### ISSUE THREAD

**Issue by MelodicCrypter** [CookPete/react-player#853]
I don't think that this issue is related to react-player directly, but it is involved in some ways. I have created a browser extension that would let the user click a movie thumbnail and show a box where they can watch that movie's trailer. I used react-player in showing that trailer.

When I tested it in it showed an error that:

_Refused to load the script 'https://www.youtube.com/iframe_api' because it violates the following Content Security Policy directive:_ 

I know that this is related to my manifest.json file which needs to be set up correctly if I want to connect to youtube's website. Before, Mozilla team did not bother about it and my app passed by adding this code to the manifest:

`"content_security_policy": "script-src 'self' https://youtube.com https://www.youtube.com https://s.ytimg.com https://ytimg.com; object-src 'self'"`

but just this week they disabled my app because they said I'm allowing remote script. I think they have changed their rules.

The main reason why I asked here is that the only solution to this is to embed directly or download the youtube script directly into my app. I want to know if there is a way I can manually put the script that connects to youtube? I don't know if that's possible to download the script. Is it possible? Or the only way to connect to youtube using react-player is through an API?

I even opened a question at Stackoverflow => [my stackoverflow question](https://stackoverflow.com/questions/61263957/mozilla-team-disabled-my-addon-because-of-content-security-policy-how-to-set-m?noredirect=1#comment108398637_61263957)

I'm hoping that someone could lend some help to this issue I'm facing. Thank you!

**Comment by CookPete** [comment]
The script behind `https://www.youtube.com/iframe_api` just sets up the `YT` global and loads another script file. You could save your own `iframe_api.js` file and just comment out the script-loading lines (example [here](https://gist.github.com/CookPete/92eb0bf00704038061be0c9b08c18ae8)) then just save the [widget code that is normally loaded](https://s.ytimg.com/yts/jsbin/www-widgetapi-vflJJaNgk/www-widgetapi.js) and include it in your extension.

Then just include the two scripts in your extension before loading ReactPlayer:

```html
<script type="text/javascript" src="./iframe_api.js"></script>
<script type="text/javascript" src="./www-widgetapi.js"></script>
<script type="text/javascript" src="./script-that-uses-react-player.js"></script>
```

No idea if this will work (there might be more scripts that load) but worth a try?

**Comment by animber0** [comment]
@cookpete 

This issue is not completed! 

This works for Vimeo but not for Youtube, and completely bypasses some of the code in React Player!
