### ISSUE TITLE
(IE 11) Replaying an .mp4 file doesn't allow for play/pause control

### ISSUE THREAD

**Issue by kphurley** [CookPete/react-player#854]
#### Current Behavior
In Internet Explorer 11, after playing an .mp4 file to the end and then playing the same file again from the beginning, the play/pause toggle no longer seems to affect the internal state of the `<video>`.

#### Expected Behavior
Play/pause toggle plays and pauses the video on subsequent replays of the video.

#### Steps to Reproduce
1. Load demo
1. Choose "mp4" button to load a sample mp4 file
1. Play or seek to the end
1. Play again from beginning

#### Environment
- URL attempting to play: http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4
- Browser:  Internet Explorer 11.778.18362.0
- Operating system:  Windows 10

**Comment by CookPete** [comment]
I’m sorry this is causing you problems but I have zero capacity (in both time and patience) to support IE11.
