### ISSUE TITLE
Can't get mp4 file to buffer

### ISSUE THREAD

**Issue by davewurtz** [CookPete/react-player#856]
#### Current Behavior
I'm using the ReactVideo component to play a set of .mp4 files:

<ReactPlayer
    ref={(player) => (this._reactPlayer = player)}
    url={this.state.playerSource}
    playing={true}
    played={0}
    loaded={0}
    controls={true}
 />

The user clicks on a video, which, ultimately, set this.state.playerSource to a URL of the file.  An example is http://www.asdnetwork.com/asdsupport/content/videos/myTestVideo.mp4, which is a fairly large video.

The video does eventually start, but not until the entire video has been 'downloaded'.  Also, as you can see, I am showing the player's controls, but I cannot click on the 'duration bar' (not sure that's what it is called) to advance the video forward or backward - it just keeps playing from the current point.

I have tried the same video (from the above URL) in the react-video demo application (https://cookpete.com/react-player/) and it loads very fast and buffers as the video plays.  I can also go forward/backward by clicking on the 'duration bar'.  However, I also downloaded, from GitHub (git clone https://github.com/CookPete/react-player.git; npm install; npm start), the demo code, built, and ran the demo application and I get the same behavior as my application, not the demo web page (https://cookpete.com/react-player/) - after pressing typing in the video and pressing "Load", the video does not appear until it is completely loaded (the "Loaded" progress bar is 100% also).

I'm not sure what code to post here, but based upon my description of the problem, is there some setting, installation, etc. that I need to do to get this to behave like the demo page?  As mentioned, I was able to duplicate by downloading the sample demo from GitHub.

#### Expected Behavior
Video to start quickly and buffer as the video is played - like the demo page

#### Environment
- URL attempting to play: http://www.asdnetwork.com/asdsupport/content/videos/myTestVideo.mp4
- Browser: Chrome
- Operating system: Windows 10

**Comment by CookPete** [comment]
I'm almost certain this is to do with the configuration of the server sending the video file.

Compare the network request for your large video:

![image](https://user-images.githubusercontent.com/1926029/82741199-b0a40700-9d47-11ea-87e4-647b3727d568.png)

to the network request for the sample MP4 at http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4

<img width="391" alt="Screenshot 2020-05-23 at 22 48 34" src="https://user-images.githubusercontent.com/1926029/82741210-c9acb800-9d47-11ea-989d-37f6657075b2.png">

Looks like the server with the large video needs to be set up to serve partial content.

As for why the load times differ on your machine.. possibly browser caching? I'm not sure.

**Comment by CookPete** [comment]
Feel free to re-open if you find out this is a problem with ReactPlayer specifically.
