### ISSUE TITLE
Trouble with WAV using Blob url

### ISSUE THREAD

**Issue by xavierboudreau** [CookPete/react-player#858]
#### Behavior
The following code works fine (plays audio) when the `separate` endpoint returns an MP3 (I'm using Flask's `send_file` on the server). However, when the endpoint returns a WAV, the audio doesn't play and the following error gets printed to console:
`error: MediaError
code: 4
message: "DEMUXER_ERROR_NO_SUPPORTED_STREAMS: FFmpegDemuxer: no supported streams"`. Note that the Blob object and url print to console fine for both WAV and MP3.

#### Code
```
import React, {useCallback, useState} from "react"
import ReactPlayer from "react-player"

export default () => {
    const [isSending, setIsSending] = useState(false);
    const [vocals, setVocals] = useState();
    
    const handleClick = useCallback(async ()=>{
        if (isSending) return;

        setIsSending(true);
        const response = await fetch('http://127.0.0.1:8001/separate', {method: 'GET',});
        var reader = response.body.getReader();
        
        reader.read().then((result) => {
            var blob = new Blob([result.value], { type: 'audio/x-wav' });
            console.log(blob);
            var url = window.URL.createObjectURL(blob);
            console.log(url);
            setVocals(url);
        });
        
        setIsSending(false);

    }, [isSending, vocals]);

    const playerError = (err) => {console.log(err)};

    const prompt = isSending ? 'Extracting vocals, please wait' :  'Hello'

    const playButton = vocals!==undefined ? <ReactPlayer url={vocals} playing onError={playerError}/> : null

    return <div>
            <button onClick={handleClick}>{prompt}</button>
            {playButton}
        </div>
}
```

#### Environment
- URL attempting to play: Blob url
- Browser: Google Chrome
- Operating system: MacOS

**Comment by CookPete** [comment]
Seems like Chrome just can't play the specific type of WAV you are serving it. `MediaError code: 4` is [`MEDIA_ERR_SRC_NOT_SUPPORTED`](https://developer.mozilla.org/en-US/docs/Web/API/MediaError/code).

Possibly related discussion: https://bugs.chromium.org/p/chromium/issues/detail?id=83323

>WAV files can be tricky because they can contain anything.
>
>The server returns Content-Type: audio/wav so Chrome attempts to play it with the built-in player, but is unable to do so because this file in question uses logarithmic / mu-law PCM:
http://en.wikipedia.org/wiki/%CE%9C-law_algorithm
>
>It's one of those more esoteric WAV formats you occasionally find in the wild.

**Comment by xavierboudreau** [comment]
Thanks for the reply. If that's what the problem is I'll go ahead and close this issue.
