### ISSUE TITLE
Where should I see or whar should I use in order to enable two buttons, one for going back 15 sec and another one to go forwrad 15 sec.

### ISSUE THREAD

**Issue by josoroma** [CookPete/react-player#859]
Hi!

I was wondering.. Where should I see or what should I use in order to enable two buttons, one for going back 30 seconds and another one to go forward 15 seconds.

Thanks!

**Comment by brauliodiez** [comment]
MMmmm... I'm taking a look to that functionallity, I think is something that ca be easy to implement if you are not in full screen mode, my idea (following the example provided by @CookPete):

  - You can get from the player the duration of the video.
  - You can get the current progress of the video (0...1 range)
  - You can get the current position that is being streamed (e.g. 0.45).
  - You can do a simple calc to know how much progress is 30 secs in that video (e.g. 1 hour video is 3600 secs, that is progress 3600 means 1, then 30 secs is 3600x = 1*30 that is to move forward sum up to the current progress 120).

¿ Makes sense @CookPete ? If that's the case can I create a branch and give a try to add that button to your example?

**Comment by josoroma** [comment]
Hi @CookPete !

I did it using:

```
  const handleSeekTo = (action, seconds) => {
    setSeeking(true);

    let seekTo = 0;

    if (action === 'replay') {
      seekTo = Math.ceil(played - seconds);
    }

    if (action === 'forward') {
      seekTo = Math.floor(played + seconds);
    }

    setPlayed(seekTo);
    inputRange.current.seekTo(seekTo, 'seconds');

    setSeeking(false);
  }
```

Thanks a bunch man!
