### ISSUE TITLE
Wrong twitch channel regex (allows only lower letters)

### ISSUE THREAD

**Issue by kamparR** [CookPete/react-player#860]
Hi,
in src/patterns.js there is:
`export const MATCH_URL_TWITCH_CHANNEL = /(?:www\.|go\.)?twitch\.tv\/([a-z0-9_]+)($|\?)/`

and as you can see in regex there is only support for lower letter a-z and not also for upper A-Z
It can be tested using demo site, eg. using first url twitch.tv/myth and then twitch.tv/Myth. Only first one will work.

**Comment by CookPete** [comment]
Fixed in `v2.0.1`
