### ISSUE TITLE
ReactPlayer is used to get multiple refs at the same time

### ISSUE THREAD

**Issue by just-myself** [CookPete/react-player#862]
In the rotatable component, I iterate over multiple ReactPalyer components, and when I switch to rotatable, I want to pause the currently playing video, so I use ref
But only the last one is bound to the ref

**Comment by just-myself** [comment]
You can use dynamic ref, where the same ref is used so that only the last one can be obtained

**Comment by kevinkashou** [comment]
Do you have an example of how you achieved this?
