### ISSUE TITLE
Build Error - gatsby

### ISSUE THREAD

**Issue by kannanseeni** [CookPete/react-player#865]
I am using gatsby. Running smoothly in development. While build it shows error

 ERROR #95313

Building static HTML failed for path "/"

See our docs page for more info on this error: https://gatsby.dev/debug-html

  Error: Minified React error #294; visit https://reactjs.org/docs/error-decoder.html?invariant=294 for the full message   or use the non-minified dev environment for full errors and additional helpful warnings.

  - react-dom-server.node.production.min.js:46 a.b.render
    [audio]/[react-dom]/cjs/react-dom-server.node.production.min.js:46:17

  - react-dom-server.node.production.min.js:44 a.b.read
    [audio]/[react-dom]/cjs/react-dom-server.node.production.min.js:44:18

  - react-dom-server.node.production.min.js:54 renderToString
    [audio]/[react-dom]/cjs/react-dom-server.node.production.min.js:54:364

  - render-page.js:618 Module../.cache/static-entry.js.__webpack_exports__.default
    D:/gatsby/audio/public/render-page.js:618:28

  - render-html.js:28 _bluebird.default
    [audio]/[gatsby]/dist/utils/worker/render-html.js:28:36

  - debuggability.js:384 Promise._execute
    [audio]/[bluebird]/js/release/debuggability.js:384:9

  - promise.js:518 Promise._resolveFromExecutor
    [audio]/[bluebird]/js/release/promise.js:518:18

  - promise.js:103 new Promise
    [audio]/[bluebird]/js/release/promise.js:103:10

  - render-html.js:24 _bluebird.default.map.path
    [audio]/[gatsby]/dist/utils/worker/render-html.js:24:47

  - util.js:16 tryCatcher
    [audio]/[bluebird]/js/release/util.js:16:23

  - map.js:68 MappingPromiseArray._promiseFulfilled
    [audio]/[bluebird]/js/release/map.js:68:38

  - promise_array.js:115 MappingPromiseArray.PromiseArray._iterate
    [audio]/[bluebird]/js/release/promise_array.js:115:31

  - promise_array.js:79 MappingPromiseArray.init
    [audio]/[bluebird]/js/release/promise_array.js:79:10

  - map.js:37 MappingPromiseArray._asyncInit
    [audio]/[bluebird]/js/release/map.js:37:10

  - async.js:97 _drainQueueStep
    [audio]/[bluebird]/js/release/async.js:97:12

  - async.js:86 _drainQueue
    [audio]/[bluebird]/js/release/async.js:86:9

**Comment by charkcl** [comment]
Same for me
Gatsby version 2.19.7

**Comment by dbismut** [comment]
It is. See here: https://github.com/CookPete/react-player/issues/738

**Comment by CookPete** [comment]
Fixed in `v2.0.1`
