### ISSUE TITLE
Safari does not load video/thumbnail as expected

### ISSUE THREAD

**Issue by tpkahlon** [CookPete/react-player#870]
#### Current Behavior
While testing the page on iPhone, Safari, video does not load.

#### Expected Behavior
Unlike Firefox, Safari fails to render the videos.

#### Steps to Reproduce
1. WEBP format files does not render in Safari.
2. On clicking play button, player fails to load the video.

#### Environment
- URL in concern: https://tiktoks.netlify.app
- Browser: Safari
- Operating system: MacOS

#### Other Information
Works fine in Firefox, Chrome.

**Comment by CookPete** [comment]
I'm getting a `403 Forbidden` from https://tiktoks.netlify.app on all browsers at the mo..

Regardless, `webm` on Safari is only partially supported: https://caniuse.com/#feat=webm
