### ISSUE TITLE
Adding rounded corners 

### ISSUE THREAD

**Issue by emieldc** [CookPete/react-player#872]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.
I tried to make the video player a little rounded. 

#### Current Behavior
.player-wrapper {
  position: relative;
  padding-top: 56.25%; /* Player ratio: 100 / (1280 / 720) */
}

.react-player {
  position: absolute;
  top: 0;
  left: 0;
  border-radius: 0.25rem !important;
}

#### Expected Behavior
Nothing changed..

#### Steps to Reproduce

1.
1.
1.

#### Environment
- URL attempting to play: 
- Browser: 
- Operating system: 
- jsFiddle example: https://jsfiddle.net/sv5x3ug1

**Comment by jlarmstrongiv** [comment]
@emieldc more of css than react-player related, try using `overflow: hidden;`
```
.react-player {
  position: absolute;
  top: 0;
  left: 0;
  border-radius: 0.25rem;
  overflow: hidden;
}
```
jsFiddle example: https://jsfiddle.net/t53zqkoj/

**Comment by sedhha** [comment]
The method you suggested works, but I notice a difference the bordering doesn't happen evenly:
![image](https://user-images.githubusercontent.com/36355685/131199786-3703da8c-b892-4374-b32e-96fb85b56f7b.png)
whereas intended is:
![image](https://user-images.githubusercontent.com/36355685/131199840-88b78649-bd0f-499a-bad4-c8277fa71144.png)
Not sure what goes wrong while styling the way you told.

**Comment by ntq2503** [comment]
@sedhha I was running into the same issue and figured out a work around: by adding a border radius to the <div> wrapper. Hope this helps!

Example: https://jsfiddle.net/ro7cb63e/16/

**Comment by sedhha** [comment]
@ntq2503 thanks a lot this definitely helps

**Comment by donivanjames** [comment]
This problem plagued me for a while. If you add a border to the div wrapper of @ntq2503's fiddle code you'll be able to clearly see why the corners aren't rounding
![image](https://github.com/cookpete/react-player/assets/76602007/a9acf656-9b07-4e35-8168-ef683c766f19)
