### ISSUE TITLE
Typescript typing the reference to the ReactPlayer

### ISSUE THREAD

**Issue by KieranO547** [CookPete/react-player#873]
#### Current Behavior
I'm trying to add a reference to the player to get access to the seekTo instance method but I can't seem to get the typescript type to work - I'm kinda new to typescript and probably doing this wrong so any pointers would be helpful!

#### Expected Behavior
Have access to the instance methods of the player

#### Steps to Reproduce
I made a small codeSandbox - basically trying to mimic the demo source for adding a ref to utilise the seekTo method onMouseUp on a range slider

https://codesandbox.io/s/react-typescript-lqgvr?file=/src/index.tsx

**Comment by harleylang** [comment]
Solution for reference (this helped me too!): https://stackoverflow.com/questions/61520187/typescript-typing-a-reference-for-third-party-custom-components-react-player
