### ISSUE TITLE
On reloading my page ReactPlayer doesn;t work.

### ISSUE THREAD

**Issue by iamjamielobo** [CookPete/react-player#88]
On reloading my page ReactPlayer doesn;t work. It gives the following error.

**YT.Player is not a constructor**

**Comment by CookPete** [comment]
@iamjamielobo What OS and browser are you using? Do you have more steps to reproduce this? Or an example repo?

**Comment by iamjamielobo** [comment]
It;s happening on all browsers.

It happens rarely when you reload the page.

I've implemented it here.

https://in.bookmyshow.com/mumbai/videos/trailers/dunkirk/ET00044852

**Comment by CookPete** [comment]
Ok I think I know what's going on. If you have several different things loading the youtube iframe API at once, the global `YT` object can sometimes be `{loading: 1, loaded: 0}` with no `Player` yet. When this happens, the `getSDK` promise is resolved with this object [here](https://github.com/CookPete/react-player/blob/master/src/players/YouTube.js#L37-L39) and the whole thing breaks. Should be a simple fix just to ensure that `loaded` is `1` as well before resolving the array.
