### ISSUE TITLE
"onDuration" not triggered on successive YouTube URLs

### ISSUE THREAD

**Issue by dlime** [CookPete/react-player#880]
#### Current Behavior
If ReactPlayer has already loaded a Youtube URL, when loading the next Youtube URL no `onDuration` is called after `onReady`

#### Expected Behavior
`onDuration` is triggered right after `onReady` providing the length of the new YouTube URL

#### Steps to Reproduce
* Go to [demo website](https://cookpete.com/react-player/)
* **Click stop**
* Click on `YouTube Test A`
* Check duration: `6:10`
* Click on `YouTube Test B`
* **Check duration: still `6:10`**
* Click play: duration of `Test B` is updated to `8:59`

Repeat these steps with `SoundCloud Test A / Test B` for replicating the expected behavior.

#### Environment
- Browser: Chrome
- Operating system:  Linux

**Comment by dlime** [comment]
Further debug, I've modified `onReady` callback to print the duration instead of using `onDuration` in the following way:
```
onReady={(reactPlayer) => console.log('onReady', reactPlayer.getDuration())}
```
This will log "0" duration on successive YouTube URLs

**Comment by dlime** [comment]
Can replicate the bug also with v1.15.3

**Comment by CookPete** [comment]
This is a quirk of the Youtube API that has been around for [over 10 years by the looks of it](https://stackoverflow.com/questions/2086260/youtube-player-api-how-to-get-duration-of-a-loaded-cued-video-without-playing-i). The duration is available for the first video that loads into the player, but any further videos loaded with `cueVideoById` will not have the duration available until _after the video has started playing._

One workaround (although not a particularly nice one) would be to add a `key`:

```jsx
<ReactPlayer key={url} url={url} ... />
```

which will force ReactPlayer to load a fresh youtube player every time the URL changes.

**Comment by dlime** [comment]
Thx for the explanation! 
I'll just set a default video length for YouTube URLs until they are played. Ugly but that's ok 👍
