### ISSUE TITLE
Does this library support multiple audio

### ISSUE THREAD

**Issue by narawit0** [CookPete/react-player#882]
When i open video with the source file that ended up with .m3u8 format, there are two audios file in there but there is no options to select audio in the player.

**Comment by CookPete** [comment]
Use `getInternalPlayer('hls')` to get the instance of `hls.js`. From there you can access `audioTracks` and set `audioTrack`.

Untested example below. No idea if this will work but hopefully it starts you off:

```jsx
class Player extends React.Component {
  ref = player => {
    this.player = player
  }
  handleReady = () => {
    const hls = this.player.getInternalPlayer('hls')
    console.log(hls.audioTracks)
    console.log(hls.audioTrack)
    hls.audioTrack = hls.audioTracks[1]
  }
  render () {
    return (
      <div>
        <ReactPlayer
          ref={this.ref}
          url='https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8'
          playing
          controls
          onReady={this.handleReady}
        />
      </div>
    )
  }
}
```

**Comment by narawit0** [comment]
Is there a way to show UI to change audio on the client side.

**Comment by CookPete** [comment]
I'm afraid you'd have to build that UI yourself. ReactPlayer is just a proxy for the various player APIs and uses the built in controls for each player.
