### ISSUE TITLE
Can't play Vimeo videos with Safari (Version 13.1) when controls = true

### ISSUE THREAD

**Issue by PRonnenberg** [CookPete/react-player#883]
Thanks for your fantastic library and the effort you've put in!

#### Current Behavior
Can't play Vimeo videos with Safari (Version 13.1) when controls = true

#### Expected Behavior
Play the Vimeo video with controls = true

#### Steps to Reproduce
I'm having the same behaviour in my code and on your demo page:
https://cookpete.com/react-player/

#### Environment
- Browser: Safari (Version 13.1)
- Operating system: macOS 10.15.4

#### Other Information
![react-player](https://user-images.githubusercontent.com/6499892/81671600-708c7c80-9449-11ea-9a55-913c574d373d.gif)

**Comment by CookPete** [comment]
I can't reproduce this on Safari 13.0.5 macOS 10.15.3:

![image](https://user-images.githubusercontent.com/1926029/81861490-395cbf00-9560-11ea-97f9-c525c6cc7de7.png)
