### ISSUE TITLE
how to trigger custom function when user click fullscreen icon?

### ISSUE THREAD

**Issue by shivarasan** [CookPete/react-player#885]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Steps to Reproduce

1.
1.
1.

#### Environment
- URL attempting to play: 
- Browser: 
- Operating system: 
- jsFiddle example: https://jsfiddle.net/sv5x3ug1

**Comment by CookPete** [comment]
If the [API that is being used](https://github.com/CookPete/react-player#supported-media) has an `onFullscreen` event to listen to, then yes. Otherwise, no. What type of URL are you trying to play?
