### ISSUE TITLE
is version 2 bigger bundle? 

### ISSUE THREAD

**Issue by shaulgo** [CookPete/react-player#886]
Hey, I thought version 2 came to improve bundle size by using the lazy loading of players. But bundlephobia seems to disagree. Is there more too it?
thanks :)

https://bundlephobia.com/result?p=react-player@2.0.1
![image](https://user-images.githubusercontent.com/2996028/81845203-eb908880-9558-11ea-8c70-8b78bc5852f1.png)

**Comment by CookPete** [comment]
My guess is that BundlePhobia doesn't factor in lazy loading. It probably just sees the `require(…)` statements in the [compiled players index file](https://unpkg.com/browse/react-player@2.0.1/lib/players/index.js#L66) and pulls in all the files for all players.

**Comment by ovbm** [comment]
![Screenshot 2020-05-19 at 09 24 07](https://user-images.githubusercontent.com/20746301/82297134-80a8dc80-99b2-11ea-83b7-2882dcd9f927.jpg)
That's how webpack works. I wanted to import only the FilePlayer, but it seems that option was removed in version 2. I will try to install v1 to see if I can get my bundle size down. 200kb is too much.

**Comment by CookPete** [comment]
Ok so it seems like I haven't quite implemented lazy players correctly. Babel compiles these lines:

https://github.com/CookPete/react-player/blob/32bb251a60f1a6449bd20e6dcf4c7dbfaeab02b7/src/players/index.js#L46-L50

into this:

```js
{
  key: 'youtube',
  canPlay: function canPlay(url) {
    return _patterns.MATCH_URL_YOUTUBE.test(url);
  },
  lazyPlayer: (0, _react.lazy)(function () {
    return Promise.resolve().then(function () {
      return _interopRequireWildcard(require('./YouTube'));
    });
  })
}
```

I'm guessing for lazy loading to work it need to remain as `import()`, eg:

```js
{
  key: 'youtube',
  canPlay: function canPlay(url) {
    return _patterns.MATCH_URL_YOUTUBE.test(url);
  },
  lazyPlayer: (0, _react.lazy)(function () {
    return import('./YouTube');
  })
}
```

The problem is that every player is then added as a chunk to the build, as there's no way of knowing at build time what players will be used. Maybe that's ok, but maybe I need to consider bringing back individual player imports…

**Comment by shaulgo** [comment]
As far as I know, multiple chunks is the way it's supposed to be.

**Comment by CookPete** [comment]
@shaulgo Try building with `react-player@2.0.2-beta.0` and let me know if that helps. It's built with `@babel/plugin-proposal-dynamic-import` excluded from the babel env preset, so the built files now have `import()` for lazy loading.

**Comment by shaulgo** [comment]
amazing :) works. Checked it on our app and it split it into chunks and worked out of the box. It also looks very very nice in bundlephobia. 
![image](https://user-images.githubusercontent.com/2996028/82560975-26a74300-9b7b-11ea-86ef-aaea0eea7629.png)

**Comment by CookPete** [comment]
Good to know! I'll work on getting this out. @shaulgo @ovbm Can you forsee any issues leaving `import()` statements in the compiled code?

Relevant comment: https://github.com/babel/babel/issues/10273#issuecomment-517838332

**Comment by CookPete** [comment]
Note that from `v2.2.0`, the lazy loading version of ReactPlayer has moved to `react-player/lazy`. See [MIGRATING.md](https://github.com/CookPete/react-player/blob/master/MIGRATING.md) for more info.

I'm not considering it a breaking change as things won't actually break – the only impact will be a slightly bigger bundle size until you start importing from `react-player/lazy`.

I've added clarification to the readme to only use it if your build pipeline supports dynamic `import()` statements.

It's also worth noting that the BundlePhobia size will now go back up to ~17kb gzipped as the default import still includes logic for all players.

**Comment by jayeshbharadva** [comment]
@cookpete  @shaulgo  I was reading the issue and new to this computer world.
So i created my project with  
import ReactPlayer from 'react-player/lazy'
and now it loads 3 chunks 
bytes 0-6533162/6533163
bytes 6520832-6533162/6533163
bytes 65536-6533162/6533163
can anyone explain if this will be it's behavior or there is a solution?
