### ISSUE TITLE
Electron app: react-player does not get injected in the DOM.

### ISSUE THREAD

**Issue by jeanmichelcote** [CookPete/react-player#89]
I am just starting with [electron-react-boilerplate](https://github.com/chentsulin/electron-react-boilerplate) and naively added the player straight on the home page. But it seems like it doesn't get rendered in the DOM. A `div` did get injected though, with styles attributes:
`<div style="width: 640px; height: 360px;"></div>`  
but no player inside the div.

Here is the `Home.js` file:

```
import React, { Component } from 'react'
import { Link } from 'react-router'
import styles from './Home.css'
import Player from 'react-player'


export default class Home extends Component {
  render() {
    return (
      <div>
        <div className={styles.container}>
          <h2>Home</h2>
          <Link to="/counter">to Counter</Link><br />
          <Link to="/project">to Projects</Link>
          <Player ulr="https://www.youtube.com/watch?v=ysz5S6PUM-U"
                  className={styles.video} 
                  playing 
                  controls
          />
        </div>
      </div>
    )
  }
}
```

Am I doing something wrong?
Thanks for the good work!

**Comment by CookPete** [comment]
You have a typo. `<Player ulr="...` should be `<Player url="...`

I'm hoping that fixes it?

**Comment by jeanmichelcote** [comment]
Hmmm. Not sure if I should say "thanks" or "sorry". Probably both.

So the player surely shows up now. 

But the video is not playing. Not even a freeze frame, just a transparent background. The clip is hosted on vimeo, I am the owner, it is on my account and is fully public.

Again, this is the component:
```
import React, { Component } from 'react'
import { Link } from 'react-router'
import styles from './Home.css'
import Player from 'react-player'


export default class Home extends Component {
  render() {
    return (
      <div>
        <div className={styles.container}>
          <h2>Home</h2>
          <Player url="https://vimeo.com/jeanmichelcote/handball"
                  playing 
                  controls
          />
        </div>
      </div>
    )
  }
}
```

And this is the rendered page:
![electronapp](https://cloud.githubusercontent.com/assets/1410655/17339520/52c0c108-58ba-11e6-897d-aa40f4d559a7.jpg)

Tell me now which silly mistake I've juste made...

**Comment by jeanmichelcote** [comment]
Ok, seems like I have to use the original url, the one with the random id number at the end (https://vimeo.com/141577529) that you can copy/paste straight from the browser's address bar rather than the one vimeo gives out when you click on the share button within the player.

Sorry about the fussing.
It's working now.

**Comment by CookPete** [comment]
Ah yes the older Vimeo player API that `ReactPlayer` uses only works with the video ID URL, not the full URL. Luckily it looks like Vimeo have just release a [new API](https://github.com/vimeo/player.js) that handles full URLs so I've opened a new issue to migrate to that.
