### ISSUE TITLE
What could be wrong for going full screen on Firefox and Safari?

### ISSUE THREAD

**Issue by JenniferFuBook** [CookPete/react-player#890]
#### Current Behavior
I can run your demo properly in Firefox and Safari.

#### Expected Behavior
When I click going full screen on Firefox and Safari from my React code, it becomes a blank full screen and comes back normal size.
The same code works on Chrome.

Would you give me some suggestion what could be wrong?

**Comment by CookPete** [comment]
It’s very hard to know what’s happening without an example of your code. Are you using screenfull like the demo app? It could just be a problem with your implementation. Either way, it is a separate issue to ReactPlayer itself.

**Comment by JenniferFuBook** [comment]
Thanks, CookPete!
I was not using screenfull. I am using the video controls to go fullscreen.
I downloaded screenfull, and it still doesn't work.
My usage is:
    <ReactPlayer
      url="http://techslides.com/demos/sample-videos/small.mp4"
      width='100%'
      height='100%'
      controls={true}
    />

**Comment by CookPete** [comment]
I can't see any problems on my machine (macOS 10.15.3). Full screen works correctly for `http://techslides.com/demos/sample-videos/small.mp4` with controls on both Safari 13.0.5 and Firefox 75.0.

**Comment by JenniferFuBook** [comment]
Thanks, Pete!
Both of the following statements in my environment do not work on Safari and Firefox:
screenfull.request(myElement.current)
myElement.current.requestFullscreen();
