### ISSUE TITLE
how to hide Youtube logo in case of controls sets 1?

### ISSUE THREAD

**Issue by gurusoft13** [CookPete/react-player#893]
Basically, I want to hide youtube logo in case of youtube controls are hidden.

>  playerVars: {
>       controls: 1,
>       modestbranding: 1,
> }
> 
Whenever I used the **youtube config** as above, I can get the result with no **youtube logo** but controls are shown. 
But if I change the controls to 0 like below, I can hide the controls, but the youtube logo is shown.

>  playerVars: {
>       controls: 0,
>       modestbranding: 1,
> }
> 

Screenshot is attached here.
![image](https://user-images.githubusercontent.com/49583931/82275745-cc905d00-9983-11ea-8071-688bb319a6d9.png)

Full example code is here.
> <ReactPlayer
>         url="https://www.youtube.com/watch?v=ysz5S6PUM-U?controls=1"
>         playing
>         config={{
>           youtube: {
>             playerVars: {
>               controls: 0,
>               modestbranding: 1,
>             },
>           },
>         }}
> />

How can I remove youtube logo while controls are hidden?

**Comment by CookPete** [comment]
I don't think it's possible to remove the logo.

>This parameter lets you use a YouTube player that does not show a YouTube logo. Set the parameter value to 1 to prevent the YouTube logo from displaying in the control bar. __Note that a small YouTube text label will still display in the upper-right corner of a paused video when the user's mouse pointer hovers over the player.__

https://developers.google.com/youtube/player_parameters#modestbranding
