### ISSUE TITLE
How to place a video 9:16 in frame 16: 9

### ISSUE THREAD

**Issue by VanTy207** [CookPete/react-player#895]
Hi,
I have problems displaying the video 9:16 in frame 16:9.
My video is taken from the facebook api with an aspect ratio of 9:16 and I have a 16: 9 display frame, but when I play the video it falls out of my 16: 9 frame, and I don't control it be video.

Environment:
- Browser: Google Chrome
- Framework dev: ReactJs (version 16.4.1)

**Comment by CookPete** [comment]
What `width` and `height` are you passing in to the player? These must be set otherwise they default to `640px` by `360px`.

Have you looked at the [responsive player](https://github.com/CookPete/react-player#responsive-player) section of the readme?

Here's a [jsFiddle example](https://jsfiddle.net/fn3ousyw/) of a portrait Facebook video.

**Comment by VanTy207** [comment]
Dear Pete Cook,

Thank you for the issues reply.
I have the control bar problem again.
The video control bar of the player on mobile is different from the control
bar when displayed on the desktop.
I want the control bar on the tablet and mobile the same as on the desktop.
Could you please help me with this issue?

Have a great day.
Sincerely.

Vào CN, 24 thg 5, 2020 vào lúc 03:10 Pete Cook <notifications@github.com>
đã viết:

**Comment by CookPete** [comment]
>I want the control bar on the tablet and mobile the same as on the desktop.
>Could you please help me with this issue?

ReactPlayer just uses the Facebook player API to play videos. There is no way for us to control how they display controls across mobile and desktop.

As far as I know there is no way to show custom controls on fullscreen iOS videos anyway. The iOS native controls will always be used.

**Comment by VanTy207** [comment]
Dear Pete Cook,

Thank you for your reply.

Have a great day.
Sincerely.

Vào Th 3, 26 thg 5, 2020 vào lúc 16:59 Pete Cook <notifications@github.com>
đã viết:
