### ISSUE TITLE
Issue with webpack and multiple chunks

### ISSUE THREAD

**Issue by Margoot** [CookPete/react-player#899]
Since recently, I have in my dist 11 files with respectively "Preview", "DailyMotion",  "Facebook", "Youtube" and so on named by [Number].js. Even when I have excluded the node_modules from my webpack config for babel-loader. 
I would like to exclude those files to have exclusively the source files in my dist.

Here is my webpack config and a screenshot of my dist: 
```
const path = require("path");
const HtmlWebpackPlugin = require("html-webpack-plugin");

module.exports = {
  mode: "development",
  entry: {
    client: "./src/client.js",
    bundle: "./src/bundle.js",
  },
  output: {
    path: path.resolve(__dirname, "assets"),
    filename: "[name].js",
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        include: path.join(__dirname, 'src'),
        exclude: /node_modules/,
        loader: "babel-loader",
      },
      {
        test: /\.scss$/,
        loader: "style-loader!css-loader!sass-loader",
        exclude: /node_modules/,
      },
      {
        test: /\.(png|jpg|woff|woff2|woff|ttf|eot|otf|svg|ico)$/i,
        use: [
          {
            loader: "file-loader",
            options: {
              outputPath: "/files",
              limit: 8195,
              publicPath: "assets/files",
            },
          },
        ],
      },
    ],
  },
  plugins: [
    new HtmlWebpackPlugin({
      favicon: "./src/assets/images/favicon.ico",
    }),
  ],
};
```

And my dist files look like: 

<img width="116" alt="Capture d’écran 2020-05-26 à 21 29 50" src="https://user-images.githubusercontent.com/17765790/82942379-29999d80-9f98-11ea-82c3-4e6bdde8fdec.png">

Thanks for your precious help. I've spent hours looking for a solution but .. nothing works!

**Comment by CookPete** [comment]
This is what I would expect in version `2.1.0`, although the lack of proper chunk names is not ideal. The different players are now [dynamically imported](https://webpack.js.org/guides/code-splitting/#dynamic-imports) when they are needed, based on the `url` passed in. This results in a chunk for each player. 

I imagine you can get more control of how things are chunked with [`SplitChunksPlugin`](https://webpack.js.org/plugins/split-chunks-plugin/) but I need to look into it properly.

I will add some comments to give chunks names (eg `reactPlayerYouTube`, `reactPlayerFacebook`, etc) for future clarity.
