### ISSUE TITLE
Update SoundCloud SDK usage

### ISSUE THREAD

**Issue by CookPete** [CookPete/react-player#9]
Looks like there's a new version of the SDK now, and it's on NPM!

https://developers.soundcloud.com/docs/api/sdks#basic
https://www.npmjs.com/package/soundcloud

**Comment by oyeanuj** [comment]
Will this include support for the SoundCloud iframe embed? It would be great to have a config parameter which supports the embed to keep their brand styling intact!

**Comment by CookPete** [comment]
I'm having second thoughts about using the npm package. It's good that they have released it, but doesn't make sense to include in the bundle if apps may not even be playing Soundcloud songs. I'll keep this issue open as a reminder to update to version 3 of the SDK at some point.

@oyeanuj, similar to my point in https://github.com/CookPete/react-player/issues/11, `ReactPlayer` is supposed to be a non-opinionated, lightweight, stateless wrapper for video/audio SDKs and not much more. The idea is for developers to provide whatever external controls they need and just feed props into the player.

**Comment by CookPete** [comment]
I just had a play with the new SDK and it seems very [buggy](http://stackoverflow.com/questions/33396266/soundcloud-javascript-api-v-3-sc-stream-errors), as well as not supporting things like track duration and load progress information. I'll close this for now until the SDK improves, as there is nothing forcing us to upgrade yet.
