### ISSUE TITLE
Migrate to new Vimeo API

### ISSUE THREAD

**Issue by CookPete** [CookPete/react-player#90]
There is a new [Vimeo Player API](https://github.com/vimeo/player.js) which looks much better than the current API, so `ReactPlayer` should probably start using that.

**Comment by manpenaloza** [comment]
I do some client stuff with that new Vimeo API at the moment. Is this something still pending here? If yes, I can try making some progress here.

**Comment by CookPete** [comment]
I already have a working branch so don't worry too much. I just haven't got around to tidying it up and merging yet. The only remaining thing is an [issue](https://github.com/vimeo/player.js/issues/38) with player dimensions, but I think I have a workaround.

**Comment by manpenaloza** [comment]
ok, in case you need support on this, just ping me.

**Comment by nikolas** [comment]
@CookPete can you make your new Vimeo API branch public? I can't see it listed under branches. I'd like to start using with the hope that it will address this Vimeo issue I ran into today: https://github.com/CookPete/react-player/issues/140

**Comment by pwbrown** [comment]
Thanks @CookPete for the public vimeo branch

**Comment by CookPete** [comment]
Fixed by https://github.com/CookPete/react-player/commit/f262c1e87be887d06c01217bc86a6f55dc90085e
