### ISSUE TITLE
window undefined when importing while server-side rendering

### ISSUE THREAD

**Issue by danikas2k2** [CookPete/react-player#900]
#### Current Behavior

On react server-side rendering importing 'react-player' fails with 'window undefined' message.

#### Expected Behavior

All 'window' access should be safely escaped by typeof window !== 'undefined' for server-side rendering.

#### Steps to Reproduce

import ReactPlayer from 'react-player'; // window undefined

#### Environment
- React 16.11.0
- ReactPlayer 2.1.0

**Comment by CookPete** [comment]
There is already a check for `window` here:

https://github.com/CookPete/react-player/blob/c4c597f8e4c16ca3de2314fe9de45e363e3fd71b/src/ReactPlayer.js#L13

This prevents any players from rendering on the server side.

What props are you passing in, and how are you rendering on the server? I can run the following (with various different URL types) without errors on node:

```jsx
import React from 'react'
import ReactPlayer from './src/ReactPlayer'
import ReactDOMServer from 'react-dom/server'

const output = ReactDOMServer.renderToString(
  <div>
    <ReactPlayer url='https://www.youtube.com/watch?v=oUFJJNQGwhk' />
  </div>
)

console.log(output)
```
