### ISSUE TITLE
Demo offline

### ISSUE THREAD

**Issue by giovannipds** [CookPete/react-player#901]
#### Current Behavior
The demo at readme is currently offline.

#### Expected Behavior
An online demo page.

#### Steps to Reproduce
1. Just click at the url below.

#### Environment
- URL attempting to play: https://cookpete.com/react-player
- Browser: Chrome 83.0.4103.61 (official version) 64 bits
- Operating system: Windows 10

#### Other Information
![image](https://user-images.githubusercontent.com/1820017/83169719-d20b4700-a0e9-11ea-9538-eb49695d77bc.png)
![image](https://user-images.githubusercontent.com/1820017/83169755-df283600-a0e9-11ea-9241-e6ab1b91a159.png)
https://downforeveryoneorjustme.com/cookpete.com

**Comment by RusseII** [comment]
Same issue

**Comment by carbonology** [comment]
Yep! 403 error

**Comment by CookPete** [comment]
There was an issue with my hosting provider. Should be sorted now. Apologies all!
