### ISSUE TITLE
Issues with version 2.1 trying to run simple example 

### ISSUE THREAD

**Issue by RusseII** [CookPete/react-player#902]
https://codesandbox.io/s/intelligent-darwin-rfw03?file=/src/App.js

![image](https://user-images.githubusercontent.com/15036618/83203882-101b6180-a110-11ea-9c02-989b07fe6133.png)

**Comment by RusseII** [comment]
Works when I downgrade the version to 2.01

**Comment by CookPete** [comment]
`2.1.0` uses `import()` statements for lazy loading players. Seems like codesandbox doesn't handle them very well.

Relevant issues:
- https://github.com/codesandbox/codesandbox-client/issues/1774
- https://github.com/codesandbox/codesandbox-client/issues/1887

Not an ideal solution but I guess it would work if you used the built file in `dist` instead? eg:

https://unpkg.com/react-player@2.1.0/dist/ReactPlayer.js
