### ISSUE TITLE
add iOS add close button

### ISSUE THREAD

**Issue by nickaws** [CookPete/react-player#903]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior
I don't have a close button

#### Expected Behavior
I would like one as in this depicted image https://dev.to/kvharish/play-videos-inline-in-html5-video-player-on-ios-2a18
#### Steps to Reproduce

1. Default settings, iOS

#### Environment
- URL attempting to play: 
- Browser: iOS
- Operating system:  13`

#### Other Information
any way I can add one without overcomplicating custom controls?

**Comment by CookPete** [comment]
As far as I know, the browser cannot control the buttons available when playing videos in iOS. I don't think there's anything that can be done here.
