### ISSUE TITLE
Update twitch embed code to handle new iframe ancestry restrictions

### ISSUE THREAD

**Issue by hashcutdev** [CookPete/react-player#904]
The twitch player as started right now runs fine, but on June 10, there will be additional restrictions on iframe embedding as detailed here:
https://discuss.dev.twitch.tv/t/twitch-embedded-player-updates-in-2020/23956

Currently, there's no way to set additional parents besides the current server that the code is running on.

#### Current Behavior
Examining the <iframe> code that react-player uses, the 'parent' parameter is set once in the iframe src URL and is automatically set to the current server hostname. However, there is no way to add additional parents, if you expect your code to be embedded in multiple sites.

I tried setting a custom config prop:
config: {
                twitch: {
                    parent: ['XXX', 'YYY', 'ZZZ'],
                },
            }
but that doesn't change how the iframe src url is generated.

Furthermore, even on the original server, with no further embedding, I'm still getting iframe ancestry errors in the browser like this:

[Report Only] Refused to frame 'https://player.twitch.tv/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors https://server.hashcut.com".

On June 10th, these [Report Only] errors will become actual errors and we won't be able to embed twitch videos any longer without setting the parent parameters properly

#### Expected Behavior
Is there a way to override the default parent parameter with the value from the config props? Note the parent array would need to be translated to &parent=XXX&parent=YYY&parent=ZZZ
Hopefully this will resolve the iframe errors I'm seeing in the browser console.

**Comment by CookPete** [comment]
You were close with `config.twitch.parent`. It needs to be inside the `options` object, as per the [readme](https://github.com/CookPete/react-player#config-prop).

```jsx
<ReactPlayer
  url='https://www.twitch.tv/videos/106400740'
  config={{
    options: {
      parent: ['fiddle.jshell.net', 'jsfiddle.net']
    }
  }}
/>
```

https://jsfiddle.net/m21w8dna/

Note that as of `2.0.0` you don't need to nest the config inside `config.twitch`, although you still can if you want.
