### ISSUE TITLE
Using an array for URL breaks the code

### ISSUE THREAD

**Issue by lcukerd** [CookPete/react-player#906]
Declaring Urls as described [here](https://www.npmjs.com/package/react-player#multiple-sources-and-tracks ) will break the code and cause Error
#### Current Behavior
Error occurs. You get
```
Uncaught TypeError: url.match is not a function
    at YouTube.load (YouTube.js:170)
    at Object.onMount (Player.js:83)
```

#### Expected Behavior
Player should load both URL and give option to play either (similar to when loading playlist).

#### Steps to Reproduce
Create player like
`<ReactPlayer playing url={['https://www.youtube.com/watch?v=d46Azg3Pm4c', 'https://www.youtube.com/watch?v=eVsXVzSse8I']} />`

#### Environment
- Browser: Chrome
- Operating system: MacOs 10.15.5

**Comment by CookPete** [comment]
Passing an array to `url` only applies to file paths, when you want to provide multiple different types _for the same video_ (eg `video/webm` and `video/ogg`) to improve cross-browser support.

You can use `playerVars` to play several Youtube videos as a playlist, although this is not documented and not very obvious:

```jsx
<ReactPlayer
  url='https://www.youtube.com/watch?v=oUFJJNQGwhk' // First video in playlist
  playing
  controls
  config={{
    playerVars: {              
      listType: 'playlist',
      playlist: 'jNgP6d9HraI,_8UJBrnYBW4' // Second and third videos, comma separated
    }
  }}
/>
```

I suppose it would be nice if ReactPlayer did this automatically for arrays of youtube URLs…
