### ISSUE TITLE
Preview image height

### ISSUE THREAD

**Issue by kingstar1227** [CookPete/react-player#908]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior

![image](https://user-images.githubusercontent.com/50105149/83566772-89d79480-a4ee-11ea-8f66-387046d315ee.png)
Preview image doesn't have full height. 
#### Steps to Reproduce

```
<ReactPlayer
     ref={player => { this.players[i] = player }}
     controls
     url={S3_BUCKET_VIDEO + v.name}
     width='100%'
     height='auto'
     playing
     light={S3_BUCKET_VIDEO_PREVIEW + v.poster}
     config={{ file: { attributes: {
          crossOrigin: 'anonymous'
     }}}}
 />
```

**Comment by CookPete** [comment]
You are using `height='auto'`. What do you expect to happen? What do you mean by "full height"?

**Comment by CookPete** [comment]
Is this what you're after?

https://github.com/CookPete/react-player#responsive-player

**Comment by kingstar1227** [comment]
No. It only works when it has a 16:9 aspect ratio.

I have several images that have a different aspect ratio not (16:9). I want to keep the aspect ratio of the images and want to show the whole images. as you can see in the screenshot, it only displays a center part of the image.

**Comment by CookPete** [comment]
You need to set the `height` prop accordingly, to ensure the player is the correct aspect ratio for your preview images.
