### ISSUE TITLE
Consecutive test cases fails with Error: Not supported

### ISSUE THREAD

**Issue by Tokimon** [CookPete/react-player#910]
#### Current Behavior
When executing several tests in the same file each consecutive test fails with the following error:

`Error: Uncaught [Error: Not supported]`

I am suspecting that the use of `Suspense` might have something to do with it since this line

https://github.com/CookPete/react-player/blob/2a9e09c7405a67ac767c6f8f03b0559e541046e0/src/ReactPlayer.js#L13

Will continue to use Suspence in a JsDom environment.

#### Expected Behavior
No error to be thrown

#### Steps to Reproduce
*React component*
```jsx
import React from 'react';
import ReactPlayer from 'react-player';

const VideoTest = ({ play }) => {
  return (
    <ReactPlayer
      url='./test-video.mp4'
      playing={!!play}
      className='react-player'
      width='100%'
      height='100%'
      style={{ lineHeight: 0 }}
    />
  );
};

VideoTest.displayName = 'VideoTest';

export default VideoTest;
```

*Test file*
```jsx
import React from 'react';
import { mount } from 'enzyme';

import VideoTest from './VideoTest';

describe('[molecule] VideoPlayerTest', () => {
  it('This test does not fail', () => {
    mount(<VideoTest file='http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4' />);
  });

  it('This test fails even if it should not', () => {
    mount(<VideoTest file='http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4' />);
  });
});
```

#### Environment
- Test Runner: Jest 
- Browser: JsDom
- Operating system: Windows

**Comment by CookPete** [comment]
This looks very similar to https://github.com/CookPete/react-player/issues/909. I recommend `shallow` rendering with Enzyme.

Or, if anyone has any ideas on how to fix this, I'm all ears.

**Comment by CookPete** [comment]
There also loads of info in the [various threads about `Enzyme` and using `mount` with `Suspense`](https://github.com/enzymejs/enzyme/search?q=suspense&type=Issues).

**Comment by Tokimon** [comment]
I will try to use shallow, but that means I have to update my already written tests. And I am unsure that I will be able to in all cases.
I will keep you posted.
