### ISSUE TITLE
ERROR in reactPlayerDailyMotion.js from Terser

### ISSUE THREAD

**Issue by IgnusG** [CookPete/react-player#912]
#### Current Behavior
Building with webpack results in error messages:
```
    ERROR in reactPlayerDailyMotion.js from Terser
    Unexpected token: punc (:) [reactPlayerDailyMotion.js:3,9]

    ERROR in reactPlayerFacebook.js from Terser
    Unexpected token: punc (:) [reactPlayerFacebook.js:3,9]

    ERROR in reactPlayerFilePlayer.js from Terser
    Unexpected token: punc (:) [reactPlayerFilePlayer.js:3,9]

    ERROR in reactPlayerMixcloud.js from Terser
    Unexpected token: punc (:) [reactPlayerMixcloud.js:3,9]

    ERROR in reactPlayerSoundCloud.js from Terser
    Unexpected token: punc (:) [reactPlayerSoundCloud.js:3,8]

    ERROR in reactPlayerStreamable.js from Terser
    Unexpected token: punc (:) [reactPlayerStreamable.js:3,9]

    ERROR in reactPlayerTwitch.js from Terser
    Unexpected token: punc (:) [reactPlayerTwitch.js:3,9]

    ERROR in reactPlayerVidyard.js from Terser
    Unexpected token: punc (:) [reactPlayerVidyard.js:3,9]

    ERROR in reactPlayerVimeo.js from Terser
    Unexpected token: punc (:) [reactPlayerVimeo.js:3,9]

    ERROR in reactPlayerWistia.js from Terser
    Unexpected token: punc (:) [reactPlayerWistia.js:3,9]

    ERROR in reactPlayerYouTube.js from Terser
    Unexpected token: punc (:) [reactPlayerYouTube.js:3,8]

    ERROR in 12.js from Terser
    Unexpected token: punc (:) [12.js:3,8]
```

#### Expected Behavior
Compile

#### Steps to Reproduce

1. I've installed the new 2.1.1 version (2.0.1 works)
2. Imported ReactPlayer the same way as in example (I don't use any advanced features and let ReactPlayer do all the heavy lifting

```tsx
import ReactPlayer from 'react-player';

export function VideoPlayer({
  url,
  volume,
  onPlayerStartsPlaying,
}) {

  return (
    <div class="fixed">
      <ReactPlayer
        width="100%"
        height="100%"
        url={url}
        playing
        volume={volume}
        onStart={onPlayerStartsPlaying}
      />
    </div>
  );
}
```

#### Environment
No bundle output so no browser or url passed in for testing
webpack: 4.42.1
react-player: 2.1.1

**Comment by CookPete** [comment]
Try setting `ecma: 8` in your terser options – https://github.com/webpack-contrib/terser-webpack-plugin/issues/114#issuecomment-521253337

**Comment by IgnusG** [comment]
I've configured the terser-webpack-plugin like this:
```js
  optimization: {
    minimizer: [
      new TerserPlugin({
        include: /\/node_modules\/react-player/,
        terserOptions: {
          ecma: 8
        }
      })
    ]
  },
```

This worked. Thank you for the tip @CookPete! 
Maybe we could include this in the docs for usage in webpack?

**Comment by IgnusG** [comment]
Realized my bundle size exploded and that the include I configured actually disables terser for everything. Removing it enables minification but setting the terser ecma option still fails with react-player.

**Comment by CookPete** [comment]
Updating the library to use `import()` statements seems to have caused more problems than it has solved. I'm tempted to ditch the lazy loading players and bring back single player imports once again.

**Comment by CookPete** [comment]
@IgnusG Does turning off code splitting fix things? Something like:

```js
  plugins: [
    new webpack.optimize.LimitChunkCountPlugin({
      maxChunks: 1
    })
  ]
```
in your webpack config. I understand it's not desirable but would be good to know if it helps.

**Comment by IgnusG** [comment]
> @IgnusG Does turning off code splitting fix things? Something like:
> 
> ```js
>   plugins: [
>     new webpack.optimize.LimitChunkCountPlugin({
>       maxChunks: 1
>     })
>   ]
> ```
> 
> in your webpack config. I understand it's not desirable but would be good to know if it helps.

Interesting. That does solve the issue. The output is properly minified and react-player is included correctly in the bundle.

**Comment by CookPete** [comment]
So it's something to do with Terser trying to parse the individual chunks from the dynamically imported players.

I'm trying to figure out what to do about this. I may have to bring back single player imports like `import YouTubePlayer from 'react-player/YouTube'`

**Comment by IgnusG** [comment]
For me the dynamic imports "worked" in version 2.0.1 but broke after updating to 2.1.0.
I think this https://github.com/CookPete/react-player/issues/886 is what's causing terser to trip up.

**Comment by CookPete** [comment]
Yeah, `2.1.0` tried to "fix" lazy loaded players by no longer transforming `import()` statements into `require()` statements (which rendered lazy loading useless). Unfortunately it breaks for any build pipeline that doesn't support `import()` statements or the chunks they produce (like yours, or [this one](https://github.com/CookPete/react-player/issues/907)).

I'm going to release `2.2.0` shortly that reverts the main `react-player` import to how things were in `2.0.1`, which should fix most problems for most users. Then, if your build system supports `import()` statements you can import from `react-player/lazy`.

**Comment by CookPete** [comment]
You should not have this issue in `2.2.0`. The lazy loading version with `import()` statements is now opt-in and imported using `react-player/lazy`.
