### ISSUE TITLE
Add 'title' attribute support

### ISSUE THREAD

**Issue by usmanmani1122** [CookPete/react-player#916]
#### Current Behavior
There is no support for `title` prop so that the rendered `iframe` have a `title` attribute. This causes the `accessibility` score to drop

#### Expected Behavior
Allow a prop `title` to add `title` in rendered `iframe`

**Comment by CookPete** [comment]
ReactPlayer has very little control over the iframes that [each player API](https://github.com/CookPete/react-player#supported-media) produces. If the API supports a title attribute, then it can probably be configured in the `config` prop. If not, there's not much that this library can do to help.
