### ISSUE TITLE
No TypeScript declarations for react-player/lazy

### ISSUE THREAD

**Issue by cduff** [CookPete/react-player#918]
#### Current Behavior
Trying to move to lazy loading as per instructions, importing "react-player/lazy". However this causes error as no TypeScript declaration file can be found.

#### Expected Behavior
Working TypeScript declaration file as per import of just "react-player".

#### Steps to Reproduce
Just try importing "react-player/lazy" in TypeScript project.

#### Environment
- CRA
- vscode

#### Other Information
n/a

**Comment by jurajkrivda** [comment]
Workaround: `declare module 'react-player/lazy';`

**Comment by CookPete** [comment]
It's been a while since I've used Typescript. Would it work if I just copied the `index.d.ts` file into the `lazy` directory before publishing?

**Comment by cduff** [comment]
> It's been a while since I've used Typescript. Would it work if I just copied the `index.d.ts` file into the `lazy` directory before publishing?

I just tried that locally and it works fine. I'm not sure if there's some other more correct way.
