### ISSUE TITLE
Page down: https://cookpete.com/react-player/

### ISSUE THREAD

**Issue by aemal** [CookPete/react-player#920]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Steps to Reproduce

1.
1.
1.

#### Environment
- URL attempting to play: 
- Browser: 
- Operating system: 
- jsFiddle example: https://jsfiddle.net/sv5x3ug1

**Comment by CookPete** [comment]
Fixed in https://github.com/CookPete/react-player/commit/041393adc60e1ff17cb771fcdb6fab094e0f8271
