### ISSUE TITLE
Twtich errors at aws server

### ISSUE THREAD

**Issue by sshun21** [CookPete/react-player#922]
#### Current Behavior
          <ReactPlayer
            ref={player_ref}
            playing
            url="https://www.twitch.tv/videos/640929049"
            controls
          ></ReactPlayer>

I used react-player like this. It's working right at in my local computer. but It doesn't working at ec2-server(aws). 

That  errors occur.
{"errors":{"parent":["parent query string value contains invalid domain name"]},"title":"One or more validation errors occurred.","status":400}

#### Expected Behavior

Working right at ec2-server

#### Environment
- URL attempting to play: https://www.twitch.tv/videos/640929049
- Browser: chrome
- Operating system: ubuntu

**Comment by CookPete** [comment]
See https://github.com/CookPete/react-player/issues/904#issuecomment-636468042

**Comment by sshun21** [comment]
I did it...
          <ReactPlayer
            ref={player_ref}
            playing
            url="https://www.twitch.tv/videos/640929049"
 	config={{
    		options: {
     		 parent: ['fiddle.jshell.net', 'jsfiddle.net']
    		}
  	}}
            controls
          ></ReactPlayer>

like this

**Comment by CookPete** [comment]
You need to update the `parent` array with the domains you are embedding the video on. The jsfiddle domains are an example.

**Comment by sshun21** [comment]
It has been resolved. Thank you!
