### ISSUE TITLE
Support for youtube playlist playback controls

### ISSUE THREAD

**Issue by thisiscarlosgomes** [CookPete/react-player#923]
Does react-player support player.nextVideo() and other youtube [playback controls](https://developers.google.com/youtube/iframe_api_reference#Playback_controls)?

**Comment by CookPete** [comment]
You can use the `getInternalPlayer()` method to access the internal YouTube player instance, then call `nextVideo` on that.

**Comment by thisiscarlosgomes** [comment]
> You can use the `getInternalPlayer()` method to access the internal YouTube player instance, then call `nextVideo` on that.

Great this worked like a charm :) Great work.
