### ISSUE TITLE
Twitch Video onSeek not fired and bug for seekTo when pause

### ISSUE THREAD

**Issue by xVanilla** [CookPete/react-player#924]
With any Twitch videos with controls, if I seek from the Twitch video controls, the onSeek method doesn't be called but the onPlay and onPause methods work.

There is a bug on Twitch videos when call seekTo. It works when playing is true but when the video is on pause. SeekTo method not work. Normally it's possible because on Twitch Video controls, we are able to seek the video when we are on pause or playing.

Thanks you for your awesome work

**Comment by xVanilla** [comment]
I just saw on the CookPete demo, the seekTo method doesn't work properly on Twitch video when playing is true (and the video time seek is not loading yet) and not work at all when playing is false.

**Comment by CookPete** [comment]
There is no `onSeek` event for the Twitch player – it's nowhere in the [Twitch embed docs](https://dev.twitch.tv/docs/embed/video-and-clips#interactive-frames-for-live-streams-and-vods).

As for `seekTo`, ReactPlayer is calling the `seek` method exactly as the docs describe. It's a problem with the Twitch embedded player if it doesn't work while paused. The docs even say

>Seeks to the specified timestamp (in seconds) in the video __and resumes playing if paused.__

which is obviously not what it actually does. There's nothing that this library can really do about this.

**Comment by RusseII** [comment]
@xVanilla did you find a workaround? We are having the same issue :(

**Comment by mrobb-twitch** [comment]
This should now be fixed - seek can be called at any time (but won't work for live streams), and a seek event was added.

**Comment by gatesyp** [comment]
That's awesome! Thank you!
