### ISSUE TITLE
how to play HLS aes encrypted video

### ISSUE THREAD

**Issue by discriminant-tech** [CookPete/react-player#925]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior
want to play this file
url-https://learnmedia-inwe.streaming.media.azure.net/5bac2481-d872-4068-a4b3-25b5519e627a/sample-mp4-file.ism/manifest(format=m3u8-aapl,encryption=cbc).m3u8

Tokan: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cm46bWljcm9zb2Z0OmF6dXJlOm1lZGlhc2VydmljZXM6Y29udGVudGtleWlkZW50aWZpZXIiOiJjNzFmNjM4Zi05Yzc5LTQxZmYtYjUxYS01ODVmY2Y2ZDY2ZjIiLCJ1cm46bWljcm9zb2Z0OmF6dXJlOm1lZGlhc2VydmljZXM6bWF4dXNlcyI6IjIwIiwibmJmIjoxNTkxNzgxMDE3LCJleHAiOjE1OTE4MTEzMTcsImlzcyI6Imh0dHA6Ly9hbGxlcm4uY29tIiwiYXVkIjoidXJuOmFsbGVybiJ9.pg-yvShnVfzqR9kt8BrH-ti9nvbNGxQS8cJa_UVAjFM

  <ReactPlayer
              ref={this.ref}
              className='react-player'
              width='100%'
              height='100%'
              url={url}
              config={true? {
                file: {
                  hlsOptions: {
                    forceHLS: true,
                    debug: false,
                    xhrSetup: function (xhr, url) {
                      xhr.setRequestHeader('Authorization', 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cm46bWljcm9zb2Z0OmF6dXJlOm1lZGlhc2VydmljZXM6Y29udGVudGtleWlkZW50aWZpZXIiOiJjNzFmNjM4Zi05Yzc5LTQxZmYtYjUxYS01ODVmY2Y2ZDY2ZjIiLCJ1cm46bWljcm9zb2Z0OmF6dXJlOm1lZGlhc2VydmljZXM6bWF4dXNlcyI6IjIwIiwibmJmIjoxNTkxNzgxMDE3LCJleHAiOjE1OTE4MTEzMTcsImlzcyI6Imh0dHA6Ly9hbGxlcm4uY29tIiwiYXVkIjoidXJuOmFsbGVybiJ9.pg-yvShnVfzqR9kt8BrH-ti9nvbNGxQS8cJa_UVAjFM')
                    },
                  },
                }
              } : ""}
                 />

output: 
Access to XMLHttpRequest at 'https://learnmedia-inwe.streaming.media.azure.net/5bac2481-d872-4068-a4b3-25b5519e627a/sample-mp4-file.ism/manifest(format=m3u8-aapl,encryption=cbc).m3u8' from origin 'http://localhost:3000' has been blocked by CORS policy: Request header field authorization is not allowed by Access-Control-Allow-Headers in preflight response.

#### Expected Behavior
want to play this video

#### Environment
- URL attempting to play: https://learnmedia-inwe.streaming.media.azure.net/5bac2481-d872-4068-a4b3-25b5519e627a/sample-mp4-file.ism/manifest(format=m3u8-aapl,encryption=cbc).m3u8
- Browser:  chrome
- Operating system: windows

**Comment by CookPete** [comment]
The error is fairly self-explanatory:

> Request header field authorization is not allowed by Access-Control-Allow-Headers in preflight response.

The server you are requesting the video from has not been set up to allow cross-origin requests from `http://localhost:3000`. The `Authorization` header is not present in the `Access-Control-Allow-Headers` response from the server.

**Comment by discriminant-tech** [comment]
> Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.
> 
> #### Current Behavior
> want to play this file
> url-https://learnmedia-inwe.streaming.media.azure.net/5bac2481-d872-4068-a4b3-25b5519e627a/sample-mp4-file.ism/manifest(format=m3u8-aapl,encryption=cbc).m3u8
> 
> Tokan: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cm46bWljcm9zb2Z0OmF6dXJlOm1lZGlhc2VydmljZXM6Y29udGVudGtleWlkZW50aWZpZXIiOiJjNzFmNjM4Zi05Yzc5LTQxZmYtYjUxYS01ODVmY2Y2ZDY2ZjIiLCJ1cm46bWljcm9zb2Z0OmF6dXJlOm1lZGlhc2VydmljZXM6bWF4dXNlcyI6IjIwIiwibmJmIjoxNTkxNzgxMDE3LCJleHAiOjE1OTE4MTEzMTcsImlzcyI6Imh0dHA6Ly9hbGxlcm4uY29tIiwiYXVkIjoidXJuOmFsbGVybiJ9.pg-yvShnVfzqR9kt8BrH-ti9nvbNGxQS8cJa_UVAjFM
> 
> <ReactPlayer
> ref={this.ref}
> className='react-player'
> width='100%'
> height='100%'
> url={url}
> config={true? {
> file: {
> hlsOptions: {
> forceHLS: true,
> debug: false,
> xhrSetup: function (xhr, url) {
> xhr.setRequestHeader('Authorization', 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cm46bWljcm9zb2Z0OmF6dXJlOm1lZGlhc2VydmljZXM6Y29udGVudGtleWlkZW50aWZpZXIiOiJjNzFmNjM4Zi05Yzc5LTQxZmYtYjUxYS01ODVmY2Y2ZDY2ZjIiLCJ1cm46bWljcm9zb2Z0OmF6dXJlOm1lZGlhc2VydmljZXM6bWF4dXNlcyI6IjIwIiwibmJmIjoxNTkxNzgxMDE3LCJleHAiOjE1OTE4MTEzMTcsImlzcyI6Imh0dHA6Ly9hbGxlcm4uY29tIiwiYXVkIjoidXJuOmFsbGVybiJ9.pg-yvShnVfzqR9kt8BrH-ti9nvbNGxQS8cJa_UVAjFM')
> },
> },
> }
> } : ""}
> />
> 
> output:
> Access to XMLHttpRequest at 'https://learnmedia-inwe.streaming.media.azure.net/5bac2481-d872-4068-a4b3-25b5519e627a/sample-mp4-file.ism/manifest(format=m3u8-aapl,encryption=cbc).m3u8' from origin 'http://localhost:3000' has been blocked by CORS policy: Request header field authorization is not allowed by Access-Control-Allow-Headers in preflight response.
> 
> #### Expected Behavior
> want to play this video
> 
> #### Environment
> * URL attempting to play: https://learnmedia-inwe.streaming.media.azure.net/5bac2481-d872-4068-a4b3-25b5519e627a/sample-mp4-file.ism/manifest(format=m3u8-aapl,encryption=cbc).m3u8
> * Browser:  chrome
> * Operating system: windows

pass to token to every chunk in react player


![image](https://user-images.githubusercontent.com/54133747/84563495-9aeb9580-ad79-11ea-9a4d-51410147ffb4.png)


![image](https://user-images.githubusercontent.com/54133747/84563512-b656a080-ad79-11ea-97c1-37dc356a6cc6.png)

![image](https://user-images.githubusercontent.com/54133747/84563531-d8e8b980-ad79-11ea-8e6d-dcc523b51c05.png)

**Comment by balazs31** [comment]
So, I kinda had the same issue, and it took me a few hours to figure it, I'll post here the solution in case anybody else if struggling to make this work. You only have to set the authorization header for the stream itself, not for the first request that only fetches the XML, so the config will be the following:

```
<ReactPlayer
  playing={true}
  muted={true}
  url={`${url}(format=m3u8-aapl)`}
  loop
  controls
  playsinline={false}
  config={{
      file: {
          forceHLS: true,
          hlsOptions: {
              forceHLS: true,
              debug: false,
              xhrSetup: (xhr: any, url: string) => {

                  // check for encryption key url and append only for that xhr
                  const encryptionKeyUrl = 'keydelivery';
                  if (!url.includes(encryptionKeyUrl)) {
                      return;
                  }
                  xhr.setRequestHeader('Authorization', `Bearer=${token}`);
              },
          },
      },
  }}
/>
```
