### ISSUE TITLE
Twitch Video don't fire onError when video is unavailable

### ISSUE THREAD

**Issue by xVanilla** [CookPete/react-player#926]
The onError method doesn't fire when the Twitch video is unavailable (expired) and ReactPlayer.canPlay(url) return true.

Tested with this url: https://www.twitch.tv/videos/5502156413386

Thanks for your time

**Comment by CookPete** [comment]
Annoyingly, there is no error event for [interactive twitch embeds](https://dev.twitch.tv/docs/embed/video-and-clips#interactive-frames-for-live-streams-and-vods). Until they add one, there's nothing that we can listen for.
