### ISSUE TITLE
Callback conflict with multiple Wistia ReactPlayers on the same page

### ISSUE THREAD

**Issue by afzaalahmad** [CookPete/react-player#929]
Identical to [#140](https://github.com/CookPete/react-player/issues/140) except that its for wistia.

#### Current Behavior
Any onProgress or onDuration or onPlay or onPause callback gets called when multiple Wistia ReactPlayers are on the page.

#### Expected Behavior
The onProgress, onDuration, onPlay and onPause callbacks for different ReactPlayer instances don't interact with each other.

#### Steps to Reproduce

Render the below code into app.js of react new app.
```
import React from "react";
import { render } from "react-dom";
import ReactPlayer from "react-player";

// Functional component
const PlayerA = () => {
  const [url] = React.useState(
    "https://spacetrics.wistia.com/medias/xdfbdw0lrz"
  );
  const onPlay = () => {
    console.log("play A");
  };
  const onPause = () => {
    console.log("pause A");
  };
  const onDuration = duration => {
    console.log("duration A");
  };
  const onProgress = progress => {
    console.log("progress A");
  };
  return (
    <div>
      <ReactPlayer
        url={url}
        onPlay={onPlay}
        onPause={onPause}
        onDuration={onDuration}
        onProgress={onProgress}
      />
    </div>
  );
};

const PlayerB = () => {
  const [url] = React.useState(
    "https://spacetrics.wistia.com/medias/xdfbdw0lrz"
  );
  const onPlay = () => {
    console.log("play B");
  };
  const onPause = () => {
    console.log("pause B");
  };
  const onDuration = duration => {
    console.log("duration B");
  };
  const onProgress = progress => {
    console.log("progress B");
  };
  return (
    <div>
      <ReactPlayer
        url={url}
        onPlay={onPlay}
        onPause={onPause}
        onDuration={onDuration}
        onProgress={onProgress}
      />
    </div>
  );
};

// Main App component
// renders a list of Messages using data from messages.json
const App = () => {
  return (
    <div>
      <PlayerA />
      <PlayerB />
    </div>
  );
};

render(<App />, document.getElementById("root"));

```

#### Environment
- URL attempting to play: https://spacetrics.wistia.com/medias/xdfbdw0lrz
- Browser: Chrome
- Operating system: Ubuntu
- codeSandBox example: https://codesandbox.io/s/codealong-for-react-functional-components-f5pxi

**Comment by CookPete** [comment]
https://github.com/CookPete/react-player/pull/905 might fix this? I'll see if I can get it in soon.

**Comment by afzaalahmad** [comment]
@CookPete yes it will fix this issue, but can't we modify in a way that if user provides key for the player we attach it to div as it is, if not provided than it will attach random key to player.

**Comment by CookPete** [comment]
https://github.com/CookPete/react-player/pull/905 is now merged and will be published shortly.
