### ISSUE TITLE
Question - Enable Closed Captions on YouTube video

### ISSUE THREAD

**Issue by newbreedofgeek** [CookPete/react-player#93]
Hello,

This is a question and not an issue.

I'm using the player to show a YouTube video. I want to enable Closed Captions by default.

I'm trying this but it does not work (based on this https://developers.google.com/youtube/player_parameters?playerVersion=HTML5#cc_load_policy).
```
this.config = {
      "playerVars": {
        "cc_load_policy" : "1"
      }
    }

<ReactPlayer url='https://www.youtube.com/watch?v=3UJiZARaXWQ' playing youtubeConfig={this.config} />
```

Am I doing something wrong?

Thanks,

**Comment by CookPete** [comment]
I can't see anything wrong with your config. In fact you can test this out on the [demo page](http://cookpete.com/react-player) if you paste in
```json
{"youtubeConfig":{"playerVars":{"cc_load_policy":1}}}
```
to the `Custom config` field. What's weird is that after entering that config, you can load up `YouTube Test B` and see captions.. but captions do not appear when loading your custom URL, so I'm not sure what's going on, unless there is a setting in Youtube for your specific video?

You can also inspect the youtube embed elements and see `cc_load_policy=1` in the embedded URL generated by the API, to make sure the custom config is definitely being sent through.

**Comment by newbreedofgeek** [comment]
Thanks for looking into this @CookPete 

I don't think this works, YouTube Test B shows CC always (I'm guessing its enabled by default on that video) so its not because of "cc_load_policy":1

Let me keep looking into this.

**Comment by CookPete** [comment]
>YouTube Test B shows CC always (I'm guessing its enabled by default on that video) so its not because of "cc_load_policy":1

They do not show for me until I put in the config (same in incognito mode on chrome). I wonder if it also depends on your YouTube account playback settings, if you are signed in?

**Comment by newbreedofgeek** [comment]
@CookPete I think you are right.

It looks like its based on what you have selected in YouTube.

We can close this off. It was not an issue.
