### ISSUE TITLE
Hls/m3u8 gives error

### ISSUE THREAD

**Issue by jimmirbn** [CookPete/react-player#930]
#### Current Behavior
Hls/m3u8 gives error

#### Expected Behavior
React-player loads video and start playing

#### Steps to Reproduce
1. Add HLS url
2. Look at console

#### Environment
- URL attempting to play: https://res.cloudinary.com/earthspeakr/video/upload/sp_full_hd/Prelaunch/zr2xflxwlxksl3vusmk2.m3u8
- Browser: Chrome
- Operating system: Mac OSX Mojave 10.14.6 

#### Other Information
The video plays fine when using react-player demo. : https://cookpete.com/react-player/

Screenshot: 
![image](https://user-images.githubusercontent.com/11026872/84427147-b42efd80-ac24-11ea-8782-1cd9c3fa34c1.png)

**Comment by CookPete** [comment]
This seems like a problem with `hls.js` and not ReactPlayer. You can see where `buildAbsoluteURL` is called [here](https://github.com/video-dev/hls.js/search?q=buildabsoluteurl&unscoped_q=buildabsoluteurl). If it works in the demo app then it's likely something specific to your implementation, and there's not much I can do to help.

**Comment by jimmirbn** [comment]
Hi.
The issue what that the url was in an array, cause I had multiple formats before. When using a streaming-url it doesn’t work.

Regards Jimmi

**Comment by joernroeder** [comment]
I'm experiencing the same error with the following array of urls
```
url = [
"https://domain.com/id.m3u8"
"https://domain.com/id/medium.mp4"
]
```
the problem is here where the array gets passed down to `hls` https://github.com/cookpete/react-player/blob/060c328f16194fe6b9072855c8749ee7eb8d456a/src/players/FilePlayer.js#L176
