### ISSUE TITLE
Wistia same video on two different routes with different configurations conflict

### ISSUE THREAD

**Issue by afzaalahmad** [CookPete/react-player#934]
#### Current Behavior
Currently going to two different routes back and forth causing configurations conflict.

#### Expected Behavior
Both configuration must behave differently and correctly.
Player A: Expected behavior is that it must be muted with controls.
Player B: Expected behavior is that it must only give option of seeking to user.

#### Steps to Reproduce
1. Goto Player A, play the video upto 5-6 seconds and then goto player B using the button above the video.
2. Goto Player B, play the video upto 5-6 seconds and then goto player A using the button above the video.

```
import React from "react";
import { render } from "react-dom";
import { BrowserRouter as Router, Switch, Route } from "react-router-dom";
import { createBrowserHistory } from "history";
import { Link } from "react-router-dom";
import ReactPlayer from "react-player";

const Home = () => {
  return (
    <div>
      <Link to="/playerA">Goto Player A</Link>
      <br />
      <br />
      <Link to="/playerB">Goto Player B</Link>
    </div>
  );
};

const PlayerA = () => {
  return (
    <div>
      <Link to="/playerB">Goto Player B</Link>
      <br />
      <br />
      <ReactPlayer url="https://home.wistia.com/medias/e4a27b971d" muted />
    </div>
  );
};

const PlayerB = () => {
  const [url] = React.useState("https://home.wistia.com/medias/e4a27b971d");
  const onPlay = () => {
    console.log("play B");
  };
  const onPause = () => {
    console.log("pause B");
  };
  const onDuration = duration => {
    console.log("duration B");
  };
  const onProgress = progress => {
    console.log("progress B");
  };
  return (
    <div>
      <Link to="/playerA">Goto Player A</Link>
      <br />
      <br />
      <ReactPlayer
        url={url}
        onPlay={onPlay}
        onPause={onPause}
        onDuration={onDuration}
        onProgress={onProgress}
        config={{
          wistia: {
            options: {
              controlsVisibleOnLoad: false,
              copyLinkAndThumbnailEnabled: false,
              fakeFullscreen: false,
              fullscreenButton: false,
              fullscreenOnRotateToLandscape: false,
              muted: true,
              settingsControl: false,
              playbutton: false,
              playSuspendedOffScreen: false,
              silentAutoPlay: true,
              smallPlayButton: false,
              volume: 0,
              volumeControl: false,
              endVideoBehavior: "auto",
              autoPlay: false,
              playbar: true
            }
          }
        }}
      />
    </div>
  );
};
// Main App component
// renders a list of Messages using data from messages.json
const App = () => {
  return (
    <div>
      <Router history={createBrowserHistory()}>
        <Switch>
          <Route exact path="/" component={Home} />
          <Route exact path="/playerA" component={PlayerA} />
          <Route exact path="/playerB" component={PlayerB} />
        </Switch>
      </Router>
    </div>
  );
};

render(<App />, document.getElementById("root"));

```

#### Environment
- URL attempting to play: https://home.wistia.com/medias/e4a27b971d
- Browser: Chrome
- Operating system: Ubuntu 20.04 
- CodeSandBox example: https://codesandbox.io/s/codealong-for-react-functional-components-n98fs

#### Other Information
I have investigated this issue on my end. Unable to pinpoint the error.

**Comment by CookPete** [comment]
I'm pretty sure this is a bug with the Wistia player. 

I've managed to boil it down to a very basic example: https://jsfiddle.net/w7Luav29/1/

Notice that when you first toggle muted to true (count = 1), the config is not picked up correctly and the player is not muted. But then every time after that (count = 3, 5, 7, etc) things work correctly.

Also even weirder is that if muted is initially `true`, things seem to work ok.

I'm honestly not sure what we can do about this apart from let the Wistia team know.

**Comment by afzaalahmad** [comment]
I investigated this issue very thoroughly and still trying to figure out that whether react rendering is the problem or may be our player configuration setup.

I want you to take a look at following two codes: 
1. [wistia-embed-options-demo](https://glitch.com/edit/#!/wistia-embed-options-demo) by wistia.

I tried the above options even with two players and it works fine.

**Comment by afzaalahmad** [comment]
Though my problem is not that I want to change options on some click. My problem is that I want to run two player with two different options. It works sometimes and sometimes it doesn't. I have also contacted wistia support on this issue.

You can also see [two-wistia-players-with-two-different-options](https://glitch.com/edit/#!/spice-useful-report)

Regards
