### ISSUE TITLE
Video black with mp4 url

### ISSUE THREAD

**Issue by alextrastero** [CookPete/react-player#935]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior
Player is showing black, nothing happening

#### Expected Behavior
Player to appear and playable as when I use a youtube `src`

#### Steps to Reproduce
https://codesandbox.io/s/blissful-dawn-9p6d7

I found this similar issue https://github.com/CookPete/react-player/issues/856 but doesn't seem to be solved

**Comment by lfzawacki** [comment]
This seems to work on Firefox, I think your problems is that your mp4 video is served via http and this yields a Mixed Content error on the browser level. So not exactly the libraries fault.

**Comment by afzaalahmad** [comment]
Since the url you provided will be used by FilePlayer. So, In order to run your video, you ither have to enable controls which you can do by providing props:
`<ReactPlayer url={src} controls />`

@CookPete I think controls prop default value must be true.

**Comment by alextrastero** [comment]
Thanks @afzaalahmad, adding `controls` prop made it work
