### ISSUE TITLE
Using "light" prop as a thumbnail that opens video in Modal

### ISSUE THREAD

**Issue by alextrastero** [CookPete/react-player#936]
This is not an issue but rather a "how to", feel free to close if not useful

#### Current Behavior
As shown in this [example](https://codesandbox.io/s/hardcore-morning-movt3?file=/src/App.js) I'm trying to show the a video with "light" prop as a thumbnail, then when clicking I would like to show the video on a Modal. This works fine although I would like the thumbnail to remain intact, as in do not render player.

#### Expected Behavior
Clicking on thumbnail stops normal behaviour

#### Steps to Reproduce
https://codesandbox.io/s/hardcore-morning-movt3

![image](https://user-images.githubusercontent.com/4152819/84640875-8edb1180-aefa-11ea-9130-c927fdaff502.png)

**Comment by alextrastero** [comment]
```jsx
  const openModal = e => {
    e.stopPropagation(); // maybe this would stop video click behaviour

    // update state and show another Player inside a Modal
  };

  return <ReactPlayer light url={url} onClick={openModal} />
```

**Comment by alextrastero** [comment]
Maybe assigning a `ref` and using the instance method `showPreview` to return a thumbnail? Although I've tried this on a stateless component and returns `null` :)

**Comment by CookPete** [comment]
@alextrastero  You must have been close! This works for me:

```jsx
export default function App() {
  const ref = useRef();
  const [show, setShow] = useState(false);
  const url = "https://www.youtube.com/watch?v=jNgP6d9HraI";
  const handleClick = () => {
    setShow(true);
    ref.current.showPreview();
  };
  return (
    <div className="App">
      <ReactPlayer ref={ref} light url={url} onClick={handleClick} />
      {show && <ReactPlayer url={url} playing />}
    </div>
  );
}
```

https://codesandbox.io/s/pensive-hertz-e0ul0?file=/src/App.js

**Comment by petrogad** [comment]
Thank you @CookPete I've been after this one for a while!
