### ISSUE TITLE
Refetch mpd format chunks after network connection reconnects 

### ISSUE THREAD

**Issue by rbhindwale** [CookPete/react-player#939]
Hi, 

I am using mpd file format to play videos in react player. I am implementing this scenario where the network (4G/Wifi) gets disconnected and then reconnects again perhaps after few secs. When the connection is severed, the player tries to fetch the video chunks but fails. After the network connection is re-established, is there a way the failed chunks can be refetched ? On network connection loss, onBuffer is triggered. Based on when the network in online again (online event listener), would it be possible to refetch the chunks ? 

#### Current Behavior
After the network connection is lost and re-established, the mpd video chunks which failed to load are not refetched

#### Expected Behavior
Once the network connection is re-established, the player refetched the failed chunks

**Comment by rbhindwale** [comment]
@CookPete, please let me know your thoughts on the same. I can try to implement, if you think it will be a valuable feature addition.

Thanks!!

**Comment by CookPete** [comment]
ReactPlayer uses `dash.js` for mpd files, so this is a matter for them and not something that should be fixed in this library.

There's lots of discussion branching from this thread: https://github.com/Dash-Industry-Forum/dash.js/issues/599

Have you tried using `config.file.dashVersion` to use a more recent version of `dash.js`?

**Comment by rbhindwale** [comment]
Thanks for the suggestion! No, I haven't tried a more recent version. I will check it out. 

Also, thank you for the amazing work with this player :) It's awesome!
