### ISSUE TITLE
You have to click on play 2 times in order to play the video, when `light` is defined

### ISSUE THREAD

**Issue by BrodaNoel** [CookPete/react-player#940]
#### Current Behavior
Click on PLAY-icon (the one is over the video), and the video is going to start loading, but not playing. You have then to click on the PLAY-control icons

#### Expected Behavior
Click on PLAY-icon should load and play the video.

#### Steps to Reproduce
1. Click on Play icon button.

#### Environment
- URL attempting to play: I can't publish it. It is an mp4 file
- Browser: Chrome 83
- Operating system: MacOS Catalina
- jsFiddle example: https://jsfiddle.net/baonLxwz/ (here the video even don't load)

**Comment by BrodaNoel** [comment]
You can even reproduce it opening https://cookpete.com/react-player/ and selecting `mp4`, `light` and `controls`

**Comment by afzaalahmad** [comment]
@BrodaNoel You can achieve your required functionality by providing playing="true" props along with light and controls.

**Comment by CookPete** [comment]
@afzaalahmad is right. `playing` is false by default (for various reasons). Use `<ReactPlayer playing light />` for the expected behaviour.
