### ISSUE TITLE
custom "light" icon cut off on render

### ISSUE THREAD

**Issue by NickDesignsThings** [CookPete/react-player#941]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior
I have a set of icons (png) to render in place of each video, and set the path using "light." When it renders on the page, those Icons are cropped/cutoff to the dimensions of the "play button" icon that superimposes over the icons.

#### Expected Behavior
I would like the icons to display uncropped and true to their aspect ratio, with the play button over top of them

**Comment by CookPete** [comment]
You need to pass in a `width` and `height` that matches the pngs you are passing as the `light` prop. The player uses background image and `background-size: cover` to ensure whatever image is passed in fills the space of the player.

Seems like a similar problem to https://github.com/CookPete/react-player/issues/908
