### ISSUE TITLE
why not working react player when i use .avi extension video url  

### ISSUE THREAD

**Issue by devsinhere** [CookPete/react-player#946]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Steps to Reproduce

1.
1.
1.

#### Environment
- URL attempting to play: 
- Browser: 
- Operating system: 
- jsFiddle example: https://jsfiddle.net/sv5x3ug1

**Comment by CookPete** [comment]
https://stackoverflow.com/questions/4129674/does-html5-video-playback-support-the-avi-format
