### ISSUE TITLE
Replay button after ending the video

### ISSUE THREAD

**Issue by lakshmikanth-reddy-au2** [CookPete/react-player#947]
I want to display a replay button when video ends just like u see in youtube. But i cant figure it out how to implement it.

Can someone help me with this please .

**Comment by CookPete** [comment]
You could use the `onEnded` prop and the `showPreview` instance method, to show the thumbnail that you see in `light` mode.

Rough example:

```jsx
<ReactPlayer
  ref={p => { this.p = p }}
  url='https://www.youtube.com/watch?v=C0DPdy98e4c'
  playing
  controls
  onEnded={() => this.p.showPreview()}
/>
```

https://jsfiddle.net/rofd9ye1/
