### ISSUE TITLE
youtube from IOS mobile device not working as aspected

### ISSUE THREAD

**Issue by ronmara** [CookPete/react-player#949]
#### Current Behavior
Watching youtube from mobile (IOS) with controls is not working.
1. I cant press the volume and full-screen buttons because the title is hiding them.
2. Clicking on the video makes double click happen

#### Expected Behavior
I would be able to click full screen and volume.
If I use youtube iframe the buttons move to the bottom

#### Steps to Reproduce

1. go to the demo page from any mobile IOS device
1. click on one of the youtube tests
1. Turn on controls

#### Environment
- URL attempting to play: any
- Browser: chrome
- Operating system: 13.5.1 
- jsFiddle example: https://cookpete.com/react-player/

**Comment by teaglebuilt** [comment]
I can confirm this issue above on safari

**Comment by CookPete** [comment]
This is not a problem with ReactPlayer. This library uses the [YouTube Player API](https://developers.google.com/youtube/iframe_api_reference) to play YouTube URLs and this looks like a recent change to that API that has broken things on mobile. Maybe try StackOverflow as per [the Player API support page](https://developers.google.com/youtube/players/support).
