### ISSUE TITLE
video player does not follow streaming engine load balancer, it does not seem to redirect

### ISSUE THREAD

**Issue by elieobeid7** [CookPete/react-player#950]
We have 2 wowza servers which use wowza load balancer. The android application is working fine. The reactJS PWA web application player which uses react-player, which contains hls.js and video.js isn't redirecting to the correct  url

I don't know which of the above components is faulty, no error is shown whatsoever is there anything we need to do in order to help react-player redirect to the correct URL?

Some settings in Wowza or some tweaks to the player? Does anyone have any experience regarding that?

Note: if I disable the load balancer and give the player a normal link, the player works.

**Comment by elieobeid7** [comment]
https://www.wowza.com/community/questions/56919/wowza-loadbalancer-web-hls-player-does-not-redirec.html?childToView=56947#answer-56947

According to by Alexey Ostroumov 

> load balancer URL like: https://[load-balancer-ip-address]/redirect/[application-name]/[stream-name]?type=m3u8 may not work because of mime type. You can set it by hls.js setting if react-player allows to add it.

Where is that setting?

**Comment by CookPete** [comment]
See https://github.com/CookPete/react-player/issues/319#issuecomment-364036156 for an example of using the `xhrSetup` option with `hls.js`. I assume you can set a mime type here as Alexey suggests.

Possibly useful links:

- https://github.com/video-dev/hls.js/blob/master/docs/API.md#xhrsetup
- https://github.com/video-dev/hls.js/issues/803
- https://github.com/video-dev/hls.js/issues/1099
- https://github.com/CookPete/react-player/issues/442
