### ISSUE TITLE
playIcon is not displayed

### ISSUE THREAD

**Issue by VapiSoft** [CookPete/react-player#951]
Hi, 
Thanks for the video player.
The code:
`      <ReactPlayer light={true} playIcon={get_images_url('celeb.png')} url={this.video_url} playing={false} loop={true} controls={true} volume={1} width={page_size.width-20}/>
`
But I see only a line with the url insead of the image.

**Comment by CookPete** [comment]
`playIcon` should be a component. If you pass a string, it will render a string. 

Try this instead:

```jsx
playIcon={<img src={get_images_url('celeb.png')} />}
```

**Comment by VapiSoft** [comment]
Hi Pete,

Thanks. Now it shows the image, but without a "play" button at the center,
so I am afraid that the user will not know that he/she needs to click on it
to start the video.


Shlomo Aran
054-7399-340
