### ISSUE TITLE
The controls line is hidden

### ISSUE THREAD

**Issue by VapiSoft** [CookPete/react-player#952]
Hi,
Thanks for nice player.
This is the code:
`      <ReactPlayer light={true} playIcon={get_images_url('celeb.png')} url={this.video_url} playing={false} loop={true} controls={true} volume={1} width={page_size.width-20}/>
`
But the controls line is displayed only when I click on video.
I assume that my clients will guess it.

**Comment by CookPete** [comment]
Passing `light={true}` shows a preview to prevent loading the player API until after the user clicks the preview. Controls will not be shown until the player API loads the full player.

**Comment by VapiSoft** [comment]
After I clicked on the image, it shows the controls for a split of a second
and then hides it.
Now there is a difference of behaviour.
In desktop mode: it shows the controls when I place the mouse over it
(hoover).
In mobile mode: it shows the controls when I click on it (There is no
hoover in mobile mode).
Thanks.




Shlomo Aran
054-7399-340

**Comment by CookPete** [comment]
What are you expecting to happen? The display of controls on hover/click is entirely down to the browser and/or player API used to play the videos. Nothing we can really control.

**Comment by VapiSoft** [comment]
OK, I thought that is i spart of the compoont.
