### ISSUE TITLE
Related youtube videos

### ISSUE THREAD

**Issue by daria-sakharova** [CookPete/react-player#959]
This is rather a question than an issue, I would be very thankful for any input.

I noticed that on your [demo page](https://cookpete.com/react-player/) you don't have any youtube's suggestions  - "More videos" when the video is paused. But since Youtube doesn't allow to remove related videos with `rel=0` anymore, I am wondering what your secret is. Not finding anything related to it in the source code, I decided to ask here.

<img width="731" alt="Screenshot 2020-07-03 at 21 15 50" src="https://user-images.githubusercontent.com/31997336/86491428-96603e80-bd73-11ea-9588-bd733f036d0a.png">

**Comment by CookPete** [comment]
It seems to be simply the width of the player. I'm not sure what the exact breakpoint is, but the demo app is `480px` wide and doesn't show suggestions. If I make it wider then it does.
