### ISSUE TITLE
Testing "legacy" browsers, Youtube links are not being embedded 

### ISSUE THREAD

**Issue by sniepoort** [CookPete/react-player#96]
I've been running a few browser compatibility checks using BrowserStack. There seems to be a consistent issue with embedding a youtube url from for example Firefox <36, Chrome <39, Safari <7. 
The only consistent console i'm getting has something to do with the widgetapi. From Chrome i'm getting:
`Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('http://localhost:5000').`

From Safari I'm getting:
`[Error] Failed to load resource: An SSL error has occurred and a secure connection to the server cannot be made. (www-widgetapi.js, line 0)` 

Firefox isn't giving any errors at all.

They all end up rendering a div with a 'youtube-player-0 ' id

**Comment by CookPete** [comment]
It seems like we are at the mercy of the Youtube iframe API here. I have seen this error before and attempted to combat it by [adding the window's `origin` to the playerVars](https://github.com/CookPete/react-player/blob/master/src/players/YouTube.js#L75), but I'm not sure what else to try.

There are [several StackOverflow and GitHub issues](https://www.google.co.uk/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=youtube+api+Failed+to+execute+'postMessage'+on+'DOMWindow'%3A+The+target+origin+provided) about this error, and most answers mention using `https` over `http` in the embed URL, whereas ReactPlayer just uses `new YT.Player` constructor to let the API do that for us.

**Comment by Deelux** [comment]
Did you guys manage to figure out how to fix this? All the videos do load but it seems that they first throw a lot of these errors. I also read somewhere you should force an SSL connection.

**Comment by CookPete** [comment]
This looks like a problem with the Youtube iframe API, not ReactPlayer. Closing this off for now.
