### ISSUE TITLE
TypeError: Cannot read property 'Player' of null

### ISSUE THREAD

**Issue by eini122** [CookPete/react-player#961]
Hi, Peter,

For some reason, I am getting the error showing the Error:
Uncaught (in promise) TypeError: Cannot read property 'Player' of null at eval (Vimeo.js?2cba:103)

I have tried other Vimeo id and get the same error. But the weird part is Youtube URL works.

**Comment by CookPete** [comment]
After you get this error. Does `window.Vimeo` return anything? If not, is `window.define` defined?

This has been reported before in AMD environments. The Vimeo player tries to `define` itself as an AMD module if `define` is present in the global scope, which means it won't be available on `window` and so `window.Vimeo.Player()` will cause this error.

**Comment by eini122** [comment]
`window.Vimeo` is undefined, 
define is defined. 
`define: function(e,i,t){var r,n;"string"!=typeof e&&(t=i,i=e,e=null),isArray(i)||(t=i,i=null),!i&&isFunction(t)&&(i=[],t.length&&(t.toString().replace(commentRegExp,commentReplace).replace(cjsRequireRegExp,function(e,t){i.push(t)}),i=(1===t.length?["require"]:["require","exports","module"]).concat(i))),useInteractive&&(r=currentlyAddingScript||getInteractiveScript())&&(e||(e=r.getAttribute("data-requiremodule")),n=contexts[r.getAttribute("data-requirecontext")]),n?(n.defQueue.push([e,i,t]),n.defQueueMap[e]=!0):globalDefQueue.push([e,i,t])}`
Would you mind providing more information for fixing the issue?

**Comment by CookPete** [comment]
You need to load the Vimeo player API manually before `define` is set in the global scope, ie:

```html
<script src="https://player.vimeo.com/api/player.js"></script>
```

When loaded later (by ReactPlayer or otherwise) the script will see `define` in the global scope and define it as an AMD module, which means ReactPlayer can't use it.

**Comment by eini122** [comment]
Thanks. It works now
