### ISSUE TITLE
Start in PiP by default

### ISSUE THREAD

**Issue by kladnik** [CookPete/react-player#962]
#### Current Behavior
Setting `pip={true}` does not load it in PiP by default. I also tried setting pip to true once the player is ready, but I get an error.

#### Expected Behavior
Setting `pip={true}` should open PiP on load.

#### Other Information
Is this a limitation with Picture in Picture?

**Comment by CookPete** [comment]
What URL are you trying to play? PiP only works with file URLs at the moment: https://github.com/CookPete/react-player/issues/957#issuecomment-653194342

**Comment by kladnik** [comment]
I am using file URLs (example: https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8).

PiP does work once I press Enable Pip button, but I would want it to load directly into pip at start.
