### ISSUE TITLE
Video is not loading extra chunk anymore after doing `hls.recoverMediaError();`

### ISSUE THREAD

**Issue by Enigma10** [CookPete/react-player#963]
I was getting `bufferstallederror` for some of our live streams. So i tried to solve this in onError Function like this: 

```
      onError={(err, data, hls, global) => {
        hls.recoverMediaError();
      }}
```

Now hls.recoverMediaError is working fine but video is not loading extra chuck anymore.

**Comment by CookPete** [comment]
This is a problem with [hls.js](https://github.com/video-dev/hls.js) rather than ReactPlayer. I recommend opening an issue over there.

**Comment by gigincg** [comment]
@Enigma10 Did you find a solution for this?
