### ISSUE TITLE
Config does not work? 

### ISSUE THREAD

**Issue by zhg-kj** [CookPete/react-player#965]
I am trying to change the playerVars for the youtube. I followed the config exactly as stated in the documentation but it does not change? I am very confused.

```
<ReactPlayer 
                            ref={this.ref}
                            url={currentVideo} 
                            playing={playing} 
                            volume={volume}
                            onEnded={this.handleStop}
                            onBufferEnd={this.bufferEnd}
                            onReady={this.bufferStart}

                            config={{
                                youtube: {
                                    playerVars: { disablekb:1, rel:0}
                                },
                            }}

                            className='reactPlayer'
                            width='52.7vw'
                            height='29.64375vw'
                        />
```

**Comment by CookPete** [comment]
See information about how `rel` changed in 2018 here: https://developers.google.com/youtube/player_parameters#august-23,-2018

`disablekb:1` works correctly for me using your exact config. After clicking to play a YouTube video, pressing space no longer pauses/unpauses the video.

**Comment by zhg-kj** [comment]
That is strange, space continues to pause and unpause the video for me. Could this be an issue with browsers? I am on Chrome

**Comment by CookPete** [comment]
>I notice that in your demo your youtube player does not show a "More videos" section when the video is paused but there is no config indicating it being disabled in the source code. Do you know how you did that?

Answered recently in https://github.com/CookPete/react-player/issues/959
