### ISSUE TITLE
react-player 内有黑框，如何给他加样式呢？去除内部video标签

### ISSUE THREAD

**Issue by fenglijunnb** [CookPete/react-player#966]
![image](https://user-images.githubusercontent.com/48191768/87389835-2014d500-c5da-11ea-9f17-e2c16135a1ee.png)

**Comment by CookPete** [comment]
Translated to:

>There is a black box in react-player, how can I style it? Remove internal video tag

The `width` and `height` props you pass in must match the aspect ratio of the video you are playing, otherwise it will not fit correctly.

Translated back using Google Translate:

> 您传入的宽度和高度必须与视频的长宽比匹配，否则将无法正确显示。
