### ISSUE TITLE
Audio stops on refresh

### ISSUE THREAD

**Issue by jnarwold** [CookPete/react-player#971]
#### Current Behavior
When I'm playing an audio file, refreshing the page does not allow for the audio to continue by default (without user interaction). I set the `playing` attribute to true and it recognizes that it _should_ be playing but does nothing.

#### Expected Behavior
Audio should resume playing on refresh

#### Steps to Reproduce
```
const renderPlayer = () => {
   const playerProps = {
      playing: true,
      controls: true,
      url: 'insertFileUrlHere',
      file: {
        forceAudio: true
      }
    }

    return (<ReactPlayer {...playerProps} />)
}
```

1. Load page w/ audio player
2. Click play button (validate audio is playing)
3. Refresh page

#### Environment
- Browser: Chrome (84.0.4147.89)
- Operating system: Windows

**Comment by CookPete** [comment]
This sounds like autoplay policy kicking in. In recent versions of Chrome, audio and video will not autoplay on unfamiliar sites without user interaction. This is the way things are going, and there's nothing we can really do about it.

https://developers.google.com/web/updates/2017/09/autoplay-policy-changes
