### ISSUE TITLE
m3u8 video is not playing when passing as URL

### ISSUE THREAD

**Issue by bgayatri-turner** [CookPete/react-player#973]
I have a video Url like this
`https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8?token=595420799~id=595420799`
When I passing this as a source its not playing the video, keep on loading.
I can see the video is playing when using Play HLS chrome extension

`<ReactPlayer
                            className='react-player'
                            style={{ background: "#000", color: "#fff" }}
                            width='100%'
                            height='100%'
                            url={videoUrl}
                            controls
                            playing
                          />`

**Comment by beamercola** [comment]
Same here

**Comment by beamercola** [comment]
I found the issue - I'm using Next.js and SSR - i just have to skip rendering the component when on server and now it loads fine 

`if (!process.browser) return null;` - hope that helps

**Comment by CookPete** [comment]
@bgayatri-turner Feel free to reopen if this is not related to SSR.

**Comment by gunslingerOP** [comment]
> I found the issue - I'm using Next.js and SSR - i just have to skip rendering the component when on server and now it loads fine
> 
> ```
> import dynamic from "next/dynamic";
> const Player = dynamic(import("./Player"), { ssr: false });
> ```
> 
> hope that helps

I'm sorry but what exactly did you import dynamically? I'm facing the same issue as well, when I hard code the HLS url the player works but when I put it in a state and use that state it simply doesn't load.
