### ISSUE TITLE
Auto loop a playlist of local videos

### ISSUE THREAD

**Issue by cspecter** [CookPete/react-player#98]
I have a list of 10 locally hosted mp4s. I would like to play through all 10 one after the other and loop through them continuously. I have it working by setting a state using the onEnded callback. My problem is that by using the components state it's reloading the component each time and there is a visible blip as the old video is unloaded and the new video loads. Since each video is only 10-20 seconds long that it's a little disjointing. Is there a way to preload a list of videos into memory and just iterate through them without reloading the component? Or a better way to design the component?

```
import React, {Component} from 'react';
import {HTTP} from 'meteor/http';
import ReactPlayer from 'react-player'

export default class VideoPlayer extends Component {
    constructor() {
        super();
        this.state = {
            index: 0,
            videos: []
        };
    }

    componentDidMount() {
        HTTP.call('GET', 'https://url.com/homepage_videos', function(err, res) {
                if (err) { console.log(err) }
                if (res) { this.setState({videos: res.data}) }
            }.bind(this)
        );
    }

    _setIndex() {
        return (this.state.index == this.state.videos.length-1) ? 0 : this.state.index++
    }

    render() {
        return (
           <div>
               <ReactPlayer url={this.state.videos[this.state.index]} playing onEnded={() => this.setState({ index: this._setIndex()})} />
           </div>
        )
    }

}

```

**Comment by CookPete** [comment]
Not sure how/if you achieved this, but I would have rendered multiple hidden players and displayed/played each one in turn using an `index` value. Or you could have just rendered (but hidden) the next video to ensure it is loaded and ready.

**Comment by alizamani** [comment]
Has a change been made? This is one of the basic needs of any player! I need local files play  after the other and loop through them continuously.

**Comment by CookPete** [comment]
>This is one of the basic needs of any player!

I respectfully disagree. The purpose of this library is to play a video based on the URL passed in. A seamless playlist system is way beyond the scope of the component. 

Anyone is more than welcome to publish a new library that uses ReactPlayer to achieve this.

>Has a change been made?

It isn't particularly difficult to implement yourself: https://jsfiddle.net/zyd7u3tv/

I've used `opacity: 0.00001` for the non-playing videos, to ensure they are preloaded in Chrome – Chrome seems to know if a video is not visible and doesn't preload it, which causes the flash of white when switching videos. Someone can probably come up with a better way to achieve this.
