### ISSUE TITLE
Video `muted` attribute not being added to File player

### ISSUE THREAD

**Issue by eheaton** [CookPete/react-player#980]
I'm trying to autoplay a video on Mobile / iOS, and I know the `muted` html attribute is required in order to make this happen. No matter what I try, I can't get the attribute to appear.

#### Current Behavior
Using this react code:

```html
<ReactPlayer
  url="/video.mp4"
  controls={false}
  muted={true}
  volume={1}
  playing={true}
  width="100%"
  height="100%"
  playsinline={true}
  config={{ file: {
    attributes: {
      muted: true,
    }
  }}}
/>
```

Produces this HTML:
```html
<div style="width: 100%; height: 100%;">
  <video src="/video.mp4" preload="auto" autoplay="" playsinline="" webkit-playsinline="" x5-playsinline="" style="width: 100%; height: 100%;"></video>
</div>
```

#### Expected Behavior
It should produce this HTML:
```html
<div style="width: 100%; height: 100%;">
  <video src="/video.mp4" preload="auto" autoplay="" playsinline="" muted webkit-playsinline="" x5-playsinline="" style="width: 100%; height: 100%;"></video>
</div>
```
_(Note the additional `muted` attribute)_

#### Steps to Reproduce
1. See code example above

#### Environment
- Browser: Chrome, Safari (Mobile & Desktop)
- Operating system: Mac, iOS

**Comment by CookPete** [comment]
After a bit of searching this looks like a bug in React: https://github.com/facebook/react/issues/10389

Potentially useful article: https://medium.com/@BoltAssaults/autoplay-muted-html5-video-safari-ios-10-in-react-673ae50ba1f5

**Comment by eheaton** [comment]
Thanks for the quick response. I'll check those out
