### ISSUE TITLE
how to unmount the player when paused

### ISSUE THREAD

**Issue by rburgst** [CookPete/react-player#984]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior
we are using react-fullpage in order to do fullpage scrolling. However, when I have one page contain `react-player` then as soon as the youtube video is open, all scroll events seem to be captured by the player and it is no longer possible to scroll the page up and down.

#### Expected Behavior
If the player is paused it should be possible to dismount the youtube player (or somehow no longer render it fully) in order to be able to interact with the page again.

#### Steps to Reproduce

see https://codesandbox.io/s/react-fullpagejs-example-eumnu?file=/src/index.js

#### Environment
- URL attempting to play: any youtube video  https://www.youtube.com/watch?v=20jfI_Z6Qe0
- Browser: Chrome
- Operating system: Mac OSX Catalina 
- codesandbox example: https://codesandbox.io/s/react-fullpagejs-example-eumnu?file=/src/index.js

#### Other Information
N/A

**Comment by CookPete** [comment]
After a quick search:

- https://github.com/alvarotrigo/fullPage.js/issues/2229
- https://stackoverflow.com/questions/53974357/prevent-iframe-scroll-capture-on-youtube-iframe-embed-on-chrome

It seems like there is no `pointer-events: none;` equivalent for only scroll events, which is basically what you're after.

You could listen to `onPlay` and set `pointer-events: none` when the video starts playing, but then you wouldn't be able to pause it again.

In fact, you could set `pointer-events: none` and have a `div` overlaying the whole player, which does `onClick={playOrPause}` and toggles the `playing` state. That might work?

**Comment by rburgst** [comment]
Ok, I came up with a different solution. I intercept the `onPause` and set `display:none` in case the player is paused. This fixes the problem and also allows me to keep the playback position when the user pauses.

**Comment by rburgst** [comment]
obviously I need to have my own poster image in that case. However, it might be interesting to have something like this supported out of the box.
