### ISSUE TITLE
webkit-playsinline

### ISSUE THREAD

**Issue by whitegrey** [CookPete/react-player#99]
With ios 10 and safari 10 on the horizon, would you consider adding "webkit-playsinline" attribute as an option?

**Comment by CookPete** [comment]
Hey @whitegrey, this is already done for FilePlayer, although it is [set on mount](https://github.com/CookPete/react-player/blob/master/src/players/FilePlayer.js#L19) due to [this issue](https://github.com/facebook/react/issues/140) with non-standard attributes in React.

**Comment by thomasmattheussen** [comment]
I think this just got fixed in a new version of React.

**Comment by CookPete** [comment]
Ok great. Just reopen the issue if there is still work to do here.

**Comment by reergymerej** [comment]
Don't forget to add the `playsinline` [prop](https://github.com/CookPete/react-player#props).
