### ISSUE TITLE
If src is MP4-file, onReady not firing :-( 

### ISSUE THREAD

**Issue by xfishernet** [CookPete/react-player#997]
If src is MP4-file, onReady not firing :-(

**Comment by CookPete** [comment]
You can see `onReady` working for mp4 files in the demo. So there must be something wrong with your implementation.

![image](https://user-images.githubusercontent.com/1926029/91152967-84d24d80-e6b7-11ea-9aca-1104c9333f40.png)

Reopen this issue with more information than just "it doesn't work" – what URL are you trying to play, what device are you using and what props are you passing in?
