### ISSUE TITLE
How to disable buffering for his video? 

### ISSUE THREAD

**Issue by xfishernet** [CookPete/react-player#998]
How to disable buffering for his video?

**Comment by crosskpixel** [comment]
try this, maybe it's enough for your need, you can find more materials for iframe manipulation at: https://developers.google.com/youtube/iframe_api_reference#stopVideo

try it:
https://codesandbox.io/s/wonderful-sanderson-zjt42?file=/src/App.js

**Comment by CookPete** [comment]
Assuming you mean `HLS` instead of `his`? I'm not sure what you're asking exactly but it sounds more suited to the `hls.js` repo: https://github.com/video-dev/hls.js/
