### ISSUE TITLE
Youtube onPause callback does not get fired

### ISSUE THREAD

**Issue by mikeycoding** [CookPete/react-player#999]
#### Current Behavior
onPause callback does not get fired

#### Expected Behavior
onPause should log to console, but I don't get any log, except the following error message:

> Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('null').

Specifiying"origin" with my local url (just a file path to index.html, no web server!) did not make any difference.

#### Steps to Reproduce
```
<ReactPlayer 
	url='https://youtu.be/jlVjbo91nKA' 
	config={{
	  youtube: {
		playerVars: { 
		  controls: 1, 
		  autoplay: 1
		}
	  }
	}}
	width='800px'
	height='460px'
	onPause={() => console.log('onPause')}
/> 
```

#### Environment
- URL attempting to play: https://youtu.be/jlVjbo91nKA
- Browser: Chromium
- Operating system: Raspberry OS

**Comment by mikeycoding** [comment]
Generally, it seems that I don't get any events working. What I'm doing wrong?

**Comment by CookPete** [comment]
Have you tried setting `origin` to `https://www.youtube.com`, which is just doing what the error is complaining about?

It seems like there are problems when using the youtube API from a local file: 
- https://stackoverflow.com/a/20504912/1250405
- https://stackoverflow.com/questions/39810233/how-to-use-youtube-iframe-player-in-localhost-html-file

**Comment by mikeycoding** [comment]
> Have you tried setting `origin` to `https://www.youtube.com`, which is just doing what the error is complaining about?
> 
> It seems like there are problems when using the youtube API from a local file:
> 
> * https://stackoverflow.com/a/20504912/1250405
> * https://stackoverflow.com/questions/39810233/how-to-use-youtube-iframe-player-in-localhost-html-file

No, I didn't try setting `origin` to `https://www.youtube.com` - obviously unnecessary, because the youtube API indeed requires a webserver. Now i run the directory with ` python -m SimpleHTTPServer ` and everything works. Thanks mate, you did a great job with this library. Cheers
